Repository blackbaud/skyux, pull requests merged in 2023-08, with the labels that each got.

#1529 test(components/action-bars): stabilize modal visual test
  apps/e2e/action-bars-storybook-e2e/src/e2e/summary-action-bar.component.cy.ts
Labels: risk level (author): 1, risk level (reviewer): 1

#1491 fix(components/lookup): set input box height to match other field types
  apps/integration-e2e/src/e2e/field-heights.cy.ts
  apps/integration-e2e/src/e2e/modal-viewkept-toolbars.cy.ts
  apps/integration-e2e/src/e2e/vertical-tabset-back-to-top.cy.ts
  apps/integration-e2e/src/e2e/viewkeeper-tabset.cy.ts
  apps/integration-e2e/src/support/commands.ts
  apps/integration/src/app/integrations/field-heights/field-heights.component.html
  apps/integration/src/app/integrations/field-heights/field-heights.component.scss
  apps/integration/src/app/integrations/field-heights/field-heights.component.spec.ts
  apps/integration/src/app/integrations/field-heights/field-heights.component.ts
  apps/integration/src/app/integrations/field-heights/field-heights.module.ts
  apps/integration/src/app/integrations/integrations.module.ts
  libs/components/forms/src/lib/modules/input-box/input-box.component.scss
  libs/components/lookup/src/lib/modules/lookup/lookup.component.scss
Labels: risk level (author): 2, risk level (reviewer): 2

#1533 build: remove next-release portion of release-please workflow to allow for initial 9 beta
  .github/workflows/release-please.yml
Labels: risk level (author): 1, risk level (reviewer): 1

#1537 fix: add support for `@skyux/dev-infra-private@9.0.0-alpha.0`
  .github/workflows/release-please.yml
  CHANGELOG.md
  package-lock.json
  package.json
Labels: risk level (author): 1, risk level (reviewer): 1

#1538 ci: add Slack notifications for issues after a merge
  .github/workflows/ci.yml
  .github/workflows/release-please.yml
Labels: risk level (author): 1, risk level (reviewer): 1

#1540 ci: update last-release-sha
  .github/workflows/release-please.yml
Labels: risk level (reviewer): 1

#1541 chore: release 9.0.0-alpha.0
  CHANGELOG.md
Labels: autorelease main: pending

#1539 ci: add Slack notifications for issues after a merge (#1538)
  .github/workflows/ci.yml
  .github/workflows/release-please.yml
Labels: risk level (author): 1, risk level (reviewer): 1

#1531 fix(components/lookup): set input box height to match other field types (#1491)
  apps/integration-e2e/src/e2e/field-heights.cy.ts
  apps/integration-e2e/src/e2e/modal-viewkept-toolbars.cy.ts
  apps/integration-e2e/src/e2e/vertical-tabset-back-to-top.cy.ts
  apps/integration-e2e/src/e2e/viewkeeper-tabset.cy.ts
  apps/integration-e2e/src/support/commands.ts
  apps/integration/src/app/integrations/field-heights/field-heights.component.html
  apps/integration/src/app/integrations/field-heights/field-heights.component.scss
  apps/integration/src/app/integrations/field-heights/field-heights.component.spec.ts
  apps/integration/src/app/integrations/field-heights/field-heights.component.ts
  apps/integration/src/app/integrations/field-heights/field-heights.module.ts
  apps/integration/src/app/integrations/integrations.module.ts
  libs/components/forms/src/lib/modules/input-box/input-box.component.scss
  libs/components/lookup/src/lib/modules/lookup/lookup.component.scss
Labels: risk level (author): 2, risk level (reviewer): 2

#1530 test(components/action-bars): stabilize modal visual test (#1529)
  apps/e2e/action-bars-storybook-e2e/src/e2e/summary-action-bar.component.cy.ts
Labels: risk level (author): 1, risk level (reviewer): 1

#1543 build: reset release-please for future 9 prereleases
  .github/workflows/release-please.yml
Labels: risk level (author): 1, risk level (reviewer): 1

#1532 feat(components/forms)!: remove source property from SkyCheckboxChange and SkyRadioChange
  libs/components/forms/src/lib/modules/checkbox/checkbox-change.ts
  libs/components/forms/src/lib/modules/checkbox/checkbox.component.spec.ts
  libs/components/forms/src/lib/modules/checkbox/checkbox.component.ts
  libs/components/forms/src/lib/modules/radio/radio.component.ts
  libs/components/forms/src/lib/modules/radio/types/radio-change.ts
Labels: risk level (author): 5, risk level (reviewer): 5

#1523 chore: release 8.7.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease 8.x.x: pending

#1546 build: bump @skyux/dev-infra-private to 9.0.0-alpha.1
  package-lock.json
  package.json
Labels: risk level (author): 1, risk level (reviewer): 1

#1545 chore: release 8.7.1 (#1523)
  CHANGELOG.md
Labels: risk level (author): 1, risk level (reviewer): 1

#1551 chore(apps/playground): add standalone modal demo
  apps/playground/src/app/components/components.module.ts
  apps/playground/src/app/components/modal/standalone/modal-opener.component.ts
  apps/playground/src/app/components/modal/standalone/modal-standalone.component.ts
Labels: risk level (author): 1, risk level (reviewer): 1

#1550 fix(components/forms): fix input/label association in input box code example
  apps/code-examples/src/app/code-examples/forms/input-box/basic/input-box-demo.component.html
Labels: risk level (author): 1, risk level (reviewer): 1

#1554 fix(components/forms): fix input/label association in input box code example (#1550)
  apps/code-examples/src/app/code-examples/forms/input-box/basic/input-box-demo.component.html
Labels: risk level (author): 1, risk level (reviewer): 1

#1547 refactor(components/forms): update default name and id for checkbox component
  libs/components/forms/src/lib/modules/checkbox/checkbox.component.spec.ts
  libs/components/forms/src/lib/modules/checkbox/checkbox.component.ts
  libs/components/forms/src/lib/modules/radio/radio.component.ts
  libs/components/forms/testing/src/checkbox/checkbox-harness.spec.ts
  libs/components/text-editor/src/lib/modules/text-editor/text-editor.component.spec.ts
Labels: risk level (author): 2, risk level (reviewer): 2

#1555 fix(components/packages): update schematic version numbers and add @skyux/popovers dependency
  libs/components/packages/src/schematics/migrations/migration-collection.json
  libs/components/packages/src/schematics/migrations/update-9/add-forms-popovers-peer-dependency/add-forms-popovers-peer-dependency.schematic.spec.ts
  libs/components/packages/src/schematics/migrations/update-9/add-forms-popovers-peer-dependency/add-forms-popovers-peer-dependency.schematic.ts
  libs/components/packages/src/schematics/rules/ensure-peers-installed.ts
Labels: risk level (author): 2, risk level (reviewer): 1

#1544 chore: release 9.0.0-alpha.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#1553 chore: release 8.7.2
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease 8.x.x: pending

#1556 chore: release 8.7.2 (#1553)
  CHANGELOG.md
Labels: risk level (author): 1, risk level (reviewer): 1

#1549 feat(components/ag-grid)!: support AG Grid 29
  apps/code-examples/src/app/code-examples/ag-grid/data-entry-grid/basic/data-entry-grid-docs-demo-edit-modal.component.ts
  apps/code-examples/src/app/code-examples/ag-grid/data-entry-grid/data-manager-added/data-manager-data-entry-grid-docs-demo-edit-modal.component.ts
  apps/code-examples/src/app/code-examples/ag-grid/data-entry-grid/inline-help/data-entry-grid-docs-demo-edit-modal.component.ts
  apps/e2e/ag-grid-storybook-e2e/src/e2e/data-manager.component.cy.ts
  apps/playground/src/app/components/ag-grid/edit-in-modal-grid/ag-grid-edit-modal.component.ts
  apps/playground/src/app/shared/data-manager/data-manager-edit-modal.component.ts
  libs/components/ag-grid/package.json
  libs/components/ag-grid/src/lib/modules/ag-grid/ag-grid-data-manager-adapter.directive.spec.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/ag-grid-data-manager-adapter.directive.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/ag-grid-row-delete.directive.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/ag-grid-wrapper.component.spec.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/ag-grid-wrapper.component.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/ag-grid.service.spec.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-editors/cell-editor-currency/cell-editor-currency.component.spec.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-editors/cell-editor-lookup/cell-editor-lookup.component.spec.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-editors/cell-editor-lookup/cell-editor-lookup.component.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-renderers/cell-renderer-row-selector/cell-renderer-row-selector.component.spec.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-renderers/cell-renderer-row-selector/cell-renderer-row-selector.component.ts
  package-lock.json
  package.json
Labels: risk level (author): 2, risk level (reviewer): 2

#1562 feat(components/packages): update ag-grid in ng update group
  libs/components/packages/package.json
Labels: risk level (author): 1, risk level (reviewer): 1

#1561 chore: release 9.0.0-alpha.2
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#1563 fix(components/modals): add support for standalone modal components
  apps/playground/src/app/home/home.component.ts
  libs/components/core/src/lib/modules/dynamic-component/dynamic-component-options.ts
  libs/components/core/src/lib/modules/dynamic-component/dynamic-component.service.spec.ts
  libs/components/core/src/lib/modules/dynamic-component/dynamic-component.service.ts
  libs/components/core/src/lib/modules/dynamic-component/fixtures/lazy-loaded-test.component.ts
  libs/components/modals/src/lib/modules/modal/modal-host.component.ts
  libs/components/tiles/src/lib/modules/tiles/tile-dashboard-column/tile-dashboard-column.component.ts
  libs/components/tiles/src/lib/modules/tiles/tile-dashboard/tile-dashboard.service.ts
  libs/components/toast/src/lib/modules/toast/toast.service.spec.ts
  libs/components/toast/src/lib/modules/toast/toast.service.ts
Labels: risk level (author): 3, risk level (reviewer): 3

#1565 chore: release 9.0.0-alpha.3
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#1566 test(sdk/eslint-config): update test config
  libs/sdk/eslint-config/jest.config.ts
  libs/sdk/eslint-config/src/test-setup.ts
Labels: risk level (author): 1, risk level (reviewer): 1

#1569 test(sdk/eslint-config): update test mock
  libs/sdk/eslint-config/jest.config.ts
  libs/sdk/eslint-config/src/schematics/ng-add/ng-add.schematic.spec.ts
  libs/sdk/eslint-config/src/test-setup.ts
Labels: risk level (author): 1, risk level (reviewer): 1

#1570 test(sdk/eslint-config): update test mock (#1569)
  libs/sdk/eslint-config/jest.config.ts
  libs/sdk/eslint-config/src/schematics/ng-add/ng-add.schematic.spec.ts
  libs/sdk/eslint-config/src/test-setup.ts
Labels: risk level (author): 1, risk level (reviewer): 1

#1568 fix(components/i18n)!: move SkyLibResourcesService to SkyI18nModule providers
  libs/components/i18n/src/lib/modules/i18n/i18n.module.ts
  libs/components/i18n/src/lib/modules/i18n/lib-resources.service.ts
Labels: risk level (author): 2, risk level (reviewer): 4

#1557 ci: reduce the scope for e2e workflow
  .github/workflows/ci.yml
  .github/workflows/e2e.yml
  nx.json
  package-lock.json
  package.json
Labels: risk level (author): 1, risk level (reviewer): 2

#1571 chore: release 9.0.0-alpha.4
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#1558 ci: reduce the scope for e2e workflow
  .github/workflows/ci.yml
  .github/workflows/e2e.yml
  nx.json
  package-lock.json
  package.json
Labels: risk level (author): 1, risk level (reviewer): 1

#1572 ci: add `skip e2e` option
  .github/workflows/e2e.yml
Labels: risk level (author): 1, risk level (reviewer): 2, skip e2e

#1573 feat(components/a11y)!: move SkySkipLinkService to SkySkipLinkModule module providers
  libs/components/a11y/src/lib/modules/skip-link/skip-link.module.ts
  libs/components/a11y/src/lib/modules/skip-link/skip-link.service.ts
Labels: risk level (author): 2, risk level (reviewer): 5

#1574 ci: add `skip e2e` option (#1572)
  .github/workflows/e2e.yml
Labels: risk level (author): 1, risk level (reviewer): 1

#1576 feat(components/ag-grid)!: move `SkyAgGridService` to `SkyAgGridModule` providers
  libs/components/ag-grid/src/lib/modules/ag-grid/ag-grid-adapter.service.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/ag-grid.module.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/ag-grid.service.ts
Labels: risk level (author): 5, risk level (reviewer): 2

#1577 fix(components/split-view): clarify split-view footer uses and remove the workspace header from the public documentation
  apps/e2e/action-bars-storybook/src/app/summary-action-bar/summary-action-bar.component.html
  apps/e2e/split-view-storybook/src/app/split-view/split-view.component.html
  libs/components/split-view/src/lib/modules/split-view/split-view-workspace-footer.component.ts
  libs/components/split-view/src/lib/modules/split-view/split-view-workspace-header.component.ts
Labels: risk level (author): 1, risk level (reviewer): 2

#1590 feat(components/pages): make page component a responsive container (#1552)
  apps/code-examples/src/app/code-examples/pages/page/record-page-blocks-layout-demo/record-page-blocks-layout-demo.component.scss
  libs/components/core/src/lib/modules/resize-observer/resize-observer-media-query.service.spec.ts
  libs/components/core/src/lib/modules/resize-observer/resize-observer-media-query.service.ts
  libs/components/core/testing/src/public-api.ts
  libs/components/core/testing/src/resize-observer-mock.ts
  libs/components/modals/src/lib/modules/modal/modal-host.component.ts
  libs/components/pages/src/lib/modules/page-header/fixtures/page-header-fixtures.component.html
  libs/components/pages/src/lib/modules/page-header/fixtures/page-header-fixtures.component.ts
  libs/components/pages/src/lib/modules/page-header/page-header.component.spec.ts
  libs/components/pages/src/lib/modules/page-header/page-header.component.ts
  libs/components/pages/src/lib/modules/page/page-content.component.spec.ts
  libs/components/pages/src/lib/modules/page/page-content.component.ts
  libs/components/pages/src/lib/modules/page/page.component.ts
  libs/components/tabs/src/lib/modules/tabs/tab.component.html
  libs/components/tabs/src/lib/modules/tabs/tab.component.ts
  libs/components/tabs/src/lib/modules/tabs/tabset.component.spec.ts
Labels: risk level (author): 2, risk level (reviewer): 3

#1588 chore: release 8.8.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease 8.x.x: pending

#1595 chore: remove unused country field code
  libs/components/lookup/src/lib/modules/country-field/country-field.component.spec.ts
  libs/components/lookup/src/lib/modules/country-field/country-field.component.ts
Labels: risk level (author): 2, risk level (reviewer): 2

#1594 chore: release 8.8.0 (#1588)
  CHANGELOG.md
Labels: risk level (author): 1, risk level (reviewer): 1

#1596 chore: remove unused country field code (#1595)
  libs/components/lookup/src/lib/modules/country-field/country-field.component.spec.ts
  libs/components/lookup/src/lib/modules/country-field/country-field.component.ts
Labels: risk level (author): 2, risk level (reviewer): 2

#1586 fix(components/ag-grid): set environment injector when creating the header
  libs/components/ag-grid/src/lib/modules/ag-grid/header/header-group.component.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/header/header.component.ts
Labels: risk level (author): 1, risk level (reviewer): 1

#1589 fix(components/lookup)!: move `SkySelectionModalService` to `SkySelectionModalModule` providers
  libs/components/lookup/src/lib/modules/selection-modal/selection-modal.module.ts
  libs/components/lookup/src/lib/modules/selection-modal/selection-modal.service.spec.ts
  libs/components/lookup/src/lib/modules/selection-modal/selection-modal.service.ts
Labels: risk level (author): 5, risk level (reviewer): 5

#1585 fix(components/indicators)!: move `SkyWaitService` to `SkyWaitModule` providers
  libs/components/indicators/src/lib/modules/wait/wait.module.ts
  libs/components/indicators/src/lib/modules/wait/wait.service.ts
Labels: risk level (author): 5, risk level (reviewer): 5

#1584 fix(components/core)!: move `SkyNumericService` to `SkyNumericModule` providers
  libs/components/core/src/lib/modules/numeric/numeric.module.ts
  libs/components/core/src/lib/modules/numeric/numeric.service.ts
Labels: risk level (author): 5, risk level (reviewer): 5

#1581 fix(components/toast)!: move `SkyToastService` to `SkyToastModule` providers
  apps/integration/src/app/integrations/toast/toast.component.spec.ts
  libs/components/toast/src/lib/modules/toast/toast.module.ts
  libs/components/toast/src/lib/modules/toast/toast.service.ts
Labels: risk level (author): 5, risk level (reviewer): 5

#1591 fix(components/modals): use environment injector when creating a modal component
  apps/code-examples/src/app/code-examples/modals/modal/modal-demo.module.ts
  apps/playground/src/app/components/modal/modal-demo.component.ts
  apps/playground/src/app/components/modal/modal-form-demo.component.ts
  apps/playground/src/app/components/modal/modal-full-page-demo.component.ts
  apps/playground/src/app/components/modal/modal-tiled-demo.component.ts
  libs/components/errors/src/lib/modules/error/error-modal.service.spec.ts
  libs/components/modals/src/lib/modules/modal/modal-configuration.ts
  libs/components/modals/src/lib/modules/modal/modal.service.spec.ts
  libs/components/modals/src/lib/modules/modal/modal.service.ts
Labels: risk level (author): 2, risk level (reviewer): 2

#1582 refactor: move `SkyDockService` to `SkyDockModule` providers
  libs/components/core/src/lib/modules/dock/dock.component.ts
  libs/components/core/src/lib/modules/dock/dock.module.ts
  libs/components/core/src/lib/modules/dock/dock.service.ts
Labels: risk level (author): 2, risk level (reviewer): 2

#1579 refactor: remove redundant import of `SkyI18nModule`
  libs/components/a11y/src/lib/modules/skip-link/skip-link.module.ts
  libs/components/action-bars/src/lib/modules/summary-action-bar/summary-action-bar.module.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/ag-grid.module.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-editors/cell-editor-lookup/cell-editor-lookup.module.ts
  libs/components/avatar/src/lib/modules/avatar/avatar.module.ts
  libs/components/colorpicker/src/lib/modules/colorpicker/colorpicker.module.ts
  libs/components/core/src/lib/modules/numeric/numeric.module.ts
  libs/components/datetime/src/lib/modules/date-range-picker/date-range-picker.module.ts
  libs/components/datetime/src/lib/modules/datepicker/datepicker.module.ts
  libs/components/datetime/src/lib/modules/timepicker/timepicker.module.ts
  libs/components/flyout/src/lib/modules/flyout/flyout.module.ts
  libs/components/forms/src/lib/modules/character-counter/character-counter.module.ts
  libs/components/forms/src/lib/modules/file-attachment/file-attachments.module.ts
  libs/components/indicators/src/lib/modules/alert/alert.module.ts
  libs/components/indicators/src/lib/modules/chevron/chevron.module.ts
  libs/components/indicators/src/lib/modules/help-inline/help-inline.module.ts
  libs/components/indicators/src/lib/modules/label/label.module.ts
  libs/components/indicators/src/lib/modules/status-indicator/status-indicator.module.ts
  libs/components/indicators/src/lib/modules/tokens/tokens.module.ts
  libs/components/indicators/src/lib/modules/wait/wait.module.ts
  libs/components/layout/src/lib/modules/back-to-top/back-to-top.module.ts
  libs/components/layout/src/lib/modules/card/card.module.ts
  libs/components/layout/src/lib/modules/definition-list/definition-list.module.ts
  libs/components/layout/src/lib/modules/description-list/description-list.module.ts
  libs/components/layout/src/lib/modules/inline-delete/inline-delete.module.ts
  libs/components/layout/src/lib/modules/text-expand-repeater/text-expand-repeater.module.ts
  libs/components/layout/src/lib/modules/text-expand/text-expand.module.ts
  libs/components/list-builder-view-grids/src/lib/modules/column-selector/column-selector-modal.module.ts
  libs/components/list-builder-view-grids/src/lib/modules/list-column-selector-action/list-column-selector-action.module.ts
  libs/components/list-builder/src/lib/modules/list-toolbar/list-secondary-actions/list-secondary-actions.module.ts
  libs/components/list-builder/src/lib/modules/list-toolbar/list-toolbar.module.ts
  libs/components/lookup/src/lib/modules/country-field/country-field.module.ts
  libs/components/lookup/src/lib/modules/lookup/lookup.module.ts
  libs/components/lookup/src/lib/modules/selection-modal/selection-modal.module.ts
  libs/components/pages/src/lib/modules/action-hub/action-hub.module.ts
  libs/components/pages/src/lib/modules/link-list/link-list.module.ts
  libs/components/pages/src/lib/modules/modal-link-list/modal-link-list.module.ts
  libs/components/pages/src/lib/modules/needs-attention/needs-attention.module.ts
  libs/components/phone-field/src/lib/modules/phone-field/phone-field.module.ts
  libs/components/progress-indicator/src/lib/modules/progress-indicator/progress-indicator.module.ts
  libs/components/select-field/src/lib/modules/select-field/select-field.module.ts
  libs/components/tabs/src/lib/modules/tabs/tabs.module.ts
  libs/components/text-editor/src/lib/modules/text-editor/text-editor.module.ts
  libs/components/tiles/src/lib/modules/tiles/tile/tile.module.ts
  libs/components/toast/src/lib/modules/toast/toast.module.ts
Labels: risk level (author): 2, risk level (reviewer): 2

#1548 fix(components/ag-grid): call stop editing callback in popup editors
  apps/playground/src/app/components/ag-grid/edit-stop-when-loses-focus/edit-stop-when-loses-focus.component.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/ag-grid-wrapper.component.spec.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/ag-grid.service.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-editors/cell-editor-autocomplete/cell-editor-autocomplete.component.html
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-editors/cell-editor-autocomplete/cell-editor-autocomplete.component.spec.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-editors/cell-editor-autocomplete/cell-editor-autocomplete.component.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-editors/cell-editor-datepicker/cell-editor-datepicker.component.html
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-editors/cell-editor-datepicker/cell-editor-datepicker.component.spec.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-editors/cell-editor-datepicker/cell-editor-datepicker.component.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-editors/cell-editor-lookup/cell-editor-lookup.component.html
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-editors/cell-editor-lookup/cell-editor-lookup.component.spec.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-editors/cell-editor-lookup/cell-editor-lookup.component.ts
  libs/components/datetime/src/lib/modules/datepicker/datepicker.component.ts
  libs/components/lookup/src/lib/modules/autocomplete/autocomplete.component.ts
  libs/components/lookup/src/lib/modules/lookup/lookup.component.html
  libs/components/lookup/src/lib/modules/lookup/lookup.component.ts
Labels: risk level (author): 2, risk level (reviewer): 2

#1597 chore: release 8.8.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease 8.x.x: pending

#1599 chore: release 8.8.1 (#1597)
  CHANGELOG.md
Labels: risk level (author): 1, risk level (reviewer): 1

#1592 refactor(components/core): make environment injector required when creating dynamic components
  apps/code-examples/src/app/features/progress-indicator.module.ts
  libs/components/a11y/src/lib/modules/skip-link/skip-link.service.ts
  libs/components/core/src/lib/modules/dynamic-component/dynamic-component-options.ts
  libs/components/core/src/lib/modules/dynamic-component/dynamic-component.service.spec.ts
  libs/components/core/src/lib/modules/dynamic-component/dynamic-component.service.ts
  libs/components/core/src/lib/modules/live-announcer/live-announcer.service.ts
  libs/components/core/src/lib/modules/overlay/overlay.service.ts
  libs/components/core/src/lib/modules/resize-observer/resize-observer.service.ts
Labels: risk level (author): 2, risk level (reviewer): 2

#1600 fix(components/ag-grid): update documentation generation
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-editors/cell-editor-autocomplete/cell-editor-autocomplete.component.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-editors/cell-editor-datepicker/cell-editor-datepicker.component.ts
Labels: risk level (author): 1, risk level (reviewer): 1

#1601 feat(sdk/eslint-config): use typescript-eslint version of no-use-before-define
  libs/sdk/eslint-config/recommended.json
Labels: risk level (author): 1, risk level (reviewer): 1

#1603 chore: release 8.8.1 (#1602)
  CHANGELOG.md
Labels: risk level (author): 1, risk level (reviewer): 1

#1605 fix(components/ag-grid): call stop editing callback in popup editors (#1548)
  apps/playground/src/app/components/ag-grid/edit-stop-when-loses-focus/edit-stop-when-loses-focus.component.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/ag-grid-wrapper.component.spec.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/ag-grid.service.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-editors/cell-editor-autocomplete/cell-editor-autocomplete.component.html
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-editors/cell-editor-autocomplete/cell-editor-autocomplete.component.spec.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-editors/cell-editor-autocomplete/cell-editor-autocomplete.component.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-editors/cell-editor-datepicker/cell-editor-datepicker.component.html
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-editors/cell-editor-datepicker/cell-editor-datepicker.component.spec.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-editors/cell-editor-datepicker/cell-editor-datepicker.component.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-editors/cell-editor-lookup/cell-editor-lookup.component.html
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-editors/cell-editor-lookup/cell-editor-lookup.component.spec.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-editors/cell-editor-lookup/cell-editor-lookup.component.ts
  libs/components/datetime/src/lib/modules/datepicker/datepicker.component.ts
  libs/components/lookup/src/lib/modules/autocomplete/autocomplete.component.ts
  libs/components/lookup/src/lib/modules/lookup/lookup.component.html
  libs/components/lookup/src/lib/modules/lookup/lookup.component.ts
Labels: risk level (author): 2, risk level (reviewer): 2

#1575 chore: release 9.0.0-alpha.5
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#1606 ci: update dev-infra to 9.0.0-alpha.5
  package-lock.json
  package.json
Labels: risk level (author): 1, risk level (reviewer): 1

#1607 feat(sdk/testing): support axe-core 4.7 (#1494)
  libs/components/ag-grid/src/lib/modules/ag-grid/ag-grid-wrapper.component.spec.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-editors/cell-editor-lookup/cell-editor-lookup.component.html
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-editors/cell-editor-lookup/cell-editor-lookup.component.spec.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-editors/cell-editor-lookup/cell-editor-lookup.component.ts
  libs/components/lookup/src/lib/modules/autocomplete/autocomplete-input.directive.ts
  libs/components/lookup/src/lib/modules/autocomplete/autocomplete.component.html
  libs/components/lookup/src/lib/modules/autocomplete/autocomplete.component.spec.ts
  libs/components/lookup/src/lib/modules/autocomplete/autocomplete.component.ts
  libs/components/lookup/src/lib/modules/lookup/lookup.component.html
  libs/components/lookup/src/lib/modules/lookup/lookup.component.spec.ts
  libs/components/lookup/src/lib/modules/lookup/lookup.component.ts
  libs/components/lookup/testing/src/autocomplete/autocomplete-harness.ts
  libs/components/lookup/testing/src/autocomplete/autocomplete-input-harness.ts
  libs/sdk/testing/src/lib/a11y/a11y-analyzer.spec.ts
  libs/sdk/testing/src/lib/a11y/a11y-analyzer.ts
Labels: risk level (author): 2, risk level (reviewer): 3

#1593 feat(components/ag-grid): provide schematic for AG Grid 29 changes
  libs/components/packages/src/schematics/migrations/migration-collection.json
  libs/components/packages/src/schematics/migrations/update-9/ag-grid-29/ag-grid-29.schematic.spec.ts
  libs/components/packages/src/schematics/migrations/update-9/ag-grid-29/ag-grid-29.schematic.ts
Labels: risk level (author): 3, risk level (reviewer): 3

#1610 chore: release 8.9.0 (#1608)
  CHANGELOG.md
Labels: risk level (author): 1, risk level (reviewer): 1

#1613 fix(components/split-view): use correct spacing class in examples
  apps/code-examples/src/app/code-examples/pages/page/split-view-page-fit-layout-demo/split-view-page-content.component.html
  apps/e2e/pages-storybook/src/app/page/layouts/fit-page/fit-page.component.html
  apps/playground/src/app/components/pages/layouts/shared/split-view-content/split-view-content.component.html
  apps/playground/src/app/components/split-view/split-view/basic/split-view.component.html
  libs/components/split-view/testing/src/split-view/fixtures/split-view-fixture-test.component.html
Labels: risk level (author): 1, risk level (reviewer): 1

#1615 fix(components/modals): use optional injector for `SkyModalConfiguration`
  libs/components/modals/src/lib/modules/modal/modal.component.spec.ts
  libs/components/modals/src/lib/modules/modal/modal.component.ts
Labels: risk level (author): 2, risk level (reviewer): 1

#1616 chore: update dev-infra to 9.0.0-alpha 6
  package-lock.json
  package.json
Labels: risk level (author): 1, risk level (reviewer): 1

#1609 chore: release 9.0.0-alpha.6
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#1619 feat: update `intl-tel-input` and `google-libphonenumber` dependencies
  apps/e2e/action-bars-storybook/project.json
  apps/e2e/avatar-storybook/project.json
  apps/e2e/colorpicker-storybook/project.json
  apps/e2e/datetime-storybook/project.json
  apps/e2e/errors-storybook/project.json
  apps/e2e/forms-storybook/project.json
  apps/e2e/lists-storybook/project.json
  apps/e2e/lookup-storybook/project.json
  apps/e2e/phone-field-storybook/project.json
  apps/e2e/tabs-storybook/project.json
  libs/components/colorpicker/src/lib/modules/colorpicker/colorpicker.component.scss
  libs/components/errors/src/lib/modules/error/error.component.scss
  libs/components/lookup/package.json
  libs/components/lookup/src/lib/modules/country-field/country-field.component.scss
  libs/components/phone-field/package.json
  libs/components/phone-field/src/lib/modules/phone-field/phone-field.component.scss
  package-lock.json
  package.json
Labels: risk level (author): 2, risk level (reviewer): 2

#1620 feat: update `autonumeric`, `dompurify`, `tslib`, and `validator` dependencies
  libs/components/a11y/package.json
  libs/components/action-bars/package.json
  libs/components/ag-grid/package.json
  libs/components/angular-tree-component/package.json
  libs/components/animations/package.json
  libs/components/assets/package.json
  libs/components/autonumeric/package.json
  libs/components/avatar/package.json
  libs/components/colorpicker/package.json
  libs/components/config/package.json
  libs/components/core/package.json
  libs/components/data-manager/package.json
  libs/components/datetime/package.json
  libs/components/errors/package.json
  libs/components/flyout/package.json
  libs/components/forms/package.json
  libs/components/forms/src/lib/modules/checkbox/checkbox.component.spec.ts
  libs/components/grids/package.json
  libs/components/http/package.json
  libs/components/i18n/package.json
  libs/components/indicators/package.json
  libs/components/inline-form/package.json
  libs/components/layout/package.json
  libs/components/list-builder-common/package.json
  libs/components/list-builder-view-checklist/package.json
  libs/components/list-builder-view-grids/package.json
  libs/components/list-builder/package.json
  libs/components/lists/package.json
  libs/components/lookup/package.json
  libs/components/modals/package.json
  libs/components/navbar/package.json
  libs/components/omnibar-interop/package.json
  libs/components/packages/package.json
  libs/components/pages/package.json
  libs/components/phone-field/package.json
  libs/components/popovers/package.json
  libs/components/progress-indicator/package.json
  libs/components/router/package.json
  libs/components/select-field/package.json
  libs/components/split-view/package.json
  libs/components/storybook/package.json
  libs/components/tabs/package.json
  libs/components/text-editor/package.json
  libs/components/theme/package.json
  libs/components/tiles/package.json
  libs/components/toast/package.json
  libs/components/validation/package.json
  libs/sdk/testing/package.json
  package-lock.json
  package.json
Labels: risk level (author): 2, risk level (reviewer): 2

#1598 docs: fix get-started link
  CONTRIBUTING.md
Labels: risk level (author): 1, risk level (reviewer): 1

#1604 feat(sdk/eslint-config): use typescript-eslint version of no-use-before-define (#1601)
  libs/sdk/eslint-config/recommended.json
Labels: risk level (author): 2, risk level (reviewer): 1

#1622 feat(components/lookup): add ability to set `aria-label` and `aria-labelledby` attributes on the search component
  apps/code-examples/src/app/code-examples/lookup/search/basic/search-demo.component.html
  apps/code-examples/src/app/code-examples/lookup/search/basic/search-demo.component.ts
  libs/components/lookup/src/lib/modules/search/fixtures/search.component.fixture.html
  libs/components/lookup/src/lib/modules/search/fixtures/search.component.fixture.ts
  libs/components/lookup/src/lib/modules/search/search.component.html
  libs/components/lookup/src/lib/modules/search/search.component.spec.ts
  libs/components/lookup/src/lib/modules/search/search.component.ts
  libs/components/lookup/testing/src/search/fixtures/search-harness-test.component.html
  libs/components/lookup/testing/src/search/fixtures/search-harness-test.component.ts
  libs/components/lookup/testing/src/search/search-harness.spec.ts
  libs/components/lookup/testing/src/search/search-harness.ts
Labels: risk level (author): 1, risk level (reviewer): 1

#1624 feat(components/lookup): add ability to set `aria-label` and `aria-labelledby` attributes on the search component (#1622)
  apps/code-examples/src/app/code-examples/lookup/search/basic/search-demo.component.html
  apps/code-examples/src/app/code-examples/lookup/search/basic/search-demo.component.ts
  libs/components/lookup/src/lib/modules/search/fixtures/search.component.fixture.html
  libs/components/lookup/src/lib/modules/search/fixtures/search.component.fixture.ts
  libs/components/lookup/src/lib/modules/search/search.component.html
  libs/components/lookup/src/lib/modules/search/search.component.spec.ts
  libs/components/lookup/src/lib/modules/search/search.component.ts
  libs/components/lookup/testing/src/search/fixtures/search-harness-test.component.html
  libs/components/lookup/testing/src/search/fixtures/search-harness-test.component.ts
  libs/components/lookup/testing/src/search/search-harness.spec.ts
  libs/components/lookup/testing/src/search/search-harness.ts
Labels: risk level (author): 1, risk level (reviewer): 1

#1621 revert: move services from module providers to `providedIn: 'any'`
  libs/components/a11y/src/lib/modules/skip-link/skip-link.module.ts
  libs/components/a11y/src/lib/modules/skip-link/skip-link.service.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/ag-grid.module.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/ag-grid.service.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/header/header-group.component.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/header/header.component.ts
  libs/components/core/src/lib/modules/dock/dock.component.ts
  libs/components/core/src/lib/modules/dock/dock.module.ts
  libs/components/core/src/lib/modules/dock/dock.service.ts
  libs/components/core/src/lib/modules/dynamic-component/dynamic-component-options.ts
  libs/components/core/src/lib/modules/dynamic-component/dynamic-component.service.ts
  libs/components/core/src/lib/modules/numeric/numeric.module.ts
  libs/components/core/src/lib/modules/numeric/numeric.service.ts
  libs/components/flyout/src/lib/modules/flyout/flyout.module.ts
  libs/components/flyout/src/lib/modules/flyout/flyout.service.ts
  libs/components/i18n/src/lib/modules/i18n/i18n.module.ts
  libs/components/i18n/src/lib/modules/i18n/lib-resources.service.ts
  libs/components/indicators/src/lib/modules/wait/wait.module.ts
  libs/components/indicators/src/lib/modules/wait/wait.service.ts
  libs/components/lookup/src/lib/modules/selection-modal/selection-modal.module.ts
  libs/components/lookup/src/lib/modules/selection-modal/selection-modal.service.ts
  libs/components/modals/src/lib/modules/modal/modal.service.ts
  libs/components/toast/src/lib/modules/toast/toast.module.ts
  libs/components/toast/src/lib/modules/toast/toast.service.ts
Labels: risk level (author): 2, risk level (reviewer): 2

#1627 ci: fix e2e workflow nx affected environment variables
  .github/workflows/e2e.yml
Labels: risk level (author): 1, risk level (reviewer): 1

#1629 ci: fix e2e workflow nx affected environment variables (#1627)
  .github/workflows/e2e.yml
Labels: risk level (author): 1, risk level (reviewer): 1, skip e2e

#1617 chore: release 9.0.0-alpha.7
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#1631 chore: fix pages e2e
  apps/e2e/pages-storybook-e2e/src/e2e/page-layout-blocks.component.cy.ts
Labels: risk level (author): 1, risk level (reviewer): 1

#1632 chore: fix pages e2e (#1631)
  apps/e2e/pages-storybook-e2e/src/e2e/page-layout-blocks.component.cy.ts
Labels: risk level (author): 1, risk level (reviewer): 1

#1633 build: bump @skyux/dev-infra-private to 9.0.0-alpha.7
  package-lock.json
  package.json
Labels: risk level (author): 1, risk level (reviewer): 1, skip e2e

#1628 fix(components/tabs): vertical tab modern theme spacing has been updated to match design specifications
  libs/components/tabs/src/lib/modules/vertical-tabset/vertical-tab.component.scss
  libs/components/tabs/src/lib/modules/vertical-tabset/vertical-tabset-group.component.scss
Labels: risk level (author): 5, risk level (reviewer): 5

#1618 fix(components/lists): repeater item spacing in split view
  apps/code-examples/src/app/code-examples/split-view/split-view/basic/split-view-demo.component.html
  libs/components/lists/src/lib/modules/repeater/repeater-item.component.scss
Labels: risk level (author): 1, risk level (reviewer): 1

#1636 fix(components/tabs): remove responsive container behavior from tabs
  apps/code-examples/src/app/code-examples/pages/page/list-page-list-layout-demo/list-page-list-layout-demo.component.spec.ts
  apps/code-examples/src/app/code-examples/pages/page/list-page-tabs-layout-demo/list-page-tabs-layout-demo.component.spec.ts
  apps/code-examples/src/app/code-examples/pages/page/record-page-blocks-layout-demo/record-page-blocks-layout-demo.component.scss
  apps/code-examples/src/app/code-examples/pages/page/record-page-blocks-layout-demo/record-page-blocks-layout-demo.component.spec.ts
  apps/code-examples/src/app/code-examples/pages/page/record-page-tabs-layout-demo/record-page-tabs-layout-demo.component.spec.ts
  apps/code-examples/src/app/code-examples/pages/page/split-view-page-fit-layout-demo/split-view-page-fit-layout-demo.component.spec.ts
  libs/components/tabs/src/lib/modules/tabs/tab.component.ts
Labels: risk level (author): 1, risk level (reviewer): 1

#1623 chore: release 8.10.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease 8.x.x: pending

#1638 chore: release 8.10.0 (#1623)
  CHANGELOG.md
Labels: risk level (author): 1, risk level (reviewer): 1

#1564 feat(components/forms): remove bottom margin for input box
  apps/code-examples/src/app/code-examples/colorpicker/colorpicker/basic/colorpicker-demo.component.html
  apps/code-examples/src/app/code-examples/datetime/date-range-picker/basic/date-range-picker-demo.component.html
  apps/code-examples/src/app/code-examples/forms/character-count/character-count-demo.component.html
  apps/code-examples/src/app/code-examples/indicators/text-highlight/basic/text-highlight-demo.component.html
  apps/code-examples/src/app/code-examples/inline-form/inline-form/basic/inline-form-demo.component.html
  apps/code-examples/src/app/code-examples/inline-form/inline-form/custom-buttons/inline-form-demo.component.html
  apps/code-examples/src/app/code-examples/lookup/autocomplete/advanced/autocomplete-demo.component.html
  apps/code-examples/src/app/code-examples/lookup/autocomplete/basic/autocomplete-demo.component.html
  apps/code-examples/src/app/code-examples/lookup/autocomplete/custom-search/autocomplete-demo.component.html
  apps/code-examples/src/app/code-examples/lookup/autocomplete/search-filters/autocomplete-demo.component.html
  apps/code-examples/src/app/code-examples/lookup/lookup/add-item/lookup-async-demo.component.html
  apps/code-examples/src/app/code-examples/lookup/lookup/async/lookup-async-demo.component.html
  apps/code-examples/src/app/code-examples/lookup/lookup/custom-picker/lookup-custom-picker-demo.component.html
  apps/code-examples/src/app/code-examples/lookup/lookup/multi-select/lookup-multiple-demo.component.html
  apps/code-examples/src/app/code-examples/lookup/lookup/result-templates/lookup-result-templates-demo.component.html
  apps/code-examples/src/app/code-examples/lookup/lookup/single-select/lookup-single-demo.component.html
  apps/code-examples/src/app/code-examples/pages/action-hub/settings-modal.component.html
  apps/code-examples/src/app/code-examples/pages/page/split-view-page-fit-layout-demo/split-view-page-content.component.html
  apps/code-examples/src/app/code-examples/validation/email-validation/control-validator/email-validation-demo.component.html
  apps/code-examples/src/app/code-examples/validation/email-validation/directive/email-validation-demo.component.html
  apps/code-examples/src/app/code-examples/validation/url-validation/control-validator/url-validation-demo.component.html
  apps/code-examples/src/app/code-examples/validation/url-validation/directive/url-validation-demo.component.html
  apps/e2e/datetime-storybook/src/app/date-range-picker/date-range-picker.component.html
  apps/e2e/datetime-storybook/src/app/timepicker/timepicker.component.html
  apps/e2e/forms-storybook/src/app/character-counter/character-counter.component.html
  apps/e2e/forms-storybook/src/app/input-box/input-box.component.html
  apps/e2e/lists-storybook/src/app/filter/filter.component.html
  apps/e2e/lookup-storybook/src/app/lookup/lookup.component.html
  apps/e2e/pages-storybook/src/app/page/layouts/fit-page/fit-page.component.html
  apps/e2e/phone-field-storybook-e2e/cypress.config.ts
  apps/e2e/phone-field-storybook-e2e/src/e2e/phone-field.component.cy.ts
  apps/e2e/phone-field-storybook-e2e/src/support/commands.ts
  apps/e2e/phone-field-storybook/src/app/phone-field/phone-field.component.html
  apps/e2e/tabs-storybook/src/app/wizard/wizard-modal.component.html
  apps/integration/src/app/integrations/field-heights/field-heights.component.html
  apps/playground/src/app/components/forms/input-box/input-box.component.html
  libs/components/datetime/src/lib/modules/date-range-picker/date-range-picker.component.html
  libs/components/forms/src/lib/modules/file-attachment/file-drop.component.html
  libs/components/lookup/src/lib/modules/search/search.component.scss
  libs/components/packages/src/schematics/migrations/migration-collection.json
  libs/components/packages/src/schematics/migrations/update-9/add-compat-stylesheets/__snapshots__/add-compat-stylesheet.schematic.spec.ts.snap
  libs/components/packages/src/schematics/migrations/update-9/add-compat-stylesheets/add-compat-stylesheet.schematic.spec.ts
  libs/components/packages/src/schematics/migrations/update-9/add-compat-stylesheets/add-compat-stylesheet.schematic.ts
  libs/components/text-editor/src/lib/modules/text-editor/url-modal/text-editor-url-modal.component.html
  libs/components/theme/src/lib/styles/_forms.scss
Labels: risk level (author): 3, risk level (reviewer): 3

#1625 fix(components/forms): update file attachment accessibility and visual labels on the input for linking to a file to be more descriptive
  libs/components/forms/src/assets/locales/resources_en_US.json
  libs/components/forms/src/lib/modules/file-attachment/file-drop.component.html
  libs/components/forms/src/lib/modules/file-attachment/file-drop.component.spec.ts
  libs/components/forms/src/lib/modules/file-attachment/file-drop.component.ts
  libs/components/forms/src/lib/modules/shared/sky-forms-resources.module.ts
Labels: risk level (author): 1, risk level (reviewer): 1

#1647 fix(components/forms): update file attachment accessibility and visual labels on the input for linking to a file to be more descriptive (#1625)
  libs/components/forms/src/assets/locales/resources_en_US.json
  libs/components/forms/src/lib/modules/file-attachment/file-drop.component.html
  libs/components/forms/src/lib/modules/file-attachment/file-drop.component.spec.ts
  libs/components/forms/src/lib/modules/file-attachment/file-drop.component.ts
  libs/components/forms/src/lib/modules/shared/sky-forms-resources.module.ts
Labels: risk level (author): 1, risk level (reviewer): 1

#1643 feat(components/phone-field)!: phone field hardcoded `aria-label` is removed and the label should now be provided through a wrapping input box
  libs/components/phone-field/src/assets/locales/resources_en_US.json
  libs/components/phone-field/src/lib/modules/phone-field/phone-field-adapter.service.ts
  libs/components/phone-field/src/lib/modules/phone-field/phone-field-input.directive.ts
  libs/components/phone-field/src/lib/modules/shared/sky-phone-field-resources.module.ts
Labels: risk level (author): 5, risk level (reviewer): 5

#1646 feat(components/datetime)!: datepicker hardcoded `aria-label` is removed and the label should now be provided through a wrapping input box
  libs/components/datetime/src/assets/locales/resources_en_US.json
  libs/components/datetime/src/lib/modules/datepicker/datepicker-input-fuzzy.directive.ts
  libs/components/datetime/src/lib/modules/datepicker/datepicker-input.directive.ts
  libs/components/datetime/src/lib/modules/datepicker/datepicker.component.spec.ts
  libs/components/datetime/src/lib/modules/datepicker/fixtures/datepicker-input-box.component.fixture.html
  libs/components/datetime/src/lib/modules/datepicker/fixtures/fuzzy-datepicker.component.fixture.html
  libs/components/datetime/src/lib/modules/datepicker/fixtures/fuzzy-datepicker.component.fixture.ts
  libs/components/datetime/src/lib/modules/datepicker/fuzzy-datepicker.component.spec.ts
  libs/components/datetime/src/lib/modules/shared/sky-datetime-resources.module.ts
Labels: risk level (author): 5, risk level (reviewer): 5

#1644 feat(components/datetime)!: timepicker hardcoded `aria-label` is removed and the label should now be provided through a wrapping input box
  libs/components/datetime/src/assets/locales/resources_en_US.json
  libs/components/datetime/src/lib/modules/shared/sky-datetime-resources.module.ts
  libs/components/datetime/src/lib/modules/timepicker/fixtures/timepicker-component.fixture.html
  libs/components/datetime/src/lib/modules/timepicker/fixtures/timepicker-input-box-component.fixture.html
  libs/components/datetime/src/lib/modules/timepicker/timepicker.component.spec.ts
  libs/components/datetime/src/lib/modules/timepicker/timepicker.directive.ts
Labels: risk level (author): 5, risk level (reviewer): 5

#1630 fix(components/forms): updated single file attachment to use more descriptive aria labels
  apps/code-examples/src/app/code-examples/forms/single-file-attachment/basic/single-file-attachment-demo.component.html
  apps/code-examples/src/app/code-examples/forms/single-file-attachment/inline-help/single-file-attachment-demo.component.html
  apps/playground/src/app/components/forms/single-file-attachment/single-file-attachment.component.html
  libs/components/forms/src/assets/locales/resources_en_US.json
  libs/components/forms/src/lib/modules/file-attachment/file-attachment-label.component.html
  libs/components/forms/src/lib/modules/file-attachment/file-attachment-label.component.ts
  libs/components/forms/src/lib/modules/file-attachment/file-attachment.component.html
  libs/components/forms/src/lib/modules/file-attachment/file-attachments.module.ts
  libs/components/forms/src/lib/modules/shared/sky-forms-resources.module.ts
Labels: risk level (author): 1, risk level (reviewer): 1

#1651 fix(components/forms): updated single file attachment to use more descriptive aria labels (#1630)
  apps/code-examples/src/app/code-examples/forms/single-file-attachment/basic/single-file-attachment-demo.component.html
  apps/code-examples/src/app/code-examples/forms/single-file-attachment/inline-help/single-file-attachment-demo.component.html
  apps/playground/src/app/components/forms/single-file-attachment/single-file-attachment.component.html
  libs/components/forms/src/assets/locales/resources_en_US.json
  libs/components/forms/src/lib/modules/file-attachment/file-attachment-label.component.html
  libs/components/forms/src/lib/modules/file-attachment/file-attachment-label.component.ts
  libs/components/forms/src/lib/modules/file-attachment/file-attachment.component.html
  libs/components/forms/src/lib/modules/file-attachment/file-attachments.module.ts
  libs/components/forms/src/lib/modules/shared/sky-forms-resources.module.ts
Labels: risk level (author): 1, risk level (reviewer): 1

#1642 feat(components/tabs): make all tabs responsive containers
  libs/components/tabs/src/lib/modules/tabs/tab.component.ts
  libs/components/tabs/src/lib/modules/tabs/tabset.component.spec.ts
Labels: risk level (author): 2, risk level (reviewer): 3

#1653 test(code-examples): remove fdescribes
  apps/code-examples/src/app/code-examples/pages/page/list-page-list-layout-demo/list-page-list-layout-demo.component.spec.ts
  apps/code-examples/src/app/code-examples/pages/page/list-page-tabs-layout-demo/list-page-tabs-layout-demo.component.spec.ts
  apps/code-examples/src/app/code-examples/pages/page/record-page-blocks-layout-demo/record-page-blocks-layout-demo.component.spec.ts
  apps/code-examples/src/app/code-examples/pages/page/record-page-tabs-layout-demo/record-page-tabs-layout-demo.component.spec.ts
  apps/code-examples/src/app/code-examples/pages/page/split-view-page-fit-layout-demo/split-view-page-fit-layout-demo.component.spec.ts
Labels: risk level (author): 1, risk level (reviewer): 1

#1639 ci: fix e2e preview publishing
  .github/workflows/e2e.yml
  libs/components/storybook/package.json
Labels: risk level (author): 1, risk level (reviewer): 2, skip e2e

#1648 chore: release 8.10.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease 8.x.x: pending

#1658 chore: release 8.10.1 (#1648)
  CHANGELOG.md
Labels: risk level (author): 1, risk level (reviewer): 1

#1657 fix(components/lookup): fix regression for lookup in modal (#1656)
  libs/components/lookup/src/lib/modules/lookup/lookup.component.ts
Labels: risk level (author): 1, risk level (reviewer): 1

#1661 fix(components/layout): fix action button margins in responsive containers
  libs/components/layout/src/lib/modules/action-button/action-button.component.scss
Labels: risk level (author): 2, risk level (reviewer): 2

#1664 fix(components/layout): fix action button margins in responsive containers (#1661)
  libs/components/layout/src/lib/modules/action-button/action-button.component.scss
Labels: risk level (author): 2, risk level (reviewer): 2

#1666 ci: change e2e affected calculation (#1650)
  .github/actions/e2e-affected/action.yml
  .github/actions/nx-set-shas/action.yml
  .github/workflows/ci.yml
  .github/workflows/e2e-cancel.yml
  .github/workflows/e2e.yml
Labels: risk level (author): 1, risk level (reviewer): 1, skip e2e

#1649 chore: release 9.0.0-alpha.9
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#1667 ci: fix `nx show projects` call in `e2e-affected` action
  .github/actions/e2e-affected/action.yml
Labels: risk level (author): 1, risk level (reviewer): 1
