Repository blackbaud/skyux, pull requests merged in 2023-11, with the labels that each got.

#1869 fix(components/popovers): dropdown position not working in firefox
  libs/components/core/src/lib/modules/affix/affix.directive.spec.ts
  libs/components/core/src/lib/modules/affix/affixer.ts
  libs/components/core/src/lib/modules/affix/fixtures/affix.component.fixture.html
  libs/components/core/src/lib/modules/affix/fixtures/affix.component.fixture.scss
  libs/components/core/src/lib/modules/affix/fixtures/affix.component.fixture.ts
Labels: risk level (author): 1

#1872 feat(components/theme): update to icons 6.5.0
  libs/components/theme/package.json
  libs/components/theme/src/lib/styles/sky.scss
  package.json
Labels: risk level (author): 1

#1874 chore: release 8.10.9
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease 8.x.x: pending

#1873 fix(components/popovers): dropdown position not working in firefox (#1869)
  libs/components/core/src/lib/modules/affix/affix.directive.spec.ts
  libs/components/core/src/lib/modules/affix/affixer.ts
  libs/components/core/src/lib/modules/affix/fixtures/affix.component.fixture.html
  libs/components/core/src/lib/modules/affix/fixtures/affix.component.fixture.scss
  libs/components/core/src/lib/modules/affix/fixtures/affix.component.fixture.ts
Labels: risk level (author): 1

#1876 chore: release 8.10.9 (#1874)
  CHANGELOG.md
Labels: risk level (author): 1, risk level (reviewer): 1

#1877 chore: fix package-lock.json mismatched versions
  package-lock.json
Labels: risk level (author): 1

#1875 chore: release 9.13.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#1852 fix(components/core): prevent ResizeObserver loop error
  apps/integration-e2e/src/e2e/modal-viewkept-toolbars.cy.ts
  apps/integration/src/app/integrations/lookup-in-modal/lookup-in-modal.component.ts
  apps/integration/src/app/integrations/modal-viewkept-toolbars/modal-viewkept-toolbars.component.html
  apps/integration/src/app/integrations/modal-viewkept-toolbars/modal-viewkept-toolbars.component.ts
  apps/integration/src/app/integrations/modal-viewkept-toolbars/modal-viewkept-toolbars.module.ts
  apps/integration/tsconfig.json
  apps/playground/src/app/components/core/resize-observer/basic/resize-observer-basic.module.ts
  libs/components/core/src/lib/modules/resize-observer/resize-observer-media-query.service.spec.ts
  libs/components/core/src/lib/modules/resize-observer/resize-observer.service.spec.ts
  libs/components/core/src/lib/modules/resize-observer/resize-observer.service.ts
  libs/components/pages/src/lib/modules/page-header/fixtures/page-header-fixtures.component.ts
  libs/components/pages/src/lib/modules/page-header/page-header.component.spec.ts
  libs/components/popovers/testing/src/dropdown/harness/dropdown-harness.ts
Labels: risk level (author): 2

#1878 chore: release 9.13.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#1866 feat(components/popovers): update dropdown docs and code example for aria label
  apps/code-examples/src/app/code-examples/popovers/dropdown/basic/demo.component.html
  libs/components/popovers/src/lib/modules/dropdown/dropdown.component.ts
Labels: risk level (author): 1

#1881 feat(components/action-bars): summary action bar announce content changes to screen readers
  libs/components/action-bars/src/lib/modules/summary-action-bar/summary-action-bar.component.html
Labels: risk level (author): 1

#1871 fix(components/data-manager): always persist sort sticky settings
  apps/code-examples/src/app/code-examples/ag-grid/data-entry-grid/data-manager-added/view-grid.component.ts
  apps/code-examples/src/app/code-examples/ag-grid/data-grid/data-manager/view-grid.component.ts
  apps/code-examples/src/app/code-examples/data-manager/data-manager/basic/view-grid.component.ts
  apps/code-examples/src/app/code-examples/data-manager/data-manager/basic/view-repeater.component.ts
  apps/playground/src/app/components/ag-grid/data-manager-large/data-manager-large.component.ts
  apps/playground/src/app/components/ag-grid/data-manager-large/data-set-large.ts
  apps/playground/src/app/components/ag-grid/data-manager/data-view-grid.component.html
  apps/playground/src/app/components/ag-grid/data-manager/data-view-grid.component.ts
  apps/playground/src/app/shared/data-manager/data-manager-view-grid.component.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/ag-grid-data-manager-adapter.directive.spec.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/ag-grid-data-manager-adapter.directive.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/fixtures/ag-grid-data-manager.component.fixture.ts
Labels: risk level (author): 2

#1884 chore: show add button in selection modal playground
  apps/playground/src/app/components/lookup/selection-modal/selection-modal-add-item-modal.component.html
  apps/playground/src/app/components/lookup/selection-modal/selection-modal-add-item-modal.component.ts
  apps/playground/src/app/components/lookup/selection-modal/selection-modal-playground.service.ts
  apps/playground/src/app/components/lookup/selection-modal/selection-modal.component.ts
  apps/playground/src/app/components/lookup/selection-modal/selection-modal.module.ts
Labels: risk level (author): 1

#1880 docs(components/tiles): fix broken links to sticky settings docs
  libs/components/data-manager/src/lib/modules/data-manager/models/data-manager-init-args.ts
  libs/components/flyout/src/lib/modules/flyout/types/flyout-config.ts
  libs/components/grids/src/lib/modules/grid/grid.component.ts
  libs/components/tiles/src/lib/modules/tiles/tile-dashboard/tile-dashboard.component.ts
Labels: risk level (author): 1

#1885 fix(components/modals): log warning about modal parameters
  libs/components/data-manager/src/lib/modules/data-manager/data-manager-toolbar/data-manager-toolbar.component.spec.ts
  libs/components/data-manager/src/lib/modules/data-manager/data-manager-toolbar/data-manager-toolbar.component.ts
  libs/components/pages/src/lib/modules/modal-link-list/modal-link-list.component.spec.ts
  libs/components/pages/src/lib/modules/modal-link-list/modal-link-list.component.ts
Labels: risk level (author): 1

#1865 feat(components/indicators): use more descriptive default ARIA labels for tokens and announce when they are dismissed to screen readers
  libs/components/indicators/src/assets/locales/resources_en_US.json
  libs/components/indicators/src/lib/modules/shared/sky-indicators-resources.module.ts
  libs/components/indicators/src/lib/modules/tokens/token.component.html
  libs/components/indicators/src/lib/modules/tokens/token.component.spec.ts
  libs/components/indicators/src/lib/modules/tokens/token.component.ts
  libs/components/indicators/src/lib/modules/tokens/tokens.component.spec.ts
  libs/components/indicators/src/lib/modules/tokens/tokens.module.ts
Labels: risk level (author): 1

#1879 chore: release 9.14.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#1888 fix(components/modals): use local environment injector when opening modal
  libs/components/modals/src/lib/modules/modal/modal-host.component.ts
  libs/components/modals/src/lib/modules/modal/modal.service.ts
Labels: risk level (author): 2

#1887 build: export css files with file extensions
  libs/components/ag-grid/package.json
  scripts/postbuild-theme.ts
Labels: risk level (author): 1

#1890 fix(components/flyout): use local environment injector when opening flyout
  libs/components/flyout/src/lib/modules/flyout/flyout.component.ts
  libs/components/flyout/src/lib/modules/flyout/flyout.service.ts
Labels: risk level (author): 2

#1889 chore: release 9.14.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#1893 feat(components/data-manager): text highlight search terms
  apps/playground/src/app/components/ag-grid/data-manager/data-view-grid.component.ts
  apps/playground/src/app/components/ag-grid/data-manager/data-view-repeater.component.ts
  libs/components/data-manager/src/lib/modules/data-manager/data-manager.component.spec.ts
  libs/components/data-manager/src/lib/modules/data-manager/data-view.component.ts
  libs/components/data-manager/src/lib/modules/data-manager/models/data-view-config.ts
  libs/components/indicators/src/index.ts
  libs/components/indicators/src/lib/modules/text-highlight/text-highlight.directive.ts
  libs/components/indicators/src/lib/modules/text-highlight/text-highlight.module.ts
Labels: risk level (author): 2

#1892 chore: release 9.15.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#1895 feat(components/theme): update to latest icons library
  libs/components/theme/package.json
  libs/components/theme/src/lib/styles/sky.scss
  package.json
Labels: risk level (author): 1

#1886 feat(components/lookup): selection modal broadcasts aria status updates when selection changes
  libs/components/lookup/src/assets/locales/resources_en_US.json
  libs/components/lookup/src/lib/modules/selection-modal/selection-modal.component.html
  libs/components/lookup/src/lib/modules/selection-modal/selection-modal.component.spec.ts
  libs/components/lookup/src/lib/modules/selection-modal/selection-modal.component.ts
  libs/components/lookup/src/lib/modules/shared/sky-lookup-resources.module.ts
Labels: risk level (author): 1

#1897 feat(components/lookup): show more modal broadcasts aria status updates when selection changes
  libs/components/lookup/src/lib/modules/lookup/lookup-show-more-modal.component.html
  libs/components/lookup/src/lib/modules/lookup/lookup-show-more-modal.component.ts
  libs/components/lookup/src/lib/modules/lookup/lookup.component.spec.ts
Labels: risk level (author): 1
