Repository blackbaud/skyux, pull requests merged in 2023-12, with the labels that each got.

#1899 ci: use shared cspell configs
  .cspell.json
  apps/e2e/.cspell.json
  apps/e2e/layout-storybook/src/app/back-to-top/back-to-top.component.html
  apps/e2e/popovers-storybook/src/app/popover/popover.component.html
  package-lock.json
  package.json
Labels: risk level (author): 1

#1896 chore: release 9.16.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#1901 fix(components/theme): update icon variant aliases
  libs/components/theme/package.json
  libs/components/theme/src/lib/styles/sky.scss
  package-lock.json
  package.json
Labels: risk level (author): 1

#1894 fix(components/packages): simplify style paths
  libs/components/packages/src/schematics/migrations/update-9/ag-grid-29/ag-grid-29.schematic.spec.ts
  libs/components/packages/src/schematics/migrations/update-9/ag-grid-29/ag-grid-29.schematic.ts
  libs/components/packages/src/schematics/ng-add/ng-add.schematic.spec.ts
  libs/components/packages/src/schematics/utility/theme.ts
Labels: risk level (author): 1

#1904 chore: release 9.16.2
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#1906 feat(components/data-manager): announce status messages
  apps/code-examples/src/app/code-examples/ag-grid/data-grid/data-manager-multiselect/view-grid.component.ts
  apps/code-examples/src/app/code-examples/ag-grid/data-grid/data-manager/view-grid.component.ts
  apps/code-examples/src/app/code-examples/data-manager/data-manager/basic/view-grid.component.ts
  apps/code-examples/src/app/code-examples/data-manager/data-manager/basic/view-repeater.component.ts
  apps/playground/src/app/components/ag-grid/data-manager/data-manager-visual.component.ts
  apps/playground/src/app/components/ag-grid/data-manager/data-view-grid.component.ts
  apps/playground/src/app/components/ag-grid/data-manager/data-view-repeater.component.ts
  libs/components/data-manager/src/assets/locales/resources_en_US.json
  libs/components/data-manager/src/lib/modules/data-manager/data-manager.component.spec.ts
  libs/components/data-manager/src/lib/modules/data-manager/data-manager.component.ts
  libs/components/data-manager/src/lib/modules/data-manager/data-manager.service.ts
  libs/components/data-manager/src/lib/modules/data-manager/models/data-manager-summary-change.ts
  libs/components/data-manager/src/lib/modules/data-manager/models/data-manager-summary.ts
  libs/components/data-manager/src/lib/modules/shared/sky-data-manager-resources.module.ts
Labels: risk level (author): 2

#1908 fix(components/data-manager): don't include sort dropdown in grid views
  apps/code-examples/src/app/code-examples/ag-grid/data-grid/data-manager-multiselect/view-grid.component.ts
Labels: risk level (author): 1

#1907 chore: release 9.17.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#1911 chore: release 9.18.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#1914 fix(components/popovers): adjust dropdown position when at the bottom of the screen
  apps/playground/src/app/components/popovers/dropdown/dropdown.component.html
  apps/playground/src/app/components/popovers/dropdown/dropdown.component.ts
  apps/playground/src/app/components/popovers/dropdown/dropdown.module.ts
  libs/components/core/src/lib/modules/affix/affixer.ts
Labels: risk level (author): 1

#1915 chore: add avatar playground page
  apps/playground/src/app/components/avatar/avatar.module.ts
  apps/playground/src/app/components/avatar/avatar/avatar-routing.module.ts
  apps/playground/src/app/components/avatar/avatar/avatar.component.html
  apps/playground/src/app/components/avatar/avatar/avatar.component.ts
  apps/playground/src/app/components/avatar/avatar/avatar.module.ts
  apps/playground/src/app/components/components.module.ts
Labels: risk level (author): 1

#1909 feat(components/lookup): announce autocomplete search result state change
  libs/components/lookup/src/assets/locales/resources_en_US.json
  libs/components/lookup/src/lib/modules/autocomplete/autocomplete.component.spec.ts
  libs/components/lookup/src/lib/modules/autocomplete/autocomplete.component.ts
  libs/components/lookup/src/lib/modules/shared/sky-lookup-resources.module.ts
Labels: risk level (author): 2

#1916 chore: release 9.19.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#1912 refactor(components/forms): create `sky-errors` component to reuse with other inputs
  apps/code-examples/src/app/code-examples/forms/input-box/basic/demo.component.html
  apps/playground/src/app/components/forms/input-box/input-box.component.html
  apps/playground/src/app/components/forms/input-box/input-box.module.ts
  libs/components/forms/src/assets/locales/resources_en_US.json
  libs/components/forms/src/index.ts
  libs/components/forms/src/lib/modules/form-error/form-error.component.ts
  libs/components/forms/src/lib/modules/form-error/form-errors.component.html
  libs/components/forms/src/lib/modules/form-error/form-errors.component.scss
  libs/components/forms/src/lib/modules/form-error/form-errors.component.ts
  libs/components/forms/src/lib/modules/form-error/form-errors.module.ts
  libs/components/forms/src/lib/modules/input-box/input-box-adapter.service.ts
  libs/components/forms/src/lib/modules/input-box/input-box-error.component.ts
  libs/components/forms/src/lib/modules/input-box/input-box-errors.component.html
  libs/components/forms/src/lib/modules/input-box/input-box-errors.component.ts
  libs/components/forms/src/lib/modules/input-box/input-box.component.html
  libs/components/forms/src/lib/modules/input-box/input-box.module.ts
  libs/components/forms/src/lib/modules/shared/sky-forms-resources.module.ts
  libs/components/forms/testing/src/input-box/input-box-harness.ts
Labels: risk level (author): 1

#1917 fix(components/ag-grid): clarify header sort buttons
  libs/components/ag-grid/src/assets/locales/resources_en_US.json
  libs/components/ag-grid/src/lib/modules/ag-grid/header/header.component.html
  libs/components/ag-grid/src/lib/modules/ag-grid/header/header.component.scss
  libs/components/ag-grid/src/lib/modules/ag-grid/header/header.component.spec.ts
  libs/components/ag-grid/src/lib/modules/shared/sky-ag-grid-resources.module.ts
  libs/components/ag-grid/src/lib/styles/_base.scss
Labels: risk level (author): 1

#1920 fix(components/popovers): dropdown position in modal footer
  apps/integration-e2e/src/e2e/modal-colorpicker.cy.ts
  apps/integration-e2e/src/e2e/modal-footer-dropdown.cy.ts
  apps/integration/src/app/integrations/integrations.module.ts
  apps/integration/src/app/integrations/modal-colorpicker/modal-colorpicker-modal.component.css
  apps/integration/src/app/integrations/modal-colorpicker/modal-colorpicker-modal.component.html
  apps/integration/src/app/integrations/modal-colorpicker/modal-colorpicker.component.html
  apps/integration/src/app/integrations/modal-colorpicker/modal-colorpicker.component.ts
  apps/integration/src/app/integrations/modal-footer-dropdown/modal-footer-dropdown-modal.component.css
  apps/integration/src/app/integrations/modal-footer-dropdown/modal-footer-dropdown-modal.component.html
  apps/integration/src/app/integrations/modal-footer-dropdown/modal-footer-dropdown-modal.component.ts
  apps/integration/src/app/integrations/modal-footer-dropdown/modal-footer-dropdown-routing.module.ts
  apps/integration/src/app/integrations/modal-footer-dropdown/modal-footer-dropdown.component.css
  apps/integration/src/app/integrations/modal-footer-dropdown/modal-footer-dropdown.component.html
  apps/integration/src/app/integrations/modal-footer-dropdown/modal-footer-dropdown.component.ts
  apps/integration/src/app/integrations/modal-footer-dropdown/modal-footer-dropdown.module.ts
  libs/components/core/src/lib/modules/affix/dom-utils.ts
Labels: risk level (author): 2

#1919 chore: release 9.19.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending
