Repository blackbaud/skyux, pull requests merged in 2023-07, with the labels that each got.

#1489 fix(components/ag-grid): update code example import path
  apps/code-examples/src/app/code-examples/ag-grid/data-entry-grid/data-manager-added/data-manager-data-entry-grid-docs-demo-view-grid.component.ts
Labels: risk level (author): 1, risk level (reviewer): 1

#1496 test(components/progress-indicator): progress indicator visual test
  apps/e2e/progress-indicator-storybook/project.json
  apps/e2e/progress-indicator-storybook/src/app/progress-indicator/progress-indicator.component.html
  apps/e2e/progress-indicator-storybook/src/app/progress-indicator/progress-indicator.module.ts
Labels: risk level (author): 1, risk level (reviewer): 1

#1495 fix(sdk/eslint-config): enable tsconfig 'strictNullChecks' to support 'prefer-nullish-coalescing' ESLint rule
  libs/sdk/eslint-config/package.json
  libs/sdk/eslint-config/src/schematics/ng-add/ng-add.schematic.spec.ts
  libs/sdk/eslint-config/src/schematics/ng-add/ng-add.schematic.ts
  libs/sdk/eslint-config/src/schematics/shared/rules/modify-tsconfig.ts
  libs/sdk/eslint-config/src/schematics/shared/utility/json-file.ts
Labels: risk level (author): 2, risk level (reviewer): 2

#1492 ci: handle empty set of e2e changes
  .github/workflows/e2e.yml
  package-lock.json
  package.json
Labels: risk level (author): 1, risk level (reviewer): 2

#1497 test(components/forms): single file attachment visual test
  apps/e2e/forms-storybook-e2e/src/e2e/single-file-attachment.component.cy.ts
  apps/e2e/forms-storybook/src/app/app.module.ts
  apps/e2e/forms-storybook/src/app/single-file-attachment/assets/myImage.jpg
  apps/e2e/forms-storybook/src/app/single-file-attachment/single-file-attachment.component.html
  apps/e2e/forms-storybook/src/app/single-file-attachment/single-file-attachment.component.scss
  apps/e2e/forms-storybook/src/app/single-file-attachment/single-file-attachment.component.stories.ts
  apps/e2e/forms-storybook/src/app/single-file-attachment/single-file-attachment.component.ts
  apps/e2e/forms-storybook/src/app/single-file-attachment/single-file-attachment.module.ts
Labels: risk level (author): 1, risk level (reviewer): 1

#1493 test(components/navbar): navbar visual test
  apps/e2e/navbar-storybook-e2e/src/e2e/navbar.component.cy.ts
  apps/e2e/navbar-storybook/project.json
  apps/e2e/navbar-storybook/src/app/navbar/navbar.component.html
  apps/e2e/navbar-storybook/src/app/navbar/navbar.component.ts
  apps/e2e/navbar-storybook/src/app/navbar/navbar.module.ts
Labels: risk level (author): 1, risk level (reviewer): 1

#1500 test(components/phone-field): phone field visual test
  apps/e2e/phone-field-storybook-e2e/src/e2e/phone-field.component.cy.ts
  apps/e2e/phone-field-storybook/project.json
  apps/e2e/phone-field-storybook/src/app/phone-field/phone-field.component.html
  apps/e2e/phone-field-storybook/src/app/phone-field/phone-field.component.ts
  apps/e2e/phone-field-storybook/src/app/phone-field/phone-field.module.ts
Labels: risk level (author): 1, risk level (reviewer): 1

#1503 test(components/text-editor): text editor visual test
  apps/e2e/text-editor-storybook-e2e/src/e2e/text-editor.component.cy.ts
  apps/e2e/text-editor-storybook/project.json
  apps/e2e/text-editor-storybook/src/app/text-editor/text-editor.component.html
  apps/e2e/text-editor-storybook/src/app/text-editor/text-editor.component.stories.ts
  apps/e2e/text-editor-storybook/src/app/text-editor/text-editor.component.ts
  apps/e2e/text-editor-storybook/src/app/text-editor/text-editor.module.ts
Labels: risk level (author): 1, risk level (reviewer): 1

#1484 feat(components/modals): add errors input to modal footer component
  apps/e2e/modals-storybook-e2e/src/e2e/modal.component.cy.ts
  apps/e2e/modals-storybook/src/app/modal/modal.component.html
  apps/e2e/modals-storybook/src/app/modal/modal.component.ts
  apps/e2e/modals-storybook/src/app/modal/modals/modal-basic.component.html
  apps/e2e/modals-storybook/src/app/modal/modals/modal-basic.component.ts
  apps/playground/src/app/components/modal/modal-error.component.html
  apps/playground/src/app/components/modal/modal-error.component.ts
  apps/playground/src/app/components/modal/modal-visual.component.html
  apps/playground/src/app/components/modal/modal-visual.component.ts
  apps/playground/src/app/components/modal/modal-visual.module.ts
  libs/components/modals/src/index.ts
  libs/components/modals/src/lib/modules/modal/fixtures/modal-footer.component.fixture.html
  libs/components/modals/src/lib/modules/modal/fixtures/modal-footer.component.fixture.ts
  libs/components/modals/src/lib/modules/modal/modal-error.ts
  libs/components/modals/src/lib/modules/modal/modal-errors.service.ts
  libs/components/modals/src/lib/modules/modal/modal-footer.component.html
  libs/components/modals/src/lib/modules/modal/modal-footer.component.scss
  libs/components/modals/src/lib/modules/modal/modal-footer.component.ts
  libs/components/modals/src/lib/modules/modal/modal.component.spec.ts
  libs/components/modals/src/lib/modules/modal/modal.component.ts
  libs/components/modals/src/lib/modules/modal/modal.module.ts
Labels: risk level (author): 1, risk level (reviewer): 2

#1506 test(components/layout): add text expand visual test
  apps/e2e/layout-storybook-e2e/src/e2e/text-expand.component.cy.ts
  apps/e2e/layout-storybook/src/app/app.module.ts
  apps/e2e/layout-storybook/src/app/text-expand/text-expand.component.html
  apps/e2e/layout-storybook/src/app/text-expand/text-expand.component.scss
  apps/e2e/layout-storybook/src/app/text-expand/text-expand.component.stories.ts
  apps/e2e/layout-storybook/src/app/text-expand/text-expand.component.ts
  apps/e2e/layout-storybook/src/app/text-expand/text-expand.module.ts
Labels: risk level (author): 1, risk level (reviewer): 1

#1501 feat(components/theme): add spacing option to themes
  apps/playground/src/app/app.module.ts
  apps/playground/src/app/shared/theme-selector/theme-selector-spacing-value.ts
  apps/playground/src/app/shared/theme-selector/theme-selector.component.html
  apps/playground/src/app/shared/theme-selector/theme-selector.component.ts
  apps/playground/src/app/shared/theme-selector/theme-selector.module.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/ag-grid-wrapper.component.spec.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/ag-grid.service.spec.ts
  libs/components/modals/src/lib/modules/modal/fixtures/mock-theme.service.ts
  libs/components/modals/testing/src/mock-theme.service.ts
  libs/components/theme/src/index.ts
  libs/components/theme/src/lib/theming/theme-settings.ts
  libs/components/theme/src/lib/theming/theme-spacing.ts
  libs/components/theme/src/lib/theming/theme.service.spec.ts
  libs/components/theme/src/lib/theming/theme.service.ts
  libs/components/theme/src/lib/theming/theme.spec.ts
  libs/components/theme/src/lib/theming/theme.ts
Labels: risk level (author): 2, risk level (reviewer): 2

#1498 fix(components/lookup): close observables during cleanup
  apps/code-examples/src/app/app.component.html
  apps/code-examples/src/app/code-examples/lookup/lookup/add-item/lookup-async-demo-search-results.ts
  apps/code-examples/src/app/code-examples/lookup/lookup/add-item/lookup-async-demo.component.html
  apps/code-examples/src/app/code-examples/lookup/lookup/add-item/lookup-async-demo.component.scss
  apps/code-examples/src/app/code-examples/lookup/lookup/add-item/lookup-async-demo.component.spec.ts
  apps/code-examples/src/app/code-examples/lookup/lookup/add-item/lookup-async-demo.component.ts
  apps/code-examples/src/app/code-examples/lookup/lookup/add-item/lookup-async-demo.module.ts
  apps/code-examples/src/app/code-examples/lookup/lookup/add-item/lookup-async-demo.service.ts
  apps/code-examples/src/app/code-examples/lookup/lookup/add-item/lookup-demo-add-item.component.html
  apps/code-examples/src/app/code-examples/lookup/lookup/add-item/lookup-demo-add-item.component.ts
  apps/code-examples/src/app/code-examples/lookup/lookup/add-item/lookup-demo-person.ts
  apps/code-examples/src/app/code-examples/lookup/selection-modal/add-item/selection-modal-demo-add-item.component.html
  apps/code-examples/src/app/code-examples/lookup/selection-modal/add-item/selection-modal-demo-add-item.component.ts
  apps/code-examples/src/app/code-examples/lookup/selection-modal/add-item/selection-modal-demo-person.ts
  apps/code-examples/src/app/code-examples/lookup/selection-modal/add-item/selection-modal-demo-search-results.ts
  apps/code-examples/src/app/code-examples/lookup/selection-modal/add-item/selection-modal-demo.component.html
  apps/code-examples/src/app/code-examples/lookup/selection-modal/add-item/selection-modal-demo.component.spec.ts
  apps/code-examples/src/app/code-examples/lookup/selection-modal/add-item/selection-modal-demo.component.ts
  apps/code-examples/src/app/code-examples/lookup/selection-modal/add-item/selection-modal-demo.module.ts
  apps/code-examples/src/app/code-examples/lookup/selection-modal/add-item/selection-modal-demo.service.ts
  apps/code-examples/src/app/features/lookup.module.ts
  libs/components/lookup/src/lib/modules/selection-modal/selection-modal.service.ts
Labels: risk level (author): 1, risk level (reviewer): 1

#1505 chore: release 8.5.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#1511 fix(components/colorpicker): icon color accessibility account for alpha
  apps/playground/src/app/components/colorpicker/colorpicker/colorpicker.component.html
  libs/components/colorpicker/src/lib/modules/colorpicker/colorpicker.component.spec.ts
  libs/components/colorpicker/src/lib/modules/colorpicker/colorpicker.component.ts
Labels: risk level (author): 2, risk level (reviewer): 2

#1514 fix(components/packages): update `ng add` schematic to work on Windows machines
  libs/components/packages/src/schematics/ng-add/ng-add.schematic.spec.ts
  libs/components/packages/src/schematics/ng-add/ng-add.schematic.ts
Labels: risk level (author): 1, risk level (reviewer): 1

#1512 feat(components/pages): add page header sub-components
  apps/code-examples/src/app/code-examples/pages/page/list-page-list-layout-demo/list-page-content.component.html
  apps/code-examples/src/app/code-examples/pages/page/list-page-tabs-layout-demo/list-page-contacts-grid.component.html
  apps/code-examples/src/app/code-examples/pages/page/record-page-tabs-layout-demo/record-page-attachments-tab.component.html
  apps/code-examples/src/app/code-examples/pages/page/record-page-tabs-layout-demo/record-page-notes-tab.component.html
  apps/code-examples/src/app/code-examples/pages/page/record-page-tabs-layout-demo/record-page-tabs-layout-demo.component.html
  apps/code-examples/src/app/code-examples/pages/page/record-page-tabs-layout-demo/record-page-tabs-layout-demo.component.spec.ts
  apps/code-examples/src/app/code-examples/pages/page/record-page-tabs-layout-demo/record-page-tabs-layout-demo.module.ts
  apps/code-examples/src/app/code-examples/pages/page/split-view-page-fit-layout-demo/split-view-page-fit-layout-demo.component.html
  apps/code-examples/src/app/code-examples/pages/page/split-view-page-fit-layout-demo/split-view-page-fit-layout-demo.module.ts
  apps/e2e/pages-storybook-e2e/src/e2e/page-layout-blocks.component.cy.ts
  apps/e2e/pages-storybook/src/app/page/layouts/blocks-page/blocks-page.component.html
  apps/e2e/pages-storybook/src/app/page/layouts/blocks-page/blocks-page.component.ts
  apps/e2e/pages-storybook/src/app/page/layouts/fit-page/fit-page.component.html
  apps/e2e/pages-storybook/src/app/page/layouts/fit-page/fit-page.component.ts
  apps/e2e/pages-storybook/src/app/page/layouts/list-page/list-page.component.html
  apps/e2e/pages-storybook/src/app/page/layouts/tabs-page/tabs-page.component.html
  libs/components/avatar/package.json
  libs/components/avatar/src/lib/modules/avatar/avatar.component.html
  libs/components/avatar/src/lib/modules/avatar/avatar.component.spec.ts
  libs/components/avatar/src/lib/modules/avatar/avatar.component.ts
  libs/components/core/src/index.ts
  libs/components/core/src/lib/modules/default-input-provider/default-input-provider.spec.ts
  libs/components/core/src/lib/modules/default-input-provider/default-input-provider.ts
  libs/components/pages/src/index.ts
  libs/components/pages/src/lib/modules/page-header/fixtures/page-header-fixtures.component.html
  libs/components/pages/src/lib/modules/page-header/fixtures/page-header-fixtures.component.ts
  libs/components/pages/src/lib/modules/page-header/page-header-actions.component.html
  libs/components/pages/src/lib/modules/page-header/page-header-actions.component.scss
  libs/components/pages/src/lib/modules/page-header/page-header-actions.component.ts
  libs/components/pages/src/lib/modules/page-header/page-header-alerts.component.html
  libs/components/pages/src/lib/modules/page-header/page-header-alerts.component.scss
  libs/components/pages/src/lib/modules/page-header/page-header-alerts.component.ts
  libs/components/pages/src/lib/modules/page-header/page-header-avatar.component.html
  libs/components/pages/src/lib/modules/page-header/page-header-avatar.component.scss
  libs/components/pages/src/lib/modules/page-header/page-header-avatar.component.ts
  libs/components/pages/src/lib/modules/page-header/page-header-details.component.html
  libs/components/pages/src/lib/modules/page-header/page-header-details.component.scss
  libs/components/pages/src/lib/modules/page-header/page-header-details.component.ts
  libs/components/pages/src/lib/modules/page-header/page-header.component.html
  libs/components/pages/src/lib/modules/page-header/page-header.component.scss
  libs/components/pages/src/lib/modules/page-header/page-header.component.spec.ts
  libs/components/pages/src/lib/modules/page-header/page-header.module.ts
  libs/components/pages/src/lib/modules/page/page.component.ts
Labels: risk level (author): 2, risk level (reviewer): 2

#1515 chore: release 8.6.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#1509 fix(components/text-editor): add icon to colorpicker
  libs/components/text-editor/src/lib/modules/text-editor/toolbar/text-editor-toolbar.component.html
Labels: risk level (author): 1, risk level (reviewer): 1

#1517 build(code-examples): add lint rule for imports
  apps/code-examples/.eslintrc.json
  apps/code-examples/src/app/code-examples/lookup/lookup/add-item/lookup-async-demo.component.ts
Labels: risk level (author): 1, risk level (reviewer): 1

#1518 fix(components/pages): page documentation fixes
  libs/components/pages/src/lib/modules/page-header/page-header-actions.component.ts
  libs/components/pages/src/lib/modules/page-header/page-header-alerts.component.ts
  libs/components/pages/src/lib/modules/page-header/page-header.component.ts
  libs/components/tabs/src/index.ts
  libs/components/tabs/src/lib/modules/tabs/tab-layout-type.ts
Labels: risk level (author): 1, risk level (reviewer): 1

#1520 ci: update e2e api call for 100+ checks
  .github/workflows/e2e.yml
Labels: risk level (author): 1, risk level (reviewer): 2

#1519 chore: release 8.7.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#1510 test(components/layout): add text expand repeater visual test
  apps/e2e/layout-storybook-e2e/src/e2e/text-expand-repeater.component.cy.ts
  apps/e2e/layout-storybook/src/app/app.module.ts
  apps/e2e/layout-storybook/src/app/text-expand-repeater/text-expand-repeater.component.html
  apps/e2e/layout-storybook/src/app/text-expand-repeater/text-expand-repeater.component.scss
  apps/e2e/layout-storybook/src/app/text-expand-repeater/text-expand-repeater.component.stories.ts
  apps/e2e/layout-storybook/src/app/text-expand-repeater/text-expand-repeater.component.ts
  apps/e2e/layout-storybook/src/app/text-expand-repeater/text-expand-repeater.module.ts
  apps/playground/src/app/components/layout/layout.module.ts
  apps/playground/src/app/components/layout/text-expand-repeater/text-expand-repeater-routing.module.ts
  apps/playground/src/app/components/layout/text-expand-repeater/text-expand-repeater.component.html
  apps/playground/src/app/components/layout/text-expand-repeater/text-expand-repeater.component.ts
  apps/playground/src/app/components/layout/text-expand-repeater/text-expand-repeater.module.ts
Labels: risk level (author): 1, risk level (reviewer): 1

#1521 test(components/angular-tree-component): tree view visual test
  apps/e2e/angular-tree-component-storybook-e2e/src/e2e/angular-tree-component.component.cy.ts
  apps/e2e/angular-tree-component-storybook/project.json
  apps/e2e/angular-tree-component-storybook/src/app/angular-tree-component/angular-tree-component.component.html
  apps/e2e/angular-tree-component-storybook/src/app/angular-tree-component/angular-tree-component.component.stories.ts
  apps/e2e/angular-tree-component-storybook/src/app/angular-tree-component/angular-tree-component.component.ts
  apps/e2e/angular-tree-component-storybook/src/app/angular-tree-component/angular-tree-component.module.ts
Labels: risk level (author): 1, risk level (reviewer): 1

#1522 ci: update e2e check for affected projects
  .github/workflows/e2e.yml
Labels: risk level (author): 2, risk level (reviewer): 2

#1513 fix(components/indicators): fix content roles
  libs/components/indicators/src/lib/modules/tokens/fixtures/tokens.component.fixture.html
  libs/components/indicators/src/lib/modules/tokens/fixtures/tokens.component.fixture.ts
  libs/components/indicators/src/lib/modules/tokens/tokens.component.html
  libs/components/indicators/src/lib/modules/tokens/tokens.component.scss
  libs/components/indicators/src/lib/modules/tokens/tokens.component.spec.ts
  libs/components/lookup/src/lib/modules/lookup/lookup.component.spec.ts
Labels: risk level (author): 2, risk level (reviewer): 2

#1524 ci: set 9.x.x prerelease
  .github/workflows/release-please.yml
Labels: risk level (author): 1, risk level (reviewer): 1

#1516 test(components/datetime): timepicker visual test
  apps/e2e/datetime-storybook-e2e/src/e2e/timepicker.component.cy.ts
  apps/e2e/datetime-storybook/src/app/app.module.ts
  apps/e2e/datetime-storybook/src/app/timepicker/timepicker.component.html
  apps/e2e/datetime-storybook/src/app/timepicker/timepicker.component.scss
  apps/e2e/datetime-storybook/src/app/timepicker/timepicker.component.stories.ts
  apps/e2e/datetime-storybook/src/app/timepicker/timepicker.component.ts
  apps/e2e/datetime-storybook/src/app/timepicker/timepicker.module.ts
Labels: risk level (author): 1, risk level (reviewer): 1

#1526 test(components/datetime): timepicker visual test (#1516)
  apps/e2e/datetime-storybook-e2e/src/e2e/timepicker.component.cy.ts
  apps/e2e/datetime-storybook/src/app/app.module.ts
  apps/e2e/datetime-storybook/src/app/timepicker/timepicker.component.html
  apps/e2e/datetime-storybook/src/app/timepicker/timepicker.component.scss
  apps/e2e/datetime-storybook/src/app/timepicker/timepicker.component.stories.ts
  apps/e2e/datetime-storybook/src/app/timepicker/timepicker.component.ts
  apps/e2e/datetime-storybook/src/app/timepicker/timepicker.module.ts
Labels: risk level (author): 1, risk level (reviewer): 1
