Repository blackbaud/skyux, pull requests merged in 2023-05, with the labels that each got.

#1344 chore: release 7.21.3
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease 7.x.x: pending

#1353 chore: release 8.0.0-beta.4
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#1356 chore: release 8.0.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#1358 chore: release 8.0.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#1366 chore: release 8.0.2
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#1367 fix(components/forms): revert fix for focus flash when checkbox and radio buttons are clicked inside of a modal
  libs/components/forms/src/lib/modules/checkbox/checkbox.component.html
  libs/components/forms/src/lib/modules/radio/radio.component.html
Labels: risk level (author): 1, risk level (reviewer): 1

#1369 chore: release 7.21.4
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease 7.x.x: pending

#1372 chore: release 8.0.3
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#1350 fix(components/datetime): date range pickers properly render when used in an inline filter item
  apps/code-examples/src/app/code-examples/lists/filter/inline/filter-demo.component.html
  apps/code-examples/src/app/code-examples/lists/filter/inline/filter-demo.module.ts
  apps/code-examples/src/app/code-examples/lists/filter/modal/filter-demo-modal.component.html
  apps/code-examples/src/app/code-examples/lists/filter/modal/filter-demo.module.ts
  apps/playground/src/app/components/ag-grid/data-manager/data-filter-modal.component.html
  apps/playground/src/app/components/ag-grid/data-manager/data-manager.module.ts
  apps/playground/src/app/components/lists/filter/filter-visual.component.html
  apps/playground/src/app/components/lists/filter/filter-visual.component.ts
  libs/components/datetime/src/lib/modules/date-range-picker/date-range-picker.component.scss
  package-lock.json
Labels: risk level (author): 2, risk level (reviewer): 2

#1379 fix: restore form group background color
  libs/components/forms/src/lib/modules/input-box/input-box.component.scss
  libs/components/lookup/src/lib/modules/search/search.component.scss
Labels: risk level (reviewer): 2

#1382 chore: enable `noPropertyAccessFromIndexSignature` typescript rule
  apps/code-examples/src/app/code-examples/datetime/date-range-picker/basic/date-range-picker-demo.component.html
  apps/code-examples/src/app/code-examples/forms/character-count/character-count-demo.component.html
  apps/code-examples/src/app/code-examples/forms/input-box/basic/input-box-demo.component.html
  apps/code-examples/src/app/code-examples/forms/input-box/inline-help/input-box-demo.component.html
  apps/code-examples/src/app/code-examples/forms/selection-box/radio/selection-box-demo.component.html
  apps/code-examples/src/app/code-examples/forms/selection-box/radio/selection-box-demo.component.ts
  apps/code-examples/src/app/code-examples/validation/email-validation/control-validator/email-validation-demo.component.html
  apps/code-examples/src/app/code-examples/validation/email-validation/directive/email-validation-demo.component.html
  apps/code-examples/src/app/code-examples/validation/url-validation/control-validator/url-validation-demo.component.html
  apps/code-examples/src/app/code-examples/validation/url-validation/directive/url-validation-demo.component.html
  apps/playground/src/app/components/lookup/lookup/lookup.component.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/ag-grid.service.spec.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-validator/ag-grid-cell-validator-tooltip.component.spec.ts
  libs/components/config/src/lib/app-config.module.spec.ts
  libs/components/core/src/lib/modules/affix/affix.directive.ts
  libs/components/datetime/src/lib/modules/date-range-picker/date-range-picker.component.ts
  libs/components/datetime/src/lib/modules/datepicker/fuzzy-datepicker.component.spec.ts
  libs/components/flyout/src/lib/modules/flyout/flyout.component.spec.ts
  libs/components/forms/src/lib/modules/file-attachment/file-attachment.component.spec.ts
  libs/components/forms/src/lib/modules/file-attachment/file-drop.component.spec.ts
  libs/components/forms/src/lib/modules/shared/forms-utility.ts
  libs/components/grids/src/lib/modules/grid/grid-column.component.ts
  libs/components/grids/src/lib/modules/grid/grid.component.ts
  libs/components/indicators/src/lib/modules/text-highlight/text-highlight.directive.ts
  libs/components/layout/src/lib/modules/fluid-grid/column.component.ts
  libs/components/lists/src/lib/modules/repeater/repeater.component.ts
  libs/components/lookup/src/lib/modules/lookup/fixtures/lookup.component.fixture.ts
  libs/components/lookup/src/lib/modules/lookup/lookup.component.spec.ts
  libs/components/packages/src/schematics/migrations/update-8/add-compat-stylesheets/add-compat-stylesheets.ts
  libs/components/packages/src/schematics/migrations/update-8/update-polyfill/update-polyfill.schematic.ts
  libs/components/packages/src/schematics/rules/add-polyfills-config.ts
  libs/components/packages/src/schematics/rules/apply-skyux-stylesheets-to-workspace.ts
  libs/components/router/src/lib/modules/link/link-external.directive.ts
  libs/components/router/src/lib/modules/link/link.directive.ts
  libs/components/storybook/src/lib/preview-wrapper/preview-wrapper-decorators.ts
  libs/components/tabs/src/lib/modules/tabs/tab.component.ts
  libs/sdk/e2e-schematics/src/generators/component-e2e/index.spec.ts
  libs/sdk/e2e-schematics/src/generators/configure-storybook/index.spec.ts
  libs/sdk/e2e-schematics/src/generators/configure-storybook/index.ts
  libs/sdk/e2e-schematics/src/generators/switch-to-variations/generator.ts
  libs/sdk/e2e-schematics/src/utils/find-module.ts
  package-lock.json
  tsconfig.base.json
Labels: risk level (author): 2

#1373 chore: release 8.1.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#1380 ci: more details in e2e visual review check
  .github/workflows/e2e.yml
Labels: risk level (author): 1

#1378 feat(components/config): exclude specified params from link URLs
  libs/components/config/src/lib/config-params.ts
  libs/components/config/src/lib/params.spec.ts
  libs/components/config/src/lib/params.ts
  libs/components/router/src/lib/modules/href/fixtures/href-fixture.component.ts
  libs/components/router/src/lib/modules/href/href.directive.spec.ts
  libs/components/router/src/lib/modules/href/href.directive.ts
Labels: risk level (author): 2, risk level (reviewer): 3

#1391 test(components/forms): add visual test for textarea input box with no label
  apps/e2e/forms-storybook/src/app/input-box/input-box.component.html
  apps/playground/src/app/components/forms/input-box/input-box.component.html
Labels: risk level (author): 1

#1388 chore: release 8.2.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#1396 fix(components/forms): make help inline clickable in input box HTML select
  apps/code-examples/src/app/code-examples/forms/input-box/inline-help/input-box-demo.component.html
  apps/code-examples/src/app/code-examples/forms/input-box/inline-help/input-box-demo.component.ts
  libs/components/forms/src/lib/modules/input-box/input-box.component.scss
Labels: risk level (author): 2

#1399 test(components/forms): add a11y testing for input box
  libs/components/forms/src/lib/modules/input-box/fixtures/input-box.component.fixture.html
  libs/components/forms/src/lib/modules/input-box/fixtures/input-box.component.fixture.ts
  libs/components/forms/src/lib/modules/input-box/fixtures/input-box.module.fixture.ts
  libs/components/forms/src/lib/modules/input-box/input-box.component.spec.ts
Labels: risk level (author): 1

#1349 fix(components/forms): autofill styles are applied correctly to input boxes
  apps/e2e/forms-storybook/project.json
  apps/e2e/lists-storybook/project.json
  apps/e2e/tabs-storybook/project.json
  apps/playground/src/app/components/forms/input-box/input-box.component.html
  apps/playground/src/app/components/forms/input-box/input-box.component.ts
  libs/components/forms/src/lib/modules/input-box/input-box.component.html
  libs/components/forms/src/lib/modules/input-box/input-box.component.scss
Labels: risk level (author): 2

#1401 test(components/forms): add visual test for checkbox with help inline
  apps/e2e/forms-storybook/src/app/checkbox/checkbox.component.html
  apps/e2e/forms-storybook/src/app/checkbox/checkbox.module.ts
Labels: risk level (author): 1, risk level (reviewer): 1

#1375 chore: release 7.22.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease 7.x.x: pending

#1404 chore: release 8.2.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#1407 fix(components/forms): use correct class in input box error documentation
  libs/components/forms/src/lib/modules/input-box/input-box.component.ts
  package-lock.json
Labels: risk level (author): 1

#1410 chore: release 8.2.2
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#1414 test(components/toast): add toast visual tests
  apps/e2e/toast-storybook-e2e/src/e2e/toast.component.cy.ts
  apps/e2e/toast-storybook/project.json
  apps/e2e/toast-storybook/src/app/toast/toast-custom.component.html
  apps/e2e/toast-storybook/src/app/toast/toast-custom.component.ts
  apps/e2e/toast-storybook/src/app/toast/toast.component.html
  apps/e2e/toast-storybook/src/app/toast/toast.component.ts
  apps/e2e/toast-storybook/src/app/toast/toast.module.ts
Labels: risk level (author): 1, risk level (reviewer): 1

#1416 ci: verify that risk labels have been applied
  .github/workflows/cherry-pick.yml
  .github/workflows/risk-assessment.yml
Labels: risk level (author): 1, risk level (reviewer): 1
