Repository blackbaud/skyux, pull requests merged in 2023-09, with the labels that each got.

#1668 deprecation(components/lookup): inputs to set autcomplete HTML attributes on the autocomplete, lookup, and country field components have been deprecated
  libs/components/ag-grid/src/lib/modules/ag-grid/types/lookup-properties.ts
  libs/components/lookup/src/lib/modules/autocomplete/autocomplete-input.directive.ts
  libs/components/lookup/src/lib/modules/country-field/country-field.component.ts
  libs/components/lookup/src/lib/modules/lookup/lookup.component.ts
  libs/components/lookup/testing/src/country-field/country-field-fixture.ts
Labels: risk level (author): 1, risk level (reviewer): 1

#1673 fix(components/pages): `lastAccessed` property on the `SkyRecentLink` interface is more descriptive
  libs/components/pages/src/lib/modules/action-hub/types/recent-link.ts
Labels: risk level (author): 1, risk level (reviewer): 1

#1671 ci: fix e2e head ref calculation
  .github/actions/nx-set-shas/action.yml
  .github/workflows/e2e-cancel.yml
Labels: risk level (author): 1, risk level (reviewer): 1, skip e2e

#1672 ci: fix e2e head ref calculation on main
  .github/actions/nx-set-shas/action.yml
  .github/workflows/e2e-cancel.yml
Labels: risk level (author): 1, risk level (reviewer): 1, skip e2e

#1654 fix(components/lookup)!: use `click` events for selecting items in an autocomplete or lookup dropdown and only close when clicking outside the dropdown
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-editors/cell-editor-lookup/cell-editor-lookup.component.spec.ts
  libs/components/lookup/src/lib/modules/autocomplete/autocomplete.component.html
  libs/components/lookup/src/lib/modules/autocomplete/autocomplete.component.spec.ts
  libs/components/lookup/src/lib/modules/autocomplete/autocomplete.component.ts
  libs/components/lookup/src/lib/modules/country-field/country-field.component.spec.ts
  libs/components/lookup/src/lib/modules/lookup/fixtures/lookup-input-box.component.fixture.html
  libs/components/lookup/src/lib/modules/lookup/fixtures/lookup-template.component.fixture.html
  libs/components/lookup/src/lib/modules/lookup/fixtures/lookup.component.fixture.html
  libs/components/lookup/src/lib/modules/lookup/lookup.component.spec.ts
  libs/components/lookup/src/lib/modules/lookup/lookup.component.ts
  libs/components/lookup/testing/src/country-field/country-field-fixture.ts
  libs/components/phone-field/src/lib/modules/phone-field/phone-field.component.spec.ts
Labels: risk level (author): 2, risk level (reviewer): 3

#1676 chore: update dev-infra to 9.0.0-alpha.9
  package-lock.json
  package.json
Labels: risk level (author): 1, risk level (reviewer): 1

#1663 chore: release 8.10.2
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease 8.x.x: pending

#1678 chore: release 8.10.2 (#1663)
  CHANGELOG.md
Labels: risk level (author): 1, risk level (reviewer): 1

#1670 refactor: remove hard-coded `id` attributes from flyout iterator and grid components
  libs/components/flyout/src/lib/modules/flyout/flyout-iterator.component.html
  libs/components/flyout/src/lib/modules/flyout/flyout.component.spec.ts
  libs/components/grids/src/lib/modules/grid/grid.component.html
  libs/components/grids/src/lib/modules/grid/grid.component.scss
  libs/components/grids/src/lib/modules/grid/grid.component.spec.ts
Labels: risk level (author): 2, risk level (reviewer): 2

#1660 fix(components/forms): easy mode input box inputs default to turning off browser autofill but respect consumer set values
  libs/components/forms/src/lib/modules/input-box/fixtures/input-box.component.fixture.html
  libs/components/forms/src/lib/modules/input-box/fixtures/input-box.component.fixture.ts
  libs/components/forms/src/lib/modules/input-box/input-box-control.directive.ts
  libs/components/forms/src/lib/modules/input-box/input-box.component.spec.ts
Labels: risk level (author): 2, risk level (reviewer): 2

#1677 feat(components/packages): add schematic to regenerate i18n resources modules for libraries
  libs/components/packages/src/schematics/migrations/migration-collection.json
  libs/components/packages/src/schematics/migrations/update-9/i18n-resources-module/i18n-resources-module.schematic.spec.ts
  libs/components/packages/src/schematics/migrations/update-9/i18n-resources-module/i18n-resources-module.schematic.ts
Labels: risk level (author): 2, risk level (reviewer): 2

#1675 fix(components/ag-grid): improve schematic for AG Grid 29 changes
  libs/components/packages/src/schematics/migrations/update-9/ag-grid-29/ag-grid-29.schematic.spec.ts
  libs/components/packages/src/schematics/migrations/update-9/ag-grid-29/ag-grid-29.schematic.ts
Labels: risk level (author): 1, risk level (reviewer): 2

#1679 chore: release 9.0.0-alpha.10
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#1683 ci: simplify e2e nx affected rules
  .github/actions/nx-set-shas/action.yml
Labels: risk level (author): 1, risk level (reviewer): 1, skip e2e

#1684 ci: simplify e2e nx affected rules (#1683)
  .github/actions/nx-set-shas/action.yml
Labels: risk level (author): 1, risk level (reviewer): 1

#1662 fix(components/datetime): remove vertical spacing and fix horizontal padding
  apps/e2e/datetime-storybook-e2e/src/e2e/date-range-picker.component.cy.ts
  apps/playground/src/app/components/datetime/date-range-picker/date-range-picker.component.html
  libs/components/datetime/src/lib/modules/date-range-picker/date-range-picker.component.html
  libs/components/datetime/src/lib/modules/date-range-picker/date-range-picker.component.scss
Labels: risk level (author): 2, risk level (reviewer): 2

#1682 feat(components/modals): make modals responsive containers
  libs/components/modals/src/lib/modules/modal/modal.component.spec.ts
  libs/components/modals/src/lib/modules/modal/modal.component.ts
Labels: risk level (author): 2, risk level (reviewer): 2

#1685 fix(components/data-manager): add providers to column picker modal
  libs/components/data-manager/src/lib/modules/data-manager/data-manager-column-picker/data-manager-column-picker-providers.ts
  libs/components/data-manager/src/lib/modules/data-manager/data-manager-toolbar/data-manager-toolbar.component.spec.ts
  libs/components/data-manager/src/lib/modules/data-manager/data-manager-toolbar/data-manager-toolbar.component.ts
  libs/components/data-manager/src/lib/modules/data-manager/data-manager.module.ts
Labels: risk level (author): 2, risk level (reviewer): 2

#1687 build: only require author risk label as a PR gate
  .github/workflows/risk-assessment.yml
Labels: risk level (author): 1, skip e2e

#1688 build: only require author risk label as a PR gate (#1687)
  .github/workflows/risk-assessment.yml
Labels: risk level (author): 1

#1665 fix(components/lookup): fix dropdown position in Safari on iOS
  libs/components/core/src/lib/modules/affix/affix.directive.spec.ts
  libs/components/core/src/lib/modules/affix/affix.service.ts
  libs/components/core/src/lib/modules/affix/affixer.spec.ts
  libs/components/core/src/lib/modules/affix/affixer.ts
  libs/components/datetime/src/lib/modules/datepicker/datepicker.component.spec.ts
  libs/components/datetime/src/lib/modules/timepicker/timepicker.component.spec.ts
  libs/components/lookup/src/lib/modules/autocomplete/autocomplete.component.scss
  libs/components/lookup/src/lib/modules/autocomplete/autocomplete.component.spec.ts
  libs/components/lookup/src/lib/modules/autocomplete/autocomplete.component.ts
  libs/components/tabs/src/lib/modules/tabs/tabset.component.spec.ts
Labels: risk level (author): 3, risk level (reviewer): 3

#1691 fix(components/lookup): fix dropdown position in Safari on iOS (#1665)
  libs/components/core/src/lib/modules/affix/affix.directive.spec.ts
  libs/components/core/src/lib/modules/affix/affix.service.ts
  libs/components/core/src/lib/modules/affix/affixer.spec.ts
  libs/components/core/src/lib/modules/affix/affixer.ts
  libs/components/datetime/src/lib/modules/datepicker/datepicker.component.spec.ts
  libs/components/datetime/src/lib/modules/timepicker/timepicker.component.spec.ts
  libs/components/lookup/src/lib/modules/autocomplete/autocomplete.component.scss
  libs/components/lookup/src/lib/modules/autocomplete/autocomplete.component.spec.ts
  libs/components/lookup/src/lib/modules/autocomplete/autocomplete.component.ts
  libs/components/tabs/src/lib/modules/tabs/tabset.component.spec.ts
Labels: risk level (author): 3, risk level (reviewer): 3

#1690 feat(sdk/testing): update axe-core peer dependency
  libs/sdk/testing/package.json
Labels: risk level (author): 1

#1694 ci: skip workflows on release pr
  .github/workflows/ci.yml
  .github/workflows/e2e.yml
Labels: risk level (author): 1

#1680 fix(components/phone-field)!: phone numbers that are valid for a country with the same dial code as the selected country but not the selected country are now properly validated
  libs/components/phone-field/src/lib/modules/phone-field/phone-field-input.directive.ts
  libs/components/phone-field/src/lib/modules/phone-field/phone-field.component.spec.ts
  libs/components/phone-field/src/lib/modules/phone-field/phone-field.component.ts
Labels: risk level (author): 2

#1698 fix(components/tabs): fixed tab permalink back button behavior
  libs/components/tabs/src/lib/modules/tabs/fixtures/tabs-fixtures.module.ts
  libs/components/tabs/src/lib/modules/tabs/fixtures/tabset-other-page.component.fixture.ts
  libs/components/tabs/src/lib/modules/tabs/fixtures/tabset-permalinks.component.fixture.ts
  libs/components/tabs/src/lib/modules/tabs/tabset-active-tab-change-args.ts
  libs/components/tabs/src/lib/modules/tabs/tabset-permalink.service.ts
  libs/components/tabs/src/lib/modules/tabs/tabset.component.spec.ts
  libs/components/tabs/src/lib/modules/tabs/tabset.component.ts
  libs/components/tabs/src/lib/modules/tabs/tabset.service.ts
Labels: risk level (author): 3, risk level (reviewer): 3

#1699 ci: switch from rebase to merge to sync pr workflows
  .github/workflows/e2e.yml
  scripts/rebase-pr.js
Labels: risk level (author): 1

#1700 ci: switch from rebase to merge to sync pr workflows (#1699)
  .github/workflows/e2e.yml
  scripts/rebase-pr.js
Labels: risk level (author): 1, risk level (reviewer): 1

#1695 ci: skip workflows on release pr (#1694)
  .github/workflows/ci.yml
  .github/workflows/e2e.yml
Labels: risk level (author): 1, skip e2e

#1701 feat(components/pages): provide schematic for updating `SkyPageComponent`
  libs/components/packages/src/schematics/migrations/migration-collection.json
  libs/components/packages/src/schematics/migrations/update-9/move-page-component/move-page-component.schematic.spec.ts
  libs/components/packages/src/schematics/migrations/update-9/move-page-component/move-page-component.schematic.ts
Labels: risk level (author): 1

#1689 feat(components/tabs): sectioned form styling improvements
  apps/code-examples/src/app/code-examples/tabs/sectioned-form/modal/address-form-demo.component.ts
  apps/code-examples/src/app/code-examples/tabs/sectioned-form/modal/information-form-demo.component.html
  apps/code-examples/src/app/code-examples/tabs/sectioned-form/modal/information-form-demo.component.ts
  apps/code-examples/src/app/code-examples/tabs/sectioned-form/modal/phone-form-demo.component.ts
  apps/code-examples/src/app/code-examples/tabs/sectioned-form/modal/sectioned-form-demo.component.ts
  apps/code-examples/src/app/code-examples/tabs/sectioned-form/modal/sectioned-form-demo.module.ts
  apps/code-examples/src/app/code-examples/tabs/sectioned-form/modal/sectioned-form-modal-demo.component.html
  apps/code-examples/src/app/code-examples/tabs/sectioned-form/modal/sectioned-form-modal-demo.component.ts
  apps/code-examples/src/app/features/tabs.module.ts
  apps/playground/src/app/components/tabs/sectioned-form/routes.ts
  apps/playground/src/app/components/tabs/sectioned-form/sectioned-form-address-form-demo.component.ts
  apps/playground/src/app/components/tabs/sectioned-form/sectioned-form-date-form-demo.component.ts
  apps/playground/src/app/components/tabs/sectioned-form/sectioned-form-information-form-demo.component.html
  apps/playground/src/app/components/tabs/sectioned-form/sectioned-form-information-form-demo.component.ts
  apps/playground/src/app/components/tabs/sectioned-form/sectioned-form-modal.component.html
  apps/playground/src/app/components/tabs/sectioned-form/sectioned-form-modal.component.ts
  apps/playground/src/app/components/tabs/sectioned-form/sectioned-form-phone-form-demo.component.ts
  apps/playground/src/app/components/tabs/sectioned-form/sectioned-form-routing.module.ts
  apps/playground/src/app/components/tabs/sectioned-form/sectioned-form.component.ts
  apps/playground/src/app/components/tabs/sectioned-form/sectioned-form.module.ts
  apps/playground/src/app/components/tabs/tabs.module.ts
  libs/components/modals/src/lib/modules/modal/modal.component.scss
  libs/components/modals/src/lib/modules/modal/modal.component.spec.ts
  libs/components/tabs/src/lib/modules/sectioned-form/sectioned-form.component.html
  libs/components/tabs/src/lib/modules/sectioned-form/sectioned-form.component.scss
  libs/components/tabs/src/lib/modules/vertical-tabset/vertical-tab.component.scss
Labels: risk level (author): 2

#1686 chore: release 9.0.0-beta.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#1702 ci: update release-as
  .github/workflows/release-please.yml
Labels: risk level (author): 1

#1703 ci: update branch workflow
  .github/workflows/update-branch.yml
Labels: risk level (author): 1

#1697 chore(components/forms): checkboxes rely on automatic skyux icons
  libs/components/forms/src/lib/modules/checkbox/checkbox.component.html
  libs/components/forms/src/lib/modules/checkbox/checkbox.component.scss
  libs/components/forms/testing/src/checkbox/checkbox-harness.ts
  libs/components/theme/package.json
  libs/components/theme/src/lib/styles/sky.scss
  package-lock.json
  package.json
Labels: risk level (author): 1

#1707 chore(components/indicators): add missing deprecation tag to `SkyIconType` and downstream consumers
  libs/components/colorpicker/src/lib/modules/colorpicker/colorpicker.component.ts
  libs/components/indicators/src/lib/modules/icon/types/icon-type.ts
Labels: risk level (author): 1

#1705 fix(components/tabs): use `replaceState()` for default tab permalink
  libs/components/tabs/src/lib/modules/tabs/fixtures/tabset-permalinks.component.fixture.ts
  libs/components/tabs/src/lib/modules/tabs/tabset.component.spec.ts
  libs/components/tabs/src/lib/modules/tabs/tabset.service.ts
Labels: risk level (author): 3, risk level (reviewer): 2

#1708 fix(components/angular-tree-component): update schematic to work in more cases
  libs/components/packages/src/schematics/migrations/update-9/update-angular-tree-component/update-angular-tree-component.schematic.spec.ts
  libs/components/packages/src/schematics/migrations/update-9/update-angular-tree-component/update-angular-tree-component.schematic.ts
Labels: risk level (author): 1, risk level (reviewer): 2

#1711 fix(components/angular-tree-component): node expansion button uses the node name as its aria-label
  libs/components/angular-tree-component/src/lib/modules/angular-tree/angular-tree-node.component.html
Labels: risk level (author): 1

#1714 ci: add git config for merge (#1713)
  scripts/rebase-pr.js
Labels: risk level (author): 1

#1712 fix(components/popovers)!: dropdown menu buttons only specify a default aria-label when configured to be a context menu
  apps/code-examples/src/app/code-examples/popovers/dropdown/basic/dropdown-demo.component.html
  apps/code-examples/src/app/code-examples/popovers/dropdown/basic/dropdown-demo.component.spec.ts
  apps/playground/src/app/components/popovers/dropdown/dropdown.component.html
  apps/playground/src/app/components/popovers/dropdown/dropdown.module.ts
  libs/components/action-bars/src/lib/modules/summary-action-bar/actions/summary-action-bar-secondary-actions.component.html
  libs/components/popovers/src/lib/modules/dropdown/dropdown.component.html
  libs/components/popovers/src/lib/modules/dropdown/dropdown.component.spec.ts
  libs/components/popovers/testing/src/dropdown/harness/dropdown-harness.spec.ts
Labels: risk level (author): 1

#1706 chore: release 9.0.0-beta.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#1715 fix(components/angular-tree-component): tree view code examples now use context specific accessibility labels and dropdown menu labels
  apps/code-examples/src/app/code-examples/angular-tree-component/angular-tree/advanced/angular-tree-demo.component.html
  apps/code-examples/src/app/code-examples/angular-tree-component/angular-tree/advanced/angular-tree-demo.component.ts
  apps/code-examples/src/app/code-examples/angular-tree-component/angular-tree/advanced/angular-tree-demo.module.ts
Labels: risk level (author): 1

#1718 ci: release-as 9.0.0
  .github/workflows/release-please.yml
Labels: risk level (author): 1

#1717 chore: release 9.0.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#1722 ci: reset release-as
  .github/workflows/release-please.yml
Labels: risk level (author): 1, risk level (reviewer): 1

#1721 feat: add support for `@angular/core@16.2.5`
  .nvmrc
  .skyuxdev.json
  apps/playground/src/app/components/layout/toolbar/toolbar.component.html
  libs/components/a11y/package.json
  libs/components/action-bars/package.json
  libs/components/ag-grid/package.json
  libs/components/angular-tree-component/package.json
  libs/components/animations/package.json
  libs/components/assets/package.json
  libs/components/autonumeric/package.json
  libs/components/avatar/package.json
  libs/components/colorpicker/package.json
  libs/components/config/package.json
  libs/components/core/package.json
  libs/components/data-manager/package.json
  libs/components/datetime/package.json
  libs/components/errors/package.json
  libs/components/flyout/package.json
  libs/components/forms/package.json
  libs/components/grids/package.json
  libs/components/http/package.json
  libs/components/i18n/package.json
  libs/components/indicators/package.json
  libs/components/inline-form/package.json
  libs/components/layout/package.json
  libs/components/list-builder-common/package.json
  libs/components/list-builder-view-checklist/package.json
  libs/components/list-builder-view-grids/package.json
  libs/components/list-builder/package.json
  libs/components/lists/package.json
  libs/components/lookup/package.json
  libs/components/modals/package.json
  libs/components/navbar/package.json
  libs/components/omnibar-interop/package.json
  libs/components/packages/package.json
  libs/components/pages/package.json
  libs/components/phone-field/package.json
  libs/components/popovers/package.json
  libs/components/progress-indicator/package.json
  libs/components/router/package.json
  libs/components/select-field/package.json
  libs/components/split-view/package.json
  libs/components/storybook/package.json
  libs/components/tabs/package.json
  libs/components/text-editor/package.json
  libs/components/theme/package.json
  libs/components/tiles/package.json
  libs/components/toast/package.json
  libs/components/validation/package.json
  libs/sdk/e2e-schematics/package.json
  libs/sdk/eslint-config/package.json
  libs/sdk/prettier-schematics/package.json
  libs/sdk/testing/package.json
  libs/sdk/tools/package.json
  package-lock.json
  package.json
Labels: risk level (author): 2, risk level (reviewer): 2

#1723 feat(components/http): add `context` to `skyAuthHttpOptions` and `skyAuthHttpJsonOptions`
  libs/components/http/src/lib/modules/auth-http-client/auth-options.ts
Labels: risk level (author): 1, risk level (reviewer): 1

#1720 feat(components/theme): update SKY UX icons to latest versions
  libs/components/theme/package.json
  libs/components/theme/src/lib/styles/sky.scss
  package-lock.json
  package.json
Labels: risk level (author): 1, risk level (reviewer): 1

#1724 chore: release 9.1.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#1725 fix(components/popovers): update background style for dropdown items
  libs/components/popovers/src/lib/modules/dropdown/dropdown-item.component.scss
Labels: risk level (author): 1

#1726 chore: release 9.1.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#1729 ci: add retry option to cypress preset
  apps/e2e/a11y-storybook-e2e/cypress.config.ts
  apps/e2e/action-bars-storybook-e2e/cypress.config.ts
  apps/e2e/ag-grid-storybook-e2e/cypress.config.ts
  apps/e2e/angular-tree-component-storybook-e2e/cypress.config.ts
  apps/e2e/avatar-storybook-e2e/cypress.config.ts
  apps/e2e/colorpicker-storybook-e2e/cypress.config.ts
  apps/e2e/core-storybook-e2e/cypress.config.ts
  apps/e2e/data-manager-storybook-e2e/cypress.config.ts
  apps/e2e/datetime-storybook-e2e/cypress.config.ts
  apps/e2e/errors-storybook-e2e/cypress.config.ts
  apps/e2e/flyout-storybook-e2e/cypress.config.ts
  apps/e2e/forms-storybook-e2e/cypress.config.ts
  apps/e2e/indicators-storybook-e2e/cypress.config.ts
  apps/e2e/inline-form-storybook-e2e/cypress.config.ts
  apps/e2e/layout-storybook-e2e/cypress.config.ts
  apps/e2e/lists-storybook-e2e/cypress.config.ts
  apps/e2e/lookup-storybook-e2e/cypress.config.ts
  apps/e2e/modals-storybook-e2e/cypress.config.ts
  apps/e2e/navbar-storybook-e2e/cypress.config.ts
  apps/e2e/pages-storybook-e2e/cypress.config.ts
  apps/e2e/phone-field-storybook-e2e/cypress.config.ts
  apps/e2e/popovers-storybook-e2e/cypress.config.ts
  apps/e2e/progress-indicator-storybook-e2e/cypress.config.ts
  apps/e2e/split-view-storybook-e2e/cypress.config.ts
  apps/e2e/tabs-storybook-e2e/cypress.config.ts
  apps/e2e/text-editor-storybook-e2e/cypress.config.ts
  apps/e2e/theme-storybook-e2e/cypress.config.ts
  apps/e2e/tiles-storybook-e2e/cypress.config.ts
  apps/e2e/toast-storybook-e2e/cypress.config.ts
  apps/integration-e2e/cypress.config.ts
  libs/sdk/e2e-schematics/src/cypress-preset.ts
  libs/sdk/e2e-schematics/src/generators/configure-percy/__snapshots__/index.spec.ts.snap
  libs/sdk/e2e-schematics/src/generators/configure-percy/files/cypress.config.ts.template
  tsconfig.base.json
Labels: risk level (author): 1

#1730 docs(components/pages): add ARIA labels to action hub code example action buttons
  apps/code-examples/src/app/code-examples/pages/action-hub/action-hub-demo.component.html
  apps/code-examples/src/app/code-examples/pages/action-hub/action-hub-demo.component.ts
Labels: risk level (author): 1

#1731 ci: handle empty response from Percy check
  .github/actions/e2e-affected/action.yml
Labels: risk level (author): 1

#1727 fix(components/lookup): reset focus for search result controls when new text entered in input
  libs/components/lookup/src/lib/modules/autocomplete/autocomplete.component.spec.ts
  libs/components/lookup/src/lib/modules/autocomplete/autocomplete.component.ts
Labels: risk level (author): 1, risk level (reviewer): 2

#1736 feat(components/indicators): icon visual test (#1168) (#1170)
  apps/e2e/indicators-storybook-e2e/src/e2e/icon.component.cy.ts
  apps/e2e/indicators-storybook/src/app/app.module.ts
  apps/e2e/indicators-storybook/src/app/icon/icon.component.html
  apps/e2e/indicators-storybook/src/app/icon/icon.component.scss
  apps/e2e/indicators-storybook/src/app/icon/icon.component.spec.ts
  apps/e2e/indicators-storybook/src/app/icon/icon.component.stories.ts
  apps/e2e/indicators-storybook/src/app/icon/icon.component.ts
  apps/e2e/indicators-storybook/src/app/icon/icon.module.ts
Labels: risk level (author): 1

#1734 feat(components/core): add `VERSION` to public exports API; update to `@skyux/icons@6.3.0`
  libs/components/core/src/index.ts
  libs/components/core/src/version.ts
  libs/components/theme/package.json
  libs/components/theme/src/lib/styles/sky.scss
  package-lock.json
  package.json
Labels: risk level (author): 1

#1733 chore: release 9.2.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#1738 fix: release 9.2.1
  CHANGELOG.md
Labels: risk level (author): 1, risk level (reviewer): 1

#1739 chore: release 9.2.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#1741 ci: update `@skyux/dev-infra-private@9.0.0-alpha.12`
  package-lock.json
  package.json
Labels: risk level (author): 1, risk level (reviewer): 1

#1737 feat(components/angular-tree-component): context menu aria labels are automatically node specific
  apps/code-examples/src/app/code-examples/angular-tree-component/angular-tree/advanced/demo.component.html
  libs/components/angular-tree-component/src/assets/locales/resources_en_US.json
  libs/components/angular-tree-component/src/lib/modules/angular-tree/angular-tree-node.component.html
  libs/components/angular-tree-component/src/lib/modules/angular-tree/angular-tree-node.component.ts
  libs/components/angular-tree-component/src/lib/modules/angular-tree/angular-tree-root.component.spec.ts
  libs/components/angular-tree-component/src/lib/modules/angular-tree/fixtures/tree-view.fixture.component.html
  libs/components/angular-tree-component/src/lib/modules/angular-tree/fixtures/tree-view.fixture.component.ts
  libs/components/angular-tree-component/src/lib/modules/shared/sky-angular-tree-component-resources.module.ts
  libs/components/popovers/src/lib/modules/dropdown/dropdown.component.html
  libs/components/popovers/src/lib/modules/dropdown/dropdown.component.spec.ts
  libs/components/popovers/src/lib/modules/dropdown/dropdown.component.ts
Labels: risk level (author): 2

#1744 ci: support merge group event
  .github/workflows/ci.yml
  .github/workflows/e2e.yml
  .github/workflows/release-please.yml
  package-lock.json
  package.json
Labels: risk level (author): 1

#1745 feat(components/lists): filter button aria label property can be specified
  libs/components/lists/src/lib/modules/filter/filter-button.component.html
  libs/components/lists/src/lib/modules/filter/filter-button.component.spec.ts
  libs/components/lists/src/lib/modules/filter/filter-button.component.ts
  libs/components/lists/src/lib/modules/filter/fixtures/filter-button.component.fixture.html
  libs/components/lists/src/lib/modules/filter/fixtures/filter-button.component.fixture.ts
Labels: risk level (author): 1

#1746 feat(components/lists): sort button aria label property can be specified
  libs/components/lists/src/lib/modules/sort/fixtures/sort.component.fixture.html
  libs/components/lists/src/lib/modules/sort/fixtures/sort.component.fixture.ts
  libs/components/lists/src/lib/modules/sort/sort.component.html
  libs/components/lists/src/lib/modules/sort/sort.component.spec.ts
  libs/components/lists/src/lib/modules/sort/sort.component.ts
Labels: risk level (author): 1

#1751 ci: move verify-e2e to typescript
  .github/actions/e2e-affected/action.yml
  .github/workflows/e2e.yml
  libs/sdk/e2e-schematics/src/workflow/index.ts
  libs/sdk/e2e-schematics/src/workflow/verify-e2e/verify-e2e.spec.ts
  libs/sdk/e2e-schematics/src/workflow/verify-e2e/verify-e2e.ts
Labels: risk level (author): 1, skip e2e

#1750 chore: create SkyContentDescriptorProvider
  libs/components/angular-tree-component/src/assets/locales/resources_en_US.json
  libs/components/angular-tree-component/src/lib/modules/angular-tree/angular-tree-node.component.ts
  libs/components/angular-tree-component/src/lib/modules/shared/sky-angular-tree-component-resources.module.ts
  libs/components/core/src/index.ts
  libs/components/core/src/lib/modules/content-info-provider/content-info-provider.spec.ts
  libs/components/core/src/lib/modules/content-info-provider/content-info-provider.ts
  libs/components/core/src/lib/modules/content-info-provider/content-info.ts
  libs/components/core/src/lib/modules/default-input-provider/default-input-provider.ts
  libs/components/popovers/src/assets/locales/resources_en_US.json
  libs/components/popovers/src/lib/modules/dropdown/dropdown.component.html
  libs/components/popovers/src/lib/modules/dropdown/dropdown.component.spec.ts
  libs/components/popovers/src/lib/modules/dropdown/dropdown.component.ts
  libs/components/popovers/src/lib/modules/shared/sky-popovers-resources.module.ts
Labels: risk level (author): 2

#1754 fix(components/phone-field): new Canadian area codes properly validate
  libs/components/phone-field/package.json
  package-lock.json
  package.json
Labels: risk level (author): 1

#1756 chore: release 8.10.4
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease 8.x.x: pending

#1759 chore: release 8.10.4 (#1756)
  CHANGELOG.md
Labels: risk level (author): 1, risk level (reviewer): 1

#1752 feat(components/datetime): date range picker input aria labels are now context specific
  .cspell.json
  libs/components/datetime/src/assets/locales/resources_en_US.json
  libs/components/datetime/src/lib/modules/date-range-picker/date-range-picker.component.html
  libs/components/datetime/src/lib/modules/date-range-picker/date-range-picker.component.spec.ts
  libs/components/datetime/src/lib/modules/shared/sky-datetime-resources.module.ts
Labels: risk level (author): 2, risk level (reviewer): 2

#1758 feat(components/config): add local dev config
  libs/components/config/src/lib/config.ts
Labels: risk level (author): 1, risk level (reviewer): 1

#1742 chore: release 9.3.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#1762 fix: release 9.3.1
  CHANGELOG.md
Labels: risk level (author): 1

#1764 ci: use Node 18.18.0
  .nvmrc
Labels: risk level (author): 1, risk level (reviewer): 1

#1755 feat(components/theme): update to latest @skyux/icons
  apps/e2e/indicators-storybook-e2e/src/e2e/icon.component.cy.ts
  apps/e2e/indicators-storybook/src/app/icon/icon.component.html
  apps/e2e/indicators-storybook/src/app/icon/icon.component.ts
  libs/components/indicators/src/lib/modules/icon/icon-resolver.service.spec.ts
  libs/components/indicators/src/lib/modules/icon/icon-resolver.service.ts
  libs/components/list-builder/src/lib/modules/list-filters/list-filter-summary.component.spec.ts
  libs/components/theme/package.json
  libs/components/theme/src/lib/styles/sky.scss
  package-lock.json
  package.json
Labels: risk level (author): 1, risk level (reviewer): 2

#1753 docs(code-examples): add descriptive ARIA labels to help inline components in code examples
  apps/code-examples/src/app/code-examples/ag-grid/data-entry-grid/inline-help/inline-help.component.html
  apps/code-examples/src/app/code-examples/ag-grid/data-entry-grid/inline-help/inline-help.component.ts
  apps/code-examples/src/app/code-examples/ag-grid/data-grid/inline-help/inline-help.component.html
  apps/code-examples/src/app/code-examples/ag-grid/data-grid/inline-help/inline-help.component.ts
  apps/code-examples/src/app/code-examples/angular-tree-component/angular-tree/inline-help/demo.component.html
  apps/code-examples/src/app/code-examples/forms/checkbox/inline-help/demo.component.html
  apps/code-examples/src/app/code-examples/forms/file-attachment/inline-help/demo.component.html
  apps/code-examples/src/app/code-examples/forms/input-box/inline-help/demo.component.html
  apps/code-examples/src/app/code-examples/forms/radio/inline-help/demo.component.html
  apps/code-examples/src/app/code-examples/forms/single-file-attachment/inline-help/demo.component.html
  apps/code-examples/src/app/code-examples/forms/toggle-switch/inline-help/demo.component.html
  apps/code-examples/src/app/code-examples/indicators/help-inline/basic/demo.component.html
  apps/code-examples/src/app/code-examples/indicators/key-info/inline-help/demo.component.html
  apps/code-examples/src/app/code-examples/indicators/status-indicator/basic/demo.component.html
  apps/code-examples/src/app/code-examples/indicators/status-indicator/inline-help/demo.component.html
  apps/code-examples/src/app/code-examples/layout/box/inline-help/demo.component.html
  apps/code-examples/src/app/code-examples/layout/description-list/inline-help/demo.component.html
  apps/code-examples/src/app/code-examples/modals/inline-help/modal.component.html
  apps/code-examples/src/app/code-examples/popovers/popover/programmatic/demo.component.html
  apps/code-examples/src/app/code-examples/progress-indicator/passive-indicator/inline-help/demo.component.html
  apps/code-examples/src/app/code-examples/progress-indicator/waterfall-indicator/inline-help/demo.component.html
  apps/code-examples/src/app/code-examples/text-editor/text-editor-inline-help/demo.component.html
  apps/code-examples/src/app/code-examples/tiles/tiles/inline-help/tile1.component.html
  apps/code-examples/src/app/code-examples/tiles/tiles/inline-help/tile2.component.html
  libs/components/indicators/src/lib/modules/help-inline/help-inline.component.ts
Labels: risk level (author): 1

#1747 feat(components/layout): toolbars include a listDescriptor which passes context to standard items aria labels
  apps/integration/src/app/integrations/integrations.module.ts
  apps/integration/src/app/integrations/toolbar-standard-items/toolbar-standard-items-routing.module.ts
  apps/integration/src/app/integrations/toolbar-standard-items/toolbar-standard-items.component.html
  apps/integration/src/app/integrations/toolbar-standard-items/toolbar-standard-items.component.spec.ts
  apps/integration/src/app/integrations/toolbar-standard-items/toolbar-standard-items.component.ts
  apps/integration/src/app/integrations/toolbar-standard-items/toolbar-standard-items.module.ts
  libs/components/layout/src/lib/modules/toolbar/fixtures/toolbar.component.fixture.html
  libs/components/layout/src/lib/modules/toolbar/fixtures/toolbar.component.fixture.ts
  libs/components/layout/src/lib/modules/toolbar/toolbar.component.spec.ts
  libs/components/layout/src/lib/modules/toolbar/toolbar.component.ts
  libs/components/lists/src/assets/locales/resources_en_US.json
  libs/components/lists/src/lib/modules/filter/filter-button.component.html
  libs/components/lists/src/lib/modules/filter/filter-button.component.spec.ts
  libs/components/lists/src/lib/modules/filter/filter-button.component.ts
  libs/components/lists/src/lib/modules/shared/sky-lists-resources.module.ts
  libs/components/lists/src/lib/modules/sort/sort.component.html
  libs/components/lists/src/lib/modules/sort/sort.component.spec.ts
  libs/components/lists/src/lib/modules/sort/sort.component.ts
  libs/components/lookup/src/assets/locales/resources_en_US.json
  libs/components/lookup/src/lib/modules/search/search.component.html
  libs/components/lookup/src/lib/modules/search/search.component.spec.ts
  libs/components/lookup/src/lib/modules/search/search.component.ts
  libs/components/lookup/src/lib/modules/shared/sky-lookup-resources.module.ts
Labels: risk level (author): 2
