Repository blackbaud/skyux, pull requests merged in 2023-10, with the labels that each got.

#1765 fix(components/core): numeric pipe now handles undefined values
  libs/components/core/src/lib/modules/numeric/fixtures/numeric.pipe.fixture.html
  libs/components/core/src/lib/modules/numeric/fixtures/numeric.pipe.fixture.ts
  libs/components/core/src/lib/modules/numeric/numeric.pipe.spec.ts
  libs/components/core/src/lib/modules/numeric/numeric.pipe.ts
  libs/components/core/src/lib/modules/numeric/numeric.service.ts
Labels: risk level (author): 2

#1771 chore: release 8.10.5
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease 8.x.x: pending

#1773 chore: release 8.10.5 (#1771)
  CHANGELOG.md
Labels: risk level (author): 1, risk level (reviewer): 1

#1770 fix(components/core): numeric pipe now handles undefined values (#1765)
  libs/components/core/src/lib/modules/numeric/fixtures/numeric.pipe.fixture.html
  libs/components/core/src/lib/modules/numeric/fixtures/numeric.pipe.fixture.ts
  libs/components/core/src/lib/modules/numeric/numeric.pipe.spec.ts
  libs/components/core/src/lib/modules/numeric/numeric.pipe.ts
  libs/components/core/src/lib/modules/numeric/numeric.service.ts
Labels: risk level (author): 2

#1772 ci: bump dev-infra to 9.0.0-alpha.14
  package-lock.json
  package.json
Labels: risk level (author): 1

#1767 chore: release 9.4.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#1774 ci: update e2e config for 8.x.x
  .github/workflows/e2e.yml
  apps/e2e/a11y-storybook-e2e/cypress.config.ts
  apps/e2e/action-bars-storybook-e2e/cypress.config.ts
  apps/e2e/action-bars-storybook-e2e/src/e2e/summary-action-bar.component.cy.ts
  apps/e2e/ag-grid-storybook-e2e/cypress.config.ts
  apps/e2e/angular-tree-component-storybook-e2e/cypress.config.ts
  apps/e2e/avatar-storybook-e2e/cypress.config.ts
  apps/e2e/colorpicker-storybook-e2e/cypress.config.ts
  apps/e2e/core-storybook-e2e/cypress.config.ts
  apps/e2e/data-manager-storybook-e2e/cypress.config.ts
  apps/e2e/datetime-storybook-e2e/cypress.config.ts
  apps/e2e/errors-storybook-e2e/cypress.config.ts
  apps/e2e/flyout-storybook-e2e/cypress.config.ts
  apps/e2e/forms-storybook-e2e/cypress.config.ts
  apps/e2e/indicators-storybook-e2e/cypress.config.ts
  apps/e2e/inline-form-storybook-e2e/cypress.config.ts
  apps/e2e/layout-storybook-e2e/cypress.config.ts
  apps/e2e/lists-storybook-e2e/cypress.config.ts
  apps/e2e/lookup-storybook-e2e/cypress.config.ts
  apps/e2e/modals-storybook-e2e/cypress.config.ts
  apps/e2e/modals-storybook-e2e/src/e2e/modal.component.cy.ts
  apps/e2e/navbar-storybook-e2e/cypress.config.ts
  apps/e2e/pages-storybook-e2e/cypress.config.ts
  apps/e2e/pages-storybook-e2e/src/e2e/page-layout-blocks.component.cy.ts
  apps/e2e/phone-field-storybook-e2e/cypress.config.ts
  apps/e2e/popovers-storybook-e2e/cypress.config.ts
  apps/e2e/progress-indicator-storybook-e2e/cypress.config.ts
  apps/e2e/split-view-storybook-e2e/cypress.config.ts
  apps/e2e/tabs-storybook-e2e/cypress.config.ts
  apps/e2e/text-editor-storybook-e2e/cypress.config.ts
  apps/e2e/theme-storybook-e2e/cypress.config.ts
  apps/e2e/tiles-storybook-e2e/cypress.config.ts
  apps/e2e/toast-storybook-e2e/cypress.config.ts
  apps/integration-e2e/cypress.config.ts
  libs/sdk/e2e-schematics/src/workflow/verify-e2e/verify-e2e.ts
  tsconfig.base.json
Labels: risk level (author): 1

#1757 ci: check for missing percy screenshots
  .github/actions/e2e-affected/action.yml
  .github/actions/nx-set-shas/action.yml
  .github/workflows/e2e.yml
  .percy.json
  apps/e2e/action-bars-storybook-e2e/src/e2e/summary-action-bar.component.cy.ts
  apps/e2e/pages-storybook-e2e/src/e2e/page-layout-blocks.component.cy.ts
  libs/sdk/e2e-schematics/src/workflow/index.ts
  libs/sdk/e2e-schematics/src/workflow/percy-api/percy-api.spec.ts
  libs/sdk/e2e-schematics/src/workflow/percy-api/percy-api.ts
  libs/sdk/e2e-schematics/src/workflow/verify-e2e/verify-e2e.spec.ts
  libs/sdk/e2e-schematics/src/workflow/verify-e2e/verify-e2e.ts
Labels: risk level (author): 1, risk level (reviewer): 1, skip e2e

#1777 docs(components/tiles): fix punctuation in tileName description
  libs/components/tiles/src/lib/modules/tiles/tile/tile.component.ts
Labels: documentation, risk level (author): 1

#1719 ci: require `BREAKING CHANGE` in commit message; disallow `!` in title
  .github/workflows/validate-pr.yml
Labels: risk level (author): 1, risk level (reviewer): 1

#1779 fix(components/toast): `SkyToastService` and `SkyToastLegacyService` add toast instances to the same pool
  apps/code-examples/src/app/code-examples/angular-tree-component/angular-tree/advanced/demo.component.scss
  apps/code-examples/src/app/code-examples/angular-tree-component/angular-tree/advanced/demo.component.ts
  libs/components/toast/src/lib/modules/toast/toast.service.ts
  libs/components/toast/src/lib/modules/toast/toaster.component.spec.ts
Labels: risk level (author): 2, risk level (reviewer): 2

#1780 chore: release 9.4.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#1775 feat(components/data-manager): data managers include a listDescriptor which passes context to standard items aria labels
  libs/components/data-manager/src/assets/locales/resources_en_US.json
  libs/components/data-manager/src/lib/modules/data-manager/data-manager-toolbar/data-manager-toolbar.component.html
  libs/components/data-manager/src/lib/modules/data-manager/data-manager-toolbar/data-manager-toolbar.component.spec.ts
  libs/components/data-manager/src/lib/modules/data-manager/fixtures/data-manager.component.fixture.ts
  libs/components/data-manager/src/lib/modules/data-manager/models/data-manager-config.ts
  libs/components/data-manager/src/lib/modules/shared/sky-data-manager-resources.module.ts
Labels: risk level (author): 1

#1781 chore(apps/playground): add selection modal playground page
  apps/playground/src/app/components/lookup/lookup.module.ts
  apps/playground/src/app/components/lookup/selection-modal/selection-modal-playground.service.ts
  apps/playground/src/app/components/lookup/selection-modal/selection-modal-routing.module.ts
  apps/playground/src/app/components/lookup/selection-modal/selection-modal.component.html
  apps/playground/src/app/components/lookup/selection-modal/selection-modal.component.ts
  apps/playground/src/app/components/lookup/selection-modal/selection-modal.module.ts
  apps/playground/src/app/components/lookup/selection-modal/types/selection-modal-playground-person.ts
  apps/playground/src/app/components/lookup/selection-modal/types/selection-modal-playground-search-results.ts
Labels: risk level (author): 1, risk level (reviewer): 1

#1785 ci: optimize the linting and formatting portions of the CI build
  .github/workflows/ci.yml
  package.json
Labels: risk level (author): 1, risk level (reviewer): 1, skip e2e

#1784 feat: add character counter, input box, and status indicator harnesses
  apps/code-examples/src/app/code-examples/forms/character-count/demo.component.html
  apps/code-examples/src/app/code-examples/forms/character-count/demo.component.spec.ts
  apps/code-examples/src/app/code-examples/forms/input-box/basic/demo.component.html
  apps/code-examples/src/app/code-examples/forms/input-box/basic/demo.component.spec.ts
  apps/code-examples/src/app/code-examples/indicators/status-indicator/basic/demo.component.html
  apps/code-examples/src/app/code-examples/indicators/status-indicator/basic/demo.component.spec.ts
  libs/components/forms/src/lib/modules/input-box/input-box-error.component.ts
  libs/components/forms/src/lib/modules/input-box/input-box-errors.component.html
  libs/components/forms/src/lib/modules/input-box/input-box.component.spec.ts
  libs/components/forms/src/lib/modules/input-box/input-box.component.ts
  libs/components/forms/testing/src/character-counter/character-counter-indicator-harness-filters.ts
  libs/components/forms/testing/src/character-counter/character-counter-indicator-harness.spec.ts
  libs/components/forms/testing/src/character-counter/character-counter-indicator-harness.ts
  libs/components/forms/testing/src/input-box/fixtures/input-box-harness-test.component.html
  libs/components/forms/testing/src/input-box/fixtures/input-box-harness-test.component.ts
  libs/components/forms/testing/src/input-box/fixtures/input-box-harness-test.module.ts
  libs/components/forms/testing/src/input-box/input-box-harness.spec.ts
  libs/components/forms/testing/src/input-box/input-box-harness.ts
  libs/components/forms/testing/src/public-api.ts
  libs/components/indicators/src/lib/modules/status-indicator/status-indicator.component.ts
  libs/components/indicators/testing/src/public-api.ts
  libs/components/indicators/testing/src/status-indicator/status-indicator-harness-filters.ts
  libs/components/indicators/testing/src/status-indicator/status-indicator-harness.spec.ts
  libs/components/indicators/testing/src/status-indicator/status-indicator-harness.ts
Labels: risk level (author): 2, risk level (reviewer): 2

#1787 feat(components/lookup): add selection modals include a `selectionDescriptor` which passes context to aria labels and the modal title
  apps/code-examples/src/app/code-examples/lookup/selection-modal/add-item/demo.component.spec.ts
  apps/code-examples/src/app/code-examples/lookup/selection-modal/add-item/demo.component.ts
  apps/code-examples/src/app/code-examples/lookup/selection-modal/basic/demo.component.spec.ts
  apps/code-examples/src/app/code-examples/lookup/selection-modal/basic/demo.component.ts
  apps/code-examples/tsconfig.editor.json
  apps/playground/src/app/components/lookup/selection-modal/selection-modal.component.html
  apps/playground/src/app/components/lookup/selection-modal/selection-modal.component.ts
  libs/components/lookup/src/assets/locales/resources_en_US.json
  libs/components/lookup/src/lib/modules/lookup/lookup.component.spec.ts
  libs/components/lookup/src/lib/modules/selection-modal/fixtures/mocks.ts
  libs/components/lookup/src/lib/modules/selection-modal/fixtures/person.ts
  libs/components/lookup/src/lib/modules/selection-modal/fixtures/search-results.ts
  libs/components/lookup/src/lib/modules/selection-modal/fixtures/selection-modal-fixture.service.ts
  libs/components/lookup/src/lib/modules/selection-modal/selection-modal.component.html
  libs/components/lookup/src/lib/modules/selection-modal/selection-modal.component.spec.ts
  libs/components/lookup/src/lib/modules/selection-modal/selection-modal.service.spec.ts
  libs/components/lookup/src/lib/modules/selection-modal/selection-modal.service.ts
  libs/components/lookup/src/lib/modules/selection-modal/types/selection-modal-context.ts
  libs/components/lookup/src/lib/modules/selection-modal/types/selection-modal-open-args.ts
  libs/components/lookup/src/lib/modules/shared/sky-lookup-resources.module.ts
  libs/components/lookup/testing/src/selection-modal/selection-modal-harness.spec.ts
  libs/components/lookup/testing/src/selection-modal/selection-modal-harness.ts
Labels: risk level (author): 2

#1778 refactor(apps/playground): use standalone components for modals, flyouts, and toasts
  apps/playground/src/app/components/action-bars/modal-summary-action-bar/modal-summary-action-bar-modal.component.ts
  apps/playground/src/app/components/action-bars/modal-summary-action-bar/modal-summary-action-bar.module.ts
  apps/playground/src/app/components/action-bars/summary-action-bar/summary-action-bar-modal.component.ts
  apps/playground/src/app/components/action-bars/summary-action-bar/summary-action-bar.module.ts
  apps/playground/src/app/components/ag-grid/data-manager/data-filter-modal.component.ts
  apps/playground/src/app/components/ag-grid/edit-complex-cells/custom-multiline/custom-multiline.component.ts
  apps/playground/src/app/components/ag-grid/edit-complex-cells/custom-multiline/custom-multiline.module.ts
  apps/playground/src/app/components/ag-grid/edit-complex-cells/edit-complex-cells-in-modal.component.ts
  apps/playground/src/app/components/ag-grid/edit-complex-cells/edit-complex-cells.component.ts
  apps/playground/src/app/components/ag-grid/edit-complex-cells/edit-complex-cells.module.ts
  apps/playground/src/app/components/ag-grid/edit-complex-cells/inline-help/inline-help.component.html
  apps/playground/src/app/components/ag-grid/edit-complex-cells/inline-help/inline-help.component.ts
  apps/playground/src/app/components/ag-grid/edit-in-modal-grid/ag-grid-edit-modal.component.ts
  apps/playground/src/app/components/ag-grid/edit-in-modal-grid/edit-in-modal-grid.module.ts
  apps/playground/src/app/components/ag-grid/readonly-grid/readonly-grid-context-menu.component.ts
  apps/playground/src/app/components/ag-grid/readonly-grid/readonly-grid-in-modal.component.ts
  apps/playground/src/app/components/ag-grid/readonly-grid/readonly-grid.component.ts
  apps/playground/src/app/components/ag-grid/readonly-grid/readonly-grid.module.ts
  apps/playground/src/app/components/core/resize-observer/flyout/resize-observer-content.component.ts
  apps/playground/src/app/components/core/resize-observer/flyout/resize-observer-flyout.module.ts
  apps/playground/src/app/components/core/resize-observer/modal/resize-observer-modal.component.ts
  apps/playground/src/app/components/core/resize-observer/modal/resize-observer-modal.module.ts
  apps/playground/src/app/components/flyout/flyout/flyout-demo.component.html
  apps/playground/src/app/components/flyout/flyout/flyout-demo.component.ts
  apps/playground/src/app/components/flyout/flyout/flyout-modal.component.ts
  apps/playground/src/app/components/flyout/flyout/flyout.module.ts
  apps/playground/src/app/components/lookup/lookup/lookup-custom-picker.component.ts
  apps/playground/src/app/components/lookup/lookup/lookup.module.ts
  apps/playground/src/app/components/modal/modal-close-confirm.component.ts
  apps/playground/src/app/components/modal/modal-content-autofocus.component.ts
  apps/playground/src/app/components/modal/modal-content-demo.component.ts
  apps/playground/src/app/components/modal/modal-demo.component.ts
  apps/playground/src/app/components/modal/modal-dirty.component.ts
  apps/playground/src/app/components/modal/modal-error.component.ts
  apps/playground/src/app/components/modal/modal-form-demo.component.ts
  apps/playground/src/app/components/modal/modal-full-page-demo.component.ts
  apps/playground/src/app/components/modal/modal-lookup.component.ts
  apps/playground/src/app/components/modal/modal-tiled-demo.component.ts
  apps/playground/src/app/components/modal/modal-visual.component.ts
  apps/playground/src/app/components/modal/modal-visual.module.ts
  apps/playground/src/app/components/pages/action-hub/action-hub.module.ts
  apps/playground/src/app/components/pages/action-hub/settings/modal/settings-modal.component.ts
  apps/playground/src/app/components/tabs/sectioned-form/sectioned-form-modal.component.ts
  apps/playground/src/app/components/tabs/vertical-tabset/vertical-tabset-modal.component.ts
  apps/playground/src/app/components/tabs/vertical-tabset/vertical-tabset.module.ts
  apps/playground/src/app/components/tabs/wizard/wizard-demo-modal.component.ts
  apps/playground/src/app/components/tabs/wizard/wizard-demo.module.ts
  apps/playground/src/app/components/tabs/wizard/wizard-dropdown-demo-modal.component.ts
  apps/playground/src/app/components/toast/toast/toast-body.component.ts
  apps/playground/src/app/components/toast/toast/toast.module.ts
  apps/playground/src/app/home/home-filter.component.ts
  apps/playground/src/app/home/home.module.ts
  apps/playground/src/app/shared/data-manager/data-manager-edit-modal.component.ts
  apps/playground/src/app/shared/data-manager/data-manager-filter-modal.component.ts
  apps/playground/src/app/shared/data-manager/data-manager.module.ts
  apps/playground/src/app/shared/lipsum/lipsum.component.ts
  apps/playground/src/app/shared/lipsum/lipsum.module.ts
Labels: risk level (author): 1, risk level (reviewer): 1

#1788 feat(components/datetime): datepicker calendar button aria label is now context specific
  libs/components/datetime/src/assets/locales/resources_en_US.json
  libs/components/datetime/src/lib/modules/datepicker/datepicker.component.html
  libs/components/datetime/src/lib/modules/datepicker/datepicker.component.spec.ts
  libs/components/datetime/src/lib/modules/datepicker/fixtures/datepicker-input-box.component.fixture.html
  libs/components/datetime/src/lib/modules/datepicker/fixtures/datepicker-input-box.component.fixture.ts
  libs/components/datetime/src/lib/modules/shared/sky-datetime-resources.module.ts
  libs/components/forms/src/lib/modules/input-box/input-box-host.service.spec.ts
  libs/components/forms/src/lib/modules/input-box/input-box-host.service.ts
Labels: risk level (author): 2

#1789 feat(components/datetime): timepicker button aria label is now context specific
  libs/components/datetime/src/assets/locales/resources_en_US.json
  libs/components/datetime/src/lib/modules/shared/sky-datetime-resources.module.ts
  libs/components/datetime/src/lib/modules/timepicker/fixtures/timepicker-input-box-component.fixture.html
  libs/components/datetime/src/lib/modules/timepicker/fixtures/timepicker-input-box-component.fixture.ts
  libs/components/datetime/src/lib/modules/timepicker/timepicker.component.html
  libs/components/datetime/src/lib/modules/timepicker/timepicker.component.spec.ts
Labels: risk level (author): 2

#1782 chore: release 9.5.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#1791 fix(components/forms): remove internal flag from character counter harness
  libs/components/forms/testing/src/character-counter/character-counter-indicator-harness.ts
Labels: risk level (author): 1

#1790 fix(components/core): prevent resize observer loop error
  apps/e2e/action-bars-storybook-e2e/src/e2e/summary-action-bar.component.cy.ts
  apps/e2e/pages-storybook-e2e/src/e2e/page-layout-blocks.component.cy.ts
  libs/components/core/src/lib/modules/resize-observer/fixtures/resize-observer-mock.ts
  libs/components/core/src/lib/modules/resize-observer/resize-observer-media-query.service.spec.ts
  libs/components/core/src/lib/modules/resize-observer/resize-observer-media-query.service.ts
  libs/components/core/src/lib/modules/resize-observer/resize-observer.service.spec.ts
  libs/components/core/src/lib/modules/resize-observer/resize-observer.service.ts
  libs/components/core/testing/src/resize-observer-mock.ts
Labels: risk level (author): 2

#1794 fix(components/core): prevent resize observer loop error (#1790)
  apps/e2e/action-bars-storybook-e2e/src/e2e/summary-action-bar.component.cy.ts
  apps/e2e/pages-storybook-e2e/src/e2e/page-layout-blocks.component.cy.ts
  libs/components/core/src/lib/modules/resize-observer/fixtures/resize-observer-mock.ts
  libs/components/core/src/lib/modules/resize-observer/resize-observer-media-query.service.spec.ts
  libs/components/core/src/lib/modules/resize-observer/resize-observer-media-query.service.ts
  libs/components/core/src/lib/modules/resize-observer/resize-observer.service.spec.ts
  libs/components/core/src/lib/modules/resize-observer/resize-observer.service.ts
  libs/components/core/testing/src/resize-observer-mock.ts
Labels: risk level (author): 2

#1798 fix(components/layout): fix action button responsive behavior in modals
  apps/e2e/layout-storybook-e2e/src/e2e/action-button.component.cy.ts
  apps/e2e/layout-storybook/src/app/action-button/action-button-modal.component.html
  apps/e2e/layout-storybook/src/app/action-button/action-button-modal.component.ts
  apps/e2e/layout-storybook/src/app/action-button/action-button.component.html
  apps/e2e/layout-storybook/src/app/action-button/action-button.component.ts
  apps/e2e/layout-storybook/src/app/action-button/action-button.module.ts
  apps/playground/src/app/components/layout/action-button/action-button-modal.component.html
  apps/playground/src/app/components/layout/action-button/action-button-modal.component.ts
  apps/playground/src/app/components/layout/action-button/action-button.component.html
  apps/playground/src/app/components/layout/action-button/action-button.component.ts
  libs/components/layout/src/lib/modules/action-button/action-button.component.scss
Labels: risk level (author): 3, risk level (reviewer): 3

#1797 feat(components/lookup): lookup show more modal native picker configurations include a `selectionDescriptor` which passes context to aria labels and the modal title
  apps/code-examples/src/app/code-examples/lookup/lookup/add-item/demo.component.html
  apps/code-examples/src/app/code-examples/lookup/lookup/add-item/demo.component.spec.ts
  apps/code-examples/src/app/code-examples/lookup/lookup/add-item/demo.component.ts
  apps/code-examples/src/app/code-examples/lookup/lookup/async/demo.component.html
  apps/code-examples/src/app/code-examples/lookup/lookup/async/demo.component.spec.ts
  apps/code-examples/src/app/code-examples/lookup/lookup/async/demo.component.ts
  apps/code-examples/src/app/code-examples/lookup/lookup/multi-select/demo.component.html
  apps/code-examples/src/app/code-examples/lookup/lookup/multi-select/demo.component.spec.ts
  apps/code-examples/src/app/code-examples/lookup/lookup/multi-select/demo.component.ts
  apps/code-examples/src/app/code-examples/lookup/lookup/result-templates/demo.component.spec.ts
  apps/code-examples/src/app/code-examples/lookup/lookup/result-templates/demo.component.ts
  apps/code-examples/src/app/code-examples/lookup/lookup/single-select/demo.component.html
  apps/code-examples/src/app/code-examples/lookup/lookup/single-select/demo.component.spec.ts
  apps/code-examples/src/app/code-examples/lookup/lookup/single-select/demo.component.ts
  apps/code-examples/tsconfig.editor.json
  libs/components/data-manager/src/lib/modules/data-manager/models/data-manager-config.ts
  libs/components/layout/src/lib/modules/toolbar/toolbar.component.ts
  libs/components/lookup/src/assets/locales/resources_en_US.json
  libs/components/lookup/src/lib/modules/lookup/lookup-show-more-modal.component.html
  libs/components/lookup/src/lib/modules/lookup/lookup.component.spec.ts
  libs/components/lookup/src/lib/modules/lookup/lookup.component.ts
  libs/components/lookup/src/lib/modules/lookup/types/lookup-show-more-native-picker-config.ts
  libs/components/lookup/src/lib/modules/selection-modal/types/selection-modal-open-args.ts
  libs/components/lookup/src/lib/modules/shared/sky-lookup-resources.module.ts
  libs/components/lookup/testing/src/lookup/fixtures/lookup-harness-test.component.html
  libs/components/lookup/testing/src/lookup/fixtures/lookup-harness-test.component.ts
  libs/components/lookup/testing/src/lookup/lookup-harness.spec.ts
  libs/components/tiles/src/lib/modules/tiles/tile/tile.component.ts
Labels: risk level (author): 2

#1799 fix(components/lookup): autocomplete position in modal with omnibar
  apps/integration-e2e/src/e2e/lookup-in-modal.cy.ts
  apps/integration/src/app/integrations/integrations.module.ts
  apps/integration/src/app/integrations/lookup-in-modal/lookup-in-modal.component.spec.ts
  apps/integration/src/app/integrations/lookup-in-modal/lookup-in-modal.component.ts
  apps/integration/src/app/integrations/lookup-in-modal/lookup-in-modal.module.ts
  apps/integration/src/app/integrations/lookup-in-modal/modal-lookup.component.html
  apps/integration/src/app/integrations/lookup-in-modal/modal-lookup.component.spec.ts
  apps/integration/src/app/integrations/lookup-in-modal/modal-lookup.component.ts
  libs/components/core/src/lib/modules/affix/affixer.ts
  libs/components/core/src/lib/modules/affix/dom-utils.ts
  libs/components/lookup/src/lib/modules/autocomplete/autocomplete.component.ts
Labels: risk level (author): 2, risk level (reviewer): 3

#1795 chore: release 8.10.6
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease 8.x.x: pending

#1803 chore: release 8.10.6 (#1795)
  CHANGELOG.md
Labels: risk level (author): 1, risk level (reviewer): 1

#1805 chore: ensure `test:affected` script matches what the CI workflow runs for cache purposes
  package.json
Labels: risk level (author): 1

#1802 fix(components/forms): toggle switch buttons will no point to the visible label via `aria-labelledby` when the `ariaLabel` input is given
  apps/code-examples/src/app/code-examples/forms/toggle-switch/basic/demo.component.html
  apps/code-examples/src/app/code-examples/forms/toggle-switch/inline-help/demo.component.html
  libs/components/forms/src/lib/modules/toggle-switch/toggle-switch.component.html
  libs/components/forms/src/lib/modules/toggle-switch/toggle-switch.component.spec.ts
Labels: risk level (author): 1

#1801 fix(components/lookup): autocomplete position in modal with omnibar (#1799)
  apps/e2e/lookup-storybook-e2e/src/e2e/autocomplete.component.cy.ts
  apps/e2e/lookup-storybook-e2e/src/e2e/country-field.component.cy.ts
  apps/e2e/lookup-storybook-e2e/src/e2e/lookup.component.cy.ts
  apps/e2e/lookup-storybook-e2e/src/e2e/search.component.cy.ts
  apps/e2e/lookup-storybook/src/app/autocomplete/autocomplete.component.html
  apps/e2e/lookup-storybook/src/app/autocomplete/autocomplete.component.ts
  apps/e2e/lookup-storybook/src/app/country-field/country-field.component.html
  apps/e2e/lookup-storybook/src/app/country-field/country-field.component.scss
  apps/e2e/lookup-storybook/src/app/country-field/country-field.component.ts
  apps/e2e/lookup-storybook/src/app/lookup/lookup.component.html
  apps/e2e/lookup-storybook/src/app/lookup/lookup.component.ts
  apps/e2e/lookup-storybook/src/app/search/search.component.html
  apps/e2e/lookup-storybook/src/app/search/search.component.scss
  apps/e2e/lookup-storybook/src/app/search/search.component.ts
  apps/integration-e2e/src/e2e/lookup-in-modal.cy.ts
  apps/integration/src/app/integrations/integrations.module.ts
  apps/integration/src/app/integrations/lookup-in-modal/lookup-in-modal.component.spec.ts
  apps/integration/src/app/integrations/lookup-in-modal/lookup-in-modal.component.ts
  apps/integration/src/app/integrations/lookup-in-modal/lookup-in-modal.module.ts
  apps/integration/src/app/integrations/lookup-in-modal/modal-lookup.component.html
  apps/integration/src/app/integrations/lookup-in-modal/modal-lookup.component.spec.ts
  apps/integration/src/app/integrations/lookup-in-modal/modal-lookup.component.ts
  libs/components/core/src/lib/modules/affix/affixer.ts
  libs/components/core/src/lib/modules/affix/dom-utils.ts
  libs/components/lookup/src/lib/modules/autocomplete/autocomplete.component.ts
Labels: risk level (author): 2, risk level (reviewer): 3

#1796 chore: release 9.6.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#1807 ci: set e2e checkout repository
  .github/workflows/e2e.yml
Labels: risk level (author): 1, risk level (reviewer): 1

#1809 chore: update design-tokens
  libs/components/theme/package.json
  package-lock.json
  package.json
Labels: risk level (author): 1

#1804 feat(components/config): add referenced remote module config
  libs/components/config/src/index.ts
  libs/components/config/src/lib/config-remote-container-reference.ts
  libs/components/config/src/lib/config-remote-modules.ts
  libs/components/config/src/lib/config.ts
Labels: risk level (author): 2, risk level (reviewer): 2

#1811 feat: add support for `@angular/core@16.2.9`
  libs/components/a11y/package.json
  libs/components/action-bars/package.json
  libs/components/ag-grid/package.json
  libs/components/angular-tree-component/package.json
  libs/components/animations/package.json
  libs/components/assets/package.json
  libs/components/autonumeric/package.json
  libs/components/avatar/package.json
  libs/components/colorpicker/package.json
  libs/components/config/package.json
  libs/components/core/package.json
  libs/components/data-manager/package.json
  libs/components/datetime/package.json
  libs/components/errors/package.json
  libs/components/flyout/package.json
  libs/components/forms/package.json
  libs/components/grids/package.json
  libs/components/http/package.json
  libs/components/i18n/package.json
  libs/components/indicators/package.json
  libs/components/inline-form/package.json
  libs/components/layout/package.json
  libs/components/list-builder-common/package.json
  libs/components/list-builder-view-checklist/package.json
  libs/components/list-builder-view-grids/package.json
  libs/components/list-builder/package.json
  libs/components/lists/package.json
  libs/components/lookup/package.json
  libs/components/modals/package.json
  libs/components/navbar/package.json
  libs/components/omnibar-interop/package.json
  libs/components/packages/package.json
  libs/components/pages/package.json
  libs/components/phone-field/package.json
  libs/components/popovers/package.json
  libs/components/progress-indicator/package.json
  libs/components/router/package.json
  libs/components/select-field/package.json
  libs/components/split-view/package.json
  libs/components/storybook/package.json
  libs/components/tabs/package.json
  libs/components/text-editor/package.json
  libs/components/theme/package.json
  libs/components/tiles/package.json
  libs/components/toast/package.json
  libs/components/validation/package.json
  libs/sdk/e2e-schematics/package.json
  libs/sdk/eslint-config/package.json
  libs/sdk/prettier-schematics/package.json
  libs/sdk/testing/package.json
  package-lock.json
  package.json
Labels: risk level (author): 2, risk level (reviewer): 2

#1800 feat(components/router): add `queryParams` to `skyHref` directive
  libs/components/config/src/lib/params.spec.ts
  libs/components/config/src/lib/params.ts
  libs/components/router/src/lib/modules/href/fixtures/href-resolver-fixture.service.ts
  libs/components/router/src/lib/modules/href/href.directive.spec.ts
  libs/components/router/src/lib/modules/href/href.directive.ts
Labels: risk level (author): 3, risk level (reviewer): 3

#1818 ci: set e2e checkout repository from event
  .github/workflows/e2e.yml
Labels: risk level (author): 1

#1820 ci: set e2e checkout repository from event
  .github/workflows/e2e.yml
Labels: risk level (author): 1

#1817 chore: update cypress config to use larger headless window (#1816)
  apps/e2e/a11y-storybook-e2e/cypress.config.ts
  apps/e2e/action-bars-storybook-e2e/cypress.config.ts
  apps/e2e/ag-grid-storybook-e2e/cypress.config.ts
  apps/e2e/datetime-storybook-e2e/cypress.config.ts
  apps/e2e/forms-storybook-e2e/src/e2e/selection-box.component.cy.ts
  apps/e2e/forms-storybook/src/app/selection-box/selection-box.component.scss
  apps/e2e/popovers-storybook-e2e/src/e2e/popover.component.cy.ts
  apps/e2e/popovers-storybook/src/app/popover/popover.component.html
  apps/e2e/popovers-storybook/src/app/popover/popover.component.scss
  apps/e2e/popovers-storybook/src/app/popover/popover.component.ts
  apps/integration-e2e/cypress.config.ts
  libs/sdk/e2e-schematics/src/cypress-preset.ts
Labels: risk level (author): 1

#1824 ci: fix node events on cypress preset
  apps/integration-e2e/src/e2e/lookup-in-modal.cy.ts
  libs/sdk/e2e-schematics/src/cypress-preset.ts
Labels: risk level (author): 1, risk level (reviewer): 1

#1825 ci: fix node events on cypress preset (#1824)
  apps/integration-e2e/src/e2e/lookup-in-modal.cy.ts
Labels: risk level (author): 1, risk level (reviewer): 1

#1814 feat(components/router): add `queryParams` to `skyHref` directive (#1800)
  libs/components/config/src/index.ts
  libs/components/config/src/lib/params.spec.ts
  libs/components/config/src/lib/params.ts
  libs/components/config/src/lib/types/get-link-url-options.ts
  libs/components/config/src/lib/types/query-params.ts
  libs/components/router/src/index.ts
  libs/components/router/src/lib/modules/href/fixtures/href-fixture.component.html
  libs/components/router/src/lib/modules/href/fixtures/href-fixture.component.ts
  libs/components/router/src/lib/modules/href/fixtures/href-resolver-fixture.service.ts
  libs/components/router/src/lib/modules/href/href-query-params.ts
  libs/components/router/src/lib/modules/href/href.directive.spec.ts
  libs/components/router/src/lib/modules/href/href.directive.ts
  libs/components/router/src/lib/modules/href/types/href-query-params.ts
Labels: risk level (author): 3, risk level (reviewer): 3

#1812 chore: release 9.7.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#1827 feat(components/theme): update modern border styles for `sky-switch-control`
  libs/components/theme/src/lib/styles/_switch.scss
  libs/components/theme/src/lib/styles/themes/modern/_custom-properties.scss
  libs/components/theme/src/lib/styles/themes/modern/_switch.scss
Labels: risk level (author): 1, risk level (reviewer): 1

#1829 fix(components/config): update `queryParams` handling to ensure params can be optional
  libs/components/config/src/lib/params.spec.ts
  libs/components/config/src/lib/params.ts
  libs/components/config/src/lib/types/query-params.ts
  libs/components/router/src/lib/modules/href/href.directive.spec.ts
  libs/components/router/src/lib/modules/href/types/href-query-params.ts
Labels: risk level (author): 1, risk level (reviewer): 1

#1806 fix(components/forms): toggle switch `ariaLabel` input gives info on when to be contextual
  apps/code-examples/src/app/code-examples/forms/toggle-switch/basic/demo.component.html
  apps/code-examples/src/app/code-examples/forms/toggle-switch/inline-help/demo.component.html
  libs/components/forms/src/lib/modules/toggle-switch/toggle-switch.component.ts
Labels: risk level (author): 1

#1834 feat(components/colorpicker): update modern border styles for color picker
  libs/components/colorpicker/src/lib/modules/colorpicker/colorpicker.component.scss
Labels: risk level (author): 1

#1835 feat(components/forms): update modern border styles for toggle switch
  libs/components/forms/src/lib/modules/toggle-switch/toggle-switch.component.scss
Labels: risk level (author): 1

#1836 feat(components/progress-indicator): update modern border styles for progress indicators
  libs/components/progress-indicator/src/lib/modules/progress-indicator/progress-indicator-status-marker/progress-indicator-status-marker.component.scss
Labels: risk level (author): 1

#1837 feat(components/forms): add `hintText` to input box
  apps/e2e/forms-storybook/src/app/input-box/input-box.component.html
  apps/playground/src/app/components/datetime/datepicker/datepicker.component.html
  apps/playground/src/app/components/datetime/datetime.module.ts
  apps/playground/src/app/components/datetime/timepicker/routes.ts
  apps/playground/src/app/components/datetime/timepicker/timepicker-routing.module.ts
  apps/playground/src/app/components/datetime/timepicker/timepicker.component.html
  apps/playground/src/app/components/datetime/timepicker/timepicker.component.ts
  apps/playground/src/app/components/forms/input-box/input-box.component.html
  apps/playground/src/app/components/lookup/country-field/country-field.component.html
  apps/playground/src/app/components/lookup/lookup/lookup.component.html
  apps/playground/src/app/components/phone-field/phone-field/phone-field.component.html
  libs/components/forms/src/lib/modules/input-box/fixtures/input-box.component.fixture.html
  libs/components/forms/src/lib/modules/input-box/fixtures/input-box.component.fixture.ts
  libs/components/forms/src/lib/modules/input-box/input-box-adapter.service.ts
  libs/components/forms/src/lib/modules/input-box/input-box-host.service.spec.ts
  libs/components/forms/src/lib/modules/input-box/input-box-host.service.ts
  libs/components/forms/src/lib/modules/input-box/input-box.component.html
  libs/components/forms/src/lib/modules/input-box/input-box.component.scss
  libs/components/forms/src/lib/modules/input-box/input-box.component.spec.ts
  libs/components/forms/src/lib/modules/input-box/input-box.component.ts
  libs/components/forms/testing/src/input-box/fixtures/input-box-harness-test.component.html
  libs/components/forms/testing/src/input-box/fixtures/input-box-harness-test.component.ts
  libs/components/forms/testing/src/input-box/input-box-harness.spec.ts
  libs/components/forms/testing/src/input-box/input-box-harness.ts
  libs/components/lookup/src/lib/modules/country-field/country-field.component.html
  libs/components/lookup/src/lib/modules/country-field/country-field.component.spec.ts
  libs/components/lookup/src/lib/modules/country-field/country-field.component.ts
  libs/components/lookup/src/lib/modules/country-field/fixtures/country-field-input-box.component.fixture.html
  libs/components/lookup/src/lib/modules/country-field/fixtures/country-field-input-box.component.fixture.ts
  libs/components/lookup/src/lib/modules/lookup/fixtures/lookup-input-box.component.fixture.html
  libs/components/lookup/src/lib/modules/lookup/fixtures/lookup-input-box.component.fixture.ts
  libs/components/lookup/src/lib/modules/lookup/lookup.component.html
  libs/components/lookup/src/lib/modules/lookup/lookup.component.spec.ts
  libs/components/lookup/src/lib/modules/lookup/lookup.component.ts
Labels: risk level (author): 3, risk level (reviewer): 2

#1832 chore: release 9.8.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#1838 ci: turn off azure sync bypass
  .github/workflows/skyux-azboards.yml
Labels: risk level (author): 1

#1826 feat(components/layout): automatically set box context menu aria label
  apps/playground/src/app/components/layout/box/box.component.html
  libs/components/layout/src/lib/modules/box/box-header-id-token.ts
  libs/components/layout/src/lib/modules/box/box-header.component.html
  libs/components/layout/src/lib/modules/box/box-header.component.ts
  libs/components/layout/src/lib/modules/box/box.component.spec.ts
  libs/components/layout/src/lib/modules/box/box.component.ts
  libs/components/layout/src/lib/modules/box/fixtures/box.component.fixture.html
  libs/components/layout/src/lib/modules/box/fixtures/box.module.fixture.ts
Labels: risk level (author): 2

#1840 chore: release 9.9.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#1843 feat(components/config): add `allowDynamicLoading` to remote module config
  libs/components/config/src/lib/config-remote-modules.ts
Labels: risk level (author): 1, risk level (reviewer): 1

#1842 fix(code-examples): add `sky-switch-icon-group` CSS class to icon radio group code example
  apps/code-examples/src/app/code-examples/forms/radio/icon/demo.component.html
  apps/playground/src/app/components/forms/radio/radio.component.html
Labels: risk level (author): 1

#1844 feat(components/text-editor): add options to 'Create link' (#1808)
  apps/playground/src/app/components/text-editor/text-editor/text-editor.component.html
  apps/playground/src/app/components/text-editor/text-editor/text-editor.component.ts
  libs/components/text-editor/src/assets/locales/resources_en_US.json
  libs/components/text-editor/src/index.ts
  libs/components/text-editor/src/lib/modules/shared/sky-text-editor-resources.module.ts
  libs/components/text-editor/src/lib/modules/text-editor/defaults/link-window-options-defaults.ts
  libs/components/text-editor/src/lib/modules/text-editor/fixtures/text-editor.component.fixture.html
  libs/components/text-editor/src/lib/modules/text-editor/fixtures/text-editor.component.fixture.ts
  libs/components/text-editor/src/lib/modules/text-editor/text-editor.component.html
  libs/components/text-editor/src/lib/modules/text-editor/text-editor.component.spec.ts
  libs/components/text-editor/src/lib/modules/text-editor/text-editor.component.ts
  libs/components/text-editor/src/lib/modules/text-editor/toolbar/text-editor-toolbar.component.ts
  libs/components/text-editor/src/lib/modules/text-editor/types/link-window-options-type.ts
  libs/components/text-editor/src/lib/modules/text-editor/url-modal/text-editor-url-modal-context.ts
  libs/components/text-editor/src/lib/modules/text-editor/url-modal/text-editor-url-modal.component.html
  libs/components/text-editor/src/lib/modules/text-editor/url-modal/text-editor-url-modal.component.ts
Labels: risk level (author): 2

#1847 chore: update `@trivago/prettier-plugin-sort-imports` to fix vulnerability
  package-lock.json
  package.json
Labels: risk level (author): 1

#1845 chore: release 9.10.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#1743 feat(components/lists): repeater item context menu aria labels are automatically item specific
  apps/code-examples/src/app/code-examples/lists/repeater/basic/demo.component.html
  apps/code-examples/src/app/code-examples/lists/repeater/basic/demo.component.spec.ts
  apps/code-examples/src/app/code-examples/lists/repeater/basic/demo.component.ts
  apps/playground/src/app/components/lists/repeater/repeater-visual.component.html
  libs/components/data-manager/src/lib/modules/data-manager/data-manager-toolbar/data-manager-toolbar.component.spec.ts
  libs/components/lists/src/lib/modules/repeater/fixtures/repeater.component.fixture.html
  libs/components/lists/src/lib/modules/repeater/fixtures/repeater.component.fixture.ts
  libs/components/lists/src/lib/modules/repeater/repeater-item.component.html
  libs/components/lists/src/lib/modules/repeater/repeater-item.component.ts
  libs/components/lists/src/lib/modules/repeater/repeater.component.spec.ts
  libs/components/lists/src/lib/modules/repeater/repeater.module.ts
  libs/components/lists/src/lib/modules/sort/sort.component.spec.ts
  libs/components/popovers/src/lib/modules/dropdown/dropdown.component.html
Labels: risk level (author): 3

#1850 fix(components/ag-grid): specify tooltip background color
  libs/components/ag-grid/src/lib/styles/_base.scss
Labels: risk level (author): 1

#1841 feat(components/forms): file attachment component announces state changes to screen readers
  .gitignore
  apps/playground/src/app/components/forms/file-attachment/file-attachment.component.html
  apps/playground/src/app/components/forms/file-attachment/file-attachment.component.ts
  libs/components/forms/src/assets/locales/resources_en_US.json
  libs/components/forms/src/lib/modules/file-attachment/file-drop.component.spec.ts
  libs/components/forms/src/lib/modules/file-attachment/file-drop.component.ts
  libs/components/forms/src/lib/modules/file-attachment/file-item.component.spec.ts
  libs/components/forms/src/lib/modules/file-attachment/file-item.component.ts
  libs/components/forms/src/lib/modules/shared/sky-forms-resources.module.ts
Labels: risk level (author): 2

#1848 chore: update CONTRIBUTING.md with information from public site
  CONTRIBUTING.md
Labels: risk level (author): 1

#1813 fix(components/lookup): autocomplete position with nested overflow elements
  apps/e2e/colorpicker-storybook-e2e/src/e2e/colorpicker.component.cy.ts
  apps/e2e/colorpicker-storybook/src/app/colorpicker/colorpicker.component.html
  apps/e2e/colorpicker-storybook/src/app/colorpicker/colorpicker.component.scss
  apps/e2e/colorpicker-storybook/src/app/colorpicker/colorpicker.component.ts
  apps/e2e/core-storybook-e2e/cypress.config.ts
  apps/e2e/core-storybook-e2e/src/e2e/affix.component.cy.ts
  apps/e2e/core-storybook-e2e/src/support/commands.ts
  apps/e2e/core-storybook/src/app/affix/affix.component.html
  apps/e2e/core-storybook/src/app/affix/affix.component.scss
  apps/e2e/core-storybook/src/app/affix/affix.component.stories.ts
  apps/e2e/core-storybook/src/app/affix/affix.component.ts
  apps/e2e/core-storybook/src/app/affix/affix.module.ts
  apps/e2e/core-storybook/src/app/app.module.ts
  apps/e2e/datetime-storybook-e2e/src/e2e/datepicker.component.cy.ts
  apps/e2e/datetime-storybook-e2e/src/e2e/timepicker.component.cy.ts
  apps/e2e/layout-storybook-e2e/src/e2e/box.component.cy.ts
  apps/e2e/layout-storybook/src/app/box/box.component.html
  apps/e2e/layout-storybook/src/app/box/box.component.ts
  apps/e2e/lookup-storybook/src/app/lookup/lookup.component.scss
  apps/e2e/popovers-storybook-e2e/src/e2e/popover.component.cy.ts
  apps/e2e/popovers-storybook/src/app/popover/popover.component.html
  apps/e2e/popovers-storybook/src/app/popover/popover.component.scss
  apps/e2e/popovers-storybook/src/app/popover/popover.component.ts
  libs/components/core/src/lib/modules/affix/affix.directive.spec.ts
  libs/components/core/src/lib/modules/affix/affix.service.ts
  libs/components/core/src/lib/modules/affix/affixer.spec.ts
  libs/components/core/src/lib/modules/affix/affixer.ts
  libs/components/core/src/lib/modules/affix/dom-utils.ts
  libs/components/core/src/lib/modules/affix/fixtures/affix.component.fixture.scss
  libs/components/core/src/lib/modules/dynamic-component/dynamic-component.service.ts
  libs/components/lookup/src/lib/modules/autocomplete/autocomplete.component.scss
  libs/components/lookup/src/lib/modules/autocomplete/autocomplete.component.spec.ts
  libs/components/lookup/src/lib/modules/autocomplete/autocomplete.component.ts
  libs/components/storybook/src/lib/preview-wrapper/preview-wrapper.component.scss
  libs/components/tabs/src/lib/modules/tabs/tabset.component.spec.ts
  libs/components/theme/src/lib/styles/_modals.scss
Labels: risk level (author): 4, risk level (reviewer): 4

#1851 chore: release 8.10.7
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease 8.x.x: pending

#1854 chore: release 8.10.7 (#1851)
  CHANGELOG.md
Labels: risk level (author): 1, risk level (reviewer): 1

#1853 fix(components/lookup): autocomplete position with nested overflow elements (#1813)
  apps/e2e/colorpicker-storybook-e2e/src/e2e/colorpicker.component.cy.ts
  apps/e2e/colorpicker-storybook/src/app/colorpicker/colorpicker.component.html
  apps/e2e/colorpicker-storybook/src/app/colorpicker/colorpicker.component.scss
  apps/e2e/colorpicker-storybook/src/app/colorpicker/colorpicker.component.ts
  apps/e2e/core-storybook-e2e/cypress.config.ts
  apps/e2e/core-storybook-e2e/src/e2e/affix.component.cy.ts
  apps/e2e/core-storybook-e2e/src/support/commands.ts
  apps/e2e/core-storybook/src/app/affix/affix.component.html
  apps/e2e/core-storybook/src/app/affix/affix.component.scss
  apps/e2e/core-storybook/src/app/affix/affix.component.stories.ts
  apps/e2e/core-storybook/src/app/affix/affix.component.ts
  apps/e2e/core-storybook/src/app/affix/affix.module.ts
  apps/e2e/core-storybook/src/app/app.module.ts
  apps/e2e/datetime-storybook-e2e/src/e2e/datepicker.component.cy.ts
  apps/e2e/datetime-storybook-e2e/src/e2e/timepicker.component.cy.ts
  apps/e2e/layout-storybook-e2e/src/e2e/box.component.cy.ts
  apps/e2e/layout-storybook/src/app/box/box.component.html
  apps/e2e/layout-storybook/src/app/box/box.component.ts
  apps/e2e/lookup-storybook/src/app/lookup/lookup.component.scss
  apps/e2e/popovers-storybook-e2e/src/e2e/popover.component.cy.ts
  libs/components/core/src/lib/modules/affix/affix.directive.spec.ts
  libs/components/core/src/lib/modules/affix/affix.service.ts
  libs/components/core/src/lib/modules/affix/affixer.spec.ts
  libs/components/core/src/lib/modules/affix/affixer.ts
  libs/components/core/src/lib/modules/affix/dom-utils.ts
  libs/components/core/src/lib/modules/affix/fixtures/affix.component.fixture.scss
  libs/components/core/src/lib/modules/dynamic-component/dynamic-component.service.ts
  libs/components/lookup/src/lib/modules/autocomplete/autocomplete.component.scss
  libs/components/lookup/src/lib/modules/autocomplete/autocomplete.component.spec.ts
  libs/components/lookup/src/lib/modules/autocomplete/autocomplete.component.ts
  libs/components/storybook/src/lib/preview-wrapper/preview-wrapper.component.scss
  libs/components/tabs/src/lib/modules/tabs/tabset.component.spec.ts
  libs/components/theme/src/lib/styles/_modals.scss
Labels: risk level (author): 4, risk level (reviewer): 4

#1849 chore: release 9.11.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#1855 feat(components/forms): single file attachment component announces state changes to screen readers
  libs/components/forms/src/assets/locales/resources_en_US.json
  libs/components/forms/src/lib/modules/file-attachment/file-attachment.component.spec.ts
  libs/components/forms/src/lib/modules/file-attachment/file-attachment.component.ts
  libs/components/forms/src/lib/modules/shared/sky-forms-resources.module.ts
Labels: risk level (author): 2

#1858 fix(components/lookup): fit lookup dropdown to viewport
  libs/components/lookup/src/lib/modules/autocomplete/autocomplete.component.ts
Labels: risk level (author): 1

#1860 chore: release 8.10.8
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease 8.x.x: pending

#1859 fix(components/lookup): fit lookup dropdown to viewport (#1858)
  libs/components/lookup/src/lib/modules/autocomplete/autocomplete.component.ts
Labels: risk level (author): 1

#1862 chore: release 9.12.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#1863 ci: update dev-infra to 9.0.0-alpha.15
  package-lock.json
  package.json
Labels: risk level (author): 1

#1867 ci: fix author for cherry pick
  .github/workflows/cherry-pick.yml
Labels: risk level (author): 1
