Repository blackbaud/skyux, pull requests merged in 2023-04, with the labels that each got.

#1203 fix(components/forms): single file attachment emits the file when a file is removed
  libs/components/forms/src/lib/modules/file-attachment/file-attachment.component.spec.ts
  libs/components/forms/src/lib/modules/file-attachment/file-attachment.component.ts
Labels: risk level (author): 2, risk level (reviewer): 2

#1205 revert: fix(components/forms): single file attachment emits the file when a file is removed (#1203)
  libs/components/forms/src/lib/modules/file-attachment/file-attachment.component.spec.ts
  libs/components/forms/src/lib/modules/file-attachment/file-attachment.component.ts
Labels: risk level (author): 1

#1201 feat(components/tabs): address incorrect tab spacing in modals
  libs/components/packages/src/schematics/migrations/update-8/add-compat-stylesheets/add-compat-stylesheets.ts
  libs/components/tabs/src/lib/modules/tabs/tabset.component.scss
  package-lock.json
Labels: risk level (author): 2, risk level (reviewer): 2

#1182 feat(components/lists): repeater visual tests
  apps/e2e/lists-storybook-e2e/.eslintrc.json
  apps/e2e/lists-storybook-e2e/cypress.config.ts
  apps/e2e/lists-storybook-e2e/project.json
  apps/e2e/lists-storybook-e2e/src/e2e/.gitkeep
  apps/e2e/lists-storybook-e2e/src/e2e/repeater.component.cy.ts
  apps/e2e/lists-storybook-e2e/src/support/commands.ts
  apps/e2e/lists-storybook-e2e/src/support/e2e.ts
  apps/e2e/lists-storybook-e2e/tsconfig.json
  apps/e2e/lists-storybook/.browserslistrc
  apps/e2e/lists-storybook/.eslintrc.json
  apps/e2e/lists-storybook/.storybook/main.ts
  apps/e2e/lists-storybook/.storybook/manager.ts
  apps/e2e/lists-storybook/.storybook/preview.ts
  apps/e2e/lists-storybook/.storybook/tsconfig.json
  apps/e2e/lists-storybook/jest.config.ts
  apps/e2e/lists-storybook/project.json
  apps/e2e/lists-storybook/src/app/app.component.ts
  apps/e2e/lists-storybook/src/app/app.module.ts
  apps/e2e/lists-storybook/src/app/app.routes.ts
  apps/e2e/lists-storybook/src/app/repeater/repeater.component.html
  apps/e2e/lists-storybook/src/app/repeater/repeater.component.scss
  apps/e2e/lists-storybook/src/app/repeater/repeater.component.spec.ts
  apps/e2e/lists-storybook/src/app/repeater/repeater.component.stories.ts
  apps/e2e/lists-storybook/src/app/repeater/repeater.component.ts
  apps/e2e/lists-storybook/src/app/repeater/repeater.module.ts
  apps/e2e/lists-storybook/src/environments/environment.prod.ts
  apps/e2e/lists-storybook/src/environments/environment.ts
  apps/e2e/lists-storybook/src/index.html
  apps/e2e/lists-storybook/src/main.ts
  apps/e2e/lists-storybook/src/polyfills.ts
  apps/e2e/lists-storybook/src/styles.scss
  apps/e2e/lists-storybook/src/test-setup.ts
  apps/e2e/lists-storybook/tsconfig.app.json
  apps/e2e/lists-storybook/tsconfig.editor.json
  apps/e2e/lists-storybook/tsconfig.json
  apps/e2e/lists-storybook/tsconfig.spec.json
  workspace.json
Labels: risk level (author): 1

#1202 feat(components/layout): update back-to-top styles
  libs/components/layout/src/lib/modules/back-to-top/back-to-top.component.html
  libs/components/layout/src/lib/modules/back-to-top/back-to-top.component.scss
  libs/components/layout/src/lib/modules/back-to-top/back-to-top.module.ts
Labels: risk level (reviewer): 1

#1204 chore: release 8.0.0-alpha.16
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#1196 feat(components/lists): repeater test harness
  libs/components/indicators/testing/src/chevron/chevron-harness.spec.ts
  libs/components/indicators/testing/src/chevron/chevron-harness.ts
  libs/components/indicators/testing/src/public-api.ts
  libs/components/lists/testing/src/repeater/fixtures/repeater-harness-test.component.html
  libs/components/lists/testing/src/repeater/fixtures/repeater-harness-test.component.ts
  libs/components/lists/testing/src/repeater/repeater-harness.spec.ts
  libs/components/lists/testing/src/repeater/repeater-item-harness.ts
Labels: risk level (author): 1, risk level (reviewer): 1

#1200 test(apps/integration): add tests for lazy loaded modules
  .github/workflows/e2e.yml
  apps/integration-e2e/cypress.config.ts
  apps/integration-e2e/project.json
  apps/integration-e2e/src/e2e/modal-viewkept-toolbars.cy.ts
  apps/integration-e2e/src/e2e/vertical-tabset-back-to-top.cy.ts
  apps/integration-e2e/src/e2e/viewkeeper-tabset.cy.ts
  apps/integration-e2e/src/support/commands.ts
  apps/integration/src/app/app.module.ts
  apps/integration/src/app/integrations/modal-viewkept-toolbars/modal-viewkept-toolbars-modal.component.html
  apps/integration/src/app/integrations/modal-viewkept-toolbars/modal-viewkept-toolbars.component.spec.ts
  apps/integration/src/app/integrations/modal-viewkept-toolbars/modal-viewkept-toolbars.module.ts
  apps/integration/src/app/integrations/viewkeeper-tabset/viewkeeper-tabset.component.html
  apps/integration/src/assets/locales/resources_en_US.json
Labels: risk level (author): 1

#1185 fix: update `sky-emphasized` style class to `sky-font-emphasized`
  apps/playground/src/app/components/datetime/date-pipe/basic/date-pipe.component.html
  libs/components/lists/src/lib/modules/repeater/repeater-item.component.html
  libs/components/lists/src/lib/modules/sort/sort-item.component.html
  libs/components/modals/src/lib/modules/confirm/confirm.component.html
  libs/components/modals/src/lib/modules/modal/modal-header.component.html
  libs/components/pages/src/lib/modules/needs-attention/needs-attention.component.html
  libs/components/popovers/src/lib/modules/popover/popover-content.component.html
  libs/components/tabs/src/lib/modules/vertical-tabset/vertical-tabset-group.component.html
Labels: risk level (author): 2, risk level (author): 3

#1212 deprecation(components/indicators): deprecate use of alert without descriptionType
  libs/components/indicators/src/lib/modules/alert/alert.component.spec.ts
  libs/components/indicators/src/lib/modules/alert/alert.component.ts
  libs/components/indicators/src/lib/modules/alert/fixtures/alert.component.fixture.ts
Labels: risk level (author): 1

#1181 feat(components/modals): modal visual test
  NX
  apps/e2e/modals-storybook-e2e/src/e2e/modal.component.cy.ts
  apps/e2e/modals-storybook/src/app/app.module.ts
  apps/e2e/modals-storybook/src/app/modal/modal.component.html
  apps/e2e/modals-storybook/src/app/modal/modal.component.scss
  apps/e2e/modals-storybook/src/app/modal/modal.component.spec.ts
  apps/e2e/modals-storybook/src/app/modal/modal.component.stories.ts
  apps/e2e/modals-storybook/src/app/modal/modal.component.ts
  apps/e2e/modals-storybook/src/app/modal/modal.module.ts
  apps/e2e/modals-storybook/src/app/modal/modals/modal-basic.component.html
  apps/e2e/modals-storybook/src/app/modal/modals/modal-basic.component.ts
Labels: risk level (author): 1, risk level (reviewer): 1

#1207 chore: release 7.15.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease 7.x.x: pending

#1219 fix(components/lists): don't animate repeater items collapsing on initial render
  libs/components/lists/src/lib/modules/repeater/repeater-item.component.html
  libs/components/lists/src/lib/modules/repeater/repeater-item.component.ts
  libs/components/lists/src/lib/modules/repeater/repeater.component.spec.ts
  libs/components/lists/src/lib/modules/repeater/repeater.component.ts
Labels: risk level (reviewer): 3

#1218 chore: release 8.0.0-alpha.17
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#1224 chore: release 8.0.0-alpha.18
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#1222 chore: release 7.16.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease 7.x.x: pending

#1225 feat(components/indicators): add ability to set aria controls and expanded states on the help inline component
  apps/playground/src/app/components/indicators/help-inline/help-inline.component.html
  apps/playground/src/app/components/indicators/help-inline/help-inline.component.ts
  apps/playground/src/app/components/indicators/help-inline/help-inline.module.ts
  libs/components/indicators/src/lib/modules/help-inline/fixtures/help-inline.component.fixture.html
  libs/components/indicators/src/lib/modules/help-inline/fixtures/help-inline.component.fixture.ts
  libs/components/indicators/src/lib/modules/help-inline/help-inline-aria-expanded.pipe.ts
  libs/components/indicators/src/lib/modules/help-inline/help-inline.component.html
  libs/components/indicators/src/lib/modules/help-inline/help-inline.component.spec.ts
  libs/components/indicators/src/lib/modules/help-inline/help-inline.component.ts
  libs/components/indicators/src/lib/modules/help-inline/help-inline.module.ts
Labels: risk level (author): 2, risk level (reviewer): 2

#1232 fix(components/indicators): fix help inline background color
  libs/components/indicators/src/lib/modules/help-inline/help-inline.component.scss
Labels: risk level (author): 1, risk level (reviewer): 1

#1237 chore(apps/playground): add tokens playground page
  apps/playground/src/app/components/indicators/indicators.module.ts
  apps/playground/src/app/components/indicators/tokens/tokens-routing.module.ts
  apps/playground/src/app/components/indicators/tokens/tokens.component.html
  apps/playground/src/app/components/indicators/tokens/tokens.component.ts
  apps/playground/src/app/components/indicators/tokens/tokens.module.ts
Labels: risk level (author): 1

#1231 chore: release 7.17.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease 7.x.x: pending

#1241 chore: release 8.0.0-alpha.19
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#1242 test(components/indicators): add icon accessibility tests
  libs/components/indicators/src/lib/modules/icon/fixtures/icon-fixtures.module.ts
  libs/components/indicators/src/lib/modules/icon/fixtures/icon-stack.component.fixture.ts
  libs/components/indicators/src/lib/modules/icon/icon-stack.component.spec.ts
  libs/components/indicators/src/lib/modules/icon/icon.component.spec.ts
Labels: risk level (author): 1

#1239 chore: allow `backticks` in cherry pick pull request
  .github/workflows/cherry-pick.yml
Labels: risk level (author): 1

#1247 fix(components/toast): close button hover text is incorrect
  apps/integration-e2e/src/e2e/toast.cy.ts
  apps/integration/src/app/integrations/integrations.module.ts
  apps/integration/src/app/integrations/toast/toast-routing.module.ts
  apps/integration/src/app/integrations/toast/toast.component.html
  apps/integration/src/app/integrations/toast/toast.component.spec.ts
  apps/integration/src/app/integrations/toast/toast.component.ts
  apps/integration/src/app/integrations/toast/toast.module.ts
  libs/components/toast/src/lib/modules/toast/toast.service.spec.ts
  libs/components/toast/src/lib/modules/toast/toast.service.ts
Labels: risk level (author): 2, risk level (reviewer): 2

#1251 fix(components/lists): update all repeater items when items query list changes
  libs/components/lists/src/lib/modules/repeater/repeater.component.spec.ts
  libs/components/lists/src/lib/modules/repeater/repeater.component.ts
Labels: risk level (author): 2, risk level (reviewer): 3

#1253 feat(components/lists): auto-scroll window or parent when dragging repeater items
  .cspell.json
  apps/e2e/lists-storybook/src/test-setup.ts
  libs/components/lists/ng-package.json
  libs/components/lists/package.json
  libs/components/lists/src/lib/modules/repeater/repeater-auto-scroll-options.ts
  libs/components/lists/src/lib/modules/repeater/repeater-auto-scroll.service.ts
  libs/components/lists/src/lib/modules/repeater/repeater-auto-scroller.ts
  libs/components/lists/src/lib/modules/repeater/repeater.component.spec.ts
  libs/components/lists/src/lib/modules/repeater/repeater.component.ts
  package-lock.json
  package.json
  tsconfig.base.json
  vendor/types/dom-autoscroller/index.d.ts
Labels: risk level (author): 3

#1244 feat(components/indicators): use alternate Font Awesome icon for default theme when available
  libs/components/indicators/src/lib/modules/icon/icon-class-list.pipe.ts
  libs/components/indicators/src/lib/modules/icon/icon-resolver.service.spec.ts
  libs/components/indicators/src/lib/modules/icon/icon-resolver.service.ts
  libs/components/indicators/src/lib/modules/icon/icon-stack.component.html
  libs/components/indicators/src/lib/modules/icon/icon-stack.component.ts
  libs/components/indicators/src/lib/modules/icon/icon.component.html
  libs/components/indicators/src/lib/modules/icon/icon.component.spec.ts
  libs/components/indicators/src/lib/modules/icon/icon.component.ts
  libs/components/indicators/src/lib/modules/icon/types/icon-resolved.ts
  libs/components/indicators/src/lib/modules/status-indicator/status-indicator.component.spec.ts
  libs/components/indicators/testing/src/icon/icon-harness.spec.ts
  libs/components/indicators/testing/src/icon/icon-harness.ts
  libs/components/packages/package.json
  libs/components/theme/package.json
  libs/components/theme/src/index.ts
  libs/components/theme/src/lib/icons/icon-manifest-glyph.ts
  libs/components/theme/src/lib/icons/icon-manifest.service.ts
  libs/components/theme/src/lib/icons/icon-manifest.ts
  libs/components/theme/src/lib/styles/sky.scss
  package-lock.json
  package.json
Labels: risk level (author): 3, risk level (reviewer): 3

#1250 chore: release 7.18.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease 7.x.x: pending

#1258 chore: release 8.0.0-alpha.20
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#1264 chore: release 7.19.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease 7.x.x: pending

#1273 fix(components/modals): apply correct spacing to link buttons in modal footers
  apps/code-examples/src/app/code-examples/modals/inline-help/modal-demo-modal.component.html
  apps/code-examples/src/app/code-examples/modals/modal/modal-demo-modal.component.html
  apps/playground/src/app/components/modal/modal-form-demo.component.html
  libs/components/modals/src/lib/modules/modal/modal-footer.component.scss
  libs/components/modals/src/lib/modules/modal/modal-footer.component.ts
  libs/components/modals/src/lib/modules/modal/modal.component.scss
  libs/components/packages/src/schematics/migrations/update-8/add-compat-stylesheets/add-compat-stylesheets.ts
Labels: risk level (author): 2, risk level (reviewer): 3

#968 feat(components/indicators): announce wait component state changes to screen readers
  apps/integration/project.json
  apps/integration/src/app/integrations/integrations.module.ts
  apps/integration/src/app/integrations/modal-wait/modal-wait-modal.component.html
  apps/integration/src/app/integrations/modal-wait/modal-wait-modal.component.ts
  apps/integration/src/app/integrations/modal-wait/modal-wait-routing-module.ts
  apps/integration/src/app/integrations/modal-wait/modal-wait.component.html
  apps/integration/src/app/integrations/modal-wait/modal-wait.component.spec.ts
  apps/integration/src/app/integrations/modal-wait/modal-wait.component.ts
  apps/integration/src/app/integrations/modal-wait/modal-wait.module.ts
  libs/components/core/src/index.ts
  libs/components/core/src/lib/modules/live-announcer/fixtures/live-announcer.component.fixture.html
  libs/components/core/src/lib/modules/live-announcer/fixtures/live-announcer.component.fixture.ts
  libs/components/core/src/lib/modules/live-announcer/live-announcer.service.spec.ts
  libs/components/core/src/lib/modules/live-announcer/live-announcer.service.ts
  libs/components/core/src/lib/modules/live-announcer/types/live-announcer-args.ts
  libs/components/core/src/lib/modules/live-announcer/types/live-announcer-politeness.ts
  libs/components/indicators/src/assets/locales/resources_en_US.json
  libs/components/indicators/src/lib/modules/shared/sky-indicators-resources.module.ts
  libs/components/indicators/src/lib/modules/wait/fixtures/wait.component.fixture.html
  libs/components/indicators/src/lib/modules/wait/fixtures/wait.component.fixture.ts
  libs/components/indicators/src/lib/modules/wait/wait.component.spec.ts
  libs/components/indicators/src/lib/modules/wait/wait.component.ts
  libs/components/modals/src/lib/modules/modal/modal.component.html
  libs/components/modals/src/lib/modules/modal/modal.component.spec.ts
  libs/components/modals/src/lib/modules/modal/modal.component.ts
  package-lock.json
Labels: risk level (author): 3, risk level (reviewer): 3

#1278 chore: release 8.0.0-alpha.21
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#1281 chore: release 7.20.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease 7.x.x: pending

#1293 chore: release 7.21.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease 7.x.x: pending

#1307 chore: release 8.0.0-beta.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#1310 chore: release 7.21.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease 7.x.x: pending

#1319 chore: release 8.0.0-beta.2
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#1321 chore: release 7.21.2
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease 7.x.x: pending

#1328 chore: release 8.0.0-beta.3
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending
