Repository blackbaud/skyux, pull requests merged in 2023-03, with the labels that each got.

#1039 chore: release 7.9.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease 7.x.x: pending

#1021 chore: release 8.0.0-alpha.2
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#1051 chore: release 8.0.0-alpha.3
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#1058 chore: release 8.0.0-alpha.5
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#1060 chore: release 7.10.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease 7.x.x: pending

#1066 chore: release 8.0.0-alpha.6
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#1072 chore: release 8.0.0-alpha.6
  CHANGELOG.md
Labels: autorelease main: pending

#1080 chore: release 8.0.0-alpha.7
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#1103 chore: release 7.10.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease 7.x.x: pending

#1111 chore: release 8.0.0-alpha.8
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#1128 chore: release 7.11.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease 7.x.x: pending

#1136 chore: release 8.0.0-alpha.9
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#1138 chore: release 7.11.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease 7.x.x: pending

#1139 chore: release 8.0.0-alpha.10
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#1150 chore: release 8.0.0-alpha.11
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#1145 chore: release 7.12.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease 7.x.x: pending

#1161 chore: release 8.0.0-alpha.12
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#1176 fix(components/lookup): use `position: absolute` for autocomplete dropdown
  apps/playground/src/app/components/modal/modal-form-demo.component.html
  apps/playground/src/app/components/modal/modal-form-demo.component.ts
  apps/playground/src/app/components/modal/modal-visual.module.ts
  libs/components/core/src/index.ts
  libs/components/core/src/lib/modules/affix/affix-config.ts
  libs/components/core/src/lib/modules/affix/affix-position.ts
  libs/components/core/src/lib/modules/affix/affix-rect.ts
  libs/components/core/src/lib/modules/affix/affix.directive.spec.ts
  libs/components/core/src/lib/modules/affix/affix.directive.ts
  libs/components/core/src/lib/modules/affix/affixer.ts
  libs/components/core/src/lib/modules/affix/fixtures/affix.component.fixture.html
  libs/components/core/src/lib/modules/affix/fixtures/affix.component.fixture.scss
  libs/components/core/src/lib/modules/affix/fixtures/affix.component.fixture.ts
  libs/components/core/src/lib/modules/overlay/overlay-config.ts
  libs/components/core/src/lib/modules/overlay/overlay-position.ts
  libs/components/core/src/lib/modules/overlay/overlay.component.html
  libs/components/core/src/lib/modules/overlay/overlay.component.scss
  libs/components/core/src/lib/modules/overlay/overlay.component.ts
  libs/components/lookup/src/lib/modules/autocomplete/autocomplete.component.scss
  libs/components/lookup/src/lib/modules/autocomplete/autocomplete.component.ts
Labels: risk level (author): 3

#1167 chore(components/core): mark numeric options as deprecated
  libs/components/core/src/lib/modules/numeric/numeric.options.ts
Labels: risk level (author): 2, risk level (reviewer): 2

#1164 chore: release 7.13.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease 7.x.x: pending

#1191 deprecation(components/forms): deprecate radioType and checkboxType
  libs/components/forms/src/lib/modules/checkbox/checkbox.component.spec.ts
  libs/components/forms/src/lib/modules/checkbox/checkbox.component.ts
  libs/components/forms/src/lib/modules/radio/radio.component.spec.ts
  libs/components/forms/src/lib/modules/radio/radio.component.ts
  libs/components/forms/src/lib/modules/radio/types/radio-type.ts
Labels: risk level (author): 1, risk level (reviewer): 1

#1194 chore: release 7.14.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease 7.x.x: pending

#1198 chore: release 8.0.0-alpha.14
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#1199 chore: release 8.0.0-alpha.15
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending
