Repository blackbaud/skyux, pull requests merged in 2023-06, with the labels that each got.

#1418 test(components/forms): radio button visual tests
  apps/e2e/forms-storybook-e2e/src/e2e/radio-button.component.cy.ts
  apps/e2e/forms-storybook/src/app/app.module.ts
  apps/e2e/forms-storybook/src/app/radio-button/radio-button.component.html
  apps/e2e/forms-storybook/src/app/radio-button/radio-button.component.scss
  apps/e2e/forms-storybook/src/app/radio-button/radio-button.component.stories.ts
  apps/e2e/forms-storybook/src/app/radio-button/radio-button.component.ts
  apps/e2e/forms-storybook/src/app/radio-button/radio-button.module.ts
Labels: risk level (author): 1, risk level (reviewer): 1

#1419 fix(sdk/eslint-config): move parser options to overrides
  libs/sdk/eslint-config/jest.config.ts
  libs/sdk/eslint-config/package.json
  libs/sdk/eslint-config/recommended.json
  libs/sdk/eslint-config/src/schematics/ng-add/ng-add.schematic.spec.ts
  libs/sdk/eslint-config/src/schematics/ng-add/ng-add.schematic.ts
  libs/sdk/eslint-config/src/schematics/shared/rules/install-dependencies.ts
  libs/sdk/eslint-config/src/schematics/shared/rules/modify-eslint-config.ts
  libs/sdk/eslint-config/src/schematics/shared/types/eslint-config.ts
  libs/sdk/eslint-config/src/schematics/shared/utility/get-latest-version.ts
  package-lock.json
  package.json
Labels: risk level (author): 1, risk level (reviewer): 1

#1423 test(components/indicators): status indicator visual tests
  apps/e2e/indicators-storybook-e2e/src/e2e/status-indicator.component.cy.ts
  apps/e2e/indicators-storybook/src/app/app.module.ts
  apps/e2e/indicators-storybook/src/app/status-indicator/status-indicator.component.html
  apps/e2e/indicators-storybook/src/app/status-indicator/status-indicator.component.scss
  apps/e2e/indicators-storybook/src/app/status-indicator/status-indicator.component.spec.ts
  apps/e2e/indicators-storybook/src/app/status-indicator/status-indicator.component.stories.ts
  apps/e2e/indicators-storybook/src/app/status-indicator/status-indicator.component.ts
  apps/e2e/indicators-storybook/src/app/status-indicator/status-indicator.module.ts
Labels: risk level (author): 1, risk level (reviewer): 1

#1424 chore: release 8.2.3
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#1425 test(components/indicators): chevron and expansion indicator visual tests
  apps/e2e/indicators-storybook-e2e/src/e2e/chevron.component.cy.ts
  apps/e2e/indicators-storybook-e2e/src/e2e/expansion-indicator.component.cy.ts
  apps/e2e/indicators-storybook/src/app/app.module.ts
  apps/e2e/indicators-storybook/src/app/chevron/chevron.component.html
  apps/e2e/indicators-storybook/src/app/chevron/chevron.component.scss
  apps/e2e/indicators-storybook/src/app/chevron/chevron.component.spec.ts
  apps/e2e/indicators-storybook/src/app/chevron/chevron.component.stories.ts
  apps/e2e/indicators-storybook/src/app/chevron/chevron.component.ts
  apps/e2e/indicators-storybook/src/app/chevron/chevron.module.ts
  apps/e2e/indicators-storybook/src/app/expansion-indicator/expansion-indicator.component.html
  apps/e2e/indicators-storybook/src/app/expansion-indicator/expansion-indicator.component.scss
  apps/e2e/indicators-storybook/src/app/expansion-indicator/expansion-indicator.component.spec.ts
  apps/e2e/indicators-storybook/src/app/expansion-indicator/expansion-indicator.component.stories.ts
  apps/e2e/indicators-storybook/src/app/expansion-indicator/expansion-indicator.component.ts
  apps/e2e/indicators-storybook/src/app/expansion-indicator/expansion-indicator.module.ts
Labels: risk level (author): 1, risk level (reviewer): 1

#1420 test(components/lookup): autocomplete visual tests
  apps/e2e/lookup-storybook-e2e/src/e2e/autocomplete.component.cy.ts
  apps/e2e/lookup-storybook/src/app/app.module.ts
  apps/e2e/lookup-storybook/src/app/autocomplete/autocomplete.component.html
  apps/e2e/lookup-storybook/src/app/autocomplete/autocomplete.component.scss
  apps/e2e/lookup-storybook/src/app/autocomplete/autocomplete.component.spec.ts
  apps/e2e/lookup-storybook/src/app/autocomplete/autocomplete.component.stories.ts
  apps/e2e/lookup-storybook/src/app/autocomplete/autocomplete.component.ts
  apps/e2e/lookup-storybook/src/app/autocomplete/autocomplete.module.ts
Labels: risk level (author): 1, risk level (reviewer): 1

#1417 feat(components/popovers): dropdown visual test
  apps/e2e/popovers-storybook-e2e/src/e2e/dropdown.component.cy.ts
  apps/e2e/popovers-storybook/src/app/app.module.ts
  apps/e2e/popovers-storybook/src/app/dropdown/dropdown.component.html
  apps/e2e/popovers-storybook/src/app/dropdown/dropdown.component.scss
  apps/e2e/popovers-storybook/src/app/dropdown/dropdown.component.spec.ts
  apps/e2e/popovers-storybook/src/app/dropdown/dropdown.component.stories.ts
  apps/e2e/popovers-storybook/src/app/dropdown/dropdown.component.ts
  apps/e2e/popovers-storybook/src/app/dropdown/dropdown.module.ts
  libs/components/popovers/testing/src/dropdown/harness/dropdown-harness.spec.ts
  libs/components/popovers/testing/src/dropdown/harness/dropdown-harness.ts
Labels: risk level (author): 1, risk level (reviewer): 1

#1426 fix(sdk/eslint-config): import 'package-json' ECMAScript module to support usage within CommonJS
  libs/sdk/eslint-config/src/schematics/shared/utility/get-latest-version.ts
Labels: risk level (author): 1, risk level (reviewer): 1

#1429 test(components/layout): action button visual tests
  apps/e2e/layout-storybook-e2e/src/e2e/action-button.component.cy.ts
  apps/e2e/layout-storybook/src/app/action-button/action-button.component.html
  apps/e2e/layout-storybook/src/app/action-button/action-button.component.scss
  apps/e2e/layout-storybook/src/app/action-button/action-button.component.spec.ts
  apps/e2e/layout-storybook/src/app/action-button/action-button.component.stories.ts
  apps/e2e/layout-storybook/src/app/action-button/action-button.component.ts
  apps/e2e/layout-storybook/src/app/action-button/action-button.module.ts
  apps/e2e/layout-storybook/src/app/app.module.ts
Labels: risk level (author): 1, risk level (reviewer): 1

#1428 test(components/avatar): add avatar visual tests
  apps/e2e/avatar-storybook-e2e/src/e2e/avatar.component.cy.ts
  apps/e2e/avatar-storybook/project.json
  apps/e2e/avatar-storybook/src/app/avatar/avatar.component.html
  apps/e2e/avatar-storybook/src/app/avatar/avatar.component.scss
  apps/e2e/avatar-storybook/src/app/avatar/avatar.component.ts
  apps/e2e/avatar-storybook/src/app/avatar/avatar.module.ts
Labels: risk level (author): 1, risk level (reviewer): 1

#1427 chore: release 8.2.4
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#1433 ci: additional triggers to verify that risk labels have been applied
  .github/workflows/risk-assessment.yml
Labels: risk level (author): 1, risk level (reviewer): 1

#1430 test(components/layout): back to top visual tests
  apps/e2e/layout-storybook-e2e/src/e2e/back-to-top.component.cy.ts
  apps/e2e/layout-storybook/src/app/app.module.ts
  apps/e2e/layout-storybook/src/app/back-to-top/back-to-top.component.html
  apps/e2e/layout-storybook/src/app/back-to-top/back-to-top.component.scss
  apps/e2e/layout-storybook/src/app/back-to-top/back-to-top.component.spec.ts
  apps/e2e/layout-storybook/src/app/back-to-top/back-to-top.component.stories.ts
  apps/e2e/layout-storybook/src/app/back-to-top/back-to-top.component.ts
  apps/e2e/layout-storybook/src/app/back-to-top/back-to-top.module.ts
Labels: risk level (author): 1, risk level (reviewer): 1

#1436 test(components/layout): add description-list visual tests
  .cspell.json
  apps/e2e/layout-storybook-e2e/src/e2e/description-list.component.cy.ts
  apps/e2e/layout-storybook-e2e/src/e2e/fluid-grid.component.cy.ts
  apps/e2e/layout-storybook/src/app/app.module.ts
  apps/e2e/layout-storybook/src/app/description-list/description-list.component.html
  apps/e2e/layout-storybook/src/app/description-list/description-list.component.scss
  apps/e2e/layout-storybook/src/app/description-list/description-list.component.spec.ts
  apps/e2e/layout-storybook/src/app/description-list/description-list.component.stories.ts
  apps/e2e/layout-storybook/src/app/description-list/description-list.component.ts
  apps/e2e/layout-storybook/src/app/description-list/description-list.module.ts
Labels: risk level (author): 1, risk level (reviewer): 1

#1434 fix(components/config): support query params with multiple values
  libs/components/config/src/lib/params.spec.ts
  libs/components/config/src/lib/params.ts
Labels: risk level (author): 2, risk level (reviewer): 3

#1435 chore: release 8.2.5
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending, risk level (author): 1

#1437 test(components/errors): add error visual tests
  apps/e2e/errors-storybook-e2e/src/e2e/error.component.cy.ts
  apps/e2e/errors-storybook-e2e/src/e2e/errors.component.cy.ts
  apps/e2e/errors-storybook/.storybook/main.ts
  apps/e2e/errors-storybook/project.json
  apps/e2e/errors-storybook/src/app/app.module.ts
  apps/e2e/errors-storybook/src/app/error/error.component.html
  apps/e2e/errors-storybook/src/app/error/error.component.scss
  apps/e2e/errors-storybook/src/app/error/error.component.stories.ts
  apps/e2e/errors-storybook/src/app/error/error.component.ts
  apps/e2e/errors-storybook/src/app/error/error.module.ts
  apps/e2e/errors-storybook/src/app/errors/errors.component.html
  apps/e2e/errors-storybook/src/app/errors/errors.component.scss
  apps/e2e/errors-storybook/src/app/errors/errors.component.stories.ts
  apps/e2e/errors-storybook/src/app/errors/errors.component.ts
  apps/e2e/errors-storybook/src/app/errors/errors.module.ts
  apps/e2e/errors-storybook/src/assets/old_broken_bird.jpg
  apps/e2e/errors-storybook/tsconfig.json
Labels: risk level (author): 1, risk level (reviewer): 1

#1442 test(components/flyout): add flyout visual tests
  apps/e2e/flyout-storybook-e2e/src/e2e/flyout.component.cy.ts
  apps/e2e/flyout-storybook/project.json
  apps/e2e/flyout-storybook/src/app/flyout/flyout-responsive.component.html
  apps/e2e/flyout-storybook/src/app/flyout/flyout-responsive.component.scss
  apps/e2e/flyout-storybook/src/app/flyout/flyout-responsive.component.ts
  apps/e2e/flyout-storybook/src/app/flyout/flyout-standard.component.html
  apps/e2e/flyout-storybook/src/app/flyout/flyout-standard.component.ts
  apps/e2e/flyout-storybook/src/app/flyout/flyout.component.html
  apps/e2e/flyout-storybook/src/app/flyout/flyout.component.scss
  apps/e2e/flyout-storybook/src/app/flyout/flyout.component.stories.ts
  apps/e2e/flyout-storybook/src/app/flyout/flyout.component.ts
  apps/e2e/flyout-storybook/src/app/flyout/flyout.module.ts
Labels: risk level (author): 1, risk level (reviewer): 1

#1443 chore(sdk/e2e-schematics): only include spec file if tests are requested
  libs/sdk/e2e-schematics/src/generators/story/__snapshots__/index.spec.ts.snap
  libs/sdk/e2e-schematics/src/generators/story/index.spec.ts
  libs/sdk/e2e-schematics/src/generators/story/index.ts
Labels: risk level (author): 1, risk level (reviewer): 1

#1440 feat(components/lookup): lookup visual test
  apps/e2e/lookup-storybook-e2e/src/e2e/lookup.component.cy.ts
  apps/e2e/lookup-storybook/src/app/app.module.ts
  apps/e2e/lookup-storybook/src/app/lookup/lookup.component.html
  apps/e2e/lookup-storybook/src/app/lookup/lookup.component.scss
  apps/e2e/lookup-storybook/src/app/lookup/lookup.component.stories.ts
  apps/e2e/lookup-storybook/src/app/lookup/lookup.component.ts
  apps/e2e/lookup-storybook/src/app/lookup/lookup.module.ts
Labels: risk level (author): 1, risk level (reviewer): 1

#1444 test(components/colorpicker): colorpicker visual tests
  apps/e2e/.cspell.json
  apps/e2e/colorpicker-storybook-e2e/src/e2e/colorpicker.component.cy.ts
  apps/e2e/colorpicker-storybook/project.json
  apps/e2e/colorpicker-storybook/src/app/colorpicker/colorpicker.component.html
  apps/e2e/colorpicker-storybook/src/app/colorpicker/colorpicker.component.ts
  apps/e2e/colorpicker-storybook/src/app/colorpicker/colorpicker.module.ts
Labels: risk level (author): 1, risk level (reviewer): 1

#1441 feat(components/datetime): add visual tests for date picker and date range picker
  apps/e2e/datetime-storybook-e2e/cypress.config.ts
  apps/e2e/datetime-storybook-e2e/project.json
  apps/e2e/datetime-storybook-e2e/src/e2e/.gitkeep
  apps/e2e/datetime-storybook-e2e/src/e2e/date-range-picker.component.cy.ts
  apps/e2e/datetime-storybook-e2e/src/e2e/datepicker.component.cy.ts
  apps/e2e/datetime-storybook-e2e/src/support/commands.ts
  apps/e2e/datetime-storybook-e2e/src/support/e2e.ts
  apps/e2e/datetime-storybook/project.json
  apps/e2e/datetime-storybook/src/app/app.module.ts
  apps/e2e/datetime-storybook/src/app/date-range-picker/date-range-picker.component.html
  apps/e2e/datetime-storybook/src/app/date-range-picker/date-range-picker.component.scss
  apps/e2e/datetime-storybook/src/app/date-range-picker/date-range-picker.component.stories.ts
  apps/e2e/datetime-storybook/src/app/date-range-picker/date-range-picker.component.ts
  apps/e2e/datetime-storybook/src/app/date-range-picker/date-range-picker.module.ts
  apps/e2e/datetime-storybook/src/app/datepicker/datepicker.component.html
  apps/e2e/datetime-storybook/src/app/datepicker/datepicker.component.scss
  apps/e2e/datetime-storybook/src/app/datepicker/datepicker.component.ts
  apps/e2e/datetime-storybook/src/app/datepicker/datepicker.module.ts
Labels: risk level (author): 1, risk level (reviewer): 1

#1448 test(components/forms): toggle switch visual tests
  apps/e2e/forms-storybook-e2e/src/e2e/toggle-switch.component.cy.ts
  apps/e2e/forms-storybook/src/app/app.module.ts
  apps/e2e/forms-storybook/src/app/toggle-switch/toggle-switch.component.html
  apps/e2e/forms-storybook/src/app/toggle-switch/toggle-switch.component.scss
  apps/e2e/forms-storybook/src/app/toggle-switch/toggle-switch.component.stories.ts
  apps/e2e/forms-storybook/src/app/toggle-switch/toggle-switch.component.ts
  apps/e2e/forms-storybook/src/app/toggle-switch/toggle-switch.module.ts
Labels: risk level (author): 1, risk level (reviewer): 1

#1449 fix(components/lookup): pass `wrapperClass` to selection modal (#996)
  apps/playground/src/app/components/ag-grid/edit-complex-cells/edit-complex-cells.component.ts
  libs/components/lookup/src/lib/modules/lookup/fixtures/lookup.component.fixture.html
  libs/components/lookup/src/lib/modules/lookup/fixtures/lookup.component.fixture.ts
  libs/components/lookup/src/lib/modules/lookup/lookup.component.spec.ts
  libs/components/lookup/src/lib/modules/lookup/lookup.component.ts
  libs/components/lookup/src/lib/modules/selection-modal/selection-modal.service.ts
  libs/components/lookup/src/lib/modules/selection-modal/types/selection-modal-open-args.ts
Labels: risk level (author): 1, risk level (reviewer): 1

#1450 test(components/lists): sort visual tests
  apps/e2e/forms-storybook/src/app/toggle-switch/toggle-switch.component.html
  apps/e2e/lists-storybook-e2e/src/e2e/sort.component.cy.ts
  apps/e2e/lists-storybook/src/app/app.module.ts
  apps/e2e/lists-storybook/src/app/sort/sort.component.html
  apps/e2e/lists-storybook/src/app/sort/sort.component.scss
  apps/e2e/lists-storybook/src/app/sort/sort.component.stories.ts
  apps/e2e/lists-storybook/src/app/sort/sort.component.ts
  apps/e2e/lists-storybook/src/app/sort/sort.module.ts
Labels: risk level (author): 1, risk level (reviewer): 1

#1445 chore: release 8.2.6
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending, risk level (author): 1, risk level (reviewer): 1

#1446 test(components/lists): add infinite scroll visual tests
  apps/e2e/lists-storybook-e2e/src/e2e/infinite-scroll.component.cy.ts
  apps/e2e/lists-storybook/src/app/app.module.ts
  apps/e2e/lists-storybook/src/app/infinite-scroll/infinite-scroll.component.html
  apps/e2e/lists-storybook/src/app/infinite-scroll/infinite-scroll.component.scss
  apps/e2e/lists-storybook/src/app/infinite-scroll/infinite-scroll.component.stories.ts
  apps/e2e/lists-storybook/src/app/infinite-scroll/infinite-scroll.component.ts
  apps/e2e/lists-storybook/src/app/infinite-scroll/infinite-scroll.module.ts
Labels: risk level (author): 1, risk level (reviewer): 1

#1453 test(components/flyout): fix flyout visual test inconsistencies
  apps/e2e/flyout-storybook-e2e/src/e2e/flyout.component.cy.ts
  apps/e2e/flyout-storybook/src/app/flyout/flyout.component.ts
Labels: risk level (author): 1, risk level (reviewer): 1

#1421 feat(components/modals): add `isDirty` directive to modals
  apps/code-examples/src/app/code-examples/modals/modal/modal-demo-modal.component.html
  apps/code-examples/src/app/code-examples/modals/modal/modal-demo-modal.component.ts
  apps/playground/src/app/components/modal/modal-dirty.component.html
  apps/playground/src/app/components/modal/modal-dirty.component.ts
  apps/playground/src/app/components/modal/modal-visual.component.html
  apps/playground/src/app/components/modal/modal-visual.component.ts
  apps/playground/src/app/components/modal/modal-visual.module.ts
  libs/components/modals/src/assets/locales/resources_en_US.json
  libs/components/modals/src/index.ts
  libs/components/modals/src/lib/modules/modal/fixtures/modal-fixtures.module.ts
  libs/components/modals/src/lib/modules/modal/fixtures/modal-is-dirty-test-context.fixture.ts
  libs/components/modals/src/lib/modules/modal/fixtures/modal-is-dirty.component.fixture.html
  libs/components/modals/src/lib/modules/modal/fixtures/modal-is-dirty.component.fixture.ts
  libs/components/modals/src/lib/modules/modal/modal-is-dirty.directive.ts
  libs/components/modals/src/lib/modules/modal/modal.component.spec.ts
  libs/components/modals/src/lib/modules/modal/modal.module.ts
  libs/components/modals/src/lib/modules/shared/sky-modals-resources.module.ts
  libs/components/modals/testing/src/modal/modal-harness.spec.ts
  libs/components/modals/testing/src/modal/modal-harness.ts
Labels: risk level (author): 2, risk level (reviewer): 3

#1456 ci: notify slack when e2e test fails
  .github/workflows/e2e.yml
  .github/workflows/risk-assessment.yml
Labels: risk level (author): 1, risk level (reviewer): 1

#1458 test(components/tabs): vertical tabset visual tests
  apps/e2e/tabs-storybook-e2e/src/e2e/vertical-tabs.component.cy.ts
  apps/e2e/tabs-storybook/src/app/app.module.ts
  apps/e2e/tabs-storybook/src/app/vertical-tabs/vertical-tabs.component.html
  apps/e2e/tabs-storybook/src/app/vertical-tabs/vertical-tabs.component.scss
  apps/e2e/tabs-storybook/src/app/vertical-tabs/vertical-tabs.component.stories.ts
  apps/e2e/tabs-storybook/src/app/vertical-tabs/vertical-tabs.component.ts
  apps/e2e/tabs-storybook/src/app/vertical-tabs/vertical-tabs.module.ts
Labels: risk level (author): 1, risk level (reviewer): 1

#1457 ci: notify slack when e2e test fails, fix link
  .github/workflows/e2e.yml
Labels: risk level (author): 1, risk level (reviewer): 1

#1431 test(components/data-manager): add data manager visual tests
  apps/e2e/ag-grid-storybook-e2e/src/e2e/data-manager.component.cy.ts
  apps/e2e/data-manager-storybook-e2e/src/e2e/data-manager.component.cy.ts
  apps/e2e/data-manager-storybook/project.json
  apps/e2e/data-manager-storybook/src/app/data-manager/data-manager.component.html
  apps/e2e/data-manager-storybook/src/app/data-manager/data-manager.component.scss
  apps/e2e/data-manager-storybook/src/app/data-manager/data-manager.component.stories.ts
  apps/e2e/data-manager-storybook/src/app/data-manager/data-manager.component.ts
  apps/e2e/data-manager-storybook/src/app/data-manager/data-manager.module.ts
  libs/components/data-manager/src/lib/modules/data-manager/data-manager-column-picker/data-manager-column-picker.component.spec.ts
Labels: risk level (author): 1, risk level (reviewer): 1

#1461 test(components/datetime): fix inconsistency with open datepicker snapshots
  apps/e2e/datetime-storybook-e2e/src/e2e/datepicker.component.cy.ts
  apps/e2e/datetime-storybook/src/app/datepicker/datepicker.component.html
Labels: risk level (author): 1, risk level (reviewer): 1

#1463 chore(apps/playground): add country field playground page
  apps/playground/src/app/components/lookup/country-field/country-field-routing.module.ts
  apps/playground/src/app/components/lookup/country-field/country-field.component.html
  apps/playground/src/app/components/lookup/country-field/country-field.component.scss
  apps/playground/src/app/components/lookup/country-field/country-field.component.ts
  apps/playground/src/app/components/lookup/country-field/country-field.module.ts
  apps/playground/src/app/components/lookup/lookup.module.ts
Labels: risk level (author): 1, risk level (reviewer): 1

#1455 test(components/inline-form): inline form visual test
  apps/e2e/inline-form-storybook-e2e/src/e2e/inline-form.component.cy.ts
  apps/e2e/inline-form-storybook/project.json
  apps/e2e/inline-form-storybook/src/app/inline-form/inline-form.component.html
  apps/e2e/inline-form-storybook/src/app/inline-form/inline-form.component.stories.ts
  apps/e2e/inline-form-storybook/src/app/inline-form/inline-form.component.ts
  apps/e2e/inline-form-storybook/src/app/inline-form/inline-form.module.ts
  package-lock.json
Labels: risk level (author): 1, risk level (reviewer): 1

#1464 test(components/ag-grid): remove search focus before column picker visual test
  apps/e2e/ag-grid-storybook-e2e/src/e2e/data-manager.component.cy.ts
Labels: risk level (author): 1, risk level (reviewer): 1

#1465 fix(components/angular-tree-component): add overflow hidden
  libs/components/angular-tree-component/src/lib/modules/angular-tree/angular-tree-wrapper.component.scss
Labels: risk level (author): 2, risk level (reviewer): 2

#1467 ci: update e2e concurrency rules
  .github/workflows/e2e.yml
Labels: risk level (author): 1, risk level (reviewer): 1

#1460 fix: call out that disabled inputs should not be used when using a reactive form
  apps/e2e/lookup-storybook/src/app/lookup/lookup.component.html
  apps/e2e/lookup-storybook/src/app/lookup/lookup.component.ts
  libs/components/datetime/src/lib/modules/date-range-picker/date-range-picker.component.ts
  libs/components/datetime/src/lib/modules/datepicker/datepicker-input-fuzzy.directive.ts
  libs/components/datetime/src/lib/modules/datepicker/datepicker-input.directive.ts
  libs/components/datetime/src/lib/modules/timepicker/timepicker.directive.ts
  libs/components/forms/src/lib/modules/checkbox/checkbox.component.ts
  libs/components/forms/src/lib/modules/file-attachment/file-attachment.component.ts
  libs/components/forms/src/lib/modules/radio/radio-group.component.ts
  libs/components/forms/src/lib/modules/radio/radio.component.ts
  libs/components/forms/src/lib/modules/toggle-switch/toggle-switch.component.ts
  libs/components/lookup/src/lib/modules/autocomplete/autocomplete-input.directive.ts
  libs/components/lookup/src/lib/modules/country-field/country-field.component.html
  libs/components/lookup/src/lib/modules/country-field/country-field.component.ts
  libs/components/lookup/src/lib/modules/lookup/lookup.component.ts
  libs/components/phone-field/src/lib/modules/phone-field/phone-field-input.directive.ts
  libs/components/select-field/src/lib/modules/select-field/select-field.component.ts
  libs/components/text-editor/src/lib/modules/text-editor/text-editor.component.ts
Labels: risk level (author): 1, risk level (reviewer): 1

#1466 chore: release 8.2.7
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#1390 feat(components/popovers): popover test harness and sample tests
  apps/code-examples/src/app/code-examples/popovers/popover/basic/popover-demo.component.html
  apps/code-examples/src/app/code-examples/popovers/popover/basic/popover-demo.component.spec.ts
  apps/code-examples/src/app/code-examples/popovers/popover/basic/popover-demo.component.ts
  libs/components/popovers/src/lib/modules/popover/popover-content.component.ts
  libs/components/popovers/src/lib/modules/popover/popover.component.ts
  libs/components/popovers/src/lib/modules/popover/popover.directive.ts
  libs/components/popovers/testing/src/popover/harness/fixtures/popover-harness-test-item-harness.ts
  libs/components/popovers/testing/src/popover/harness/fixtures/popover-harness-test.component.html
  libs/components/popovers/testing/src/popover/harness/fixtures/popover-harness-test.component.ts
  libs/components/popovers/testing/src/popover/harness/popover-body-harness.ts
  libs/components/popovers/testing/src/popover/harness/popover-content-harness-filters.ts
  libs/components/popovers/testing/src/popover/harness/popover-content-harness.ts
  libs/components/popovers/testing/src/popover/harness/popover-harness-filters.ts
  libs/components/popovers/testing/src/popover/harness/popover-harness.spec.ts
  libs/components/popovers/testing/src/popover/harness/popover-harness.ts
  libs/components/popovers/testing/src/public-api.ts
Labels: risk level (author): 2, risk level (reviewer): 2

#1470 test(components/indicators): text highlight visual test
  apps/e2e/indicators-storybook-e2e/src/e2e/text-highlight.component.cy.ts
  apps/e2e/indicators-storybook/src/app/app.module.ts
  apps/e2e/indicators-storybook/src/app/text-highlight/text-highlight.component.html
  apps/e2e/indicators-storybook/src/app/text-highlight/text-highlight.component.scss
  apps/e2e/indicators-storybook/src/app/text-highlight/text-highlight.component.stories.ts
  apps/e2e/indicators-storybook/src/app/text-highlight/text-highlight.component.ts
  apps/e2e/indicators-storybook/src/app/text-highlight/text-highlight.module.ts
Labels: risk level (author): 1, risk level (reviewer): 1

#1469 fix(components/inline-form): code example custom button action
  apps/code-examples/src/app/code-examples/inline-form/inline-form/custom-buttons/inline-form-demo.component.ts
Labels: risk level (author): 1, risk level (reviewer): 1

#1439 ci: switch workflows with secrets to use pull_request_target trigger
  .github/workflows/ci.yml
  .github/workflows/e2e.yml
  .github/workflows/risk-assessment.yml
Labels: risk level (author): 1, risk level (reviewer): 1

#1454 feat(components/modals): add `isDirty` directive to modals (#1421)
  apps/code-examples/src/app/code-examples/modals/modal/modal-demo-modal.component.html
  apps/code-examples/src/app/code-examples/modals/modal/modal-demo-modal.component.ts
  apps/playground/src/app/components/modal/modal-dirty.component.html
  apps/playground/src/app/components/modal/modal-dirty.component.ts
  apps/playground/src/app/components/modal/modal-visual.component.html
  apps/playground/src/app/components/modal/modal-visual.component.ts
  apps/playground/src/app/components/modal/modal-visual.module.ts
  libs/components/modals/src/assets/locales/resources_en_US.json
  libs/components/modals/src/index.ts
  libs/components/modals/src/lib/modules/modal/fixtures/modal-fixtures.module.ts
  libs/components/modals/src/lib/modules/modal/fixtures/modal-is-dirty-test-context.fixture.ts
  libs/components/modals/src/lib/modules/modal/fixtures/modal-is-dirty.component.fixture.html
  libs/components/modals/src/lib/modules/modal/fixtures/modal-is-dirty.component.fixture.ts
  libs/components/modals/src/lib/modules/modal/modal-is-dirty.directive.ts
  libs/components/modals/src/lib/modules/modal/modal.component.spec.ts
  libs/components/modals/src/lib/modules/modal/modal.module.ts
  libs/components/modals/src/lib/modules/shared/sky-modals-resources.module.ts
  libs/components/modals/testing/src/modal/modal-harness.spec.ts
  libs/components/modals/testing/src/modal/modal-harness.ts
Labels: risk level (author): 2, risk level (reviewer): 3

#1474 ci: update e2e checkout ref
  .github/workflows/e2e.yml
Labels: risk level (author): 2, risk level (reviewer): 2

#1472 fix(components/forms): input box borders are now properly applied when using Firefox
  libs/components/forms/src/lib/modules/input-box/input-box.component.scss
Labels: risk level (author): 2, risk level (reviewer): 2

#1475 ci: publish apps on pr-preview
  .github/workflows/e2e.yml
Labels: risk level (author): 1, risk level (reviewer): 2

#1473 fix(components/ag-grid): update uneditable cell background color
  apps/e2e/ag-grid-storybook/src/app/data-entry-grid/data-entry-grid.component.ts
  libs/components/ag-grid/src/lib/styles/_default.scss
  libs/components/ag-grid/src/lib/styles/_modern-light.scss
  libs/components/theme/package.json
  libs/sdk/e2e-schematics/src/lib/send-cypress-screenshots-to-percy/send-cypress-screenshots-to-percy.spec.ts
  libs/sdk/e2e-schematics/src/lib/send-cypress-screenshots-to-percy/send-cypress-screenshots-to-percy.ts
  package-lock.json
  package.json
Labels: risk level (author): 2, risk level (reviewer): 2

#1468 chore: release 8.3.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#1471 fix(components/lookup): lookup modals do not show an unintended wait when a search with more than ten items is applied after the modal has been scrolled to the bottom
  libs/components/lookup/src/lib/modules/lookup/fixtures/lookup-template.component.fixture.html
  libs/components/lookup/src/lib/modules/lookup/fixtures/lookup-template.component.fixture.ts
  libs/components/lookup/src/lib/modules/lookup/fixtures/lookup.component.fixture.ts
  libs/components/lookup/src/lib/modules/lookup/lookup-show-more-modal.component.html
  libs/components/lookup/src/lib/modules/lookup/lookup-show-more-modal.component.ts
  libs/components/lookup/src/lib/modules/lookup/lookup.component.spec.ts
  libs/components/lookup/src/lib/modules/lookup/lookup.component.ts
  libs/components/modals/src/lib/modules/modal/fixtures/modal.component.fixture.html
  libs/components/modals/src/lib/modules/modal/fixtures/modal.component.fixture.ts
  libs/components/modals/src/lib/modules/modal/modal-adapter.service.ts
  libs/components/modals/src/lib/modules/modal/modal-host.component.ts
  libs/components/modals/src/lib/modules/modal/modal-instance.ts
  libs/components/modals/src/lib/modules/modal/modal.service.spec.ts
Labels: risk level (author): 3, risk level (reviewer): 3

#1478 test(components/forms): add character counter e2e tests
  apps/e2e/forms-storybook-e2e/src/e2e/character-counter.component.cy.ts
  apps/e2e/forms-storybook/src/app/app.module.ts
  apps/e2e/forms-storybook/src/app/character-counter/character-counter.component.html
  apps/e2e/forms-storybook/src/app/character-counter/character-counter.component.stories.ts
  apps/e2e/forms-storybook/src/app/character-counter/character-counter.component.ts
  apps/e2e/forms-storybook/src/app/character-counter/character-counter.module.ts
Labels: risk level (author): 1, risk level (reviewer): 1

#1480 test(components/lists): add filter e2e tests
  apps/e2e/lists-storybook-e2e/src/e2e/filter.component.cy.ts
  apps/e2e/lists-storybook/src/app/app.module.ts
  apps/e2e/lists-storybook/src/app/filter/filter.component.html
  apps/e2e/lists-storybook/src/app/filter/filter.component.stories.ts
  apps/e2e/lists-storybook/src/app/filter/filter.component.ts
  apps/e2e/lists-storybook/src/app/filter/filter.module.ts
Labels: risk level (author): 1, risk level (reviewer): 1

#1482 fix(components/lookup): country field docs clarify that the `autocompleteAttribute` is for the HTML attribute and no longer list an internal input
  libs/components/lookup/src/lib/modules/country-field/country-field.component.ts
Labels: risk level (author): 1, risk level (reviewer): 1

#1483 fix(components/datetime): disabled date range picker now use correct colors
  apps/e2e/datetime-storybook-e2e/src/e2e/date-range-picker.component.cy.ts
  apps/e2e/datetime-storybook/src/app/date-range-picker/date-range-picker.component.ts
  libs/components/datetime/src/lib/modules/date-range-picker/date-range-picker.component.html
  libs/components/theme/src/lib/styles/_forms.scss
Labels: risk level (author): 2, risk level (reviewer): 2

#1481 test(components/layout): add inline delete e2e tests
  apps/e2e/layout-storybook-e2e/src/e2e/inline-delete.component.cy.ts
  apps/e2e/layout-storybook/src/app/app.module.ts
  apps/e2e/layout-storybook/src/app/inline-delete/inline-delete.component.html
  apps/e2e/layout-storybook/src/app/inline-delete/inline-delete.component.scss
  apps/e2e/layout-storybook/src/app/inline-delete/inline-delete.component.stories.ts
  apps/e2e/layout-storybook/src/app/inline-delete/inline-delete.component.ts
  apps/e2e/layout-storybook/src/app/inline-delete/inline-delete.module.ts
Labels: risk level (author): 1, risk level (reviewer): 1

#1477 fix(components/inline-form): updated descriptions of `action` and `reason` properties to be more descriptive
  libs/components/inline-form/src/lib/modules/inline-form/types/inline-form-button-config.ts
  libs/components/inline-form/src/lib/modules/inline-form/types/inline-form-close-args.ts
Labels: risk level (author): 1, risk level (reviewer): 1

#1479 chore: release 8.3.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#1476 test(components/lookup): country field visual test
  .cspell.json
  apps/e2e/lookup-storybook-e2e/src/e2e/country-field.component.cy.ts
  apps/e2e/lookup-storybook/src/app/app.module.ts
  apps/e2e/lookup-storybook/src/app/country-field/country-field.component.html
  apps/e2e/lookup-storybook/src/app/country-field/country-field.component.scss
  apps/e2e/lookup-storybook/src/app/country-field/country-field.component.stories.ts
  apps/e2e/lookup-storybook/src/app/country-field/country-field.component.ts
  apps/e2e/lookup-storybook/src/app/country-field/country-field.module.ts
Labels: risk level (author): 1, risk level (reviewer): 1

#1485 deprecation(components/forms): deprecate source property for checkbox and radio button change outputs
  libs/components/forms/src/lib/modules/checkbox/checkbox-change.ts
  libs/components/forms/src/lib/modules/radio/types/radio-change.ts
Labels: risk level (author): 1, risk level (reviewer): 1
