Repository blackbaud/skyux, pull requests merged in 2024-01, with the labels that each got.

#1898 feat(components/lists): add content section to paging for accessibility
  apps/code-examples/src/app/app-routing.module.ts
  apps/code-examples/src/app/app.component.html
  apps/code-examples/src/app/app.module.ts
  apps/code-examples/src/app/code-examples/lists/paging/with-content/demo-data.service.ts
  apps/code-examples/src/app/code-examples/lists/paging/with-content/demo-data.ts
  apps/code-examples/src/app/code-examples/lists/paging/with-content/demo.component.html
  apps/code-examples/src/app/code-examples/lists/paging/with-content/demo.component.ts
  apps/code-examples/src/app/code-examples/lists/paging/with-content/person.ts
  apps/code-examples/src/app/features/lists.module.ts
  apps/code-examples/src/app/home/home.component.html
  apps/code-examples/src/app/home/home.component.ts
  apps/code-examples/src/app/home/home.module.ts
  apps/playground/src/app/components/ag-grid/data-manager/data-manager-paged-items.pipe.ts
  apps/playground/src/app/components/ag-grid/data-manager/data-manager-visual.component.ts
  apps/playground/src/app/components/ag-grid/data-manager/data-view-grid.component.html
  apps/playground/src/app/components/ag-grid/data-manager/data-view-grid.component.ts
  apps/playground/src/app/components/ag-grid/data-manager/data-view-repeater.component.html
  apps/playground/src/app/components/ag-grid/data-manager/data-view-repeater.component.ts
  apps/playground/src/app/components/lists/paging/paging-visual.component.html
  apps/playground/src/app/components/lists/paging/paging-visual.component.ts
  libs/components/lists/src/assets/locales/resources_en_US.json
  libs/components/lists/src/index.ts
  libs/components/lists/src/lib/modules/paging/fixtures/paging-adapter.service.ts
  libs/components/lists/src/lib/modules/paging/fixtures/paging-with-content.component.fixture.ts
  libs/components/lists/src/lib/modules/paging/fixtures/paging.component.fixture.html
  libs/components/lists/src/lib/modules/paging/fixtures/paging.component.fixture.ts
  libs/components/lists/src/lib/modules/paging/fixtures/paging.module.fixture.ts
  libs/components/lists/src/lib/modules/paging/paging-content.component.ts
  libs/components/lists/src/lib/modules/paging/paging.component.html
  libs/components/lists/src/lib/modules/paging/paging.component.scss
  libs/components/lists/src/lib/modules/paging/paging.component.spec.ts
  libs/components/lists/src/lib/modules/paging/paging.component.ts
  libs/components/lists/src/lib/modules/paging/paging.module.ts
  libs/components/lists/src/lib/modules/paging/types/paging-content-change-args.ts
  libs/components/lists/src/lib/modules/shared/sky-lists-resources.module.ts
Labels: risk level (author): 3

#1922 chore: release 9.20.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending, risk level (author): 3

#1921 fix(components/tiles): adjust column behavior when wrapped in multiple responsive contexts
  apps/integration-e2e/src/e2e/modal-split-view-tile-dashboard.cy.ts
  apps/integration/src/app/integrations/integrations.module.ts
  apps/integration/src/app/integrations/modal-split-view-tile-dashboard/context.ts
  apps/integration/src/app/integrations/modal-split-view-tile-dashboard/data.service.ts
  apps/integration/src/app/integrations/modal-split-view-tile-dashboard/data.ts
  apps/integration/src/app/integrations/modal-split-view-tile-dashboard/modal-split-view-tile-dashboard-routing.module.ts
  apps/integration/src/app/integrations/modal-split-view-tile-dashboard/modal-split-view-tile-dashboard.component.html
  apps/integration/src/app/integrations/modal-split-view-tile-dashboard/modal-split-view-tile-dashboard.component.spec.ts
  apps/integration/src/app/integrations/modal-split-view-tile-dashboard/modal-split-view-tile-dashboard.component.ts
  apps/integration/src/app/integrations/modal-split-view-tile-dashboard/modal-split-view-tile-dashboard.module.ts
  apps/integration/src/app/integrations/modal-split-view-tile-dashboard/modal.component.html
  apps/integration/src/app/integrations/modal-split-view-tile-dashboard/modal.component.ts
  apps/integration/src/app/integrations/modal-split-view-tile-dashboard/record.ts
  apps/integration/src/app/integrations/modal-split-view-tile-dashboard/tile1.component.html
  apps/integration/src/app/integrations/modal-split-view-tile-dashboard/tile1.component.ts
  apps/integration/src/app/integrations/modal-split-view-tile-dashboard/tile2.component.html
  apps/integration/src/app/integrations/modal-split-view-tile-dashboard/tile2.component.ts
  libs/components/tiles/src/lib/modules/tiles/tile-dashboard/tile-dashboard.component.scss
  libs/components/tiles/src/lib/modules/tiles/tile-dashboard/tile-dashboard.component.ts
Labels: risk level (author): 2

#1924 chore: update skyux-dev-infra to 9.0.0-alpha.17
  package-lock.json
  package.json
Labels: risk level (author): 1

#1926 chore: release 9.20.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#1927 chore: set playground to use port 4201 locally by default
  apps/playground/project.json
Labels: risk level (author): 1

#1929 fix(components/datetime): timepicker overlay prevents unintended keyboard navigation from reaching parent components
  libs/components/datetime/src/lib/modules/timepicker/timepicker.component.spec.ts
  libs/components/datetime/src/lib/modules/timepicker/timepicker.component.ts
Labels: risk level (author): 3

#1925 feat(components/forms): form errors test harness
  apps/playground/src/app/components/forms/input-box/input-box.component.html
  libs/components/forms/testing/src/form-error/form-error-harness.filters.ts
  libs/components/forms/testing/src/form-error/form-error-harness.ts
  libs/components/forms/testing/src/form-error/form-errors-harness.filters.ts
  libs/components/forms/testing/src/form-error/form-errors-harness.spec.ts
  libs/components/forms/testing/src/form-error/form-errors-harness.ts
  libs/components/forms/testing/src/public-api.ts
Labels: risk level (author): 1

#1933 docs(code-examples): simplify data grid template column code example
  apps/code-examples/src/app/code-examples/ag-grid/data-grid/template-ref-column/data.ts
  apps/code-examples/src/app/code-examples/ag-grid/data-grid/template-ref-column/demo.component.html
  apps/code-examples/src/app/code-examples/ag-grid/data-grid/template-ref-column/demo.component.ts
Labels: risk level (author): 1

#1937 chore: revert "feat(components/forms): checkbox errors easy mode"
  apps/code-examples/src/app/code-examples/forms/checkbox/basic/demo.component.html
  apps/code-examples/src/app/code-examples/forms/checkbox/basic/demo.component.ts
  apps/code-examples/src/app/code-examples/modals/modal/modal.component.html
  apps/code-examples/src/app/code-examples/modals/modal/modal.component.ts
  apps/e2e/forms-storybook-e2e/src/e2e/checkbox.component.cy.ts
  apps/e2e/forms-storybook/src/app/checkbox/checkbox.component.html
  apps/e2e/forms-storybook/src/app/checkbox/checkbox.module.ts
  apps/playground/src/app/components/forms/checkbox/checkbox.component.html
  apps/playground/src/app/components/forms/checkbox/checkbox.component.ts
  libs/components/forms/src/assets/locales/resources_en_US.json
  libs/components/forms/src/lib/modules/checkbox/checkbox.component.html
  libs/components/forms/src/lib/modules/checkbox/checkbox.component.spec.ts
  libs/components/forms/src/lib/modules/checkbox/checkbox.component.ts
  libs/components/forms/src/lib/modules/checkbox/checkbox.module.ts
  libs/components/forms/src/lib/modules/form-error/form-errors.component.scss
  libs/components/forms/src/lib/modules/shared/sky-forms-resources.module.ts
  libs/components/forms/testing/src/checkbox/checkbox-harness.spec.ts
  libs/components/forms/testing/src/checkbox/checkbox-harness.ts
  libs/components/forms/testing/src/checkbox/fixtures/checkbox-harness-test.component.html
  libs/components/forms/testing/src/checkbox/fixtures/checkbox-harness-test.component.ts
Labels: risk level (author): 1

#1935 chore: update skyux-dev-infra to 9.0.0-alpha.18
  libs/sdk/eslint-config/peers.ts
  package-lock.json
  package.json
Labels: risk level (author): 1

#1936 fix(components/phone-field): phone field will switch to the correct country when a valid number for that country is given when the dial code matches multiple countries
  libs/components/phone-field/src/lib/modules/phone-field/phone-field.component.spec.ts
  libs/components/phone-field/src/lib/modules/phone-field/phone-field.component.ts
Labels: risk level (author): 3

#1930 chore: release 9.21.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#1938 fix(components/ag-grid): update focus style in data grid
  libs/components/ag-grid/src/lib/styles/_base.scss
Labels: risk level (author): 1

#1940 fix(components/colorpicker): updated color picker selection cursors to have accessible color contrast
  libs/components/colorpicker/src/lib/modules/colorpicker/colorpicker.component.scss
Labels: risk level (author): 2

#1943 chore(components/theme): update @skyux/icons to 6.8.0
  libs/components/ag-grid/package.json
  libs/components/packages/package.json
  libs/components/pages/package.json
  libs/components/storybook/package.json
  libs/components/theme/package.json
  libs/components/theme/src/lib/styles/sky.scss
  libs/sdk/e2e-schematics/package.json
  libs/sdk/tools/package.json
  package-lock.json
  package.json
Labels: risk level (author): 1

#1939 chore: release 9.21.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#1942 fix(components/colorpicker): rgba inputs are properly associated with each other
  libs/components/colorpicker/src/assets/locales/resources_en_US.json
  libs/components/colorpicker/src/lib/modules/colorpicker/colorpicker.component.html
  libs/components/colorpicker/src/lib/modules/colorpicker/colorpicker.component.scss
  libs/components/colorpicker/src/lib/modules/shared/sky-colorpicker-resources.module.ts
  package-lock.json
  package.json
Labels: risk level (author): 2

#1944 fix(components/forms): reactive form required validator sets required
  libs/components/forms/src/index.ts
  libs/components/forms/src/lib/modules/checkbox/checkbox-required-validator.directive.ts
  libs/components/forms/src/lib/modules/checkbox/checkbox.component.spec.ts
  libs/components/forms/src/lib/modules/checkbox/checkbox.component.ts
  libs/components/forms/src/lib/modules/checkbox/checkbox.module.ts
Labels: risk level (author): 1

#1946 chore(apps/playground): add character counter playground page
  apps/playground/src/app/components/forms/character-counter/character-counter-routing.module.ts
  apps/playground/src/app/components/forms/character-counter/character-counter.component.html
  apps/playground/src/app/components/forms/character-counter/character-counter.component.ts
  apps/playground/src/app/components/forms/character-counter/character-counter.module.ts
  apps/playground/src/app/components/forms/forms.module.ts
Labels: risk level (author): 1

#1945 chore: release 9.21.2
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#1950 refactor: move ESLint overrides to .eslintrc-overrides.json
  .eslintrc-overrides.json
  .eslintrc.json
  .nvmrc
  apps/e2e/ag-grid-storybook/.eslintrc.json
  apps/e2e/ag-grid-storybook/.storybook/manager.ts
  apps/e2e/ag-grid-storybook/src/app/shared/baseball-players-data.ts
  apps/e2e/angular-tree-component-storybook/.eslintrc.json
  apps/e2e/angular-tree-component-storybook/.storybook/manager.ts
  apps/e2e/datetime-storybook/src/app/datepicker/datepicker.component.ts
  apps/e2e/flyout-storybook/.eslintrc.json
  apps/e2e/flyout-storybook/.storybook/manager.ts
  apps/e2e/lists-storybook/src/polyfills.ts
  apps/e2e/lookup-storybook/src/app/autocomplete/autocomplete.component.ts
  apps/e2e/modals-storybook/.eslintrc.json
  apps/e2e/modals-storybook/.storybook/manager.ts
  apps/e2e/theme-storybook/.eslintrc.json
  apps/e2e/theme-storybook/.storybook/manager.ts
  apps/e2e/theme-storybook/src/app/switch-controls/switch-controls.component.ts
  apps/e2e/tiles-storybook/.eslintrc.json
  apps/e2e/tiles-storybook/.storybook/manager.ts
  libs/components/packages/src/schematics/migrations/update-9/ag-grid-29/ag-grid-29.schematic.spec.ts
  libs/components/packages/src/schematics/migrations/update-9/move-page-component/move-page-component.schematic.spec.ts
  libs/components/packages/src/schematics/utility/json-file.ts
  libs/sdk/e2e-schematics/src/workflow/percy-api/percy-api.ts
  libs/sdk/e2e-schematics/src/workflow/verify-e2e/verify-e2e.spec.ts
  package-lock.json
  package.json
Labels: risk level (author): 1

#1951 fix(components/toast): toast close buttons have distinct aria labels
  apps/integration-e2e/src/e2e/toast.cy.ts
  libs/components/toast/src/assets/locales/resources_en_US.json
  libs/components/toast/src/lib/modules/shared/sky-toast-resources.module.ts
  libs/components/toast/src/lib/modules/toast/toast.component.html
  libs/components/toast/src/lib/modules/toast/toast.component.ts
  libs/components/toast/testing/src/toast-fixture.ts
Labels: risk level (author): 1

#1957 fix(components/toast): toast close buttons have distinct aria labels (#1951)
  apps/integration-e2e/src/e2e/toast.cy.ts
  libs/components/toast/src/assets/locales/resources_en_US.json
  libs/components/toast/src/lib/modules/shared/sky-toast-resources.module.ts
  libs/components/toast/src/lib/modules/toast/toast.component.html
  libs/components/toast/src/lib/modules/toast/toast.component.ts
  libs/components/toast/testing/src/toast-fixture.ts
Labels: risk level (author): 1

#1958 chore(apps/playground): add popovers playground page
  apps/playground/src/app/components/popovers/popovers.module.ts
  apps/playground/src/app/components/popovers/popovers/popovers-routing.module.ts
  apps/playground/src/app/components/popovers/popovers/popovers.component.html
  apps/playground/src/app/components/popovers/popovers/popovers.component.ts
  apps/playground/src/app/components/popovers/popovers/popovers.module.ts
Labels: risk level (author): 1

#1960 chore(apps/playground): add popovers playground page (#1958)
  apps/playground/src/app/components/popovers/popovers.module.ts
  apps/playground/src/app/components/popovers/popovers/popovers-routing.module.ts
  apps/playground/src/app/components/popovers/popovers/popovers.component.html
  apps/playground/src/app/components/popovers/popovers/popovers.component.ts
  apps/playground/src/app/components/popovers/popovers/popovers.module.ts
Labels: risk level (author): 1

#1954 chore: setup 10.x.x prerelease
  .github/workflows/release-please.yml
Labels: risk level (author): 1

#1961 chore: setup 10.x.x prerelease with json api
  .github/workflows/release-please.yml
Labels: risk level (author): 1

#1959 chore: release 10.0.0-alpha.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#1962 chore: update skyux-dev-infra to 9.0.0-alpha.20
  package-lock.json
  package.json
Labels: risk level (author): 1

#1963 chore: update skyux-dev-infra to 9.0.0-alpha.20 for main
  package-lock.json
  package.json
Labels: risk level (author): 1

#1965 feat(components/forms): add checkbox labelText input
  apps/code-examples/src/app/code-examples/forms/checkbox/basic/demo.component.html
  apps/playground/src/app/components/forms/checkbox/checkbox.component.html
  libs/components/forms/src/lib/modules/checkbox/checkbox.component.html
  libs/components/forms/src/lib/modules/checkbox/checkbox.component.spec.ts
  libs/components/forms/src/lib/modules/checkbox/checkbox.component.ts
Labels: risk level (author): 1

#1966 feat(components/forms): add checkbox labelText input (#1965)
  apps/code-examples/src/app/code-examples/forms/checkbox/basic/demo.component.html
  apps/playground/src/app/components/forms/checkbox/checkbox.component.html
  libs/components/forms/src/lib/modules/checkbox/checkbox.component.html
  libs/components/forms/src/lib/modules/checkbox/checkbox.component.spec.ts
  libs/components/forms/src/lib/modules/checkbox/checkbox.component.ts
Labels: risk level (author): 1

#1967 fix(components/packages): standardize how schematics visit project files
  libs/components/packages/src/schematics/migrations/update-9/ag-grid-29/ag-grid-29.schematic.ts
  libs/components/packages/src/schematics/migrations/update-9/i18n-resources-module/i18n-resources-module.schematic.ts
  libs/components/packages/src/schematics/migrations/update-9/legacy-services/legacy-services.schematic.ts
  libs/components/packages/src/schematics/migrations/update-9/move-page-component/move-page-component.schematic.ts
  libs/components/packages/src/schematics/migrations/update-9/update-angular-tree-component/update-angular-tree-component.schematic.ts
  libs/components/packages/src/schematics/utility/visit-project-files.ts
Labels: risk level (author): 1

#1970 fix(components/packages): standardize how schematics visit project files (#1967)
  libs/components/packages/src/schematics/migrations/update-9/ag-grid-29/ag-grid-29.schematic.ts
  libs/components/packages/src/schematics/migrations/update-9/i18n-resources-module/i18n-resources-module.schematic.ts
  libs/components/packages/src/schematics/migrations/update-9/legacy-services/legacy-services.schematic.ts
  libs/components/packages/src/schematics/migrations/update-9/move-page-component/move-page-component.schematic.ts
  libs/components/packages/src/schematics/migrations/update-9/update-angular-tree-component/update-angular-tree-component.schematic.ts
  libs/components/packages/src/schematics/utility/visit-project-files.ts
Labels: risk level (author): 1

#1956 chore: release 9.22.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease 9.x.x: pending

#1971 chore: release 9.22.0 (#1956)
  CHANGELOG.md
Labels: risk level (author): 1, risk level (reviewer): 1

#1972 chore: setup compat-stylesheet schematic
  libs/components/packages/src/schematics/migrations/migration-collection.json
  libs/components/packages/src/schematics/migrations/update-10/add-compat-stylesheets/__snapshots__/add-compat-stylesheet.schematic.spec.ts.snap
  libs/components/packages/src/schematics/migrations/update-10/add-compat-stylesheets/add-compat-stylesheet.schematic.spec.ts
  libs/components/packages/src/schematics/migrations/update-10/add-compat-stylesheets/add-compat-stylesheet.schematic.ts
  libs/components/packages/src/schematics/migrations/update-10/i18n-resources-module/i18n-resources-module.schematic.spec.ts
  libs/components/packages/src/schematics/migrations/update-10/i18n-resources-module/i18n-resources-module.schematic.ts
  libs/components/packages/src/schematics/migrations/update-9/add-forms-popovers-peer-dependency/add-forms-popovers-peer-dependency.schematic.spec.ts
  libs/components/packages/src/schematics/migrations/update-9/add-forms-popovers-peer-dependency/add-forms-popovers-peer-dependency.schematic.ts
  libs/components/packages/src/schematics/migrations/update-9/ag-grid-29/ag-grid-29.schematic.spec.ts
  libs/components/packages/src/schematics/migrations/update-9/ag-grid-29/ag-grid-29.schematic.ts
  libs/components/packages/src/schematics/migrations/update-9/legacy-services/legacy-services.schematic.spec.ts
  libs/components/packages/src/schematics/migrations/update-9/legacy-services/legacy-services.schematic.ts
  libs/components/packages/src/schematics/migrations/update-9/move-page-component/move-page-component.schematic.spec.ts
  libs/components/packages/src/schematics/migrations/update-9/move-page-component/move-page-component.schematic.ts
  libs/components/packages/src/schematics/migrations/update-9/update-angular-tree-component/update-angular-tree-component.schematic.spec.ts
  libs/components/packages/src/schematics/migrations/update-9/update-angular-tree-component/update-angular-tree-component.schematic.ts
Labels: risk level (author): 1

#1973 feat(components/text-editor): update `dompurify` to `3.0.8`
  libs/components/text-editor/package.json
  package-lock.json
  package.json
Labels: risk level (author): 1

#1974 feat(components/autonumeric): update `autonumeric` to `4.10.4`
  libs/components/ag-grid/src/lib/modules/ag-grid/types/currency-properties.ts
  libs/components/autonumeric/package.json
  package-lock.json
  package.json
Labels: risk level (author): 1

#1975 feat(components/datetime): update `moment` to `2.30.1`
  libs/components/datetime/package.json
  package-lock.json
  package.json
Labels: risk level (author): 1

#1976 chore(components/packages): update autonumeric in packages
  libs/components/packages/package.json
Labels: risk level (author): 1
