Repository blackbaud/skyux, pull requests merged in 2024-07, with the labels that each got.

#2410 feat(components/indicators): add `helpKey`, `helpPopoverContent`, and `helpPopoverTitle` inputs to the key info component
  apps/code-examples/src/app/code-examples/indicators/key-info/basic/demo.component.html
  apps/code-examples/src/app/code-examples/indicators/key-info/basic/demo.component.spec.ts
  apps/code-examples/src/app/code-examples/indicators/key-info/inline-help/demo.component.html
  apps/code-examples/src/app/code-examples/indicators/key-info/inline-help/demo.component.spec.ts
  apps/code-examples/src/app/code-examples/indicators/key-info/inline-help/demo.component.ts
  apps/code-examples/src/app/features/indicators.module.ts
  apps/e2e/indicators-storybook/src/app/key-info/key-info.component.html
  apps/e2e/indicators-storybook/src/app/key-info/key-info.component.ts
  libs/components/indicators/src/lib/modules/key-info/fixtures/key-info.component.fixture.html
  libs/components/indicators/src/lib/modules/key-info/fixtures/key-info.component.fixture.ts
  libs/components/indicators/src/lib/modules/key-info/key-info-label.component.ts
  libs/components/indicators/src/lib/modules/key-info/key-info.component.html
  libs/components/indicators/src/lib/modules/key-info/key-info.component.spec.ts
  libs/components/indicators/src/lib/modules/key-info/key-info.component.ts
  libs/components/indicators/src/lib/modules/key-info/key-info.module.ts
Labels: risk level (author): 1

#2400 chore: release 10.32.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#2406 fix(components/datetime): fuzzy datepicker calendar updates appropriately when `futureDisabled` input is set after initialization
  apps/playground/src/app/components/datetime/datepicker/datepicker.component.html
  apps/playground/src/app/components/datetime/datepicker/datepicker.component.ts
  libs/components/datetime/src/lib/modules/datepicker/datepicker-input-fuzzy.directive.ts
  libs/components/datetime/src/lib/modules/datepicker/fuzzy-datepicker.component.spec.ts
Labels: risk level (author): 1

#2414 fix(components/help-inline): mark `labelledBy` input as "internal"
  libs/components/help-inline/src/lib/modules/help-inline/fixtures/help-inline.component.fixture.html
  libs/components/help-inline/src/lib/modules/help-inline/fixtures/help-inline.component.fixture.ts
  libs/components/help-inline/src/lib/modules/help-inline/help-inline-aria-controls.pipe.ts
  libs/components/help-inline/src/lib/modules/help-inline/help-inline-aria-haspopup.pipe.ts
  libs/components/help-inline/src/lib/modules/help-inline/help-inline.component.html
  libs/components/help-inline/src/lib/modules/help-inline/help-inline.component.scss
  libs/components/help-inline/src/lib/modules/help-inline/help-inline.component.ts
  libs/components/help-inline/testing/src/help-inline/help-inline-harness.ts
Labels: risk level (author): 1

#2413 feat(components/layout): add `helpKey`, `helpPopoverContent`, and `helpPopoverTitle` inputs to the description list component
  apps/code-examples/src/app/code-examples/layout/description-list/horizontal/demo.component.html
  apps/code-examples/src/app/code-examples/layout/description-list/horizontal/demo.component.ts
  apps/code-examples/src/app/code-examples/layout/description-list/inline-help/demo.component.html
  apps/code-examples/src/app/code-examples/layout/description-list/inline-help/demo.component.ts
  apps/code-examples/src/app/code-examples/layout/description-list/vertical/demo.component.html
  apps/code-examples/src/app/code-examples/layout/description-list/vertical/demo.component.ts
  apps/e2e/layout-storybook/src/app/app.module.ts
  apps/e2e/layout-storybook/src/app/description-list/description-list.component.html
  apps/e2e/layout-storybook/src/app/description-list/description-list.component.ts
  libs/components/layout/package.json
  libs/components/layout/src/lib/modules/description-list/description-list-content.component.ts
  libs/components/layout/src/lib/modules/description-list/description-list-term.component.html
  libs/components/layout/src/lib/modules/description-list/description-list-term.component.scss
  libs/components/layout/src/lib/modules/description-list/description-list-term.component.ts
  libs/components/layout/src/lib/modules/description-list/description-list.component.scss
  libs/components/layout/src/lib/modules/description-list/description-list.module.ts
Labels: risk level (author): 1

#2416 fix(code-examples): add mock help service provider to modal code example
  apps/code-examples/src/app/code-examples/modals/modal/basic-with-controller/demo.component.ts
  apps/code-examples/src/app/code-examples/modals/modal/basic-with-controller/help.service.ts
Labels: risk level (author): 1

#2377 build: add local registry option
  .verdaccio/config.yml
  libs/sdk/tools/project.json
  package-lock.json
  package.json
  scripts/publish-local.ts
Labels: risk level (author): 1

#2418 feat(components/forms): remove preview tags from new form field features
  libs/components/angular-tree-component/src/lib/modules/angular-tree/angular-tree-node.component.ts
  libs/components/colorpicker/src/lib/modules/colorpicker/colorpicker.component.ts
  libs/components/datetime/src/lib/modules/date-range-picker/date-range-picker.component.ts
  libs/components/forms/src/lib/modules/checkbox/checkbox-group.component.ts
  libs/components/forms/src/lib/modules/checkbox/checkbox.component.ts
  libs/components/forms/src/lib/modules/field-group/field-group.component.ts
  libs/components/forms/src/lib/modules/file-attachment/file-drop.component.ts
  libs/components/forms/src/lib/modules/input-box/input-box.component.ts
  libs/components/forms/src/lib/modules/radio/radio-group.component.ts
  libs/components/forms/src/lib/modules/radio/radio.component.ts
  libs/components/forms/src/lib/modules/toggle-switch/toggle-switch.component.ts
  libs/components/indicators/src/lib/modules/status-indicator/status-indicator.component.ts
  libs/components/modals/src/lib/modules/modal/modal.component.ts
  libs/components/progress-indicator/src/lib/modules/progress-indicator/progress-indicator-item/progress-indicator-item.component.ts
  libs/components/text-editor/src/lib/modules/text-editor/text-editor.component.ts
  libs/components/tiles/src/lib/modules/tiles/tile/tile.component.ts
Labels: risk level (author): 1

#2417 ci: retry e2e on scss module issue
  .github/workflows/e2e.yml
  libs/sdk/e2e-schematics/src/workflow/verify-e2e/verify-e2e.spec.ts
  libs/sdk/e2e-schematics/src/workflow/verify-e2e/verify-e2e.ts
Labels: risk level (author): 1, skip e2e

#2415 chore: release 10.33.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#2423 fix(code-examples): satisfy ESLint rules for action button and AG Grid code examples
  apps/code-examples/src/app/app.component.ts
  apps/code-examples/src/app/app.module.ts
  apps/code-examples/src/app/code-examples/ag-grid/data-entry-grid/basic/context-menu.component.ts
  apps/code-examples/src/app/code-examples/ag-grid/data-entry-grid/basic/data.ts
  apps/code-examples/src/app/code-examples/ag-grid/data-entry-grid/basic/demo.component.ts
  apps/code-examples/src/app/code-examples/ag-grid/data-entry-grid/basic/edit-modal.component.ts
  apps/code-examples/src/app/code-examples/ag-grid/data-entry-grid/data-manager-added/context-menu.component.ts
  apps/code-examples/src/app/code-examples/ag-grid/data-entry-grid/data-manager-added/demo.component.ts
  apps/code-examples/src/app/code-examples/ag-grid/data-entry-grid/data-manager-added/edit-modal.component.ts
  apps/code-examples/src/app/code-examples/ag-grid/data-entry-grid/data-manager-added/filter-modal.component.ts
  apps/code-examples/src/app/code-examples/ag-grid/data-entry-grid/data-manager-added/filters.ts
  apps/code-examples/src/app/code-examples/ag-grid/data-entry-grid/data-manager-added/view-grid.component.ts
  apps/code-examples/src/app/code-examples/ag-grid/data-entry-grid/inline-help/context-menu.component.ts
  apps/code-examples/src/app/code-examples/ag-grid/data-entry-grid/inline-help/data.ts
  apps/code-examples/src/app/code-examples/ag-grid/data-entry-grid/inline-help/demo.component.ts
  apps/code-examples/src/app/code-examples/ag-grid/data-entry-grid/inline-help/edit-modal.component.ts
  apps/code-examples/src/app/code-examples/ag-grid/data-grid/basic-multiselect/context-menu.component.ts
  apps/code-examples/src/app/code-examples/ag-grid/data-grid/basic-multiselect/demo.component.ts
  apps/code-examples/src/app/code-examples/ag-grid/data-grid/basic/context-menu.component.ts
  apps/code-examples/src/app/code-examples/ag-grid/data-grid/basic/demo.component.ts
  apps/code-examples/src/app/code-examples/ag-grid/data-grid/data-manager-multiselect/context-menu.component.ts
  apps/code-examples/src/app/code-examples/ag-grid/data-grid/data-manager-multiselect/demo.component.ts
  apps/code-examples/src/app/code-examples/ag-grid/data-grid/data-manager-multiselect/filter-modal.component.ts
  apps/code-examples/src/app/code-examples/ag-grid/data-grid/data-manager-multiselect/filters.ts
  apps/code-examples/src/app/code-examples/ag-grid/data-grid/data-manager-multiselect/view-grid.component.ts
  apps/code-examples/src/app/code-examples/ag-grid/data-grid/data-manager/context-menu.component.ts
  apps/code-examples/src/app/code-examples/ag-grid/data-grid/data-manager/demo.component.ts
  apps/code-examples/src/app/code-examples/ag-grid/data-grid/data-manager/filter-modal.component.ts
  apps/code-examples/src/app/code-examples/ag-grid/data-grid/data-manager/filters.ts
  apps/code-examples/src/app/code-examples/ag-grid/data-grid/data-manager/view-grid.component.ts
  apps/code-examples/src/app/code-examples/ag-grid/data-grid/inline-help/context-menu.component.ts
  apps/code-examples/src/app/code-examples/ag-grid/data-grid/inline-help/demo.component.ts
  apps/code-examples/src/app/code-examples/ag-grid/data-grid/paging/context-menu.component.ts
  apps/code-examples/src/app/code-examples/ag-grid/data-grid/paging/demo.component.ts
  apps/code-examples/src/app/code-examples/ag-grid/data-grid/top-scroll/context-menu.component.ts
  apps/code-examples/src/app/code-examples/ag-grid/data-grid/top-scroll/demo.component.ts
  apps/code-examples/src/app/code-examples/data-manager/data-manager/basic/demo.component.ts
  apps/code-examples/src/app/code-examples/data-manager/data-manager/basic/filter-modal.component.ts
  apps/code-examples/src/app/code-examples/data-manager/data-manager/basic/filters.ts
  apps/code-examples/src/app/code-examples/data-manager/data-manager/basic/view-grid.component.ts
  apps/code-examples/src/app/code-examples/data-manager/data-manager/basic/view-repeater.component.ts
  apps/code-examples/src/main.ts
Labels: risk level (author): 1

#2424 fix(code-examples): satisfy ESLint rules for colorpicker code examples
  apps/code-examples/src/app/code-examples/colorpicker/colorpicker/basic/demo.component.ts
  apps/code-examples/src/app/code-examples/colorpicker/colorpicker/programmatic/demo.component.ts
Labels: risk level (author): 1

#2430 chore: release 11.0.0-alpha.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#2425 fix(code-examples): satisfy ESLint rules for action button and AG Grid code examples (#2423)
  apps/code-examples/src/app/app.component.ts
  apps/code-examples/src/app/app.module.ts
  apps/code-examples/src/app/code-examples/ag-grid/data-entry-grid/basic/context-menu.component.ts
  apps/code-examples/src/app/code-examples/ag-grid/data-entry-grid/basic/data.ts
  apps/code-examples/src/app/code-examples/ag-grid/data-entry-grid/basic/demo.component.ts
  apps/code-examples/src/app/code-examples/ag-grid/data-entry-grid/basic/edit-modal.component.ts
  apps/code-examples/src/app/code-examples/ag-grid/data-entry-grid/data-manager-added/context-menu.component.ts
  apps/code-examples/src/app/code-examples/ag-grid/data-entry-grid/data-manager-added/demo.component.ts
  apps/code-examples/src/app/code-examples/ag-grid/data-entry-grid/data-manager-added/edit-modal.component.ts
  apps/code-examples/src/app/code-examples/ag-grid/data-entry-grid/data-manager-added/filter-modal.component.ts
  apps/code-examples/src/app/code-examples/ag-grid/data-entry-grid/data-manager-added/filters.ts
  apps/code-examples/src/app/code-examples/ag-grid/data-entry-grid/data-manager-added/view-grid.component.ts
  apps/code-examples/src/app/code-examples/ag-grid/data-entry-grid/inline-help/context-menu.component.ts
  apps/code-examples/src/app/code-examples/ag-grid/data-entry-grid/inline-help/data.ts
  apps/code-examples/src/app/code-examples/ag-grid/data-entry-grid/inline-help/demo.component.ts
  apps/code-examples/src/app/code-examples/ag-grid/data-entry-grid/inline-help/edit-modal.component.ts
  apps/code-examples/src/app/code-examples/ag-grid/data-grid/basic-multiselect/context-menu.component.ts
  apps/code-examples/src/app/code-examples/ag-grid/data-grid/basic-multiselect/demo.component.ts
  apps/code-examples/src/app/code-examples/ag-grid/data-grid/basic/context-menu.component.ts
  apps/code-examples/src/app/code-examples/ag-grid/data-grid/basic/demo.component.ts
  apps/code-examples/src/app/code-examples/ag-grid/data-grid/data-manager-multiselect/context-menu.component.ts
  apps/code-examples/src/app/code-examples/ag-grid/data-grid/data-manager-multiselect/demo.component.ts
  apps/code-examples/src/app/code-examples/ag-grid/data-grid/data-manager-multiselect/filter-modal.component.ts
  apps/code-examples/src/app/code-examples/ag-grid/data-grid/data-manager-multiselect/filters.ts
  apps/code-examples/src/app/code-examples/ag-grid/data-grid/data-manager-multiselect/view-grid.component.ts
  apps/code-examples/src/app/code-examples/ag-grid/data-grid/data-manager/context-menu.component.ts
  apps/code-examples/src/app/code-examples/ag-grid/data-grid/data-manager/demo.component.ts
  apps/code-examples/src/app/code-examples/ag-grid/data-grid/data-manager/filter-modal.component.ts
  apps/code-examples/src/app/code-examples/ag-grid/data-grid/data-manager/filters.ts
  apps/code-examples/src/app/code-examples/ag-grid/data-grid/data-manager/view-grid.component.ts
  apps/code-examples/src/app/code-examples/ag-grid/data-grid/inline-help/context-menu.component.ts
  apps/code-examples/src/app/code-examples/ag-grid/data-grid/inline-help/demo.component.ts
  apps/code-examples/src/app/code-examples/ag-grid/data-grid/paging/context-menu.component.ts
  apps/code-examples/src/app/code-examples/ag-grid/data-grid/paging/demo.component.ts
  apps/code-examples/src/app/code-examples/ag-grid/data-grid/top-scroll/context-menu.component.ts
  apps/code-examples/src/app/code-examples/ag-grid/data-grid/top-scroll/demo.component.ts
  apps/code-examples/src/app/code-examples/data-manager/data-manager/basic/demo.component.ts
  apps/code-examples/src/app/code-examples/data-manager/data-manager/basic/filter-modal.component.ts
  apps/code-examples/src/app/code-examples/data-manager/data-manager/basic/filters.ts
  apps/code-examples/src/app/code-examples/data-manager/data-manager/basic/view-grid.component.ts
  apps/code-examples/src/app/code-examples/data-manager/data-manager/basic/view-repeater.component.ts
  apps/code-examples/src/main.ts
Labels: risk level (author): 1

#2427 fix(code-examples): satisfy ESLint rules for datetime code examples
  apps/code-examples/src/app/code-examples/datetime/date-range-picker/custom-calculator/demo.component.ts
  apps/code-examples/src/app/code-examples/datetime/datepicker/basic/demo.component.html
  apps/code-examples/src/app/code-examples/datetime/datepicker/basic/demo.component.ts
  apps/code-examples/src/app/code-examples/datetime/datepicker/custom-dates/demo.component.html
  apps/code-examples/src/app/code-examples/datetime/datepicker/custom-dates/demo.component.ts
  apps/code-examples/src/app/code-examples/datetime/timepicker/basic/demo.component.ts
Labels: risk level (author): 1

#2433 feat(components/icon): add internal support for SVG-based icons
  .cspell.json
  apps/e2e/indicators-storybook-e2e/src/e2e/icon.component.cy.ts
  apps/e2e/indicators-storybook/src/app/icon/icon.component.html
  apps/playground/src/app/components/indicators/icon/icon-routing.module.ts
  apps/playground/src/app/components/indicators/icon/icon.component.html
  apps/playground/src/app/components/indicators/icon/icon.component.ts
  apps/playground/src/app/components/indicators/icon/icon.module.ts
  apps/playground/src/app/components/indicators/indicators.module.ts
  libs/components/icon/src/lib/icon/icon-svg-resolver.service.spec.ts
  libs/components/icon/src/lib/icon/icon-svg-resolver.service.ts
  libs/components/icon/src/lib/icon/icon-svg.component.html
  libs/components/icon/src/lib/icon/icon-svg.component.spec.ts
  libs/components/icon/src/lib/icon/icon-svg.component.ts
  libs/components/icon/src/lib/icon/icon-svg.default.component.scss
  libs/components/icon/src/lib/icon/icon-svg.modern.component.scss
  libs/components/icon/src/lib/icon/icon.component.html
  libs/components/icon/src/lib/icon/icon.component.ts
  libs/components/icon/src/lib/icon/icon.module.ts
Labels: risk level (author): 3

#2436 feat(components/icon): add internal support for SVG-based icons (#2433)
  .cspell.json
  apps/e2e/indicators-storybook-e2e/src/e2e/icon.component.cy.ts
  apps/e2e/indicators-storybook/src/app/icon/icon.component.html
  apps/playground/src/app/components/indicators/icon/icon-routing.module.ts
  apps/playground/src/app/components/indicators/icon/icon.component.html
  apps/playground/src/app/components/indicators/icon/icon.component.ts
  apps/playground/src/app/components/indicators/icon/icon.module.ts
  apps/playground/src/app/components/indicators/indicators.module.ts
  libs/components/icon/src/lib/icon/icon-svg-resolver.service.spec.ts
  libs/components/icon/src/lib/icon/icon-svg-resolver.service.ts
  libs/components/icon/src/lib/icon/icon-svg.component.html
  libs/components/icon/src/lib/icon/icon-svg.component.spec.ts
  libs/components/icon/src/lib/icon/icon-svg.component.ts
  libs/components/icon/src/lib/icon/icon-svg.default.component.scss
  libs/components/icon/src/lib/icon/icon-svg.modern.component.scss
  libs/components/icon/src/lib/icon/icon.component.html
  libs/components/icon/src/lib/icon/icon.component.ts
  libs/components/icon/src/lib/icon/icon.module.ts
Labels: risk level (author): 3

#2429 fix(code-examples): satisfy ESLint rules for colorpicker code examples (#2424)
  apps/code-examples/src/app/code-examples/colorpicker/colorpicker/basic/demo.component.ts
  apps/code-examples/src/app/code-examples/colorpicker/colorpicker/programmatic/demo.component.ts
Labels: risk level (author): 1

#2434 fix(code-examples): satisfy ESLint rules for datetime code examples (#2427)
  apps/code-examples/src/app/code-examples/datetime/date-range-picker/custom-calculator/demo.component.ts
  apps/code-examples/src/app/code-examples/datetime/datepicker/basic/demo.component.html
  apps/code-examples/src/app/code-examples/datetime/datepicker/basic/demo.component.ts
  apps/code-examples/src/app/code-examples/datetime/datepicker/custom-dates/demo.component.html
  apps/code-examples/src/app/code-examples/datetime/datepicker/custom-dates/demo.component.ts
  apps/code-examples/src/app/code-examples/datetime/timepicker/basic/demo.component.ts
Labels: risk level (author): 1

#2437 fix(components/forms): file attachment components report file size errors with appropriate orders of magnitude
  libs/components/forms/src/assets/locales/resources_en_US.json
  libs/components/forms/src/lib/modules/file-attachment/file-attachment.component.html
  libs/components/forms/src/lib/modules/file-attachment/file-attachment.component.spec.ts
  libs/components/forms/src/lib/modules/file-attachment/file-drop.component.html
  libs/components/forms/src/lib/modules/file-attachment/file-drop.component.spec.ts
  libs/components/forms/src/lib/modules/file-attachment/file-size.pipe.spec.ts
  libs/components/forms/src/lib/modules/file-attachment/file-size.pipe.ts
  libs/components/forms/src/lib/modules/shared/sky-forms-resources.module.ts
Labels: risk level (author): 2

#2438 fix(components/forms): file attachment components report file size errors with appropriate orders of magnitude (#2437)
  libs/components/forms/src/assets/locales/resources_en_US.json
  libs/components/forms/src/lib/modules/file-attachment/file-attachment.component.html
  libs/components/forms/src/lib/modules/file-attachment/file-attachment.component.spec.ts
  libs/components/forms/src/lib/modules/file-attachment/file-drop.component.html
  libs/components/forms/src/lib/modules/file-attachment/file-drop.component.spec.ts
  libs/components/forms/src/lib/modules/file-attachment/file-size.pipe.spec.ts
  libs/components/forms/src/lib/modules/file-attachment/file-size.pipe.ts
  libs/components/forms/src/lib/modules/shared/sky-forms-resources.module.ts
Labels: risk level (author): 2

#2420 fix(components/forms): improve default value handling for heading styles on form group components
  apps/playground/src/app/components/forms/radio/radio.component.html
  apps/playground/src/app/components/forms/radio/radio.component.ts
  libs/components/forms/src/lib/modules/checkbox/checkbox-group.component.spec.ts
  libs/components/forms/src/lib/modules/checkbox/checkbox-group.component.ts
  libs/components/forms/src/lib/modules/checkbox/fixtures/standard-checkbox-group.component.ts
  libs/components/forms/src/lib/modules/field-group/field-group.component.spec.ts
  libs/components/forms/src/lib/modules/field-group/field-group.component.ts
  libs/components/forms/src/lib/modules/field-group/fixtures/field-group.component.fixture.ts
  libs/components/forms/src/lib/modules/radio/fixtures/radio-group-reactive.component.fixture.ts
  libs/components/forms/src/lib/modules/radio/radio-group.component.spec.ts
  libs/components/forms/src/lib/modules/radio/radio-group.component.ts
Labels: risk level (author): 1

#2440 fix(components/forms): improve default value handling for heading styles on form group components (#2420)
  apps/playground/src/app/components/forms/radio/radio.component.html
  apps/playground/src/app/components/forms/radio/radio.component.ts
  libs/components/forms/src/lib/modules/checkbox/checkbox-group.component.spec.ts
  libs/components/forms/src/lib/modules/checkbox/checkbox-group.component.ts
  libs/components/forms/src/lib/modules/checkbox/fixtures/standard-checkbox-group.component.ts
  libs/components/forms/src/lib/modules/field-group/field-group.component.spec.ts
  libs/components/forms/src/lib/modules/field-group/field-group.component.ts
  libs/components/forms/src/lib/modules/field-group/fixtures/field-group.component.fixture.ts
  libs/components/forms/src/lib/modules/radio/fixtures/radio-group-reactive.component.fixture.ts
  libs/components/forms/src/lib/modules/radio/radio-group.component.spec.ts
  libs/components/forms/src/lib/modules/radio/radio-group.component.ts
Labels: risk level (author): 1

#2428 feat(components/help-inline): update documentation and deprecate `indicators/help-inline`
  apps/playground/src/app/app.module.ts
  apps/playground/src/app/components/help-inline/help-inline.component.html
  apps/playground/src/app/components/indicators/help-inline/help-inline.component.html
  apps/playground/src/app/components/indicators/help-inline/help-inline.component.ts
  apps/playground/src/app/components/indicators/help-inline/help-inline.module.ts
  apps/playground/src/app/components/indicators/indicators.module.ts
  libs/components/help-inline/src/lib/modules/help-inline/help-inline.component.ts
  libs/components/help-inline/testing/src/help-inline/help-inline-harness.ts
  libs/components/indicators/src/lib/modules/help-inline/help-inline.component.spec.ts
  libs/components/indicators/src/lib/modules/help-inline/help-inline.component.ts
Labels: risk level (author): 1

#2426 chore: release 10.34.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease 10.x.x: pending

#2431 chore: release 11.0.0-alpha.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#2444 fix(code-examples): satisfy ESLint rules for core, forms, indicators, and inline form code examples (#2432)
  apps/code-examples/src/app/code-examples/core/numeric/basic/demo.component.spec.ts
  apps/code-examples/src/app/code-examples/forms/character-count/demo.component.spec.ts
  apps/code-examples/src/app/code-examples/forms/file-attachment/basic/demo.component.ts
  apps/code-examples/src/app/code-examples/forms/input-box/basic/demo.component.spec.ts
  apps/code-examples/src/app/code-examples/forms/radio/standard/demo.component.ts
  apps/code-examples/src/app/code-examples/forms/selection-box/checkbox/demo.component.ts
  apps/code-examples/src/app/code-examples/forms/selection-box/radio/demo.component.ts
  apps/code-examples/src/app/code-examples/forms/single-file-attachment/basic/demo.component.ts
  apps/code-examples/src/app/code-examples/indicators/illustration/basic/illustration-demo-resolver.service.ts
  apps/code-examples/src/app/code-examples/indicators/tokens/custom/demo.component.spec.ts
  apps/code-examples/src/app/code-examples/indicators/wait/element/demo.component.spec.ts
  apps/code-examples/src/app/code-examples/indicators/wait/page/demo.component.spec.ts
  apps/code-examples/src/app/code-examples/indicators/wait/page/demo.component.ts
  apps/code-examples/src/app/code-examples/inline-form/inline-form/basic/demo.component.html
  apps/code-examples/src/app/code-examples/inline-form/inline-form/basic/demo.component.ts
  apps/code-examples/src/app/code-examples/inline-form/inline-form/custom-buttons/demo.component.html
  apps/code-examples/src/app/code-examples/inline-form/inline-form/custom-buttons/demo.component.ts
  apps/code-examples/src/app/code-examples/inline-form/inline-form/repeaters/demo.component.ts
Labels: risk level (author): 1

#2441 feat(components/help-inline): update documentation and deprecate `indicators/help-inline` (#2428)
  apps/playground/src/app/app.module.ts
  apps/playground/src/app/components/help-inline/help-inline.component.html
  apps/playground/src/app/components/indicators/help-inline/help-inline.component.html
  apps/playground/src/app/components/indicators/help-inline/help-inline.component.ts
  apps/playground/src/app/components/indicators/help-inline/help-inline.module.ts
  apps/playground/src/app/components/indicators/indicators.module.ts
  libs/components/help-inline/src/lib/modules/help-inline/help-inline.component.ts
  libs/components/help-inline/testing/src/help-inline/help-inline-harness.ts
  libs/components/indicators/src/lib/modules/help-inline/help-inline.component.spec.ts
  libs/components/indicators/src/lib/modules/help-inline/help-inline.component.ts
Labels: risk level (author): 1

#2442 chore: release 10.34.0 (#2426)
  CHANGELOG.md
Labels: risk level (author): 1, risk level (reviewer): 1

#2443 fix(components/phone-field): required phone field controls are not "touched" on initialization
  apps/e2e/phone-field-storybook/src/app/phone-field/phone-field.component.ts
  libs/components/phone-field/src/lib/modules/phone-field/phone-field-adapter.service.ts
  libs/components/phone-field/src/lib/modules/phone-field/phone-field-input.directive.ts
  libs/components/phone-field/src/lib/modules/phone-field/phone-field.component.html
  libs/components/phone-field/src/lib/modules/phone-field/phone-field.component.spec.ts
  libs/components/phone-field/src/lib/modules/phone-field/phone-field.component.ts
Labels: risk level (author): 3, risk level (reviewer): 3

#2449 build: update implicit dependencies for testing
  libs/components/indicators/testing/project.json
  libs/components/modals/testing/project.json
Labels: risk level (author): 1

#2452 ci: update changelog cherry-pick message (#2451)
  .github/workflows/cherry-pick.yml
  package-lock.json
  package.json
Labels: risk level (author): 1

#2435 fix(code-examples): satisfy ESLint rules for layout, lists, lookup, modals, pages, and others
  apps/code-examples/.eslintrc.json
  apps/code-examples/src/app/code-examples/layout/back-to-top/infinite-scroll/demo.component.ts
  apps/code-examples/src/app/code-examples/layout/box/basic/demo.component.spec.ts
  apps/code-examples/src/app/code-examples/lists/filter/modal/demo.component.ts
  apps/code-examples/src/app/code-examples/lists/infinite-scroll/repeater/demo.component.ts
  apps/code-examples/src/app/code-examples/lists/paging/with-content/demo.component.ts
  apps/code-examples/src/app/code-examples/lists/repeater/add-remove/demo.component.spec.ts
  apps/code-examples/src/app/code-examples/lists/repeater/inline-form/demo.component.ts
  apps/code-examples/src/app/code-examples/lists/sort/basic/demo.component.ts
  apps/code-examples/src/app/code-examples/lookup/autocomplete/advanced/demo.component.ts
  apps/code-examples/src/app/code-examples/lookup/autocomplete/custom-search/demo.component.ts
  apps/code-examples/src/app/code-examples/lookup/country-field/basic/demo.component.html
  apps/code-examples/src/app/code-examples/lookup/country-field/basic/demo.component.ts
  apps/code-examples/src/app/code-examples/lookup/lookup/add-item/demo.component.spec.ts
  apps/code-examples/src/app/code-examples/lookup/lookup/add-item/demo.component.ts
  apps/code-examples/src/app/code-examples/lookup/lookup/async/demo.component.spec.ts
  apps/code-examples/src/app/code-examples/lookup/lookup/async/demo.component.ts
  apps/code-examples/src/app/code-examples/lookup/lookup/custom-picker/demo.component.spec.ts
  apps/code-examples/src/app/code-examples/lookup/lookup/custom-picker/demo.component.ts
  apps/code-examples/src/app/code-examples/lookup/lookup/custom-picker/picker-modal.component.ts
  apps/code-examples/src/app/code-examples/lookup/lookup/multi-select/demo.component.ts
  apps/code-examples/src/app/code-examples/lookup/lookup/result-templates/demo.component.spec.ts
  apps/code-examples/src/app/code-examples/lookup/lookup/result-templates/demo.component.ts
  apps/code-examples/src/app/code-examples/lookup/lookup/single-select/demo.component.ts
  apps/code-examples/src/app/code-examples/lookup/search/basic/demo.component.ts
  apps/code-examples/src/app/code-examples/lookup/selection-modal/add-item/demo.component.spec.ts
  apps/code-examples/src/app/code-examples/lookup/selection-modal/add-item/demo.component.ts
  apps/code-examples/src/app/code-examples/lookup/selection-modal/basic/demo.component.spec.ts
  apps/code-examples/src/app/code-examples/modals/confirm/basic-with-controller/demo.component.spec.ts
  apps/code-examples/src/app/code-examples/modals/confirm/basic-with-harness/demo.component.spec.ts
  apps/code-examples/src/app/code-examples/modals/modal/basic-with-controller/demo.component.ts
  apps/code-examples/src/app/code-examples/modals/modal/basic-with-harness/demo.component.ts
  apps/code-examples/src/app/code-examples/modals/modal/with-error/demo.component.ts
  apps/code-examples/src/app/code-examples/modals/modal/with-error/modal.component.ts
  apps/code-examples/src/app/code-examples/pages/page/list-page-list-layout-demo/dashboards-grid-context-menu.component.ts
  apps/code-examples/src/app/code-examples/pages/page/list-page-list-layout-demo/demo.component.spec.ts
  apps/code-examples/src/app/code-examples/pages/page/list-page-list-layout-demo/item.ts
  apps/code-examples/src/app/code-examples/pages/page/list-page-list-layout-demo/list-page-content.component.ts
  apps/code-examples/src/app/code-examples/pages/page/list-page-tabs-layout-demo/contact-context-menu.component.ts
  apps/code-examples/src/app/code-examples/pages/page/list-page-tabs-layout-demo/contact.ts
  apps/code-examples/src/app/code-examples/pages/page/list-page-tabs-layout-demo/demo.component.spec.ts
  apps/code-examples/src/app/code-examples/pages/page/list-page-tabs-layout-demo/list-page-content.component.ts
  apps/code-examples/src/app/code-examples/pages/page/record-page-blocks-layout-demo/demo.component.spec.ts
  apps/code-examples/src/app/code-examples/pages/page/record-page-tabs-layout-demo/attachment.ts
  apps/code-examples/src/app/code-examples/pages/page/record-page-tabs-layout-demo/attachments-grid-context-menu.component.ts
  apps/code-examples/src/app/code-examples/pages/page/record-page-tabs-layout-demo/demo.component.spec.ts
  apps/code-examples/src/app/code-examples/pages/page/record-page-tabs-layout-demo/detail.ts
  apps/code-examples/src/app/code-examples/pages/page/record-page-tabs-layout-demo/record-page-attachments-tab.component.ts
  apps/code-examples/src/app/code-examples/pages/page/record-page-tabs-layout-demo/record-page-overview-tab.component.ts
  apps/code-examples/src/app/code-examples/pages/page/split-view-page-fit-layout-demo/demo.component.spec.ts
  apps/code-examples/src/app/code-examples/router/href/basic/custom-resolver/custom-sky-href-resolver.service.spec.ts
  apps/code-examples/src/app/code-examples/router/href/basic/custom-resolver/custom-sky-href-resolver.service.ts
  apps/code-examples/src/app/code-examples/split-view/split-view/basic/demo.component.ts
  apps/code-examples/src/app/code-examples/split-view/split-view/page-bound/demo.component.ts
  apps/code-examples/src/app/code-examples/tabs/sectioned-form/modal/information-form.component.ts
  apps/code-examples/src/app/code-examples/text-editor/text-editor/demo.component.ts
Labels: risk level (author): 1

#2456 ci: fix cherry-pick title
  .github/workflows/cherry-pick.yml
Labels: risk level (author): 1

#2455 ci: fix cherry-pick title
  .github/workflows/cherry-pick.yml
Labels: risk level (author): 1

#2457 fix(code-examples): satisfy ESLint rules for layout, lists, lookup, modals, pages, and others (#2435)
  apps/code-examples/.eslintrc.json
  apps/code-examples/src/app/code-examples/layout/back-to-top/infinite-scroll/demo.component.ts
  apps/code-examples/src/app/code-examples/layout/box/basic/demo.component.spec.ts
  apps/code-examples/src/app/code-examples/lists/filter/modal/demo.component.ts
  apps/code-examples/src/app/code-examples/lists/infinite-scroll/repeater/demo.component.ts
  apps/code-examples/src/app/code-examples/lists/paging/with-content/demo.component.ts
  apps/code-examples/src/app/code-examples/lists/repeater/add-remove/demo.component.spec.ts
  apps/code-examples/src/app/code-examples/lists/repeater/inline-form/demo.component.ts
  apps/code-examples/src/app/code-examples/lists/sort/basic/demo.component.ts
  apps/code-examples/src/app/code-examples/lookup/autocomplete/advanced/demo.component.ts
  apps/code-examples/src/app/code-examples/lookup/autocomplete/custom-search/demo.component.ts
  apps/code-examples/src/app/code-examples/lookup/country-field/basic/demo.component.html
  apps/code-examples/src/app/code-examples/lookup/country-field/basic/demo.component.ts
  apps/code-examples/src/app/code-examples/lookup/lookup/add-item/demo.component.spec.ts
  apps/code-examples/src/app/code-examples/lookup/lookup/add-item/demo.component.ts
  apps/code-examples/src/app/code-examples/lookup/lookup/async/demo.component.spec.ts
  apps/code-examples/src/app/code-examples/lookup/lookup/async/demo.component.ts
  apps/code-examples/src/app/code-examples/lookup/lookup/custom-picker/demo.component.spec.ts
  apps/code-examples/src/app/code-examples/lookup/lookup/custom-picker/demo.component.ts
  apps/code-examples/src/app/code-examples/lookup/lookup/custom-picker/picker-modal.component.ts
  apps/code-examples/src/app/code-examples/lookup/lookup/multi-select/demo.component.ts
  apps/code-examples/src/app/code-examples/lookup/lookup/result-templates/demo.component.spec.ts
  apps/code-examples/src/app/code-examples/lookup/lookup/result-templates/demo.component.ts
  apps/code-examples/src/app/code-examples/lookup/lookup/single-select/demo.component.ts
  apps/code-examples/src/app/code-examples/lookup/search/basic/demo.component.ts
  apps/code-examples/src/app/code-examples/lookup/selection-modal/add-item/demo.component.spec.ts
  apps/code-examples/src/app/code-examples/lookup/selection-modal/add-item/demo.component.ts
  apps/code-examples/src/app/code-examples/lookup/selection-modal/basic/demo.component.spec.ts
  apps/code-examples/src/app/code-examples/modals/confirm/basic-with-controller/demo.component.spec.ts
  apps/code-examples/src/app/code-examples/modals/confirm/basic-with-harness/demo.component.spec.ts
  apps/code-examples/src/app/code-examples/modals/modal/basic-with-controller/demo.component.ts
  apps/code-examples/src/app/code-examples/modals/modal/basic-with-harness/demo.component.ts
  apps/code-examples/src/app/code-examples/modals/modal/with-error/demo.component.ts
  apps/code-examples/src/app/code-examples/modals/modal/with-error/modal.component.ts
  apps/code-examples/src/app/code-examples/pages/page/list-page-list-layout-demo/dashboards-grid-context-menu.component.ts
  apps/code-examples/src/app/code-examples/pages/page/list-page-list-layout-demo/demo.component.spec.ts
  apps/code-examples/src/app/code-examples/pages/page/list-page-list-layout-demo/item.ts
  apps/code-examples/src/app/code-examples/pages/page/list-page-list-layout-demo/list-page-content.component.ts
  apps/code-examples/src/app/code-examples/pages/page/list-page-tabs-layout-demo/contact-context-menu.component.ts
  apps/code-examples/src/app/code-examples/pages/page/list-page-tabs-layout-demo/contact.ts
  apps/code-examples/src/app/code-examples/pages/page/list-page-tabs-layout-demo/demo.component.spec.ts
  apps/code-examples/src/app/code-examples/pages/page/list-page-tabs-layout-demo/list-page-content.component.ts
  apps/code-examples/src/app/code-examples/pages/page/record-page-blocks-layout-demo/demo.component.spec.ts
  apps/code-examples/src/app/code-examples/pages/page/record-page-tabs-layout-demo/attachment.ts
  apps/code-examples/src/app/code-examples/pages/page/record-page-tabs-layout-demo/attachments-grid-context-menu.component.ts
  apps/code-examples/src/app/code-examples/pages/page/record-page-tabs-layout-demo/demo.component.spec.ts
  apps/code-examples/src/app/code-examples/pages/page/record-page-tabs-layout-demo/detail.ts
  apps/code-examples/src/app/code-examples/pages/page/record-page-tabs-layout-demo/record-page-attachments-tab.component.ts
  apps/code-examples/src/app/code-examples/pages/page/record-page-tabs-layout-demo/record-page-overview-tab.component.ts
  apps/code-examples/src/app/code-examples/pages/page/split-view-page-fit-layout-demo/demo.component.spec.ts
  apps/code-examples/src/app/code-examples/router/href/basic/custom-resolver/custom-sky-href-resolver.service.spec.ts
  apps/code-examples/src/app/code-examples/router/href/basic/custom-resolver/custom-sky-href-resolver.service.ts
  apps/code-examples/src/app/code-examples/split-view/split-view/basic/demo.component.ts
  apps/code-examples/src/app/code-examples/split-view/split-view/page-bound/demo.component.ts
  apps/code-examples/src/app/code-examples/tabs/sectioned-form/modal/information-form.component.ts
  apps/code-examples/src/app/code-examples/text-editor/text-editor/demo.component.ts
Labels: risk level (author): 1

#2448 fix(components/phone-field): required phone field controls are not "touched" on initialization (#2443)
  apps/e2e/phone-field-storybook/src/app/phone-field/phone-field.component.ts
  libs/components/phone-field/src/lib/modules/phone-field/phone-field-adapter.service.ts
  libs/components/phone-field/src/lib/modules/phone-field/phone-field-input.directive.ts
  libs/components/phone-field/src/lib/modules/phone-field/phone-field.component.html
  libs/components/phone-field/src/lib/modules/phone-field/phone-field.component.spec.ts
  libs/components/phone-field/src/lib/modules/phone-field/phone-field.component.ts
Labels: risk level (author): 3, risk level (reviewer): 3

#2459 fix(components/datetime): ignore extraneous properties when setting calculator value
  libs/components/datetime/src/lib/modules/date-range-picker/date-range-picker.component.spec.ts
  libs/components/datetime/src/lib/modules/date-range-picker/date-range-picker.component.ts
Labels: risk level (author): 2

#2460 fix(components/datetime): ignore extraneous properties when setting calculator value (#2459)
  libs/components/datetime/src/lib/modules/date-range-picker/date-range-picker.component.spec.ts
  libs/components/datetime/src/lib/modules/date-range-picker/date-range-picker.component.ts
Labels: risk level (author): 2

#2450 feat(components/ag-grid): add support for AG Grid 31.3.2
  libs/components/ag-grid/package.json
  libs/components/ag-grid/src/lib/modules/ag-grid/ag-grid-data-manager-adapter.directive.spec.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/ag-grid-wrapper.component.spec.ts
  libs/components/packages/package.json
  libs/components/packages/src/schematics/ag-grid-migrate/ag-grid-migrate.schematic.spec.ts
  libs/components/packages/src/schematics/ag-grid-migrate/ag-grid-migrate.schematic.ts
  libs/components/packages/src/schematics/migrations/update-10/ag-grid/ag-grid.schematic.spec.ts
  libs/components/packages/src/schematics/migrations/update-10/ag-grid/ag-grid.schematic.ts
  package-lock.json
  package.json
Labels: risk level (author): 2

#2458 revert(components/help-inline): stop propagation of click events
  libs/components/help-inline/src/lib/modules/help-inline/help-inline.component.html
  libs/components/help-inline/src/lib/modules/help-inline/help-inline.component.spec.ts
  libs/components/help-inline/src/lib/modules/help-inline/help-inline.component.ts
Labels: risk level (author): 1

#2463 ci: fix cherry-pick title, one line
  .github/workflows/cherry-pick.yml
Labels: risk level (author): 1

#2461 ci: fix cherry-pick title, one line
  .github/workflows/cherry-pick.yml
Labels: risk level (author): 1

#2447 feat(components/datetime): add support for additional date formats to `SkyDatePipe`
  libs/components/datetime/src/lib/modules/date-pipe/date.service.spec.ts
  libs/components/datetime/src/lib/modules/date-pipe/date.service.ts
Labels: risk level (author): 2

#2467 chore(components/help-inline): split help-inline styles (#2464)
  apps/playground/src/app/components/help-inline/help-inline.component.html
  libs/components/help-inline/src/lib/modules/help-inline/help-inline.component.scss
  libs/components/help-inline/src/lib/modules/help-inline/help-inline.component.ts
  libs/components/help-inline/src/lib/modules/help-inline/help-inline.default.component.scss
  libs/components/help-inline/src/lib/modules/help-inline/help-inline.modern.component.scss
  libs/components/theme/src/lib/styles/_public-api/_mixins.scss
Labels: risk level (author): 1

#2462 revert(components/help-inline): stop propagation of click events (#2458)
  libs/components/help-inline/src/lib/modules/help-inline/help-inline.component.html
  libs/components/help-inline/src/lib/modules/help-inline/help-inline.component.spec.ts
  libs/components/help-inline/src/lib/modules/help-inline/help-inline.component.ts
Labels: risk level (author): 1

#2469 feat(components/datetime): add support for additional date formats to `SkyDatePipe` (#2447)
  libs/components/datetime/src/lib/modules/date-pipe/date.service.spec.ts
  libs/components/datetime/src/lib/modules/date-pipe/date.service.ts
Labels: risk level (author): 2

#2470 ci: fix cherry-pick title
  .github/workflows/cherry-pick.yml
Labels: risk level (author): 1

#2468 fix(components/tiles): do not expand/collapse content when help inline clicked
  libs/components/tiles/src/lib/modules/tiles/tile/tile.component.html
  libs/components/tiles/src/lib/modules/tiles/tile/tile.component.spec.ts
  libs/components/tiles/src/lib/modules/tiles/tile/tile.component.ts
Labels: risk level (author): 2

#2445 chore: release 10.35.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease 10.x.x: pending

#2472 chore: changelog for 10.35.0 (#2445) 🍒
  CHANGELOG.md
Labels: risk level (author): 1, risk level (reviewer): 1

#2471 fix(components/tiles): do not expand/collapse content when help inline clicked (#2468)
  libs/components/tiles/src/lib/modules/tiles/tile/tile.component.html
  libs/components/tiles/src/lib/modules/tiles/tile/tile.component.spec.ts
  libs/components/tiles/src/lib/modules/tiles/tile/tile.component.ts
Labels: risk level (author): 2

#2465 fix(components/lookup)!: lookup aria labels are now set appropriately when using the input box `labelText` input
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-editors/cell-editor-lookup/cell-editor-lookup.component.html
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-editors/cell-editor-lookup/cell-editor-lookup.component.spec.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-editors/cell-editor-lookup/cell-editor-lookup.component.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-editors/cell-editor-lookup/cell-editor-lookup.module.ts
  libs/components/forms/src/lib/modules/input-box/input-box-host.service.spec.ts
  libs/components/forms/src/lib/modules/input-box/input-box-host.service.ts
  libs/components/forms/src/lib/modules/input-box/input-box.component.html
  libs/components/forms/src/lib/modules/input-box/input-box.component.ts
  libs/components/lookup/src/lib/modules/lookup/fixtures/lookup-input-box.component.fixture.html
  libs/components/lookup/src/lib/modules/lookup/fixtures/lookup-input-box.component.fixture.ts
  libs/components/lookup/src/lib/modules/lookup/lookup.component.html
  libs/components/lookup/src/lib/modules/lookup/lookup.component.spec.ts
  libs/components/lookup/src/lib/modules/lookup/lookup.component.ts
Labels: risk level (author): 2

#2473 chore(components/indicators): split key info and illustration styles (#2466)
  libs/components/indicators/src/lib/modules/illustration/illustration.component.scss
  libs/components/indicators/src/lib/modules/illustration/illustration.component.ts
  libs/components/indicators/src/lib/modules/illustration/illustration.default.component.scss
  libs/components/indicators/src/lib/modules/illustration/illustration.modern.component.scss
  libs/components/indicators/src/lib/modules/key-info/key-info.component.ts
  libs/components/indicators/src/lib/modules/key-info/key-info.default.component.scss
  libs/components/indicators/src/lib/modules/key-info/key-info.modern.component.scss
Labels: risk level (author): 2

#2474 fix(components/icon): provide HTTP with interceptors
  libs/components/icon/src/lib/icon/icon.module.ts
Labels: risk level (author): 2

#2476 chore: release 10.35.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease 10.x.x: pending

#2477 chore: changelog for 10.35.1 (#2476) 🍒
  CHANGELOG.md
Labels: risk level (author): 1, risk level (reviewer): 1

#2475 fix(components/icon): provide HTTP with interceptors (#2474)
  libs/components/icon/src/lib/icon/icon.module.ts
Labels: risk level (author): 2

#2479 feat(components/icon): add icon stack visual tests
  apps/e2e/indicators-storybook/src/app/icon/icon.component.html
Labels: risk level (author): 1

#2439 feat(components/layout): add heading and inline help inputs to box component
  apps/code-examples/src/app/code-examples/layout/box/basic/demo.component.html
  apps/code-examples/src/app/code-examples/layout/box/basic/demo.component.spec.ts
  apps/code-examples/src/app/code-examples/layout/box/inline-help/demo.component.html
  apps/code-examples/src/app/code-examples/layout/box/inline-help/demo.component.ts
  apps/code-examples/src/app/features/layout.module.ts
  apps/code-examples/src/app/home/home.component.html
  apps/e2e/layout-storybook/src/app/box/box.component.html
  apps/e2e/layout-storybook/src/app/box/box.component.ts
  apps/playground/src/app/components/layout/box/box.component.html
  apps/playground/src/app/components/layout/box/box.component.ts
  libs/components/layout/src/index.ts
  libs/components/layout/src/lib/modules/box/box-header.component.ts
  libs/components/layout/src/lib/modules/box/box-heading-level.ts
  libs/components/layout/src/lib/modules/box/box-heading-style.ts
  libs/components/layout/src/lib/modules/box/box.component.html
  libs/components/layout/src/lib/modules/box/box.component.scss
  libs/components/layout/src/lib/modules/box/box.component.spec.ts
  libs/components/layout/src/lib/modules/box/box.component.ts
  libs/components/layout/src/lib/modules/box/box.module.ts
  libs/components/layout/src/lib/modules/box/fixtures/box.component.fixture.html
  libs/components/layout/src/lib/modules/box/fixtures/box.component.fixture.ts
  libs/components/layout/testing/src/box/box-harness.spec.ts
  libs/components/layout/testing/src/box/box-harness.ts
  libs/components/layout/testing/src/box/fixtures/box-harness-test.component.html
  libs/components/layout/testing/src/box/fixtures/box-harness-test.component.ts
  libs/components/layout/testing/src/box/fixtures/box-harness-test.module.ts
Labels: risk level (author): 2

#2482 feat(components/layout): add heading and inline help inputs to box component (#2439)
  apps/code-examples/src/app/code-examples/layout/box/basic/demo.component.html
  apps/code-examples/src/app/code-examples/layout/box/basic/demo.component.spec.ts
  apps/code-examples/src/app/code-examples/layout/box/inline-help/demo.component.html
  apps/code-examples/src/app/code-examples/layout/box/inline-help/demo.component.ts
  apps/code-examples/src/app/features/layout.module.ts
  apps/code-examples/src/app/home/home.component.html
  apps/e2e/layout-storybook/src/app/box/box.component.html
  apps/e2e/layout-storybook/src/app/box/box.component.ts
  apps/playground/src/app/components/layout/box/box.component.html
  apps/playground/src/app/components/layout/box/box.component.ts
  libs/components/layout/src/index.ts
  libs/components/layout/src/lib/modules/box/box-header.component.ts
  libs/components/layout/src/lib/modules/box/box-heading-level.ts
  libs/components/layout/src/lib/modules/box/box-heading-style.ts
  libs/components/layout/src/lib/modules/box/box.component.html
  libs/components/layout/src/lib/modules/box/box.component.scss
  libs/components/layout/src/lib/modules/box/box.component.spec.ts
  libs/components/layout/src/lib/modules/box/box.component.ts
  libs/components/layout/src/lib/modules/box/box.module.ts
  libs/components/layout/src/lib/modules/box/fixtures/box.component.fixture.html
  libs/components/layout/src/lib/modules/box/fixtures/box.component.fixture.ts
  libs/components/layout/testing/src/box/box-harness.spec.ts
  libs/components/layout/testing/src/box/box-harness.ts
  libs/components/layout/testing/src/box/fixtures/box-harness-test.component.html
  libs/components/layout/testing/src/box/fixtures/box-harness-test.component.ts
  libs/components/layout/testing/src/box/fixtures/box-harness-test.module.ts
Labels: risk level (author): 2

#2480 feat(components/icon): add icon stack visual tests (#2479)
  apps/e2e/indicators-storybook/src/app/icon/icon.component.html
Labels: risk level (author): 1

#2483 fix(components/packages): switch to `@ag-grid-devtools/cli` for AG Grid codemods
  libs/components/packages/src/schematics/ag-grid-migrate/ag-grid-migrate.schematic.spec.ts
  libs/components/packages/src/schematics/ag-grid-migrate/ag-grid-migrate.schematic.ts
  libs/components/packages/src/schematics/ag-grid-migrate/schema.ts
Labels: risk level (author): 1

#2478 feat(components/icon): use native fetch() for retrieving icon sprite
  libs/components/icon/src/lib/icon/icon-svg-resolver.service.spec.ts
  libs/components/icon/src/lib/icon/icon-svg-resolver.service.ts
  libs/components/icon/src/lib/icon/icon-svg.component.spec.ts
  libs/components/icon/src/lib/icon/icon.module.ts
Labels: risk level (author): 2

#2481 chore: release 10.36.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease 10.x.x: pending

#2484 feat(components/ag-grid): add support for AG Grid 31.3.2 (#2450)
  libs/components/ag-grid/package.json
  libs/components/ag-grid/src/lib/modules/ag-grid/ag-grid-data-manager-adapter.directive.spec.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/ag-grid-wrapper.component.spec.ts
  libs/components/packages/package.json
  libs/components/packages/src/schematics/ag-grid-migrate/ag-grid-migrate.schematic.spec.ts
  libs/components/packages/src/schematics/ag-grid-migrate/ag-grid-migrate.schematic.ts
  libs/components/packages/src/schematics/migrations/update-10/ag-grid/ag-grid.schematic.spec.ts
  libs/components/packages/src/schematics/migrations/update-10/ag-grid/ag-grid.schematic.ts
  package-lock.json
  package.json
Labels: risk level (author): 1

#2486 chore: changelog for 10.36.0 (#2481) 🍒
  CHANGELOG.md
Labels: risk level (author): 1, risk level (reviewer): 1

#2485 feat(components/icon): use native fetch() for retrieving icon sprite (#2478)
  libs/components/icon/src/lib/icon/icon-svg-resolver.service.spec.ts
  libs/components/icon/src/lib/icon/icon-svg-resolver.service.ts
  libs/components/icon/src/lib/icon/icon-svg.component.spec.ts
  libs/components/icon/src/lib/icon/icon.module.ts
Labels: risk level (author): 2

#2487 fix(components/packages): switch to `@ag-grid-devtools/cli` for AG Grid codemods (#2483)
  libs/components/packages/src/schematics/ag-grid-migrate/ag-grid-migrate.schematic.spec.ts
  libs/components/packages/src/schematics/ag-grid-migrate/ag-grid-migrate.schematic.ts
  libs/components/packages/src/schematics/ag-grid-migrate/schema.ts
Labels: risk level (author): 1

#2446 chore: release 11.0.0-alpha.2
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#2488 chore: reset schematics
  libs/components/packages/src/schematics/migrations/migration-collection.json
  libs/components/packages/src/schematics/migrations/update-10/add-compat-stylesheets/__snapshots__/add-compat-stylesheet.schematic.spec.ts.snap
  libs/components/packages/src/schematics/migrations/update-10/add-compat-stylesheets/add-compat-stylesheet.schematic.spec.ts
  libs/components/packages/src/schematics/migrations/update-10/add-compat-stylesheets/add-compat-stylesheet.schematic.ts
  libs/components/packages/src/schematics/migrations/update-10/add-forms-help-inline-peer-dependency/add-forms-help-inline-peer-dependency.schematic.spec.ts
  libs/components/packages/src/schematics/migrations/update-10/add-forms-help-inline-peer-dependency/add-forms-help-inline-peer-dependency.schematic.ts
  libs/components/packages/src/schematics/migrations/update-10/add-indicators-help-inline-peer-dependency/add-indicators-help-inline-peer-dependency.schematic.spec.ts
  libs/components/packages/src/schematics/migrations/update-10/add-indicators-help-inline-peer-dependency/add-indicators-help-inline-peer-dependency.schematic.ts
  libs/components/packages/src/schematics/migrations/update-10/ag-grid/__snapshots__/ag-grid.schematic.spec.ts.snap
  libs/components/packages/src/schematics/migrations/update-10/ag-grid/ag-grid-codemod-task.ts
  libs/components/packages/src/schematics/migrations/update-10/ag-grid/ag-grid.schematic.spec.ts
  libs/components/packages/src/schematics/migrations/update-10/ag-grid/ag-grid.schematic.ts
  libs/components/packages/src/schematics/migrations/update-10/axe-core/axe-core.schematic.spec.ts
  libs/components/packages/src/schematics/migrations/update-10/axe-core/axe-core.schematic.ts
  libs/components/packages/src/schematics/migrations/update-10/confirm-instance-observable/confirm-instance-observable.schematic.spec.ts
  libs/components/packages/src/schematics/migrations/update-10/confirm-instance-observable/confirm-instance-observable.schematic.ts
  libs/components/packages/src/schematics/migrations/update-10/remove-nx-cache/remove-nx-cache.schematic.spec.ts
  libs/components/packages/src/schematics/migrations/update-10/remove-nx-cache/remove-nx-cache.schematic.ts
  libs/components/packages/src/schematics/migrations/update-10/rename-harness-queries/rename-harness-queries.schematic.test.ts
  libs/components/packages/src/schematics/migrations/update-10/rename-harness-queries/rename-harness-queries.schematic.ts
  libs/components/packages/src/schematics/migrations/update-10/rename-tabset-tabindex/rename-tabset-tabindex.schematic.spec.ts
  libs/components/packages/src/schematics/migrations/update-10/rename-tabset-tabindex/rename-tabset-tabindex.schematic.ts
  libs/components/packages/src/schematics/migrations/update-11/i18n-resources-module/i18n-resources-module.schematic.spec.ts
  libs/components/packages/src/schematics/migrations/update-11/i18n-resources-module/i18n-resources-module.schematic.ts
  libs/components/packages/src/schematics/migrations/update-11/remove-old-compat-stylesheets/remove-old-compat-stylesheets.schematic.spec.ts
  libs/components/packages/src/schematics/migrations/update-11/remove-old-compat-stylesheets/remove-old-compat-stylesheets.schematic.ts
Labels: risk level (author): 1

#2490 chore(components/indicators): move help inline and icon code examples out
  apps/code-examples/src/app/app-routing.module.ts
  apps/code-examples/src/app/code-examples/help-inline/basic/demo.component.html
  apps/code-examples/src/app/code-examples/help-inline/basic/demo.component.spec.ts
  apps/code-examples/src/app/code-examples/help-inline/basic/demo.component.ts
  apps/code-examples/src/app/code-examples/icon/basic/demo.component.html
  apps/code-examples/src/app/code-examples/icon/basic/demo.component.spec.ts
  apps/code-examples/src/app/code-examples/icon/basic/demo.component.ts
  apps/code-examples/src/app/code-examples/icon/icon-button/demo.component.html
  apps/code-examples/src/app/code-examples/icon/icon-button/demo.component.spec.ts
  apps/code-examples/src/app/code-examples/icon/icon-button/demo.component.ts
  apps/code-examples/src/app/features/help-inline.module.ts
  apps/code-examples/src/app/features/icon.module.ts
  apps/code-examples/src/app/features/indicators.module.ts
  apps/code-examples/src/app/home/home.component.html
Labels: risk level (author): 1

#2493 chore(components/indicators): move help inline and icon code examples out (#2490)
  apps/code-examples/src/app/app-routing.module.ts
  apps/code-examples/src/app/code-examples/help-inline/basic/demo.component.html
  apps/code-examples/src/app/code-examples/help-inline/basic/demo.component.spec.ts
  apps/code-examples/src/app/code-examples/help-inline/basic/demo.component.ts
  apps/code-examples/src/app/code-examples/icon/basic/demo.component.html
  apps/code-examples/src/app/code-examples/icon/basic/demo.component.spec.ts
  apps/code-examples/src/app/code-examples/icon/basic/demo.component.ts
  apps/code-examples/src/app/code-examples/icon/icon-button/demo.component.html
  apps/code-examples/src/app/code-examples/icon/icon-button/demo.component.spec.ts
  apps/code-examples/src/app/code-examples/icon/icon-button/demo.component.ts
  apps/code-examples/src/app/features/help-inline.module.ts
  apps/code-examples/src/app/features/icon.module.ts
  apps/code-examples/src/app/features/indicators.module.ts
  apps/code-examples/src/app/home/home.component.html
Labels: risk level (author): 1

#2491 feat(components/ag-grid): add support for AG Grid 31.3.4
  libs/components/ag-grid/package.json
  libs/components/layout/testing/project.json
  libs/components/packages/package.json
  libs/components/packages/src/schematics/ag-grid-migrate/ag-grid-migrate.schematic.spec.ts
  libs/components/packages/src/schematics/ag-grid-migrate/ag-grid-migrate.schematic.ts
  libs/components/packages/src/schematics/migrations/update-10/ag-grid/ag-grid.schematic.spec.ts
  libs/components/packages/src/schematics/migrations/update-10/ag-grid/ag-grid.schematic.ts
  package-lock.json
  package.json
Labels: risk level (author): 1

#2494 chore: release 10.37.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease 10.x.x: pending

#2496 chore(components/icon): icon stack overrides visual tests
  apps/e2e/indicators-storybook/src/app/icon/icon.component.html
  libs/components/icon/src/lib/icon/icon-stack.component.scss
Labels: risk level (author): 1

#2495 chore: changelog for 10.37.0 (#2494) 🍒
  CHANGELOG.md
Labels: risk level (author): 1, risk level (reviewer): 1

#2498 chore(components/icon): icon stack overrides visual tests (#2496)
  apps/e2e/indicators-storybook/src/app/icon/icon.component.html
  libs/components/icon/src/lib/icon/icon-stack.component.scss
Labels: risk level (author): 1

#2492 fix(components/lists): reorderable repeater will not throw a warning when no repeater items exist
  libs/components/lists/src/lib/modules/repeater/fixtures/repeater.component.fixture.ts
  libs/components/lists/src/lib/modules/repeater/repeater.component.spec.ts
  libs/components/lists/src/lib/modules/repeater/repeater.component.ts
Labels: risk level (author): 2

#2501 fix(components/lists): reorderable repeater will not throw a warning when no repeater items exist (#2492)
  libs/components/lists/src/lib/modules/repeater/fixtures/repeater.component.fixture.ts
  libs/components/lists/src/lib/modules/repeater/repeater.component.spec.ts
  libs/components/lists/src/lib/modules/repeater/repeater.component.ts
Labels: risk level (author): 2

#2489 feat(components/packages): schematic to update `async()` tests to use `waitForAsync()`
  libs/components/packages/package.json
  libs/components/packages/src/schematics/migrations/migration-collection.json
  libs/components/packages/src/schematics/migrations/update-11/ng-wait-for-async-test/ng-wait-for-async-test.schematic.spec.ts
  libs/components/packages/src/schematics/migrations/update-11/ng-wait-for-async-test/ng-wait-for-async-test.schematic.ts
Labels: risk level (author): 1

#2503 fix(sdk/testing): `expectAsync` type includes async matchers from Jasmine
  libs/sdk/testing/src/lib/matchers/matchers.spec.ts
  libs/sdk/testing/src/lib/matchers/matchers.ts
Labels: risk level (author): 2

#2499 feat(components/ag-grid): add support for AG Grid 31.3.4 (#2491)
  libs/components/ag-grid/package.json
  libs/components/layout/testing/project.json
  libs/components/packages/package.json
  libs/components/packages/src/schematics/ag-grid-migrate/ag-grid-migrate.schematic.spec.ts
  libs/components/packages/src/schematics/ag-grid-migrate/ag-grid-migrate.schematic.ts
  libs/components/packages/src/schematics/migrations/update-11/ag-grid/__snapshots__/ag-grid.schematic.spec.ts.snap
  libs/components/packages/src/schematics/migrations/update-11/ag-grid/ag-grid-codemod-task.ts
  libs/components/packages/src/schematics/migrations/update-11/ag-grid/ag-grid.schematic.spec.ts
  libs/components/packages/src/schematics/migrations/update-11/ag-grid/ag-grid.schematic.ts
  package-lock.json
  package.json
Labels: risk level (author): 1

#2505 fix(components/layout): box headingHidden input shouldn't hide controls component
  libs/components/layout/src/lib/modules/box/box.component.html
  libs/components/layout/testing/src/box/box-harness.spec.ts
  libs/components/layout/testing/src/box/box-harness.ts
Labels: risk level (author): 1

#2506 fix(components/help-inline): add schematic for missing popovers peer which may be missing due to the package being added by schematic
  libs/components/packages/src/schematics/migrations/migration-collection.json
  libs/components/packages/src/schematics/migrations/update-10/add-help-inline-popovers-peer-dependency/add-help-inline-popovers-peer-dependency.schematic.spec.ts
  libs/components/packages/src/schematics/migrations/update-10/add-help-inline-popovers-peer-dependency/add-help-inline-popovers-peer-dependency.schematic.ts
Labels: risk level (author): 1

#2500 chore: release 10.37.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease 10.x.x: pending

#2508 chore: changelog for 10.37.1 (#2500) 🍒
  CHANGELOG.md
Labels: risk level (author): 1, risk level (reviewer): 1

#2507 fix(components/layout): box headingHidden input shouldn't hide controls component (#2505)
  libs/components/layout/src/lib/modules/box/box.component.html
  libs/components/layout/testing/src/box/box-harness.spec.ts
  libs/components/layout/testing/src/box/box-harness.ts
Labels: risk level (author): 1

#2502 chore: release 11.0.0-alpha.3
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#2509 fix(components/packages): additional error handling for AG Grid schematic
  libs/components/packages/src/schematics/ag-grid-migrate/ag-grid-migrate.schematic.spec.ts
  libs/components/packages/src/schematics/ag-grid-migrate/ag-grid-migrate.schematic.ts
  libs/components/packages/src/schematics/ag-grid-migrate/schema.json
Labels: risk level (author): 1

#2511 chore: release 10.37.2
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease 10.x.x: pending

#2513 chore: changelog for 10.37.2 (#2511) 🍒
  CHANGELOG.md
Labels: risk level (author): 1, risk level (reviewer): 1

#2512 fix(components/packages): additional error handling for AG Grid schematic (#2509)
  libs/components/packages/src/schematics/ag-grid-migrate/ag-grid-migrate.schematic.spec.ts
  libs/components/packages/src/schematics/ag-grid-migrate/ag-grid-migrate.schematic.ts
  libs/components/packages/src/schematics/ag-grid-migrate/schema.json
Labels: risk level (author): 1

#2515 fix(components/layout): remove onpush change detection from description list term to dynamically detect inline help inputs from description list content
  apps/playground/src/app/components/layout/description-list/description-list.component.html
  apps/playground/src/app/components/layout/description-list/description-list.component.ts
  libs/components/layout/src/lib/modules/description-list/description-list-term.component.ts
Labels: risk level (author): 1

#2516 fix(components/layout): remove onpush change detection from description list term to dynamically detect inline help inputs from description list content (#2515)
  apps/playground/src/app/components/layout/description-list/description-list.component.html
  apps/playground/src/app/components/layout/description-list/description-list.component.ts
  libs/components/layout/src/lib/modules/description-list/description-list-term.component.ts
Labels: risk level (author): 1

#2517 chore: release 10.37.3
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease 10.x.x: pending

#2510 build: remove sandbox override
  karma.conf.js
Labels: risk level (author): 1

#2519 build: remove sandbox override (#2510)
  karma.conf.js
Labels: risk level (author): 1

#2520 chore(components/indicators): chevron split scss stylesheets
  libs/components/indicators/src/lib/modules/chevron/chevron.component.ts
  libs/components/indicators/src/lib/modules/chevron/chevron.default.component.scss
  libs/components/indicators/src/lib/modules/chevron/chevron.modern.component.scss
Labels: risk level (author): 2

#2521 feat: support Angular 18.1.1
  apps/code-examples/src/app/code-examples/lookup/autocomplete/custom-search/demo.component.ts
  apps/code-examples/src/app/code-examples/lookup/lookup/custom-picker/picker-modal.component.ts
  apps/playground/src/app/components/datetime/datepicker/datepicker.component.ts
  libs/components/a11y/package.json
  libs/components/action-bars/package.json
  libs/components/ag-grid/package.json
  libs/components/angular-tree-component/package.json
  libs/components/animations/package.json
  libs/components/assets/package.json
  libs/components/autonumeric/package.json
  libs/components/avatar/package.json
  libs/components/colorpicker/package.json
  libs/components/config/package.json
  libs/components/core/package.json
  libs/components/data-manager/package.json
  libs/components/datetime/package.json
  libs/components/errors/package.json
  libs/components/flyout/package.json
  libs/components/forms/package.json
  libs/components/grids/package.json
  libs/components/help-inline/package.json
  libs/components/i18n/package.json
  libs/components/i18n/src/lib/modules/i18n/currency/currency-format.service.ts
  libs/components/i18n/src/lib/modules/i18n/intl-number-formatter.ts
  libs/components/icon/package.json
  libs/components/indicators/package.json
  libs/components/inline-form/package.json
  libs/components/layout/package.json
  libs/components/list-builder-common/package.json
  libs/components/list-builder-view-checklist/package.json
  libs/components/list-builder-view-grids/package.json
  libs/components/list-builder/package.json
  libs/components/lists/package.json
  libs/components/lookup/package.json
  libs/components/modals/package.json
  libs/components/navbar/package.json
  libs/components/omnibar-interop/package.json
  libs/components/packages/package.json
  libs/components/pages/package.json
  libs/components/phone-field/package.json
  libs/components/popovers/package.json
  libs/components/progress-indicator/package.json
  libs/components/router/package.json
  libs/components/select-field/package.json
  libs/components/split-view/package.json
  libs/components/storybook/package.json
  libs/components/tabs/package.json
  libs/components/text-editor/package.json
  libs/components/theme/package.json
  libs/components/theme/src/lib/styles/sky.scss
  libs/components/tiles/package.json
  libs/components/toast/package.json
  libs/components/validation/package.json
  libs/sdk/e2e-schematics/package.json
  libs/sdk/eslint-config/package.json
  libs/sdk/prettier-schematics/package.json
  libs/sdk/testing/package.json
  libs/sdk/tools/package.json
  package-lock.json
  package.json
Labels: risk level (author): 1

#2523 fix(components/i18n): switch to string union type
  libs/components/i18n/src/lib/modules/i18n/intl-number-formatter.ts
Labels: risk level (author): 1

#2514 chore: release 11.0.0-alpha.4
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#2524 fix(components/packages): check for existing `waitForAsync` import
  libs/components/packages/src/schematics/migrations/update-11/ng-wait-for-async-test/ng-wait-for-async-test.schematic.spec.ts
  libs/components/packages/src/schematics/migrations/update-11/ng-wait-for-async-test/ng-wait-for-async-test.schematic.ts
Labels: risk level (author): 1

#2522 chore(components/indicators): chevron split scss stylesheets (#2520)
  libs/components/indicators/src/lib/modules/chevron/chevron.component.ts
  libs/components/indicators/src/lib/modules/chevron/chevron.default.component.scss
  libs/components/indicators/src/lib/modules/chevron/chevron.modern.component.scss
Labels: risk level (author): 2

#2525 chore: release 11.0.0-alpha.5
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#2526 fix(components/indicators): hide illustration while loading
  libs/components/indicators/src/lib/modules/illustration/illustration.component.html
  libs/components/indicators/src/lib/modules/illustration/illustration.component.spec.ts
  libs/components/indicators/src/lib/modules/illustration/illustration.default.component.scss
  libs/components/indicators/src/lib/modules/illustration/illustration.modern.component.scss
Labels: risk level (author): 2

#2527 fix(components/tiles): remove `::ng-deep` from tile styles
  libs/components/tiles/src/lib/modules/tiles/tile-content/tile-content-section.component.scss
  libs/components/tiles/src/lib/modules/tiles/tile-content/tile-content.component.scss
  libs/components/tiles/src/lib/modules/tiles/tile-content/tile-content.component.ts
  libs/components/tiles/src/lib/modules/tiles/tile-dashboard/tile-dashboard.component.scss
  libs/components/tiles/src/lib/modules/tiles/tile/tile.component.scss
Labels: risk level (author): 3

#2533 fix!: use `booleanAttribute` transform instead of `SkyFormsUtility.coerceBooleanProperty` on boolean inputs
  libs/components/core/src/lib/modules/forms-utility/forms-utility.ts
  libs/components/forms/src/lib/modules/checkbox/checkbox.component.ts
  libs/components/forms/src/lib/modules/file-attachment/file-attachment.component.ts
  libs/components/forms/src/lib/modules/radio/radio-group.component.ts
  libs/components/forms/src/lib/modules/radio/radio.component.ts
  libs/components/text-editor/src/lib/modules/text-editor/menubar/text-editor-menubar.component.ts
  libs/components/text-editor/src/lib/modules/text-editor/text-editor.component.ts
  libs/components/text-editor/src/lib/modules/text-editor/toolbar/text-editor-toolbar.component.ts
Labels: risk level (author): 2

#2531 chore: release 10.37.4
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease 10.x.x: pending

#2535 chore: changelog for 10.37.4 (#2531) 🍒
  CHANGELOG.md
Labels: risk level (author): 1, risk level (reviewer): 1

#2532 fix(components/tiles): remove `::ng-deep` from tile styles (#2527)
  libs/components/tiles/src/lib/modules/tiles/tile-content/tile-content-section.component.scss
  libs/components/tiles/src/lib/modules/tiles/tile-content/tile-content.component.scss
  libs/components/tiles/src/lib/modules/tiles/tile-content/tile-content.component.ts
  libs/components/tiles/src/lib/modules/tiles/tile-dashboard/tile-dashboard.component.scss
  libs/components/tiles/src/lib/modules/tiles/tile/tile.component.scss
Labels: risk level (author): 3

#2536 fix(components/datetime): resources strings for default calculators are not resolved in the service
  libs/components/datetime/src/lib/modules/date-range-picker/date-range.service.spec.ts
  libs/components/datetime/src/lib/modules/date-range-picker/date-range.service.ts
Labels: risk level (author): 3

#2530 fix(components/indicators): hide illustration while loading (#2526)
  libs/components/indicators/src/lib/modules/illustration/illustration.component.html
  libs/components/indicators/src/lib/modules/illustration/illustration.component.spec.ts
  libs/components/indicators/src/lib/modules/illustration/illustration.default.component.scss
  libs/components/indicators/src/lib/modules/illustration/illustration.modern.component.scss
Labels: risk level (author): 2

#2540 build: disable html trailing commas to avoid cherry-pick conflicts
  .prettierrc
  libs/components/ag-grid/src/lib/modules/ag-grid/ag-grid-row-delete.component.ts
  libs/components/core/src/lib/modules/affix/affixer.spec.ts
  libs/components/forms/src/lib/modules/file-attachment/file-attachment.component.html
  libs/components/forms/src/lib/modules/file-attachment/file-drop.component.html
  libs/components/forms/src/lib/modules/input-box/input-box.component.html
  libs/components/help-inline/src/lib/modules/help-inline/help-inline.component.html
  libs/components/indicators/src/lib/modules/illustration/illustration.component.html
  libs/components/layout/src/lib/modules/box/box.component.html
  libs/components/lookup/src/lib/modules/lookup/lookup.component.html
  libs/components/phone-field/src/lib/modules/phone-field/phone-field.component.html
  libs/components/tiles/src/lib/modules/tiles/tile/tile.component.html
Labels: risk level (author): 1

#2537 feat(components/core): add scroll shadow directive
  libs/components/core/src/index.ts
  libs/components/core/src/lib/modules/scroll-shadow/fixtures/scroll-shadow.component.fixture.html
  libs/components/core/src/lib/modules/scroll-shadow/fixtures/scroll-shadow.component.fixture.scss
  libs/components/core/src/lib/modules/scroll-shadow/fixtures/scroll-shadow.component.fixture.ts
  libs/components/core/src/lib/modules/scroll-shadow/scroll-shadow-event-args.ts
  libs/components/core/src/lib/modules/scroll-shadow/scroll-shadow.directive.spec.ts
  libs/components/core/src/lib/modules/scroll-shadow/scroll-shadow.directive.ts
  libs/components/modals/src/lib/modules/modal/modal.component.html
  libs/components/modals/src/lib/modules/modal/modal.component.spec.ts
  libs/components/modals/src/lib/modules/modal/modal.component.ts
Labels: risk level (author): 2

#2543 feat(components/core): add scroll shadow directive (#2537)
  libs/components/core/src/index.ts
  libs/components/core/src/lib/modules/scroll-shadow/fixtures/scroll-shadow.component.fixture.html
  libs/components/core/src/lib/modules/scroll-shadow/fixtures/scroll-shadow.component.fixture.scss
  libs/components/core/src/lib/modules/scroll-shadow/fixtures/scroll-shadow.component.fixture.ts
  libs/components/core/src/lib/modules/scroll-shadow/scroll-shadow-event-args.ts
  libs/components/core/src/lib/modules/scroll-shadow/scroll-shadow.directive.spec.ts
  libs/components/core/src/lib/modules/scroll-shadow/scroll-shadow.directive.ts
  libs/components/modals/src/lib/modules/modal/modal.component.html
  libs/components/modals/src/lib/modules/modal/modal.component.spec.ts
  libs/components/modals/src/lib/modules/modal/modal.component.ts
Labels: risk level (author): 2

#2544 chore: release 10.38.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease 10.x.x: pending

#2545 chore: changelog for 10.38.0 (#2544) 🍒
  CHANGELOG.md
Labels: risk level (author): 1, risk level (reviewer): 1

#2542 feat: update `intl-tel-input` and `google-libphonenumber` dependencies
  libs/components/lookup/package.json
  libs/components/lookup/src/lib/modules/country-field/country-field.component.ts
  libs/components/phone-field/package.json
  libs/components/phone-field/src/lib/modules/phone-field/phone-field.component.ts
  package-lock.json
  package.json
Labels: risk level (author): 1

#2538 fix(components/lists): remove `::ng-deep` from sort styles
  libs/components/lists/src/lib/modules/sort/sort-item.component.scss
  libs/components/lists/src/lib/modules/sort/sort-item.component.ts
  libs/components/lists/src/lib/modules/sort/sort.component.scss
  libs/components/theme/src/lib/styles/_public-api/_compat/_mixins.scss
Labels: risk level (author): 3

#2547 fix(components/lists): remove `::ng-deep` from sort styles (#2538)
  libs/components/lists/src/lib/modules/sort/sort-item.component.scss
  libs/components/lists/src/lib/modules/sort/sort-item.component.ts
  libs/components/lists/src/lib/modules/sort/sort.component.scss
  libs/components/theme/src/lib/styles/_public-api/_compat/_mixins.scss
Labels: risk level (author): 3

#2549 feat(components/icon): upgrade icons library to 7.5.0
  libs/components/packages/package.json
  libs/components/theme/package.json
  libs/components/theme/src/lib/styles/sky.scss
  package-lock.json
  package.json
Labels: risk level (author): 1

#2550 feat(components/icon): upgrade icons library to 7.5.0
  libs/components/packages/package.json
  libs/components/theme/package.json
  libs/components/theme/src/lib/styles/sky.scss
  package-lock.json
  package.json
Labels: risk level (author): 1

#2541 fix(components/help-inline): set `aria-controls` on help inline button when widget element exists
  apps/playground/src/app/shared/help.service.ts
  libs/components/core/src/lib/modules/help/help.service.spec.ts
  libs/components/core/src/lib/modules/help/help.service.ts
  libs/components/core/testing/src/help/help-testing-controller.spec.ts
  libs/components/core/testing/src/help/help-testing-controller.ts
  libs/components/core/testing/src/help/help-testing.service.ts
  libs/components/help-inline/src/lib/modules/help-inline/help-inline-aria-controls.pipe.ts
  libs/components/help-inline/src/lib/modules/help-inline/help-inline.component.html
  libs/components/help-inline/src/lib/modules/help-inline/help-inline.component.spec.ts
Labels: risk level (author): 2

#2546 chore: release 10.39.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease 10.x.x: pending

#2552 chore: changelog for 10.39.0 (#2546) 🍒
  CHANGELOG.md
Labels: risk level (author): 1, risk level (reviewer): 1

#2534 chore: release 11.0.0-alpha.6
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#2555 feat!: remove @skyux/omnibar-interop
  .github/workflows/validate-pr.yml
  .skyuxdev.json
  README.md
  libs/components/omnibar-interop/.eslintrc.json
  libs/components/omnibar-interop/CHANGELOG.md
  libs/components/omnibar-interop/README.md
  libs/components/omnibar-interop/karma.conf.js
  libs/components/omnibar-interop/ng-package.json
  libs/components/omnibar-interop/package.json
  libs/components/omnibar-interop/project.json
  libs/components/omnibar-interop/src/index.ts
  libs/components/omnibar-interop/src/lib/omnibar-provider.spec.ts
  libs/components/omnibar-interop/src/lib/omnibar-provider.ts
  libs/components/omnibar-interop/src/lib/omnibar-ready-args.ts
  libs/components/omnibar-interop/src/lib/search-results-provider.spec.ts
  libs/components/omnibar-interop/src/lib/search-results-provider.ts
  libs/components/omnibar-interop/tsconfig.json
  libs/components/omnibar-interop/tsconfig.lib.json
  libs/components/omnibar-interop/tsconfig.lib.prod.json
  libs/components/omnibar-interop/tsconfig.spec.json
  libs/components/packages/package.json
  tsconfig.base.json
Labels: risk level (author): 2

#2551 fix(components/help-inline): set `aria-controls` on help inline button when widget element exists (#2541)
  apps/playground/src/app/shared/help.service.ts
  libs/components/core/src/lib/modules/help/help.service.spec.ts
  libs/components/core/src/lib/modules/help/help.service.ts
  libs/components/core/testing/src/help/help-testing-controller.spec.ts
  libs/components/core/testing/src/help/help-testing-controller.ts
  libs/components/core/testing/src/help/help-testing.service.ts
  libs/components/help-inline/src/lib/modules/help-inline/help-inline-aria-controls.pipe.ts
  libs/components/help-inline/src/lib/modules/help-inline/help-inline.component.html
  libs/components/help-inline/src/lib/modules/help-inline/help-inline.component.spec.ts
Labels: risk level (author): 2

#2557 feat: update Angular, `dompurify`, `eslint-plugin-deprecation`, `intl-tel-input`, and `validator`
  libs/components/a11y/package.json
  libs/components/action-bars/package.json
  libs/components/ag-grid/package.json
  libs/components/angular-tree-component/package.json
  libs/components/animations/package.json
  libs/components/assets/package.json
  libs/components/autonumeric/package.json
  libs/components/avatar/package.json
  libs/components/colorpicker/package.json
  libs/components/config/package.json
  libs/components/core/package.json
  libs/components/data-manager/package.json
  libs/components/datetime/package.json
  libs/components/errors/package.json
  libs/components/flyout/package.json
  libs/components/forms/package.json
  libs/components/grids/package.json
  libs/components/help-inline/package.json
  libs/components/i18n/package.json
  libs/components/icon/package.json
  libs/components/indicators/package.json
  libs/components/inline-form/package.json
  libs/components/layout/package.json
  libs/components/list-builder-common/package.json
  libs/components/list-builder-view-checklist/package.json
  libs/components/list-builder-view-grids/package.json
  libs/components/list-builder/package.json
  libs/components/lists/package.json
  libs/components/lookup/package.json
  libs/components/modals/package.json
  libs/components/navbar/package.json
  libs/components/packages/package.json
  libs/components/pages/package.json
  libs/components/phone-field/package.json
  libs/components/popovers/package.json
  libs/components/progress-indicator/package.json
  libs/components/router/package.json
  libs/components/select-field/package.json
  libs/components/split-view/package.json
  libs/components/storybook/package.json
  libs/components/tabs/package.json
  libs/components/text-editor/package.json
  libs/components/theme/package.json
  libs/components/tiles/package.json
  libs/components/toast/package.json
  libs/components/validation/package.json
  libs/sdk/e2e-schematics/package.json
  libs/sdk/eslint-config/package.json
  libs/sdk/prettier-schematics/package.json
  libs/sdk/testing/package.json
  libs/sdk/tools/package.json
  package-lock.json
  package.json
Labels: risk level (author): 1

#2554 fix(components/lists): repeater focus styles show on focus-visible in modern theme
  libs/components/lists/src/lib/modules/repeater/repeater-item.component.scss
Labels: risk level (author): 2

#2561 chore: update development dependencies
  package-lock.json
  package.json
Labels: risk level (author): 1

#2553 feat(components/forms): improve file attachments error messaging for incorrect file types
  libs/components/forms/src/assets/locales/resources_en_US.json
  libs/components/forms/src/lib/modules/file-attachment/file-attachment.component.html
  libs/components/forms/src/lib/modules/file-attachment/file-attachment.component.spec.ts
  libs/components/forms/src/lib/modules/file-attachment/file-attachment.component.ts
  libs/components/forms/src/lib/modules/file-attachment/file-attachment.service.ts
  libs/components/forms/src/lib/modules/file-attachment/file-drop.component.html
  libs/components/forms/src/lib/modules/file-attachment/file-drop.component.spec.ts
  libs/components/forms/src/lib/modules/file-attachment/file-drop.component.ts
  libs/components/forms/src/lib/modules/shared/sky-forms-resources.module.ts
Labels: risk level (author): 2

#2559 chore: release 10.40.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease 10.x.x: pending

#2563 chore: changelog for 10.40.0 (#2559) 🍒
  CHANGELOG.md
Labels: risk level (author): 1, risk level (reviewer): 1

#2562 feat(components/forms): improve file attachments error messaging for incorrect file types (#2553)
  libs/components/forms/src/assets/locales/resources_en_US.json
  libs/components/forms/src/lib/modules/file-attachment/file-attachment.component.html
  libs/components/forms/src/lib/modules/file-attachment/file-attachment.component.spec.ts
  libs/components/forms/src/lib/modules/file-attachment/file-attachment.component.ts
  libs/components/forms/src/lib/modules/file-attachment/file-attachment.service.ts
  libs/components/forms/src/lib/modules/file-attachment/file-drop.component.html
  libs/components/forms/src/lib/modules/file-attachment/file-drop.component.spec.ts
  libs/components/forms/src/lib/modules/file-attachment/file-drop.component.ts
  libs/components/forms/src/lib/modules/shared/sky-forms-resources.module.ts
Labels: risk level (author): 2

#2556 chore: release 11.0.0-alpha.7
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#2567 fix(components/modals): `SkyModalTestingController.closeTopModal` passes `reason` and `result` to the modal instance (#2565)
  libs/components/modals/testing/src/modal/controller/modal-testing.controller.spec.ts
  libs/components/modals/testing/src/modal/controller/modal-testing.service.ts
Labels: risk level (author): 2, risk level (reviewer): 2

#2566 fix(components/core): remove @angular/forms peer dependency
  libs/components/core/package.json
  libs/components/core/src/index.ts
  libs/components/core/src/lib/modules/forms-utility/forms-utility.ts
  libs/components/forms/src/lib/modules/file-attachment/file-attachment.component.html
  libs/components/forms/src/lib/modules/file-attachment/file-attachment.component.ts
  libs/components/forms/src/lib/modules/radio/radio-group.component.html
  libs/components/forms/src/lib/modules/radio/radio-group.component.ts
Labels: risk level (author): 2

#2571 feat(components/popovers): remove `dismissOnBlur` input from popover and dropdown
  apps/code-examples/src/app/code-examples/popovers/popover/basic/demo.component.html
  apps/code-examples/src/app/code-examples/popovers/popover/basic/demo.component.spec.ts
  apps/code-examples/src/app/code-examples/popovers/popover/basic/demo.component.ts
  apps/playground/src/app/components/core/affix/affix.component.html
  apps/playground/src/app/components/core/affix/affix.component.ts
  libs/components/popovers/src/lib/modules/dropdown/dropdown-menu.component.ts
  libs/components/popovers/src/lib/modules/dropdown/dropdown.component.spec.ts
  libs/components/popovers/src/lib/modules/dropdown/dropdown.component.ts
  libs/components/popovers/src/lib/modules/dropdown/fixtures/dropdown.component.fixture.html
  libs/components/popovers/src/lib/modules/dropdown/fixtures/dropdown.component.fixture.ts
  libs/components/popovers/src/lib/modules/popover/fixtures/popover.component.fixture.html
  libs/components/popovers/src/lib/modules/popover/fixtures/popover.component.fixture.ts
  libs/components/popovers/src/lib/modules/popover/popover-content.component.ts
  libs/components/popovers/src/lib/modules/popover/popover.component.ts
  libs/components/popovers/src/lib/modules/popover/popover.directive.spec.ts
  libs/components/popovers/src/lib/modules/popover/popover.directive.ts
  libs/components/popovers/testing/src/dropdown/harness/dropdown-harness.spec.ts
  libs/components/popovers/testing/src/dropdown/harness/dropdown-menu-harness.ts
  libs/components/popovers/testing/src/popover/harness/fixtures/popover-harness-test.component.html
  libs/components/popovers/testing/src/popover/harness/fixtures/popover-harness-test.component.ts
  libs/components/popovers/testing/src/popover/harness/popover-content-harness.ts
  libs/components/popovers/testing/src/popover/harness/popover-harness.spec.ts
  libs/components/popovers/testing/src/popover/popover-fixture.spec.ts
Labels: risk level (author): 2

#2570 feat(components/packages): schematic to update `SkyHelpInlineModule` import from the indicators library to the help-inline library
  apps/code-examples/src/app/code-examples/ag-grid/data-entry-grid/inline-help/inline-help.component.ts
  apps/code-examples/src/app/code-examples/ag-grid/data-grid/inline-help/inline-help.component.ts
  apps/code-examples/src/app/code-examples/angular-tree-component/angular-tree/basic/demo.component.ts
  apps/code-examples/src/app/code-examples/forms/toggle-switch/inline-help/demo.component.ts
  apps/code-examples/src/app/code-examples/help-inline/basic/demo.component.ts
  apps/code-examples/src/app/code-examples/indicators/status-indicator/inline-help/demo.component.ts
  apps/code-examples/src/app/code-examples/layout/description-list/inline-help/demo.component.ts
  apps/code-examples/src/app/code-examples/popovers/popover/programmatic/demo.component.ts
  apps/e2e/ag-grid-storybook/src/app/shared/inline-help/inline-help.module.ts
  apps/e2e/angular-tree-component-storybook/src/app/angular-tree-component/angular-tree-component.module.ts
  apps/e2e/forms-storybook/src/app/checkbox/checkbox.module.ts
  apps/e2e/forms-storybook/src/app/file-attachment/file-attachment.module.ts
  apps/e2e/forms-storybook/src/app/input-box/input-box.module.ts
  apps/e2e/forms-storybook/src/app/radio-button/radio-button.module.ts
  apps/e2e/forms-storybook/src/app/single-file-attachment/single-file-attachment.module.ts
  apps/e2e/forms-storybook/src/app/toggle-switch/toggle-switch.module.ts
  apps/e2e/indicators-storybook/src/app/help-inline/help-inline.module.ts
  apps/e2e/indicators-storybook/src/app/status-indicator/status-indicator.module.ts
  apps/e2e/layout-storybook/src/app/box/box.module.ts
  apps/e2e/modals-storybook/src/app/modal/modals/modal-basic.component.ts
  apps/e2e/progress-indicator-storybook/src/app/progress-indicator/progress-indicator.module.ts
  apps/e2e/text-editor-storybook/src/app/text-editor/text-editor.module.ts
  apps/e2e/tiles-storybook/src/app/tile-dashboard/tile-dashboard.module.ts
  apps/integration/src/app/integrations/field-heights/field-heights.module.ts
  apps/playground/src/app/components/ag-grid/data-manager-large/data-manager-large.module.ts
  apps/playground/src/app/components/ag-grid/edit-complex-cells/inline-help/inline-help.component.ts
  apps/playground/src/app/components/forms/checkbox/checkbox.module.ts
  apps/playground/src/app/components/forms/input-box/input-box.module.ts
  apps/playground/src/app/components/forms/radio/radio.module.ts
  apps/playground/src/app/components/forms/single-file-attachment/single-file-attachment.module.ts
  apps/playground/src/app/components/forms/toggle-switch/toggle-switch.module.ts
  apps/playground/src/app/components/indicators/help-inline/help-inline.module.ts
  apps/playground/src/app/components/indicators/key-info/key-info.module.ts
  apps/playground/src/app/components/indicators/status-indicator/status-indicator.module.ts
  apps/playground/src/app/components/layout/box/box.module.ts
  apps/playground/src/app/components/layout/description-list/description-list.module.ts
  apps/playground/src/app/components/tiles/tile-dashboard/tile2.component.ts
  libs/components/forms/src/lib/modules/file-attachment/fixtures/file-attachment.module.fixture.ts
  libs/components/forms/src/lib/modules/input-box/fixtures/input-box.module.fixture.ts
  libs/components/forms/src/lib/modules/toggle-switch/fixtures/toggle-switch.module.fixture.ts
  libs/components/grids/package.json
  libs/components/grids/src/lib/modules/grid/grid.component.spec.ts
  libs/components/grids/src/lib/modules/grid/grid.module.ts
  libs/components/indicators/src/index.ts
  libs/components/indicators/src/lib/modules/help-inline/fixtures/help-inline-fixtures.module.ts
  libs/components/indicators/src/lib/modules/help-inline/fixtures/help-inline.component.fixture.html
  libs/components/indicators/src/lib/modules/help-inline/fixtures/help-inline.component.fixture.ts
  libs/components/indicators/src/lib/modules/help-inline/help-inline-aria-expanded.pipe.ts
  libs/components/indicators/src/lib/modules/help-inline/help-inline.component.html
  libs/components/indicators/src/lib/modules/help-inline/help-inline.component.scss
  libs/components/indicators/src/lib/modules/help-inline/help-inline.component.spec.ts
  libs/components/indicators/src/lib/modules/help-inline/help-inline.component.ts
  libs/components/indicators/src/lib/modules/help-inline/help-inline.module.ts
  libs/components/indicators/testing/src/help-inline/help-inline-harness.spec.ts
  libs/components/packages/src/schematics/migrations/migration-collection.json
  libs/components/packages/src/schematics/migrations/update-11/help-inline-import-path/help-inline-import-path.schematic.spec.ts
  libs/components/packages/src/schematics/migrations/update-11/help-inline-import-path/help-inline-import-path.schematic.ts
  libs/components/packages/src/schematics/utility/move-class-to-library.ts
Labels: risk level (author): 2

#2564 feat(components/packages): schematic to remove compat stylesheets
  libs/components/packages/collection.json
  libs/components/packages/src/schematics/migrations/update-11/remove-old-compat-stylesheets/remove-old-compat-stylesheets.schematic.spec.ts
  libs/components/packages/src/schematics/migrations/update-11/remove-old-compat-stylesheets/remove-old-compat-stylesheets.schematic.ts
  libs/components/packages/src/schematics/ng-generate/remove-compat-stylesheets/remove-compat-stylesheets.schematic.spec.ts
  libs/components/packages/src/schematics/ng-generate/remove-compat-stylesheets/remove-compat-stylesheets.schematic.ts
  libs/components/packages/src/schematics/ng-generate/remove-compat-stylesheets/schema.json
  libs/components/packages/src/schematics/ng-generate/remove-compat-stylesheets/schema.ts
Labels: risk level (author): 1

#2572 feat(components/packages): schematic to update icon type imports from the indicators library to the icon library
  apps/code-examples/src/app/code-examples/forms/selection-box/checkbox/demo.component.ts
  apps/code-examples/src/app/code-examples/forms/selection-box/radio/demo.component.ts
  apps/code-examples/src/app/code-examples/icon/basic/demo.component.ts
  apps/code-examples/src/app/code-examples/icon/icon-button/demo.component.ts
  apps/code-examples/src/app/code-examples/inline-form/inline-form/basic/demo.component.ts
  apps/code-examples/src/app/code-examples/inline-form/inline-form/custom-buttons/demo.component.ts
  apps/code-examples/src/app/code-examples/inline-form/inline-form/repeaters/demo.component.ts
  apps/code-examples/src/app/code-examples/layout/inline-delete/custom/demo.component.ts
  apps/code-examples/src/app/code-examples/layout/toolbar/basic/demo.component.ts
  apps/code-examples/src/app/code-examples/layout/toolbar/sectioned/demo.component.ts
  apps/code-examples/src/app/code-examples/lists/repeater/inline-form/demo.component.ts
  apps/code-examples/src/app/code-examples/lookup/autocomplete/custom-search/demo.component.ts
  apps/code-examples/src/app/code-examples/lookup/lookup/custom-picker/picker-modal.component.ts
  apps/code-examples/src/app/code-examples/pages/page/list-page-list-layout-demo/list-page-content.component.ts
  apps/code-examples/src/app/code-examples/pages/page/list-page-tabs-layout-demo/list-page-contacts-grid.component.ts
  apps/code-examples/src/app/code-examples/pages/page/record-page-blocks-layout-demo/record-page-content.component.ts
  apps/code-examples/src/app/code-examples/pages/page/record-page-tabs-layout-demo/record-page-attachments-tab.component.ts
  apps/code-examples/src/app/code-examples/pages/page/record-page-tabs-layout-demo/record-page-notes-tab.component.ts
  apps/code-examples/src/app/code-examples/pages/page/record-page-tabs-layout-demo/record-page-overview-tab.component.ts
  apps/code-examples/src/app/code-examples/tabs/sectioned-form/modal/modal.component.ts
  apps/e2e/indicators-storybook/src/app/illustration/illustration.module.ts
  libs/components/colorpicker/package.json
  libs/components/colorpicker/src/lib/modules/colorpicker/colorpicker.component.ts
  libs/components/colorpicker/src/lib/modules/colorpicker/fixtures/colorpicker-component.fixture.ts
  libs/components/forms/src/lib/modules/input-box/fixtures/input-box.module.fixture.ts
  libs/components/indicators/package.json
  libs/components/indicators/src/index.ts
  libs/components/packages/src/schematics/migrations/migration-collection.json
  libs/components/packages/src/schematics/migrations/update-11/icons-migration/icons-migration.schematic.spec.ts
  libs/components/packages/src/schematics/migrations/update-11/icons-migration/icons-migration.schematic.ts
  libs/components/toast/package.json
  libs/components/toast/src/lib/modules/toast/toast.component.ts
Labels: risk level (author): 2

#2574 feat: move help inline features out of developer preview for key info, box, and description list
  libs/components/indicators/src/lib/modules/key-info/key-info.component.ts
  libs/components/layout/src/lib/modules/box/box.component.ts
  libs/components/layout/src/lib/modules/description-list/description-list-content.component.ts
Labels: risk level (author): 1

#2577 fix(components/layout): fix key info display in page summary (#2576)
  libs/components/indicators/src/lib/modules/key-info/key-info.component.scss
  libs/components/indicators/src/lib/modules/key-info/key-info.component.ts
  libs/components/indicators/src/lib/modules/key-info/key-info.default.component.scss
  libs/components/layout/src/lib/modules/page-summary/page-summary-key-info.component.scss
Labels: risk level (author): 2
