Repository blackbaud/skyux, pull requests merged in 2024-03, with the labels that each got.

#2054 feat(components/ag-grid)!: add support for AG Grid 31
  libs/components/ag-grid/package.json
  libs/components/ag-grid/src/lib/modules/ag-grid/ag-grid-wrapper.component.spec.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/ag-grid.service.spec.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/ag-grid.service.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-renderers/cell-renderer-row-selector/cell-renderer-row-selector.component.spec.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/fixtures/ag-grid.component.fixture.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/header/header-group.component.ts
  package-lock.json
  package.json
Labels: risk level (author): 3

#2071 chore: release 9.28.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease 9.x.x: pending

#2078 chore: release 9.28.0 (#2071)
  CHANGELOG.md
Labels: risk level (author): 1, risk level (reviewer): 1

#2077 fix(components/packages): skip deleting compat stylesheets if they don't exist
  libs/components/packages/src/schematics/migrations/update-10/remove-old-compat-stylesheets/remove-old-compat-stylesheets.schematic.spec.ts
  libs/components/packages/src/schematics/migrations/update-10/remove-old-compat-stylesheets/remove-old-compat-stylesheets.schematic.ts
Labels: risk level (author): 1

#2080 fix(components/ag-grid): check `isDestroyed` before grid api call
  libs/components/ag-grid/src/lib/modules/ag-grid/ag-grid-wrapper.component.spec.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/ag-grid-wrapper.component.ts
Labels: risk level (author): 1

#2081 feat(components/tiles): set tile content aria label to tile title id
  libs/components/tiles/src/lib/modules/tiles/tile-dashboard/tile-dashboard.service.spec.ts
  libs/components/tiles/src/lib/modules/tiles/tile/tile-title-id-token.ts
  libs/components/tiles/src/lib/modules/tiles/tile/tile-title.component.html
  libs/components/tiles/src/lib/modules/tiles/tile/tile-title.component.ts
  libs/components/tiles/src/lib/modules/tiles/tile/tile.component.html
  libs/components/tiles/src/lib/modules/tiles/tile/tile.component.spec.ts
  libs/components/tiles/src/lib/modules/tiles/tile/tile.component.ts
Labels: risk level (author): 2

#2086 fix(components/ag-grid): a11y test intermittently failing
  libs/components/ag-grid/src/lib/modules/ag-grid/ag-grid-wrapper.component.spec.ts
Labels: risk level (author): 1

#2087 fix: mark new `labelText` inputs as preview features
  libs/components/colorpicker/src/lib/modules/colorpicker/colorpicker.component.ts
  libs/components/forms/src/lib/modules/checkbox/checkbox.component.ts
  libs/components/forms/src/lib/modules/file-attachment/file-attachment.component.ts
  libs/components/forms/src/lib/modules/radio/radio-group.component.ts
  libs/components/forms/src/lib/modules/toggle-switch/toggle-switch.component.ts
Labels: risk level (author): 1

#2061 feat(components/phone-field): phone format information moved to input box hint text
  libs/components/forms/src/lib/modules/input-box/fixtures/input-box-host-service.component.fixture.ts
  libs/components/forms/src/lib/modules/input-box/fixtures/input-box.component.fixture.ts
  libs/components/forms/src/lib/modules/input-box/input-box-host.service.spec.ts
  libs/components/forms/src/lib/modules/input-box/input-box-host.service.ts
  libs/components/forms/src/lib/modules/input-box/input-box.component.html
  libs/components/forms/src/lib/modules/input-box/input-box.component.scss
  libs/components/forms/src/lib/modules/input-box/input-box.component.spec.ts
  libs/components/forms/src/lib/modules/input-box/input-box.component.ts
  libs/components/phone-field/package.json
  libs/components/phone-field/src/assets/locales/resources_en_US.json
  libs/components/phone-field/src/lib/modules/phone-field/fixtures/phone-field-input-box.component.fixture.html
  libs/components/phone-field/src/lib/modules/phone-field/fixtures/phone-field-input-box.component.fixture.ts
  libs/components/phone-field/src/lib/modules/phone-field/fixtures/phone-field-reactive.component.fixture.html
  libs/components/phone-field/src/lib/modules/phone-field/fixtures/phone-field.component.fixture.html
  libs/components/phone-field/src/lib/modules/phone-field/phone-field-adapter.service.ts
  libs/components/phone-field/src/lib/modules/phone-field/phone-field-input.directive.ts
  libs/components/phone-field/src/lib/modules/phone-field/phone-field.component.spec.ts
  libs/components/phone-field/src/lib/modules/phone-field/phone-field.component.ts
  libs/components/phone-field/src/lib/modules/shared/sky-phone-field-resources.module.ts
Labels: risk level (author): 2

#2088 fix: mark new `labelText` inputs as preview features (#2087)
  libs/components/colorpicker/src/lib/modules/colorpicker/colorpicker.component.ts
  libs/components/forms/src/lib/modules/checkbox/checkbox.component.ts
  libs/components/forms/src/lib/modules/file-attachment/file-attachment.component.ts
  libs/components/forms/src/lib/modules/radio/radio-group.component.ts
  libs/components/forms/src/lib/modules/toggle-switch/toggle-switch.component.ts
Labels: risk level (author): 1

#2084 feat(components/tiles): set tile content aria label to tile title id (#2081)
  libs/components/tiles/src/lib/modules/tiles/tile-dashboard/tile-dashboard.service.spec.ts
  libs/components/tiles/src/lib/modules/tiles/tile/tile-title-id-token.ts
  libs/components/tiles/src/lib/modules/tiles/tile/tile-title.component.html
  libs/components/tiles/src/lib/modules/tiles/tile/tile-title.component.ts
  libs/components/tiles/src/lib/modules/tiles/tile/tile.component.html
  libs/components/tiles/src/lib/modules/tiles/tile/tile.component.spec.ts
  libs/components/tiles/src/lib/modules/tiles/tile/tile.component.ts
Labels: risk level (author): 2

#2089 feat(components/lists): repeater back to top button uses new `arrow-up` icon
  libs/components/lists/src/lib/modules/repeater/repeater-item.component.html
Labels: risk level (author): 2

#2082 fix(components/forms): style `sky-radio` as an inline-block element
  libs/components/forms/src/lib/modules/radio/radio.component.scss
Labels: risk level (author): 2

#2091 feat(components/ag-grid): datepicker cell editor date format information moved to input tooltip
  libs/components/ag-grid/src/assets/locales/resources_en_US.json
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-editors/cell-editor-autocomplete/cell-editor-autocomplete.component.spec.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-editors/cell-editor-autocomplete/cell-editor-autocomplete.component.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-editors/cell-editor-currency/cell-editor-currency.component.spec.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-editors/cell-editor-currency/cell-editor-currency.component.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-editors/cell-editor-datepicker/cell-editor-datepicker.component.html
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-editors/cell-editor-datepicker/cell-editor-datepicker.component.spec.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-editors/cell-editor-datepicker/cell-editor-datepicker.component.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-editors/cell-editor-datepicker/cell-editor-datepicker.module.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-editors/cell-editor-number/cell-editor-number.component.spec.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-editors/cell-editor-number/cell-editor-number.component.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-editors/cell-editor-text/cell-editor-text.component.spec.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-editors/cell-editor-text/cell-editor-text.component.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-renderers/cell-renderer-currency/cell-renderer-currency.component.ts
  libs/components/ag-grid/src/lib/modules/shared/sky-ag-grid-resources.module.ts
  libs/components/datetime/src/lib/modules/datepicker/datepicker.component.ts
Labels: risk level (author): 2

#2093 fix(components/forms): style `sky-radio` as an inline-block element (#2082)
  libs/components/forms/src/lib/modules/radio/radio.component.scss
Labels: risk level (author): 2

#2083 chore: release 9.29.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease 9.x.x: pending

#2095 feat(components/theme): update h4 and h5 styles in modern theme
  libs/components/packages/src/schematics/migrations/update-10/add-compat-stylesheets/__snapshots__/add-compat-stylesheet.schematic.spec.ts.snap
  libs/components/packages/src/schematics/migrations/update-10/add-compat-stylesheets/add-compat-stylesheet.schematic.ts
  libs/components/theme/src/lib/styles/_custom-properties.scss
  libs/components/theme/src/lib/styles/themes/modern/_theme.scss
Labels: risk level (author): 1

#2098 chore: release 9.29.0 (#2083)
  CHANGELOG.md
Labels: risk level (author): 1, risk level (reviewer): 1

#2097 feat: update `intl-tel-input` and `google-libphonenumber` dependencies
  libs/components/lookup/package.json
  libs/components/lookup/src/lib/modules/country-field/country-field.component.spec.ts
  libs/components/lookup/src/lib/modules/country-field/country-field.component.ts
  libs/components/phone-field/package.json
  libs/components/phone-field/src/lib/modules/phone-field/phone-field.component.spec.ts
  package-lock.json
  package.json
Labels: risk level (author): 2

#2048 chore: release 10.0.0-alpha.3
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#2100 feat(components/ag-grid): schematic for AG Grid 31 changes
  libs/components/packages/collection.json
  libs/components/packages/src/schematics/ag-grid-migrate/ag-grid-migrate.schematic.spec.ts
  libs/components/packages/src/schematics/ag-grid-migrate/ag-grid-migrate.schematic.ts
  libs/components/packages/src/schematics/ag-grid-migrate/schema.json
  libs/components/packages/src/schematics/ag-grid-migrate/schema.ts
  libs/components/packages/src/schematics/migrations/update-10/ag-grid/ag-grid-codemod-task.ts
  libs/components/packages/src/schematics/migrations/update-10/ag-grid/ag-grid.schematic.ts
  scripts/postbuild-packages.ts
Labels: risk level (author): 1

#2104 ci: update pipelines node support
  .github/actions/e2e-affected/action.yml
  .github/actions/nx-set-shas/action.yml
  .github/workflows/cherry-pick.yml
  .github/workflows/ci.yml
  .github/workflows/e2e-cancel.yml
  .github/workflows/e2e-check.yml
  .github/workflows/e2e-cleanup.yml
  .github/workflows/e2e.yml
  .github/workflows/release-please.yml
  .github/workflows/risk-assessment.yml
  .github/workflows/skyux-azboards.yml
  .github/workflows/update-branch.yml
  .github/workflows/validate-pr.yml
  .nvmrc
  libs/sdk/e2e-schematics/jest.config.ts
  libs/sdk/e2e-schematics/src/generators/configure-percy/__snapshots__/index.spec.ts.snap
  libs/sdk/e2e-schematics/src/generators/stories/__snapshots__/index.spec.ts.snap
  libs/sdk/e2e-schematics/src/generators/story/__snapshots__/index.spec.ts.snap
  libs/sdk/tools/jest.config.ts
  package-lock.json
  package.json
Labels: risk level (author): 1

#2102 refactor(components/packages): use regular expression to rename tabIndex
  libs/components/packages/package.json
  libs/components/packages/src/schematics/migrations/update-10/rename-tabset-tabindex/rename-tabset-tabindex.schematic.spec.ts
  libs/components/packages/src/schematics/migrations/update-10/rename-tabset-tabindex/rename-tabset-tabindex.schematic.ts
  package-lock.json
  package.json
Labels: risk level (author): 3

#2094 feat(components/forms): add form errors to single file attachment
  apps/e2e/forms-storybook/src/app/single-file-attachment/single-file-attachment.component.ts
  apps/playground/src/app/components/forms/single-file-attachment/single-file-attachment.component.html
  libs/components/forms/src/assets/locales/resources_en_US.json
  libs/components/forms/src/lib/modules/file-attachment/file-attachment.component.html
  libs/components/forms/src/lib/modules/file-attachment/file-attachment.component.spec.ts
  libs/components/forms/src/lib/modules/file-attachment/file-attachment.component.ts
  libs/components/forms/src/lib/modules/file-attachment/file-attachments.module.ts
  libs/components/forms/src/lib/modules/file-attachment/fixtures/file-attachment.component.fixture.html
  libs/components/forms/src/lib/modules/file-attachment/fixtures/file-attachment.component.fixture.ts
  libs/components/forms/src/lib/modules/shared/sky-forms-resources.module.ts
Labels: risk level (author): 3

#2107 feat(components/ag-grid): move and resize column header via keyboard
  libs/components/ag-grid/src/lib/modules/ag-grid/header/header.component.spec.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/header/header.component.ts
Labels: risk level (author): 1

#2108 refactor(components/packages): skip tabIndex replacement for non-template files
  libs/components/packages/src/schematics/migrations/update-10/rename-tabset-tabindex/rename-tabset-tabindex.schematic.spec.ts
  libs/components/packages/src/schematics/migrations/update-10/rename-tabset-tabindex/rename-tabset-tabindex.schematic.ts
Labels: risk level (author): 2

#2103 feat(components/forms)!: `SkyComponentHarness.queryHarness` throws if child harness not found
  apps/code-examples/src/app/code-examples/lookup/lookup/add-item/demo.component.spec.ts
  apps/code-examples/src/app/code-examples/lookup/lookup/async/demo.component.spec.ts
  apps/code-examples/src/app/code-examples/lookup/lookup/custom-picker/demo.component.spec.ts
  apps/code-examples/src/app/code-examples/lookup/lookup/multi-select/demo.component.spec.ts
  apps/code-examples/src/app/code-examples/lookup/lookup/result-templates/demo.component.spec.ts
  apps/code-examples/src/app/code-examples/lookup/lookup/single-select/demo.component.spec.ts
  apps/integration/src/app/integrations/lookup-in-modal/modal-lookup.component.spec.ts
  libs/components/core/testing/src/overlay/overlay-harness.spec.ts
  libs/components/core/testing/src/overlay/overlay-harness.ts
  libs/components/core/testing/src/public-api.ts
  libs/components/core/testing/src/shared/component-harness.ts
  libs/components/core/testing/src/shared/queryable-component-harness.spec.ts
  libs/components/core/testing/src/shared/queryable-component-harness.ts
  libs/components/forms/testing/src/input-box/fixtures/nonexistent-harness.ts
  libs/components/forms/testing/src/input-box/input-box-harness.spec.ts
  libs/components/forms/testing/src/input-box/input-box-harness.ts
  libs/components/lists/testing/src/repeater/fixtures/nonexistent-harness.ts
  libs/components/lists/testing/src/repeater/repeater-harness.spec.ts
  libs/components/lists/testing/src/repeater/repeater-item-harness.ts
  libs/components/lookup/testing/src/autocomplete/autocomplete-harness.spec.ts
  libs/components/lookup/testing/src/autocomplete/autocomplete-harness.ts
  libs/components/lookup/testing/src/autocomplete/autocomplete-search-result-harness.ts
  libs/components/lookup/testing/src/autocomplete/fixtures/nonexistent-harness.ts
  libs/components/lookup/testing/src/lookup/lookup-harness.spec.ts
  libs/components/packages/src/schematics/migrations/migration-collection.json
  libs/components/packages/src/schematics/migrations/update-10/rename-harness-queries/rename-harness-queries.schematic.test.ts
  libs/components/packages/src/schematics/migrations/update-10/rename-harness-queries/rename-harness-queries.schematic.ts
  libs/components/popovers/testing/src/popover/harness/fixtures/nonexistent-harness.ts
  libs/components/popovers/testing/src/popover/harness/popover-body-harness.ts
  libs/components/popovers/testing/src/popover/harness/popover-content-harness.ts
  libs/components/popovers/testing/src/popover/harness/popover-harness.spec.ts
Labels: risk level (author): 3

#2106 feat(components/forms): add form errors to single file attachment (#2094)
  .prettierrc
  apps/e2e/forms-storybook/src/app/single-file-attachment/single-file-attachment.component.ts
  apps/playground/src/app/components/forms/single-file-attachment/single-file-attachment.component.html
  libs/components/forms/src/assets/locales/resources_en_US.json
  libs/components/forms/src/lib/modules/file-attachment/file-attachment.component.html
  libs/components/forms/src/lib/modules/file-attachment/file-attachment.component.spec.ts
  libs/components/forms/src/lib/modules/file-attachment/file-attachment.component.ts
  libs/components/forms/src/lib/modules/file-attachment/file-attachments.module.ts
  libs/components/forms/src/lib/modules/file-attachment/fixtures/file-attachment.component.fixture.html
  libs/components/forms/src/lib/modules/file-attachment/fixtures/file-attachment.component.fixture.ts
  libs/components/forms/src/lib/modules/shared/sky-forms-resources.module.ts
Labels: risk level (author): 3

#2092 fix(components/tabs): set appropriate `:focus-visible` styles for selected tab buttons
  apps/e2e/tabs-storybook-e2e/src/e2e/tabs.component.cy.ts
  libs/components/theme/src/lib/styles/_buttons.scss
  libs/components/theme/src/lib/styles/_public-api/_compat/_mixins.scss
  libs/components/theme/src/lib/styles/_public-api/themes/modern/_compat/_mixins.scss
Labels: risk level (author): 2

#2111 chore: update to NX 18 and Angular 17.2
  .env
  .github/workflows/e2e.yml
  .nvmrc
  apps/e2e/phone-field-storybook-e2e/src/e2e/phone-field.component.cy.ts
  libs/components/a11y/package.json
  libs/components/action-bars/package.json
  libs/components/ag-grid/package.json
  libs/components/angular-tree-component/package.json
  libs/components/animations/package.json
  libs/components/assets/package.json
  libs/components/autonumeric/package.json
  libs/components/avatar/package.json
  libs/components/colorpicker/package.json
  libs/components/config/package.json
  libs/components/core/package.json
  libs/components/data-manager/package.json
  libs/components/datetime/package.json
  libs/components/errors/package.json
  libs/components/flyout/package.json
  libs/components/forms/package.json
  libs/components/grids/package.json
  libs/components/http/package.json
  libs/components/i18n/package.json
  libs/components/indicators/package.json
  libs/components/inline-form/package.json
  libs/components/layout/package.json
  libs/components/list-builder-common/package.json
  libs/components/list-builder-view-checklist/package.json
  libs/components/list-builder-view-grids/package.json
  libs/components/list-builder/package.json
  libs/components/lists/package.json
  libs/components/lookup/package.json
  libs/components/modals/package.json
  libs/components/navbar/package.json
  libs/components/omnibar-interop/package.json
  libs/components/packages/package.json
  libs/components/pages/package.json
  libs/components/phone-field/package.json
  libs/components/popovers/package.json
  libs/components/progress-indicator/package.json
  libs/components/router/package.json
  libs/components/select-field/package.json
  libs/components/split-view/package.json
  libs/components/storybook/package.json
  libs/components/tabs/package.json
  libs/components/text-editor/package.json
  libs/components/theme/package.json
  libs/components/tiles/package.json
  libs/components/toast/package.json
  libs/components/validation/package.json
  libs/sdk/e2e-schematics/package.json
  libs/sdk/eslint-config/package.json
  libs/sdk/prettier-schematics/package.json
  libs/sdk/testing/package.json
  libs/sdk/tools/package.json
  libs/sdk/tools/src/generators/update-dependencies/generator.spec.ts
  nx.json
  package-lock.json
  package.json
Labels: risk level (author): 1

#2109 build: add build targets for testing projects
  libs/components/a11y/testing/project.json
  libs/components/action-bars/testing/project.json
  libs/components/avatar/testing/project.json
  libs/components/colorpicker/testing/project.json
  libs/components/core/testing/project.json
  libs/components/datetime/testing/project.json
  libs/components/errors/testing/project.json
  libs/components/forms/testing/project.json
  libs/components/http/testing/project.json
  libs/components/indicators/testing/project.json
  libs/components/layout/testing/project.json
  libs/components/list-builder-view-checklist/testing/project.json
  libs/components/list-builder-view-grids/testing/project.json
  libs/components/lists/testing/project.json
  libs/components/lookup/testing/project.json
  libs/components/modals/testing/project.json
  libs/components/pages/testing/project.json
  libs/components/phone-field/testing/project.json
  libs/components/popovers/testing/project.json
  libs/components/router/testing/project.json
  libs/components/split-view/testing/project.json
  libs/components/tabs/testing/project.json
  libs/components/toast/testing/project.json
  libs/sdk/tools/src/generators/configure-test-ci/generator.spec.ts
  libs/sdk/tools/src/generators/update-dependencies/__snapshots__/generator.spec.ts.snap
  libs/sdk/tools/src/generators/update-dependencies/generator.spec.ts
  libs/sdk/tools/src/generators/update-dependencies/generator.ts
Labels: risk level (author): 1

#2112 feat(components/modals): add `close` method to `SkyConfirmInstance`
  libs/components/modals/src/lib/modules/confirm/confirm-instance.ts
  libs/components/modals/src/lib/modules/confirm/confirm.component.spec.ts
  libs/components/modals/src/lib/modules/confirm/confirm.component.ts
  libs/components/modals/src/lib/modules/confirm/confirm.service.spec.ts
  libs/components/modals/src/lib/modules/confirm/confirm.service.ts
  libs/components/packages/src/schematics/migrations/migration-collection.json
  libs/components/packages/src/schematics/migrations/update-10/confirm-instance-observable/confirm-instance-observable.schematic.spec.ts
  libs/components/packages/src/schematics/migrations/update-10/confirm-instance-observable/confirm-instance-observable.schematic.ts
Labels: risk level (author): 4

#2110 fix(components/tabs): don't apply negative margins to vertical tabsets and sectioned forms that do not use full modal
  apps/playground/src/app/components/tabs/sectioned-form/sectioned-form-modal-with-columns.component.html
  apps/playground/src/app/components/tabs/sectioned-form/sectioned-form-modal-with-columns.component.scss
  apps/playground/src/app/components/tabs/sectioned-form/sectioned-form-modal-with-columns.component.ts
  apps/playground/src/app/components/tabs/sectioned-form/sectioned-form.component.html
  apps/playground/src/app/components/tabs/sectioned-form/sectioned-form.component.ts
  apps/playground/src/app/components/tabs/vertical-tabset/vertical-tabset-modal-with-columns.component.html
  apps/playground/src/app/components/tabs/vertical-tabset/vertical-tabset-modal-with-columns.component.scss
  apps/playground/src/app/components/tabs/vertical-tabset/vertical-tabset-modal-with-columns.component.ts
  apps/playground/src/app/components/tabs/vertical-tabset/vertical-tabset.component.html
  apps/playground/src/app/components/tabs/vertical-tabset/vertical-tabset.component.ts
  libs/components/modals/src/lib/modules/modal/modal.component.scss
  libs/components/packages/src/schematics/migrations/update-10/add-compat-stylesheets/__snapshots__/add-compat-stylesheet.schematic.spec.ts.snap
  libs/components/packages/src/schematics/migrations/update-10/add-compat-stylesheets/add-compat-stylesheet.schematic.spec.ts
  libs/components/packages/src/schematics/migrations/update-10/add-compat-stylesheets/add-compat-stylesheet.schematic.ts
  libs/components/tabs/src/lib/modules/sectioned-form/sectioned-form.component.scss
  libs/components/tabs/src/lib/modules/vertical-tabset/vertical-tabset.component.scss
Labels: risk level (author): 3

#2115 fix(components/forms): add booleanAttribute transform to labelHidden inputs
  libs/components/forms/src/lib/modules/checkbox/checkbox.component.ts
  libs/components/forms/src/lib/modules/radio/radio-group.component.ts
  libs/components/forms/src/lib/modules/toggle-switch/toggle-switch.component.ts
Labels: risk level (author): 2

#2116 fix(components/forms): add booleanAttribute transform to labelHidden inputs (#2115)
  libs/components/forms/src/lib/modules/checkbox/checkbox.component.ts
  libs/components/forms/src/lib/modules/radio/radio-group.component.ts
  libs/components/forms/src/lib/modules/toggle-switch/toggle-switch.component.ts
Labels: risk level (author): 2

#2114 feat(components/modals): add `SkyConfirmTestingController` to mock confirm dialogs in tests
  apps/code-examples/src/app/code-examples/modals/confirm/demo-controller.spec.ts
  libs/components/modals/src/index.ts
  libs/components/modals/src/lib/modules/confirm/confirm-service-interface.ts
  libs/components/modals/src/lib/modules/confirm/confirm.service.ts
  libs/components/modals/testing/src/confirm/confirm-testing.controller.spec.ts
  libs/components/modals/testing/src/confirm/confirm-testing.controller.ts
  libs/components/modals/testing/src/confirm/confirm-testing.module.ts
  libs/components/modals/testing/src/confirm/confirm-testing.service.ts
  libs/components/modals/testing/src/confirm/provide-confirm-testing.ts
  libs/components/modals/testing/src/public-api.ts
Labels: risk level (author): 1

#2117 fix(components/tabs): add stacked to wizard code example input boxes
  apps/code-examples/src/app/code-examples/tabs/wizard/basic/modal.component.html
Labels: risk level (author): 1

#2118 fix(components/tabs): add stacked to wizard code example input boxes (#2117)
  apps/code-examples/src/app/code-examples/tabs/wizard/basic/modal.component.html
Labels: risk level (author): 1

#2120 chore: release 9.30.0 (#2105)
  CHANGELOG.md
Labels: risk level (author): 1, risk level (reviewer): 1

#2113 feat(components/forms): move file attachment url placeholder text to hint text
  libs/components/forms/src/assets/locales/resources_en_US.json
  libs/components/forms/src/lib/modules/file-attachment/file-drop.component.html
  libs/components/forms/src/lib/modules/file-attachment/file-drop.component.scss
  libs/components/forms/src/lib/modules/file-attachment/file-drop.component.spec.ts
  libs/components/forms/src/lib/modules/shared/sky-forms-resources.module.ts
Labels: risk level (author): 1

#2101 chore: release 10.0.0-alpha.4
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#2124 fix(components/datetime): accept manual input for month name date formats
  apps/playground/src/app/components/datetime/datepicker/datepicker.component.ts
  libs/components/datetime/src/lib/modules/datepicker/datepicker-input.directive.ts
  libs/components/datetime/src/lib/modules/datepicker/datepicker.component.spec.ts
Labels: risk level (author): 2, risk level (reviewer): 3

#2123 chore: release 9.30.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease 9.x.x: pending

#2129 fix(components/theme): address clipboard icon metadata issue
  libs/components/theme/package.json
  libs/components/theme/src/lib/styles/sky.scss
  package.json
Labels: risk level (author): 1

#2128 chore: release 9.30.1 (#2123)
  CHANGELOG.md
Labels: risk level (author): 1, risk level (reviewer): 1

#2132 fix(components/theme): address clipboard icon metadata issue (#2129)
  libs/components/theme/package.json
  libs/components/theme/src/lib/styles/sky.scss
  package.json
Labels: risk level (author): 1

#2119 feat(components/ag-grid): add hover style for header resize
  apps/playground/src/app/components/ag-grid/edit-complex-cells/edit-complex-cells.component.ts
  apps/playground/src/app/components/ag-grid/edit-stop-when-loses-focus/edit-stop-when-loses-focus.component.ts
  apps/playground/src/app/components/ag-grid/editable-grid/editable-grid.component.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/ag-grid-data-manager-adapter.directive.spec.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/ag-grid-data-manager-adapter.directive.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/ag-grid-wrapper.component.spec.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/ag-grid-wrapper.component.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/ag-grid.service.spec.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/ag-grid.service.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-editors/cell-editor-lookup/cell-editor-lookup.component.html
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-editors/cell-editor-lookup/cell-editor-lookup.component.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-renderers/cell-renderer-currency/cell-renderer-currency.component.spec.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-renderers/cell-renderer-row-selector/cell-renderer-row-selector.component.spec.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/fixtures/ag-grid-row-delete.component.fixture.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/fixtures/ag-grid.component.fixture.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/types/header-class.ts
  libs/components/ag-grid/src/lib/styles/_modern.scss
  libs/components/ag-grid/src/lib/styles/_variables.scss
  libs/components/ag-grid/src/lib/styles/ag-grid-styles.scss
Labels: risk level (author): 1

#2126 fix(components/datetime): accept manual input for month name date formats (#2124)
  apps/playground/src/app/components/datetime/datepicker/datepicker.component.ts
  libs/components/datetime/src/lib/modules/datepicker/datepicker-input.directive.ts
  libs/components/datetime/src/lib/modules/datepicker/datepicker.component.spec.ts
Labels: risk level (author): 2, risk level (reviewer): 3

#2063 ci: set percy target commit
  .github/actions/e2e-affected/action.yml
  .github/actions/nx-set-shas/action.yml
  .github/workflows/e2e.yml
  libs/sdk/e2e-schematics/src/workflow/index.ts
  libs/sdk/e2e-schematics/src/workflow/percy-api/percy-api.spec.ts
  libs/sdk/e2e-schematics/src/workflow/percy-api/percy-api.ts
  nx.json
  package-lock.json
  package.json
Labels: risk level (author): 1, skip e2e

#2131 chore: release 9.30.2
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease 9.x.x: pending

#2136 chore: release 9.30.2 (#2131)
  CHANGELOG.md
Labels: risk level (author): 1, risk level (reviewer): 1

#2130 chore: release 10.0.0-alpha.5
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#2135 ci: set percy target commit (#2063)
  .github/actions/e2e-affected/action.yml
  .github/actions/nx-set-shas/action.yml
  .github/workflows/e2e.yml
  libs/sdk/e2e-schematics/src/workflow/index.ts
  libs/sdk/e2e-schematics/src/workflow/percy-api/percy-api.spec.ts
  libs/sdk/e2e-schematics/src/workflow/percy-api/percy-api.ts
  package-lock.json
  package.json
Labels: risk level (author): 1

#2137 chore: add vscode launch configurations for debugging
  .vscode/launch.json
  .vscode/tasks.json
Labels: risk level (author): 1

#2138 chore: add vscode launch configurations for debugging (#2137)
  .vscode/launch.json
  .vscode/tasks.json
Labels: risk level (author): 1

#2134 fix(components/ag-grid): make row selector keyboard accessible
  .github/workflows/e2e.yml
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-renderers/cell-renderer-row-selector/cell-renderer-row-selector.component.html
  libs/components/ag-grid/src/lib/styles/_modern-dark.scss
  libs/components/ag-grid/src/lib/styles/_modern-light.scss
Labels: risk level (author): 1, skip e2e

#2139 feat(components/text-editor): add `labelText` input to text editor component
  apps/e2e/text-editor-storybook-e2e/src/e2e/text-editor.component.cy.ts
  apps/e2e/text-editor-storybook/src/app/text-editor/text-editor.component.html
  apps/e2e/text-editor-storybook/src/app/text-editor/text-editor.component.ts
  apps/playground/src/app/components/text-editor/text-editor/text-editor.component.html
  apps/playground/src/app/components/text-editor/text-editor/text-editor.component.ts
  libs/components/forms/src/lib/modules/input-box/input-box.component.scss
  libs/components/text-editor/src/lib/modules/text-editor/services/text-editor-adapter.service.ts
  libs/components/text-editor/src/lib/modules/text-editor/services/text-editor.service.ts
  libs/components/text-editor/src/lib/modules/text-editor/text-editor.component.html
  libs/components/text-editor/src/lib/modules/text-editor/text-editor.component.scss
  libs/components/text-editor/src/lib/modules/text-editor/text-editor.component.ts
  libs/components/text-editor/src/lib/modules/text-editor/types/editor-setting.ts
  libs/components/theme/src/lib/styles/_variables-private.scss
Labels: risk level (author): 3, screenshot removed

#2143 chore(components/ag-grid): update ng-update range
  libs/components/packages/package.json
Labels: risk level (author): 1

#2144 ci: update pipelines on 9.x.x
  .github/actions/e2e-affected/action.yml
  .github/actions/nx-set-shas/action.yml
  .github/workflows/cherry-pick.yml
  .github/workflows/ci.yml
  .github/workflows/e2e-cancel.yml
  .github/workflows/e2e-check.yml
  .github/workflows/e2e-cleanup.yml
  .github/workflows/e2e.yml
  .github/workflows/release-please.yml
  .github/workflows/risk-assessment.yml
  .github/workflows/skyux-azboards.yml
  .github/workflows/update-branch.yml
  .github/workflows/validate-pr.yml
Labels: risk level (author): 1, skip e2e

#2140 chore: release 10.0.0-alpha.6
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#2142 fix(components/forms): radio group uses a fieldset for accessibility grouping
  apps/playground/src/app/components/forms/radio/radio.component.html
  libs/components/forms/src/lib/modules/radio/radio-group.component.html
  libs/components/forms/src/lib/modules/radio/radio-group.component.spec.ts
Labels: risk level (author): 2

#2147 fix(components/tabs): suppress indistinct values from sectioned form `indexChange` event
  libs/components/tabs/src/lib/modules/sectioned-form/sectioned-form.component.spec.ts
  libs/components/tabs/src/lib/modules/sectioned-form/sectioned-form.component.ts
Labels: risk level (author): 2

#2148 fix(components/tabs): suppress indistinct values from sectioned form `indexChange` event (#2147)
  libs/components/tabs/src/lib/modules/sectioned-form/sectioned-form.component.spec.ts
  libs/components/tabs/src/lib/modules/sectioned-form/sectioned-form.component.ts
Labels: risk level (author): 2

#2145 fix(components/forms): radio group uses a fieldset for accessibility grouping (#2142)
  apps/playground/src/app/components/forms/radio/radio.component.html
  libs/components/forms/src/lib/modules/radio/radio-group.component.html
  libs/components/forms/src/lib/modules/radio/radio-group.component.spec.ts
Labels: risk level (author): 2

#2146 chore: release 9.30.3
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease 9.x.x: pending

#2151 chore: release 9.30.3 (#2146)
  CHANGELOG.md
Labels: risk level (author): 1, risk level (reviewer): 1

#2150 feat(components/ag-grid): support AG Grid 31.2.0
  libs/components/ag-grid/package.json
  libs/components/ag-grid/src/lib/modules/ag-grid/ag-grid.service.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-editors/cell-editor-lookup/cell-editor-lookup.component.ts
  libs/components/packages/package.json
  libs/components/packages/src/schematics/ag-grid-migrate/ag-grid-migrate.schematic.spec.ts
  libs/components/packages/src/schematics/ag-grid-migrate/ag-grid-migrate.schematic.ts
  libs/components/packages/src/schematics/migrations/update-10/ag-grid/__snapshots__/ag-grid.schematic.spec.ts.snap
  libs/components/packages/src/schematics/migrations/update-10/ag-grid/ag-grid.schematic.spec.ts
  libs/components/packages/src/schematics/migrations/update-10/ag-grid/ag-grid.schematic.ts
  libs/sdk/tools/src/generators/update-dependencies/generator.spec.ts
  libs/sdk/tools/src/generators/update-dependencies/generator.ts
  package-lock.json
  package.json
Labels: risk level (author): 1

#2153 fix(components/datetime): update date-range-picker status when calculator changes
  libs/components/datetime/src/lib/modules/date-range-picker/date-range-picker.component.spec.ts
  libs/components/datetime/src/lib/modules/date-range-picker/date-range-picker.component.ts
Labels: risk level (author): 1

#2156 fix(components/datetime): update date-range-picker status when calculator changes (#2153)
  libs/components/datetime/src/lib/modules/date-range-picker/date-range-picker.component.spec.ts
  libs/components/datetime/src/lib/modules/date-range-picker/date-range-picker.component.ts
Labels: risk level (author): 1

#2154 feat!: remove `@skyux/http`
  .github/workflows/validate-pr.yml
  .skyuxdev.json
  README.md
  libs/components/http/.eslintrc.json
  libs/components/http/CHANGELOG.md
  libs/components/http/README.md
  libs/components/http/karma.conf.js
  libs/components/http/ng-package.json
  libs/components/http/package.json
  libs/components/http/project.json
  libs/components/http/src/index.ts
  libs/components/http/src/lib/modules/auth-http-client/auth-context-args.ts
  libs/components/http/src/lib/modules/auth-http-client/auth-context-provider.spec.ts
  libs/components/http/src/lib/modules/auth-http-client/auth-context-provider.ts
  libs/components/http/src/lib/modules/auth-http-client/auth-get-token-args.ts
  libs/components/http/src/lib/modules/auth-http-client/auth-http-client.module.ts
  libs/components/http/src/lib/modules/auth-http-client/auth-interceptor-default-permission-scope.ts
  libs/components/http/src/lib/modules/auth-http-client/auth-interceptor-params.ts
  libs/components/http/src/lib/modules/auth-http-client/auth-interceptor.spec.ts
  libs/components/http/src/lib/modules/auth-http-client/auth-interceptor.ts
  libs/components/http/src/lib/modules/auth-http-client/auth-options.spec.ts
  libs/components/http/src/lib/modules/auth-http-client/auth-options.ts
  libs/components/http/src/lib/modules/auth-http-client/auth-token-context-args.ts
  libs/components/http/src/lib/modules/auth-http-client/auth-token-provider.spec.ts
  libs/components/http/src/lib/modules/auth-http-client/auth-token-provider.ts
  libs/components/http/src/lib/modules/auth-http-client/auth-token.ts
  libs/components/http/src/lib/modules/auth-http-client/no-auth-interceptor.spec.ts
  libs/components/http/src/lib/modules/auth-http-client/no-auth-interceptor.ts
  libs/components/http/src/lib/modules/auth-http-client/testing/sky-http-interceptor.test-utils.ts
  libs/components/http/testing/karma.conf.js
  libs/components/http/testing/ng-package.json
  libs/components/http/testing/project.json
  libs/components/http/testing/src/auth-http-client/auth-http-client-controller.spec.ts
  libs/components/http/testing/src/auth-http-client/auth-http-client-testing.module.ts
  libs/components/http/testing/src/auth-http-client/auth-http-testing-controller.ts
  libs/components/http/testing/src/auth-http-client/auth-token-mock-provider.ts
  libs/components/http/testing/src/auth-http-client/mock-app-config.ts
  libs/components/http/testing/src/public-api.ts
  libs/components/http/testing/tsconfig.spec.json
  libs/components/http/tsconfig.json
  libs/components/http/tsconfig.lib.json
  libs/components/http/tsconfig.lib.prod.json
  libs/components/http/tsconfig.spec.json
  libs/components/packages/package.json
  tsconfig.base.json
Labels: risk level (author): 4

#2152 fix(components/text-editor): paste menu button works on browsers supporting the Clipboard API
  libs/components/text-editor/src/assets/locales/resources_en_US.json
  libs/components/text-editor/src/lib/modules/shared/sky-text-editor-resources.module.ts
  libs/components/text-editor/src/lib/modules/text-editor/services/text-editor-adapter.service.ts
  libs/components/text-editor/src/lib/modules/text-editor/text-editor.component.html
  libs/components/text-editor/src/lib/modules/text-editor/text-editor.component.spec.ts
Labels: risk level (author): 2

#2159 fix(components/text-editor): paste menu button works on browsers supporting the Clipboard API (#2152)
  libs/components/text-editor/src/assets/locales/resources_en_US.json
  libs/components/text-editor/src/lib/modules/shared/sky-text-editor-resources.module.ts
  libs/components/text-editor/src/lib/modules/text-editor/services/text-editor-adapter.service.ts
  libs/components/text-editor/src/lib/modules/text-editor/text-editor.component.html
  libs/components/text-editor/src/lib/modules/text-editor/text-editor.component.spec.ts
Labels: risk level (author): 2

#2157 ci: allow missing screenshots on pr merge
  .github/workflows/e2e.yml
Labels: risk level (author): 1

#2161 ci: allow missing screenshots on pr merge (#2157)
  .github/workflows/e2e.yml
Labels: risk level (author): 1

#2163 feat(components/ag-grid): additional schematics
  libs/components/packages/src/schematics/migrations/update-10/ag-grid/__snapshots__/ag-grid.schematic.spec.ts.snap
  libs/components/packages/src/schematics/migrations/update-10/ag-grid/ag-grid.schematic.spec.ts
  libs/components/packages/src/schematics/migrations/update-10/ag-grid/ag-grid.schematic.ts
Labels: risk level (author): 1

#2164 feat(components/theme): update to icons library version 7
  libs/components/packages/package.json
  libs/components/theme/package.json
  libs/components/theme/src/lib/styles/sky.scss
  package-lock.json
  package.json
Labels: risk level (author): 1

#2155 chore: release 9.30.4
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease 9.x.x: pending

#2167 ci: release as 10.0.0-rc.0
  .github/workflows/release-please.yml
Labels: risk level (author): 1

#2160 chore: release 10.0.0-rc.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#2170 feat(components/ag-grid): update grid api references
  libs/components/packages/src/schematics/migrations/update-10/ag-grid/__snapshots__/ag-grid.schematic.spec.ts.snap
  libs/components/packages/src/schematics/migrations/update-10/ag-grid/ag-grid.schematic.spec.ts
  libs/components/packages/src/schematics/migrations/update-10/ag-grid/ag-grid.schematic.ts
Labels: risk level (author): 1

#2172 ci: reset release-as
  .github/workflows/release-please.yml
Labels: risk level (author): 1

#2166 fix(components/phone-field): add change detection for input only events
  libs/components/phone-field/src/lib/modules/phone-field/phone-field-input.directive.ts
Labels: risk level (author): 1

#2173 fix(components/phone-field): add change detection for input only events (#2166)
  libs/components/phone-field/src/lib/modules/phone-field/phone-field-input.directive.ts
Labels: risk level (author): 1

#2176 fix(components/ag-grid): modify schematics after testing
  libs/components/packages/src/schematics/migrations/update-10/ag-grid/__snapshots__/ag-grid.schematic.spec.ts.snap
  libs/components/packages/src/schematics/migrations/update-10/ag-grid/ag-grid.schematic.spec.ts
  libs/components/packages/src/schematics/migrations/update-10/ag-grid/ag-grid.schematic.ts
Labels: risk level (author): 1

#2171 chore: release 10.0.0-rc.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#2178 feat: release 10.0.0
  .github/workflows/release-please.yml
Labels: risk level (author): 1

#2180 chore: release 10.0.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#2169 feat(components/forms): add labelText and labelHidden preview inputs to multi file attachment component
  apps/code-examples/src/app/code-examples/forms/file-attachment/basic/demo.component.html
  apps/code-examples/src/app/code-examples/forms/file-attachment/basic/demo.component.ts
  libs/components/forms/src/lib/modules/file-attachment/file-drop.component.html
  libs/components/forms/src/lib/modules/file-attachment/file-drop.component.scss
  libs/components/forms/src/lib/modules/file-attachment/file-drop.component.spec.ts
  libs/components/forms/src/lib/modules/file-attachment/file-drop.component.ts
Labels: risk level (author): 1

#2184 chore: update changelog for 10.0.0
  .github/workflows/release-please.yml
  CHANGELOG.md
Labels: risk level (author): 1

#2183 ci: reset release-as
  .github/workflows/release-please.yml
Labels: risk level (author): 1

#2168 feat(components/forms): add radio labelText input and deprecate old labels
  apps/code-examples/src/app/code-examples/forms/radio/standard/demo.component.html
  apps/e2e/forms-storybook/src/app/radio-button/radio-button.component.html
  libs/components/forms/src/lib/modules/radio/fixtures/radio.component.fixture.html
  libs/components/forms/src/lib/modules/radio/fixtures/radio.component.fixture.ts
  libs/components/forms/src/lib/modules/radio/radio-label.component.ts
  libs/components/forms/src/lib/modules/radio/radio.component.html
  libs/components/forms/src/lib/modules/radio/radio.component.spec.ts
  libs/components/forms/src/lib/modules/radio/radio.component.ts
Labels: risk level (author): 1

#2174 chore: release 9.30.5
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease 9.x.x: pending

#2185 chore: release 9.30.5 (#2174)
  CHANGELOG.md
Labels: risk level (author): 1, risk level (reviewer): 1

#2186 ci: capture error logs on release
  .github/workflows/release-please.yml
Labels: risk level (author): 1

#2188 ci: capture error logs on release, fix path
  .github/workflows/release-please.yml
Labels: risk level (author): 1

#2189 fix(components/forms): file sizes use powers of two to calculate KB, MB, and GB
  libs/components/avatar/src/lib/modules/avatar/avatar.component.spec.ts
  libs/components/avatar/src/lib/modules/avatar/avatar.component.ts
  libs/components/avatar/src/lib/modules/avatar/fixtures/avatar.component.fixture.ts
  libs/components/forms/src/lib/modules/file-attachment/file-item.component.spec.ts
  libs/components/forms/src/lib/modules/file-attachment/file-size.pipe.spec.ts
  libs/components/forms/src/lib/modules/file-attachment/file-size.pipe.ts
  package.json
Labels: risk level (author): 2

#2191 ci: update dev-infra to 9.0.0-alpha.21
  package-lock.json
  package.json
Labels: risk level (author): 1

#2190 fix(components/phone-field): phone field hint text uses generic characters to display the phone number format
  libs/components/phone-field/src/lib/modules/phone-field/phone-field.component.spec.ts
  libs/components/phone-field/src/lib/modules/phone-field/phone-field.component.ts
Labels: risk level (author): 1

#2192 fix(sdk/testing): allow fieldsets with radiogroup role during accessibility testing
  libs/sdk/testing/src/lib/a11y/a11y-analyzer.spec.ts
  libs/sdk/testing/src/lib/a11y/a11y-analyzer.ts
Labels: risk level (author): 2

#2194 chore: release 9.30.6
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease 9.x.x: pending

#2196 chore: release 9.30.6 (#2194)
  CHANGELOG.md
Labels: risk level (author): 1, risk level (reviewer): 1
