Repository blackbaud/skyux, pull requests merged in 2024-02, with the labels that each got.

#1979 feat(components/colorpicker): add labelText input (#1968)
  apps/code-examples/src/app/code-examples/colorpicker/colorpicker/basic/demo.component.html
  apps/code-examples/src/app/code-examples/colorpicker/colorpicker/basic/demo.component.ts
  apps/code-examples/src/app/code-examples/colorpicker/colorpicker/programmatic/demo.component.html
  apps/code-examples/src/app/code-examples/colorpicker/colorpicker/programmatic/demo.component.ts
  apps/playground/src/app/components/colorpicker/colorpicker/colorpicker.component.html
  apps/playground/src/app/components/colorpicker/colorpicker/colorpicker.module.ts
  libs/components/colorpicker/src/lib/modules/colorpicker/colorpicker-input.directive.ts
  libs/components/colorpicker/src/lib/modules/colorpicker/colorpicker-input.service.ts
  libs/components/colorpicker/src/lib/modules/colorpicker/colorpicker.component.html
  libs/components/colorpicker/src/lib/modules/colorpicker/colorpicker.component.spec.ts
  libs/components/colorpicker/src/lib/modules/colorpicker/colorpicker.component.ts
  libs/components/colorpicker/src/lib/modules/colorpicker/fixtures/colorpicker-component.fixture.html
  libs/components/colorpicker/src/lib/modules/colorpicker/fixtures/colorpicker-component.fixture.ts
  libs/components/colorpicker/src/lib/modules/colorpicker/fixtures/colorpicker-reactive-component.fixture.html
  libs/components/colorpicker/src/lib/modules/colorpicker/fixtures/colorpicker-reactive-component.fixture.ts
Labels: risk level (author): 1

#1985 fix(sdk/eslint-config): downgrade `package-json` to `7.0.0` since it only works with ES modules
  libs/sdk/eslint-config/package.json
  package-lock.json
  package.json
Labels: risk level (author): 1

#1981 fix(components/forms): refactor form errors
  apps/code-examples/src/app/code-examples/forms/input-box/basic/demo.component.html
  apps/code-examples/src/app/code-examples/forms/input-box/basic/demo.component.spec.ts
  apps/code-examples/src/app/code-examples/forms/input-box/basic/demo.component.ts
  apps/playground/src/app/components/forms/input-box/input-box.component.html
  apps/playground/src/app/components/forms/input-box/input-box.component.ts
  libs/components/forms/src/index.ts
  libs/components/forms/src/lib/modules/form-error/form-error.component.spec.ts
  libs/components/forms/src/lib/modules/form-error/form-error.component.ts
  libs/components/forms/src/lib/modules/form-error/form-error.module.ts
  libs/components/forms/src/lib/modules/form-error/form-errors-enabled-token.ts
  libs/components/forms/src/lib/modules/form-error/form-errors.component.html
  libs/components/forms/src/lib/modules/form-error/form-errors.component.scss
  libs/components/forms/src/lib/modules/form-error/form-errors.module.ts
  libs/components/forms/src/lib/modules/input-box/input-box.component.html
  libs/components/forms/src/lib/modules/input-box/input-box.component.ts
  libs/components/forms/src/lib/modules/input-box/input-box.module.ts
  libs/components/forms/testing/src/form-error/form-error-harness.ts
  libs/components/forms/testing/src/form-error/form-errors-harness.spec.ts
  libs/components/forms/testing/src/form-error/form-errors-harness.ts
  libs/components/forms/testing/src/input-box/fixtures/input-box-harness-test.component.html
  libs/components/forms/testing/src/input-box/fixtures/input-box-harness-test.component.ts
  libs/components/forms/testing/src/input-box/fixtures/input-box-harness-test.module.ts
  libs/components/forms/testing/src/input-box/input-box-harness.spec.ts
  libs/components/forms/testing/src/input-box/input-box-harness.ts
Labels: risk level (author): 1

#1988 fix(components/forms): refactor form errors (#1981)
  apps/code-examples/src/app/code-examples/forms/input-box/basic/demo.component.html
  apps/code-examples/src/app/code-examples/forms/input-box/basic/demo.component.spec.ts
  apps/code-examples/src/app/code-examples/forms/input-box/basic/demo.component.ts
  apps/playground/src/app/components/forms/input-box/input-box.component.html
  apps/playground/src/app/components/forms/input-box/input-box.component.ts
  libs/components/forms/src/index.ts
  libs/components/forms/src/lib/modules/form-error/form-error.component.spec.ts
  libs/components/forms/src/lib/modules/form-error/form-error.component.ts
  libs/components/forms/src/lib/modules/form-error/form-error.module.ts
  libs/components/forms/src/lib/modules/form-error/form-errors-enabled-token.ts
  libs/components/forms/src/lib/modules/form-error/form-errors.component.html
  libs/components/forms/src/lib/modules/form-error/form-errors.component.scss
  libs/components/forms/src/lib/modules/form-error/form-errors.module.ts
  libs/components/forms/src/lib/modules/input-box/input-box.component.html
  libs/components/forms/src/lib/modules/input-box/input-box.component.ts
  libs/components/forms/src/lib/modules/input-box/input-box.module.ts
  libs/components/forms/testing/src/form-error/form-error-harness.ts
  libs/components/forms/testing/src/form-error/form-errors-harness.spec.ts
  libs/components/forms/testing/src/form-error/form-errors-harness.ts
  libs/components/forms/testing/src/input-box/fixtures/input-box-harness-test.component.html
  libs/components/forms/testing/src/input-box/fixtures/input-box-harness-test.component.ts
  libs/components/forms/testing/src/input-box/fixtures/input-box-harness-test.module.ts
  libs/components/forms/testing/src/input-box/input-box-harness.spec.ts
  libs/components/forms/testing/src/input-box/input-box-harness.ts
Labels: risk level (author): 1

#1987 chore(components/theme): update @skyux/icons to 6.9.0
  libs/components/theme/package.json
  libs/components/theme/src/lib/styles/sky.scss
  package-lock.json
  package.json
Labels: risk level (author): 1

#1990 chore(components/theme): update @skyux/icons to 6.9.0 (#1987)
  libs/components/theme/package.json
  libs/components/theme/src/lib/styles/sky.scss
  package-lock.json
  package.json
Labels: risk level (author): 1

#1980 chore: release 9.23.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease 9.x.x: pending

#1992 chore: release 9.23.0 (#1980)
  CHANGELOG.md
Labels: risk level (author): 1, risk level (reviewer): 1

#1986 feat(components/tabs): add keyboard navigation to vertical tabset (#1978)
  apps/playground/src/app/components/tabs/vertical-tabset/vertical-tabset.component.html
  libs/components/tabs/src/lib/modules/vertical-tabset/vertical-tab.component.html
  libs/components/tabs/src/lib/modules/vertical-tabset/vertical-tab.component.scss
  libs/components/tabs/src/lib/modules/vertical-tabset/vertical-tab.component.ts
  libs/components/tabs/src/lib/modules/vertical-tabset/vertical-tabset-adapter.service.ts
  libs/components/tabs/src/lib/modules/vertical-tabset/vertical-tabset-group-message.ts
  libs/components/tabs/src/lib/modules/vertical-tabset/vertical-tabset-group.component.html
  libs/components/tabs/src/lib/modules/vertical-tabset/vertical-tabset-group.component.scss
  libs/components/tabs/src/lib/modules/vertical-tabset/vertical-tabset-group.component.ts
  libs/components/tabs/src/lib/modules/vertical-tabset/vertical-tabset-group.service.ts
  libs/components/tabs/src/lib/modules/vertical-tabset/vertical-tabset.component.html
  libs/components/tabs/src/lib/modules/vertical-tabset/vertical-tabset.component.spec.ts
  libs/components/tabs/src/lib/modules/vertical-tabset/vertical-tabset.component.ts
  libs/components/tabs/src/lib/modules/vertical-tabset/vertical-tabset.service.spec.ts
  libs/components/tabs/src/lib/modules/vertical-tabset/vertical-tabset.service.ts
Labels: risk level (author): 3

#1983 chore(sdk/testing): add support for `axe-core` version `4.8`
  libs/sdk/testing/package.json
  libs/sdk/testing/src/lib/matchers/matchers.spec.ts
  package-lock.json
  package.json
Labels: risk level (author): 1

#1982 feat(components/forms): hide required asterisk from screen readers
  libs/components/theme/src/lib/styles/_public-api/_compat/_mixins.scss
Labels: risk level (author): 1

#1991 fix(components/popovers): popovers with a hover trigger display when the trigger element is focused
  libs/components/popovers/src/lib/modules/popover/popover.directive.spec.ts
  libs/components/popovers/src/lib/modules/popover/popover.directive.ts
Labels: risk level (author): 2, risk level (reviewer): 2

#1997 fix(components/popovers): popovers with a hover trigger display when the trigger element is focused (#1991)
  libs/components/popovers/src/lib/modules/popover/popover.directive.spec.ts
  libs/components/popovers/src/lib/modules/popover/popover.directive.ts
Labels: risk level (author): 2, risk level (reviewer): 2

#1995 feat(components/forms): hide required asterisk from screen readers (#1982)
  libs/components/theme/src/lib/styles/_public-api/_compat/_mixins.scss
Labels: risk level (author): 1

#1998 ci: only published libraries in ci build step
  .github/workflows/ci.yml
Labels: risk level (author): 1

#1984 fix(components/tabs): tabs are read by screen readers in an industry standard format
  libs/components/tabs/src/assets/locales/resources_en_US.json
  libs/components/tabs/src/lib/modules/shared/sky-tabs-resources.module.ts
  libs/components/tabs/src/lib/modules/tabs/tab-button.component.html
  libs/components/tabs/src/lib/modules/tabs/tabs.module.ts
  libs/components/tabs/src/lib/modules/tabs/tabset.component.spec.ts
  libs/components/tabs/testing/src/tabs/tabset-fixture.ts
Labels: risk level (author): 2

#2000 fix(components/tabs): tabs are read by screen readers in an industry standard format (#1984)
  libs/components/tabs/src/assets/locales/resources_en_US.json
  libs/components/tabs/src/lib/modules/shared/sky-tabs-resources.module.ts
  libs/components/tabs/src/lib/modules/tabs/tab-button.component.html
  libs/components/tabs/src/lib/modules/tabs/tabs.module.ts
  libs/components/tabs/src/lib/modules/tabs/tabset.component.spec.ts
  libs/components/tabs/testing/src/tabs/tabset-fixture.ts
Labels: risk level (author): 2

#2001 fix(components/forms): character counter reads to screen readers at unobtrusive intervals (#1947)
  apps/playground/src/app/components/forms/character-counter/character-counter.component.html
  apps/playground/src/app/components/forms/character-counter/character-counter.component.ts
  apps/playground/src/app/components/forms/character-counter/character-counter.module.ts
  libs/components/forms/src/assets/locales/resources_en_US.json
  libs/components/forms/src/index.ts
  libs/components/forms/src/lib/modules/character-counter/character-counter-indicator.component.html
  libs/components/forms/src/lib/modules/character-counter/character-counter-screen-reader.pipe.ts
  libs/components/forms/src/lib/modules/character-counter/character-counter.component.spec.ts
  libs/components/forms/src/lib/modules/character-counter/character-counter.module.ts
  libs/components/forms/src/lib/modules/character-counter/fixtures/character-count.component.fixture.html
  libs/components/forms/src/lib/modules/input-box/input-box.component.html
  libs/components/forms/src/lib/modules/input-box/input-box.component.spec.ts
  libs/components/forms/src/lib/modules/input-box/input-box.component.ts
  libs/components/forms/src/lib/modules/input-box/input-box.module.ts
  libs/components/forms/src/lib/modules/shared/sky-forms-resources.module.ts
Labels: risk level (author): 1

#1994 feat(components/forms): add form errors to checkbox
  apps/code-examples/src/app/code-examples/forms/checkbox/basic/demo.component.html
  apps/code-examples/src/app/code-examples/forms/checkbox/basic/demo.component.ts
  apps/e2e/forms-storybook-e2e/src/e2e/checkbox.component.cy.ts
  apps/e2e/forms-storybook/src/app/checkbox/checkbox.component.html
  apps/e2e/forms-storybook/src/app/checkbox/checkbox.module.ts
  apps/playground/src/app/components/forms/checkbox/checkbox.component.ts
  libs/components/forms/src/assets/locales/resources_en_US.json
  libs/components/forms/src/lib/modules/checkbox/checkbox.component.html
  libs/components/forms/src/lib/modules/checkbox/checkbox.component.ts
  libs/components/forms/src/lib/modules/checkbox/checkbox.module.ts
  libs/components/forms/src/lib/modules/shared/sky-forms-resources.module.ts
  libs/components/forms/testing/src/checkbox/checkbox-harness.spec.ts
  libs/components/forms/testing/src/checkbox/checkbox-harness.ts
  libs/components/forms/testing/src/checkbox/fixtures/checkbox-harness-test.component.html
  libs/components/forms/testing/src/checkbox/fixtures/checkbox-harness-test.component.ts
Labels: risk level (author): 2

#1999 feat(components/colorpicker): add form errors to colorpicker
  apps/code-examples/src/app/code-examples/colorpicker/colorpicker/basic/demo.component.html
  apps/code-examples/src/app/code-examples/colorpicker/colorpicker/basic/demo.component.ts
  apps/playground/src/app/components/colorpicker/colorpicker/colorpicker.component.html
  apps/playground/src/app/components/colorpicker/colorpicker/colorpicker.component.ts
  libs/components/colorpicker/src/lib/modules/colorpicker/colorpicker-input.directive.ts
  libs/components/colorpicker/src/lib/modules/colorpicker/colorpicker-input.service.ts
  libs/components/colorpicker/src/lib/modules/colorpicker/colorpicker.component.html
  libs/components/colorpicker/src/lib/modules/colorpicker/colorpicker.component.spec.ts
  libs/components/colorpicker/src/lib/modules/colorpicker/colorpicker.component.ts
  libs/components/colorpicker/src/lib/modules/colorpicker/colorpicker.module.ts
  libs/components/colorpicker/src/lib/modules/colorpicker/fixtures/colorpicker-reactive-component.fixture.html
  libs/components/colorpicker/src/lib/modules/colorpicker/fixtures/colorpicker-reactive-component.fixture.ts
Labels: risk level (author): 2

#2004 feat(components/colorpicker): add form errors to colorpicker (#1999)
  apps/code-examples/src/app/code-examples/colorpicker/colorpicker/basic/demo.component.html
  apps/code-examples/src/app/code-examples/colorpicker/colorpicker/basic/demo.component.ts
  apps/playground/src/app/components/colorpicker/colorpicker/colorpicker.component.html
  apps/playground/src/app/components/colorpicker/colorpicker/colorpicker.component.ts
  libs/components/colorpicker/src/lib/modules/colorpicker/colorpicker-input.directive.ts
  libs/components/colorpicker/src/lib/modules/colorpicker/colorpicker-input.service.ts
  libs/components/colorpicker/src/lib/modules/colorpicker/colorpicker.component.html
  libs/components/colorpicker/src/lib/modules/colorpicker/colorpicker.component.spec.ts
  libs/components/colorpicker/src/lib/modules/colorpicker/colorpicker.component.ts
  libs/components/colorpicker/src/lib/modules/colorpicker/colorpicker.module.ts
  libs/components/colorpicker/src/lib/modules/colorpicker/fixtures/colorpicker-reactive-component.fixture.html
  libs/components/colorpicker/src/lib/modules/colorpicker/fixtures/colorpicker-reactive-component.fixture.ts
Labels: risk level (author): 2

#2003 feat(components/forms): add form errors to checkbox (#1994)
  apps/code-examples/src/app/code-examples/forms/checkbox/basic/demo.component.html
  apps/code-examples/src/app/code-examples/forms/checkbox/basic/demo.component.ts
  apps/e2e/forms-storybook-e2e/src/e2e/checkbox.component.cy.ts
  apps/e2e/forms-storybook/src/app/checkbox/checkbox.component.html
  apps/e2e/forms-storybook/src/app/checkbox/checkbox.module.ts
  apps/playground/src/app/components/forms/checkbox/checkbox.component.ts
  libs/components/forms/src/assets/locales/resources_en_US.json
  libs/components/forms/src/lib/modules/checkbox/checkbox.component.html
  libs/components/forms/src/lib/modules/checkbox/checkbox.component.ts
  libs/components/forms/src/lib/modules/checkbox/checkbox.module.ts
  libs/components/forms/src/lib/modules/shared/sky-forms-resources.module.ts
  libs/components/forms/testing/src/checkbox/checkbox-harness.spec.ts
  libs/components/forms/testing/src/checkbox/checkbox-harness.ts
  libs/components/forms/testing/src/checkbox/fixtures/checkbox-harness-test.component.html
  libs/components/forms/testing/src/checkbox/fixtures/checkbox-harness-test.component.ts
Labels: risk level (author): 2

#1996 chore: release 9.24.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease 9.x.x: pending

#2006 chore: release 9.24.0 (#1996)
  CHANGELOG.md
Labels: risk level (author): 1, risk level (reviewer): 1

#1993 feat(components/ag-grid): add support for AG Grid 30
  apps/e2e/ag-grid-storybook/src/app/shared/baseball-players-data.ts
  libs/components/ag-grid/package.json
  libs/components/ag-grid/src/lib/modules/ag-grid/ag-grid-wrapper.component.spec.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/ag-grid.service.spec.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/ag-grid.service.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-editors/cell-editor-autocomplete/cell-editor-autocomplete.component.spec.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-editors/cell-editor-autocomplete/cell-editor-autocomplete.component.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-editors/cell-editor-currency/cell-editor-currency.component.html
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-editors/cell-editor-currency/cell-editor-currency.component.spec.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-editors/cell-editor-currency/cell-editor-currency.component.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-editors/cell-editor-datepicker/cell-editor-datepicker.component.spec.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-editors/cell-editor-datepicker/cell-editor-datepicker.component.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-editors/cell-editor-lookup/cell-editor-lookup.component.spec.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-editors/cell-editor-lookup/cell-editor-lookup.component.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-editors/cell-editor-number/cell-editor-number.component.spec.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-editors/cell-editor-number/cell-editor-number.component.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-editors/cell-editor-text/cell-editor-text.component.spec.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-editors/cell-editor-text/cell-editor-text.component.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/types/cell-editor-currency-params.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/types/cell-editor-utils.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/types/header-params.ts
  libs/components/ag-grid/src/lib/styles/_base.scss
  libs/components/packages/package.json
  libs/components/packages/src/schematics/migrations/migration-collection.json
  libs/components/packages/src/schematics/migrations/update-10/ag-grid-30/__snapshots__/ag-grid-30.schematic.spec.ts.snap
  libs/components/packages/src/schematics/migrations/update-10/ag-grid-30/ag-grid-30.schematic.spec.ts
  libs/components/packages/src/schematics/migrations/update-10/ag-grid-30/ag-grid-30.schematic.ts
  package-lock.json
  package.json
Labels: risk level (author): 2

#2007 fix(components/forms): improve form error documentation
  libs/components/forms/src/lib/modules/form-error/form-error.component.ts
  libs/components/forms/testing/src/input-box/input-box-harness.ts
Labels: risk level (author): 1

#2008 fix(components/forms): improve form error documentation (#2007)
  libs/components/forms/src/lib/modules/form-error/form-error.component.ts
  libs/components/forms/testing/src/input-box/input-box-harness.ts
Labels: risk level (author): 1

#2009 chore: release 9.24.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease 9.x.x: pending

#2010 chore: release 9.24.1 (#2009)
  CHANGELOG.md
Labels: risk level (author): 1, risk level (reviewer): 1

#2011 fix(components/forms): document form error inputs as required
  libs/components/forms/src/lib/modules/form-error/form-error.component.ts
Labels: risk level (author): 1

#2013 chore: release 9.24.2
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease 9.x.x: pending

#2014 chore: release 9.24.2 (#2013)
  CHANGELOG.md
Labels: risk level (author): 1, risk level (reviewer): 1

#2002 fix(components/tiles): tile summary is not visible to screen readers when tile is expanded
  libs/components/tiles/src/lib/modules/tiles/tile/tile.component.scss
Labels: risk level (author): 1

#2016 fix(components/tiles): tile summary is not visible to screen readers when tile is expanded (#2002)
  libs/components/tiles/src/lib/modules/tiles/tile/tile.component.scss
Labels: risk level (author): 1

#2012 fix(components/forms): document form error inputs as required (#2011)
  libs/components/forms/src/lib/modules/form-error/form-error.component.ts
Labels: risk level (author): 1

#2020 fix(components/popovers): disabled dropdown items are styled to not appear clickable
  libs/components/popovers/src/lib/modules/dropdown/dropdown-item.component.scss
Labels: risk level (author): 2

#2021 feat(components/indicators): add up arrow icon
  libs/components/theme/package.json
  libs/components/theme/src/lib/styles/sky.scss
  package-lock.json
  package.json
Labels: risk level (author): 1

#2022 feat(components/indicators): add up arrow icon (#2021)
  libs/components/theme/package.json
  libs/components/theme/src/lib/styles/sky.scss
  package-lock.json
  package.json
Labels: risk level (author): 1

#2015 chore: release 9.25.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease 9.x.x: pending

#2023 chore: release 9.25.0 (#2015)
  CHANGELOG.md
Labels: risk level (author): 1, risk level (reviewer): 1

#1964 feat(components/datetime): improve keyboard navigation on datepicker calendar
  libs/components/datetime/package.json
  libs/components/datetime/src/lib/modules/datepicker/datepicker-calendar-inner.component.html
  libs/components/datetime/src/lib/modules/datepicker/datepicker-calendar-inner.component.scss
  libs/components/datetime/src/lib/modules/datepicker/datepicker-calendar-inner.component.ts
  libs/components/datetime/src/lib/modules/datepicker/datepicker-calendar.component.html
  libs/components/datetime/src/lib/modules/datepicker/datepicker-calendar.component.spec.ts
  libs/components/datetime/src/lib/modules/datepicker/datepicker.component.html
  libs/components/datetime/src/lib/modules/datepicker/datepicker.component.ts
  libs/components/datetime/src/lib/modules/datepicker/datepicker.module.ts
  libs/components/datetime/src/lib/modules/datepicker/daypicker.component.html
  libs/components/datetime/src/lib/modules/datepicker/daypicker.component.scss
  libs/components/datetime/src/lib/modules/datepicker/daypicker.component.ts
  libs/components/datetime/src/lib/modules/datepicker/monthpicker.component.html
  libs/components/datetime/src/lib/modules/datepicker/monthpicker.component.scss
  libs/components/datetime/src/lib/modules/datepicker/monthpicker.component.ts
  libs/components/datetime/src/lib/modules/datepicker/yearpicker.component.html
  libs/components/datetime/src/lib/modules/datepicker/yearpicker.component.scss
  libs/components/datetime/src/lib/modules/datepicker/yearpicker.component.ts
Labels: risk level (author): 2

#2017 chore: set ESLint rules `complexity` and `max-depth`
  .eslintrc-overrides.json
  libs/components/phone-field/src/lib/modules/phone-field/phone-field.component.ts
Labels: risk level (author): 1

#2026 feat(components/datetime): improve keyboard navigation on datepicker calendar (#1964)
  libs/components/datetime/package.json
  libs/components/datetime/src/lib/modules/datepicker/datepicker-calendar-inner.component.html
  libs/components/datetime/src/lib/modules/datepicker/datepicker-calendar-inner.component.scss
  libs/components/datetime/src/lib/modules/datepicker/datepicker-calendar-inner.component.ts
  libs/components/datetime/src/lib/modules/datepicker/datepicker-calendar.component.html
  libs/components/datetime/src/lib/modules/datepicker/datepicker-calendar.component.spec.ts
  libs/components/datetime/src/lib/modules/datepicker/datepicker.component.html
  libs/components/datetime/src/lib/modules/datepicker/datepicker.component.ts
  libs/components/datetime/src/lib/modules/datepicker/datepicker.module.ts
  libs/components/datetime/src/lib/modules/datepicker/daypicker.component.html
  libs/components/datetime/src/lib/modules/datepicker/daypicker.component.scss
  libs/components/datetime/src/lib/modules/datepicker/daypicker.component.ts
  libs/components/datetime/src/lib/modules/datepicker/monthpicker.component.html
  libs/components/datetime/src/lib/modules/datepicker/monthpicker.component.scss
  libs/components/datetime/src/lib/modules/datepicker/monthpicker.component.ts
  libs/components/datetime/src/lib/modules/datepicker/yearpicker.component.html
  libs/components/datetime/src/lib/modules/datepicker/yearpicker.component.scss
  libs/components/datetime/src/lib/modules/datepicker/yearpicker.component.ts
Labels: risk level (author): 2

#2024 fix(components/tabs): show vertical tab content when activated programmatically after init
  libs/components/tabs/src/lib/modules/vertical-tabset/fixtures/vertical-tabs-fixtures.module.ts
  libs/components/tabs/src/lib/modules/vertical-tabset/fixtures/vertical-tabset-programmatic.component.ts
  libs/components/tabs/src/lib/modules/vertical-tabset/fixtures/vertical-tabset.component.fixture.ts
  libs/components/tabs/src/lib/modules/vertical-tabset/vertical-tab.component.ts
  libs/components/tabs/src/lib/modules/vertical-tabset/vertical-tabset.component.spec.ts
Labels: risk level (author): 2

#2029 feat(components/ag-grid): support custom label for row selector
  apps/code-examples/src/app/code-examples/ag-grid/data-entry-grid/basic/demo.component.ts
  apps/code-examples/src/app/code-examples/ag-grid/data-entry-grid/data-manager-added/view-grid.component.ts
  apps/code-examples/src/app/code-examples/ag-grid/data-entry-grid/inline-help/demo.component.ts
  apps/code-examples/src/app/code-examples/ag-grid/data-grid/basic-multiselect/demo.component.ts
  apps/code-examples/src/app/code-examples/ag-grid/data-grid/data-manager-multiselect/view-grid.component.ts
  apps/code-examples/src/app/code-examples/ag-grid/data-grid/inline-help/demo.component.ts
  apps/code-examples/src/app/code-examples/ag-grid/data-grid/top-scroll/demo.component.ts
  apps/code-examples/src/app/code-examples/data-manager/data-manager/basic/view-grid.component.ts
  apps/playground/src/app/components/ag-grid/edit-complex-cells/edit-complex-cells.component.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-renderers/cell-renderer-row-selector/cell-renderer-row-selector.component.html
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-renderers/cell-renderer-row-selector/cell-renderer-row-selector.component.spec.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-renderers/cell-renderer-row-selector/cell-renderer-row-selector.component.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-renderers/cell-renderer-row-selector/cell-renderer-row-selector.module.ts
Labels: risk level (author): 1

#2032 feat(components/ag-grid): support custom label for row selector (#2029)
  apps/code-examples/src/app/code-examples/ag-grid/data-entry-grid/basic/demo.component.ts
  apps/code-examples/src/app/code-examples/ag-grid/data-entry-grid/data-manager-added/view-grid.component.ts
  apps/code-examples/src/app/code-examples/ag-grid/data-entry-grid/inline-help/demo.component.ts
  apps/code-examples/src/app/code-examples/ag-grid/data-grid/basic-multiselect/demo.component.ts
  apps/code-examples/src/app/code-examples/ag-grid/data-grid/data-manager-multiselect/view-grid.component.ts
  apps/code-examples/src/app/code-examples/ag-grid/data-grid/inline-help/demo.component.ts
  apps/code-examples/src/app/code-examples/ag-grid/data-grid/top-scroll/demo.component.ts
  apps/code-examples/src/app/code-examples/data-manager/data-manager/basic/view-grid.component.ts
  apps/playground/src/app/components/ag-grid/edit-complex-cells/edit-complex-cells.component.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-renderers/cell-renderer-row-selector/cell-renderer-row-selector.component.html
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-renderers/cell-renderer-row-selector/cell-renderer-row-selector.component.spec.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-renderers/cell-renderer-row-selector/cell-renderer-row-selector.component.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-renderers/cell-renderer-row-selector/cell-renderer-row-selector.module.ts
Labels: risk level (author): 1

#2027 fix(components/tabs): show vertical tab content when activated programmatically after init (#2024)
  libs/components/tabs/src/lib/modules/vertical-tabset/fixtures/vertical-tabs-fixtures.module.ts
  libs/components/tabs/src/lib/modules/vertical-tabset/fixtures/vertical-tabset-programmatic.component.ts
  libs/components/tabs/src/lib/modules/vertical-tabset/fixtures/vertical-tabset.component.fixture.ts
  libs/components/tabs/src/lib/modules/vertical-tabset/vertical-tab.component.ts
  libs/components/tabs/src/lib/modules/vertical-tabset/vertical-tabset.component.spec.ts
Labels: risk level (author): 2

#2037 feat(components/forms): add labelText to radio group (#2018)
  apps/code-examples/src/app/code-examples/forms/radio/icon/demo.component.html
  apps/code-examples/src/app/code-examples/forms/radio/inline-help/demo.component.html
  apps/code-examples/src/app/code-examples/forms/radio/standard/demo.component.html
  apps/e2e/forms-storybook/src/app/radio-button/radio-button.component.html
  apps/playground/src/app/components/forms/radio/radio.component.html
  libs/components/forms/src/lib/modules/radio/fixtures/radio-group-reactive.component.fixture.html
  libs/components/forms/src/lib/modules/radio/fixtures/radio-group-reactive.component.fixture.ts
  libs/components/forms/src/lib/modules/radio/radio-group.component.html
  libs/components/forms/src/lib/modules/radio/radio-group.component.spec.ts
  libs/components/forms/src/lib/modules/radio/radio-group.component.ts
  libs/components/forms/src/lib/modules/radio/radio.module.ts
  libs/components/theme/src/lib/styles/_switch.scss
Labels: risk level (author): 2

#2034 fix(components/datetime): keep date consistent when switching meridies
  libs/components/datetime/src/lib/modules/timepicker/timepicker.component.spec.ts
  libs/components/datetime/src/lib/modules/timepicker/timepicker.component.ts
Labels: risk level (author): 2

#2039 fix(components/datetime): keep date consistent when switching meridies (#2034)
  libs/components/datetime/src/lib/modules/timepicker/timepicker.component.spec.ts
  libs/components/datetime/src/lib/modules/timepicker/timepicker.component.ts
Labels: risk level (author): 2

#2005 feat(components/lists): improve keyboard navigation on sort picker
  libs/components/lists/src/lib/modules/sort/sort-item.component.html
  libs/components/lists/src/lib/modules/sort/sort-item.component.scss
  libs/components/lists/src/lib/modules/sort/sort-item.component.ts
  libs/components/lists/src/lib/modules/sort/sort.component.html
  libs/components/lists/src/lib/modules/sort/sort.component.scss
  libs/components/lists/src/lib/modules/sort/sort.component.ts
Labels: risk level (author): 3

#2040 feat(components/lists): improve keyboard navigation on sort picker (#2005)
  libs/components/lists/src/lib/modules/sort/sort-item.component.html
  libs/components/lists/src/lib/modules/sort/sort-item.component.scss
  libs/components/lists/src/lib/modules/sort/sort-item.component.ts
  libs/components/lists/src/lib/modules/sort/sort.component.html
  libs/components/lists/src/lib/modules/sort/sort.component.scss
  libs/components/lists/src/lib/modules/sort/sort.component.ts
Labels: risk level (author): 3

#2030 feat(components/packages): update axe-core if @skyux-sdk/testing installed
  libs/components/packages/src/schematics/migrations/migration-collection.json
  libs/components/packages/src/schematics/migrations/update-10/axe-core/axe-core.schematic.spec.ts
  libs/components/packages/src/schematics/migrations/update-10/axe-core/axe-core.schematic.ts
Labels: risk level (author): 2

#2033 feat(components/datetime): add aria labels to datepicker calendar navigation buttons
  libs/components/datetime/src/assets/locales/resources_en_US.json
  libs/components/datetime/src/lib/modules/datepicker/datepicker-calendar-inner.component.html
  libs/components/datetime/src/lib/modules/datepicker/datepicker-calendar-inner.component.ts
  libs/components/datetime/src/lib/modules/datepicker/datepicker-calendar.component.spec.ts
  libs/components/datetime/src/lib/modules/shared/sky-datetime-resources.module.ts
Labels: risk level (author): 1

#2025 chore: release 9.26.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease 9.x.x: pending

#2042 feat(components/datetime): add aria labels to datepicker calendar navigation buttons (#2033)
  libs/components/datetime/src/assets/locales/resources_en_US.json
  libs/components/datetime/src/lib/modules/datepicker/datepicker-calendar-inner.component.html
  libs/components/datetime/src/lib/modules/datepicker/datepicker-calendar-inner.component.ts
  libs/components/datetime/src/lib/modules/datepicker/datepicker-calendar.component.spec.ts
  libs/components/datetime/src/lib/modules/shared/sky-datetime-resources.module.ts
Labels: risk level (author): 1

#2043 chore: release 9.26.0 (#2025)
  CHANGELOG.md
Labels: risk level (author): 1, risk level (reviewer): 1

#2046 feat(components/forms): radio button form errors support (#2044)
  apps/e2e/forms-storybook-e2e/src/e2e/radio-button.component.cy.ts
  apps/e2e/forms-storybook/src/app/radio-button/radio-button.component.html
  apps/e2e/forms-storybook/src/app/radio-button/radio-button.component.ts
  apps/playground/src/app/components/forms/radio/radio.component.html
  apps/playground/src/app/components/forms/radio/radio.component.ts
  libs/components/forms/src/assets/locales/resources_en_US.json
  libs/components/forms/src/lib/modules/form-error/form-errors.component.html
  libs/components/forms/src/lib/modules/input-box/fixtures/input-box.component.fixture.html
  libs/components/forms/src/lib/modules/input-box/input-box.component.html
  libs/components/forms/src/lib/modules/input-box/input-box.component.spec.ts
  libs/components/forms/src/lib/modules/radio/fixtures/radio-group-reactive.component.fixture.html
  libs/components/forms/src/lib/modules/radio/fixtures/radio-group-reactive.component.fixture.ts
  libs/components/forms/src/lib/modules/radio/radio-group.component.html
  libs/components/forms/src/lib/modules/radio/radio-group.component.spec.ts
  libs/components/forms/src/lib/modules/radio/radio-group.component.ts
  libs/components/forms/src/lib/modules/radio/radio.module.ts
  libs/components/forms/src/lib/modules/shared/sky-forms-resources.module.ts
Labels: risk level (author): 2

#2041 feat(components/packages): remove backward compatible stylesheets from prior migrations
  libs/components/packages/src/index.ts
  libs/components/packages/src/schematics/migrations/migration-collection.json
  libs/components/packages/src/schematics/migrations/update-10/add-compat-stylesheets/__snapshots__/add-compat-stylesheet.schematic.spec.ts.snap
  libs/components/packages/src/schematics/migrations/update-10/add-compat-stylesheets/add-compat-stylesheet.schematic.spec.ts
  libs/components/packages/src/schematics/migrations/update-10/add-compat-stylesheets/add-compat-stylesheet.schematic.ts
  libs/components/packages/src/schematics/migrations/update-10/remove-old-compat-stylesheets/remove-old-compat-stylesheets.schematic.spec.ts
  libs/components/packages/src/schematics/migrations/update-10/remove-old-compat-stylesheets/remove-old-compat-stylesheets.schematic.ts
  libs/components/packages/src/version.ts
Labels: risk level (author): 2

#1989 chore: release 10.0.0-alpha.2
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#2047 feat(components/ag-grid): update default theme background for uneditable cells
  libs/components/ag-grid/src/lib/styles/_default.scss
Labels: risk level (author): 1

#2028 feat(components/datetime): datepicker date format information moved to input box hint text
  apps/e2e/datetime-storybook/src/app/datepicker/datepicker.component.html
  apps/playground/src/app/components/datetime/datepicker/datepicker.component.html
  apps/playground/src/app/components/forms/input-box/input-box-visual-host.component.ts
  apps/playground/src/app/components/forms/input-box/input-box.component.html
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-editors/cell-editor-datepicker/cell-editor-datepicker.component.spec.ts
  libs/components/datetime/src/assets/locales/resources_en_US.json
  libs/components/datetime/src/lib/modules/datepicker/datepicker-adapter.service.ts
  libs/components/datetime/src/lib/modules/datepicker/datepicker-calendar.component.ts
  libs/components/datetime/src/lib/modules/datepicker/datepicker-input.directive.ts
  libs/components/datetime/src/lib/modules/datepicker/datepicker.component.spec.ts
  libs/components/datetime/src/lib/modules/datepicker/datepicker.component.ts
  libs/components/datetime/src/lib/modules/datepicker/fixtures/datepicker-input-box.component.fixture.html
  libs/components/datetime/src/lib/modules/datepicker/fixtures/datepicker-input-box.component.fixture.ts
  libs/components/datetime/src/lib/modules/datepicker/fixtures/datepicker-reactive.component.fixture.html
  libs/components/datetime/src/lib/modules/datepicker/fixtures/datepicker.component.fixture.html
  libs/components/datetime/src/lib/modules/datepicker/fixtures/fuzzy-datepicker-reactive.component.fixture.html
  libs/components/datetime/src/lib/modules/shared/sky-datetime-resources.module.ts
  libs/components/forms/src/lib/modules/input-box/fixtures/input-box-host-service.component.fixture.ts
  libs/components/forms/src/lib/modules/input-box/fixtures/input-box.component.fixture.html
  libs/components/forms/src/lib/modules/input-box/input-box-hint-text.pipe.ts
  libs/components/forms/src/lib/modules/input-box/input-box-host.service.spec.ts
  libs/components/forms/src/lib/modules/input-box/input-box-host.service.ts
  libs/components/forms/src/lib/modules/input-box/input-box.component.html
  libs/components/forms/src/lib/modules/input-box/input-box.component.spec.ts
  libs/components/forms/src/lib/modules/input-box/input-box.component.ts
  libs/components/forms/src/lib/modules/input-box/input-box.module.ts
  libs/components/indicators/src/lib/modules/wait/wait.component.spec.ts
Labels: risk level (author): 5

#2019 feat(components/forms): add labelText input to toggle switch
  apps/e2e/forms-storybook/src/app/toggle-switch/toggle-switch.component.html
  apps/playground/src/app/components/forms/toggle-switch/toggle-switch.component.html
  libs/components/forms/src/lib/modules/toggle-switch/fixtures/toggle-switch.component.fixture.html
  libs/components/forms/src/lib/modules/toggle-switch/fixtures/toggle-switch.component.fixture.ts
  libs/components/forms/src/lib/modules/toggle-switch/toggle-switch-label.component.ts
  libs/components/forms/src/lib/modules/toggle-switch/toggle-switch.component.html
  libs/components/forms/src/lib/modules/toggle-switch/toggle-switch.component.spec.ts
  libs/components/forms/src/lib/modules/toggle-switch/toggle-switch.component.ts
Labels: risk level (author): 2

#2052 feat(components/forms): add labelText input to toggle switch (#2019)
  apps/e2e/forms-storybook/src/app/toggle-switch/toggle-switch.component.html
  apps/playground/src/app/components/forms/toggle-switch/toggle-switch.component.html
  libs/components/forms/src/lib/modules/toggle-switch/fixtures/toggle-switch.component.fixture.html
  libs/components/forms/src/lib/modules/toggle-switch/fixtures/toggle-switch.component.fixture.ts
  libs/components/forms/src/lib/modules/toggle-switch/toggle-switch-label.component.ts
  libs/components/forms/src/lib/modules/toggle-switch/toggle-switch.component.html
  libs/components/forms/src/lib/modules/toggle-switch/toggle-switch.component.spec.ts
  libs/components/forms/src/lib/modules/toggle-switch/toggle-switch.component.ts
Labels: risk level (author): 2

#2058 ci: set percy target branch
  .github/workflows/e2e.yml
Labels: risk level (author): 1

#2057 test: include both easy and hard mode input boxes in field height tests
  apps/integration/src/app/integrations/field-heights/field-heights.component.html
  apps/integration/src/app/integrations/field-heights/field-heights.component.scss
  apps/integration/src/app/integrations/field-heights/field-heights.component.ts
Labels: risk level (author): 1

#2053 feat(sdk/prettier-schematics)!: add support for `prettier@3`
  .prettierrc
  libs/components/packages/src/schematics/migrations/update-10/axe-core/axe-core.schematic.spec.ts
  libs/sdk/prettier-schematics/package.json
  libs/sdk/prettier-schematics/src/schematics/migrations/migration-collection.json
  libs/sdk/prettier-schematics/src/schematics/migrations/update-10/sort-imports-plugin/sort-imports-plugin.schematic.spec.ts
  libs/sdk/prettier-schematics/src/schematics/migrations/update-10/sort-imports-plugin/sort-imports-plugin.schematic.ts
  libs/sdk/prettier-schematics/src/schematics/ng-add/ng-add.schematic.spec.ts
  libs/sdk/prettier-schematics/src/schematics/ng-add/rules/add-prettier-dependencies.ts
  package-lock.json
  package.json
Labels: risk level (author): 2

#2055 feat(components/forms): checkbox label deprecations
  libs/components/forms/src/lib/modules/checkbox/checkbox-label-text-label.component.html
  libs/components/forms/src/lib/modules/checkbox/checkbox-label-text-label.component.ts
  libs/components/forms/src/lib/modules/checkbox/checkbox-label.component.ts
  libs/components/forms/src/lib/modules/checkbox/checkbox.component.html
  libs/components/forms/src/lib/modules/checkbox/checkbox.component.spec.ts
  libs/components/forms/src/lib/modules/checkbox/checkbox.component.ts
  libs/components/forms/src/lib/modules/checkbox/checkbox.module.ts
  libs/components/forms/src/lib/modules/radio/radio-group.component.html
  libs/components/forms/src/lib/modules/radio/radio-group.component.spec.ts
  libs/components/forms/src/lib/modules/radio/radio-group.component.ts
  libs/components/forms/testing/src/checkbox/checkbox-harness.spec.ts
  libs/components/forms/testing/src/checkbox/checkbox-harness.ts
  libs/components/forms/testing/src/checkbox/checkbox-label-text-label.harness.ts
  libs/components/forms/testing/src/checkbox/fixtures/checkbox-harness-test.component.html
  libs/components/forms/testing/src/checkbox/fixtures/checkbox-harness-test.component.ts
  libs/components/lists/src/lib/modules/repeater/repeater.component.spec.ts
Labels: risk level (author): 2

#2065 feat(components/modals): add modal form errors code example
  apps/code-examples/src/app/code-examples/modals/modal-with-error/context.ts
  apps/code-examples/src/app/code-examples/modals/modal-with-error/data.service.ts
  apps/code-examples/src/app/code-examples/modals/modal-with-error/data.ts
  apps/code-examples/src/app/code-examples/modals/modal-with-error/demo.component.html
  apps/code-examples/src/app/code-examples/modals/modal-with-error/demo.component.spec.ts
  apps/code-examples/src/app/code-examples/modals/modal-with-error/demo.component.ts
  apps/code-examples/src/app/code-examples/modals/modal-with-error/modal.component.html
  apps/code-examples/src/app/code-examples/modals/modal-with-error/modal.component.ts
  apps/code-examples/src/app/features/modals.module.ts
  apps/code-examples/src/app/home/home.component.html
Labels: risk level (author): 1

#2035 feat(components/ag-grid)!: enable text selection for data grids
  apps/playground/src/app/components/ag-grid/edit-complex-cells/edit-complex-cells.component.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/ag-grid-wrapper.component.spec.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/ag-grid-wrapper.component.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/ag-grid.service.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/fixtures/ag-grid.component.fixture.ts
  libs/components/ag-grid/src/lib/styles/_base.scss
Labels: risk level (author): 2

#2059 feat(components/forms): add labelText to single file attachment
  apps/e2e/forms-storybook/src/app/single-file-attachment/single-file-attachment.component.html
  apps/playground/src/app/components/forms/single-file-attachment/single-file-attachment.component.html
  libs/components/forms/src/lib/modules/file-attachment/file-attachment-label.component.ts
  libs/components/forms/src/lib/modules/file-attachment/file-attachment.component.html
  libs/components/forms/src/lib/modules/file-attachment/file-attachment.component.scss
  libs/components/forms/src/lib/modules/file-attachment/file-attachment.component.spec.ts
  libs/components/forms/src/lib/modules/file-attachment/file-attachment.component.ts
  libs/components/forms/src/lib/modules/file-attachment/fixtures/file-attachment.component.fixture.html
  libs/components/forms/src/lib/modules/file-attachment/fixtures/file-attachment.component.fixture.ts
Labels: risk level (author): 2

#2072 feat(components/forms): add labelText to single file attachment (#2059)
  apps/e2e/forms-storybook/src/app/single-file-attachment/single-file-attachment.component.html
  apps/playground/src/app/components/forms/single-file-attachment/single-file-attachment.component.html
  libs/components/forms/src/lib/modules/file-attachment/file-attachment-label.component.ts
  libs/components/forms/src/lib/modules/file-attachment/file-attachment.component.html
  libs/components/forms/src/lib/modules/file-attachment/file-attachment.component.scss
  libs/components/forms/src/lib/modules/file-attachment/file-attachment.component.spec.ts
  libs/components/forms/src/lib/modules/file-attachment/file-attachment.component.ts
  libs/components/forms/src/lib/modules/file-attachment/fixtures/file-attachment.component.fixture.html
  libs/components/forms/src/lib/modules/file-attachment/fixtures/file-attachment.component.fixture.ts
Labels: risk level (author): 2

#2069 fix(components/indicators): address icon metadata issues
  libs/components/theme/package.json
  libs/components/theme/src/lib/styles/sky.scss
  package-lock.json
  package.json
Labels: risk level (author): 1

#2067 chore: release 9.27.0 (#2045)
  CHANGELOG.md
Labels: risk level (author): 1, risk level (reviewer): 1

#2038 feat(components/http): provide svcid to auth-client
  libs/components/http/package.json
  libs/components/http/src/lib/modules/auth-http-client/auth-token-provider.spec.ts
  libs/components/http/src/lib/modules/auth-http-client/auth-token-provider.ts
  package-lock.json
  package.json
Labels: risk level (author): 1

#2066 feat(components/modals): add modal form errors code example (#2065)
  apps/code-examples/src/app/code-examples/modals/modal-with-error/context.ts
  apps/code-examples/src/app/code-examples/modals/modal-with-error/data.service.ts
  apps/code-examples/src/app/code-examples/modals/modal-with-error/data.ts
  apps/code-examples/src/app/code-examples/modals/modal-with-error/demo.component.html
  apps/code-examples/src/app/code-examples/modals/modal-with-error/demo.component.spec.ts
  apps/code-examples/src/app/code-examples/modals/modal-with-error/demo.component.ts
  apps/code-examples/src/app/code-examples/modals/modal-with-error/modal.component.html
  apps/code-examples/src/app/code-examples/modals/modal-with-error/modal.component.ts
  apps/code-examples/src/app/features/modals.module.ts
  apps/code-examples/src/app/home/home.component.html
Labels: risk level (author): 1

#2073 fix(components/indicators): address icon metadata issues (#2069)
  libs/components/theme/package.json
  libs/components/theme/src/lib/styles/sky.scss
  package-lock.json
  package.json
Labels: risk level (author): 1

#2070 fix(components/ag-grid): additional AG Grid schematic changes
  libs/components/packages/src/schematics/migrations/migration-collection.json
  libs/components/packages/src/schematics/migrations/update-10/ag-grid/__snapshots__/ag-grid.schematic.spec.ts.snap
  libs/components/packages/src/schematics/migrations/update-10/ag-grid/ag-grid.schematic.spec.ts
  libs/components/packages/src/schematics/migrations/update-10/ag-grid/ag-grid.schematic.ts
Labels: risk level (author): 1

#2060 feat(components/colorpicker): add focus trap to colorpicker
  libs/components/colorpicker/package.json
  libs/components/colorpicker/src/lib/modules/colorpicker/colorpicker.component.html
  libs/components/colorpicker/src/lib/modules/colorpicker/colorpicker.component.spec.ts
  libs/components/colorpicker/src/lib/modules/colorpicker/colorpicker.component.ts
  libs/components/colorpicker/src/lib/modules/colorpicker/colorpicker.module.ts
  libs/components/core/src/lib/modules/overlay/overlay-adapter.service.ts
  libs/components/core/src/lib/modules/overlay/overlay-config.ts
  libs/components/core/src/lib/modules/overlay/overlay.component.ts
  libs/components/core/src/lib/modules/overlay/overlay.service.spec.ts
Labels: risk level (author): 3

#2075 feat(components/colorpicker): add focus trap to colorpicker (#2060)
  libs/components/colorpicker/package.json
  libs/components/colorpicker/src/lib/modules/colorpicker/colorpicker.component.html
  libs/components/colorpicker/src/lib/modules/colorpicker/colorpicker.component.spec.ts
  libs/components/colorpicker/src/lib/modules/colorpicker/colorpicker.component.ts
  libs/components/colorpicker/src/lib/modules/colorpicker/colorpicker.module.ts
  libs/components/core/src/lib/modules/overlay/overlay-adapter.service.ts
  libs/components/core/src/lib/modules/overlay/overlay-config.ts
  libs/components/core/src/lib/modules/overlay/overlay.component.ts
  libs/components/core/src/lib/modules/overlay/overlay.service.spec.ts
Labels: risk level (author): 3

#2051 feat(components/datetime): improve screen reader labels for values on datepicker calendar
  libs/components/datetime/src/lib/modules/datepicker/datepicker-calendar-inner.component.ts
  libs/components/datetime/src/lib/modules/datepicker/datepicker-calendar-label.pipe.spec.ts
  libs/components/datetime/src/lib/modules/datepicker/datepicker-calendar-label.pipe.ts
  libs/components/datetime/src/lib/modules/datepicker/datepicker.module.ts
  libs/components/datetime/src/lib/modules/datepicker/daypicker-button.component.html
  libs/components/datetime/src/lib/modules/datepicker/daypicker-cell.component.spec.ts
  libs/components/datetime/src/lib/modules/datepicker/daypicker.component.ts
  libs/components/datetime/src/lib/modules/datepicker/monthpicker.component.html
  libs/components/datetime/src/lib/modules/datepicker/monthpicker.component.ts
  libs/components/datetime/src/lib/modules/datepicker/yearpicker.component.html
  libs/components/datetime/src/lib/modules/datepicker/yearpicker.component.ts
Labels: risk level (author): 1

#2076 feat(components/datetime): improve screen reader labels for values on datepicker calendar (#2051)
  libs/components/datetime/src/lib/modules/datepicker/datepicker-calendar-inner.component.ts
  libs/components/datetime/src/lib/modules/datepicker/datepicker-calendar-label.pipe.spec.ts
  libs/components/datetime/src/lib/modules/datepicker/datepicker-calendar-label.pipe.ts
  libs/components/datetime/src/lib/modules/datepicker/datepicker.module.ts
  libs/components/datetime/src/lib/modules/datepicker/daypicker-button.component.html
  libs/components/datetime/src/lib/modules/datepicker/daypicker-cell.component.spec.ts
  libs/components/datetime/src/lib/modules/datepicker/daypicker.component.ts
  libs/components/datetime/src/lib/modules/datepicker/monthpicker.component.html
  libs/components/datetime/src/lib/modules/datepicker/monthpicker.component.ts
  libs/components/datetime/src/lib/modules/datepicker/yearpicker.component.html
  libs/components/datetime/src/lib/modules/datepicker/yearpicker.component.ts
Labels: risk level (author): 1
