Repository blackbaud/skyux, pull requests merged in 2024-06, with the labels that each got.

#2341 fix(components/popovers): allow taller dropdowns in small viewports
  apps/playground/src/app/components/popovers/dropdown/dropdown-example.component.html
  apps/playground/src/app/components/popovers/dropdown/dropdown-example.component.ts
  apps/playground/src/app/components/popovers/dropdown/dropdown-routing.module.ts
  apps/playground/src/app/components/popovers/dropdown/dropdown.component.html
  apps/playground/src/app/components/popovers/dropdown/dropdown.component.ts
  apps/playground/src/app/components/popovers/dropdown/dropdown.module.ts
  apps/playground/src/app/components/popovers/popovers.module.ts
  libs/components/popovers/src/lib/styles/_mixins.scss
Labels: risk level (author): 2

#2332 chore: release 10.22.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#2343 feat(components/phone-field): update phone field code example
  apps/code-examples/src/app/code-examples/phone-field/phone-field/basic/demo.component.html
  apps/code-examples/src/app/code-examples/phone-field/phone-field/basic/demo.component.ts
Labels: risk level (author): 1

#2342 feat(components/datetime): update timepicker code example
  apps/code-examples/src/app/code-examples/datetime/timepicker/basic/demo.component.html
  apps/code-examples/src/app/code-examples/datetime/timepicker/basic/demo.component.ts
  apps/code-examples/src/app/code-examples/forms/field-group/basic/demo.component.html
  apps/code-examples/src/app/code-examples/forms/field-group/basic/demo.component.ts
  apps/code-examples/src/app/code-examples/forms/toggle-switch/basic/demo.component.html
  apps/code-examples/src/app/code-examples/forms/toggle-switch/basic/demo.component.ts
  apps/code-examples/src/app/code-examples/lookup/country-field/basic/demo.component.html
  apps/code-examples/src/app/code-examples/lookup/country-field/basic/demo.component.ts
Labels: risk level (author): 1

#2344 feat(components/forms): make `headingLevel` optional for checkbox and radio group components
  apps/e2e/forms-storybook/src/app/checkbox/checkbox.component.html
  apps/e2e/forms-storybook/src/app/radio-button/radio-button.component.html
  libs/components/forms/src/lib/modules/checkbox/checkbox-group.component.html
  libs/components/forms/src/lib/modules/checkbox/checkbox-group.component.spec.ts
  libs/components/forms/src/lib/modules/checkbox/checkbox-group.component.ts
  libs/components/forms/src/lib/modules/checkbox/fixtures/standard-checkbox-group.component.ts
  libs/components/forms/src/lib/modules/radio/fixtures/radio-group-reactive.component.fixture.ts
  libs/components/forms/src/lib/modules/radio/radio-group.component.html
  libs/components/forms/src/lib/modules/radio/radio-group.component.scss
  libs/components/forms/src/lib/modules/radio/radio-group.component.spec.ts
  libs/components/forms/src/lib/modules/radio/radio-group.component.ts
  libs/components/forms/testing/src/checkbox/checkbox-group-harness.spec.ts
  libs/components/forms/testing/src/checkbox/checkbox-group-harness.ts
  libs/components/forms/testing/src/checkbox/fixtures/checkbox-harness-test.component.html
  libs/components/forms/testing/src/checkbox/fixtures/checkbox-harness-test.component.ts
Labels: risk level (author): 2

#2346 chore: release 10.23.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#2350 fix(components/text-editor): support transparency on text background color
  libs/components/text-editor/src/lib/modules/text-editor/text-editor.component.spec.ts
  libs/components/text-editor/src/lib/modules/text-editor/toolbar/text-editor-toolbar.component.ts
Labels: risk level (author): 1

#2349 feat(components/datetime): update datepicker code examples
  apps/code-examples/src/app/code-examples/datetime/datepicker/basic/demo.component.html
  apps/code-examples/src/app/code-examples/datetime/datepicker/basic/demo.component.ts
  apps/code-examples/src/app/code-examples/datetime/datepicker/custom-dates/demo.component.html
  apps/code-examples/src/app/code-examples/datetime/datepicker/custom-dates/demo.component.ts
  apps/code-examples/src/app/code-examples/datetime/datepicker/fuzzy/demo.component.html
  apps/code-examples/src/app/code-examples/datetime/datepicker/fuzzy/demo.component.ts
Labels: risk level (author): 1

#2345 feat(components/lookup): update lookup code examples
  apps/code-examples/src/app/code-examples/lookup/lookup/add-item/add-item-modal.component.html
  apps/code-examples/src/app/code-examples/lookup/lookup/add-item/demo.component.html
  apps/code-examples/src/app/code-examples/lookup/lookup/add-item/demo.component.scss
  apps/code-examples/src/app/code-examples/lookup/lookup/add-item/demo.component.ts
  apps/code-examples/src/app/code-examples/lookup/lookup/async/demo.component.html
  apps/code-examples/src/app/code-examples/lookup/lookup/async/demo.component.scss
  apps/code-examples/src/app/code-examples/lookup/lookup/async/demo.component.ts
  apps/code-examples/src/app/code-examples/lookup/lookup/custom-picker/demo.component.html
  apps/code-examples/src/app/code-examples/lookup/lookup/custom-picker/demo.component.scss
  apps/code-examples/src/app/code-examples/lookup/lookup/custom-picker/demo.component.ts
  apps/code-examples/src/app/code-examples/lookup/lookup/multi-select/demo.component.html
  apps/code-examples/src/app/code-examples/lookup/lookup/multi-select/demo.component.scss
  apps/code-examples/src/app/code-examples/lookup/lookup/multi-select/demo.component.ts
  apps/code-examples/src/app/code-examples/lookup/lookup/result-templates/demo.component.html
  apps/code-examples/src/app/code-examples/lookup/lookup/result-templates/demo.component.scss
  apps/code-examples/src/app/code-examples/lookup/lookup/result-templates/demo.component.ts
  apps/code-examples/src/app/code-examples/lookup/lookup/single-select/demo.component.html
  apps/code-examples/src/app/code-examples/lookup/lookup/single-select/demo.component.scss
  apps/code-examples/src/app/code-examples/lookup/lookup/single-select/demo.component.ts
  apps/code-examples/src/app/code-examples/lookup/selection-modal/add-item/add-item-modal.component.html
Labels: risk level (author): 1

#2348 fix(components/ag-grid): disable row selection checkbox
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-renderers/cell-renderer-row-selector/cell-renderer-row-selector.component.html
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-renderers/cell-renderer-row-selector/cell-renderer-row-selector.component.spec.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-renderers/cell-renderer-row-selector/cell-renderer-row-selector.component.ts
Labels: risk level (author): 1

#2351 fix(components/ag-grid): data manager should capture when sort is removed
  libs/components/ag-grid/src/lib/modules/ag-grid/ag-grid-data-manager-adapter.directive.spec.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/ag-grid-data-manager-adapter.directive.ts
Labels: risk level (author): 1

#2352 chore: release 10.24.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#2358 fix(components/ag-grid): row delete confirmation should still show when first column is hidden
  libs/components/ag-grid/src/lib/modules/ag-grid/ag-grid-row-delete.directive.spec.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/ag-grid-row-delete.directive.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/fixtures/ag-grid-row-delete.component.fixture.ts
Labels: risk level (author): 1

#2359 chore: remove novalidate from code example forms
  apps/code-examples/src/app/code-examples/angular-tree-component/angular-tree/advanced/demo.component.html
  apps/code-examples/src/app/code-examples/autonumeric/autonumeric/currency/demo.component.html
  apps/code-examples/src/app/code-examples/autonumeric/autonumeric/international-formatting/demo.component.html
  apps/code-examples/src/app/code-examples/autonumeric/autonumeric/options-provider/demo.component.html
  apps/code-examples/src/app/code-examples/autonumeric/autonumeric/preset/demo.component.html
  apps/code-examples/src/app/code-examples/colorpicker/colorpicker/basic/demo.component.html
  apps/code-examples/src/app/code-examples/colorpicker/colorpicker/programmatic/demo.component.html
  apps/code-examples/src/app/code-examples/datetime/date-range-picker/basic/demo.component.html
  apps/code-examples/src/app/code-examples/datetime/date-range-picker/custom-calculator/demo.component.html
  apps/code-examples/src/app/code-examples/datetime/datepicker/fuzzy/demo.component.html
  apps/code-examples/src/app/code-examples/datetime/timepicker/basic/demo.component.html
  apps/code-examples/src/app/code-examples/forms/character-count/demo.component.html
  apps/code-examples/src/app/code-examples/forms/radio/icon/demo.component.html
  apps/code-examples/src/app/code-examples/forms/radio/standard/demo.component.html
  apps/code-examples/src/app/code-examples/forms/single-file-attachment/basic/demo.component.html
  apps/code-examples/src/app/code-examples/text-editor/text-editor/demo.component.html
Labels: risk level (author): 1

#2360 feat(components/forms): update radio button code examples
  apps/code-examples/src/app/code-examples/forms/radio/icon/demo.component.html
  apps/code-examples/src/app/code-examples/forms/radio/inline-help/demo.component.html
  apps/code-examples/src/app/code-examples/forms/radio/inline-help/demo.component.ts
  apps/code-examples/src/app/code-examples/forms/radio/standard/demo.component.html
  apps/code-examples/src/app/code-examples/forms/radio/standard/demo.component.ts
  apps/code-examples/src/app/features/forms.module.ts
  apps/code-examples/src/app/home/home.component.html
Labels: risk level (author): 1

#2355 chore: release 10.25.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#2356 fix(components/popovers): support popover in horizontal scrolling elements
  apps/e2e/core-storybook-e2e/src/e2e/affix.component.cy.ts
  apps/e2e/core-storybook/src/app/affix/affix.component.html
  apps/e2e/core-storybook/src/app/affix/affix.component.scss
  apps/e2e/core-storybook/src/app/affix/affix.component.stories.ts
  apps/e2e/core-storybook/src/app/affix/affix.component.ts
  apps/playground/src/app/components/core/affix/affix-routing.module.ts
  apps/playground/src/app/components/core/affix/affix.component.css
  apps/playground/src/app/components/core/affix/affix.component.html
  apps/playground/src/app/components/core/affix/affix.component.spec.ts
  apps/playground/src/app/components/core/affix/affix.component.ts
  apps/playground/src/app/components/core/affix/affix.module.ts
  apps/playground/src/app/components/core/core.module.ts
  libs/components/core/src/lib/modules/affix/dom-utils.ts
Labels: risk level (author): 1

#2365 fix(components/datetime): adjust date range picker component vertical spacing in responsive containers
  libs/components/datetime/src/lib/modules/date-range-picker/date-range-picker.component.scss
Labels: risk level (author): 1

#2367 feat(components/forms): update checkbox code examples
  apps/code-examples/src/app/code-examples/forms/checkbox/basic/demo.component.html
  apps/code-examples/src/app/code-examples/forms/checkbox/basic/demo.component.ts
  apps/code-examples/src/app/code-examples/forms/checkbox/icon-group/demo.component.html
  apps/code-examples/src/app/code-examples/forms/checkbox/inline-help/demo.component.html
  apps/code-examples/src/app/code-examples/forms/checkbox/inline-help/demo.component.ts
  apps/code-examples/src/app/features/forms.module.ts
  apps/code-examples/src/app/home/home.component.html
Labels: risk level (author): 1

#2368 feat(components/forms): automatically add required validator to checkbox group
  apps/playground/src/app/components/forms/checkbox/checkbox.component.html
  apps/playground/src/app/components/forms/checkbox/checkbox.component.ts
  libs/components/forms/src/lib/modules/checkbox/checkbox-group.component.html
  libs/components/forms/src/lib/modules/checkbox/checkbox-group.component.spec.ts
  libs/components/forms/src/lib/modules/checkbox/checkbox-group.component.ts
  libs/components/forms/src/lib/modules/checkbox/fixtures/standard-checkbox-group.component.ts
  libs/components/forms/src/lib/modules/checkbox/fixtures/template-driven-checkbox-group.component.ts
Labels: risk level (author): 3

#2362 chore: release 10.26.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#2371 ci: add help-inline as a valid scope
  .github/workflows/validate-pr.yml
Labels: risk level (author): 1

#2372 fix(components/help-inline): add `@skyux/help-inline` to the `ng update` group
  libs/components/packages/package.json
Labels: risk level (author): 1

#2366 feat(components/forms): automatically add required validator to checkbox group
  apps/e2e/forms-storybook/src/app/checkbox/checkbox.component.html
  apps/e2e/forms-storybook/src/app/checkbox/checkbox.component.ts
  apps/playground/src/app/components/forms/checkbox/checkbox.component.html
  apps/playground/src/app/components/forms/checkbox/checkbox.component.ts
  libs/components/forms/src/lib/modules/checkbox/checkbox-group.component.html
  libs/components/forms/src/lib/modules/checkbox/checkbox-group.component.spec.ts
  libs/components/forms/src/lib/modules/checkbox/checkbox-group.component.ts
  libs/components/forms/src/lib/modules/checkbox/fixtures/standard-checkbox-group.component.html
  libs/components/forms/src/lib/modules/checkbox/fixtures/standard-checkbox-group.component.ts
  libs/components/forms/src/lib/modules/checkbox/fixtures/template-driven-checkbox-group.component.ts
  libs/components/forms/testing/src/checkbox/checkbox-group-harness.spec.ts
  libs/components/forms/testing/src/checkbox/checkbox-group-harness.ts
  libs/components/forms/testing/src/checkbox/fixtures/checkbox-harness-test.component.html
  libs/components/forms/testing/src/checkbox/fixtures/checkbox-harness-test.component.ts
Labels: risk level (author): 2

#2373 chore: release 10.27.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#2364 feat(components/forms): update input box code examples
  apps/code-examples/src/app/code-examples/forms/input-box/basic/demo.component.html
  apps/code-examples/src/app/code-examples/forms/input-box/basic/demo.component.spec.ts
  apps/code-examples/src/app/code-examples/forms/input-box/inline-help/demo.component.html
  apps/code-examples/src/app/code-examples/forms/input-box/inline-help/demo.component.ts
  apps/code-examples/src/app/features/forms.module.ts
  apps/code-examples/src/app/home/home.component.html
Labels: risk level (author): 1

#2376 chore: release 10.28.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#2380 feat(components/theme): add new-tab icon
  libs/components/packages/package.json
  libs/components/theme/package.json
  libs/components/theme/src/lib/styles/sky.scss
  package-lock.json
  package.json
Labels: risk level (author): 1

#2375 fix(components/packages): update package group name to `@skyux/packages`
  libs/components/packages/package.json
  libs/components/packages/project.json
  libs/sdk/eslint-config/package.json
  libs/sdk/prettier-schematics/package.json
  scripts/postbuild-packages.ts
Labels: risk level (author): 1

#2374 feat(components/colorpicker): add `hintText`, `helpKey`, `labelHidden`, and `stacked` inputs to colorpicker
  apps/e2e/colorpicker-storybook-e2e/src/e2e/colorpicker.component.cy.ts
  apps/e2e/colorpicker-storybook/src/app/colorpicker/colorpicker.component.html
  apps/e2e/colorpicker-storybook/src/app/colorpicker/colorpicker.component.ts
  apps/playground/src/app/components/colorpicker/colorpicker/colorpicker.component.html
  libs/components/colorpicker/src/lib/modules/colorpicker/colorpicker.component.html
  libs/components/colorpicker/src/lib/modules/colorpicker/colorpicker.component.scss
  libs/components/colorpicker/src/lib/modules/colorpicker/colorpicker.component.spec.ts
  libs/components/colorpicker/src/lib/modules/colorpicker/colorpicker.component.ts
  libs/components/colorpicker/src/lib/modules/colorpicker/colorpicker.module.ts
  libs/components/colorpicker/src/lib/modules/colorpicker/fixtures/colorpicker-component.fixture.html
  libs/components/colorpicker/src/lib/modules/colorpicker/fixtures/colorpicker-component.fixture.ts
  libs/components/colorpicker/src/lib/modules/colorpicker/fixtures/colorpicker-fixtures.module.ts
Labels: risk level (author): 2

#2382 feat(components/colorpicker): update colorpicker code examples
  apps/code-examples/src/app/code-examples/colorpicker/colorpicker/basic/demo.component.html
  apps/code-examples/src/app/code-examples/colorpicker/colorpicker/programmatic/demo.component.html
  apps/code-examples/src/app/code-examples/colorpicker/colorpicker/programmatic/demo.component.ts
Labels: risk level (author): 1

#2379 feat(components/angular-tree-component): add help key and inline help to tree nodes
  apps/code-examples/src/app/code-examples/angular-tree-component/angular-tree/advanced/demo.component.html
  apps/code-examples/src/app/code-examples/angular-tree-component/angular-tree/advanced/demo.component.ts
  apps/code-examples/src/app/code-examples/angular-tree-component/angular-tree/advanced/node.ts
  apps/code-examples/src/app/code-examples/angular-tree-component/angular-tree/basic/demo.component.html
  apps/code-examples/src/app/code-examples/angular-tree-component/angular-tree/basic/demo.component.ts
  apps/code-examples/src/app/features/angular-tree.modules.ts
  apps/code-examples/src/app/home/home.component.html
  apps/e2e/angular-tree-component-storybook/src/app/angular-tree-component/angular-tree-component.component.html
  libs/components/angular-tree-component/package.json
  libs/components/angular-tree-component/src/lib/modules/angular-tree/angular-tree-node.component.html
  libs/components/angular-tree-component/src/lib/modules/angular-tree/angular-tree-node.component.ts
  libs/components/angular-tree-component/src/lib/modules/angular-tree/angular-tree-root.component.spec.ts
  libs/components/angular-tree-component/src/lib/modules/angular-tree/angular-tree.module.ts
  libs/components/angular-tree-component/src/lib/modules/angular-tree/fixtures/tree-view.fixture.component.html
Labels: risk level (author): 2

#2381 chore: release 10.29.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#2385 feat(components/forms): update helpKey docs
  libs/components/angular-tree-component/src/lib/modules/angular-tree/angular-tree-node.component.ts
  libs/components/colorpicker/src/lib/modules/colorpicker/colorpicker.component.ts
  libs/components/datetime/src/lib/modules/date-range-picker/date-range-picker.component.ts
  libs/components/forms/src/lib/modules/checkbox/checkbox-group.component.ts
  libs/components/forms/src/lib/modules/checkbox/checkbox.component.ts
  libs/components/forms/src/lib/modules/field-group/field-group.component.ts
  libs/components/forms/src/lib/modules/file-attachment/file-attachment.component.ts
  libs/components/forms/src/lib/modules/file-attachment/file-drop.component.ts
  libs/components/forms/src/lib/modules/input-box/input-box.component.ts
  libs/components/forms/src/lib/modules/radio/radio-group.component.ts
  libs/components/forms/src/lib/modules/radio/radio.component.ts
  libs/components/forms/src/lib/modules/toggle-switch/toggle-switch.component.ts
  libs/components/text-editor/src/lib/modules/text-editor/text-editor.component.ts
Labels: risk level (author): 1

#2386 chore: release 10.30.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#2388 fix(components/core): adjust viewkeeper element size when parent element's size changes
  apps/playground/src/app/components/core/viewkeeper/viewkeeper.component.html
  apps/playground/src/app/components/core/viewkeeper/viewkeeper.component.scss
  apps/playground/src/app/components/core/viewkeeper/viewkeeper.component.ts
  libs/components/core/src/lib/modules/resize-observer/fixtures/resize-observer-mock.ts
  libs/components/core/src/lib/modules/resize-observer/resize-observer-media-query.service.spec.ts
  libs/components/core/src/lib/modules/resize-observer/resize-observer.service.spec.ts
  libs/components/core/src/lib/modules/viewkeeper/viewkeeper.spec.ts
  libs/components/core/src/lib/modules/viewkeeper/viewkeeper.ts
  package-lock.json
Labels: risk level (author): 2

#2387 fix(components/theme): update icon metadata
  libs/components/packages/package.json
  libs/components/theme/package.json
  libs/components/theme/src/lib/styles/sky.scss
  package-lock.json
  package.json
Labels: risk level (author): 1

#2391 chore: update to NX 19
  .eslintrc.json
  .gitignore
  .prettierignore
  libs/components/storybook/package.json
  libs/sdk/e2e-schematics/package.json
  libs/sdk/e2e-schematics/src/generators/component-e2e/index.spec.ts
  libs/sdk/e2e-schematics/src/generators/component-e2e/index.ts
  libs/sdk/e2e-schematics/src/generators/configure-percy/index.spec.ts
  libs/sdk/e2e-schematics/src/generators/configure-storybook/index.spec.ts
  libs/sdk/e2e-schematics/src/generators/story/index.spec.ts
  libs/sdk/e2e-schematics/src/generators/storybook-composition/index.spec.ts
  libs/sdk/e2e-schematics/src/generators/switch-to-variations/generator.spec.ts
  libs/sdk/e2e-schematics/src/utils/__snapshots__/find-module.spec.ts.snap
  libs/sdk/e2e-schematics/src/utils/angular-module-generator.spec.ts
  libs/sdk/e2e-schematics/src/utils/ast-utils.spec.ts
  libs/sdk/e2e-schematics/src/utils/find-module.spec.ts
  libs/sdk/e2e-schematics/src/utils/get-projects.spec.ts
  libs/sdk/e2e-schematics/src/utils/testing.ts
  libs/sdk/tools/package.json
  libs/sdk/tools/src/generators/configure-test-ci/generator.spec.ts
  libs/sdk/tools/src/generators/update-dependencies/generator.spec.ts
  package-lock.json
  package.json
Labels: risk level (author): 1

#2389 chore: release 10.30.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#2390 feat(components/tiles): add help key and inline help to the tile component
  apps/code-examples/src/app/code-examples/tiles/tiles/basic/tile1.component.html
  apps/code-examples/src/app/code-examples/tiles/tiles/basic/tile2.component.html
  apps/code-examples/src/app/code-examples/tiles/tiles/inline-help/demo.component.html
  apps/code-examples/src/app/code-examples/tiles/tiles/inline-help/demo.component.ts
  apps/code-examples/src/app/code-examples/tiles/tiles/inline-help/tile1.component.html
  apps/code-examples/src/app/code-examples/tiles/tiles/inline-help/tile1.component.ts
  apps/code-examples/src/app/features/tiles.module.ts
  apps/code-examples/src/app/home/home.component.html
  apps/e2e/tiles-storybook/src/app/tile-dashboard/tile-dashboard.component.ts
  apps/e2e/tiles-storybook/src/app/tile-dashboard/tile3/tile3.component.ts
  apps/playground/src/app/components/tiles/tile-dashboard/tile-dashboard.component.ts
  apps/playground/src/app/components/tiles/tile-dashboard/tile1.component.html
  apps/playground/src/app/components/tiles/tile-dashboard/tile2.component.html
  apps/playground/src/app/components/tiles/tile-dashboard/tile2.component.ts
  apps/playground/src/app/components/tiles/tile-dashboard/tile3.component.ts
  libs/components/tiles/package.json
  libs/components/tiles/src/lib/modules/tiles/tile/fixtures/tile.component.fixture.html
  libs/components/tiles/src/lib/modules/tiles/tile/fixtures/tile.component.fixture.ts
  libs/components/tiles/src/lib/modules/tiles/tile/tile-title.component.scss
  libs/components/tiles/src/lib/modules/tiles/tile/tile.component.html
  libs/components/tiles/src/lib/modules/tiles/tile/tile.component.scss
  libs/components/tiles/src/lib/modules/tiles/tile/tile.component.spec.ts
  libs/components/tiles/src/lib/modules/tiles/tile/tile.component.ts
Labels: risk level (author): 2

#2395 fix(components/colorpicker): colorpicker shows appropriate error styles and required indicator
  apps/e2e/colorpicker-storybook-e2e/src/e2e/colorpicker.component.cy.ts
  apps/e2e/colorpicker-storybook/src/app/colorpicker/colorpicker.component.html
  apps/e2e/colorpicker-storybook/src/app/colorpicker/colorpicker.component.ts
  apps/playground/src/app/components/colorpicker/colorpicker/colorpicker.component.html
  apps/playground/src/app/components/colorpicker/colorpicker/colorpicker.component.ts
  libs/components/colorpicker/src/lib/modules/colorpicker/colorpicker-input.directive.ts
  libs/components/colorpicker/src/lib/modules/colorpicker/colorpicker.component.html
  libs/components/colorpicker/src/lib/modules/colorpicker/colorpicker.component.scss
  libs/components/colorpicker/src/lib/modules/colorpicker/colorpicker.component.spec.ts
  libs/components/colorpicker/src/lib/modules/colorpicker/colorpicker.component.ts
  libs/components/colorpicker/src/lib/modules/colorpicker/fixtures/colorpicker-component.fixture.html
  libs/components/colorpicker/src/lib/modules/colorpicker/fixtures/colorpicker-component.fixture.ts
  libs/components/colorpicker/src/lib/modules/colorpicker/fixtures/colorpicker-reactive-component.fixture.ts
Labels: risk level (author): 2

#2393 fix(components/datetime): date range picker elements horizontal spacing rules applied to responsive containers
  libs/components/datetime/src/lib/modules/date-range-picker/date-range-picker.component.scss
Labels: risk level (author): 1

#2392 chore: release 10.31.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#2397 fix(components/indicators): re-add lambda component exports for legacy icons
  libs/components/indicators/src/index.ts
Labels: risk level (author): 2

#2398 chore: release 10.31.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#2396 ci: skip publishing dependency graph
  .github/workflows/ci.yml
  .github/workflows/e2e.yml
Labels: risk level (author): 1, skip e2e

#2399 fix(components/help-inline): implement `@skyux/icon` instead of FontAwesome
  libs/components/help-inline/ng-package.json
  libs/components/help-inline/package.json
  libs/components/help-inline/src/lib/modules/help-inline/help-inline.component.html
  libs/components/help-inline/src/lib/modules/help-inline/help-inline.component.scss
  libs/components/help-inline/src/lib/modules/help-inline/help-inline.component.spec.ts
  libs/components/help-inline/src/lib/modules/help-inline/help-inline.component.ts
Labels: risk level (author): 3

#2268 feat(components/progress-indicator): add help inline to progress indicator component
  apps/code-examples/src/app/code-examples/progress-indicator/passive-indicator/basic/demo.component.html
  apps/code-examples/src/app/code-examples/progress-indicator/passive-indicator/inline-help/demo.component.html
  apps/code-examples/src/app/code-examples/progress-indicator/passive-indicator/inline-help/demo.component.ts
  apps/code-examples/src/app/code-examples/progress-indicator/waterfall-indicator/basic/demo.component.html
  apps/code-examples/src/app/code-examples/progress-indicator/waterfall-indicator/inline-help/demo.component.html
  apps/code-examples/src/app/code-examples/progress-indicator/waterfall-indicator/inline-help/demo.component.ts
  apps/code-examples/src/app/code-examples/progress-indicator/waterfall-indicator/inline-help/modal-context.ts
  apps/code-examples/src/app/code-examples/progress-indicator/waterfall-indicator/inline-help/modal.component.html
  apps/code-examples/src/app/code-examples/progress-indicator/waterfall-indicator/inline-help/modal.component.ts
  apps/code-examples/src/app/features/progress-indicator.module.ts
  apps/code-examples/src/app/home/home.component.html
  apps/e2e/progress-indicator-storybook/src/app/progress-indicator/progress-indicator.component.html
  libs/components/progress-indicator/package.json
  libs/components/progress-indicator/src/lib/modules/progress-indicator/fixtures/progress-indicator.component.fixture.html
  libs/components/progress-indicator/src/lib/modules/progress-indicator/fixtures/progress-indicator.component.fixture.ts
  libs/components/progress-indicator/src/lib/modules/progress-indicator/progress-indicator-item/progress-indicator-item.component.html
  libs/components/progress-indicator/src/lib/modules/progress-indicator/progress-indicator-item/progress-indicator-item.component.ts
  libs/components/progress-indicator/src/lib/modules/progress-indicator/progress-indicator.component.spec.ts
  libs/components/progress-indicator/src/lib/modules/progress-indicator/progress-indicator.module.ts
Labels: risk level (author): 2

#2403 ci: update e2e verification step
  .github/actions/e2e-affected/action.yml
  .github/workflows/e2e.yml
  libs/sdk/e2e-schematics/src/workflow/percy-api/percy-api.spec.ts
  libs/sdk/e2e-schematics/src/workflow/percy-api/percy-api.ts
  libs/sdk/e2e-schematics/src/workflow/verify-e2e/verify-e2e.spec.ts
  libs/sdk/e2e-schematics/src/workflow/verify-e2e/verify-e2e.ts
Labels: risk level (author): 1, skip e2e

#2404 fix(components/datetime): refine modal date range picker horizontal spacing
  apps/integration-e2e/src/e2e/modal-date-range-picker.cy.ts
  apps/integration/src/app/integrations/integrations.module.ts
  apps/integration/src/app/integrations/modal-date-range-picker/modal-date-range-picker-modal.component.html
  apps/integration/src/app/integrations/modal-date-range-picker/modal-date-range-picker-modal.component.ts
  apps/integration/src/app/integrations/modal-date-range-picker/modal-date-range-picker-routing.module.ts
  apps/integration/src/app/integrations/modal-date-range-picker/modal-date-range-picker.component.html
  apps/integration/src/app/integrations/modal-date-range-picker/modal-date-range-picker.component.ts
  apps/integration/src/app/integrations/modal-date-range-picker/modal-date-range-picker.module.ts
  libs/components/datetime/src/lib/modules/date-range-picker/date-range-picker.component.scss
Labels: risk level (author): 1

#2394 feat(components/indicators): add help-inline button inputs to status indicator
  apps/code-examples/src/app/code-examples/indicators/status-indicator/basic/demo.component.html
  apps/code-examples/src/app/code-examples/indicators/status-indicator/basic/demo.component.ts
  apps/e2e/indicators-storybook/src/app/status-indicator/status-indicator.component.html
  apps/e2e/modals-storybook/project.json
  apps/e2e/progress-indicator-storybook/project.json
  apps/e2e/toast-storybook/project.json
  apps/playground/src/app/components/indicators/status-indicator/status-indicator.component.html
  libs/components/forms/src/lib/modules/input-box/input-box.component.spec.ts
  libs/components/help-inline/src/lib/modules/help-inline/fixtures/help-inline.component.fixture.html
  libs/components/help-inline/src/lib/modules/help-inline/fixtures/help-inline.component.fixture.ts
  libs/components/help-inline/src/lib/modules/help-inline/help-inline.component.html
  libs/components/help-inline/src/lib/modules/help-inline/help-inline.component.spec.ts
  libs/components/help-inline/src/lib/modules/help-inline/help-inline.component.ts
  libs/components/help-inline/testing/src/help-inline/help-inline-harness.spec.ts
  libs/components/help-inline/testing/src/help-inline/help-inline-harness.ts
  libs/components/indicators/package.json
  libs/components/indicators/src/lib/modules/status-indicator/status-indicator.component.html
  libs/components/indicators/src/lib/modules/status-indicator/status-indicator.component.ts
  libs/components/indicators/src/lib/modules/status-indicator/status-indicator.module.ts
  libs/components/packages/src/schematics/migrations/migration-collection.json
  libs/components/packages/src/schematics/migrations/update-10/add-indicators-help-inline-peer-dependency/add-indicators-help-inline-peer-dependency.schematic.spec.ts
  libs/components/packages/src/schematics/migrations/update-10/add-indicators-help-inline-peer-dependency/add-indicators-help-inline-peer-dependency.schematic.ts
Labels: risk level (author): 1

#2409 build: update the `dev:format` command
  package.json
Labels: risk level (author): 1

#2407 fix(components/help-inline): help inline test content is appropriately styled
  libs/components/help-inline/src/lib/modules/help-inline/help-inline.component.html
  libs/components/help-inline/src/lib/modules/help-inline/help-inline.component.scss
Labels: risk level (author): 2

#2402 feat(components/modals): add `helpKey`, `helpPopoverContent`, and `helpPopoverTitle` inputs to the modal component
  apps/code-examples/src/app/code-examples/modals/modal/basic-with-controller/modal.component.ts
  apps/code-examples/src/app/code-examples/modals/modal/basic-with-harness/demo.component.spec.ts
  apps/code-examples/src/app/code-examples/modals/modal/basic-with-harness/modal.component.html
  apps/code-examples/src/app/code-examples/modals/modal/inline-help/context.ts
  apps/code-examples/src/app/code-examples/modals/modal/inline-help/data.service.ts
  apps/code-examples/src/app/code-examples/modals/modal/inline-help/data.ts
  apps/code-examples/src/app/code-examples/modals/modal/inline-help/demo.component.html
  apps/code-examples/src/app/code-examples/modals/modal/inline-help/demo.component.ts
  apps/code-examples/src/app/code-examples/modals/modal/inline-help/modal.component.html
  apps/code-examples/src/app/code-examples/modals/modal/inline-help/modal.component.ts
  apps/code-examples/src/app/code-examples/modals/modal/with-error/modal.component.html
  apps/code-examples/src/app/features/modals.module.ts
  apps/code-examples/src/app/home/home.component.html
  apps/e2e/modals-storybook-e2e/src/e2e/modal.component.cy.ts
  apps/e2e/modals-storybook/src/app/modal/modal.component.html
  apps/e2e/modals-storybook/src/app/modal/modal.component.ts
  apps/e2e/modals-storybook/src/app/modal/modals/modal-basic.component.html
  apps/e2e/modals-storybook/src/app/modal/modals/modal-basic.component.ts
  apps/e2e/modals-storybook/src/app/modal/modals/modal-context.ts
  libs/components/modals/package.json
  libs/components/modals/src/lib/modules/modal/fixtures/modal-context.ts
  libs/components/modals/src/lib/modules/modal/fixtures/modal.component.fixture.html
  libs/components/modals/src/lib/modules/modal/fixtures/modal.component.fixture.ts
  libs/components/modals/src/lib/modules/modal/modal-configuration.ts
  libs/components/modals/src/lib/modules/modal/modal-header.component.html
  libs/components/modals/src/lib/modules/modal/modal-host.service.ts
  libs/components/modals/src/lib/modules/modal/modal-instance.ts
  libs/components/modals/src/lib/modules/modal/modal.component.html
  libs/components/modals/src/lib/modules/modal/modal.component.scss
  libs/components/modals/src/lib/modules/modal/modal.component.spec.ts
  libs/components/modals/src/lib/modules/modal/modal.component.ts
  libs/components/modals/src/lib/modules/modal/modal.interface.ts
  libs/components/modals/testing/src/modal/modal-harness.spec.ts
  libs/components/modals/testing/src/modal/modal-harness.ts
Labels: risk level (author): 2

#2412 fix(components/help-inline): stop propagation of click events
  libs/components/help-inline/src/lib/modules/help-inline/fixtures/help-inline.component.fixture.html
  libs/components/help-inline/src/lib/modules/help-inline/fixtures/help-inline.component.fixture.ts
  libs/components/help-inline/src/lib/modules/help-inline/help-inline.component.html
  libs/components/help-inline/src/lib/modules/help-inline/help-inline.component.spec.ts
  libs/components/help-inline/src/lib/modules/help-inline/help-inline.component.ts
Labels: risk level (author): 2
