Repository blackbaud/skyux, pull requests merged in 2024-12, with the labels that each got.

#2923 chore: add hint text to single file attachment playground and fix errors
  apps/playground/src/app/components/forms/single-file-attachment/single-file-attachment.component.html
  apps/playground/src/app/components/forms/single-file-attachment/single-file-attachment.component.ts
Labels: risk level (author): 1

#2927 feat(components/forms): tokenize single file attachment styles
  apps/e2e/forms-storybook-e2e/src/e2e/single-file-attachment.component.cy.ts
  libs/components/forms/src/lib/modules/file-attachment/file-attachment/file-attachment.component.html
  libs/components/forms/src/lib/modules/file-attachment/file-attachment/file-attachment.component.scss
  libs/components/forms/src/lib/modules/file-attachment/file-attachment/file-attachment.component.spec.ts
  libs/components/forms/src/lib/modules/file-attachment/file-attachment/file-attachment.component.ts
  libs/components/theme/src/lib/styles/_forms.scss
Labels: risk level (author): 2

#2925 feat(components/datetime): add methods to the date-range-picker harness to get the selected calculator, and the start and end date values
  libs/components/datetime/src/lib/modules/date-range-picker/date-range-picker.component.spec.ts
  libs/components/datetime/src/lib/modules/date-range-picker/date-range-picker.component.ts
  libs/components/datetime/testing/src/modules/date-range-picker/date-range-picker-harness.spec.ts
  libs/components/datetime/testing/src/modules/date-range-picker/date-range-picker-harness.ts
Labels: risk level (author): 2

#2928 chore: release 11.25.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#2924 feat(components/colorpicker): tokenize colorpicker styles
  apps/e2e/colorpicker-storybook-e2e/src/e2e/colorpicker.component.cy.ts
  apps/e2e/colorpicker-storybook/project.json
  libs/components/colorpicker/src/lib/modules/colorpicker/colorpicker.component.html
  libs/components/colorpicker/src/lib/modules/colorpicker/colorpicker.component.scss
  libs/components/colorpicker/src/lib/modules/colorpicker/colorpicker.component.spec.ts
  libs/components/colorpicker/src/lib/modules/colorpicker/colorpicker.component.ts
  libs/components/colorpicker/testing/src/modules/colorpicker/colorpicker-dropdown-harness.ts
  libs/components/colorpicker/testing/src/modules/colorpicker/colorpicker-harness.ts
  libs/components/text-editor/src/lib/modules/text-editor/toolbar/text-editor-toolbar.component.scss
Labels: risk level (author): 3

#2929 fix(components/ag-grid): handle focus for adjacent lookup cells
  libs/components/ag-grid/src/lib/modules/ag-grid/ag-grid-wrapper.component.spec.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-editors/cell-editor-lookup/cell-editor-lookup.component.spec.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-editors/cell-editor-lookup/cell-editor-lookup.component.ts
Labels: risk level (author): 1

#2931 chore: release 11.26.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#2932 feat(components/datetime): add fuzzy datepicker input harness
  apps/code-examples/src/app/code-examples/datetime/datepicker/fuzzy/demo.component.html
  apps/code-examples/src/app/code-examples/datetime/datepicker/fuzzy/demo.component.spec.ts
  apps/code-examples/src/app/code-examples/datetime/datepicker/fuzzy/demo.component.ts
  libs/components/datetime/testing/src/modules/datepicker/datepicker-harness.spec.ts
  libs/components/datetime/testing/src/modules/datepicker/datepicker-harness.ts
  libs/components/datetime/testing/src/modules/datepicker/fuzzy-datepicker-input-harness.ts
Labels: risk level (author): 1

#2926 feat(components/split-view): add harnesses for split view
  apps/code-examples/src/app/code-examples/split-view/split-view/page-bound/demo.component.spec.ts
  libs/components/split-view/package.json
  libs/components/split-view/testing/src/modules/split-view/fixtures/record.ts
  libs/components/split-view/testing/src/modules/split-view/fixtures/split-view-harness-test.component.html
  libs/components/split-view/testing/src/modules/split-view/fixtures/split-view-harness-test.component.ts
  libs/components/split-view/testing/src/modules/split-view/split-view-drawer-harness.ts
  libs/components/split-view/testing/src/modules/split-view/split-view-harness-filters.ts
  libs/components/split-view/testing/src/modules/split-view/split-view-harness.spec.ts
  libs/components/split-view/testing/src/modules/split-view/split-view-harness.ts
  libs/components/split-view/testing/src/modules/split-view/split-view-workspace-content-harness.ts
  libs/components/split-view/testing/src/modules/split-view/split-view-workspace-footer-harness.ts
  libs/components/split-view/testing/src/modules/split-view/split-view-workspace-harness.ts
  libs/components/split-view/testing/src/modules/split-view/split-view-workspace-header-harness.ts
  libs/components/split-view/testing/src/public-api.ts
Labels: risk level (author): 1

#2936 feat(components/text-editor): tokenize text editor styles
  apps/e2e/text-editor-storybook-e2e/src/e2e/text-editor.component.cy.ts
  apps/e2e/text-editor-storybook/project.json
  libs/components/colorpicker/src/lib/modules/colorpicker/colorpicker.component.scss
  libs/components/text-editor/src/lib/modules/text-editor/text-editor.component.html
  libs/components/text-editor/src/lib/modules/text-editor/text-editor.component.scss
  libs/components/text-editor/src/lib/modules/text-editor/text-editor.component.spec.ts
  libs/components/text-editor/src/lib/modules/text-editor/text-editor.component.ts
  libs/components/text-editor/src/lib/modules/text-editor/toolbar/text-editor-toolbar.component.scss
Labels: risk level (author): 2

#2935 feat(components/forms): tokenize file drop styles
  apps/code-examples/src/app/code-examples/forms/file-drop/basic/demo.component.html
  apps/e2e/forms-storybook-e2e/src/e2e/file-attachment.component.cy.ts
  apps/e2e/forms-storybook/src/app/file-attachment/file-attachment.component.html
  apps/playground/src/app/components/forms/file-attachment/file-attachment.component.html
  apps/playground/src/app/components/forms/file-attachment/file-attachment.component.ts
  libs/components/ag-grid/src/lib/styles/_modern-dark.scss
  libs/components/ag-grid/src/lib/styles/_modern-light.scss
  libs/components/forms/src/lib/modules/file-attachment/file-drop/file-drop.component.html
  libs/components/forms/src/lib/modules/file-attachment/file-drop/file-drop.component.scss
  libs/components/forms/src/lib/modules/file-attachment/file-drop/file-drop.component.spec.ts
  libs/components/forms/src/lib/modules/file-attachment/file-drop/file-drop.component.ts
  libs/components/forms/src/lib/modules/file-attachment/file-drop/file-item.component.html
  libs/components/forms/src/lib/modules/file-attachment/file-drop/file-item.component.scss
  libs/components/forms/src/lib/modules/file-attachment/file-drop/file-item.component.spec.ts
  libs/components/forms/src/lib/modules/input-box/input-box.component.scss
  libs/components/lookup/src/lib/modules/search/search.component.scss
Labels: risk level (author): 2

#2938 fix(components/datetime): fix date range picker harness to assert start date visible when setting values
  libs/components/datetime/testing/src/modules/date-range-picker/date-range-picker-harness.spec.ts
  libs/components/datetime/testing/src/modules/date-range-picker/date-range-picker-harness.ts
Labels: risk level (author): 2

#2933 chore: release 11.27.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#2941 feat(components/forms): add `provideSkyFileAttachmentTesting` to aid in file attachment unit tests (internal)
  libs/components/core/src/index.ts
  libs/components/core/src/lib/modules/file-reader/file-reader.service.spec.ts
  libs/components/core/src/lib/modules/file-reader/file-reader.service.ts
  libs/components/core/testing/src/modules/file-reader/file-reader-testing.service.ts
  libs/components/core/testing/src/modules/file-reader/provide-file-reader-testing.spec.ts
  libs/components/core/testing/src/modules/file-reader/provide-file-reader-testing.ts
  libs/components/core/testing/src/public-api.ts
  libs/components/forms/src/lib/modules/file-attachment/file-attachment/file-attachment.component.spec.ts
  libs/components/forms/src/lib/modules/file-attachment/file-attachment/file-attachment.component.ts
  libs/components/forms/testing/src/modules/file-attachment/shared/provide-file-attachment-testing.ts
  libs/components/forms/testing/src/public-api.ts
Labels: risk level (author): 1

#2943 fix(components/lookup): lookup library test harnesses properly denote deprecated functions and internally do not use deprecated functions
  libs/components/lookup/testing/src/legacy/country-field/country-field-fixture.spec.ts
  libs/components/lookup/testing/src/legacy/search/search-fixture.spec.ts
  libs/components/lookup/testing/src/legacy/search/search-fixture.ts
  libs/components/lookup/testing/src/modules/autocomplete/autocomplete-harness.spec.ts
  libs/components/lookup/testing/src/modules/autocomplete/fixtures/autocomplete-harness-test.component.ts
  libs/components/lookup/testing/src/modules/country-field/country-field-harness.spec.ts
  libs/components/lookup/testing/src/modules/country-field/country-field-harness.ts
  libs/components/lookup/testing/src/modules/country-field/fixtures/country-field-harness-test.component.ts
  libs/components/lookup/testing/src/modules/lookup/fixtures/lookup-harness-test.component.ts
  libs/components/lookup/testing/src/modules/lookup/fixtures/lookup-harness-test.module.ts
  libs/components/lookup/testing/src/modules/lookup/lookup-harness.spec.ts
  libs/components/lookup/testing/src/modules/lookup/lookup-harness.ts
  libs/components/lookup/testing/src/modules/search/search-harness.spec.ts
  scripts/__snapshots__/deprecations.json
Labels: risk level (author): 2

#2930 feat(components/forms): file attachment harness
  apps/code-examples/src/app/code-examples/forms/file-attachment/basic/demo.component.html
  apps/code-examples/src/app/code-examples/forms/file-attachment/basic/demo.component.spec.ts
  apps/playground/src/app/components/forms/file-attachment/file-attachment.component.html
  apps/playground/src/app/components/forms/file-attachment/file-attachment.component.ts
  libs/components/forms/src/lib/modules/file-attachment/file-attachment/file-attachment.component.html
  libs/components/forms/src/lib/modules/file-attachment/file-attachment/file-attachment.component.spec.ts
  libs/components/forms/src/lib/modules/file-attachment/file-attachment/file-attachment.component.ts
  libs/components/forms/testing/src/modules/file-attachment/file-attachment/file-attachment-harness-filters.ts
  libs/components/forms/testing/src/modules/file-attachment/file-attachment/file-attachment-harness.spec.ts
  libs/components/forms/testing/src/modules/file-attachment/file-attachment/file-attachment-harness.ts
  libs/components/forms/testing/src/public-api.ts
Labels: risk level (author): 2

#2945 fix(components/layout): deprecation error for box header component lists correct component
  libs/components/layout/src/lib/modules/box/box-header.component.ts
Labels: risk level (author): 1

#2942 fix(sdk/skyux-eslint): remove duplicate rules
  libs/sdk/skyux-eslint/src/configs/ts-base-type-checked.ts
  libs/sdk/skyux-eslint/src/configs/ts-base.ts
Labels: risk level (author): 1

#2947 fix(components/datetime): date range picker emits touched status when focus leaves composite control
  libs/components/datetime/src/lib/modules/date-range-picker/date-range-picker.component.html
  libs/components/datetime/src/lib/modules/date-range-picker/date-range-picker.component.spec.ts
  libs/components/datetime/src/lib/modules/date-range-picker/date-range-picker.component.ts
  libs/components/datetime/src/lib/modules/datepicker/datepicker.component.ts
Labels: risk level (author): 2

#2944 fix(components/modals): modal host sets initial modal focus to avoid race condition
  apps/integration/src/app/integrations/lookup-in-modal/lookup-in-modal.component.spec.ts
  apps/integration/src/app/integrations/lookup-in-modal/modal-lookup.component.spec.ts
  libs/components/modals/src/lib/modules/modal/modal-adapter.service.ts
  libs/components/modals/src/lib/modules/modal/modal-component-adapter.service.ts
  libs/components/modals/src/lib/modules/modal/modal-host.component.ts
  libs/components/modals/src/lib/modules/modal/modal.component.spec.ts
  libs/components/modals/src/lib/modules/modal/modal.component.ts
  package-lock.json
Labels: risk level (author): 3

#2940 chore: release 11.28.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#2948 feat(components/datetime): add `shortDescription$` observable for date range calculators
  apps/code-examples/src/app/code-examples/datetime/date-range-picker/basic/demo.component.html
  apps/code-examples/src/app/code-examples/datetime/date-range-picker/basic/demo.component.ts
  apps/code-examples/src/app/code-examples/datetime/date-range-picker/custom-calculator/demo.component.html
  apps/code-examples/src/app/code-examples/datetime/date-range-picker/custom-calculator/demo.component.ts
  apps/code-examples/src/app/code-examples/datetime/date-range-picker/help-key/demo.component.html
  apps/code-examples/src/app/code-examples/datetime/date-range-picker/help-key/demo.component.spec.ts
  apps/code-examples/src/app/code-examples/datetime/date-range-picker/help-key/demo.component.ts
  apps/code-examples/src/app/code-examples/layout/text-expand/inline/demo.component.spec.ts
  libs/components/datetime/src/lib/modules/date-range-picker/date-range-picker.component.html
  libs/components/datetime/src/lib/modules/date-range-picker/date-range.service.spec.ts
  libs/components/datetime/src/lib/modules/date-range-picker/date-range.service.ts
  libs/components/datetime/src/lib/modules/date-range-picker/types/date-range-calculator.spec.ts
  libs/components/datetime/src/lib/modules/date-range-picker/types/date-range-calculator.ts
Labels: risk level (author): 2

#2951 feat(sdk/skyux-eslint): add `no-radio-group-with-nested-list` rule
  libs/sdk/skyux-eslint/docs/rules/template/no-radio-group-with-nested-list.md
  libs/sdk/skyux-eslint/src/configs/template-all.ts
  libs/sdk/skyux-eslint/src/configs/template-recommended.ts
  libs/sdk/skyux-eslint/src/plugins/template-plugin.ts
  libs/sdk/skyux-eslint/src/rules/template/no-radio-group-with-nested-list.spec.ts
  libs/sdk/skyux-eslint/src/rules/template/no-radio-group-with-nested-list.ts
  libs/sdk/skyux-eslint/src/rules/template/prefer-label-text.ts
  libs/sdk/skyux-eslint/src/rules/testing/create-template-rule-tester.ts
  libs/sdk/skyux-eslint/src/rules/utils/ast-utils.ts
  libs/sdk/skyux-eslint/src/rules/utils/get-child-node-of.ts
  libs/sdk/skyux-eslint/src/rules/utils/get-text-content.ts
  package-lock.json
  package.json
  scripts/__snapshots__/deprecations.json
Labels: risk level (author): 1

#2953 feat(sdk/skyux-eslint): add `no-deprecated-classnames` rule
  apps/code-examples/src/app/code-examples/ag-grid/data-grid/template-ref-column/demo.component.html
  apps/code-examples/src/app/code-examples/forms/checkbox/basic/demo.component.html
  apps/code-examples/src/app/code-examples/forms/checkbox/help-key/demo.component.html
  apps/code-examples/src/app/code-examples/forms/checkbox/icon-group/demo.component.html
  apps/code-examples/src/app/code-examples/modals/confirm/basic-with-harness/demo.component.html
  libs/sdk/skyux-eslint/docs/rules/template/no-deprecated-classnames.md
  libs/sdk/skyux-eslint/src/configs/template-all.ts
  libs/sdk/skyux-eslint/src/configs/template-recommended.ts
  libs/sdk/skyux-eslint/src/plugins/template-plugin.ts
  libs/sdk/skyux-eslint/src/rules/template/no-deprecated-classnames.spec.ts
  libs/sdk/skyux-eslint/src/rules/template/no-deprecated-classnames.ts
Labels: risk level (author): 1

#2954 fix(components/text-editor): update `dompurify` to address a security vulnerability
  libs/components/text-editor/package.json
  package-lock.json
  package.json
Labels: risk level (author): 1

#2952 chore: release 11.30.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#2955 fix(components/tabs): remove tabset overflow when collapsed
  libs/components/tabs/src/lib/modules/tabs/tabset.component.scss
Labels: risk level (author): 1

#2957 fix(components/forms): styles do not output build warnings when utlizing checkboxes or radio buttons
  apps/playground/project.json
  libs/components/theme/src/lib/styles/themes/modern/_switch.scss
Labels: risk level (author): 2

#2958 fix(components/datetime): date range picker code example imports `SkyDatepickerModule`
  apps/code-examples/src/app/code-examples/datetime/date-range-picker/basic/demo.component.ts
Labels: risk level (author): 1

#2956 chore: release 11.30.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending
