Repository blackbaud/skyux, pull requests merged in 2024-10, with the labels that each got.

#2789 feat(components/lookup): add autocomplete test harness
  apps/code-examples/src/app/code-examples/lookup/autocomplete/basic/demo.component.html
  apps/code-examples/src/app/code-examples/lookup/autocomplete/basic/demo.component.spec.ts
  apps/code-examples/src/app/code-examples/lookup/autocomplete/basic/demo.component.ts
  libs/components/lookup/testing/src/autocomplete/autocomplete-harness-filters.ts
  libs/components/lookup/testing/src/autocomplete/autocomplete-harness.spec.ts
  libs/components/lookup/testing/src/autocomplete/autocomplete-harness.ts
  libs/components/lookup/testing/src/autocomplete/autocomplete-input-harness.ts
  libs/components/lookup/testing/src/autocomplete/autocomplete-search-result-harness.ts
  libs/components/lookup/testing/src/autocomplete/fixtures/autocomplete-harness-test.component.html
  libs/components/lookup/testing/src/autocomplete/fixtures/autocomplete-harness-test.component.ts
Labels: risk level (author): 1

#2783 feat(components/popovers): tokenize popover styling
  apps/e2e/popovers-storybook-e2e/src/e2e/popover.component.cy.ts
  apps/e2e/popovers-storybook/project.json
  apps/e2e/popovers-storybook/src/app/popover/popover.component.html
  apps/e2e/popovers-storybook/src/app/popover/popover.component.scss
  libs/components/popovers/src/lib/modules/popover/popover-content.component.html
  libs/components/popovers/src/lib/modules/popover/popover-content.component.scss
  libs/components/theme/package.json
  libs/components/theme/src/lib/styles/themes/modern/_elevation.scss
  libs/components/theme/src/lib/styles/themes/modern/_sizing.scss
  package-lock.json
  package.json
Labels: risk level (author): 3

#2780 chore: mark confirm component as internal
  libs/components/modals/src/lib/modules/confirm/confirm.component.ts
Labels: risk level (author): 1

#2793 ci: remove requirement for commits in single commit PRs to match the PR title
  .github/workflows/validate-pr.yml
Labels: risk level (author): 1

#2777 fix(components/forms): delay error display to allow clicks to content below to complete
  apps/playground/src/app/components/modal/modal-required.component.ts
  apps/playground/src/app/components/modal/modal-visual.component.html
  apps/playground/src/app/components/modal/modal-visual.component.ts
  libs/components/forms/src/lib/modules/form-error/form-error.component.ts
Labels: risk level (author): 3

#2795 fix(sdk/testing): adjust async matchers
  libs/sdk/testing/src/lib/matchers/matchers.ts
Labels: risk level (author): 1

#2792 fix(components/tiles): remove horizontal spacing from tile dashboard in blocks page layout
  apps/e2e/pages-storybook-e2e/src/e2e/blocks-tile-dashboard-page.component.cy.ts
  apps/e2e/pages-storybook-e2e/src/e2e/tabs-tile-dashboard-page.component.cy.ts
  apps/e2e/pages-storybook/src/app/page/layouts/blocks-tile-dashboard-page/blocks-tile-dashboard-page.component.stories.ts
  apps/e2e/pages-storybook/src/app/page/layouts/blocks-tile-dashboard-page/blocks-tile-dashboard-page.component.ts
  apps/e2e/pages-storybook/src/app/page/layouts/routes.ts
  apps/e2e/pages-storybook/src/app/page/layouts/shared/tiles/tile-dashboard.component.ts
  apps/e2e/pages-storybook/src/app/page/layouts/shared/tiles/tile1.component.ts
  apps/e2e/pages-storybook/src/app/page/layouts/shared/tiles/tile2.component.ts
  apps/e2e/pages-storybook/src/app/page/layouts/tabs-tile-dashboard-page/tabs-tile-dashboard-page.component.stories.ts
  apps/e2e/pages-storybook/src/app/page/layouts/tabs-tile-dashboard-page/tabs-tile-dashboard-page.component.ts
  apps/playground/src/app/components/pages/layouts/blocks-page-tile-dashboard/blocks-page-tile-dashboard.component.ts
  apps/playground/src/app/components/pages/layouts/routes.ts
  apps/playground/src/app/components/pages/layouts/shared/tiles/tile-dashboard.component.ts
  apps/playground/src/app/components/pages/layouts/shared/tiles/tile1.component.ts
  apps/playground/src/app/components/pages/layouts/shared/tiles/tile2.component.ts
  apps/playground/src/app/components/pages/layouts/shared/tiles/tile3.component.ts
  apps/playground/src/app/components/pages/layouts/tabs-page/tabs-page.component.html
  apps/playground/src/app/components/pages/layouts/tabs-page/tabs-page.component.ts
  libs/components/tiles/src/lib/modules/tiles/tile-dashboard-column/tile-dashboard-column.component.scss
  libs/components/tiles/src/lib/modules/tiles/tile-dashboard/tile-dashboard.component.html
  libs/components/tiles/src/lib/modules/tiles/tile-dashboard/tile-dashboard.component.scss
  libs/components/tiles/src/lib/modules/tiles/tile-dashboard/tile-dashboard.component.ts
Labels: risk level (author): 3

#2794 fix(components/pages): display dropdowns as inline and fix margins around wrapped buttons
  apps/e2e/pages-storybook/src/app/page/layouts/blocks-page/blocks-page.component.html
  apps/e2e/pages-storybook/src/app/page/layouts/blocks-page/blocks-page.component.ts
  libs/components/pages/src/lib/modules/page-header/page-header-actions.component.html
  libs/components/pages/src/lib/modules/page-header/page-header-actions.component.scss
  libs/components/pages/src/lib/modules/page-header/page-header-actions.component.ts
Labels: risk level (author): 3

#2791 feat(components/toast): tokenize toast styling
  apps/e2e/toast-storybook-e2e/src/e2e/toast.component.cy.ts
  apps/e2e/toast-storybook/project.json
  libs/components/indicators/src/lib/modules/alert/alert.modern.component.scss
  libs/components/indicators/src/lib/modules/label/label.component.scss
  libs/components/indicators/src/lib/modules/status-indicator/status-indicator.component.scss
  libs/components/layout/src/lib/modules/box/box-header.component.scss
  libs/components/layout/src/lib/modules/box/box.component.scss
  libs/components/theme/package.json
  libs/components/theme/src/lib/styles/_forms.scss
  libs/components/theme/src/lib/styles/themes/modern/_elevation.scss
  libs/components/theme/src/lib/styles/themes/modern/_theme.scss
  libs/components/toast/src/lib/modules/toast/toast.component.scss
  libs/components/toast/src/lib/modules/toast/toaster.component.scss
  package-lock.json
  package.json
Labels: risk level (author): 2

#2787 chore: release 11.7.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#2796 feat(components/forms): add `linkUploadHintText` input to the file drop component
  apps/code-examples/src/app/code-examples/forms/file-drop/basic/demo.component.html
  apps/e2e/forms-storybook/src/app/file-attachment/file-attachment.component.html
  apps/playground/src/app/components/forms/file-attachment/file-attachment.component.html
  libs/components/forms/src/assets/locales/resources_en_US.json
  libs/components/forms/src/lib/modules/file-attachment/file-drop/file-drop.component.html
  libs/components/forms/src/lib/modules/file-attachment/file-drop/file-drop.component.spec.ts
  libs/components/forms/src/lib/modules/file-attachment/file-drop/file-drop.component.ts
  libs/components/forms/src/lib/modules/input-box/input-box.component.scss
  libs/components/forms/src/lib/modules/shared/sky-forms-resources.module.ts
  libs/sdk/testing/src/lib/matchers/matchers.ts
Labels: risk level (author): 3

#2784 feat(components/pages): add `sky-link-list` component
  apps/code-examples/src/app/code-examples/pages/page/record-page-blocks-layout-demo/demo.component.html
  apps/e2e/pages-storybook/src/app/app.module.ts
  apps/e2e/pages-storybook/src/app/page/layouts/blocks-page/blocks-page.component.html
  apps/e2e/pages-storybook/src/app/page/layouts/blocks-page/blocks-page.component.ts
  apps/e2e/pages-storybook/src/app/page/layouts/fit-page/fit-page.component.html
  apps/e2e/pages-storybook/src/app/page/layouts/fit-page/fit-page.component.ts
  apps/e2e/pages-storybook/src/app/page/layouts/list-page/list-page.component.html
  apps/e2e/pages-storybook/src/app/page/layouts/list-page/list-page.component.ts
  apps/e2e/pages-storybook/src/app/page/layouts/tabs-page/tabs-page.component.html
  apps/e2e/pages-storybook/src/app/page/layouts/tabs-page/tabs-page.component.ts
  apps/e2e/pages-storybook/src/app/shared/links/links.component.html
  apps/e2e/pages-storybook/src/app/shared/links/links.component.ts
  apps/playground/src/app/components/pages/layouts/blocks-page/blocks-page.component.html
  apps/playground/src/app/components/pages/layouts/blocks-page/blocks-page.component.ts
  libs/components/colorpicker/testing/project.json
  libs/components/pages/src/index.ts
  libs/components/pages/src/lib/modules/action-hub/action-hub.component.html
  libs/components/pages/src/lib/modules/action-hub/action-hub.component.spec.ts
  libs/components/pages/src/lib/modules/link-list/fixtures/link-list-fixture.component.ts
  libs/components/pages/src/lib/modules/link-list/link-list-item.component.ts
  libs/components/pages/src/lib/modules/link-list/link-list.component.html
  libs/components/pages/src/lib/modules/link-list/link-list.component.spec.ts
  libs/components/pages/src/lib/modules/link-list/link-list.component.ts
  libs/components/pages/src/lib/modules/link-list/link-list.module.ts
  libs/components/pages/src/lib/modules/page/page-links.component.ts
  libs/components/pages/src/lib/modules/page/page.module.ts
  libs/components/pages/testing/project.json
  libs/components/pages/testing/src/link-list/link-list-harness-filters.ts
  libs/components/pages/testing/src/link-list/link-list-harness.spec.ts
  libs/components/pages/testing/src/link-list/link-list-harness.ts
  libs/components/pages/testing/src/public-api.ts
Labels: risk level (author): 1

#2798 feat(components/lookup): add search test harness
  apps/code-examples/src/app/code-examples/lookup/search/basic/demo.component.html
  apps/code-examples/src/app/code-examples/lookup/search/basic/demo.component.spec.ts
  apps/code-examples/src/app/code-examples/lookup/search/basic/demo.component.ts
  libs/components/lookup/testing/src/search/search-harness.spec.ts
  libs/components/lookup/testing/src/search/search-harness.ts
Labels: risk level (author): 1

#2797 feat(components/theme): tokenize type and theme
  apps/e2e/theme-storybook-e2e/src/e2e/theming.component.cy.ts
  apps/e2e/theme-storybook/project.json
  libs/components/theme/package.json
  libs/components/theme/src/lib/styles/themes/modern/_compat-tokens-mixins.scss
  libs/components/theme/src/lib/styles/themes/modern/_theme.scss
  libs/components/theme/src/lib/styles/themes/modern/_type.scss
  package-lock.json
  package.json
Labels: risk level (author): 3

#2800 feat(components/pages): add `sky-link-list-recently-accessed` component
  apps/code-examples/src/app/code-examples/pages/page/record-page-blocks-layout-demo/demo.component.html
  apps/code-examples/src/app/code-examples/pages/page/record-page-blocks-layout-demo/demo.component.ts
  libs/components/pages/src/index.ts
  libs/components/pages/src/lib/modules/action-hub/action-hub-recent-links-resolve.pipe.ts
  libs/components/pages/src/lib/modules/action-hub/action-hub.component.html
  libs/components/pages/src/lib/modules/action-hub/action-hub.module.ts
  libs/components/pages/src/lib/modules/link-list-recently-accessed/link-list-recently-accessed.component.spec.ts
  libs/components/pages/src/lib/modules/link-list-recently-accessed/link-list-recently-accessed.component.ts
  libs/components/pages/src/lib/modules/link-list/link-list.component.ts
  libs/components/pages/src/lib/modules/link-list/link-list.module.ts
  libs/components/pages/src/lib/modules/page/page-links.component.ts
  libs/components/pages/src/lib/modules/page/page.module.ts
Labels: risk level (author): 1

#2801 chore: release 11.8.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#2804 feat(components/indicators): tokenize key info styling
  apps/e2e/indicators-storybook-e2e/src/e2e/key-info.component.cy.ts
  libs/components/indicators/src/lib/modules/key-info/key-info.component.scss
Labels: risk level (author): 1

#2799 fix(components/popovers): update arrow position when scrolling in flex layout
  apps/e2e/popovers-storybook/src/app/app.module.ts
  libs/components/popovers/src/lib/modules/popover/popover-adapter.service.spec.ts
  libs/components/popovers/src/lib/modules/popover/popover-adapter.service.ts
  libs/components/popovers/src/lib/modules/popover/popover-content.component.html
  libs/components/popovers/src/lib/modules/popover/popover-content.component.scss
  libs/components/popovers/src/lib/modules/popover/popover-content.component.ts
  libs/components/popovers/src/lib/modules/popover/popover.directive.spec.ts
Labels: risk level (author): 2

#2806 chore: release 10.44.2
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease 10.x.x: pending

#2809 chore: changelog for 10.44.2 (#2806) 🍒
  CHANGELOG.md
Labels: risk level (author): 1, risk level (reviewer): 1

#2808 fix(components/popovers): update arrow position when scrolling in flex layout (#2799)
  apps/e2e/popovers-storybook/src/app/app.module.ts
  libs/components/popovers/src/lib/modules/popover/popover-adapter.service.spec.ts
  libs/components/popovers/src/lib/modules/popover/popover-adapter.service.ts
  libs/components/popovers/src/lib/modules/popover/popover-content.component.html
  libs/components/popovers/src/lib/modules/popover/popover-content.component.scss
  libs/components/popovers/src/lib/modules/popover/popover-content.component.ts
  libs/components/popovers/src/lib/modules/popover/popover.directive.spec.ts
Labels: risk level (author): 2

#2810 fix(components/icon): reorganize internal file structure for correct documentation output
  libs/components/icon/src/index.ts
  libs/components/icon/src/lib/modules/icon/fixtures/icon-fixtures.module.ts
  libs/components/icon/src/lib/modules/icon/fixtures/icon-stack.component.fixture.html
  libs/components/icon/src/lib/modules/icon/fixtures/icon-stack.component.fixture.ts
  libs/components/icon/src/lib/modules/icon/fixtures/icon.component.fixture.html
  libs/components/icon/src/lib/modules/icon/fixtures/icon.component.fixture.ts
  libs/components/icon/src/lib/modules/icon/icon-class-list.pipe.ts
  libs/components/icon/src/lib/modules/icon/icon-resolver.service.spec.ts
  libs/components/icon/src/lib/modules/icon/icon-resolver.service.ts
  libs/components/icon/src/lib/modules/icon/icon-stack-item.ts
  libs/components/icon/src/lib/modules/icon/icon-stack.component.html
  libs/components/icon/src/lib/modules/icon/icon-stack.component.scss
  libs/components/icon/src/lib/modules/icon/icon-stack.component.spec.ts
  libs/components/icon/src/lib/modules/icon/icon-stack.component.ts
  libs/components/icon/src/lib/modules/icon/icon-svg-resolver.service.spec.ts
  libs/components/icon/src/lib/modules/icon/icon-svg-resolver.service.ts
  libs/components/icon/src/lib/modules/icon/icon-svg.component.html
  libs/components/icon/src/lib/modules/icon/icon-svg.component.spec.ts
  libs/components/icon/src/lib/modules/icon/icon-svg.component.ts
  libs/components/icon/src/lib/modules/icon/icon-svg.default.component.scss
  libs/components/icon/src/lib/modules/icon/icon-svg.modern.component.scss
  libs/components/icon/src/lib/modules/icon/icon-variant.ts
  libs/components/icon/src/lib/modules/icon/icon.component.html
  libs/components/icon/src/lib/modules/icon/icon.component.scss
  libs/components/icon/src/lib/modules/icon/icon.component.spec.ts
  libs/components/icon/src/lib/modules/icon/icon.component.ts
  libs/components/icon/src/lib/modules/icon/icon.module.ts
  libs/components/icon/src/lib/modules/icon/types/icon-resolved.ts
  libs/components/icon/src/lib/modules/icon/types/icon-type.ts
  libs/components/icon/src/lib/modules/icon/types/icon-variant-type.ts
  libs/components/icon/testing/ng-package.json
  libs/components/icon/testing/src/icon/icon-harness.spec.ts
  libs/components/icon/testing/src/public-api.ts
  tsconfig.base.json
Labels: risk level (author): 3

#2805 chore: release 11.9.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#2814 feat(components/progress-indicator): add progress indicator test harness
  apps/code-examples/src/app/code-examples/progress-indicator/passive-indicator/basic/demo.component.html
  apps/code-examples/src/app/code-examples/progress-indicator/passive-indicator/basic/demo.component.spec.ts
  apps/code-examples/src/app/code-examples/progress-indicator/waterfall-indicator/basic/demo.component.html
  apps/code-examples/src/app/code-examples/progress-indicator/waterfall-indicator/basic/demo.component.spec.ts
  libs/components/progress-indicator/package.json
  libs/components/progress-indicator/src/lib/modules/progress-indicator/progress-indicator-reset-button/progress-indicator-reset-button.component.ts
  libs/components/progress-indicator/src/lib/modules/progress-indicator/progress-indicator.component.spec.ts
  libs/components/progress-indicator/testing/karma.conf.js
  libs/components/progress-indicator/testing/ng-package.json
  libs/components/progress-indicator/testing/project.json
  libs/components/progress-indicator/testing/src/progress-indicator/progress-indicator-harness-filters.ts
  libs/components/progress-indicator/testing/src/progress-indicator/progress-indicator-harness.spec.ts
  libs/components/progress-indicator/testing/src/progress-indicator/progress-indicator-harness.ts
  libs/components/progress-indicator/testing/src/progress-indicator/progress-indicator-item-harness-filters.ts
  libs/components/progress-indicator/testing/src/progress-indicator/progress-indicator-item-harness.ts
  libs/components/progress-indicator/testing/src/public-api.ts
  libs/components/progress-indicator/testing/tsconfig.spec.json
  tsconfig.base.json
Labels: risk level (author): 1

#2815 chore: release 11.10.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#2820 fix(components/ag-grid): capture sort changes in data manager when not using sort index
  libs/components/ag-grid/src/lib/modules/ag-grid/ag-grid-data-manager-adapter.directive.spec.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/ag-grid-data-manager-adapter.directive.ts
Labels: risk level (author): 1

#2816 feat(components/ag-grid): support AG Grid 32.2.2
  apps/code-examples/src/app/code-examples/ag-grid/data-grid/basic/demo.component.ts
  apps/code-examples/src/app/code-examples/ag-grid/data-grid/data-manager/view-grid.component.ts
  apps/code-examples/src/app/code-examples/ag-grid/data-grid/paging/demo.component.ts
  libs/components/ag-grid/package.json
  libs/components/ag-grid/src/lib/modules/ag-grid/ag-grid-data-manager-adapter.directive.spec.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/ag-grid-data-manager-adapter.directive.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/ag-grid.service.spec.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/ag-grid.service.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/fixtures/ag-grid-data-manager.component.fixture.ts
  libs/components/packages/package.json
  libs/components/packages/src/schematics/ag-grid-migrate/ag-grid-migrate.schematic.spec.ts
  libs/components/packages/src/schematics/ag-grid-migrate/ag-grid-migrate.schematic.ts
  libs/components/packages/src/schematics/migrations/update-11/ag-grid/ag-grid.schematic.spec.ts
  libs/components/packages/src/schematics/migrations/update-11/ag-grid/ag-grid.schematic.ts
  libs/components/storybook/package.json
  package-lock.json
  package.json
Labels: risk level (author): 2

#2812 fix(components/pages): adjust page links spacing
  apps/e2e/pages-storybook-e2e/src/e2e/page-layout-blocks.component.cy.ts
  apps/e2e/pages-storybook/src/app/page/layouts/blocks-page/blocks-page.component.html
  apps/e2e/pages-storybook/src/app/page/layouts/blocks-page/blocks-page.component.stories.ts
  apps/e2e/pages-storybook/src/app/page/layouts/blocks-page/blocks-page.component.ts
  apps/e2e/pages-storybook/src/app/page/layouts/routes.ts
  libs/components/pages/src/lib/modules/page-header/page-header.component.html
  libs/components/theme/src/lib/styles/_layout-host.scss
Labels: risk level (author): 1

#2818 chore: upgrade to NX 20
  .github/workflows/ci.yml
  .github/workflows/e2e.yml
  jest.config.ts
  libs/sdk/e2e-schematics/package.json
  libs/sdk/e2e-schematics/src/generators/component-e2e/index.ts
  libs/sdk/e2e-schematics/src/generators/configure-storybook/index.spec.ts
  libs/sdk/e2e-schematics/src/generators/story/index.spec.ts
  libs/sdk/e2e-schematics/src/generators/storybook-composition/index.spec.ts
  libs/sdk/e2e-schematics/src/utils/__snapshots__/find-module.spec.ts.snap
  libs/sdk/e2e-schematics/src/utils/angular-module-generator.ts
  libs/sdk/e2e-schematics/src/utils/ast-utils.spec.ts
  libs/sdk/e2e-schematics/src/utils/get-projects.spec.ts
  libs/sdk/e2e-schematics/src/utils/nx-generator-utils.spec.ts
  libs/sdk/e2e-schematics/src/utils/testing.ts
  libs/sdk/tools/package.json
  libs/sdk/tools/src/generators/configure-test-ci/generator.spec.ts
  libs/sdk/tools/src/generators/configure-test-ci/generator.ts
  libs/sdk/tools/src/generators/update-dependencies/generator.spec.ts
  libs/sdk/tools/src/generators/update-dependencies/generator.ts
  nx.json
  package-lock.json
  package.json
Labels: risk level (author): 2, skip e2e

#2826 fix(components/theme): address warning in styles
  libs/components/theme/package.json
  package-lock.json
  package.json
Labels: risk level (author): 1

#2825 fix: run schematic to set VSCode plugin setting to not expect flat configs for ESLint 9 which was included in `11.x.x`
  libs/components/packages/src/schematics/migrations/migration-collection.json
  libs/components/packages/src/schematics/migrations/update-11/vscode-eslint-setting/vscode-eslint-setting.schematic.spec.ts
  libs/components/packages/src/schematics/migrations/update-11/vscode-eslint-setting/vscode-eslint-setting.schematic.ts
  libs/components/packages/src/schematics/utility/tree.ts
Labels: risk level (author): 2

#2827 chore: release 11.11.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#2828 fix(components/tabs): push permalink query params via router
  .github/workflows/ci.yml
  libs/components/tabs/src/lib/modules/tabs/fixtures/tabset-loop.component.fixture.html
  libs/components/tabs/src/lib/modules/tabs/tabset-permalink.service.ts
  libs/components/tabs/src/lib/modules/tabs/tabset.component.html
  libs/components/tabs/src/lib/modules/tabs/tabset.component.spec.ts
Labels: risk level (author): 1

#2829 chore: release 11.11.2
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#2803 feat(components/theme): tokenize button styling
  .cspell.json
  apps/e2e/theme-storybook-e2e/src/e2e/buttons.component.cy.ts
  apps/playground/src/app/app.component.scss
  libs/components/indicators/src/lib/modules/alert/alert.modern.component.scss
  libs/components/theme/src/lib/styles/themes/modern/_buttons.scss
  libs/components/theme/src/lib/styles/themes/modern/_theme.scss
Labels: risk level (author): 2

#2833 fix(components/packages): accommodate vscode settings with json comments
  libs/components/packages/src/schematics/migrations/update-11/vscode-eslint-setting/vscode-eslint-setting.schematic.spec.ts
  libs/components/packages/src/schematics/migrations/update-11/vscode-eslint-setting/vscode-eslint-setting.schematic.ts
Labels: risk level (author): 1

#2832 fix(components/pages): constrain page sizing
  apps/e2e/pages-storybook/src/app/app.module.ts
  libs/components/pages/src/lib/modules/page-header/page-header.component.spec.ts
  libs/components/pages/src/lib/modules/page-header/page-header.component.ts
  libs/components/pages/src/lib/modules/page/page-content.component.ts
  libs/components/pages/src/lib/modules/page/page.component.ts
  libs/components/theme/src/lib/styles/_layout-host.scss
Labels: risk level (author): 1

#2831 chore: release 11.12.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#2834 feat(components/forms): tokenize stacked input box styling
  libs/components/forms/src/lib/modules/input-box/fixtures/input-box.component.fixture.html
  libs/components/forms/src/lib/modules/input-box/input-box.component.spec.ts
  libs/components/forms/src/lib/modules/input-box/input-box.component.ts
  libs/components/forms/testing/src/input-box/input-box-harness.ts
  libs/components/theme/src/lib/styles/_sizing.scss
  libs/components/theme/src/lib/styles/themes/modern/_sizing.scss
Labels: risk level (author): 1

#2824 fix(components/pages): update code example for action hub pattern
  apps/code-examples/src/app/code-examples/pages/page/home-page-blocks-layout-demo/demo.component.html
  apps/code-examples/src/app/code-examples/pages/page/home-page-blocks-layout-demo/demo.component.spec.ts
  apps/code-examples/src/app/code-examples/pages/page/home-page-blocks-layout-demo/demo.component.ts
  apps/code-examples/src/app/code-examples/pages/page/home-page-blocks-layout-demo/home-page-content.component.html
  apps/code-examples/src/app/code-examples/pages/page/home-page-blocks-layout-demo/home-page-content.component.ts
  apps/code-examples/src/app/code-examples/pages/page/home-page-blocks-layout-demo/tile-my-actions.component.html
  apps/code-examples/src/app/code-examples/pages/page/home-page-blocks-layout-demo/tile-my-actions.component.ts
  apps/code-examples/src/app/code-examples/pages/page/home-page-blocks-layout-demo/tile-updates.component.html
  apps/code-examples/src/app/code-examples/pages/page/home-page-blocks-layout-demo/tile-updates.component.ts
  apps/code-examples/src/app/code-examples/pages/page/record-page-blocks-layout-demo/demo.component.scss
  apps/code-examples/src/app/features/pages.module.ts
  apps/code-examples/src/app/home/home.component.html
  apps/e2e/pages-storybook-e2e/src/e2e/action-hub.component.cy.ts
  apps/e2e/pages-storybook/src/app/app.module.ts
  apps/e2e/pages-storybook/src/styles.scss
  libs/components/pages/src/lib/modules/action-hub/action-hub-buttons.component.scss
  libs/components/pages/src/lib/modules/action-hub/action-hub.component.html
  libs/components/pages/src/lib/modules/action-hub/action-hub.component.scss
  libs/components/pages/src/lib/modules/action-hub/action-hub.module.ts
  libs/components/theme/src/lib/styles/_layout-host.scss
Labels: risk level (author): 1

#2837 feat(components/indicators): tokenize chevron and expansion indicator styles
  apps/e2e/indicators-storybook-e2e/src/e2e/chevron.component.cy.ts
  apps/e2e/indicators-storybook-e2e/src/e2e/expansion-indicator.component.cy.ts
  libs/components/indicators/src/lib/modules/chevron/chevron.modern.component.scss
  libs/components/indicators/src/lib/modules/expansion-indicator/expansion-indicator.modern.component.scss
Labels: risk level (author): 1

#2838 fix(components/theme): public api publishes successfully
  libs/components/tabs/src/lib/modules/sectioned-form/sectioned-form-section.component.scss
  libs/components/theme/src/lib/styles/_forms.scss
  libs/components/theme/src/lib/styles/_public-api/_compat/_mixins.scss
Labels: risk level (author): 1

#2835 chore: release 11.13.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#2842 fix(components/ag-grid): adjust row selection options
  libs/components/ag-grid/src/lib/modules/ag-grid/ag-grid.service.spec.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/ag-grid.service.ts
Labels: risk level (author): 1

#2843 chore: release 11.13.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#2841 feat(components/help-inline): tokenize help inline styles
  apps/e2e/help-inline-storybook-e2e/src/e2e/help-inline.component.cy.ts
  apps/e2e/help-inline-storybook/project.json
  libs/components/help-inline/src/lib/modules/help-inline/help-inline.modern.component.scss
  libs/components/theme/src/lib/styles/themes/modern/_compat-tokens-mixins.scss
  libs/components/theme/src/lib/styles/themes/modern/_theme.scss
  libs/components/theme/src/lib/styles/themes/modern/_type.scss
Labels: risk level (author): 2

#2846 ci: auto retry e2e when build not finalized
  .github/workflows/e2e.yml
Labels: risk level (author): 1, skip e2e

#2836 feat(components/datetime): add datepicker test harness
  apps/code-examples/src/app/code-examples/datetime/datepicker/basic/demo.component.html
  apps/code-examples/src/app/code-examples/datetime/datepicker/basic/demo.component.spec.ts
  apps/code-examples/src/app/code-examples/datetime/datepicker/basic/demo.component.ts
  libs/components/datetime/testing/src/datepicker/datepicker-calendar-harness.filters.ts
  libs/components/datetime/testing/src/datepicker/datepicker-calendar-harness.ts
  libs/components/datetime/testing/src/datepicker/datepicker-harness.filters.ts
  libs/components/datetime/testing/src/datepicker/datepicker-harness.spec.ts
  libs/components/datetime/testing/src/datepicker/datepicker-harness.ts
  libs/components/datetime/testing/src/public-api.ts
Labels: risk level (author): 1

#2844 chore: release 11.14.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#2847 feat(components/popovers): tokenize dropdown styles
  apps/e2e/popovers-storybook-e2e/src/e2e/dropdown.component.cy.ts
  libs/components/popovers/src/lib/modules/dropdown/dropdown-item.component.scss
  libs/components/popovers/src/lib/modules/dropdown/dropdown-menu.component.scss
  libs/components/popovers/src/lib/modules/dropdown/dropdown.component.scss
  libs/components/theme/src/lib/styles/themes/modern/_elevation.scss
Labels: risk level (author): 2

#2817 feat(components/core): allow `currencyDisplay` to be specified for `SkyNumericOptions` (Thanks @Blackbaud-MitchellThomas)
  libs/components/core/src/lib/modules/numeric/numeric.options.ts
  libs/components/core/src/lib/modules/numeric/numeric.service.spec.ts
  libs/components/core/src/lib/modules/numeric/numeric.service.ts
  libs/components/core/src/lib/modules/shared/number-format/number-format-utility.spec.ts
  libs/components/core/src/lib/modules/shared/number-format/number-format-utility.ts
  libs/components/i18n/src/lib/modules/i18n/intl-number-formatter-options.ts
  libs/components/i18n/src/lib/modules/i18n/intl-number-formatter.spec.ts
  libs/components/i18n/src/lib/modules/i18n/intl-number-formatter.ts
Labels: risk level (author): 2

#2854 build: flip build dependency for testing projects
  libs/components/a11y/project.json
  libs/components/a11y/testing/project.json
  libs/components/action-bars/project.json
  libs/components/action-bars/testing/project.json
  libs/components/avatar/project.json
  libs/components/avatar/testing/project.json
  libs/components/colorpicker/project.json
  libs/components/colorpicker/testing/project.json
  libs/components/core/project.json
  libs/components/core/testing/project.json
  libs/components/datetime/project.json
  libs/components/datetime/testing/project.json
  libs/components/errors/project.json
  libs/components/errors/testing/project.json
  libs/components/forms/project.json
  libs/components/forms/testing/project.json
  libs/components/help-inline/project.json
  libs/components/help-inline/testing/project.json
  libs/components/icon/project.json
  libs/components/icon/testing/project.json
  libs/components/indicators/project.json
  libs/components/indicators/testing/project.json
  libs/components/layout/project.json
  libs/components/layout/testing/project.json
  libs/components/list-builder-view-checklist/project.json
  libs/components/list-builder-view-checklist/testing/project.json
  libs/components/list-builder-view-grids/project.json
  libs/components/list-builder-view-grids/testing/project.json
  libs/components/lists/project.json
  libs/components/lists/testing/project.json
  libs/components/lookup/project.json
  libs/components/lookup/testing/project.json
  libs/components/modals/project.json
  libs/components/modals/testing/project.json
  libs/components/pages/project.json
  libs/components/pages/testing/project.json
  libs/components/phone-field/project.json
  libs/components/phone-field/testing/project.json
  libs/components/popovers/project.json
  libs/components/popovers/testing/project.json
  libs/components/progress-indicator/project.json
  libs/components/progress-indicator/testing/project.json
  libs/components/router/project.json
  libs/components/router/testing/project.json
  libs/components/split-view/project.json
  libs/components/split-view/testing/project.json
  libs/components/tabs/project.json
  libs/components/tabs/testing/project.json
  libs/components/toast/project.json
  libs/components/toast/testing/project.json
  libs/sdk/tools/src/generators/update-dependencies/__snapshots__/generator.spec.ts.snap
  libs/sdk/tools/src/generators/update-dependencies/generator.spec.ts
  libs/sdk/tools/src/generators/update-dependencies/generator.ts
  libs/sdk/tools/src/generators/update-dependencies/schema.json
Labels: risk level (author): 1

#2850 feat(components/tabs): tokenize tabs styling
  apps/e2e/tabs-storybook-e2e/src/e2e/tabs.component.cy.ts
  apps/e2e/tabs-storybook/project.json
  apps/playground/src/app/components/modal/modal-visual.component.html
  apps/playground/src/app/components/modal/modal-visual.component.ts
  apps/playground/src/app/components/modal/modal-with-tabs.component.html
  apps/playground/src/app/components/modal/modal-with-tabs.component.ts
  libs/components/popovers/src/lib/modules/dropdown/dropdown.component.scss
  libs/components/tabs/src/lib/modules/tabs/tab-button.component.scss
  libs/components/tabs/src/lib/modules/tabs/tabset.component.html
  libs/components/tabs/src/lib/modules/tabs/tabset.component.scss
  libs/components/tabs/src/lib/modules/tabs/tabset.component.spec.ts
  libs/components/theme/package.json
  libs/components/theme/src/lib/styles/_buttons.scss
  libs/components/theme/src/lib/styles/_layout-host.scss
  libs/components/theme/src/lib/styles/themes/modern/_buttons.scss
  package-lock.json
  package.json
Labels: risk level (author): 3

#2853 feat(components/lists): tokenize sort styles
  apps/e2e/lists-storybook-e2e/src/e2e/sort.component.cy.ts
  apps/e2e/lists-storybook/project.json
  libs/components/forms/src/lib/modules/input-box/input-box.component.scss
  libs/components/lists/src/lib/modules/sort/sort-item.component.html
  libs/components/lists/src/lib/modules/sort/sort-item.component.scss
  libs/components/lists/src/lib/modules/sort/sort-menu-heading.component.scss
  libs/components/lists/src/lib/modules/sort/sort.component.scss
Labels: risk level (author): 2

#2855 feat(components/theme): tokenize border, sizing, and elevation styles
  apps/e2e/theme-storybook-e2e/src/e2e/borders.component.cy.ts
  libs/components/theme/package.json
  libs/components/theme/src/lib/styles/_borders.scss
  libs/components/theme/src/lib/styles/themes/modern/_borders.scss
  libs/components/theme/src/lib/styles/themes/modern/_elevation.scss
  libs/components/theme/src/lib/styles/themes/modern/_sizing.scss
  libs/components/theme/src/lib/styles/themes/modern/styles.scss
  package-lock.json
  package.json
Labels: risk level (author): 2

#2851 test(components/core): add test harness utility
  libs/components/core/testing/src/public-api.ts
  libs/components/core/testing/src/shared/harness-utility.spec.ts
  libs/components/core/testing/src/shared/harness-utility.ts
Labels: risk level (author): 1

#2848 chore: release 11.15.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#2856 fix(components/theme): remove anchor tag tokens which changed css specificity
  apps/playground/src/app/components/theme/buttons/buttons.component.html
  libs/components/theme/src/lib/styles/themes/modern/_theme.scss
Labels: risk level (author): 2

#2857 chore: release 11.15.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#2858 build: use build target `dependsOn` rather than `implicitDependencies`
  libs/components/a11y/project.json
  libs/components/a11y/testing/project.json
  libs/components/action-bars/project.json
  libs/components/action-bars/testing/project.json
  libs/components/avatar/testing/project.json
  libs/components/colorpicker/project.json
  libs/components/colorpicker/testing/project.json
  libs/components/datetime/project.json
  libs/components/datetime/testing/project.json
  libs/components/errors/testing/project.json
  libs/components/forms/project.json
  libs/components/forms/testing/project.json
  libs/components/help-inline/project.json
  libs/components/help-inline/testing/project.json
  libs/components/icon/project.json
  libs/components/icon/testing/project.json
  libs/components/indicators/project.json
  libs/components/indicators/testing/project.json
  libs/components/layout/project.json
  libs/components/layout/testing/project.json
  libs/components/list-builder-view-checklist/testing/project.json
  libs/components/list-builder-view-grids/testing/project.json
  libs/components/lists/project.json
  libs/components/lists/testing/project.json
  libs/components/lookup/project.json
  libs/components/lookup/testing/project.json
  libs/components/modals/project.json
  libs/components/modals/testing/project.json
  libs/components/pages/project.json
  libs/components/pages/testing/project.json
  libs/components/phone-field/project.json
  libs/components/phone-field/testing/project.json
  libs/components/popovers/project.json
  libs/components/popovers/testing/project.json
  libs/components/progress-indicator/project.json
  libs/components/progress-indicator/testing/project.json
  libs/components/router/project.json
  libs/components/router/testing/project.json
  libs/components/split-view/project.json
  libs/components/split-view/testing/project.json
  libs/components/tabs/testing/project.json
  libs/components/toast/testing/project.json
  libs/sdk/tools/src/generators/update-dependencies/__snapshots__/generator.spec.ts.snap
  libs/sdk/tools/src/generators/update-dependencies/generator.spec.ts
  libs/sdk/tools/src/generators/update-dependencies/generator.ts
Labels: risk level (author): 1

#2860 test: add errors and forms harnesses
  libs/components/errors/project.json
  libs/components/errors/testing/src/error-modal/error-modal-harness.spec.ts
  libs/components/errors/testing/src/error-modal/error-modal-harness.ts
  libs/components/errors/testing/src/public-api.ts
  libs/components/forms/testing/src/file-drop/file-drop-harness-filters.ts
  libs/components/forms/testing/src/file-drop/file-drop-harness.spec.ts
  libs/components/forms/testing/src/file-drop/file-drop-harness.ts
  libs/components/forms/testing/src/public-api.ts
Labels: risk level (author): 1

#2859 feat(components/forms): tokenize character counter styles
  apps/e2e/forms-storybook-e2e/src/e2e/character-counter.component.cy.ts
  apps/playground/src/app/components/forms/input-box/input-box.component.html
  libs/components/forms/src/lib/modules/character-counter/character-counter-indicator.component.html
  libs/components/forms/src/lib/modules/character-counter/character-counter-indicator.component.scss
  libs/components/forms/src/lib/modules/input-box/input-box.component.scss
  libs/components/theme/src/lib/styles/themes/modern/_forms.scss
Labels: risk level (author): 2

#2864 build: fix dependency graph for testing projects
  libs/components/a11y/project.json
  libs/components/a11y/testing/project.json
  libs/components/action-bars/project.json
  libs/components/action-bars/testing/project.json
  libs/components/avatar/project.json
  libs/components/avatar/testing/project.json
  libs/components/colorpicker/project.json
  libs/components/colorpicker/testing/project.json
  libs/components/core/project.json
  libs/components/core/testing/project.json
  libs/components/datetime/project.json
  libs/components/datetime/testing/project.json
  libs/components/errors/project.json
  libs/components/errors/testing/project.json
  libs/components/forms/project.json
  libs/components/forms/testing/project.json
  libs/components/help-inline/project.json
  libs/components/help-inline/testing/project.json
  libs/components/icon/project.json
  libs/components/icon/testing/project.json
  libs/components/indicators/project.json
  libs/components/indicators/testing/project.json
  libs/components/layout/project.json
  libs/components/layout/testing/project.json
  libs/components/list-builder-view-checklist/project.json
  libs/components/list-builder-view-checklist/testing/project.json
  libs/components/list-builder-view-grids/project.json
  libs/components/list-builder-view-grids/testing/project.json
  libs/components/lists/project.json
  libs/components/lists/testing/project.json
  libs/components/lookup/project.json
  libs/components/lookup/testing/project.json
  libs/components/modals/project.json
  libs/components/modals/testing/project.json
  libs/components/pages/project.json
  libs/components/pages/testing/project.json
  libs/components/phone-field/project.json
  libs/components/phone-field/testing/project.json
  libs/components/popovers/project.json
  libs/components/popovers/testing/project.json
  libs/components/progress-indicator/project.json
  libs/components/progress-indicator/testing/project.json
  libs/components/router/project.json
  libs/components/router/testing/project.json
  libs/components/split-view/project.json
  libs/components/split-view/testing/project.json
  libs/components/tabs/project.json
  libs/components/tabs/testing/project.json
  libs/components/toast/project.json
  libs/components/toast/testing/project.json
  libs/sdk/tools/src/generators/update-dependencies/__snapshots__/generator.spec.ts.snap
  libs/sdk/tools/src/generators/update-dependencies/generator.ts
  nx.json
Labels: risk level (author): 1

#2861 feat(components/lookup): add `getControl()` method to the autocomplete test harness
  libs/components/core/testing/src/public-api.ts
  libs/components/core/testing/src/shared/input-harness.spec.ts
  libs/components/core/testing/src/shared/input-harness.ts
  libs/components/lookup/testing/src/autocomplete/autocomplete-harness.spec.ts
  libs/components/lookup/testing/src/autocomplete/autocomplete-harness.ts
  libs/components/lookup/testing/src/autocomplete/autocomplete-input-harness.ts
Labels: risk level (author): 1

#2840 feat(components/avatar): add avatar test harness
  apps/code-examples/src/app/code-examples/avatar/avatar/demo.component.html
  apps/code-examples/src/app/code-examples/avatar/avatar/demo.component.spec.ts
  apps/code-examples/src/app/code-examples/avatar/avatar/demo.component.ts
  apps/code-examples/src/app/code-examples/avatar/avatar/demo.service.ts
  libs/components/avatar/package.json
  libs/components/avatar/testing/src/avatar/avatar-harness-filters.ts
  libs/components/avatar/testing/src/avatar/avatar-harness.spec.ts
  libs/components/avatar/testing/src/avatar/avatar-harness.ts
  libs/components/avatar/testing/src/public-api.ts
Labels: risk level (author): 1

#2863 feat(components/forms): tokenize field group styles
  apps/e2e/forms-storybook-e2e/src/e2e/field-group/field-group.component.cy.ts
  libs/components/forms/src/lib/modules/field-group/field-group.component.html
  libs/components/forms/src/lib/modules/field-group/field-group.component.scss
  libs/components/forms/src/lib/modules/field-group/field-group.component.ts
  libs/components/forms/testing/src/field-group/field-group-harness.ts
Labels: risk level (author): 1

#2862 chore: release 11.16.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#2865 feat(components/forms): tokenize toggle switch styles
  apps/e2e/forms-storybook-e2e/src/e2e/toggle-switch.component.cy.ts
  libs/components/forms/src/lib/modules/toggle-switch/toggle-switch.component.scss
Labels: risk level (author): 2

#2870 fix(components/lookup): fix lookup component to emit `valueChanges` only once per change
  libs/components/lookup/src/lib/modules/lookup/lookup.component.spec.ts
  libs/components/lookup/src/lib/modules/lookup/lookup.component.ts
Labels: risk level (author): 2

#2871 ci(components/forms): use cypress screenshots for checkbox
  apps/e2e/forms-storybook-e2e/cypress.config.ts
  apps/e2e/forms-storybook-e2e/src/e2e/checkbox.component.cy.ts
  apps/e2e/forms-storybook-e2e/src/support/commands.ts
Labels: risk level (author): 1

#2866 chore: release 11.17.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#2867 fix(components/datetime): fix date range picker to emit `valueChanges` only once per change
  apps/e2e/datetime-storybook/src/app/date-range-picker/date-range-picker.component.ts
  apps/playground/src/app/components/datetime/date-range-picker/date-range-picker.component.html
  apps/playground/src/app/components/datetime/date-range-picker/date-range-picker.component.ts
  libs/components/datetime/src/lib/modules/date-range-picker/date-range-picker.component.html
  libs/components/datetime/src/lib/modules/date-range-picker/date-range-picker.component.spec.ts
  libs/components/datetime/src/lib/modules/date-range-picker/date-range-picker.component.ts
  libs/components/datetime/src/lib/modules/date-range-picker/types/date-range-relative-value.spec.ts
  libs/components/datetime/src/lib/modules/datepicker/datepicker.component.ts
  libs/components/datetime/src/lib/modules/datepicker/daypicker.component.html
  libs/components/datetime/src/lib/modules/datepicker/monthpicker.component.html
  libs/components/datetime/src/lib/modules/datepicker/yearpicker.component.html
Labels: risk level (author): 3

#2875 ci: add types to datetime to satisfy `typedoc` build
  libs/components/datetime/src/lib/modules/date-range-picker/date-range-picker.component.ts
  package-lock.json
Labels: risk level (author): 1

#2790 docs(components/lookup): update lookup harness docs
  libs/components/lookup/testing/src/lookup/lookup-harness.spec.ts
  libs/components/lookup/testing/src/lookup/lookup-harness.ts
  libs/components/lookup/testing/src/lookup/lookup-search-result-harness-filters.ts
  libs/components/lookup/testing/src/lookup/lookup-search-result-harness.ts
Labels: risk level (author): 1, risk level (reviewer): 1

#2876 fix(components/lookup): selection modal choices satisfy the required state of the lookup component
  apps/playground/src/app/components/lookup/lookup/lookup.component.html
  libs/components/lookup/src/lib/modules/lookup/lookup.component.spec.ts
  libs/components/lookup/src/lib/modules/lookup/lookup.component.ts
Labels: risk level (author): 2

#2874 feat(components/forms): tokenize radio styles
  apps/e2e/forms-storybook-e2e/src/e2e/radio-button.component.cy.ts
  libs/components/forms/src/lib/modules/checkbox/checkbox-group.component.html
  libs/components/forms/src/lib/modules/checkbox/checkbox-group.component.ts
  libs/components/forms/src/lib/modules/checkbox/checkbox.component.html
  libs/components/forms/src/lib/modules/checkbox/checkbox.modern.component.scss
  libs/components/forms/src/lib/modules/checkbox/checkbox.module.ts
  libs/components/forms/src/lib/modules/radio/radio-group.component.html
  libs/components/forms/src/lib/modules/radio/radio-group.component.scss
  libs/components/forms/src/lib/modules/radio/radio-group.component.spec.ts
  libs/components/forms/src/lib/modules/radio/radio-group.component.ts
  libs/components/forms/src/lib/modules/radio/radio.component.html
  libs/components/forms/src/lib/modules/radio/radio.component.scss
  libs/components/forms/src/lib/modules/radio/radio.component.ts
  libs/components/forms/src/lib/modules/radio/radio.module.ts
  libs/components/forms/src/lib/modules/toggle-switch/toggle-switch.component.scss
  libs/components/forms/testing/src/radio/radio-group-harness.ts
  libs/components/theme/package.json
  libs/components/theme/src/lib/styles/_switch.scss
  libs/components/theme/src/lib/styles/themes/modern/_switch.scss
  package-lock.json
  package.json
Labels: risk level (author): 2

#2878 fix(components/angular-tree-component): handle key event when node is not passed
  libs/components/angular-tree-component/src/lib/modules/angular-tree/angular-tree-wrapper.component.ts
Labels: risk level (author): 1

#2849 feat(components/phone-field): add phone field test harness
  apps/code-examples/src/app/code-examples/phone-field/phone-field/basic/demo.component.html
  apps/code-examples/src/app/code-examples/phone-field/phone-field/basic/demo.component.spec.ts
  apps/code-examples/src/app/code-examples/phone-field/phone-field/basic/demo.component.ts
  libs/components/phone-field/testing/src/phonefield/fixtures/phone-field-harness-test.component.ts
  libs/components/phone-field/testing/src/phonefield/phone-field-harness-filters.ts
  libs/components/phone-field/testing/src/phonefield/phone-field-harness.spec.ts
  libs/components/phone-field/testing/src/phonefield/phone-field-harness.ts
  libs/components/phone-field/testing/src/phonefield/phone-field-input-harness.ts
  libs/components/phone-field/testing/src/public-api.ts
Labels: risk level (author): 1

#2881 feat(components/theme): tokenize body font size
  libs/components/theme/src/lib/styles/themes/modern/_theme.scss
Labels: risk level (author): 1
