Repository blackbaud/skyux, pull requests merged in 2024-08, with the labels that each got.

#2568 chore: release 10.41.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease 10.x.x: pending

#2578 chore: changelog for 10.41.0 (#2568) 🍒
  CHANGELOG.md
Labels: risk level (author): 1, risk level (reviewer): 1

#2569 chore: release 11.0.0-alpha.8
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#2580 fix(components/router): fix `SkyHrefHarness` to find elements when `skyHref` is bound to a template variable
  libs/components/router/testing/src/href/fixtures/href-harness-test.component.html
  libs/components/router/testing/src/href/fixtures/href-harness-test.component.ts
  libs/components/router/testing/src/href/href-harness.spec.ts
  libs/components/router/testing/src/href/href-harness.ts
Labels: risk level (author): 1

#2582 chore: release 10.41.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease 10.x.x: pending

#2581 fix(components/router): fix `SkyHrefHarness` to find elements when `skyHref` is bound to a template variable (#2580)
  libs/components/router/testing/src/href/fixtures/href-harness-test.component.html
  libs/components/router/testing/src/href/fixtures/href-harness-test.component.ts
  libs/components/router/testing/src/href/href-harness.spec.ts
  libs/components/router/testing/src/href/href-harness.ts
Labels: risk level (author): 1

#2583 chore: changelog for 10.41.1 (#2582) 🍒
  CHANGELOG.md
Labels: risk level (author): 1, risk level (reviewer): 1

#2588 test: add ESLint rules from `@angular-eslint/template`
  .eslintrc-overrides.json
  libs/components/tiles/src/lib/modules/tiles/tile/tile.component.html
Labels: risk level (author): 1

#2589 test: add ESLint rules from `@angular-eslint/template` (#2588)
  .eslintrc-overrides.json
  libs/components/tiles/src/lib/modules/tiles/tile/tile.component.html
Labels: risk level (author): 1

#2579 feat(components/packages): update schematic for AG Grid 32
  libs/components/packages/collection.json
  libs/components/packages/src/schematics/migrations/update-11/ag-grid/__snapshots__/ag-grid.schematic.spec.ts.snap
  libs/components/packages/src/schematics/migrations/update-11/ag-grid/ag-grid.schematic.spec.ts
  libs/components/packages/src/schematics/migrations/update-11/ag-grid/ag-grid.schematic.ts
  libs/components/packages/src/schematics/migrations/update-11/ag-grid/event-type-strings/event-type-strings.spec.ts
  libs/components/packages/src/schematics/migrations/update-11/ag-grid/event-type-strings/event-type-strings.ts
  libs/components/packages/src/schematics/migrations/update-11/ag-grid/schema.json
  libs/components/packages/src/schematics/migrations/update-11/ag-grid/switch-to-update-grid-options/switch-to-update-grid-options.spec.ts
  libs/components/packages/src/schematics/migrations/update-11/ag-grid/switch-to-update-grid-options/switch-to-update-grid-options.ts
  libs/components/packages/src/schematics/utility/typescript/remove-import.spec.ts
  libs/components/packages/src/schematics/utility/typescript/remove-import.ts
  libs/components/packages/src/schematics/utility/typescript/swap-imported-class.spec.ts
  libs/components/packages/src/schematics/utility/typescript/swap-imported-class.ts
Labels: risk level (author): 1

#2592 fix(components/indicators): add exports from `icon` and `help-inline`
  libs/components/indicators/src/index.ts
Labels: risk level (author): 1

#2591 fix(components/colorpicker): match label text to easy mode label styling
  apps/playground/src/app/components/colorpicker/colorpicker/colorpicker.component.html
  libs/components/colorpicker/src/lib/modules/colorpicker/colorpicker.component.html
  libs/components/colorpicker/src/lib/modules/colorpicker/colorpicker.component.scss
Labels: risk level (author): 1

#2597 fix(components/icon): icon package is a peer dependency when used in other packages
  libs/components/action-bars/package.json
  libs/components/ag-grid/package.json
  libs/components/angular-tree-component/package.json
  libs/components/colorpicker/package.json
  libs/components/datetime/package.json
  libs/components/flyout/package.json
  libs/components/forms/package.json
  libs/components/grids/package.json
  libs/components/help-inline/package.json
  libs/components/layout/package.json
  libs/components/list-builder-view-grids/package.json
  libs/components/list-builder/package.json
  libs/components/lists/package.json
  libs/components/lookup/package.json
  libs/components/modals/package.json
  libs/components/pages/package.json
  libs/components/phone-field/package.json
  libs/components/popovers/package.json
  libs/components/progress-indicator/package.json
  libs/components/select-field/package.json
  libs/components/split-view/package.json
  libs/components/tabs/package.json
  libs/components/text-editor/package.json
  libs/components/tiles/package.json
  libs/components/toast/package.json
Labels: risk level (author): 2

#2590 fix(components/forms): fix field group `labelText` inputs to work with async pipe
  apps/playground/src/app/components/forms/field-group/field-group.component.html
  apps/playground/src/app/components/forms/field-group/field-group.component.ts
  libs/components/datetime/src/lib/modules/date-range-picker/date-range-picker.component.ts
  libs/components/forms/src/index.ts
  libs/components/forms/src/lib/modules/checkbox/checkbox.component.ts
  libs/components/forms/src/lib/modules/file-attachment/file-attachment.component.ts
  libs/components/forms/src/lib/modules/file-attachment/file-drop.component.ts
  libs/components/forms/src/lib/modules/input-box/input-box.component.ts
  libs/components/forms/src/lib/modules/radio/radio-group.component.ts
  libs/components/forms/src/lib/modules/radio/radio.component.ts
  libs/components/forms/src/lib/modules/shared/form-field-label-text-required.directive.spec.ts
  libs/components/forms/src/lib/modules/shared/form-field-label-text-required.directive.ts
  libs/components/forms/src/lib/modules/shared/form-field-label-text-required.service.spec.ts
  libs/components/forms/src/lib/modules/shared/form-field-label-text-required.service.ts
  libs/components/forms/src/lib/modules/toggle-switch/toggle-switch.component.ts
  libs/components/text-editor/src/lib/modules/text-editor/text-editor.component.ts
Labels: risk level (author): 1

#2594 fix(components/colorpicker): match label text to easy mode label styling (#2591)
  apps/playground/src/app/components/colorpicker/colorpicker/colorpicker.component.html
  libs/components/colorpicker/src/lib/modules/colorpicker/colorpicker.component.html
  libs/components/colorpicker/src/lib/modules/colorpicker/colorpicker.component.scss
Labels: risk level (author): 1

#2599 fix(components/pages): use CSP_NONCE when creating style elements
  libs/components/pages/src/lib/modules/page/page-theme-adapter.service.spec.ts
  libs/components/pages/src/lib/modules/page/page-theme-adapter.service.ts
Labels: risk level (author): 1

#2601 fix(components/pages): use CSP_NONCE when creating style elements (#2599)
  libs/components/pages/src/lib/modules/page/page-theme-adapter.service.spec.ts
  libs/components/pages/src/lib/modules/page/page-theme-adapter.service.ts
Labels: risk level (author): 1

#2600 fix(components/forms): fix field group `labelText` inputs to work with async pipe (#2590)
  apps/playground/src/app/components/forms/field-group/field-group.component.html
  apps/playground/src/app/components/forms/field-group/field-group.component.ts
  libs/components/datetime/src/lib/modules/date-range-picker/date-range-picker.component.ts
  libs/components/forms/src/index.ts
  libs/components/forms/src/lib/modules/checkbox/checkbox.component.ts
  libs/components/forms/src/lib/modules/file-attachment/file-attachment/file-attachment.component.ts
  libs/components/forms/src/lib/modules/file-attachment/file-drop/file-drop.component.ts
  libs/components/forms/src/lib/modules/input-box/input-box.component.ts
  libs/components/forms/src/lib/modules/radio/radio-group.component.ts
  libs/components/forms/src/lib/modules/radio/radio.component.ts
  libs/components/forms/src/lib/modules/shared/form-field-label-text-required.directive.spec.ts
  libs/components/forms/src/lib/modules/shared/form-field-label-text-required.directive.ts
  libs/components/forms/src/lib/modules/shared/form-field-label-text-required.service.spec.ts
  libs/components/forms/src/lib/modules/shared/form-field-label-text-required.service.ts
  libs/components/forms/src/lib/modules/toggle-switch/toggle-switch.component.ts
  libs/components/text-editor/src/lib/modules/text-editor/text-editor.component.ts
Labels: risk level (author): 1

#2595 chore: release 10.41.2
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease 10.x.x: pending

#2604 chore: changelog for 10.41.2 (#2595) 🍒
  CHANGELOG.md
Labels: risk level (author): 1, risk level (reviewer): 1

#2584 chore: release 11.0.0-alpha.9
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#2596 fix: `sky-form-errors` is no longer created and destroyed when form errors are present
  libs/components/colorpicker/src/lib/modules/colorpicker/colorpicker.component.html
  libs/components/datetime/src/lib/modules/date-range-picker/date-range-picker.component.html
  libs/components/datetime/src/lib/modules/date-range-picker/date-range-picker.component.spec.ts
  libs/components/forms/src/assets/locales/resources_en_US.json
  libs/components/forms/src/lib/modules/checkbox/checkbox-group.component.html
  libs/components/forms/src/lib/modules/checkbox/checkbox.component.html
  libs/components/forms/src/lib/modules/checkbox/checkbox.default.component.scss
  libs/components/forms/src/lib/modules/checkbox/checkbox.modern.component.scss
  libs/components/forms/src/lib/modules/file-attachment/file-attachment.component.html
  libs/components/forms/src/lib/modules/file-attachment/file-drop.component.html
  libs/components/forms/src/lib/modules/form-error/form-errors.component.html
  libs/components/forms/src/lib/modules/form-error/form-errors.component.scss
  libs/components/forms/src/lib/modules/radio/radio-group.component.html
  libs/components/forms/src/lib/modules/shared/sky-forms-resources.module.ts
  libs/components/forms/testing/src/checkbox/checkbox-group-harness.ts
  libs/components/forms/testing/src/checkbox/checkbox-harness.ts
  libs/components/text-editor/src/lib/modules/text-editor/text-editor.component.html
  libs/components/text-editor/src/lib/modules/text-editor/text-editor.component.spec.ts
Labels: risk level (author): 1

#2606 fix: `sky-form-errors` is no longer created and destroyed when form errors are present (#2596)
  libs/components/colorpicker/src/lib/modules/colorpicker/colorpicker.component.html
  libs/components/datetime/src/lib/modules/date-range-picker/date-range-picker.component.html
  libs/components/datetime/src/lib/modules/date-range-picker/date-range-picker.component.spec.ts
  libs/components/forms/src/assets/locales/resources_en_US.json
  libs/components/forms/src/lib/modules/checkbox/checkbox-group.component.html
  libs/components/forms/src/lib/modules/checkbox/checkbox.component.html
  libs/components/forms/src/lib/modules/checkbox/checkbox.default.component.scss
  libs/components/forms/src/lib/modules/checkbox/checkbox.modern.component.scss
  libs/components/forms/src/lib/modules/file-attachment/file-attachment/file-attachment.component.html
  libs/components/forms/src/lib/modules/file-attachment/file-drop/file-drop.component.html
  libs/components/forms/src/lib/modules/form-error/form-errors.component.html
  libs/components/forms/src/lib/modules/form-error/form-errors.component.scss
  libs/components/forms/src/lib/modules/radio/radio-group.component.html
  libs/components/forms/src/lib/modules/shared/sky-forms-resources.module.ts
  libs/components/forms/testing/src/checkbox/checkbox-group-harness.ts
  libs/components/forms/testing/src/checkbox/checkbox-harness.ts
  libs/components/text-editor/src/lib/modules/text-editor/text-editor.component.html
  libs/components/text-editor/src/lib/modules/text-editor/text-editor.component.spec.ts
Labels: risk level (author): 1

#2603 feat(components/forms): update `sky-file-attachment` component to use `ControlValueAccessor`; deprecate `validateFn` attribute in favor of custom form control validators; deprecate `fileChange` event in favor of form control `valueChanges` observable
  apps/code-examples/src/app/code-examples/forms/file-attachment/basic/demo.component.html
  apps/code-examples/src/app/code-examples/forms/file-attachment/basic/demo.component.ts
  libs/components/forms/src/lib/modules/file-attachment/file-attachment/file-attachment-join-ids.pipe.ts
  libs/components/forms/src/lib/modules/file-attachment/file-attachment/file-attachment.component.html
  libs/components/forms/src/lib/modules/file-attachment/file-attachment/file-attachment.component.spec.ts
  libs/components/forms/src/lib/modules/file-attachment/file-attachment/file-attachment.component.ts
Labels: risk level (author): 2

#2598 feat!: remove compat variables for previous compat stylesheets
  libs/components/forms/src/lib/modules/selection-box/selection-box-grid.component.scss
  libs/components/layout/src/lib/modules/action-button/action-button-container.default.component.scss
  libs/components/layout/src/lib/modules/description-list/description-list.component.scss
  libs/components/layout/src/lib/modules/text-expand-repeater/text-expand-repeater.component.scss
  libs/components/modals/src/lib/modules/modal/modal-footer.component.scss
  libs/components/pages/src/lib/modules/action-hub/action-hub.component.scss
  libs/components/pages/src/lib/modules/page-header/page-header.component.scss
  libs/components/tabs/src/lib/modules/sectioned-form/sectioned-form.component.scss
  libs/components/tabs/src/lib/modules/tabs/tabset.component.scss
  libs/components/tabs/src/lib/modules/vertical-tabset/vertical-tabset.component.scss
  libs/components/theme/src/lib/styles/_forms.scss
  libs/components/theme/src/lib/styles/themes/modern/_theme.scss
Labels: risk level (author): 2

#2593 fix(components/phone-field): phone numbers validate when selected country is changed programmatically
  apps/playground/src/app/components/phone-field/phone-field/phone-field.component.html
  apps/playground/src/app/components/phone-field/phone-field/phone-field.component.scss
  apps/playground/src/app/components/phone-field/phone-field/phone-field.component.ts
  libs/components/phone-field/src/lib/modules/phone-field/fixtures/phone-field-input-box.component.fixture.html
  libs/components/phone-field/src/lib/modules/phone-field/fixtures/phone-field-input-box.component.fixture.ts
  libs/components/phone-field/src/lib/modules/phone-field/phone-field-input.directive.ts
  libs/components/phone-field/src/lib/modules/phone-field/phone-field.component.spec.ts
  libs/components/phone-field/src/lib/modules/phone-field/phone-field.component.ts
Labels: risk level (author): 2

#2608 feat(components/forms): file attachment automatically creates download link for file uploads
  libs/components/forms/src/lib/modules/file-attachment/file-attachment/file-attachment.component.html
  libs/components/forms/src/lib/modules/file-attachment/file-attachment/file-attachment.component.scss
  libs/components/forms/src/lib/modules/file-attachment/file-attachment/file-attachment.component.spec.ts
  libs/components/forms/src/lib/modules/file-attachment/file-attachment/file-attachment.component.ts
Labels: risk level (author): 5

#2609 fix(components/phone-field): phone numbers validate when selected country is changed programmatically (#2593)
  apps/playground/src/app/components/phone-field/phone-field/phone-field.component.html
  apps/playground/src/app/components/phone-field/phone-field/phone-field.component.scss
  apps/playground/src/app/components/phone-field/phone-field/phone-field.component.ts
  libs/components/phone-field/src/lib/modules/phone-field/fixtures/phone-field-input-box.component.fixture.html
  libs/components/phone-field/src/lib/modules/phone-field/fixtures/phone-field-input-box.component.fixture.ts
  libs/components/phone-field/src/lib/modules/phone-field/phone-field-input.directive.ts
  libs/components/phone-field/src/lib/modules/phone-field/phone-field.component.spec.ts
  libs/components/phone-field/src/lib/modules/phone-field/phone-field.component.ts
Labels: risk level (author): 2

#2610 fix(components/lookup): autocomplete and lookup show wait in dropdown when using an async search when no dropdown was previously open
  apps/playground/src/app/components/lookup/lookup/lookup.component.html
  libs/components/lookup/src/lib/modules/autocomplete/autocomplete.component.spec.ts
  libs/components/lookup/src/lib/modules/autocomplete/autocomplete.component.ts
Labels: risk level (author): 2

#2605 chore: release 10.41.3
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease 10.x.x: pending

#2612 chore: changelog for 10.41.3 (#2605) 🍒
  CHANGELOG.md
Labels: risk level (author): 1, risk level (reviewer): 1

#2611 fix(components/lookup): autocomplete and lookup show wait in dropdown when using an async search when no dropdown was previously open (#2610)
  apps/playground/src/app/components/lookup/lookup/lookup.component.html
  libs/components/lookup/src/lib/modules/autocomplete/autocomplete.component.spec.ts
  libs/components/lookup/src/lib/modules/autocomplete/autocomplete.component.ts
Labels: risk level (author): 2

#2615 feat(components/ag-grid): option for hidden column heading
  apps/code-examples/src/app/code-examples/ag-grid/data-entry-grid/basic/demo.component.ts
  apps/code-examples/src/app/code-examples/ag-grid/data-entry-grid/data-manager-added/view-grid.component.ts
  apps/code-examples/src/app/code-examples/ag-grid/data-entry-grid/inline-help/demo.component.ts
  apps/playground/src/app/components/ag-grid/readonly-grid/readonly-grid.component.ts
  libs/components/ag-grid/src/assets/locales/resources_en_US.json
  libs/components/ag-grid/src/lib/modules/ag-grid/ag-grid.service.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/fixtures/ag-grid.component.fixture.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/header/header.component.html
  libs/components/ag-grid/src/lib/modules/ag-grid/header/header.component.spec.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/header/header.component.ts
  libs/components/ag-grid/src/lib/modules/shared/sky-ag-grid-resources.module.ts
Labels: risk level (author): 1

#2617 deprecation(components/lookup): lookup component's `data` input has been deprecated and consumers should use the `searchAsync` event instead
  libs/components/lookup/src/lib/modules/lookup/lookup-autocomplete-adapter.ts
  libs/components/lookup/src/lib/modules/lookup/lookup.component.ts
Labels: risk level (author): 1

#2618 deprecation(components/lookup): lookup component's `data` input has been deprecated and consumers should use the `searchAsync` event instead (#2617)
  libs/components/lookup/src/lib/modules/lookup/lookup-autocomplete-adapter.ts
  libs/components/lookup/src/lib/modules/lookup/lookup.component.ts
Labels: risk level (author): 1

#2616 chore: skyux-dev-infra 10.0.0-alpha.10
  package-lock.json
  package.json
Labels: risk level (author): 1

#2614 chore: skyux-dev-infra 10.0.0-alpha.10
  package-lock.json
  package.json
Labels: risk level (author): 1

#2620 feat(components/ag-grid): remove enter key navigation in cell editors
  libs/components/ag-grid/src/lib/modules/ag-grid/ag-grid.service.ts
Labels: risk level (author): 1

#2623 feat(components/packages): warn when using ssr
  libs/components/packages/src/schematics/migrations/migration-collection.json
  libs/components/packages/src/schematics/migrations/update-11/workspace-check/workspace-check.schematic.spec.ts
  libs/components/packages/src/schematics/migrations/update-11/workspace-check/workspace-check.schematic.ts
  libs/components/packages/src/schematics/ng-add/ng-add.schematic.ts
  libs/components/packages/src/schematics/rules/workspace-check/workspace-check.spec.ts
  libs/components/packages/src/schematics/rules/workspace-check/workspace-check.ts
  libs/components/packages/src/schematics/testing/scaffold.ts
Labels: risk level (author): 1

#2622 fix(components/ag-grid): focused cell link outline
  apps/e2e/ag-grid-storybook/src/app/data-manager/data-manager.component.html
  apps/e2e/ag-grid-storybook/src/app/data-manager/data-manager.component.ts
  apps/e2e/ag-grid-storybook/src/app/shared/baseball-players-data.ts
  libs/components/ag-grid/src/lib/styles/_base.scss
Labels: risk level (author): 1

#2621 fix(code-examples): update lookup code examples to all use the `searchAsync` event
  apps/code-examples/src/app/code-examples/lookup/lookup/add-item/demo.component.html
  apps/code-examples/src/app/code-examples/lookup/lookup/async/demo.component.html
  apps/code-examples/src/app/code-examples/lookup/lookup/async/demo.component.spec.ts
  apps/code-examples/src/app/code-examples/lookup/lookup/async/demo.component.ts
  apps/code-examples/src/app/code-examples/lookup/lookup/async/person.ts
  apps/code-examples/src/app/code-examples/lookup/lookup/custom-picker/demo.component.html
  apps/code-examples/src/app/code-examples/lookup/lookup/custom-picker/demo.component.spec.ts
  apps/code-examples/src/app/code-examples/lookup/lookup/custom-picker/demo.component.ts
  apps/code-examples/src/app/code-examples/lookup/lookup/custom-picker/demo.service.ts
  apps/code-examples/src/app/code-examples/lookup/lookup/custom-picker/picker-modal.component.html
  apps/code-examples/src/app/code-examples/lookup/lookup/custom-picker/picker-modal.component.scss
  apps/code-examples/src/app/code-examples/lookup/lookup/custom-picker/picker-modal.component.ts
  apps/code-examples/src/app/code-examples/lookup/lookup/custom-picker/search-results.ts
  apps/code-examples/src/app/code-examples/lookup/lookup/multi-select/demo.component.html
  apps/code-examples/src/app/code-examples/lookup/lookup/multi-select/demo.component.spec.ts
  apps/code-examples/src/app/code-examples/lookup/lookup/multi-select/demo.component.ts
  apps/code-examples/src/app/code-examples/lookup/lookup/multi-select/demo.service.ts
  apps/code-examples/src/app/code-examples/lookup/lookup/multi-select/search-results.ts
  apps/code-examples/src/app/code-examples/lookup/lookup/result-templates/demo.component.html
  apps/code-examples/src/app/code-examples/lookup/lookup/result-templates/demo.component.spec.ts
  apps/code-examples/src/app/code-examples/lookup/lookup/result-templates/demo.component.ts
  apps/code-examples/src/app/code-examples/lookup/lookup/result-templates/demo.service.ts
  apps/code-examples/src/app/code-examples/lookup/lookup/result-templates/search-results.ts
  apps/code-examples/src/app/code-examples/lookup/lookup/single-select/demo.component.html
  apps/code-examples/src/app/code-examples/lookup/lookup/single-select/demo.component.spec.ts
  apps/code-examples/src/app/code-examples/lookup/lookup/single-select/demo.component.ts
  apps/code-examples/src/app/code-examples/lookup/lookup/single-select/demo.service.ts
  apps/code-examples/src/app/code-examples/lookup/lookup/single-select/search-results.ts
  apps/code-examples/src/app/features/lookup.module.ts
  apps/code-examples/src/app/home/home.component.html
Labels: risk level (author): 1

#2619 chore: release 10.41.4
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease 10.x.x: pending

#2607 chore: release 11.0.0-alpha.10
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#2628 chore: changelog for 10.41.4 (#2619) 🍒
  CHANGELOG.md
Labels: risk level (author): 1, risk level (reviewer): 1

#2629 fix(components/packages): fix collection path to `workspace-check` schematic
  libs/components/packages/src/schematics/migrations/migration-collection.json
Labels: risk level (author): 1

#2630 chore: release 11.0.0-alpha.11
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#2613 fix(components/forms)!: remove radio button extra space on top
  apps/e2e/forms-storybook-e2e/src/e2e/checkbox.component.cy.ts
  libs/components/forms/src/lib/modules/checkbox/checkbox.default.component.scss
  libs/components/forms/src/lib/modules/checkbox/checkbox.modern.component.scss
  libs/components/forms/src/lib/modules/radio/radio.component.scss
Labels: risk level (author): 2

#2632 fix(code-examples): update lookup code examples to all use the `searchAsync` event (#2621)
  apps/code-examples/src/app/code-examples/lookup/lookup/add-item/demo.component.html
  apps/code-examples/src/app/code-examples/lookup/lookup/async/demo.component.html
  apps/code-examples/src/app/code-examples/lookup/lookup/async/demo.component.spec.ts
  apps/code-examples/src/app/code-examples/lookup/lookup/async/demo.component.ts
  apps/code-examples/src/app/code-examples/lookup/lookup/async/person.ts
  apps/code-examples/src/app/code-examples/lookup/lookup/custom-picker/demo.component.html
  apps/code-examples/src/app/code-examples/lookup/lookup/custom-picker/demo.component.spec.ts
  apps/code-examples/src/app/code-examples/lookup/lookup/custom-picker/demo.component.ts
  apps/code-examples/src/app/code-examples/lookup/lookup/custom-picker/demo.service.ts
  apps/code-examples/src/app/code-examples/lookup/lookup/custom-picker/picker-modal.component.html
  apps/code-examples/src/app/code-examples/lookup/lookup/custom-picker/picker-modal.component.scss
  apps/code-examples/src/app/code-examples/lookup/lookup/custom-picker/picker-modal.component.ts
  apps/code-examples/src/app/code-examples/lookup/lookup/custom-picker/search-results.ts
  apps/code-examples/src/app/code-examples/lookup/lookup/multi-select/demo.component.html
  apps/code-examples/src/app/code-examples/lookup/lookup/multi-select/demo.component.spec.ts
  apps/code-examples/src/app/code-examples/lookup/lookup/multi-select/demo.component.ts
  apps/code-examples/src/app/code-examples/lookup/lookup/multi-select/demo.service.ts
  apps/code-examples/src/app/code-examples/lookup/lookup/multi-select/search-results.ts
  apps/code-examples/src/app/code-examples/lookup/lookup/result-templates/demo.component.html
  apps/code-examples/src/app/code-examples/lookup/lookup/result-templates/demo.component.spec.ts
  apps/code-examples/src/app/code-examples/lookup/lookup/result-templates/demo.component.ts
  apps/code-examples/src/app/code-examples/lookup/lookup/result-templates/demo.service.ts
  apps/code-examples/src/app/code-examples/lookup/lookup/result-templates/search-results.ts
  apps/code-examples/src/app/code-examples/lookup/lookup/single-select/demo.component.html
  apps/code-examples/src/app/code-examples/lookup/lookup/single-select/demo.component.spec.ts
  apps/code-examples/src/app/code-examples/lookup/lookup/single-select/demo.component.ts
  apps/code-examples/src/app/code-examples/lookup/lookup/single-select/demo.service.ts
  apps/code-examples/src/app/code-examples/lookup/lookup/single-select/search-results.ts
  apps/code-examples/src/app/features/lookup.module.ts
  apps/code-examples/src/app/home/home.component.html
Labels: risk level (author): 1

#2634 chore: rotate nx token
  .github/workflows/ci.yml
  .github/workflows/e2e.yml
  .gitignore
  apps/e2e/angular-tree-component-storybook/project.json
  apps/e2e/text-editor-storybook/project.json
  nx.json
Labels: risk level (author): 1

#2636 chore: rotate nx token (#2634)
  .github/workflows/ci.yml
  .github/workflows/e2e.yml
  .gitignore
  apps/e2e/angular-tree-component-storybook/project.json
  apps/e2e/text-editor-storybook/project.json
  nx.json
Labels: risk level (author): 1

#2638 fix(components/packages): handle edge cases for package migration
  libs/components/packages/src/schematics/utility/move-class-to-library.spec.ts
  libs/components/packages/src/schematics/utility/move-class-to-library.ts
Labels: risk level (author): 1

#2637 feat(components/ag-grid): switch to using `setGridOption` for deprecated api calls
  libs/components/packages/src/schematics/migrations/update-11/ag-grid/ag-grid.schematic.ts
  libs/components/packages/src/schematics/migrations/update-11/ag-grid/switch-to-set-grid-option/switch-to-set-grid-option.spec.ts
  libs/components/packages/src/schematics/migrations/update-11/ag-grid/switch-to-set-grid-option/switch-to-set-grid-option.ts
  libs/components/packages/src/schematics/migrations/update-11/ag-grid/switch-to-update-grid-options/switch-to-update-grid-options.spec.ts
  libs/components/packages/src/schematics/migrations/update-11/ag-grid/switch-to-update-grid-options/switch-to-update-grid-options.ts
Labels: risk level (author): 1

#2633 feat(components/ag-grid): remember last position when tabbing in and out of the grid
  libs/components/ag-grid/src/lib/modules/ag-grid/ag-grid-adapter.service.spec.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/ag-grid-adapter.service.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/ag-grid-wrapper.component.spec.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/ag-grid-wrapper.component.ts
Labels: risk level (author): 1

#2624 fix(components/forms)!: show all first class errors on touched
  apps/playground/src/app/components/forms/single-file-attachment/single-file-attachment.component.html
  libs/components/colorpicker/src/lib/modules/colorpicker/colorpicker.component.html
  libs/components/datetime/src/lib/modules/date-range-picker/date-range-picker.component.html
  libs/components/datetime/src/lib/modules/date-range-picker/date-range-picker.component.spec.ts
  libs/components/forms/src/lib/modules/checkbox/checkbox-group.component.html
  libs/components/forms/src/lib/modules/checkbox/checkbox-group.component.spec.ts
  libs/components/forms/src/lib/modules/checkbox/checkbox.component.html
  libs/components/forms/src/lib/modules/checkbox/fixtures/standard-checkbox-group.component.ts
  libs/components/forms/src/lib/modules/file-attachment/file-attachment/file-attachment.component.html
  libs/components/forms/src/lib/modules/file-attachment/file-attachment/file-attachment.component.spec.ts
  libs/components/forms/src/lib/modules/file-attachment/file-drop/file-drop.component.html
  libs/components/forms/src/lib/modules/form-error/form-errors.component.html
  libs/components/forms/src/lib/modules/form-error/form-errors.component.spec.ts
  libs/components/forms/src/lib/modules/form-error/form-errors.component.ts
  libs/components/forms/src/lib/modules/input-box/input-box.component.html
  libs/components/forms/src/lib/modules/radio/radio-group.component.html
  libs/components/forms/testing/src/checkbox/checkbox-group-harness.spec.ts
  libs/components/forms/testing/src/checkbox/checkbox-harness.spec.ts
  libs/components/forms/testing/src/form-error/form-errors-harness.spec.ts
  libs/components/forms/testing/src/input-box/input-box-harness.spec.ts
  libs/components/text-editor/src/lib/modules/text-editor/text-editor.component.html
Labels: risk level (author): 2

#2626 refactor: use control flow syntax for switch statements
  apps/code-examples/src/app/code-examples/pages/action-hub/settings-modal.component.html
  apps/e2e/pages-storybook/src/app/action-hub/settings-modal.component.html
  libs/components/layout/src/lib/modules/action-button/action-button.component.html
  libs/components/list-builder-view-checklist/src/lib/modules/list-view-checklist/list-view-checklist.component.html
  libs/components/popovers/src/lib/modules/dropdown/dropdown.component.html
  libs/components/text-editor/src/lib/modules/text-editor/menubar/text-editor-menubar.component.html
  libs/components/text-editor/src/lib/modules/text-editor/toolbar/text-editor-toolbar.component.html
Labels: risk level (author): 2

#2631 chore: release 11.0.0-alpha.12
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#2641 fix(components/lists): selectable repeater items do not log a checkbox `label` deprecation warning
  libs/components/lists/src/lib/modules/repeater/repeater-item.component.html
Labels: risk level (author): 1

#2643 fix(components/lists): selectable repeater items do not log a checkbox `label` deprecation warning (#2641)
  libs/components/lists/src/lib/modules/repeater/repeater-item.component.html
Labels: risk level (author): 1

#2651 fix(components/packages): update `move-class-to-library` to handle partial migration
  libs/components/packages/src/schematics/utility/move-class-to-library.spec.ts
  libs/components/packages/src/schematics/utility/move-class-to-library.ts
Labels: risk level (author): 1

#2639 refactor: implement Angular control flow for `a11y`, `action-bars`, `angular-tree-component`, `avatar`, `colorpicker`, `core`, and `data-manager` libraries
  libs/components/a11y/src/lib/modules/skip-link/skip-link-host.component.html
  libs/components/a11y/src/lib/modules/skip-link/skip-link-host.component.ts
  libs/components/action-bars/src/lib/modules/summary-action-bar/actions/summary-action-bar-secondary-action.component.html
  libs/components/action-bars/src/lib/modules/summary-action-bar/actions/summary-action-bar-secondary-actions.component.html
  libs/components/action-bars/src/lib/modules/summary-action-bar/fixtures/summary-action-bar-split-view.component.fixture.html
  libs/components/action-bars/src/lib/modules/summary-action-bar/fixtures/summary-action-bar-tabs.component.fixture.html
  libs/components/action-bars/src/lib/modules/summary-action-bar/fixtures/summary-action-bar.component.fixture.html
  libs/components/action-bars/src/lib/modules/summary-action-bar/summary-action-bar.component.html
  libs/components/action-bars/testing/src/summary-action-bar/fixtures/summary-action-bar-fixture-test.component.html
  libs/components/angular-tree-component/src/lib/modules/angular-tree/angular-tree-node.component.html
  libs/components/angular-tree-component/src/lib/modules/angular-tree/angular-tree-toolbar.component.html
  libs/components/angular-tree-component/src/lib/modules/angular-tree/angular-tree-wrapper.component.html
  libs/components/angular-tree-component/src/lib/modules/angular-tree/fixtures/tree-view.fixture.component.html
  libs/components/avatar/src/lib/modules/avatar/avatar.component.html
  libs/components/avatar/src/lib/modules/avatar/avatar.inner.component.html
  libs/components/colorpicker/src/lib/modules/colorpicker/colorpicker.component.html
  libs/components/colorpicker/src/lib/modules/colorpicker/fixtures/colorpicker-reactive-component.fixture.html
  libs/components/core/src/lib/modules/dynamic-component/fixtures/dynamic-component-test.component.fixture.ts
  libs/components/core/src/lib/modules/overlay/overlay.component.html
  libs/components/core/src/lib/modules/screen-reader-label/fixtures/screen-reader-label.directive.fixture.ts
  libs/components/core/src/lib/modules/viewkeeper/fixtures/viewkeeper-test.component.html
  libs/components/data-manager/src/lib/modules/data-manager/data-manager-column-picker/data-manager-column-picker.component.html
  libs/components/data-manager/src/lib/modules/data-manager/data-manager-column-picker/data-manager-column-picker.component.ts
  libs/components/data-manager/src/lib/modules/data-manager/data-manager-toolbar/data-manager-toolbar.component.html
  libs/components/data-manager/src/lib/modules/data-manager/data-manager-toolbar/data-manager-toolbar.component.ts
  libs/components/data-manager/src/lib/modules/data-manager/data-manager.component.html
  libs/components/data-manager/src/lib/modules/data-manager/data-manager.component.ts
  libs/components/data-manager/src/lib/modules/data-manager/data-view.component.html
  libs/components/data-manager/src/lib/modules/data-manager/data-view.component.ts
  libs/components/data-manager/src/lib/modules/data-manager/fixtures/data-manager-card-view.component.fixture.html
  libs/components/data-manager/src/lib/modules/data-manager/fixtures/data-manager-repeater-view.component.fixture.html
  libs/components/data-manager/src/lib/modules/data-manager/fixtures/data-manager.component.fixture.html
Labels: risk level (author): 3

#2646 refactor: implement Angular control flow for `datetime`, `errors`, and `flyout` libraries
  libs/components/datetime/src/lib/modules/date-range-picker/date-range-picker.component.html
  libs/components/datetime/src/lib/modules/date-range-picker/fixtures/date-range-picker.component.fixture.html
  libs/components/datetime/src/lib/modules/date-range-picker/fixtures/date-range-picker.component.fixture.ts
  libs/components/datetime/src/lib/modules/datepicker/datepicker-calendar-inner.component.html
  libs/components/datetime/src/lib/modules/datepicker/datepicker-calendar.component.html
  libs/components/datetime/src/lib/modules/datepicker/datepicker.component.html
  libs/components/datetime/src/lib/modules/datepicker/daypicker-button.component.html
  libs/components/datetime/src/lib/modules/datepicker/daypicker-cell.component.html
  libs/components/datetime/src/lib/modules/datepicker/daypicker.component.html
  libs/components/datetime/src/lib/modules/datepicker/fixtures/datepicker.component.fixture.html
  libs/components/datetime/src/lib/modules/datepicker/fixtures/fuzzy-datepicker.component.fixture.html
  libs/components/datetime/src/lib/modules/datepicker/monthpicker.component.html
  libs/components/datetime/src/lib/modules/datepicker/yearpicker.component.html
  libs/components/datetime/src/lib/modules/timepicker/timepicker.component.html
  libs/components/errors/src/lib/modules/error/error.component.html
  libs/components/flyout/src/lib/modules/flyout/fixtures/flyout-sample.component.fixture.html
  libs/components/flyout/src/lib/modules/flyout/flyout-iterator.component.ts
  libs/components/flyout/src/lib/modules/flyout/flyout.component.html
Labels: risk level (author): 3

#2653 fix(components/ag-grid): migrate `ColumnApi` to `GridApi`
  libs/components/packages/src/schematics/migrations/update-11/ag-grid/__snapshots__/ag-grid.schematic.spec.ts.snap
  libs/components/packages/src/schematics/migrations/update-11/ag-grid/ag-grid.schematic.spec.ts
  libs/components/packages/src/schematics/migrations/update-11/ag-grid/ag-grid.schematic.ts
  libs/components/packages/src/schematics/migrations/update-11/ag-grid/switch-to-set-grid-option/switch-to-set-grid-option.ts
  libs/components/packages/src/schematics/utility/typescript/swap-imported-class.spec.ts
  libs/components/packages/src/schematics/utility/typescript/swap-imported-class.ts
Labels: risk level (author): 1

#2625 feat(components/ag-grid): use SkyCheckboxComponent style for boolean fields
  apps/e2e/ag-grid-storybook/src/app/data-entry-grid/data-entry-grid.component.html
  apps/e2e/ag-grid-storybook/src/app/data-entry-grid/data-entry-grid.component.scss
  apps/e2e/ag-grid-storybook/src/app/data-entry-grid/data-entry-grid.component.ts
  apps/e2e/ag-grid-storybook/src/app/shared/baseball-players-data.ts
  libs/components/ag-grid/src/lib/styles/_ag-grid-extra.scss
  libs/components/ag-grid/src/lib/styles/_default.scss
  libs/components/ag-grid/src/lib/styles/_modern.scss
Labels: risk level (author): 1

#2644 chore: release 11.0.0-alpha.13
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#2640 fix(components/forms): update checkbox and checkbox group harness to return false instead of throw when no form errors are present
  libs/components/forms/testing/src/checkbox/checkbox-group-harness.spec.ts
  libs/components/forms/testing/src/checkbox/checkbox-group-harness.ts
  libs/components/forms/testing/src/checkbox/checkbox-harness.spec.ts
  libs/components/forms/testing/src/checkbox/checkbox-harness.ts
Labels: risk level (author): 2

#2627 docs(components/ag-grid): add example of using a cell renderer with a row action in an editable grid
  apps/code-examples/src/app/code-examples/ag-grid/data-entry-grid/basic/edit-modal.component.html
  apps/code-examples/src/app/code-examples/ag-grid/data-entry-grid/basic/edit-modal.component.ts
  apps/code-examples/src/app/code-examples/ag-grid/data-entry-grid/basic/mark-inactive.component.html
  apps/code-examples/src/app/code-examples/ag-grid/data-entry-grid/basic/mark-inactive.component.ts
  apps/playground/src/app/components/ag-grid/edit-complex-cells/action/action.component.html
  apps/playground/src/app/components/ag-grid/edit-complex-cells/action/action.component.ts
  apps/playground/src/app/components/ag-grid/edit-complex-cells/edit-complex-cells.component.html
  apps/playground/src/app/components/ag-grid/edit-complex-cells/edit-complex-cells.component.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/ag-grid.service.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/types/cell-class.ts
  libs/components/ag-grid/src/lib/styles/_base.scss
Labels: risk level (author): 1

#2656 test(components/ag-grid): update flakey data manager directive test
  libs/components/ag-grid/src/lib/modules/ag-grid/ag-grid-data-manager-adapter.directive.spec.ts
Labels: risk level (author): 1

#2652 ci: use nx agents
  .github/workflows/ci.yml
  .github/workflows/e2e.yml
Labels: risk level (author): 1, skip e2e

#2645 feat(components/ag-grid): implement sticky setting for column widths
  apps/code-examples/src/app/code-examples/ag-grid/data-entry-grid/basic/demo.component.ts
  apps/code-examples/src/app/code-examples/ag-grid/data-entry-grid/basic/edit-modal.component.ts
  apps/code-examples/src/app/code-examples/ag-grid/data-entry-grid/data-manager-added/edit-modal.component.ts
  apps/code-examples/src/app/code-examples/ag-grid/data-entry-grid/data-manager-added/view-grid.component.ts
  apps/code-examples/src/app/code-examples/ag-grid/data-entry-grid/inline-help/demo.component.ts
  apps/code-examples/src/app/code-examples/ag-grid/data-entry-grid/inline-help/edit-modal.component.ts
  apps/code-examples/src/app/code-examples/ag-grid/data-grid/basic-multiselect/demo.component.ts
  apps/code-examples/src/app/code-examples/ag-grid/data-grid/basic/demo.component.ts
  apps/code-examples/src/app/code-examples/ag-grid/data-grid/data-manager-multiselect/view-grid.component.ts
  apps/code-examples/src/app/code-examples/ag-grid/data-grid/data-manager/view-grid.component.ts
  apps/code-examples/src/app/code-examples/ag-grid/data-grid/inline-help/demo.component.ts
  apps/code-examples/src/app/code-examples/ag-grid/data-grid/paging/demo.component.ts
  apps/code-examples/src/app/code-examples/ag-grid/data-grid/top-scroll/demo.component.ts
  apps/code-examples/src/app/code-examples/data-manager/data-manager/basic/view-grid.component.ts
  apps/code-examples/src/app/code-examples/pages/page/list-page-list-layout-demo/list-page-content.component.ts
  apps/code-examples/src/app/code-examples/pages/page/list-page-tabs-layout-demo/list-page-contacts-grid.component.ts
  apps/code-examples/src/app/code-examples/pages/page/record-page-tabs-layout-demo/record-page-attachments-tab.component.ts
  apps/playground/src/app/components/ag-grid/data-manager/data-view-grid.component.html
  apps/playground/src/app/components/ag-grid/data-manager/data-view-grid.component.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/ag-grid-data-manager-adapter.directive.spec.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/ag-grid-data-manager-adapter.directive.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/fixtures/ag-grid-data-manager.component.fixture.ts
  libs/components/data-manager/src/lib/modules/data-manager/data-manager.component.spec.ts
  libs/components/data-manager/src/lib/modules/data-manager/data-view.component.ts
  libs/components/data-manager/src/lib/modules/data-manager/models/data-view-column-widths.ts
  libs/components/data-manager/src/lib/modules/data-manager/models/data-view-state-options.ts
  libs/components/data-manager/src/lib/modules/data-manager/models/data-view-state.ts
  package-lock.json
Labels: risk level (author): 3

#2648 refactor: implement Angular control flow for `forms` library
  libs/components/forms/src/lib/modules/character-counter/character-counter-indicator.component.html
  libs/components/forms/src/lib/modules/character-counter/fixtures/character-count-no-indicator.component.fixture.html
  libs/components/forms/src/lib/modules/character-counter/fixtures/character-count.component.fixture.html
  libs/components/forms/src/lib/modules/checkbox/checkbox-group.component.html
  libs/components/forms/src/lib/modules/checkbox/checkbox-label-text-label.component.html
  libs/components/forms/src/lib/modules/checkbox/checkbox.component.html
  libs/components/forms/src/lib/modules/checkbox/checkbox.component.spec.ts
  libs/components/forms/src/lib/modules/checkbox/fixtures/standard-checkbox-group.component.html
  libs/components/forms/src/lib/modules/checkbox/fixtures/standard-checkbox-group.component.ts
  libs/components/forms/src/lib/modules/checkbox/fixtures/template-driven-checkbox-group.component.ts
  libs/components/forms/src/lib/modules/field-group/field-group.component.html
  libs/components/forms/src/lib/modules/file-attachment/file-attachment/file-attachment-label.component.ts
  libs/components/forms/src/lib/modules/file-attachment/file-attachment/file-attachment.component.html
  libs/components/forms/src/lib/modules/file-attachment/file-attachment/fixtures/file-attachment.component.fixture.html
  libs/components/forms/src/lib/modules/file-attachment/file-attachment/fixtures/file-attachment.component.fixture.ts
  libs/components/forms/src/lib/modules/file-attachment/file-attachment/fixtures/template-driven-file-attachment.component.fixture.ts
  libs/components/forms/src/lib/modules/file-attachment/file-drop/file-drop.component.html
  libs/components/forms/src/lib/modules/file-attachment/file-drop/file-item.component.html
  libs/components/forms/src/lib/modules/file-attachment/file-drop/file-item.component.ts
  libs/components/forms/src/lib/modules/form-error/form-error.component.ts
  libs/components/forms/src/lib/modules/form-error/form-errors.component.ts
  libs/components/forms/src/lib/modules/input-box/fixtures/input-box.component.fixture.html
  libs/components/forms/src/lib/modules/input-box/input-box.component.html
  libs/components/forms/src/lib/modules/radio/fixtures/radio-group-reactive.component.fixture.html
  libs/components/forms/src/lib/modules/radio/fixtures/radio-group.component.fixture.ts
  libs/components/forms/src/lib/modules/radio/radio-group.component.html
  libs/components/forms/src/lib/modules/radio/radio.component.html
  libs/components/forms/src/lib/modules/selection-box/fixtures/selection-box-grid.component.fixture.html
  libs/components/forms/src/lib/modules/selection-box/fixtures/selection-box.component.fixture.html
  libs/components/forms/src/lib/modules/toggle-switch/fixtures/toggle-switch-on-push.component.fixture.html
  libs/components/forms/src/lib/modules/toggle-switch/fixtures/toggle-switch.component.fixture.html
  libs/components/forms/src/lib/modules/toggle-switch/toggle-switch.component.html
  libs/components/forms/testing/src/character-counter/character-counter-indicator-harness.spec.ts
  libs/components/forms/testing/src/checkbox/fixtures/checkbox-harness-test.component.html
  libs/components/forms/testing/src/radio-fixture.spec.ts
Labels: risk level (author): 3

#2657 refactor: implement Angular control flow for `indicators` and `inline-form` libraries
  libs/components/grids/.eslintrc.json
  libs/components/indicators/src/lib/modules/alert/alert.component.html
  libs/components/indicators/src/lib/modules/key-info/key-info.component.html
  libs/components/indicators/src/lib/modules/label/label.component.html
  libs/components/indicators/src/lib/modules/status-indicator/fixtures/status-indicator.component.fixture.html
  libs/components/indicators/src/lib/modules/status-indicator/status-indicator.component.html
  libs/components/indicators/src/lib/modules/text-highlight/fixtures/text-highlight.component.fixture.html
  libs/components/indicators/src/lib/modules/tokens/fixtures/tokens.component.fixture.html
  libs/components/indicators/src/lib/modules/tokens/token.component.html
  libs/components/indicators/src/lib/modules/tokens/tokens.component.html
  libs/components/indicators/src/lib/modules/wait/fixtures/wait.component.fixture.html
  libs/components/indicators/src/lib/modules/wait/wait.component.html
  libs/components/indicators/testing/src/status-indicator/status-indicator-harness.spec.ts
  libs/components/inline-form/src/lib/modules/inline-form/fixtures/inline-form.fixture.html
  libs/components/inline-form/src/lib/modules/inline-form/inline-form.component.html
  libs/components/list-builder-common/.eslintrc.json
  libs/components/list-builder-view-checklist/.eslintrc.json
  libs/components/list-builder-view-grids/.eslintrc.json
  libs/components/list-builder/.eslintrc.json
Labels: risk level (author): 3

#2654 feat(components/datetime)!: remove deprecated required inputs and update error validation
  apps/playground/src/app/components/datetime/date-range-picker/date-range-picker.component.html
  apps/playground/src/app/components/datetime/date-range-picker/date-range-picker.component.ts
  libs/components/datetime/src/lib/modules/date-range-picker/date-range-picker.component.html
  libs/components/datetime/src/lib/modules/date-range-picker/date-range-picker.component.spec.ts
  libs/components/datetime/src/lib/modules/date-range-picker/date-range-picker.component.ts
  libs/components/datetime/src/lib/modules/date-range-picker/fixtures/date-range-picker.component.fixture.html
  libs/components/forms/src/lib/modules/input-box/fixtures/input-box.component.fixture.html
  libs/components/forms/src/lib/modules/input-box/fixtures/input-box.component.fixture.ts
  libs/components/forms/src/lib/modules/input-box/input-box.component.html
  libs/components/forms/src/lib/modules/input-box/input-box.component.spec.ts
  libs/components/forms/src/lib/modules/input-box/input-box.component.ts
Labels: risk level (author): 3

#2658 feat(components/ag-grid): allow template ref cell renderers to be used for row actions in editable grids
  apps/code-examples/src/app/code-examples/ag-grid/data-entry-grid/basic/edit-modal.component.ts
  apps/playground/src/app/components/ag-grid/edit-complex-cells/edit-complex-cells.component.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/ag-grid-wrapper.component.spec.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/ag-grid-wrapper.component.ts
Labels: risk level (author): 1

#2660 refactor: implement Angular control flow for `lookup`, `modals`, and `pages` libraries
  libs/components/lookup/src/lib/modules/autocomplete/autocomplete.component.html
  libs/components/lookup/src/lib/modules/autocomplete/fixtures/autocomplete.component.fixture.html
  libs/components/lookup/src/lib/modules/country-field/country-field.component.html
  libs/components/lookup/src/lib/modules/country-field/fixtures/country-field-input-box.component.fixture.ts
  libs/components/lookup/src/lib/modules/lookup/lookup-show-more-modal.component.html
  libs/components/lookup/src/lib/modules/lookup/lookup.component.html
  libs/components/lookup/src/lib/modules/search/search.component.html
  libs/components/lookup/src/lib/modules/selection-modal/selection-modal.component.html
  libs/components/modals/src/lib/modules/confirm/confirm.component.html
  libs/components/modals/src/lib/modules/modal/fixtures/modal.component.fixture.html
  libs/components/modals/src/lib/modules/modal/modal-footer.component.html
  libs/components/modals/src/lib/modules/modal/modal.component.html
  libs/components/modals/testing/src/confirm/confirm-testing.controller.spec.ts
  libs/components/pages/src/lib/modules/action-hub/action-hub.component.html
  libs/components/pages/src/lib/modules/link-list/link-list.component.html
  libs/components/pages/src/lib/modules/modal-link-list/modal-link-list.component.html
  libs/components/pages/src/lib/modules/needs-attention/needs-attention.component.html
  libs/components/pages/src/lib/modules/page-header/fixtures/page-header-fixtures.component.html
  libs/components/pages/src/lib/modules/page-header/fixtures/page-header-fixtures.component.ts
  libs/components/pages/src/lib/modules/page-header/page-header.component.html
  libs/components/pages/src/lib/modules/page/fixtures/page-content-fixture.component.ts
  libs/components/pages/testing/src/page/page-harness.spec.ts
Labels: risk level (author): 3

#2665 refactor: implement Angular control flow for `text-editor`, `tiles`, `toast`, and `validation` libraries
  libs/components/text-editor/src/lib/modules/text-editor/menubar/text-editor-menubar.component.html
  libs/components/text-editor/src/lib/modules/text-editor/text-editor.component.html
  libs/components/text-editor/src/lib/modules/text-editor/toolbar/text-editor-toolbar.component.html
  libs/components/text-editor/src/lib/modules/text-editor/url-modal/text-editor-url-modal.component.html
  libs/components/text-editor/src/lib/modules/text-editor/url-modal/text-editor-url-modal.component.ts
  libs/components/tiles/src/lib/modules/tiles/tile-dashboard/tile-dashboard.component.html
  libs/components/tiles/src/lib/modules/tiles/tile/fixtures/tile.component.fixture.ts
  libs/components/tiles/src/lib/modules/tiles/tile/tile.component.html
  libs/components/toast/src/lib/modules/toast/fixtures/toast.component.fixture.html
  libs/components/toast/src/lib/modules/toast/toaster.component.html
  libs/components/validation/src/lib/modules/email-validation/fixtures/email-validation.component.fixture.html
  libs/components/validation/src/lib/modules/url-validation/fixtures/url-validation-ruleset.component.fixture.html
  libs/components/validation/src/lib/modules/url-validation/fixtures/url-validation.component.fixture.html
Labels: risk level (author): 3

#2666 refactor: implement Angular control flow for `integration` app
  apps/integration/src/app/app.component.html
  apps/integration/src/app/home/home.component.html
  apps/integration/src/app/integrations/field-heights/field-heights.component.html
  apps/integration/src/app/integrations/lookup-in-modal/lookup-in-modal.component.ts
  apps/integration/src/app/integrations/modal-colorpicker/modal-colorpicker-modal.component.ts
  apps/integration/src/app/integrations/modal-date-range-picker/modal-date-range-picker-modal.component.ts
  apps/integration/src/app/integrations/modal-footer-dropdown/modal-footer-dropdown-modal.component.html
  apps/integration/src/app/integrations/modal-footer-dropdown/modal-footer-dropdown-modal.component.ts
  apps/integration/src/app/integrations/modal-split-view-tile-dashboard/modal-split-view-tile-dashboard.component.html
  apps/integration/src/app/integrations/modal-split-view-tile-dashboard/modal.component.html
  apps/integration/src/app/integrations/modal-split-view-tile-dashboard/modal.component.ts
  apps/integration/src/app/integrations/modal-viewkept-toolbars/modal-viewkept-toolbars-modal.component.html
  apps/integration/src/app/integrations/modal-viewkept-toolbars/modal-viewkept-toolbars-modal.component.ts
  apps/integration/src/app/integrations/modal-viewkept-toolbars/modal-viewkept-toolbars.component.html
  apps/integration/src/app/integrations/modal-wait/modal-wait-modal.component.html
  apps/integration/src/app/integrations/modal-wait/modal-wait-modal.component.ts
  apps/integration/src/app/integrations/modal-wait/modal-wait.component.html
  apps/integration/src/app/integrations/viewkeeper-tabset/viewkeeper-tabset.component.html
  apps/integration/src/app/shared/theme-selector/theme-selector.component.html
  apps/integration/src/app/shared/theme-selector/theme-selector.component.ts
Labels: risk level (author): 1

#2667 ci: avoid nx agents for e2e
  .github/workflows/e2e.yml
Labels: risk level (author): 1, skip e2e

#2663 feat(components/forms): update `SkyFileValidateFn` export
  libs/components/forms/src/index.ts
  libs/components/packages/src/schematics/migrations/migration-collection.json
  libs/components/packages/src/schematics/migrations/update-11/forms/forms.schematic.spec.ts
  libs/components/packages/src/schematics/migrations/update-11/forms/forms.schematic.ts
Labels: risk level (author): 1, skip e2e

#2661 ci: fail dependent jobs
  .github/workflows/ci.yml
Labels: risk level (author): 1, skip e2e

#2662 fix(components/packages): additional AG Grid event migrations
  libs/components/packages/src/schematics/migrations/update-11/ag-grid/__snapshots__/ag-grid.schematic.spec.ts.snap
  libs/components/packages/src/schematics/migrations/update-11/ag-grid/ag-grid.schematic.spec.ts
  libs/components/packages/src/schematics/migrations/update-11/ag-grid/ag-grid.schematic.ts
  libs/components/packages/src/schematics/migrations/update-11/ag-grid/event-type-strings/event-type-strings.spec.ts
  libs/components/packages/src/schematics/migrations/update-11/ag-grid/event-type-strings/event-type-strings.ts
Labels: risk level (author): 1

#2669 chore: changelog for 10.41.5 (#2642) 🍒
  CHANGELOG.md
Labels: risk level (author): 1, risk level (reviewer): 1
