Repository blackbaud/skyux, pull requests merged in 2024-09, with the labels that each got.

#2655 chore: release 11.0.0-alpha.14
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#2674 fix(components/forms): stop requiring labelText in field group
  karma.conf.js
  libs/components/core/src/lib/modules/scroll-shadow/scroll-shadow.directive.spec.ts
  libs/components/datetime/src/lib/modules/date-range-picker/date-range-picker.component.spec.ts
  libs/components/datetime/src/lib/modules/date-range-picker/date-range-picker.component.ts
  libs/components/forms/src/lib/modules/checkbox/checkbox.component.spec.ts
  libs/components/forms/src/lib/modules/checkbox/checkbox.component.ts
  libs/components/forms/src/lib/modules/field-group/field-group.component.ts
  libs/components/forms/src/lib/modules/file-attachment/file-attachment.component.spec.ts
  libs/components/forms/src/lib/modules/file-attachment/file-attachment.component.ts
  libs/components/forms/src/lib/modules/file-attachment/file-drop.component.spec.ts
  libs/components/forms/src/lib/modules/file-attachment/file-drop.component.ts
  libs/components/forms/src/lib/modules/input-box/input-box.component.spec.ts
  libs/components/forms/src/lib/modules/input-box/input-box.component.ts
  libs/components/forms/src/lib/modules/radio/radio-group.component.spec.ts
  libs/components/forms/src/lib/modules/radio/radio-group.component.ts
  libs/components/forms/src/lib/modules/radio/radio.component.spec.ts
  libs/components/forms/src/lib/modules/radio/radio.component.ts
  libs/components/forms/src/lib/modules/toggle-switch/toggle-switch.component.spec.ts
  libs/components/forms/src/lib/modules/toggle-switch/toggle-switch.component.ts
  libs/components/lookup/src/lib/modules/lookup/lookup.component.ts
  libs/components/text-editor/src/lib/modules/text-editor/text-editor.component.spec.ts
  libs/components/text-editor/src/lib/modules/text-editor/text-editor.component.ts
Labels: risk level (author): 1

#2679 chore: clean up lookup
  libs/components/lookup/src/lib/modules/lookup/lookup.component.ts
Labels: risk level (author): 1

#2682 ci: use nx agents in 10.x.x
  .github/workflows/ci.yml
  .github/workflows/e2e.yml
  package-lock.json
  package.json
Labels: risk level (author): 1

#2683 ci: additional `--no-agents` flag
  .github/workflows/e2e.yml
Labels: risk level (author): 1, skip e2e

#2684 ci: additional `--no-agents` flag (#2683)
  .github/workflows/e2e.yml
Labels: risk level (author): 1

#2677 fix(components/forms): stop requiring labelText in field group (#2674)
  libs/components/datetime/src/lib/modules/date-range-picker/date-range-picker.component.spec.ts
  libs/components/datetime/src/lib/modules/date-range-picker/date-range-picker.component.ts
  libs/components/forms/src/index.ts
  libs/components/forms/src/lib/modules/checkbox/checkbox.component.spec.ts
  libs/components/forms/src/lib/modules/checkbox/checkbox.component.ts
  libs/components/forms/src/lib/modules/field-group/field-group.component.ts
  libs/components/forms/src/lib/modules/file-attachment/file-attachment/file-attachment.component.spec.ts
  libs/components/forms/src/lib/modules/file-attachment/file-attachment/file-attachment.component.ts
  libs/components/forms/src/lib/modules/file-attachment/file-drop/file-drop.component.spec.ts
  libs/components/forms/src/lib/modules/file-attachment/file-drop/file-drop.component.ts
  libs/components/forms/src/lib/modules/input-box/input-box.component.spec.ts
  libs/components/forms/src/lib/modules/input-box/input-box.component.ts
  libs/components/forms/src/lib/modules/radio/radio-group.component.spec.ts
  libs/components/forms/src/lib/modules/radio/radio-group.component.ts
  libs/components/forms/src/lib/modules/radio/radio.component.spec.ts
  libs/components/forms/src/lib/modules/radio/radio.component.ts
  libs/components/forms/src/lib/modules/shared/form-field-label-text-required.directive.spec.ts
  libs/components/forms/src/lib/modules/shared/form-field-label-text-required.directive.ts
  libs/components/forms/src/lib/modules/shared/form-field-label-text-required.service.spec.ts
  libs/components/forms/src/lib/modules/shared/form-field-label-text-required.service.ts
  libs/components/forms/src/lib/modules/toggle-switch/toggle-switch.component.spec.ts
  libs/components/forms/src/lib/modules/toggle-switch/toggle-switch.component.ts
  libs/components/text-editor/src/lib/modules/text-editor/text-editor.component.spec.ts
  libs/components/text-editor/src/lib/modules/text-editor/text-editor.component.ts
Labels: risk level (author): 1

#2687 refactor(components/core): adjust alpha test to work within ±3%
  libs/components/core/src/lib/modules/scroll-shadow/scroll-shadow.directive.spec.ts
Labels: risk level (author): 1

#2681 feat(components/ag-grid): support AG Grid 32.1.0
  libs/components/ag-grid/package.json
  libs/components/ag-grid/src/lib/modules/ag-grid/ag-grid-data-manager-adapter.directive.ts
  libs/components/ag-grid/src/lib/styles/_base.scss
  libs/components/data-manager/src/index.ts
  libs/components/packages/package.json
  libs/components/packages/src/schematics/ag-grid-migrate/ag-grid-migrate.schematic.spec.ts
  libs/components/packages/src/schematics/ag-grid-migrate/ag-grid-migrate.schematic.ts
  libs/components/packages/src/schematics/migrations/update-11/ag-grid/ag-grid.schematic.spec.ts
  libs/components/packages/src/schematics/migrations/update-11/ag-grid/ag-grid.schematic.ts
  package-lock.json
  package.json
Labels: risk level (author): 1

#2692 ci: use fewer connections
  .github/workflows/ci.yml
  .github/workflows/e2e.yml
Labels: risk level (author): 1, skip e2e

#2670 fix(components/forms)!: radio button add proper spacing when not in unordered lists
  apps/code-examples/src/app/code-examples/forms/radio/standard/demo.component.html
  apps/e2e/forms-storybook/src/app/radio-button/radio-button.component.html
  apps/e2e/theme-storybook/src/app/switch-controls/switch-controls.component.html
  apps/playground/src/app/components/forms/radio/radio.component.html
  libs/components/forms/src/lib/modules/radio/radio.component.scss
Labels: risk level (author): 2

#2695 ci: use fewer connections (#2692)
  .github/workflows/ci.yml
  .github/workflows/e2e.yml
Labels: risk level (author): 1, skip e2e

#2697 ci: use fewer connections (#2692) (#2695)
  .github/workflows/ci.yml
  .github/workflows/e2e.yml
Labels: risk level (author): 1, skip e2e

#2699 ci: adjust e2e concurrency
  .github/workflows/e2e.yml
Labels: risk level (author): 1, skip e2e

#2698 ci: adjust e2e concurrency
  .github/workflows/e2e.yml
Labels: risk level (author): 1, skip e2e

#2675 fix(components/forms): separate file attachment help inline button from label
  libs/components/forms/src/lib/modules/file-attachment/file-attachment/file-attachment.component.html
  libs/components/forms/src/lib/modules/file-attachment/file-attachment/file-attachment.component.spec.ts
  libs/components/forms/src/lib/modules/file-attachment/file-attachment/file-attachment.component.ts
Labels: risk level (author): 1

#2680 fix(components/forms): add missing ARIA attributes to file attachment button
  libs/components/forms/src/lib/modules/file-attachment/file-attachment/file-attachment.component.html
  libs/components/forms/src/lib/modules/file-attachment/file-attachment/file-attachment.component.spec.ts
Labels: risk level (author): 1

#2678 feat(components/theme): add support for @skyux/icons@7.8.0
  libs/components/packages/package.json
  libs/components/theme/package.json
  libs/components/theme/src/lib/styles/sky.scss
  package-lock.json
  package.json
Labels: risk level (author): 2

#2688 fix(components/icon): variant input is respected for SVG-based icons
  libs/components/icon/src/lib/icon/fixtures/icon.component.fixture.html
  libs/components/icon/src/lib/icon/fixtures/icon.component.fixture.ts
  libs/components/icon/src/lib/icon/icon-svg.component.spec.ts
  libs/components/icon/src/lib/icon/icon.component.html
  libs/components/icon/src/lib/icon/icon.component.spec.ts
Labels: risk level (author): 1

#2701 fix(components/icon): variant input is respected for SVG-based icons (#2688)
  libs/components/icon/src/lib/icon/fixtures/icon.component.fixture.html
  libs/components/icon/src/lib/icon/fixtures/icon.component.fixture.ts
  libs/components/icon/src/lib/icon/icon-svg.component.spec.ts
  libs/components/icon/src/lib/icon/icon.component.html
  libs/components/icon/src/lib/icon/icon.component.spec.ts
Labels: risk level (author): 1

#2676 chore: release 10.42.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease 10.x.x: pending

#2702 chore: changelog for 10.42.0 (#2676) 🍒
  CHANGELOG.md
Labels: risk level (author): 1, risk level (reviewer): 1

#2703 feat(components/theme): add support for @skyux/icons@7.8.0 (#2678)
  libs/components/packages/package.json
  libs/components/theme/package.json
  libs/components/theme/src/lib/styles/sky.scss
  package-lock.json
  package.json
Labels: risk level (author): 1

#2686 chore: release 11.0.0-alpha.15
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#2700 fix(components/forms): add unique ARIA labels to file drop item delete buttons
  libs/components/forms/src/assets/locales/resources_en_US.json
  libs/components/forms/src/lib/modules/file-attachment/file-drop/file-item.component.html
  libs/components/forms/src/lib/modules/shared/sky-forms-resources.module.ts
Labels: risk level (author): 1

#2696 feat: add support for `axe-core@4.10.0`
  libs/components/packages/src/schematics/migrations/update-10/axe-core/axe-core.schematic.spec.ts
  libs/components/packages/src/schematics/migrations/update-10/axe-core/axe-core.schematic.ts
  libs/sdk/testing/package.json
  package-lock.json
  package.json
Labels: risk level (author): 2

#2705 chore: update Angular 17
  karma.conf.js
  libs/components/a11y/package.json
  libs/components/action-bars/package.json
  libs/components/ag-grid/package.json
  libs/components/angular-tree-component/package.json
  libs/components/animations/package.json
  libs/components/assets/package.json
  libs/components/autonumeric/package.json
  libs/components/avatar/package.json
  libs/components/colorpicker/package.json
  libs/components/config/package.json
  libs/components/core/package.json
  libs/components/data-manager/package.json
  libs/components/datetime/package.json
  libs/components/errors/package.json
  libs/components/flyout/package.json
  libs/components/forms/package.json
  libs/components/grids/package.json
  libs/components/help-inline/package.json
  libs/components/i18n/package.json
  libs/components/icon/package.json
  libs/components/indicators/package.json
  libs/components/inline-form/package.json
  libs/components/layout/package.json
  libs/components/list-builder-common/package.json
  libs/components/list-builder-view-checklist/package.json
  libs/components/list-builder-view-grids/package.json
  libs/components/list-builder/package.json
  libs/components/lists/package.json
  libs/components/lookup/package.json
  libs/components/modals/package.json
  libs/components/navbar/package.json
  libs/components/omnibar-interop/package.json
  libs/components/packages/package.json
  libs/components/pages/package.json
  libs/components/phone-field/package.json
  libs/components/popovers/package.json
  libs/components/progress-indicator/package.json
  libs/components/router/package.json
  libs/components/select-field/package.json
  libs/components/split-view/package.json
  libs/components/storybook/package.json
  libs/components/tabs/package.json
  libs/components/text-editor/package.json
  libs/components/theme/package.json
  libs/components/tiles/package.json
  libs/components/toast/package.json
  libs/components/validation/package.json
  libs/sdk/e2e-schematics/package.json
  libs/sdk/eslint-config/package.json
  libs/sdk/prettier-schematics/package.json
  libs/sdk/testing/package.json
  package-lock.json
  package.json
Labels: risk level (author): 1

#2708 fix(components/packages): adjust AG Grid migration
  libs/components/packages/src/schematics/migrations/update-11/ag-grid/ag-grid.schematic.spec.ts
  libs/components/packages/src/schematics/migrations/update-11/ag-grid/ag-grid.schematic.ts
  libs/components/packages/src/schematics/migrations/update-11/ag-grid/event-type-strings/event-type-strings.ts
  libs/components/packages/src/schematics/utility/typescript/remove-import.spec.ts
  libs/components/packages/src/schematics/utility/typescript/remove-import.ts
  libs/components/packages/src/schematics/utility/typescript/swap-imported-class.spec.ts
  libs/components/packages/src/schematics/utility/typescript/swap-imported-class.ts
Labels: risk level (author): 1

#2691 fix(components/ag-grid): improve row selector performance
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-renderers/cell-renderer-row-selector/cell-renderer-row-selector.component.html
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-renderers/cell-renderer-row-selector/cell-renderer-row-selector.component.spec.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-renderers/cell-renderer-row-selector/cell-renderer-row-selector.component.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-renderers/cell-renderer-row-selector/cell-renderer-row-selector.module.ts
Labels: risk level (author): 1

#2710 fix(components/ag-grid): improve row selector performance (#2691)
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-renderers/cell-renderer-row-selector/cell-renderer-row-selector.component.html
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-renderers/cell-renderer-row-selector/cell-renderer-row-selector.component.spec.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-renderers/cell-renderer-row-selector/cell-renderer-row-selector.component.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-renderers/cell-renderer-row-selector/cell-renderer-row-selector.module.ts
Labels: risk level (author): 1

#2694 fix(components/lookup): add required label asterisk for template driven forms
  apps/playground/src/app/components/lookup/lookup/lookup.component.html
  apps/playground/src/app/components/lookup/lookup/lookup.component.ts
  libs/components/forms/src/lib/modules/input-box/fixtures/input-box.component.fixture.html
  libs/components/forms/src/lib/modules/input-box/input-box-host.service.ts
  libs/components/forms/src/lib/modules/input-box/input-box.component.spec.ts
  libs/components/forms/src/lib/modules/input-box/input-box.component.ts
  libs/components/lookup/src/lib/modules/lookup/fixtures/lookup-input-box.component.fixture.html
  libs/components/lookup/src/lib/modules/lookup/fixtures/lookup-input-box.component.fixture.ts
  libs/components/lookup/src/lib/modules/lookup/lookup.component.spec.ts
  libs/components/lookup/src/lib/modules/lookup/lookup.component.ts
Labels: risk level (author): 1

#2711 fix(components/lookup): add required label asterisk for template driven forms (#2694)
  apps/playground/src/app/components/lookup/lookup/lookup.component.html
  apps/playground/src/app/components/lookup/lookup/lookup.component.ts
  libs/components/forms/src/lib/modules/input-box/fixtures/input-box.component.fixture.html
  libs/components/forms/src/lib/modules/input-box/input-box-host.service.ts
  libs/components/forms/src/lib/modules/input-box/input-box.component.spec.ts
  libs/components/forms/src/lib/modules/input-box/input-box.component.ts
  libs/components/lookup/src/lib/modules/lookup/fixtures/lookup-input-box.component.fixture.html
  libs/components/lookup/src/lib/modules/lookup/fixtures/lookup-input-box.component.fixture.ts
  libs/components/lookup/src/lib/modules/lookup/lookup.component.spec.ts
  libs/components/lookup/src/lib/modules/lookup/lookup.component.ts
Labels: risk level (author): 1

#2706 chore: release 11.0.0-alpha.16
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#2714 chore: update to Angular 18.2
  karma.conf.js
  libs/components/a11y/package.json
  libs/components/action-bars/package.json
  libs/components/ag-grid/package.json
  libs/components/angular-tree-component/package.json
  libs/components/animations/package.json
  libs/components/assets/package.json
  libs/components/autonumeric/package.json
  libs/components/avatar/package.json
  libs/components/colorpicker/package.json
  libs/components/config/package.json
  libs/components/core/package.json
  libs/components/data-manager/package.json
  libs/components/datetime/package.json
  libs/components/errors/package.json
  libs/components/flyout/package.json
  libs/components/forms/package.json
  libs/components/grids/package.json
  libs/components/help-inline/package.json
  libs/components/i18n/package.json
  libs/components/icon/package.json
  libs/components/indicators/package.json
  libs/components/inline-form/package.json
  libs/components/layout/package.json
  libs/components/list-builder-common/package.json
  libs/components/list-builder-view-checklist/package.json
  libs/components/list-builder-view-grids/package.json
  libs/components/list-builder/package.json
  libs/components/lists/package.json
  libs/components/lookup/package.json
  libs/components/modals/package.json
  libs/components/navbar/package.json
  libs/components/packages/package.json
  libs/components/pages/package.json
  libs/components/phone-field/package.json
  libs/components/popovers/package.json
  libs/components/progress-indicator/package.json
  libs/components/router/package.json
  libs/components/select-field/package.json
  libs/components/split-view/package.json
  libs/components/storybook/package.json
  libs/components/tabs/package.json
  libs/components/text-editor/package.json
  libs/components/theme/package.json
  libs/components/tiles/package.json
  libs/components/toast/package.json
  libs/components/validation/package.json
  libs/sdk/e2e-schematics/package.json
  libs/sdk/eslint-config/package.json
  libs/sdk/prettier-schematics/package.json
  libs/sdk/testing/package.json
  package-lock.json
  package.json
Labels: risk level (author): 1

#2712 ci: beta release
  .github/workflows/release-please.yml
Labels: risk level (author): 1, skip e2e

#2716 chore: changelog for 10.43.0 (#2707) 🍒
  CHANGELOG.md
Labels: risk level (author): 1, risk level (reviewer): 1

#2718 feat: add support for `axe-core@4.10.0` (#2696)
  libs/components/indicators/package.json
  libs/components/packages/src/schematics/migrations/migration-collection.json
  libs/components/packages/src/schematics/migrations/update-11/axe-core/axe-core.schematic.spec.ts
  libs/components/packages/src/schematics/migrations/update-11/axe-core/axe-core.schematic.ts
  libs/sdk/testing/package.json
  package-lock.json
  package.json
Labels: risk level (author): 1

#2715 chore: release 11.0.0-beta.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#2709 ci: run e2e without nx cloud
  .github/actions/e2e-affected/action.yml
  .github/workflows/ci.yml
  .github/workflows/e2e.yml
  nx.json
  package-lock.json
  package.json
Labels: risk level (author): 1, skip e2e

#2720 ci: run e2e without nx cloud (#2709)
  .github/actions/e2e-affected/action.yml
  .github/workflows/ci.yml
  .github/workflows/e2e.yml
  nx.json
Labels: risk level (author): 1, skip e2e

#2719 fix(components/datetime): date range picker's datepickers are always required & datepicker `invalid` error is consistent
  libs/components/datetime/src/lib/modules/date-range-picker/date-range-picker.component.html
  libs/components/datetime/src/lib/modules/date-range-picker/date-range-picker.component.spec.ts
  libs/components/datetime/src/lib/modules/date-range-picker/date-range-picker.component.ts
  libs/components/datetime/src/lib/modules/datepicker/datepicker-input.directive.ts
Labels: risk level (author): 2

#2717 feat(components/popovers): implement disclosure pattern for popovers
  .eslintrc-overrides.json
  apps/code-examples/src/app/code-examples/popovers/popover/basic/demo.component.html
  apps/playground/src/app/components/help-inline/help-inline.component.html
  apps/playground/src/app/components/help-inline/help-inline.component.ts
  apps/playground/src/app/components/popovers/popovers/popovers.component.html
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-validator/ag-grid-cell-validator-tooltip.component.html
  libs/components/forms/testing/src/checkbox/checkbox-harness.spec.ts
  libs/components/forms/testing/src/checkbox/fixtures/checkbox-harness-test.component.html
  libs/components/forms/testing/src/field-group/field-group-harness.spec.ts
  libs/components/forms/testing/src/field-group/fixtures/field-group.component.fixture.ts
  libs/components/forms/testing/src/input-box/fixtures/input-box-harness-test.component.ts
  libs/components/forms/testing/src/input-box/input-box-harness.spec.ts
  libs/components/help-inline/src/lib/modules/help-inline/aria-label.pipe.ts
  libs/components/help-inline/src/lib/modules/help-inline/button-help-key.component.ts
  libs/components/help-inline/src/lib/modules/help-inline/button-popover.component.ts
  libs/components/help-inline/src/lib/modules/help-inline/help-inline-aria-controls.pipe.ts
  libs/components/help-inline/src/lib/modules/help-inline/help-inline-aria-expanded.pipe.ts
  libs/components/help-inline/src/lib/modules/help-inline/help-inline-aria-haspopup.pipe.ts
  libs/components/help-inline/src/lib/modules/help-inline/help-inline.component.html
  libs/components/help-inline/src/lib/modules/help-inline/help-inline.component.spec.ts
  libs/components/help-inline/src/lib/modules/help-inline/help-inline.component.ts
  libs/components/help-inline/testing/src/help-inline/help-inline-harness.spec.ts
  libs/components/popovers/src/lib/modules/popover/fixtures/popover-a11y.component.fixture.ts
  libs/components/popovers/src/lib/modules/popover/popover-content.component.html
  libs/components/popovers/src/lib/modules/popover/popover-sr-pointer.service.ts
  libs/components/popovers/src/lib/modules/popover/popover.component.ts
  libs/components/popovers/src/lib/modules/popover/popover.directive.spec.ts
  libs/components/popovers/src/lib/modules/popover/popover.directive.ts
  libs/components/popovers/src/lib/modules/popover/types/popover-trigger.ts
  libs/components/popovers/testing/src/popover/harness/popover-harness.ts
Labels: risk level (author): 3

#2721 chore: release 11.0.0-beta.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#2723 build: use node 20.17.0
  .nvmrc
Labels: risk level (author): 1

#2724 build: use node 20.17.0 (#2723)
  .nvmrc
Labels: risk level (author): 1

#2722 ci: release 11
  .github/workflows/release-please.yml
Labels: risk level (author): 1

#2725 feat: release 11.0.0
  .github/workflows/release-please.yml
Labels: risk level (author): 1

#2726 chore: release 11.0.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#2727 ci: revert 'release-as'
  .github/workflows/release-please.yml
Labels: risk level (author): 1

#2728 chore: update changelog for 11.0.0
  CHANGELOG.md
Labels: risk level (author): 1

#2730 fix(components/modals): modal footers do not reserve space when an emtpy form error array is provided
  libs/components/modals/src/lib/modules/modal/modal-footer.component.html
  libs/components/modals/src/lib/modules/modal/modal.component.spec.ts
Labels: risk level (author): 1

#2689 feat: add support for `google-libphonenumber@3.2.38` and `intl-tel-input@24.4.0`
  libs/components/colorpicker/src/lib/modules/colorpicker/colorpicker.component.scss
  libs/components/errors/src/lib/modules/error/error.component.scss
  libs/components/lookup/package.json
  libs/components/lookup/src/lib/modules/country-field/country-field.component.scss
  libs/components/lookup/src/lib/modules/country-field/country-field.component.ts
  libs/components/phone-field/package.json
  libs/components/phone-field/src/lib/modules/phone-field/phone-field.component.html
  libs/components/phone-field/src/lib/modules/phone-field/phone-field.component.scss
  package-lock.json
  package.json
Labels: risk level (author): 2

#2732 ci: improve e2e affected checking
  .github/actions/e2e-affected/action.yml
  .github/workflows/e2e.yml
  apps/e2e/popovers-storybook-e2e/src/e2e/popover.component.cy.ts
  libs/sdk/e2e-schematics/src/workflow/percy-api/percy-api.spec.ts
  libs/sdk/e2e-schematics/src/workflow/percy-api/percy-api.ts
Labels: risk level (author): 1, skip e2e

#2736 ci: fix e2e build check
  .github/actions/e2e-affected/action.yml
  .github/workflows/e2e.yml
Labels: risk level (author): 1, skip e2e

#2735 ci: improve e2e affected checking (#2732)
  .github/actions/e2e-affected/action.yml
  .github/workflows/e2e.yml
  apps/e2e/popovers-storybook-e2e/src/e2e/popover.component.cy.ts
  libs/sdk/e2e-schematics/src/workflow/percy-api/percy-api.spec.ts
  libs/sdk/e2e-schematics/src/workflow/percy-api/percy-api.ts
Labels: risk level (author): 1, skip e2e

#2729 feat(components/popovers): implement disclosure pattern for popovers
  .eslintrc-overrides.json
  apps/code-examples/src/app/code-examples/popovers/popover/basic/demo.component.html
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-validator/ag-grid-cell-validator-tooltip.component.html
  libs/components/forms/testing/src/checkbox/checkbox-harness.spec.ts
  libs/components/forms/testing/src/checkbox/fixtures/checkbox-harness-test.component.html
  libs/components/forms/testing/src/field-group/field-group-harness.spec.ts
  libs/components/forms/testing/src/field-group/fixtures/field-group.component.fixture.ts
  libs/components/forms/testing/src/input-box/fixtures/input-box-harness-test.component.ts
  libs/components/forms/testing/src/input-box/input-box-harness.spec.ts
  libs/components/help-inline/src/lib/modules/help-inline/aria-label.pipe.ts
  libs/components/help-inline/src/lib/modules/help-inline/button-help-key.component.ts
  libs/components/help-inline/src/lib/modules/help-inline/button-popover.component.ts
  libs/components/help-inline/src/lib/modules/help-inline/help-inline-aria-controls.pipe.ts
  libs/components/help-inline/src/lib/modules/help-inline/help-inline-aria-expanded.pipe.ts
  libs/components/help-inline/src/lib/modules/help-inline/help-inline-aria-haspopup.pipe.ts
  libs/components/help-inline/src/lib/modules/help-inline/help-inline.component.html
  libs/components/help-inline/src/lib/modules/help-inline/help-inline.component.spec.ts
  libs/components/help-inline/src/lib/modules/help-inline/help-inline.component.ts
  libs/components/help-inline/testing/src/help-inline/help-inline-harness.spec.ts
  libs/components/popovers/src/lib/modules/popover/fixtures/popover-a11y.component.fixture.ts
  libs/components/popovers/src/lib/modules/popover/fixtures/popover.component.fixture.html
  libs/components/popovers/src/lib/modules/popover/popover-content.component.html
  libs/components/popovers/src/lib/modules/popover/popover-sr-pointer.service.ts
  libs/components/popovers/src/lib/modules/popover/popover.component.ts
  libs/components/popovers/src/lib/modules/popover/popover.directive.spec.ts
  libs/components/popovers/src/lib/modules/popover/popover.directive.ts
  libs/components/popovers/src/lib/modules/popover/types/popover-trigger.ts
  libs/components/popovers/testing/src/popover/harness/popover-harness.ts
Labels: risk level (author): 3

#2738 fix(components/datetime): notify date range value changes when switching between calculators without datepickers
  libs/components/datetime/src/lib/modules/date-range-picker/date-range-picker.component.spec.ts
  libs/components/datetime/src/lib/modules/date-range-picker/date-range-picker.component.ts
Labels: risk level (author): 2

#2737 chore: release 10.44.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease 10.x.x: pending

#2740 fix(components/datetime): notify date range value changes when switching between calculators without datepickers (#2738)
  libs/components/datetime/src/lib/modules/date-range-picker/date-range-picker.component.spec.ts
  libs/components/datetime/src/lib/modules/date-range-picker/date-range-picker.component.ts
Labels: risk level (author): 2

#2741 chore: changelog for 10.44.0 (#2737) 🍒
  CHANGELOG.md
Labels: risk level (author): 1, risk level (reviewer): 1

#2742 chore: release 11.1.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#2744 feat(components/phone-field): update revalidation to occur on input
  apps/playground/src/app/components/phone-field/phone-field/phone-field.component.html
  libs/components/phone-field/src/lib/modules/phone-field/phone-field-input.directive.ts
  libs/components/phone-field/src/lib/modules/phone-field/phone-field.component.spec.ts
Labels: risk level (author): 2

#2745 fix: update JSDocs to communicate that inline help features require a value for `labelText`
  libs/components/colorpicker/src/lib/modules/colorpicker/colorpicker.component.ts
  libs/components/datetime/src/lib/modules/date-range-picker/date-range-picker.component.ts
  libs/components/forms/src/lib/modules/checkbox/checkbox-group.component.ts
  libs/components/forms/src/lib/modules/checkbox/checkbox.component.ts
  libs/components/forms/src/lib/modules/field-group/field-group.component.ts
  libs/components/forms/src/lib/modules/file-attachment/file-attachment.component.ts
  libs/components/forms/src/lib/modules/file-attachment/file-drop.component.ts
  libs/components/forms/src/lib/modules/input-box/fixtures/input-box.component.fixture.html
  libs/components/forms/src/lib/modules/input-box/fixtures/input-box.component.fixture.ts
  libs/components/forms/src/lib/modules/input-box/input-box.component.html
  libs/components/forms/src/lib/modules/input-box/input-box.component.spec.ts
  libs/components/forms/src/lib/modules/input-box/input-box.component.ts
  libs/components/forms/src/lib/modules/radio/radio-group.component.ts
  libs/components/forms/src/lib/modules/radio/radio.component.ts
  libs/components/forms/src/lib/modules/toggle-switch/toggle-switch.component.ts
  libs/components/layout/src/lib/modules/box/box.component.ts
  libs/components/modals/src/lib/modules/modal/modal.component.ts
  libs/components/progress-indicator/src/lib/modules/progress-indicator/progress-indicator-item/progress-indicator-item.component.ts
  libs/components/text-editor/src/lib/modules/text-editor/text-editor.component.ts
  libs/components/tiles/src/lib/modules/tiles/tile/tile.component.ts
Labels: risk level (author): 2

#2749 chore: release 10.44.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease 10.x.x: pending

#2746 fix(sdk/eslint-config): remove utilization of the eslint deprecation plugin as it is not compatible with ESLint 9
  libs/components/packages/src/schematics/migrations/migration-collection.json
  libs/components/packages/src/schematics/migrations/update-11/remove-deprecation-eslint-plugin/remove-deprecation-eslint-plugin.schematic.spec.ts
  libs/components/packages/src/schematics/migrations/update-11/remove-deprecation-eslint-plugin/remove-deprecation-eslint-plugin.schematic.ts
  libs/sdk/eslint-config/package.json
  libs/sdk/eslint-config/peers.ts
  libs/sdk/eslint-config/recommended.json
  libs/sdk/eslint-config/src/schematics/ng-add/ng-add.schematic.spec.ts
  libs/sdk/eslint-config/src/schematics/ng-add/ng-add.schematic.ts
  libs/sdk/eslint-config/src/schematics/shared/rules/install-dependencies.ts
  libs/sdk/eslint-config/tsconfig.lib.json
Labels: risk level (author): 3

#2750 chore: changelog for 10.44.1 (#2749) 🍒
  CHANGELOG.md
Labels: risk level (author): 1, risk level (reviewer): 1

#2752 chore: release 11.2.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#2743 fix(components/ag-grid): sort direction button is not visible when sorting is not active on a column
  libs/components/ag-grid/src/lib/modules/ag-grid/header/header.component.html
  libs/components/ag-grid/src/lib/modules/ag-grid/header/header.component.scss
  libs/components/ag-grid/src/lib/modules/ag-grid/header/header.component.spec.ts
Labels: risk level (author): 2

#2755 fix(sdk/eslint-config): alternatively look for `angular-eslint` dependency
  libs/sdk/eslint-config/src/schematics/ng-add/ng-add.schematic.spec.ts
  libs/sdk/eslint-config/src/schematics/ng-add/ng-add.schematic.ts
Labels: risk level (author): 1

#2760 ci: fix e2e for pristine commits
  .github/actions/e2e-affected/action.yml
  apps/integration-e2e/src/e2e/modal-viewkept-toolbars.cy.ts
Labels: risk level (author): 1, skip e2e

#2748 feat(components/ag-grid): support changing the tab focus behavior
  apps/code-examples/src/app/code-examples/ag-grid/data-entry-grid/focus/data.ts
  apps/code-examples/src/app/code-examples/ag-grid/data-entry-grid/focus/demo.component.html
  apps/code-examples/src/app/code-examples/ag-grid/data-entry-grid/focus/demo.component.ts
  apps/code-examples/src/app/features/ag-grid.module.ts
  apps/code-examples/src/app/home/home.component.html
  libs/components/ag-grid/src/lib/modules/ag-grid/ag-grid-wrapper.component.spec.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/ag-grid-wrapper.component.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/ag-grid.service.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/types/last-focused.cell.ts
Labels: risk level (author): 1

#2757 fix(components/ag-grid): non-resizeable columns show a column divider but do not show a resize cursor or hover indicator
  apps/code-examples/src/app/app.component.html
  apps/code-examples/src/app/app.component.scss
  apps/code-examples/src/app/app.component.ts
  apps/code-examples/src/app/app.module.ts
  apps/code-examples/src/app/shared/theme-selector/theme-selector-spacing-value.ts
  apps/code-examples/src/app/shared/theme-selector/theme-selector-value.ts
  apps/code-examples/src/app/shared/theme-selector/theme-selector.component.html
  apps/code-examples/src/app/shared/theme-selector/theme-selector.component.ts
  libs/components/ag-grid/src/lib/styles/_base.scss
  libs/components/ag-grid/src/lib/styles/_modern.scss
Labels: risk level (author): 1

#2751 fix: update JSDocs to communicate that inline help features require a value for `labelText` (#2745)
  libs/components/colorpicker/src/lib/modules/colorpicker/colorpicker.component.ts
  libs/components/datetime/src/lib/modules/date-range-picker/date-range-picker.component.ts
  libs/components/forms/src/lib/modules/checkbox/checkbox-group.component.ts
  libs/components/forms/src/lib/modules/checkbox/checkbox.component.ts
  libs/components/forms/src/lib/modules/field-group/field-group.component.ts
  libs/components/forms/src/lib/modules/file-attachment/file-attachment/file-attachment.component.ts
  libs/components/forms/src/lib/modules/file-attachment/file-drop/file-drop.component.ts
  libs/components/forms/src/lib/modules/input-box/fixtures/input-box.component.fixture.html
  libs/components/forms/src/lib/modules/input-box/fixtures/input-box.component.fixture.ts
  libs/components/forms/src/lib/modules/input-box/input-box.component.html
  libs/components/forms/src/lib/modules/input-box/input-box.component.spec.ts
  libs/components/forms/src/lib/modules/input-box/input-box.component.ts
  libs/components/forms/src/lib/modules/radio/radio-group.component.ts
  libs/components/forms/src/lib/modules/radio/radio.component.ts
  libs/components/forms/src/lib/modules/toggle-switch/toggle-switch.component.ts
  libs/components/layout/src/lib/modules/box/box.component.ts
  libs/components/modals/src/lib/modules/modal/modal.component.ts
  libs/components/progress-indicator/src/lib/modules/progress-indicator/progress-indicator-item/progress-indicator-item.component.ts
  libs/components/text-editor/src/lib/modules/text-editor/text-editor.component.ts
  libs/components/tiles/src/lib/modules/tiles/tile/tile.component.ts
Labels: risk level (author): 2

#2753 chore: release 11.3.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#2739 feat(components/pages): add `helpKey` input to the page component
  apps/code-examples/src/app/code-examples/pages/page/list-page-list-layout-demo/demo.component.html
  apps/code-examples/src/app/code-examples/pages/page/list-page-list-layout-demo/demo.component.spec.ts
  apps/code-examples/src/app/code-examples/pages/page/list-page-tabs-layout-demo/demo.component.html
  apps/code-examples/src/app/code-examples/pages/page/list-page-tabs-layout-demo/demo.component.spec.ts
  apps/code-examples/src/app/code-examples/pages/page/record-page-blocks-layout-demo/demo.component.html
  apps/code-examples/src/app/code-examples/pages/page/record-page-blocks-layout-demo/demo.component.spec.ts
  apps/code-examples/src/app/code-examples/pages/page/record-page-tabs-layout-demo/demo.component.html
  apps/code-examples/src/app/code-examples/pages/page/record-page-tabs-layout-demo/demo.component.spec.ts
  apps/code-examples/src/app/code-examples/pages/page/split-view-page-fit-layout-demo/demo.component.html
  apps/code-examples/src/app/code-examples/pages/page/split-view-page-fit-layout-demo/demo.component.spec.ts
  libs/components/pages/src/lib/modules/page/page.component.spec.ts
  libs/components/pages/src/lib/modules/page/page.component.ts
Labels: risk level (author): 2

#2762 fix(components/datetime): show minimum and maximum date in error message
  libs/components/datetime/src/lib/modules/datepicker/datepicker-input-fuzzy.directive.ts
  libs/components/datetime/src/lib/modules/datepicker/datepicker-input.directive.ts
  libs/components/datetime/src/lib/modules/datepicker/datepicker.component.spec.ts
  libs/components/datetime/src/lib/modules/datepicker/fuzzy-date.service.ts
  libs/components/datetime/src/lib/modules/datepicker/fuzzy-datepicker.component.spec.ts
  libs/components/forms/src/assets/locales/resources_en_US.json
  libs/components/forms/src/lib/modules/form-error/form-errors.component.html
  libs/components/forms/src/lib/modules/form-error/form-errors.component.spec.ts
  libs/components/forms/src/lib/modules/shared/sky-forms-resources.module.ts
Labels: risk level (author): 1

#2754 feat(components/forms): add harnesses for radio and radio group components
  apps/code-examples/src/app/code-examples/forms/radio/standard/demo.component.html
  apps/code-examples/src/app/code-examples/forms/radio/standard/demo.component.spec.ts
  libs/components/forms/src/lib/modules/radio/radio-group.component.html
  libs/components/forms/src/lib/modules/radio/radio-group.component.scss
  libs/components/forms/src/lib/modules/radio/radio.component.html
  libs/components/forms/testing/src/public-api.ts
  libs/components/forms/testing/src/radio/fixtures/radio-harness-test.component.html
  libs/components/forms/testing/src/radio/fixtures/radio-harness-test.component.ts
  libs/components/forms/testing/src/radio/radio-group-harness-filters.ts
  libs/components/forms/testing/src/radio/radio-group-harness.spec.ts
  libs/components/forms/testing/src/radio/radio-group-harness.ts
  libs/components/forms/testing/src/radio/radio-harness-filters.ts
  libs/components/forms/testing/src/radio/radio-harness.spec.ts
  libs/components/forms/testing/src/radio/radio-harness.ts
  libs/components/forms/testing/src/radio/radio-label-harness.ts
Labels: risk level (author): 1

#2761 chore: release 11.4.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#2759 feat(components/ag-grid): support AG Grid 32.2
  apps/e2e/a11y-storybook/src/app/skip-link/skip-link.component.ts
  apps/e2e/action-bars-storybook/src/app/summary-action-bar/summary-action-bar.component.ts
  apps/e2e/ag-grid-storybook/src/app/ag-grid-widgets/ag-grid-widgets.component.ts
  apps/e2e/ag-grid-storybook/src/app/ag-grid/ag-grid-stories.component.ts
  apps/e2e/ag-grid-storybook/src/app/ag-grid/ag-grid-stories.module.ts
  apps/e2e/ag-grid-storybook/src/app/data-entry-grid/data-entry-grid.component.ts
  apps/e2e/ag-grid-storybook/src/app/data-entry-grid/data-entry-grid.module.ts
  apps/e2e/ag-grid-storybook/src/app/data-manager/data-manager.component.ts
  apps/e2e/avatar-storybook/src/app/avatar/avatar.component.ts
  apps/e2e/core-storybook/src/app/affix/affix.component.ts
  apps/e2e/data-manager-storybook/src/app/data-manager/data-manager.component.ts
  apps/e2e/datetime-storybook/src/app/date-range-picker/date-range-picker.component.ts
  apps/e2e/datetime-storybook/src/app/datepicker/datepicker.component.ts
  apps/e2e/errors-storybook/src/app/error/error.component.ts
  apps/e2e/flyout-storybook/src/app/flyout/flyout.component.ts
  apps/e2e/forms-storybook/src/app/selection-box/selection-box.component.ts
  apps/e2e/indicators-storybook/src/app/icon/icon.component.ts
  apps/e2e/layout-storybook/src/app/box/box.component.ts
  apps/e2e/lists-storybook/src/app/infinite-scroll/infinite-scroll.component.ts
  apps/e2e/lookup-storybook/src/app/autocomplete/autocomplete.component.ts
  apps/e2e/lookup-storybook/src/app/country-field/country-field.component.ts
  apps/e2e/lookup-storybook/src/app/lookup/lookup.component.ts
  apps/e2e/lookup-storybook/src/app/search/search.component.ts
  apps/e2e/navbar-storybook/src/app/navbar/navbar.component.ts
  apps/e2e/split-view-storybook/src/app/split-view/split-view.component.ts
  libs/components/ag-grid/package.json
  libs/components/ag-grid/src/lib/modules/ag-grid/ag-grid.service.spec.ts
  libs/components/ag-grid/src/lib/styles/_base.scss
  libs/components/ag-grid/src/lib/styles/_modern.scss
  libs/components/packages/package.json
  libs/components/packages/src/schematics/ag-grid-migrate/ag-grid-migrate.schematic.spec.ts
  libs/components/packages/src/schematics/ag-grid-migrate/ag-grid-migrate.schematic.ts
  libs/components/packages/src/schematics/migrations/update-11/ag-grid/ag-grid.schematic.spec.ts
  libs/components/packages/src/schematics/migrations/update-11/ag-grid/ag-grid.schematic.ts
  libs/components/storybook/src/index-components.ts
  libs/components/storybook/src/lib/preview-wrapper/preview-wrapper-decorators.ts
  package-lock.json
  package.json
  tsconfig.base.json
Labels: risk level (author): 1

#2766 fix(components/core): fix `SkyLogLevel` to support `--isolatedModules`
  libs/components/core/src/lib/modules/log/types/log-level.ts
Labels: risk level (author): 1

#2772 fix(components/colorpicker): set `aria-expanded` to false when closed with `cancel` button
  libs/components/colorpicker/src/lib/modules/colorpicker/colorpicker.component.spec.ts
  libs/components/colorpicker/src/lib/modules/colorpicker/colorpicker.component.ts
Labels: risk level (author): 2

#2771 feat(components/indicators): tokenize alert styling
  apps/e2e/indicators-storybook-e2e/src/e2e/alert.component.cy.ts
  apps/e2e/indicators-storybook/project.json
  apps/playground/project.json
  apps/playground/src/app/components/indicators/alert/alert.component.html
  apps/playground/src/app/shared/theme-selector/theme-selector-mode-value.ts
  apps/playground/src/app/shared/theme-selector/theme-selector-value.ts
  apps/playground/src/app/shared/theme-selector/theme-selector.component.html
  apps/playground/src/app/shared/theme-selector/theme-selector.component.ts
  libs/components/indicators/src/lib/modules/alert/alert.modern.component.scss
  libs/components/storybook/project.json
  libs/components/storybook/src/lib/preview-wrapper/preview-wrapper-global-types.ts
  libs/components/storybook/src/lib/preview-wrapper/preview-wrapper-theme-value.ts
  libs/components/storybook/src/lib/preview-wrapper/preview-wrapper.component.spec.ts
  libs/components/storybook/src/lib/preview-wrapper/preview-wrapper.component.ts
  libs/components/theme/package.json
  libs/components/theme/src/lib/styles/_compat-tokens-mixins.scss
  libs/components/theme/src/lib/styles/themes/modern/_box.scss
  libs/components/theme/src/lib/styles/themes/modern/_compat-tokens-mixins.scss
  libs/components/theme/src/lib/styles/themes/modern/_elevation.scss
  libs/components/theme/src/lib/styles/themes/modern/styles.scss
  libs/sdk/e2e-schematics/src/lib/e2e-variations/e2e-variations.spec.ts
  libs/sdk/e2e-schematics/src/lib/e2e-variations/e2e-variations.ts
  package-lock.json
  package.json
Labels: risk level (author): 2

#2779 ci: e2e mark affected on error
  .github/actions/e2e-affected/action.yml
  .github/workflows/e2e.yml
Labels: risk level (author): 1, skip e2e

#2778 feat(components/indicators): tokenize status indicator styles
  apps/e2e/indicators-storybook-e2e/src/e2e/status-indicator.component.cy.ts
  libs/components/indicators/src/lib/modules/status-indicator/status-indicator.component.html
  libs/components/indicators/src/lib/modules/status-indicator/status-indicator.component.scss
Labels: risk level (author): 2

#2775 feat(components/indicators): tokenize label styling
  apps/e2e/indicators-storybook-e2e/src/e2e/label.component.cy.ts
  apps/playground/src/app/shared/help.service.ts
  libs/components/indicators/src/lib/modules/label/label.component.scss
Labels: risk level (author): 2

#2774 feat(components/layout): tokenize box styling
  apps/e2e/layout-storybook-e2e/src/e2e/box.component.cy.ts
  apps/e2e/layout-storybook/project.json
  libs/components/layout/src/lib/modules/box/box-header.component.scss
  libs/components/layout/src/lib/modules/box/box.component.html
  libs/components/layout/src/lib/modules/box/box.component.scss
  libs/components/theme/src/lib/styles/_forms.scss
Labels: risk level (author): 2

#2776 feat(components/forms): add test harnesses for checkbox and checkbox group
  apps/code-examples/src/app/code-examples/forms/checkbox/basic/demo.component.html
  apps/code-examples/src/app/code-examples/forms/checkbox/basic/demo.component.spec.ts
  apps/playground/src/app/components/forms/checkbox/checkbox.component.html
  apps/playground/src/app/components/forms/checkbox/checkbox.component.ts
  libs/components/forms/src/assets/locales/resources_en_US.json
  libs/components/forms/src/lib/modules/checkbox/checkbox-group.component.html
  libs/components/forms/src/lib/modules/checkbox/checkbox-group.component.scss
  libs/components/forms/src/lib/modules/shared/sky-forms-resources.module.ts
  libs/components/forms/testing/src/checkbox/checkbox-group-harness.spec.ts
  libs/components/forms/testing/src/checkbox/checkbox-group-harness.ts
  libs/components/forms/testing/src/checkbox/checkbox-harness.spec.ts
  libs/components/forms/testing/src/checkbox/checkbox-harness.ts
  libs/components/forms/testing/src/checkbox/fixtures/checkbox-harness-test.component.html
  libs/components/forms/testing/src/checkbox/fixtures/checkbox-harness-test.component.ts
  libs/components/forms/testing/src/checkbox/fixtures/checkbox-harness-test.module.ts
  libs/components/forms/testing/src/public-api.ts
Labels: risk level (author): 2

#2768 feat(components/colorpicker): add colorpicker test harness
  apps/code-examples/src/app/code-examples/colorpicker/colorpicker/basic/demo.component.html
  apps/code-examples/src/app/code-examples/colorpicker/colorpicker/basic/demo.component.spec.ts
  libs/components/colorpicker/testing/src/colorpicker/colorpicker-dropdown-harness.filters.ts
  libs/components/colorpicker/testing/src/colorpicker/colorpicker-dropdown-harness.ts
  libs/components/colorpicker/testing/src/colorpicker/colorpicker-harness.filters.ts
  libs/components/colorpicker/testing/src/colorpicker/colorpicker-harness.spec.ts
  libs/components/colorpicker/testing/src/colorpicker/colorpicker-harness.ts
  libs/components/colorpicker/testing/src/public-api.ts
Labels: risk level (author): 1

#2773 chore: release 11.6.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#2786 fix(components/forms): legends for radio group and field group are properly detectable by screen readers
  libs/components/forms/src/lib/modules/field-group/field-group.component.html
  libs/components/forms/src/lib/modules/field-group/field-group.component.scss
  libs/components/forms/src/lib/modules/radio/radio-group.component.html
  libs/components/forms/src/lib/modules/radio/radio-group.component.scss
  libs/components/forms/src/lib/modules/radio/radio-group.component.spec.ts
  libs/components/forms/testing/src/field-group/field-group-harness.ts
  libs/components/forms/testing/src/radio/fixtures/radio-harness-test.component.html
  libs/components/forms/testing/src/radio/fixtures/radio-harness-test.component.ts
  libs/components/forms/testing/src/radio/radio-group-harness.spec.ts
  libs/components/forms/testing/src/radio/radio-group-harness.ts
Labels: risk level (author): 2
