Repository blackbaud/skyux, pull requests merged in 2024-04, with the labels that each got.

#2193 feat(components/text-editor): text editor form errors and error styling
  apps/code-examples/src/app/code-examples/text-editor/text-editor/demo.component.html
  apps/code-examples/src/app/code-examples/text-editor/text-editor/demo.component.ts
  apps/e2e/text-editor-storybook-e2e/src/e2e/text-editor.component.cy.ts
  apps/e2e/text-editor-storybook/src/app/text-editor/text-editor.component.ts
  libs/components/text-editor/src/assets/locales/resources_en_US.json
  libs/components/text-editor/src/lib/modules/shared/sky-text-editor-resources.module.ts
  libs/components/text-editor/src/lib/modules/text-editor/fixtures/text-editor.component.fixture.html
  libs/components/text-editor/src/lib/modules/text-editor/fixtures/text-editor.component.fixture.ts
  libs/components/text-editor/src/lib/modules/text-editor/text-editor.component.html
  libs/components/text-editor/src/lib/modules/text-editor/text-editor.component.scss
  libs/components/text-editor/src/lib/modules/text-editor/text-editor.component.spec.ts
  libs/components/text-editor/src/lib/modules/text-editor/text-editor.component.ts
  libs/components/text-editor/src/lib/modules/text-editor/text-editor.module.ts
Labels: risk level (author): 2

#2199 ci: improve e2e stability
  apps/e2e/avatar-storybook-e2e/src/e2e/avatar.component.cy.ts
  apps/e2e/avatar-storybook/src/app/avatar/avatar.component.html
  apps/e2e/avatar-storybook/src/app/avatar/avatar.component.ts
  apps/e2e/phone-field-storybook-e2e/src/e2e/phone-field.component.cy.ts
  apps/e2e/phone-field-storybook/src/app/phone-field/phone-field.component.html
  apps/e2e/phone-field-storybook/src/app/phone-field/phone-field.component.ts
Labels: risk level (author): 1

#2197 ci: update dev-infra to 10.0.0-alpha.1
  .github/workflows/release-please.yml
  package-lock.json
  package.json
Labels: risk level (author): 1

#2200 fix(components/indicators): adjust stacked icon position
  libs/components/indicators/src/lib/modules/icon/icon-stack.component.scss
Labels: risk level (author): 1

#2201 feat(components/forms): add form errors to file drop
  apps/playground/src/app/components/forms/file-attachment/file-attachment.component.html
  libs/components/forms/src/assets/locales/resources_en_US.json
  libs/components/forms/src/lib/modules/file-attachment/file-attachments.module.ts
  libs/components/forms/src/lib/modules/file-attachment/file-drop.component.html
  libs/components/forms/src/lib/modules/file-attachment/file-drop.component.spec.ts
  libs/components/forms/src/lib/modules/file-attachment/file-drop.component.ts
  libs/components/forms/src/lib/modules/file-attachment/file-validate-function.ts
  libs/components/forms/src/lib/modules/form-error/form-errors.component.html
  libs/components/forms/src/lib/modules/form-error/form-errors.component.spec.ts
  libs/components/forms/src/lib/modules/shared/sky-forms-resources.module.ts
Labels: risk level (author): 2

#2207 feat(components/datetime): add startAtDate to specify a date when the calendar initially opens
  apps/playground/src/app/components/datetime/datepicker/datepicker.component.html
  apps/playground/src/app/components/datetime/datepicker/datepicker.component.ts
  libs/components/datetime/src/lib/modules/datepicker/datepicker-calendar-inner.component.ts
  libs/components/datetime/src/lib/modules/datepicker/datepicker-calendar.component.html
  libs/components/datetime/src/lib/modules/datepicker/datepicker-calendar.component.spec.ts
  libs/components/datetime/src/lib/modules/datepicker/datepicker-calendar.component.ts
  libs/components/datetime/src/lib/modules/datepicker/datepicker-config.service.ts
  libs/components/datetime/src/lib/modules/datepicker/datepicker-input-fuzzy.directive.ts
  libs/components/datetime/src/lib/modules/datepicker/datepicker-input.directive.ts
  libs/components/datetime/src/lib/modules/datepicker/datepicker.component.html
  libs/components/datetime/src/lib/modules/datepicker/datepicker.component.spec.ts
  libs/components/datetime/src/lib/modules/datepicker/datepicker.component.ts
  libs/components/datetime/src/lib/modules/datepicker/fixtures/datepicker-calendar.component.fixture.html
  libs/components/datetime/src/lib/modules/datepicker/fixtures/datepicker-calendar.component.fixture.ts
  libs/components/datetime/src/lib/modules/datepicker/fixtures/datepicker-reactive.component.fixture.html
  libs/components/datetime/src/lib/modules/datepicker/fixtures/datepicker-reactive.component.fixture.ts
  libs/components/datetime/src/lib/modules/datepicker/fixtures/datepicker.component.fixture.html
  libs/components/datetime/src/lib/modules/datepicker/fixtures/datepicker.component.fixture.ts
  libs/components/datetime/src/lib/modules/datepicker/fixtures/fuzzy-datepicker-reactive.component.fixture.html
  libs/components/datetime/src/lib/modules/datepicker/fixtures/fuzzy-datepicker-reactive.component.fixture.ts
  libs/components/datetime/src/lib/modules/datepicker/fixtures/fuzzy-datepicker.component.fixture.html
  libs/components/datetime/src/lib/modules/datepicker/fixtures/fuzzy-datepicker.component.fixture.ts
  libs/components/datetime/src/lib/modules/datepicker/fuzzy-datepicker.component.spec.ts
Labels: risk level (author): 3

#2202 chore: release 10.2.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#2208 fix(components/text-editor): accessibility attributes are properly set on the editor element
  .gitignore
  libs/components/core/package.json
  libs/components/core/src/index.ts
  libs/components/core/src/lib/modules/forms-utility/forms-utility.ts
  libs/components/forms/src/lib/modules/checkbox/checkbox.component.ts
  libs/components/forms/src/lib/modules/file-attachment/file-attachment.component.ts
  libs/components/forms/src/lib/modules/radio/radio-group.component.ts
  libs/components/forms/src/lib/modules/radio/radio.component.ts
  libs/components/text-editor/src/lib/modules/shared/forms-utility.ts
  libs/components/text-editor/src/lib/modules/text-editor/menubar/text-editor-menubar.component.ts
  libs/components/text-editor/src/lib/modules/text-editor/services/text-editor-adapter.service.ts
  libs/components/text-editor/src/lib/modules/text-editor/text-editor.component.html
  libs/components/text-editor/src/lib/modules/text-editor/text-editor.component.spec.ts
  libs/components/text-editor/src/lib/modules/text-editor/text-editor.component.ts
  libs/components/text-editor/src/lib/modules/text-editor/toolbar/text-editor-toolbar.component.ts
Labels: risk level (author): 2

#2209 fix: documentation for inputs with argument objects is generated correctly
  package-lock.json
  package.json
Labels: risk level (author): 1

#2203 fix(components/forms): input box uses "disabled" styles when child form control is disabled
  .cspell.json
  apps/e2e/forms-storybook/src/app/input-box/input-box.component.html
  apps/e2e/forms-storybook/src/app/input-box/input-box.component.ts
  apps/playground/src/app/components/forms/input-box/input-box-disabled.component.ts
  apps/playground/src/app/components/forms/input-box/input-box-routing.module.ts
  libs/components/forms/src/lib/modules/input-box/input-box.component.html
  libs/components/forms/src/lib/modules/input-box/input-box.component.spec.ts
  libs/components/forms/src/lib/modules/input-box/input-box.component.ts
Labels: risk level (author): 3, risk level (reviewer): 3

#2212 feat(components/forms): add field group component
  apps/e2e/forms-storybook-e2e/src/e2e/field-group/field-group.component.cy.ts
  apps/e2e/forms-storybook/src/app/field-group/field-group.component.html
  apps/e2e/forms-storybook/src/app/field-group/field-group.component.scss
  apps/e2e/forms-storybook/src/app/field-group/field-group.component.stories.ts
  apps/e2e/forms-storybook/src/app/field-group/field-group.component.ts
  apps/playground/src/app/components/forms/field-group/field-group-routing.module.ts
  apps/playground/src/app/components/forms/field-group/field-group.component.html
  apps/playground/src/app/components/forms/field-group/field-group.component.ts
  apps/playground/src/app/components/forms/field-group/field-group.module.ts
  apps/playground/src/app/components/forms/forms.module.ts
  libs/components/forms/src/index.ts
  libs/components/forms/src/lib/modules/field-group/field-group.component.html
  libs/components/forms/src/lib/modules/field-group/field-group.component.spec.ts
  libs/components/forms/src/lib/modules/field-group/field-group.component.ts
  libs/components/forms/src/lib/modules/field-group/field-group.module.ts
  libs/components/forms/src/lib/modules/field-group/fixtures/field-group.component.fixture.html
  libs/components/forms/src/lib/modules/field-group/fixtures/field-group.component.fixture.ts
  libs/components/forms/testing/src/checkbox/checkbox-group-harness.ts
  libs/components/forms/testing/src/field-group/field-group-harness-filters.ts
  libs/components/forms/testing/src/field-group/field-group-harness.spec.ts
  libs/components/forms/testing/src/field-group/field-group-harness.ts
  libs/components/forms/testing/src/field-group/fixtures/field-group.component.fixture.html
  libs/components/forms/testing/src/field-group/fixtures/field-group.component.fixture.ts
Labels: risk level (author): 2

#2210 chore: release 10.3.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#2211 feat(components/forms): add `hintText` input to multi file attachment component
  apps/e2e/forms-storybook/src/app/file-attachment/file-attachment.component.html
  apps/playground/src/app/components/forms/file-attachment/file-attachment.component.html
  libs/components/forms/src/lib/modules/file-attachment/file-drop.component.html
  libs/components/forms/src/lib/modules/file-attachment/file-drop.component.scss
  libs/components/forms/src/lib/modules/file-attachment/file-drop.component.spec.ts
  libs/components/forms/src/lib/modules/file-attachment/file-drop.component.ts
Labels: risk level (author): 1

#2214 feat(components/forms): add heading semantic and styling inputs to field group
  apps/e2e/forms-storybook/src/app/field-group/field-group.component.html
  apps/e2e/forms-storybook/src/app/field-group/field-group.component.ts
  apps/playground/src/app/components/forms/field-group/field-group.component.html
  libs/components/forms/src/index.ts
  libs/components/forms/src/lib/modules/field-group/field-group-heading-level.ts
  libs/components/forms/src/lib/modules/field-group/field-group-heading-style.ts
  libs/components/forms/src/lib/modules/field-group/field-group.component.html
  libs/components/forms/src/lib/modules/field-group/field-group.component.scss
  libs/components/forms/src/lib/modules/field-group/field-group.component.spec.ts
  libs/components/forms/src/lib/modules/field-group/field-group.component.ts
  libs/components/forms/src/lib/modules/field-group/fixtures/field-group.component.fixture.html
  libs/components/forms/src/lib/modules/field-group/fixtures/field-group.component.fixture.ts
  libs/components/forms/testing/src/field-group/field-group-harness.spec.ts
  libs/components/forms/testing/src/field-group/field-group-harness.ts
  libs/components/forms/testing/src/field-group/fixtures/field-group.component.fixture.html
  libs/components/forms/testing/src/field-group/fixtures/field-group.component.fixture.ts
Labels: risk level (author): 1

#2215 chore: release 10.4.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#2162 feat(components/modals): add `SkyModalTestingController` to mock modals in tests
  apps/code-examples/src/app/code-examples/modals/modal/demo-controller.spec.ts
  libs/components/modals/src/index.ts
  libs/components/modals/src/lib/modules/modal/modal-service-interface.ts
  libs/components/modals/src/lib/modules/modal/modal.service.ts
  libs/components/modals/testing/src/modal/controller/modal-testing.controller.spec.ts
  libs/components/modals/testing/src/modal/controller/modal-testing.controller.ts
  libs/components/modals/testing/src/modal/controller/modal-testing.module.ts
  libs/components/modals/testing/src/modal/controller/modal-testing.service.ts
  libs/components/modals/testing/src/modal/controller/provide-modal-testing.ts
  libs/components/modals/testing/src/public-api.ts
Labels: risk level (author): 2

#2216 chore: release 10.5.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#2217 feat(components/theme): environment provider for modern theme
  libs/components/theme/src/index.ts
  libs/components/theme/src/lib/providers/provide-initial-theme.spec.ts
  libs/components/theme/src/lib/providers/provide-initial-theme.ts
Labels: risk level (author): 1

#2223 fix(components/modals): keep absolutely positioned background elements visible (#2219)
  apps/e2e/modals-storybook-e2e/src/e2e/modal.component.cy.ts
  apps/e2e/modals-storybook/src/app/modal/modal.component.html
  apps/e2e/modals-storybook/src/app/modal/modal.component.scss
  apps/e2e/modals-storybook/src/app/modal/modal.component.ts
  apps/e2e/modals-storybook/src/styles.scss
  libs/components/theme/src/lib/styles/_modals.scss
Labels: risk level (author): 4

#2220 fix(components/forms): checkbox group announces required state to screen readers
  apps/playground/src/app/components/forms/checkbox/checkbox.component.html
  apps/playground/src/app/components/forms/checkbox/checkbox.component.ts
  libs/components/forms/src/assets/locales/resources_en_US.json
  libs/components/forms/src/lib/modules/checkbox/checkbox-group.component.html
  libs/components/forms/src/lib/modules/checkbox/checkbox-group.component.spec.ts
  libs/components/forms/src/lib/modules/checkbox/checkbox-group.component.ts
  libs/components/forms/src/lib/modules/checkbox/fixtures/standard-checkbox-group.component.html
  libs/components/forms/src/lib/modules/checkbox/fixtures/standard-checkbox-group.component.ts
  libs/components/forms/src/lib/modules/shared/sky-forms-resources.module.ts
Labels: risk level (author): 2

#2218 fix(components/forms): single file attachment announces required state to screen readers
  libs/components/forms/src/assets/locales/resources_en_US.json
  libs/components/forms/src/lib/modules/file-attachment/file-attachment.component.html
  libs/components/forms/src/lib/modules/file-attachment/file-attachment.component.spec.ts
  libs/components/forms/src/lib/modules/shared/sky-forms-resources.module.ts
Labels: risk level (author): 2

#2222 chore: release 9.30.7
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease 9.x.x: pending

#2225 chore: release 9.30.7 (#2222)
  CHANGELOG.md
Labels: risk level (author): 1, risk level (reviewer): 1

#2221 chore: release 10.6.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#2226 fix(components/modals): throw when calling `SkyConfirmTestingController.close` with an invalid action
  libs/components/modals/testing/src/confirm/confirm-testing.controller.spec.ts
  libs/components/modals/testing/src/confirm/confirm-testing.service.ts
Labels: risk level (author): 2

#2227 fix(code-examples): move spec that uses SkyConfirmTestingController to another code example
  apps/code-examples/src/app/code-examples/modals/confirm/basic-with-controller/demo.component.spec.ts
  apps/code-examples/src/app/code-examples/modals/confirm/basic-with-controller/demo.component.ts
  apps/code-examples/src/app/code-examples/modals/confirm/basic-with-harness/demo.component.html
  apps/code-examples/src/app/code-examples/modals/confirm/basic-with-harness/demo.component.spec.ts
  apps/code-examples/src/app/code-examples/modals/confirm/basic-with-harness/demo.component.ts
  apps/code-examples/src/app/code-examples/modals/confirm/demo-controller.spec.ts
  apps/code-examples/src/app/features/modals.module.ts
  apps/code-examples/src/app/home/home.component.html
Labels: risk level (author): 1

#2228 fix(components/forms): radio group labels include an asterisk when the radio group is required
  libs/components/forms/src/lib/modules/radio/radio-group.component.html
  libs/components/forms/src/lib/modules/radio/radio-group.component.spec.ts
Labels: risk level (author): 1

#2230 fix(code-examples): move spec that uses SkyModalTestingController to another code example
  apps/code-examples/src/app/code-examples/modals/modal/basic-with-controller/demo.component.spec.ts
  apps/code-examples/src/app/code-examples/modals/modal/basic-with-controller/demo.component.ts
  apps/code-examples/src/app/code-examples/modals/modal/basic-with-controller/modal-context.ts
  apps/code-examples/src/app/code-examples/modals/modal/basic-with-controller/modal.component.ts
  apps/code-examples/src/app/code-examples/modals/modal/basic-with-harness/context.ts
  apps/code-examples/src/app/code-examples/modals/modal/basic-with-harness/data.service.ts
  apps/code-examples/src/app/code-examples/modals/modal/basic-with-harness/data.ts
  apps/code-examples/src/app/code-examples/modals/modal/basic-with-harness/demo.component.html
  apps/code-examples/src/app/code-examples/modals/modal/basic-with-harness/demo.component.spec.ts
  apps/code-examples/src/app/code-examples/modals/modal/basic-with-harness/demo.component.ts
  apps/code-examples/src/app/code-examples/modals/modal/basic-with-harness/modal.component.html
  apps/code-examples/src/app/code-examples/modals/modal/basic-with-harness/modal.component.ts
  apps/code-examples/src/app/code-examples/modals/modal/demo-controller.spec.ts
  apps/code-examples/src/app/code-examples/modals/modal/inline-help/context.ts
  apps/code-examples/src/app/code-examples/modals/modal/inline-help/data.service.ts
  apps/code-examples/src/app/code-examples/modals/modal/inline-help/data.ts
  apps/code-examples/src/app/code-examples/modals/modal/inline-help/demo.component.html
  apps/code-examples/src/app/code-examples/modals/modal/inline-help/demo.component.ts
  apps/code-examples/src/app/code-examples/modals/modal/inline-help/modal.component.html
  apps/code-examples/src/app/code-examples/modals/modal/inline-help/modal.component.ts
  apps/code-examples/src/app/code-examples/modals/modal/with-error/context.ts
  apps/code-examples/src/app/code-examples/modals/modal/with-error/data.service.ts
  apps/code-examples/src/app/code-examples/modals/modal/with-error/data.ts
  apps/code-examples/src/app/code-examples/modals/modal/with-error/demo.component.html
  apps/code-examples/src/app/code-examples/modals/modal/with-error/demo.component.spec.ts
  apps/code-examples/src/app/code-examples/modals/modal/with-error/demo.component.ts
  apps/code-examples/src/app/code-examples/modals/modal/with-error/modal.component.html
  apps/code-examples/src/app/code-examples/modals/modal/with-error/modal.component.ts
  apps/code-examples/src/app/features/modals.module.ts
  apps/code-examples/src/app/home/home.component.html
Labels: risk level (author): 1

#2232 fix(code-examples): set component selector for modal and confirm controller demos
  apps/code-examples/src/app/code-examples/modals/confirm/basic-with-controller/demo.component.ts
  apps/code-examples/src/app/code-examples/modals/modal/basic-with-controller/demo.component.ts
Labels: risk level (author): 1

#2233 chore: release 10.6.2
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#2234 fix(components/lists): update modern active filter button colors to match design guidelines
  libs/components/lists/src/lib/modules/filter/filter-button.component.html
  libs/components/lists/src/lib/modules/filter/filter-button.component.scss
Labels: risk level (author): 2

#2231 feat(components/datetime): add hint text input to date range picker
  apps/e2e/datetime-storybook/src/app/date-range-picker/date-range-picker.component.html
  apps/e2e/datetime-storybook/src/app/date-range-picker/date-range-picker.component.ts
  apps/playground/src/app/components/datetime/date-range-picker/date-range-picker.component.html
  libs/components/datetime/src/lib/modules/date-range-picker/date-range-picker.component.html
  libs/components/datetime/src/lib/modules/date-range-picker/date-range-picker.component.scss
  libs/components/datetime/src/lib/modules/date-range-picker/date-range-picker.component.spec.ts
  libs/components/datetime/src/lib/modules/date-range-picker/date-range-picker.component.ts
  libs/components/datetime/src/lib/modules/date-range-picker/date-range-picker.module.ts
  libs/components/datetime/src/lib/modules/date-range-picker/fixtures/date-range-picker.component.fixture.html
  libs/components/datetime/src/lib/modules/date-range-picker/fixtures/date-range-picker.component.fixture.ts
  libs/components/datetime/src/lib/modules/datepicker/datepicker-hint-token.ts
  libs/components/datetime/src/lib/modules/datepicker/datepicker.component.spec.ts
  libs/components/datetime/src/lib/modules/datepicker/datepicker.component.ts
  libs/components/forms/src/index.ts
  libs/components/forms/src/lib/modules/input-box/fixtures/input-box-host-service.component.fixture.ts
  libs/components/forms/src/lib/modules/input-box/input-box-hint-text.pipe.ts
  libs/components/forms/src/lib/modules/input-box/input-box-host.service.spec.ts
  libs/components/forms/src/lib/modules/input-box/input-box-host.service.ts
  libs/components/forms/src/lib/modules/input-box/input-box.component.html
  libs/components/forms/src/lib/modules/input-box/input-box.component.spec.ts
  libs/components/forms/src/lib/modules/input-box/input-box.component.ts
  libs/components/forms/src/lib/modules/input-box/input-box.module.ts
  libs/components/phone-field/src/lib/modules/phone-field/phone-field.component.spec.ts
Labels: risk level (author): 1

#2235 fix(components/forms): multi file attachment announces required state to screen readers
  .env
  apps/playground/src/app/components/forms/file-attachment/file-attachment.component.html
  apps/playground/src/app/components/forms/file-attachment/file-attachment.component.ts
  libs/components/forms/src/lib/modules/file-attachment/file-drop.component.html
  libs/components/forms/src/lib/modules/file-attachment/file-drop.component.spec.ts
  libs/components/forms/src/lib/modules/file-attachment/file-drop.component.ts
Labels: risk level (author): 2

#2239 feat: add support for @angular/core@17.3.4 and ng2-dragula@5.1.0
  libs/components/a11y/package.json
  libs/components/action-bars/package.json
  libs/components/ag-grid/package.json
  libs/components/angular-tree-component/package.json
  libs/components/animations/package.json
  libs/components/assets/package.json
  libs/components/autonumeric/package.json
  libs/components/avatar/package.json
  libs/components/colorpicker/package.json
  libs/components/config/package.json
  libs/components/core/package.json
  libs/components/data-manager/package.json
  libs/components/datetime/package.json
  libs/components/errors/package.json
  libs/components/flyout/package.json
  libs/components/forms/package.json
  libs/components/grids/package.json
  libs/components/i18n/package.json
  libs/components/indicators/package.json
  libs/components/inline-form/package.json
  libs/components/layout/package.json
  libs/components/list-builder-common/package.json
  libs/components/list-builder-view-checklist/package.json
  libs/components/list-builder-view-grids/package.json
  libs/components/list-builder/package.json
  libs/components/lists/package.json
  libs/components/lookup/package.json
  libs/components/modals/package.json
  libs/components/navbar/package.json
  libs/components/omnibar-interop/package.json
  libs/components/packages/package.json
  libs/components/packages/src/schematics/migrations/migration-collection.json
  libs/components/pages/package.json
  libs/components/phone-field/package.json
  libs/components/popovers/package.json
  libs/components/progress-indicator/package.json
  libs/components/router/package.json
  libs/components/select-field/package.json
  libs/components/split-view/package.json
  libs/components/storybook/package.json
  libs/components/tabs/package.json
  libs/components/text-editor/package.json
  libs/components/theme/package.json
  libs/components/tiles/package.json
  libs/components/toast/package.json
  libs/components/validation/package.json
  libs/sdk/e2e-schematics/package.json
  libs/sdk/eslint-config/package.json
  libs/sdk/prettier-schematics/package.json
  libs/sdk/testing/package.json
  package-lock.json
  package.json
Labels: risk level (author): 1

#2238 feat(components/theme): upgrade icons library to 7.1.0
  libs/components/packages/package.json
  libs/components/theme/package.json
  libs/components/theme/src/lib/styles/sky.scss
  package-lock.json
  package.json
Labels: risk level (author): 1

#2236 chore: release 10.7.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#2244 fix(components/forms): restore spacing between file attachment action buttons in mobile size
  libs/components/forms/src/lib/modules/file-attachment/file-drop.component.scss
Labels: risk level (author): 1

#2241 feat(components/forms): add `hintText` to file attachment
  apps/e2e/forms-storybook/src/app/single-file-attachment/single-file-attachment.component.html
  apps/playground/src/app/components/forms/file-attachment/file-attachment.component.html
  apps/playground/src/app/components/forms/file-attachment/file-attachment.component.ts
  apps/playground/src/app/components/forms/file-attachment/file-attachment.module.ts
  libs/components/forms/src/lib/modules/file-attachment/file-attachment.component.html
  libs/components/forms/src/lib/modules/file-attachment/file-attachment.component.scss
  libs/components/forms/src/lib/modules/file-attachment/file-attachment.component.spec.ts
  libs/components/forms/src/lib/modules/file-attachment/file-attachment.component.ts
  libs/components/forms/src/lib/modules/file-attachment/fixtures/file-attachment.component.fixture.html
  libs/components/forms/src/lib/modules/file-attachment/fixtures/file-attachment.component.fixture.ts
Labels: risk level (author): 1

#2250 fix(components/forms): fix hint text preview tag
  libs/components/datetime/src/lib/modules/date-range-picker/date-range-picker.component.ts
  libs/components/forms/src/lib/modules/field-group/field-group.component.ts
Labels: risk level (author): 1

#2251 feat(components/forms): add help inline inputs to checkbox group
  apps/e2e/forms-storybook/src/app/checkbox/checkbox.component.html
  apps/playground/src/app/components/forms/checkbox/checkbox.component.html
  libs/components/forms/src/lib/modules/checkbox/checkbox-group.component.html
  libs/components/forms/src/lib/modules/checkbox/checkbox-group.component.spec.ts
  libs/components/forms/src/lib/modules/checkbox/checkbox-group.component.ts
  libs/components/forms/testing/src/checkbox/checkbox-group-harness.spec.ts
  libs/components/forms/testing/src/checkbox/checkbox-group-harness.ts
  libs/components/forms/testing/src/checkbox/fixtures/checkbox-harness-test.component.html
  libs/components/forms/testing/src/checkbox/fixtures/checkbox-harness-test.component.ts
  libs/components/forms/testing/src/checkbox/fixtures/checkbox-harness-test.module.ts
  tsconfig.base.json
Labels: risk level (author): 2

#2248 feat(components/forms): add `hintText` to checkbox component
  apps/e2e/forms-storybook/src/app/checkbox/checkbox.component.html
  libs/components/forms/src/lib/modules/checkbox/checkbox.component.html
  libs/components/forms/src/lib/modules/checkbox/checkbox.component.scss
  libs/components/forms/src/lib/modules/checkbox/checkbox.component.spec.ts
  libs/components/forms/src/lib/modules/checkbox/checkbox.component.ts
  libs/components/forms/src/lib/modules/checkbox/checkbox.module.ts
  libs/components/forms/testing/src/checkbox/checkbox-harness.spec.ts
  libs/components/forms/testing/src/checkbox/checkbox-harness.ts
  libs/components/forms/testing/src/checkbox/fixtures/checkbox-harness-test.component.html
  libs/components/forms/testing/src/checkbox/fixtures/checkbox-harness-test.component.ts
  libs/components/theme/src/lib/styles/_custom-properties.scss
  libs/components/theme/src/lib/styles/_switch.scss
  libs/components/theme/src/lib/styles/_variables-private.scss
  libs/components/theme/src/lib/styles/themes/modern/_custom-properties.scss
  libs/components/theme/src/lib/styles/themes/modern/_switch.scss
Labels: risk level (author): 1

#2249 feat(components/forms): add `hintText` to radio button component
  apps/e2e/forms-storybook/src/app/radio-button/radio-button.component.html
  apps/e2e/forms-storybook/src/app/radio-button/radio-button.component.ts
  libs/components/forms/src/lib/modules/radio/fixtures/radio.component.fixture.html
  libs/components/forms/src/lib/modules/radio/fixtures/radio.component.fixture.ts
  libs/components/forms/src/lib/modules/radio/radio-group.component.spec.ts
  libs/components/forms/src/lib/modules/radio/radio.component.html
  libs/components/forms/src/lib/modules/radio/radio.component.scss
  libs/components/forms/src/lib/modules/radio/radio.component.spec.ts
  libs/components/forms/src/lib/modules/radio/radio.component.ts
Labels: risk level (author): 1

#2247 feat(components/forms): add help inline inputs to checkbox
  apps/e2e/forms-storybook-e2e/src/e2e/checkbox.component.cy.ts
  apps/e2e/forms-storybook/src/app/checkbox/checkbox.component.html
  apps/playground/src/app/components/forms/checkbox/checkbox.component.html
  libs/components/forms/src/lib/modules/checkbox/checkbox-label-text-label.component.scss
  libs/components/forms/src/lib/modules/checkbox/checkbox-label-text-label.component.ts
  libs/components/forms/src/lib/modules/checkbox/checkbox.component.html
  libs/components/forms/src/lib/modules/checkbox/checkbox.component.scss
  libs/components/forms/src/lib/modules/checkbox/checkbox.component.spec.ts
  libs/components/forms/src/lib/modules/checkbox/checkbox.component.ts
  libs/components/forms/src/lib/modules/checkbox/checkbox.module.ts
  libs/components/forms/src/lib/modules/file-attachment/file-attachment.component.ts
  libs/components/forms/testing/src/checkbox/checkbox-group-harness.ts
  libs/components/forms/testing/src/checkbox/checkbox-harness.spec.ts
  libs/components/forms/testing/src/checkbox/checkbox-harness.ts
  libs/components/forms/testing/src/checkbox/fixtures/checkbox-harness-test.component.html
Labels: risk level (author): 3

#2254 fix(components/packages): ignore `.nx/cache` directory
  libs/components/packages/collection.json
  libs/components/packages/src/schematics/migrations/migration-collection.json
  libs/components/packages/src/schematics/migrations/update-10/remove-nx-cache/remove-nx-cache.schematic.spec.ts
  libs/components/packages/src/schematics/migrations/update-10/remove-nx-cache/remove-nx-cache.schematic.ts
  libs/components/packages/src/schematics/ng-generate/remove-nx-cache/remove-nx-cache.schematic.spec.ts
  libs/components/packages/src/schematics/ng-generate/remove-nx-cache/remove-nx-cache.schematic.ts
  libs/components/packages/src/schematics/ng-generate/remove-nx-cache/schema.json
  libs/components/packages/src/schematics/rules/remove-nx-cache/remove-nx-cache.test.ts
  libs/components/packages/src/schematics/rules/remove-nx-cache/remove-nx-cache.ts
  scripts/postbuild-packages.ts
Labels: risk level (author): 1

#2243 chore: release 10.8.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#2253 feat(components/forms): require labelText for form field components in field group
  apps/playground/src/app/components/forms/field-group/field-group.component.html
  apps/playground/src/app/components/forms/field-group/field-group.component.ts
  libs/components/datetime/src/lib/modules/date-range-picker/date-range-picker.component.spec.ts
  libs/components/datetime/src/lib/modules/date-range-picker/date-range-picker.component.ts
  libs/components/forms/src/index.ts
  libs/components/forms/src/lib/modules/checkbox/checkbox.component.spec.ts
  libs/components/forms/src/lib/modules/checkbox/checkbox.component.ts
  libs/components/forms/src/lib/modules/field-group/field-group.component.ts
  libs/components/forms/src/lib/modules/file-attachment/file-attachment.component.spec.ts
  libs/components/forms/src/lib/modules/file-attachment/file-attachment.component.ts
  libs/components/forms/src/lib/modules/file-attachment/file-drop.component.spec.ts
  libs/components/forms/src/lib/modules/file-attachment/file-drop.component.ts
  libs/components/forms/src/lib/modules/input-box/input-box.component.spec.ts
  libs/components/forms/src/lib/modules/input-box/input-box.component.ts
  libs/components/forms/src/lib/modules/radio/radio-group.component.spec.ts
  libs/components/forms/src/lib/modules/radio/radio-group.component.ts
  libs/components/forms/src/lib/modules/radio/radio.component.spec.ts
  libs/components/forms/src/lib/modules/radio/radio.component.ts
  libs/components/forms/src/lib/modules/shared/form-field-label-text-required.service.spec.ts
  libs/components/forms/src/lib/modules/shared/form-field-label-text-required.service.ts
  libs/components/forms/src/lib/modules/toggle-switch/toggle-switch.component.spec.ts
  libs/components/forms/src/lib/modules/toggle-switch/toggle-switch.component.ts
  libs/components/text-editor/src/lib/modules/text-editor/text-editor.component.spec.ts
  libs/components/text-editor/src/lib/modules/text-editor/text-editor.component.ts
Labels: risk level (author): 2

#2255 feat(components/forms): add `hintText` to radio group component
  apps/e2e/forms-storybook/src/app/radio-button/radio-button.component.html
  apps/playground/src/app/components/forms/radio/radio.component.html
  libs/components/forms/src/lib/modules/radio/fixtures/radio-group-reactive.component.fixture.html
  libs/components/forms/src/lib/modules/radio/fixtures/radio-group-reactive.component.fixture.ts
  libs/components/forms/src/lib/modules/radio/radio-group.component.html
  libs/components/forms/src/lib/modules/radio/radio-group.component.scss
  libs/components/forms/src/lib/modules/radio/radio-group.component.spec.ts
  libs/components/forms/src/lib/modules/radio/radio-group.component.ts
Labels: risk level (author): 1

#2257 feat(components/text-editor): add hint text to text editor component
  apps/e2e/text-editor-storybook/src/app/text-editor/text-editor.component.html
  apps/e2e/text-editor-storybook/src/app/text-editor/text-editor.component.ts
  apps/playground/src/app/components/text-editor/text-editor/text-editor.component.html
  libs/components/text-editor/src/lib/modules/text-editor/fixtures/text-editor.component.fixture.html
  libs/components/text-editor/src/lib/modules/text-editor/fixtures/text-editor.component.fixture.ts
  libs/components/text-editor/src/lib/modules/text-editor/text-editor.component.html
  libs/components/text-editor/src/lib/modules/text-editor/text-editor.component.spec.ts
  libs/components/text-editor/src/lib/modules/text-editor/text-editor.component.ts
Labels: risk level (author): 1

#2252 feat(components/forms): add hint text to checkbox group component
  apps/e2e/forms-storybook/src/app/checkbox/checkbox.component.html
  apps/playground/src/app/components/forms/checkbox/checkbox.component.html
  libs/components/forms/src/lib/modules/checkbox/checkbox-group.component.html
  libs/components/forms/src/lib/modules/checkbox/checkbox-group.component.spec.ts
  libs/components/forms/src/lib/modules/checkbox/checkbox-group.component.ts
  libs/components/forms/src/lib/modules/checkbox/fixtures/standard-checkbox-group.component.html
  libs/components/forms/src/lib/modules/checkbox/fixtures/standard-checkbox-group.component.ts
  libs/components/forms/testing/src/checkbox/checkbox-group-harness.spec.ts
  libs/components/forms/testing/src/checkbox/checkbox-group-harness.ts
  libs/components/forms/testing/src/checkbox/fixtures/checkbox-harness-test.component.html
  libs/components/forms/testing/src/checkbox/fixtures/checkbox-harness-test.component.ts
Labels: risk level (author): 1

#2256 chore: release 10.9.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#2262 feat(components/forms): add help inline to toggle switch
  apps/e2e/forms-storybook/src/app/toggle-switch/toggle-switch.component.html
  apps/playground/src/app/components/forms/toggle-switch/toggle-switch.component.html
  libs/components/forms/src/lib/modules/toggle-switch/fixtures/toggle-switch.component.fixture.html
  libs/components/forms/src/lib/modules/toggle-switch/fixtures/toggle-switch.component.fixture.ts
  libs/components/forms/src/lib/modules/toggle-switch/toggle-switch.component.html
  libs/components/forms/src/lib/modules/toggle-switch/toggle-switch.component.spec.ts
  libs/components/forms/src/lib/modules/toggle-switch/toggle-switch.component.ts
  libs/components/forms/src/lib/modules/toggle-switch/toggle-switch.module.ts
Labels: risk level (author): 2

#2264 fix(code-examples): update single fite attachment examples to only allow data urls
  apps/code-examples/src/app/code-examples/forms/single-file-attachment/basic/demo.component.ts
  apps/code-examples/src/app/code-examples/forms/single-file-attachment/inline-help/demo.component.ts
Labels: risk level (author): 1

#2261 feat(components/datetime): add help inline inputs to date range picker
  apps/e2e/datetime-storybook-e2e/src/e2e/date-range-picker.component.cy.ts
  apps/e2e/datetime-storybook/src/app/date-range-picker/date-range-picker.component.html
  apps/e2e/datetime-storybook/src/app/date-range-picker/date-range-picker.component.ts
  libs/components/datetime/src/lib/modules/date-range-picker/date-range-picker.component.html
  libs/components/datetime/src/lib/modules/date-range-picker/date-range-picker.component.spec.ts
  libs/components/datetime/src/lib/modules/date-range-picker/date-range-picker.component.ts
  libs/components/datetime/src/lib/modules/date-range-picker/fixtures/date-range-picker.component.fixture.html
  libs/components/datetime/src/lib/modules/date-range-picker/fixtures/date-range-picker.component.fixture.ts
  libs/components/forms/testing/project.json
  libs/components/help-inline/package.json
Labels: risk level (author): 2
