Repository blackbaud/skyux, pull requests merged in 2024-11, with the labels that each got.

#2882 feat(components/datetime): tokenize date range picker styles
  apps/e2e/datetime-storybook-e2e/src/e2e/date-range-picker.component.cy.ts
  apps/e2e/datetime-storybook/project.json
  libs/components/datetime/src/lib/modules/date-range-picker/date-range-picker.component.scss
  libs/components/datetime/src/lib/modules/date-range-picker/date-range-picker.component.spec.ts
  libs/components/datetime/src/lib/modules/date-range-picker/date-range-picker.component.ts
  libs/components/forms/src/lib/modules/checkbox/checkbox-group.component.scss
  libs/components/forms/src/lib/modules/checkbox/checkbox-group.component.spec.ts
  libs/components/forms/src/lib/modules/checkbox/checkbox-group.component.ts
  libs/components/forms/src/lib/modules/checkbox/checkbox.component.spec.ts
  libs/components/forms/src/lib/modules/checkbox/checkbox.component.ts
  libs/components/forms/src/lib/modules/checkbox/checkbox.default.component.scss
  libs/components/forms/src/lib/modules/checkbox/checkbox.modern.component.scss
  libs/components/forms/src/lib/modules/radio/radio-group.component.scss
  libs/components/forms/src/lib/modules/radio/radio-group.component.spec.ts
  libs/components/forms/src/lib/modules/radio/radio-group.component.ts
  libs/components/forms/testing/src/checkbox/checkbox-group-harness.ts
  libs/components/forms/testing/src/checkbox/checkbox-harness.ts
  libs/components/forms/testing/src/radio/radio-group-harness.ts
  libs/components/theme/src/lib/styles/themes/modern/_forms.scss
Labels: risk level (author): 2

#2883 feat(components/indicators): tokenize text highlight styles
  apps/e2e/indicators-storybook-e2e/src/e2e/text-highlight.component.cy.ts
  apps/e2e/indicators-storybook/src/app/text-highlight/text-highlight.component.html
  libs/components/theme/src/lib/styles/themes/modern/_theme.scss
Labels: risk level (author): 2

#2877 chore: release 11.19.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#2889 fix(components/ag-grid): handle and set last focused cell context correctly
  libs/components/ag-grid/src/lib/modules/ag-grid/ag-grid-wrapper.component.spec.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/ag-grid-wrapper.component.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/ag-grid.service.ts
Labels: risk level (author): 1

#2890 fix(components/phone-field): move phone field testing artifacts to correct location
  libs/components/phone-field/testing/src/phone-field/fixtures/phone-field-harness-test.component.ts
  libs/components/phone-field/testing/src/phone-field/phone-field-fixture.spec.ts
  libs/components/phone-field/testing/src/phone-field/phone-field-fixture.ts
  libs/components/phone-field/testing/src/phone-field/phone-field-harness-filters.ts
  libs/components/phone-field/testing/src/phone-field/phone-field-harness.spec.ts
  libs/components/phone-field/testing/src/phone-field/phone-field-harness.ts
  libs/components/phone-field/testing/src/phone-field/phone-field-input-harness.ts
  libs/components/phone-field/testing/src/phone-field/phone-field-testing.module.ts
  libs/components/phone-field/testing/src/public-api.ts
Labels: risk level (author): 1

#2891 fix(components/lists): disable repeater item selection checkbox
  apps/e2e/lists-storybook/src/app/repeater/repeater.component.html
  libs/components/lists/src/lib/modules/repeater/repeater-item.component.html
Labels: risk level (author): 1

#2893 fix(components/ag-grid): hidden header showing as `undefined`
  libs/components/ag-grid/src/lib/modules/ag-grid/header/header.component.html
  libs/components/ag-grid/src/lib/modules/ag-grid/types/header-group-info.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/types/header-group-params.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/types/header-info.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/types/header-params.ts
Labels: risk level (author): 1

#2894 chore: release 11.19.2
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#2895 docs(components/ag-grid): simplify reference in docs
  libs/components/ag-grid/src/lib/modules/ag-grid/types/header-group-info.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/types/header-info.ts
Labels: risk level (author): 1

#2896 chore: release 11.20.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#2885 feat(components/datetime): add date range picker harness
  apps/code-examples/src/app/code-examples/datetime/date-range-picker/basic/demo.component.html
  apps/code-examples/src/app/code-examples/datetime/date-range-picker/basic/demo.component.spec.ts
  apps/code-examples/src/app/code-examples/datetime/date-range-picker/basic/demo.component.ts
  libs/components/datetime/src/lib/modules/date-range-picker/date-range-picker.component.html
  libs/components/datetime/testing/src/date-range-picker/date-range-picker-harness.filters.ts
  libs/components/datetime/testing/src/date-range-picker/date-range-picker-harness.spec.ts
  libs/components/datetime/testing/src/date-range-picker/date-range-picker-harness.ts
  libs/components/datetime/testing/src/datepicker/datepicker-harness-input.ts
  libs/components/datetime/testing/src/datepicker/datepicker-harness.spec.ts
  libs/components/datetime/testing/src/datepicker/datepicker-harness.ts
  libs/components/datetime/testing/src/public-api.ts
  libs/components/forms/src/lib/modules/file-attachment/file-attachment/file-attachment.component.html
  libs/components/forms/src/lib/modules/input-box/input-box.component.html
  libs/components/forms/testing/src/input-box/input-box-harness.ts
Labels: risk level (author): 2

#2898 chore: release 11.21.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#2880 feat(components/datetime): tokenize datepicker styles
  apps/e2e/datetime-storybook-e2e/src/e2e/datepicker.component.cy.ts
  libs/components/datetime/src/lib/modules/datepicker/datepicker-calendar-inner.component.html
  libs/components/datetime/src/lib/modules/datepicker/datepicker-calendar-inner.component.scss
  libs/components/datetime/src/lib/modules/datepicker/datepicker.component.scss
  libs/components/datetime/src/lib/modules/datepicker/daypicker-button.component.scss
  libs/components/datetime/src/lib/modules/datepicker/daypicker.component.html
  libs/components/datetime/testing/src/datepicker/datepicker-calendar-harness.ts
  libs/components/forms/src/lib/modules/input-box/input-box.component.scss
Labels: risk level (author): 3

#2902 feat(components/lookup): tokenize autocomplete styles
  apps/e2e/lookup-storybook-e2e/src/e2e/autocomplete.component.cy.ts
  libs/components/lookup/src/lib/modules/autocomplete/autocomplete.component.html
  libs/components/lookup/src/lib/modules/autocomplete/autocomplete.component.scss
  libs/components/lookup/testing/src/autocomplete/autocomplete-harness.ts
Labels: risk level (author): 2

#2905 fix(components/i18n): remove deprecated features from generated resources module
  libs/components/a11y/src/lib/modules/shared/sky-a11y-resources.module.ts
  libs/components/action-bars/src/lib/modules/shared/sky-action-bars-resources.module.ts
  libs/components/ag-grid/src/lib/modules/shared/sky-ag-grid-resources.module.ts
  libs/components/angular-tree-component/src/lib/modules/shared/sky-angular-tree-component-resources.module.ts
  libs/components/avatar/src/lib/modules/shared/sky-avatar-resources.module.ts
  libs/components/colorpicker/src/lib/modules/shared/sky-colorpicker-resources.module.ts
  libs/components/core/src/lib/modules/shared/sky-core-resources.module.ts
  libs/components/data-manager/src/lib/modules/shared/sky-data-manager-resources.module.ts
  libs/components/datetime/src/lib/modules/shared/sky-datetime-resources.module.ts
  libs/components/errors/src/lib/modules/shared/sky-errors-resources.module.ts
  libs/components/flyout/src/lib/modules/shared/sky-flyout-resources.module.ts
  libs/components/forms/src/lib/modules/shared/sky-forms-resources.module.ts
  libs/components/grids/src/lib/modules/shared/sky-grids-resources.module.ts
  libs/components/help-inline/src/lib/modules/shared/sky-help-inline-resources.module.ts
  libs/components/i18n/schematics/ng-generate/lib-resources-module/files/__name@dasherize__-resources.module.ts.template
  libs/components/i18n/schematics/ng-generate/lib-resources-module/lib-resources-module.schematic.spec.ts
  libs/components/indicators/src/lib/modules/shared/sky-indicators-resources.module.ts
  libs/components/inline-form/src/lib/modules/shared/sky-inline-form-resources.module.ts
  libs/components/layout/src/lib/modules/shared/sky-layout-resources.module.ts
  libs/components/list-builder-view-grids/src/lib/modules/shared/sky-list-builder-view-grids-resources.module.ts
  libs/components/list-builder/src/lib/modules/shared/sky-list-builder-resources.module.ts
  libs/components/lists/src/lib/modules/shared/sky-lists-resources.module.ts
  libs/components/lookup/src/lib/modules/shared/sky-lookup-resources.module.ts
  libs/components/modals/src/lib/modules/shared/sky-modals-resources.module.ts
  libs/components/pages/src/lib/modules/shared/sky-pages-resources.module.ts
  libs/components/phone-field/src/lib/modules/shared/sky-phone-field-resources.module.ts
  libs/components/popovers/src/lib/modules/shared/sky-popovers-resources.module.ts
  libs/components/progress-indicator/src/lib/modules/shared/sky-progress-indicator-resources.module.ts
  libs/components/select-field/src/lib/modules/shared/sky-select-field-resources.module.ts
  libs/components/split-view/src/lib/modules/shared/sky-split-view-resources.module.ts
  libs/components/tabs/src/lib/modules/shared/sky-tabs-resources.module.ts
  libs/components/text-editor/src/lib/modules/shared/sky-text-editor-resources.module.ts
  libs/components/tiles/src/lib/modules/shared/sky-tiles-resources.module.ts
  libs/components/toast/src/lib/modules/shared/sky-toast-resources.module.ts
Labels: risk level (author): 3

#2907 ci: update `nx` to `20.1.0`
  eslint-apps.config.js
  eslint-libs.config.js
  libs/sdk/eslint-config/recommended.json
  libs/sdk/skyux-eslint/src/configs/ts-base-type-checked.ts
  nx.json
  package-lock.json
  package.json
Labels: risk level (author): 1

#2904 ci: verify package group
  .github/workflows/ci.yml
  libs/components/datetime/eslint.config.js
  libs/components/datetime/project.json
  libs/components/datetime/src/lib/modules/datepicker/datepicker-input-fuzzy.directive.ts
  libs/components/datetime/src/lib/modules/datepicker/datepicker-input.directive.ts
  libs/components/packages/package.json
  libs/sdk/tools/jest.config.ts
  libs/sdk/tools/src/generators/update-dependencies/generator.spec.ts
  libs/sdk/tools/src/generators/update-dependencies/generator.ts
Labels: risk level (author): 1

#2901 chore: release 11.22.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#2900 fix(components/datetime): timepicker minute picker highlights closest passed time
  libs/components/datetime/src/lib/modules/timepicker/timepicker.component.html
  libs/components/datetime/src/lib/modules/timepicker/timepicker.component.spec.ts
  libs/components/datetime/src/lib/modules/timepicker/timepicker.component.ts
Labels: risk level (author): 1

#2910 fix(components/datetime): date range picker visually invalid on custom errors
  apps/playground/src/app/components/datetime/date-range-picker/date-range-picker.component.html
  apps/playground/src/app/components/datetime/date-range-picker/date-range-picker.component.ts
  libs/components/datetime/src/lib/modules/date-range-picker/date-range-picker.component.spec.ts
  libs/components/datetime/src/lib/modules/date-range-picker/date-range-picker.component.ts
  libs/components/datetime/src/lib/modules/date-range-picker/fixtures/date-range-picker.component.fixture.html
Labels: risk level (author): 2

#2911 feat(components/datetime): tokenize timepicker styles
  apps/e2e/datetime-storybook-e2e/src/e2e/timepicker.component.cy.ts
  libs/components/datetime/src/lib/modules/timepicker/timepicker.component.scss
Labels: risk level (author): 2

#2913 feat(components/lookup): tokenize lookup styles
  apps/e2e/lookup-storybook-e2e/src/e2e/lookup.component.cy.ts
  libs/components/lookup/src/lib/modules/autocomplete/autocomplete.component.scss
  libs/components/lookup/src/lib/modules/lookup/lookup.component.scss
Labels: risk level (author): 2

#2915 refactor: update design tokens and update selected border tokens to their new name
  libs/components/datetime/src/lib/modules/datepicker/datepicker-calendar-inner.component.scss
  libs/components/datetime/src/lib/modules/timepicker/timepicker.component.scss
  libs/components/forms/src/lib/modules/toggle-switch/toggle-switch.component.scss
  libs/components/indicators/src/lib/modules/tokens/token.component.scss
  libs/components/lists/src/lib/modules/sort/sort-item.component.scss
  libs/components/lookup/src/lib/modules/search/search.component.scss
  libs/components/popovers/src/lib/modules/dropdown/dropdown.component.scss
  libs/components/theme/package.json
  libs/components/theme/src/lib/styles/themes/modern/_buttons.scss
  libs/components/theme/src/lib/styles/themes/modern/_switch.scss
  package-lock.json
  package.json
Labels: risk level (author): 1

#2914 feat(components/lookup): tokenize country field styles
  apps/e2e/lookup-storybook-e2e/src/e2e/country-field.component.cy.ts
  libs/components/lookup/src/lib/modules/country-field/country-field.component.html
  libs/components/lookup/src/lib/modules/country-field/country-field.component.scss
  libs/components/lookup/src/lib/modules/country-field/country-field.component.spec.ts
Labels: risk level (author): 2

#2909 fix(components/datetime): datepicker emits touched status when focus leaves composite control
  libs/components/datetime/src/lib/modules/date-range-picker/date-range-picker.component.spec.ts
  libs/components/datetime/src/lib/modules/datepicker/datepicker-host.service.spec.ts
  libs/components/datetime/src/lib/modules/datepicker/datepicker-host.service.ts
  libs/components/datetime/src/lib/modules/datepicker/datepicker-input-fuzzy.directive.ts
  libs/components/datetime/src/lib/modules/datepicker/datepicker-input.directive.ts
  libs/components/datetime/src/lib/modules/datepicker/datepicker.component.spec.ts
  libs/components/datetime/src/lib/modules/datepicker/datepicker.component.ts
  libs/components/datetime/src/lib/modules/datepicker/fuzzy-datepicker.component.spec.ts
  libs/components/datetime/testing/src/datepicker/datepicker-harness.spec.ts
  libs/components/datetime/testing/src/datepicker/datepicker-harness.ts
  libs/components/datetime/testing/src/datepicker/datepicker-input-harness.ts
  libs/components/datetime/testing/src/public-api.ts
Labels: risk level (author): 3

#2912 chore: release 11.23.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#2918 feat(components/phone-field): tokenize phone field styles
  apps/e2e/phone-field-storybook-e2e/src/e2e/phone-field.component.cy.ts
  apps/e2e/phone-field-storybook/project.json
  libs/components/forms/src/lib/modules/input-box/input-box.component.scss
  libs/components/phone-field/src/lib/modules/phone-field/phone-field.component.scss
  libs/components/theme/src/lib/styles/themes/modern/_forms.scss
Labels: risk level (author): 2

#2919 chore: release 11.24.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending
