Repository blackbaud/skyux, pull requests merged in 2024-05, with the labels that each got.

#2266 fix(components/ag-grid): unable to edit currency cell
  apps/code-examples/src/app/code-examples/ag-grid/data-entry-grid/basic/demo.component.ts
  apps/code-examples/src/app/code-examples/ag-grid/data-entry-grid/data-manager-added/view-grid.component.ts
  apps/code-examples/src/app/code-examples/ag-grid/data-entry-grid/inline-help/demo.component.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/ag-grid.service.spec.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/ag-grid.service.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-editors/cell-editor-autocomplete/cell-editor-autocomplete.component.spec.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-editors/cell-editor-autocomplete/cell-editor-autocomplete.component.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-editors/cell-editor-currency/cell-editor-currency.component.html
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-editors/cell-editor-currency/cell-editor-currency.component.spec.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-editors/cell-editor-currency/cell-editor-currency.component.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-editors/cell-editor-datepicker/cell-editor-datepicker.component.spec.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-editors/cell-editor-datepicker/cell-editor-datepicker.component.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-editors/cell-editor-lookup/cell-editor-lookup.component.spec.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-editors/cell-editor-lookup/cell-editor-lookup.component.ts
Labels: risk level (author): 1

#2267 fix(components/modals): skyConfirmTestingService verify custom button configurations
  libs/components/modals/testing/src/confirm/confirm-testing.controller.spec.ts
  libs/components/modals/testing/src/confirm/confirm-testing.service.ts
Labels: risk level (author): 1

#2272 feat(components/colorpicker): add help inline inputs to colorpicker
  apps/e2e/colorpicker-storybook/src/app/colorpicker/colorpicker.component.html
  apps/playground/src/app/components/colorpicker/colorpicker/colorpicker.component.html
  libs/components/colorpicker/package.json
  libs/components/colorpicker/src/lib/modules/colorpicker/colorpicker.component.html
  libs/components/colorpicker/src/lib/modules/colorpicker/colorpicker.component.spec.ts
  libs/components/colorpicker/src/lib/modules/colorpicker/colorpicker.component.ts
  libs/components/colorpicker/src/lib/modules/colorpicker/colorpicker.module.ts
  libs/components/colorpicker/src/lib/modules/colorpicker/fixtures/colorpicker-component.fixture.html
  libs/components/colorpicker/src/lib/modules/colorpicker/fixtures/colorpicker-component.fixture.ts
Labels: risk level (author): 2

#2263 feat(components/forms): add help inline popover to file attachment
  apps/e2e/forms-storybook/src/app/file-attachment/file-attachment.component.html
  apps/e2e/forms-storybook/src/app/file-attachment/file-attachment.component.ts
  apps/playground/src/app/components/forms/file-attachment/file-attachment.component.html
  apps/playground/src/app/components/forms/file-attachment/file-attachment.module.ts
  libs/components/forms/src/lib/modules/file-attachment/file-drop.component.html
  libs/components/forms/src/lib/modules/file-attachment/file-drop.component.spec.ts
  libs/components/forms/src/lib/modules/file-attachment/file-drop.component.ts
Labels: risk level (author): 2

#2265 chore: release 10.10.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#2271 feat(components/forms): add help inline inputs to radio button
  apps/e2e/forms-storybook/src/app/radio-button/radio-button.component.html
  apps/playground/src/app/components/forms/radio/radio.component.html
  libs/components/forms/src/lib/modules/radio/fixtures/radio.component.fixture.html
  libs/components/forms/src/lib/modules/radio/fixtures/radio.component.fixture.ts
  libs/components/forms/src/lib/modules/radio/radio.component.html
  libs/components/forms/src/lib/modules/radio/radio.component.scss
  libs/components/forms/src/lib/modules/radio/radio.component.spec.ts
  libs/components/forms/src/lib/modules/radio/radio.component.ts
  libs/components/forms/src/lib/modules/radio/radio.module.ts
Labels: risk level (author): 3

#2273 fix(components/layout): box sets the internal content info provider only on the box controls
  apps/playground/src/app/components/layout/box/box.component.html
  apps/playground/src/app/components/layout/box/box.component.ts
  apps/playground/src/app/components/layout/box/box.module.ts
  libs/components/layout/src/lib/modules/box/box-controls.component.ts
  libs/components/layout/src/lib/modules/box/box.component.spec.ts
  libs/components/layout/src/lib/modules/box/box.component.ts
  libs/components/layout/src/lib/modules/box/fixtures/box.component.fixture.html
  libs/components/layout/src/lib/modules/box/fixtures/box.component.fixture.ts
Labels: risk level (author): 2

#2277 fix(components/forms): add error styling to checkboxes
  apps/playground/src/app/components/forms/checkbox/checkbox.component.html
  libs/components/forms/src/lib/modules/checkbox/checkbox.component.html
  libs/components/theme/src/lib/styles/_switch.scss
  libs/components/theme/src/lib/styles/themes/modern/_switch.scss
Labels: risk level (author): 2

#2274 chore: release 10.11.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#2282 fix(components/forms): move radio help key outside label
  libs/components/forms/src/lib/modules/radio/radio.component.html
  libs/components/forms/src/lib/modules/radio/radio.component.scss
  libs/components/forms/src/lib/modules/radio/radio.component.spec.ts
Labels: risk level (author): 1

#2279 fix(sdk/eslint-config): update `eslint-plugin-deprecation` dependency
  libs/sdk/eslint-config/package.json
  libs/sdk/eslint-config/src/schematics/ng-add/ng-add.schematic.spec.ts
  libs/sdk/eslint-config/src/schematics/shared/rules/install-dependencies.ts
Labels: risk level (author): 1

#2280 feat(components/packages): configure commonjs dependencies
  libs/components/packages/src/schematics/ng-add/ng-add.schematic.ts
  libs/components/packages/src/schematics/rules/add-commonjs-config.spec.ts
  libs/components/packages/src/schematics/rules/add-commonjs-config.ts
Labels: risk level (author): 1

#2285 feat(components/datetime): add stacked input to date range picker
  apps/e2e/datetime-storybook/src/app/date-range-picker/date-range-picker.component.html
  apps/playground/src/app/components/datetime/date-range-picker/date-range-picker.component.html
  libs/components/datetime/src/lib/modules/date-range-picker/date-range-picker.component.spec.ts
  libs/components/datetime/src/lib/modules/date-range-picker/date-range-picker.component.ts
  libs/components/datetime/src/lib/modules/date-range-picker/fixtures/date-range-picker.component.fixture.html
  libs/components/datetime/src/lib/modules/date-range-picker/fixtures/date-range-picker.component.fixture.ts
Labels: risk level (author): 1

#2281 feat(components/packages): schematic for ag-grid styles
  libs/components/packages/collection.json
  libs/components/packages/src/schematics/ng-generate/add-ag-grid-styles/add-ag-grid-styles.schematic.spec.ts
  libs/components/packages/src/schematics/ng-generate/add-ag-grid-styles/add-ag-grid-styles.schematic.ts
  libs/components/packages/src/schematics/ng-generate/add-ag-grid-styles/schema.json
  libs/components/packages/src/schematics/ng-generate/add-ag-grid-styles/schema.ts
  libs/components/packages/src/schematics/rules/add-ag-grid-styles-config.ts
  scripts/postbuild-packages.ts
Labels: risk level (author): 1

#2275 fix(components/text-editor): add asterisk to label when field is required
  libs/components/core/src/lib/modules/forms-utility/forms-utility.ts
  libs/components/forms/src/index.ts
  libs/components/forms/src/lib/modules/required-state/fixtures/reactive.component.fixture.ts
  libs/components/forms/src/lib/modules/required-state/fixtures/template-driven.component.fixture.ts
  libs/components/forms/src/lib/modules/required-state/fixtures/test-control.component.fixture.ts
  libs/components/forms/src/lib/modules/required-state/required-state.directive.spec.ts
  libs/components/forms/src/lib/modules/required-state/required-state.directive.ts
  libs/components/text-editor/src/lib/modules/text-editor/text-editor.component.html
  libs/components/text-editor/src/lib/modules/text-editor/text-editor.component.spec.ts
  libs/components/text-editor/src/lib/modules/text-editor/text-editor.component.ts
Labels: risk level (author): 2

#2276 feat(components/forms): add help inline inputs to radio group
  apps/e2e/forms-storybook/src/app/radio-button/radio-button.component.html
  apps/playground/src/app/components/forms/radio/radio.component.html
  libs/components/forms/src/lib/modules/radio/fixtures/radio-group-reactive.component.fixture.html
  libs/components/forms/src/lib/modules/radio/fixtures/radio-group-reactive.component.fixture.ts
  libs/components/forms/src/lib/modules/radio/radio-group.component.html
  libs/components/forms/src/lib/modules/radio/radio-group.component.scss
  libs/components/forms/src/lib/modules/radio/radio-group.component.spec.ts
  libs/components/forms/src/lib/modules/radio/radio-group.component.ts
Labels: risk level (author): 2

#2286 feat(components/forms): add stacked input to file attachment component
  apps/e2e/forms-storybook/src/app/file-attachment/file-attachment.component.html
  apps/playground/src/app/components/forms/file-attachment/file-attachment.component.html
  libs/components/forms/src/lib/modules/file-attachment/file-drop.component.html
  libs/components/forms/src/lib/modules/file-attachment/file-drop.component.scss
  libs/components/forms/src/lib/modules/file-attachment/file-drop.component.spec.ts
  libs/components/forms/src/lib/modules/file-attachment/file-drop.component.ts
Labels: risk level (author): 1

#2287 feat(components/forms): add stacked input to single file attachment
  apps/e2e/forms-storybook/src/app/single-file-attachment/single-file-attachment.component.html
  apps/playground/src/app/components/forms/single-file-attachment/single-file-attachment.component.html
  libs/components/forms/src/lib/modules/file-attachment/file-attachment.component.scss
  libs/components/forms/src/lib/modules/file-attachment/file-attachment.component.spec.ts
  libs/components/forms/src/lib/modules/file-attachment/file-attachment.component.ts
  libs/components/forms/src/lib/modules/file-attachment/fixtures/file-attachment.component.fixture.html
  libs/components/forms/src/lib/modules/file-attachment/fixtures/file-attachment.component.fixture.ts
Labels: risk level (author): 1

#2288 feat(components/forms): add stacked input to radio group
  apps/e2e/forms-storybook/src/app/radio-button/radio-button.component.html
  apps/playground/src/app/components/forms/radio/radio.component.html
  libs/components/forms/src/lib/modules/radio/fixtures/radio-group-reactive.component.fixture.html
  libs/components/forms/src/lib/modules/radio/fixtures/radio-group-reactive.component.fixture.ts
  libs/components/forms/src/lib/modules/radio/radio-group.component.scss
  libs/components/forms/src/lib/modules/radio/radio-group.component.spec.ts
  libs/components/forms/src/lib/modules/radio/radio-group.component.ts
Labels: risk level (author): 1

#2289 feat(components/text-editor): add stacked input to text editor
  apps/e2e/text-editor-storybook/src/app/text-editor/text-editor.component.html
  libs/components/text-editor/src/lib/modules/text-editor/fixtures/text-editor.component.fixture.html
  libs/components/text-editor/src/lib/modules/text-editor/fixtures/text-editor.component.fixture.ts
  libs/components/text-editor/src/lib/modules/text-editor/text-editor.component.scss
  libs/components/text-editor/src/lib/modules/text-editor/text-editor.component.spec.ts
  libs/components/text-editor/src/lib/modules/text-editor/text-editor.component.ts
Labels: risk level (author): 1

#2284 chore: release 10.12.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#2290 ci: update e2e to not cancel verification step
  .github/workflows/e2e.yml
Labels: risk level (author): 1, skip e2e

#2270 feat(components/text-editor): add help inline to text editor
  apps/e2e/text-editor-storybook/src/app/text-editor/text-editor.component.html
  apps/playground/src/app/components/text-editor/text-editor/text-editor.component.html
  libs/components/forms/src/lib/modules/checkbox/checkbox.component.ts
  libs/components/forms/src/lib/modules/file-attachment/file-attachment.component.ts
  libs/components/forms/src/lib/modules/radio/radio-group.component.ts
  libs/components/text-editor/package.json
  libs/components/text-editor/src/lib/modules/text-editor/fixtures/text-editor.component.fixture.html
  libs/components/text-editor/src/lib/modules/text-editor/fixtures/text-editor.component.fixture.ts
  libs/components/text-editor/src/lib/modules/text-editor/text-editor.component.html
  libs/components/text-editor/src/lib/modules/text-editor/text-editor.component.spec.ts
  libs/components/text-editor/src/lib/modules/text-editor/text-editor.component.ts
Labels: risk level (author): 2

#2292 fix(components/ag-grid): enable `enableCellTextSelection` option
  libs/components/ag-grid/src/lib/modules/ag-grid/ag-grid.service.spec.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/ag-grid.service.ts
Labels: risk level (author): 1

#2278 fix(components/datetime): date range picker only shows datepicker hint text when appropriate
  apps/playground/src/app/components/datetime/date-range-picker/date-range-picker.component.html
  apps/playground/src/app/components/datetime/date-range-picker/date-range-picker.component.ts
  libs/components/datetime/src/lib/modules/date-range-picker/date-range-picker.component.html
  libs/components/datetime/src/lib/modules/date-range-picker/date-range-picker.component.scss
  libs/components/datetime/src/lib/modules/date-range-picker/date-range-picker.component.spec.ts
  libs/components/datetime/src/lib/modules/date-range-picker/date-range-picker.component.ts
  libs/components/datetime/src/lib/modules/datepicker/datepicker-hint-token.ts
  libs/components/datetime/src/lib/modules/datepicker/datepicker.component.ts
Labels: risk level (author): 1

#2291 feat(components/core): add `SkyHelpService` for displaying global help
  libs/components/core/src/index.ts
  libs/components/core/src/lib/modules/help/help-global-options-token.ts
  libs/components/core/src/lib/modules/help/help-global-options.ts
  libs/components/core/src/lib/modules/help/help-open-args.ts
  libs/components/core/src/lib/modules/help/help.service.spec.ts
  libs/components/core/src/lib/modules/help/help.service.ts
  libs/components/core/testing/src/help/help-testing-controller.spec.ts
  libs/components/core/testing/src/help/help-testing-controller.ts
  libs/components/core/testing/src/help/help-testing.module.ts
  libs/components/core/testing/src/help/help-testing.service.ts
  libs/components/core/testing/src/public-api.ts
  libs/components/help-inline/src/lib/modules/help-inline/fixtures/help-inline.component.fixture.html
  libs/components/help-inline/src/lib/modules/help-inline/fixtures/help-inline.component.fixture.ts
  libs/components/help-inline/src/lib/modules/help-inline/help-inline-aria-controls.pipe.ts
  libs/components/help-inline/src/lib/modules/help-inline/help-inline-aria-haspopup.pipe.ts
  libs/components/help-inline/src/lib/modules/help-inline/help-inline.component.html
  libs/components/help-inline/src/lib/modules/help-inline/help-inline.component.spec.ts
  libs/components/help-inline/src/lib/modules/help-inline/help-inline.component.ts
Labels: risk level (author): 2

#2295 ci: update e2e verification step for release pr
  .github/workflows/e2e.yml
Labels: risk level (author): 1

#2293 chore: release 10.13.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#2296 fix(components/forms): add separate messages for different datepicker errors
  apps/playground/src/app/components/datetime/datepicker/datepicker.component.html
  libs/components/forms/src/assets/locales/resources_en_US.json
  libs/components/forms/src/lib/modules/form-error/form-errors.component.html
  libs/components/forms/src/lib/modules/form-error/form-errors.component.spec.ts
  libs/components/forms/src/lib/modules/shared/sky-forms-resources.module.ts
  libs/components/forms/testing/src/form-error/form-errors-harness.spec.ts
  libs/components/forms/testing/src/input-box/fixtures/input-box-harness-test.component.html
  libs/components/forms/testing/src/input-box/fixtures/input-box-harness-test.component.ts
  libs/components/forms/testing/src/input-box/input-box-harness.spec.ts
  libs/components/forms/testing/src/input-box/input-box-harness.ts
Labels: risk level (author): 1

#2294 feat(components/popovers): keyboard navigation for popovers with interactable content
  .cspell.json
  apps/playground/src/app/components/forms/single-file-attachment/single-file-attachment.component.html
  apps/playground/src/app/components/forms/single-file-attachment/single-file-attachment.module.ts
  libs/components/popovers/src/lib/modules/popover/popover-content.component.ts
  libs/components/popovers/src/lib/modules/popover/popover.component.ts
  libs/components/popovers/src/lib/modules/popover/popover.directive.spec.ts
  libs/components/popovers/src/lib/modules/popover/popover.directive.ts
Labels: risk level (author): 3

#2300 feat(components/forms): add `helpKey` input to single file attachment
  apps/playground/src/app/components/forms/single-file-attachment/single-file-attachment.component.html
  apps/playground/src/app/components/forms/single-file-attachment/single-file-attachment.component.ts
  libs/components/forms/src/lib/modules/file-attachment/file-attachment.component.html
  libs/components/forms/src/lib/modules/file-attachment/file-attachment.component.spec.ts
  libs/components/forms/src/lib/modules/file-attachment/file-attachment.component.ts
  libs/components/forms/src/lib/modules/file-attachment/fixtures/file-attachment.component.fixture.html
  libs/components/forms/src/lib/modules/file-attachment/fixtures/file-attachment.component.fixture.ts
Labels: risk level (author): 1

#2237 feat(components/ag-grid): compact option
  apps/e2e/ag-grid-storybook-e2e/src/e2e/ag-grid-stories.component.cy.ts
  apps/e2e/ag-grid-storybook-e2e/src/e2e/data-entry-grid.component.cy.ts
  apps/e2e/ag-grid-storybook-e2e/src/e2e/data-manager.component.cy.ts
  apps/e2e/ag-grid-storybook/src/app/ag-grid/ag-grid-stories.component.html
  apps/e2e/ag-grid-storybook/src/app/ag-grid/ag-grid-stories.component.stories.ts
  apps/e2e/ag-grid-storybook/src/app/ag-grid/ag-grid-stories.component.ts
  apps/e2e/ag-grid-storybook/src/app/app.module.ts
  apps/e2e/ag-grid-storybook/src/app/data-entry-grid/data-entry-grid.component.html
  apps/e2e/ag-grid-storybook/src/app/data-entry-grid/data-entry-grid.component.stories.ts
  apps/e2e/ag-grid-storybook/src/app/data-entry-grid/data-entry-grid.component.ts
  apps/e2e/ag-grid-storybook/src/app/data-manager/data-manager.component.html
  apps/e2e/ag-grid-storybook/src/app/data-manager/data-manager.component.stories.ts
  apps/e2e/ag-grid-storybook/src/app/data-manager/data-manager.component.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/ag-grid-wrapper.component.spec.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/ag-grid-wrapper.component.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/ag-grid.service.spec.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/ag-grid.service.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/fixtures/ag-grid.component.fixture.ts
  libs/components/ag-grid/src/lib/styles/_base.scss
  libs/components/ag-grid/src/lib/styles/_modern-dark.scss
  libs/components/ag-grid/src/lib/styles/_modern-light.scss
  libs/components/ag-grid/src/lib/styles/_modern.scss
  libs/components/ag-grid/src/lib/styles/ag-grid-theme.ts
Labels: risk level (author): 2

#2297 fix(components/forms): implement `Validator` in the checkbox component to check required state
  apps/playground/src/app/components/forms/checkbox/checkbox.component.html
  apps/playground/src/app/components/forms/checkbox/checkbox.component.ts
  libs/components/forms/src/lib/modules/checkbox/checkbox.component.html
  libs/components/forms/src/lib/modules/checkbox/checkbox.component.ts
Labels: risk level (author): 3

#2298 chore: release 10.14.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#2302 feat(components/core): make `SkyHelpService` optional
  libs/components/core/src/lib/modules/help/help.service.spec.ts
  libs/components/core/src/lib/modules/help/help.service.ts
  libs/components/help-inline/src/lib/modules/help-inline/help-inline.component.html
  libs/components/help-inline/src/lib/modules/help-inline/help-inline.component.scss
  libs/components/help-inline/src/lib/modules/help-inline/help-inline.component.spec.ts
  libs/components/help-inline/src/lib/modules/help-inline/help-inline.component.ts
  libs/components/help-inline/testing/src/help-inline/help-inline-harness.spec.ts
  libs/components/help-inline/testing/src/help-inline/help-inline-harness.ts
Labels: risk level (author): 2

#2303 chore: release 10.15.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#2305 fix(components/lookup): search emits a change event when set back to previous text after the clear button is clicked
  libs/components/lookup/src/lib/modules/search/fixtures/search.component.fixture.ts
  libs/components/lookup/src/lib/modules/search/search.component.spec.ts
  libs/components/lookup/src/lib/modules/search/search.component.ts
Labels: risk level (author): 2

#2307 feat(components/forms): update single file attachment code examples to use preview features
  apps/code-examples/src/app/code-examples/forms/single-file-attachment/basic/demo.component.html
  apps/code-examples/src/app/code-examples/forms/single-file-attachment/basic/demo.component.ts
  apps/code-examples/src/app/code-examples/forms/single-file-attachment/inline-help/demo.component.html
  apps/code-examples/src/app/code-examples/forms/single-file-attachment/inline-help/demo.component.ts
  apps/code-examples/src/app/features/forms.module.ts
  apps/code-examples/src/app/home/home.component.html
Labels: risk level (author): 1

#2306 chore: release 10.16.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#2309 feat(components/forms): remove preview tags from single file attachment inputs
  libs/components/forms/src/lib/modules/file-attachment/file-attachment.component.ts
Labels: risk level (author): 1

#2310 chore: release 10.17.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#2312 build(components/ag-grid): add implicit dependencies
  libs/components/ag-grid/project.json
Labels: risk level (author): 1

#2308 feat(components/forms): add `helpKey` input to field group
  apps/playground/src/app/app.module.ts
  apps/playground/src/app/components/forms/field-group/field-group.component.html
  apps/playground/src/app/shared/help.service.ts
  libs/components/forms/src/lib/modules/field-group/field-group.component.html
  libs/components/forms/src/lib/modules/field-group/field-group.component.scss
  libs/components/forms/src/lib/modules/field-group/field-group.component.spec.ts
  libs/components/forms/src/lib/modules/field-group/field-group.component.ts
  libs/components/forms/src/lib/modules/field-group/fixtures/field-group.component.fixture.html
  libs/components/forms/src/lib/modules/field-group/fixtures/field-group.component.fixture.ts
  libs/components/forms/testing/src/field-group/field-group-harness.spec.ts
  libs/components/forms/testing/src/field-group/fixtures/field-group.component.fixture.html
  libs/components/forms/testing/src/field-group/fixtures/field-group.component.fixture.ts
Labels: risk level (author): 1

#2301 feat(components/forms): add `helpKey` input to input box
  apps/code-examples/src/app/code-examples/forms/input-box/basic/demo.component.spec.ts
  apps/e2e/forms-storybook/src/app/input-box/input-box.component.html
  apps/playground/src/app/components/forms/input-box/input-box.component.html
  apps/playground/src/app/components/forms/input-box/input-box.component.ts
  libs/components/datetime/src/lib/modules/date-range-picker/date-range-picker.component.spec.ts
  libs/components/forms/src/lib/modules/file-attachment/file-attachment.component.spec.ts
  libs/components/forms/src/lib/modules/input-box/fixtures/input-box.component.fixture.html
  libs/components/forms/src/lib/modules/input-box/fixtures/input-box.component.fixture.ts
  libs/components/forms/src/lib/modules/input-box/input-box-help-inline.component.html
  libs/components/forms/src/lib/modules/input-box/input-box-help-inline.component.ts
  libs/components/forms/src/lib/modules/input-box/input-box.component.html
  libs/components/forms/src/lib/modules/input-box/input-box.component.spec.ts
  libs/components/forms/src/lib/modules/input-box/input-box.component.ts
  libs/components/forms/src/lib/modules/input-box/input-box.module.ts
  libs/components/forms/testing/src/input-box/fixtures/input-box-harness-test.component.html
  libs/components/forms/testing/src/input-box/fixtures/input-box-harness-test.component.ts
  libs/components/forms/testing/src/input-box/input-box-harness.spec.ts
  libs/components/forms/testing/src/input-box/input-box-harness.ts
Labels: risk level (author): 2

#2304 fix(components/ag-grid): compact cell text wrapping
  apps/e2e/ag-grid-storybook-e2e/src/e2e/data-manager.component.cy.ts
  apps/e2e/ag-grid-storybook/src/app/data-manager/data-manager.component.html
  apps/e2e/ag-grid-storybook/src/app/data-manager/data-manager.component.stories.ts
  apps/e2e/ag-grid-storybook/src/app/data-manager/data-manager.component.ts
  apps/e2e/ag-grid-storybook/src/app/data-manager/data-manager.module.ts
  apps/playground/src/app/components/ag-grid/data-manager-large/data-manager-large.component.html
  apps/playground/src/app/components/ag-grid/data-manager-large/data-manager-large.component.ts
  libs/components/ag-grid/src/lib/styles/_modern-dark.scss
  libs/components/ag-grid/src/lib/styles/_modern-light.scss
  libs/components/ag-grid/src/lib/styles/_variables.scss
Labels: risk level (author): 1

#2314 chore: release 10.18.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#2313 feat(components/forms): add `helpKey` input to file attachment
  apps/playground/src/app/components/forms/file-attachment/file-attachment.component.html
  libs/components/forms/src/lib/modules/file-attachment/file-drop.component.html
  libs/components/forms/src/lib/modules/file-attachment/file-drop.component.spec.ts
  libs/components/forms/src/lib/modules/file-attachment/file-drop.component.ts
Labels: risk level (author): 1

#2315 feat(components/forms): add `helpKey` input to checkbox and checkbox group
  apps/playground/src/app/components/forms/checkbox/checkbox.component.html
  libs/components/forms/src/lib/modules/checkbox/checkbox-group.component.html
  libs/components/forms/src/lib/modules/checkbox/checkbox-group.component.spec.ts
  libs/components/forms/src/lib/modules/checkbox/checkbox-group.component.ts
  libs/components/forms/src/lib/modules/checkbox/checkbox.component.html
  libs/components/forms/src/lib/modules/checkbox/checkbox.component.spec.ts
  libs/components/forms/src/lib/modules/checkbox/checkbox.component.ts
  libs/components/forms/src/lib/modules/checkbox/fixtures/standard-checkbox-group.component.html
  libs/components/forms/src/lib/modules/checkbox/fixtures/standard-checkbox-group.component.ts
  libs/components/forms/testing/src/checkbox/checkbox-group-harness.spec.ts
  libs/components/forms/testing/src/checkbox/checkbox-group-harness.ts
  libs/components/forms/testing/src/checkbox/checkbox-harness.spec.ts
  libs/components/forms/testing/src/checkbox/checkbox-harness.ts
  libs/components/forms/testing/src/checkbox/fixtures/checkbox-harness-test.component.html
  libs/components/forms/testing/src/checkbox/fixtures/checkbox-harness-test.component.ts
  libs/components/forms/testing/src/field-group/field-group-harness.spec.ts
  libs/components/forms/testing/src/field-group/field-group-harness.ts
  libs/components/forms/testing/src/input-box/input-box-harness.spec.ts
  libs/components/forms/testing/src/input-box/input-box-harness.ts
  libs/components/help-inline/testing/src/help-inline/help-inline-harness.spec.ts
  libs/components/help-inline/testing/src/help-inline/help-inline-harness.ts
  libs/components/popovers/testing/src/popover/harness/popover-harness.ts
Labels: risk level (author): 1

#2319 feat(components/forms): add semantic and styling header inputs to radio group
  apps/e2e/forms-storybook/src/app/radio-button/radio-button.component.html
  apps/playground/src/app/components/forms/radio/radio.component.html
  libs/components/forms/src/lib/modules/radio/fixtures/radio-group-reactive.component.fixture.html
  libs/components/forms/src/lib/modules/radio/fixtures/radio-group-reactive.component.fixture.ts
  libs/components/forms/src/lib/modules/radio/radio-group.component.html
  libs/components/forms/src/lib/modules/radio/radio-group.component.scss
  libs/components/forms/src/lib/modules/radio/radio-group.component.spec.ts
  libs/components/forms/src/lib/modules/radio/radio-group.component.ts
  libs/components/forms/src/lib/modules/radio/types/radio-group-heading-level.ts
  libs/components/forms/src/lib/modules/radio/types/radio-group-heading-style.ts
Labels: risk level (author): 1

#2318 fix(components/autonumeric): cleanup autonumeric instance
  libs/components/autonumeric/src/lib/modules/autonumeric/autonumeric.directive.spec.ts
  libs/components/autonumeric/src/lib/modules/autonumeric/autonumeric.directive.ts
Labels: risk level (author): 1

#2321 fix(components/forms): change field group, checkbox group, and radio group label inputs to heading inputs
  apps/code-examples/src/app/code-examples/forms/checkbox/basic/demo.component.html
  apps/code-examples/src/app/code-examples/forms/checkbox/icon-group/demo.component.html
  apps/code-examples/src/app/code-examples/forms/radio/icon/demo.component.html
  apps/code-examples/src/app/code-examples/forms/radio/inline-help/demo.component.html
  apps/code-examples/src/app/code-examples/forms/radio/standard/demo.component.html
  apps/e2e/forms-storybook/src/app/checkbox/checkbox.component.html
  apps/e2e/forms-storybook/src/app/field-group/field-group.component.html
  apps/e2e/forms-storybook/src/app/radio-button/radio-button.component.html
  apps/playground/src/app/components/forms/checkbox/checkbox.component.html
  apps/playground/src/app/components/forms/field-group/field-group.component.html
  apps/playground/src/app/components/forms/radio/radio.component.html
  libs/components/forms/src/lib/modules/checkbox/checkbox-group.component.html
  libs/components/forms/src/lib/modules/checkbox/checkbox-group.component.spec.ts
  libs/components/forms/src/lib/modules/checkbox/checkbox-group.component.ts
  libs/components/forms/src/lib/modules/checkbox/fixtures/icon-checkbox-group.component.html
  libs/components/forms/src/lib/modules/checkbox/fixtures/standard-checkbox-group.component.html
  libs/components/forms/src/lib/modules/checkbox/fixtures/standard-checkbox-group.component.ts
  libs/components/forms/src/lib/modules/field-group/field-group.component.html
  libs/components/forms/src/lib/modules/field-group/field-group.component.spec.ts
  libs/components/forms/src/lib/modules/field-group/field-group.component.ts
  libs/components/forms/src/lib/modules/field-group/fixtures/field-group.component.fixture.html
  libs/components/forms/src/lib/modules/field-group/fixtures/field-group.component.fixture.ts
  libs/components/forms/src/lib/modules/radio/fixtures/radio-group-reactive.component.fixture.html
  libs/components/forms/src/lib/modules/radio/fixtures/radio-group-reactive.component.fixture.ts
  libs/components/forms/src/lib/modules/radio/radio-group.component.html
  libs/components/forms/src/lib/modules/radio/radio-group.component.spec.ts
  libs/components/forms/src/lib/modules/radio/radio-group.component.ts
  libs/components/forms/testing/src/checkbox/checkbox-group-harness.spec.ts
  libs/components/forms/testing/src/checkbox/checkbox-group-harness.ts
  libs/components/forms/testing/src/checkbox/fixtures/checkbox-harness-test.component.html
  libs/components/forms/testing/src/checkbox/fixtures/checkbox-harness-test.component.ts
  libs/components/forms/testing/src/field-group/field-group-harness.spec.ts
  libs/components/forms/testing/src/field-group/field-group-harness.ts
  libs/components/forms/testing/src/field-group/fixtures/field-group.component.fixture.html
  libs/components/forms/testing/src/field-group/fixtures/field-group.component.fixture.ts
Labels: risk level (author): 5

#2320 feat(components/text-editor): add `helpKey` to text editor
  apps/playground/src/app/components/text-editor/text-editor/text-editor.component.html
  libs/components/text-editor/src/lib/modules/text-editor/fixtures/text-editor.component.fixture.html
  libs/components/text-editor/src/lib/modules/text-editor/fixtures/text-editor.component.fixture.ts
  libs/components/text-editor/src/lib/modules/text-editor/text-editor.component.html
  libs/components/text-editor/src/lib/modules/text-editor/text-editor.component.spec.ts
  libs/components/text-editor/src/lib/modules/text-editor/text-editor.component.ts
Labels: risk level (author): 1

#2311 feat(components/datetime): date range picker announces required state to screen readers
  apps/playground/src/app/components/datetime/date-range-picker/date-range-picker.component.html
  apps/playground/src/app/components/datetime/date-range-picker/date-range-picker.component.scss
  apps/playground/src/app/components/datetime/date-range-picker/date-range-picker.component.ts
  apps/playground/src/app/components/datetime/date-range-picker/date-range-picker.module.ts
  apps/playground/src/app/components/datetime/date-range-picker/locale-provider.ts
  libs/components/datetime/src/lib/modules/date-range-picker/date-range-picker-end-date-resource-key.pipe.ts
  libs/components/datetime/src/lib/modules/date-range-picker/date-range-picker-start-date-resource-key.pipe.ts
  libs/components/datetime/src/lib/modules/date-range-picker/date-range-picker.component.html
  libs/components/datetime/src/lib/modules/date-range-picker/date-range-picker.component.spec.ts
  libs/components/datetime/src/lib/modules/date-range-picker/date-range-picker.component.ts
  libs/components/datetime/src/lib/modules/date-range-picker/date-range-picker.module.ts
  libs/components/datetime/src/lib/modules/date-range-picker/date-range.service.spec.ts
  libs/components/datetime/src/lib/modules/date-range-picker/date-range.service.ts
  libs/components/datetime/src/lib/modules/date-range-picker/fixtures/date-range-picker.component.fixture.html
  libs/components/datetime/src/lib/modules/date-range-picker/fixtures/date-range-picker.component.fixture.ts
  libs/components/datetime/src/lib/modules/date-range-picker/fixtures/date-range-picker.module.fixture.ts
  libs/components/datetime/src/lib/modules/date-range-picker/types/date-range-calculator.ts
  libs/components/datetime/src/lib/modules/date-range-picker/types/date-range-default-calculator-configs.ts
  libs/components/forms/src/lib/modules/input-box/fixtures/input-box.component.fixture.html
  libs/components/forms/src/lib/modules/input-box/fixtures/input-box.component.fixture.ts
  libs/components/forms/src/lib/modules/input-box/input-box.component.html
  libs/components/forms/src/lib/modules/input-box/input-box.component.spec.ts
  libs/components/forms/src/lib/modules/input-box/input-box.component.ts
Labels: risk level (author): 4

#2324 feat(components/forms): add `helpKey` input to radio button and group
  libs/components/forms/src/lib/modules/radio/fixtures/radio-group-reactive.component.fixture.html
  libs/components/forms/src/lib/modules/radio/fixtures/radio-group-reactive.component.fixture.ts
  libs/components/forms/src/lib/modules/radio/fixtures/radio.component.fixture.html
  libs/components/forms/src/lib/modules/radio/fixtures/radio.component.fixture.ts
  libs/components/forms/src/lib/modules/radio/radio-group.component.html
  libs/components/forms/src/lib/modules/radio/radio-group.component.spec.ts
  libs/components/forms/src/lib/modules/radio/radio-group.component.ts
  libs/components/forms/src/lib/modules/radio/radio.component.html
  libs/components/forms/src/lib/modules/radio/radio.component.spec.ts
  libs/components/forms/src/lib/modules/radio/radio.component.ts
Labels: risk level (author): 1

#2322 feat(components/forms): add headingLevel and headingStyle inputs to checkbox group
  apps/e2e/forms-storybook/src/app/checkbox/checkbox.component.html
  libs/components/forms/src/index.ts
  libs/components/forms/src/lib/modules/checkbox/checkbox-group-heading-level.ts
  libs/components/forms/src/lib/modules/checkbox/checkbox-group-heading-style.ts
  libs/components/forms/src/lib/modules/checkbox/checkbox-group.component.html
  libs/components/forms/src/lib/modules/checkbox/checkbox-group.component.scss
  libs/components/forms/src/lib/modules/checkbox/checkbox-group.component.spec.ts
  libs/components/forms/src/lib/modules/checkbox/checkbox-group.component.ts
  libs/components/forms/src/lib/modules/checkbox/fixtures/standard-checkbox-group.component.html
  libs/components/forms/src/lib/modules/checkbox/fixtures/standard-checkbox-group.component.ts
  libs/components/forms/src/lib/modules/field-group/field-group.component.ts
  libs/components/forms/src/lib/modules/radio/radio-group.component.ts
  libs/components/forms/testing/src/checkbox/checkbox-group-harness.spec.ts
  libs/components/forms/testing/src/checkbox/checkbox-group-harness.ts
  libs/components/forms/testing/src/checkbox/fixtures/checkbox-harness-test.component.html
  libs/components/forms/testing/src/checkbox/fixtures/checkbox-harness-test.component.ts
Labels: risk level (author): 1

#2323 chore: release 10.20.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#2316 feat(components/indicators): add illustration component
  .cspell.json
  apps/code-examples/src/app/code-examples/indicators/illustration/basic/demo.component.html
  apps/code-examples/src/app/code-examples/indicators/illustration/basic/demo.component.spec.ts
  apps/code-examples/src/app/code-examples/indicators/illustration/basic/demo.component.ts
  apps/code-examples/src/app/code-examples/indicators/illustration/basic/illustration-demo-resolver.service.ts
  apps/code-examples/src/app/features/indicators.module.ts
  apps/code-examples/src/app/home/home.component.html
  apps/e2e/indicators-storybook-e2e/src/e2e/illustration.component.cy.ts
  apps/e2e/indicators-storybook/src/app/app.module.ts
  apps/e2e/indicators-storybook/src/app/illustration/illustration-resolver.service.ts
  apps/e2e/indicators-storybook/src/app/illustration/illustration.component.html
  apps/e2e/indicators-storybook/src/app/illustration/illustration.component.scss
  apps/e2e/indicators-storybook/src/app/illustration/illustration.component.stories.ts
  apps/e2e/indicators-storybook/src/app/illustration/illustration.component.ts
  apps/e2e/indicators-storybook/src/app/illustration/illustration.module.ts
  apps/playground/src/app/components/indicators/illustration/illustration-resolver.service.ts
  apps/playground/src/app/components/indicators/illustration/illustration-routing.module.ts
  apps/playground/src/app/components/indicators/illustration/illustration.component.html
  apps/playground/src/app/components/indicators/illustration/illustration.component.ts
  apps/playground/src/app/components/indicators/illustration/illustration.module.ts
  apps/playground/src/app/components/indicators/indicators.module.ts
  libs/components/indicators/src/index.ts
  libs/components/indicators/src/lib/modules/illustration/fixtures/illustration-test-resolver.service.ts
  libs/components/indicators/src/lib/modules/illustration/illustration-resolver.service.ts
  libs/components/indicators/src/lib/modules/illustration/illustration-size.ts
  libs/components/indicators/src/lib/modules/illustration/illustration.component.html
  libs/components/indicators/src/lib/modules/illustration/illustration.component.scss
  libs/components/indicators/src/lib/modules/illustration/illustration.component.spec.ts
  libs/components/indicators/src/lib/modules/illustration/illustration.component.ts
  libs/components/indicators/src/lib/modules/illustration/illustration.module.ts
  libs/components/indicators/testing/src/illustration/fixtures/illustration-test-resolver.service.ts
  libs/components/indicators/testing/src/illustration/fixtures/illustration-test.component.ts
  libs/components/indicators/testing/src/illustration/fixtures/illustration-test.module.ts
  libs/components/indicators/testing/src/illustration/illustration-harness-filters.ts
  libs/components/indicators/testing/src/illustration/illustration-harness.spec.ts
  libs/components/indicators/testing/src/illustration/illustration-harness.ts
  libs/components/indicators/testing/src/public-api.ts
Labels: risk level (author): 2

#2325 feat(components/forms): add `helpKey` input to toggle switch
  libs/components/forms/src/lib/modules/toggle-switch/fixtures/toggle-switch.component.fixture.html
  libs/components/forms/src/lib/modules/toggle-switch/fixtures/toggle-switch.component.fixture.ts
  libs/components/forms/src/lib/modules/toggle-switch/toggle-switch.component.html
  libs/components/forms/src/lib/modules/toggle-switch/toggle-switch.component.spec.ts
  libs/components/forms/src/lib/modules/toggle-switch/toggle-switch.component.ts
Labels: risk level (author): 1

#2327 feat(components/datetime): add `helpKey` input to date range picker
  apps/playground/src/app/components/datetime/date-range-picker/date-range-picker.component.html
  libs/components/datetime/src/lib/modules/date-range-picker/date-range-picker.component.html
  libs/components/datetime/src/lib/modules/date-range-picker/date-range-picker.component.spec.ts
  libs/components/datetime/src/lib/modules/date-range-picker/date-range-picker.component.ts
  libs/components/datetime/src/lib/modules/date-range-picker/fixtures/date-range-picker.component.fixture.html
  libs/components/datetime/src/lib/modules/date-range-picker/fixtures/date-range-picker.component.fixture.ts
Labels: risk level (author): 1

#2326 chore: release 10.21.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#2328 fix(components/phone-field): phone field hint text uses an example number instead of an example format
  libs/components/phone-field/src/assets/locales/resources_en_US.json
  libs/components/phone-field/src/lib/modules/phone-field/phone-field.component.spec.ts
  libs/components/phone-field/src/lib/modules/phone-field/phone-field.component.ts
  libs/components/phone-field/src/lib/modules/shared/sky-phone-field-resources.module.ts
Labels: risk level (author): 1

#2330 fix(components/lookup): search emits a change event when set back to previous text after the value is cleared via the input binding
  libs/components/lookup/src/lib/modules/search/search.component.spec.ts
  libs/components/lookup/src/lib/modules/search/search.component.ts
Labels: risk level (author): 1

#2329 chore: release 10.21.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#2331 feat(components/forms): add field group code example
  apps/code-examples/src/app/code-examples/forms/field-group/basic/demo.component.html
  apps/code-examples/src/app/code-examples/forms/field-group/basic/demo.component.ts
  apps/code-examples/src/app/features/forms.module.ts
  apps/code-examples/src/app/home/home.component.html
Labels: risk level (author): 1

#2335 fix(components/ag-grid): lookup renderer should use `descriptorProperty`
  apps/playground/src/app/components/ag-grid/edit-complex-cells/edit-complex-cells.component.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/ag-grid.service.spec.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/ag-grid.service.ts
Labels: risk level (author): 1

#2333 feat(components/forms): update toggle switch code example
  apps/code-examples/src/app/code-examples/forms/toggle-switch/basic/demo.component.html
  apps/code-examples/src/app/code-examples/forms/toggle-switch/basic/demo.component.ts
Labels: risk level (author): 1

#2336 feat(components/datetime): update date range picker code example
  apps/code-examples/src/app/code-examples/datetime/date-range-picker/basic/demo.component.html
  apps/code-examples/src/app/code-examples/datetime/date-range-picker/basic/demo.component.ts
Labels: risk level (author): 1

#2334 fix(components/ag-grid): prevent data-grid layout shift when focusing on a cell
  libs/components/ag-grid/src/lib/styles/_base.scss
Labels: risk level (author): 1

#2339 feat(components/omnibar-interop): add disabled to omnibar ready args
  libs/components/omnibar-interop/src/lib/omnibar-provider.spec.ts
  libs/components/omnibar-interop/src/lib/omnibar-ready-args.ts
Labels: risk level (author): 1, risk level (reviewer): 1

#2340 feat(components/lookup): update country field code example
  apps/code-examples/src/app/code-examples/lookup/country-field/basic/demo.component.html
  apps/code-examples/src/app/code-examples/lookup/country-field/basic/demo.component.ts
Labels: risk level (author): 1

#2337 feat(components/text-editor): update code examples with new form field features
  apps/code-examples/src/app/code-examples/text-editor/text-editor-inline-help/demo.component.html
  apps/code-examples/src/app/code-examples/text-editor/text-editor-inline-help/demo.component.ts
  apps/code-examples/src/app/code-examples/text-editor/text-editor/demo.component.html
  apps/code-examples/src/app/code-examples/text-editor/text-editor/demo.component.ts
  apps/code-examples/src/app/features/text-editor.module.ts
  apps/code-examples/src/app/home/home.component.html
Labels: risk level (author): 1
