Repository blackbaud/skyux, pull requests merged in 2025-02, with the labels that each got.

#3087 fix(components/ag-grid): refocus cell editors on api refresh
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-editors/cell-editor-autocomplete/cell-editor-autocomplete.component.spec.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-editors/cell-editor-autocomplete/cell-editor-autocomplete.component.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-editors/cell-editor-currency/cell-editor-currency.component.spec.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-editors/cell-editor-currency/cell-editor-currency.component.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-editors/cell-editor-lookup/cell-editor-lookup.component.spec.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-editors/cell-editor-lookup/cell-editor-lookup.component.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-editors/cell-editor-number/cell-editor-number.component.spec.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-editors/cell-editor-number/cell-editor-number.component.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-editors/cell-editor-text/cell-editor-text.component.spec.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-editors/cell-editor-text/cell-editor-text.component.ts
Labels: risk level (author): 1

#3092 fix(components/ag-grid): refocus cell editors on api refresh (#3087)
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-editors/cell-editor-autocomplete/cell-editor-autocomplete.component.spec.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-editors/cell-editor-autocomplete/cell-editor-autocomplete.component.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-editors/cell-editor-currency/cell-editor-currency.component.spec.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-editors/cell-editor-currency/cell-editor-currency.component.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-editors/cell-editor-lookup/cell-editor-lookup.component.spec.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-editors/cell-editor-lookup/cell-editor-lookup.component.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-editors/cell-editor-number/cell-editor-number.component.spec.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-editors/cell-editor-number/cell-editor-number.component.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-editors/cell-editor-text/cell-editor-text.component.spec.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-editors/cell-editor-text/cell-editor-text.component.ts
Labels: risk level (author): 1

#3090 feat(components/layout): tokenize fluid grid styles
  apps/code-examples/src/app/app.component.ts
  apps/code-examples/src/app/shared/theme-selector/theme-selector-mode-value.ts
  apps/code-examples/src/app/shared/theme-selector/theme-selector-value.ts
  apps/code-examples/src/app/shared/theme-selector/theme-selector.component.html
  apps/code-examples/src/app/shared/theme-selector/theme-selector.component.ts
  apps/e2e/layout-storybook-e2e/src/e2e/fluid-grid.component.cy.ts
  apps/playground/src/app/shared/theme-selector/theme-selector.component.ts
  libs/components/layout/src/lib/modules/fluid-grid/column.component.scss
  libs/components/layout/src/lib/modules/fluid-grid/fluid-grid.component.scss
  libs/components/layout/src/lib/modules/fluid-grid/row.component.scss
  libs/components/layout/src/lib/modules/fluid-grid/scss/_variables.scss
Labels: risk level (author): 2

#3064 feat(components/tabs): add harnesses for tab component
  apps/code-examples/src/app/code-examples/pages/page/record-page-tabs-layout-demo/record-page-content-component.spec.ts
  apps/code-examples/src/app/code-examples/pages/page/record-page-tabs-layout-demo/record-page-overview-tab-harness.ts
  apps/code-examples/src/app/code-examples/tabs/tabs/dynamic-add-close/demo.component.html
  apps/code-examples/src/app/code-examples/tabs/tabs/dynamic-add-close/demo.component.spec.ts
  apps/code-examples/src/app/code-examples/tabs/tabs/dynamic-add-close/demo.component.ts
  apps/code-examples/src/app/code-examples/tabs/tabs/dynamic/demo.component.html
  apps/code-examples/src/app/code-examples/tabs/tabs/dynamic/demo.component.spec.ts
  apps/code-examples/src/app/code-examples/tabs/tabs/static-add-close/demo.component.html
  apps/code-examples/src/app/code-examples/tabs/tabs/static-add-close/demo.component.spec.ts
  apps/code-examples/src/app/code-examples/tabs/tabs/static-add-close/demo.component.ts
  apps/code-examples/src/app/code-examples/tabs/tabs/static/demo.component.html
  apps/code-examples/src/app/code-examples/tabs/tabs/static/demo.component.spec.ts
  apps/playground/src/app/components/tabs/tabs/tabs.component.html
  apps/playground/src/app/components/tabs/tabs/tabs.component.ts
  libs/components/popovers/testing/src/modules/dropdown/dropdown-menu-harness.ts
  libs/components/tabs/package.json
  libs/components/tabs/src/lib/modules/tabs/tabset.component.html
  libs/components/tabs/testing/src/modules/tabs/tab-button-harness-filters.ts
  libs/components/tabs/testing/src/modules/tabs/tab-button-harness.ts
  libs/components/tabs/testing/src/modules/tabs/tab-content-harness-filters.ts
  libs/components/tabs/testing/src/modules/tabs/tab-content-harness.ts
  libs/components/tabs/testing/src/modules/tabs/tabset-harness-filters.ts
  libs/components/tabs/testing/src/modules/tabs/tabset-harness.spec.ts
  libs/components/tabs/testing/src/modules/tabs/tabset-harness.ts
  libs/components/tabs/testing/src/public-api.ts
Labels: risk level (author): 1

#3093 chore: changelog for 11.38.0 (#3081) 🍒
  CHANGELOG.md
Labels: risk level (author): 1, risk level (reviewer): 1

#3095 feat(components/tabs): add harnesses for tab component (#3064)
  apps/code-examples/src/app/code-examples/pages/page/record-page-tabs-layout-demo/record-page-content-component.spec.ts
  apps/code-examples/src/app/code-examples/pages/page/record-page-tabs-layout-demo/record-page-overview-tab-harness.ts
  apps/code-examples/src/app/code-examples/tabs/tabs/dynamic-add-close/demo.component.html
  apps/code-examples/src/app/code-examples/tabs/tabs/dynamic-add-close/demo.component.spec.ts
  apps/code-examples/src/app/code-examples/tabs/tabs/dynamic-add-close/demo.component.ts
  apps/code-examples/src/app/code-examples/tabs/tabs/dynamic/demo.component.html
  apps/code-examples/src/app/code-examples/tabs/tabs/dynamic/demo.component.spec.ts
  apps/code-examples/src/app/code-examples/tabs/tabs/static-add-close/demo.component.html
  apps/code-examples/src/app/code-examples/tabs/tabs/static-add-close/demo.component.spec.ts
  apps/code-examples/src/app/code-examples/tabs/tabs/static-add-close/demo.component.ts
  apps/code-examples/src/app/code-examples/tabs/tabs/static/demo.component.html
  apps/code-examples/src/app/code-examples/tabs/tabs/static/demo.component.spec.ts
  apps/playground/src/app/components/tabs/tabs/tabs.component.html
  apps/playground/src/app/components/tabs/tabs/tabs.component.ts
  libs/components/popovers/testing/src/modules/dropdown/dropdown-menu-harness.ts
  libs/components/tabs/package.json
  libs/components/tabs/src/lib/modules/tabs/tabset.component.html
  libs/components/tabs/testing/src/modules/tabs/tab-button-harness-filters.ts
  libs/components/tabs/testing/src/modules/tabs/tab-button-harness.ts
  libs/components/tabs/testing/src/modules/tabs/tab-content-harness-filters.ts
  libs/components/tabs/testing/src/modules/tabs/tab-content-harness.ts
  libs/components/tabs/testing/src/modules/tabs/tabset-harness-filters.ts
  libs/components/tabs/testing/src/modules/tabs/tabset-harness.spec.ts
  libs/components/tabs/testing/src/modules/tabs/tabset-harness.ts
  libs/components/tabs/testing/src/public-api.ts
Labels: risk level (author): 1

#3097 ci: fix library dependency check
  .github/workflows/ci.yml
  libs/components/tabs/project.json
  libs/components/tiles/project.json
Labels: risk level (author): 1, skip e2e

#3100 ci: fix library dependency check (#3097)
  .github/workflows/ci.yml
  libs/components/tabs/project.json
Labels: risk level (author): 1, skip e2e

#3102 fix(components/text-editor): allow initializing as disabled (#3099)
  libs/components/text-editor/src/lib/modules/text-editor/fixtures/text-editor-reactive.component.fixture.html
  libs/components/text-editor/src/lib/modules/text-editor/fixtures/text-editor-reactive.component.fixture.ts
  libs/components/text-editor/src/lib/modules/text-editor/text-editor.component.spec.ts
  libs/components/text-editor/src/lib/modules/text-editor/text-editor.component.ts
Labels: risk level (author): 1

#3104 fix(components/toast): toasts read to assistive technology on initial rendering
  libs/components/toast/src/lib/modules/toast/toast.component.html
  libs/components/toast/src/lib/modules/toast/toast.component.spec.ts
  libs/components/toast/src/lib/modules/toast/toast.component.ts
Labels: risk level (author): 2

#3105 fix(components/toast): toasts read to assistive technology on initial rendering (#3104)
  libs/components/toast/src/lib/modules/toast/toast.component.html
  libs/components/toast/src/lib/modules/toast/toast.component.spec.ts
  libs/components/toast/src/lib/modules/toast/toast.component.ts
Labels: risk level (author): 2

#3096 fix(components/action-bars): summary action bar should stack with back to top
  apps/integration-e2e/src/e2e/vertical-tabset-back-to-top.cy.ts
  apps/integration/src/app/integrations/modal-viewkept-toolbars/modal-viewkept-toolbars-modal.component.html
  apps/integration/src/app/integrations/modal-viewkept-toolbars/modal-viewkept-toolbars-modal.component.ts
  apps/integration/src/app/integrations/vertical-tabset-back-to-top/vertical-tabset-back-to-top.component.html
  apps/integration/src/app/integrations/vertical-tabset-back-to-top/vertical-tabset-back-to-top.component.ts
  apps/integration/src/app/integrations/vertical-tabset-back-to-top/vertical-tabset-back-to-top.module.ts
  apps/playground/src/app/components/action-bars/summary-action-bar/summary-action-bar.component.html
  apps/playground/src/app/components/action-bars/summary-action-bar/summary-action-bar.component.ts
  apps/playground/src/app/components/action-bars/summary-action-bar/summary-action-bar.module.ts
  libs/components/action-bars/src/lib/modules/summary-action-bar/summary-action-bar-adapter.service.ts
  libs/components/action-bars/src/lib/modules/summary-action-bar/summary-action-bar.component.scss
  libs/components/action-bars/src/lib/modules/summary-action-bar/summary-action-bar.component.spec.ts
  libs/components/core/src/lib/modules/dock/dock-dom-adapter.service.ts
  libs/components/core/src/lib/modules/dock/dock.component.spec.ts
  libs/components/core/src/lib/modules/dock/dock.service.ts
  libs/components/modals/src/lib/modules/modal/modal.component.scss
  libs/components/split-view/src/lib/modules/split-view/split-view.component.spec.ts
Labels: risk level (author): 1

#3107 fix(components/action-bars): summary action bar should stack with back to top (#3096)
  apps/integration-e2e/src/e2e/vertical-tabset-back-to-top.cy.ts
  apps/integration/src/app/integrations/modal-viewkept-toolbars/modal-viewkept-toolbars-modal.component.html
  apps/integration/src/app/integrations/modal-viewkept-toolbars/modal-viewkept-toolbars-modal.component.ts
  apps/integration/src/app/integrations/vertical-tabset-back-to-top/vertical-tabset-back-to-top.component.html
  apps/integration/src/app/integrations/vertical-tabset-back-to-top/vertical-tabset-back-to-top.component.ts
  apps/integration/src/app/integrations/vertical-tabset-back-to-top/vertical-tabset-back-to-top.module.ts
  apps/playground/src/app/components/action-bars/summary-action-bar/summary-action-bar.component.html
  apps/playground/src/app/components/action-bars/summary-action-bar/summary-action-bar.component.ts
  apps/playground/src/app/components/action-bars/summary-action-bar/summary-action-bar.module.ts
  libs/components/action-bars/src/lib/modules/summary-action-bar/summary-action-bar-adapter.service.ts
  libs/components/action-bars/src/lib/modules/summary-action-bar/summary-action-bar.component.scss
  libs/components/action-bars/src/lib/modules/summary-action-bar/summary-action-bar.component.spec.ts
  libs/components/core/src/lib/modules/dock/dock-dom-adapter.service.ts
  libs/components/core/src/lib/modules/dock/dock.component.spec.ts
  libs/components/core/src/lib/modules/dock/dock.service.ts
  libs/components/modals/src/lib/modules/modal/modal.component.scss
  libs/components/split-view/src/lib/modules/split-view/split-view.component.spec.ts
Labels: risk level (author): 1

#3106 fix(components/lists): mark repeater item `reorderable` property as internal as a consumer setting this property has no affect
  libs/components/lists/src/lib/modules/repeater/repeater-item.component.ts
Labels: risk level (author): 1

#3103 chore: release 11.38.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease 11.x.x: pending

#3108 fix(components/lists): mark repeater item `reorderable` property as internal as a consumer setting this property has no affect (#3106)
  libs/components/lists/src/lib/modules/repeater/repeater-item.component.ts
Labels: risk level (author): 1

#3110 chore: changelog for 11.38.1 (#3103) 🍒
  CHANGELOG.md
Labels: risk level (author): 1, risk level (reviewer): 1

#3059 chore: release 12.0.0-alpha.3
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#3101 feat(components/layout): add action button harness
  apps/code-examples/src/app/code-examples/layout/action-button/basic/demo.component.html
  apps/code-examples/src/app/code-examples/layout/action-button/basic/demo.component.spec.ts
  apps/code-examples/src/app/code-examples/layout/action-button/basic/demo.component.ts
  apps/code-examples/src/app/code-examples/layout/action-button/permalink/demo.component.html
  apps/code-examples/src/app/code-examples/layout/action-button/permalink/demp.component.spec.ts
  libs/components/layout/project.json
  libs/components/layout/testing/src/modules/action-button/action-button-container-harness.filters.ts
  libs/components/layout/testing/src/modules/action-button/action-button-container-harness.spec.ts
  libs/components/layout/testing/src/modules/action-button/action-button-container-harness.ts
  libs/components/layout/testing/src/modules/action-button/action-button-harness.filters.ts
  libs/components/layout/testing/src/modules/action-button/action-button-harness.spec.ts
  libs/components/layout/testing/src/modules/action-button/action-button-harness.ts
  libs/components/layout/testing/src/public-api.ts
Labels: risk level (author): 1

#3098 feat(components/flyout): tokenize flyout styles
  apps/e2e/flyout-storybook-e2e/src/e2e/flyout.component.cy.ts
  apps/e2e/flyout-storybook/project.json
  libs/components/flyout/src/lib/modules/flyout/flyout-iterator.component.html
  libs/components/flyout/src/lib/modules/flyout/flyout-iterator.component.scss
  libs/components/flyout/src/lib/modules/flyout/flyout.component.html
  libs/components/flyout/src/lib/modules/flyout/flyout.component.scss
  libs/components/theme/package.json
  package-lock.json
  package.json
Labels: risk level (author): 2

#3111 feat(components/layout): tokenize inline delete styles
  apps/e2e/layout-storybook-e2e/src/e2e/inline-delete.component.cy.ts
  libs/components/layout/src/lib/modules/inline-delete/inline-delete.component.html
  libs/components/layout/src/lib/modules/inline-delete/inline-delete.component.scss
Labels: risk level (author): 2

#3109 feat(components/pages): tokenize action hub styles
  apps/e2e/pages-storybook-e2e/src/e2e/action-hub.component.cy.ts
  apps/playground/src/app/components/pages/action-hub/recent/action-hub-recent-links.component.ts
  libs/components/pages/src/lib/modules/needs-attention/needs-attention.component.scss
Labels: risk level (author): 2

#3116 feat(components/inline-form): tokenize inline form styles
  apps/code-examples/project.json
  apps/e2e/inline-form-storybook-e2e/src/e2e/inline-form.component.cy.ts
  apps/e2e/inline-form-storybook/project.json
  libs/components/inline-form/src/lib/modules/inline-form/inline-form.component.html
  libs/components/inline-form/src/lib/modules/inline-form/inline-form.component.scss
Labels: risk level (author): 2

#3124 feat(components/layout): add harness for description list
  apps/code-examples/src/app/code-examples/layout/description-list/help-key/demo.component.spec.ts
  apps/code-examples/src/app/code-examples/layout/description-list/horizontal/demo.component.spec.ts
  apps/code-examples/src/app/code-examples/layout/description-list/inline-help/demo.component.spec.ts
  apps/code-examples/src/app/code-examples/layout/description-list/long-description/demo.component.spec.ts
  apps/code-examples/src/app/code-examples/layout/description-list/vertical/demo.component.spec.ts
  libs/components/layout/testing/src/modules/description-list/description-list-content-harness.ts
  libs/components/layout/testing/src/modules/description-list/description-list-description-harness.ts
  libs/components/layout/testing/src/modules/description-list/description-list-harness-filters.ts
  libs/components/layout/testing/src/modules/description-list/description-list-harness.spec.ts
  libs/components/layout/testing/src/modules/description-list/description-list-harness.ts
  libs/components/layout/testing/src/modules/description-list/description-list-term-harness.ts
  libs/components/layout/testing/src/modules/description-list/fixtures/description-list-test.component.html
  libs/components/layout/testing/src/modules/description-list/fixtures/description-list-test.component.ts
  libs/components/layout/testing/src/public-api.ts
Labels: risk level (author): 1

#3119 feat(components/split-view): tokenize split view styles
  apps/e2e/split-view-storybook-e2e/src/e2e/split-view.component.cy.ts
  apps/e2e/split-view-storybook/project.json
  libs/components/split-view/src/lib/modules/split-view/split-view-drawer.component.scss
  libs/components/split-view/src/lib/modules/split-view/split-view-workspace-footer.component.html
  libs/components/split-view/src/lib/modules/split-view/split-view-workspace-footer.component.scss
  libs/components/split-view/src/lib/modules/split-view/split-view-workspace-header.component.scss
  libs/components/split-view/src/lib/modules/split-view/split-view-workspace.component.scss
  libs/components/split-view/src/lib/modules/split-view/split-view.component.scss
Labels: risk level (author): 2

#3125 feat(components/layout): add harness for description list (#3124)
  apps/code-examples/src/app/code-examples/layout/description-list/help-key/demo.component.spec.ts
  apps/code-examples/src/app/code-examples/layout/description-list/horizontal/demo.component.spec.ts
  apps/code-examples/src/app/code-examples/layout/description-list/inline-help/demo.component.spec.ts
  apps/code-examples/src/app/code-examples/layout/description-list/long-description/demo.component.spec.ts
  apps/code-examples/src/app/code-examples/layout/description-list/vertical/demo.component.spec.ts
  libs/components/code-examples/src/lib/modules/layout/description-list/help-key/example.component.spec.ts
  libs/components/code-examples/src/lib/modules/layout/description-list/horizontal/example.component.spec.ts
  libs/components/code-examples/src/lib/modules/layout/description-list/inline-help/example.component.spec.ts
  libs/components/code-examples/src/lib/modules/layout/description-list/long-description/example.component.spec.ts
  libs/components/code-examples/src/lib/modules/layout/description-list/vertical/example.component.spec.ts
  libs/components/layout/testing/src/modules/description-list/description-list-content-harness.ts
  libs/components/layout/testing/src/modules/description-list/description-list-description-harness.ts
  libs/components/layout/testing/src/modules/description-list/description-list-harness-filters.ts
  libs/components/layout/testing/src/modules/description-list/description-list-harness.spec.ts
  libs/components/layout/testing/src/modules/description-list/description-list-harness.ts
  libs/components/layout/testing/src/modules/description-list/description-list-term-harness.ts
  libs/components/layout/testing/src/modules/description-list/fixtures/description-list-test.component.html
  libs/components/layout/testing/src/modules/description-list/fixtures/description-list-test.component.ts
  libs/components/layout/testing/src/public-api.ts
Labels: risk level (author): 1

#3122 feat(components/manifest): add code example file contents (internal use only)
  libs/components/indicators/documentation.json
  libs/components/manifest/code-examples.json
  libs/components/manifest/package.json
  libs/components/manifest/src/__snapshots__/get-documentation-group.test.ts.snap
  libs/components/manifest/src/generator/__snapshots__/generate-manifest.test.ts.snap
  libs/components/manifest/src/generator/generate-manifest.test.ts
  libs/components/manifest/src/generator/generate-manifest.ts
  libs/components/manifest/src/generator/get-code-examples.ts
  libs/components/manifest/src/generator/get-documentation-config.ts
  libs/components/manifest/src/generator/get-public-api.ts
  libs/components/manifest/src/generator/testing/fixtures/example-packages/code-examples/documentation.json
  libs/components/manifest/src/generator/testing/fixtures/example-packages/code-examples/package.json
  libs/components/manifest/src/generator/testing/fixtures/example-packages/code-examples/src/index.ts
  libs/components/manifest/src/generator/testing/fixtures/example-packages/code-examples/src/lib/types.ts
  libs/components/manifest/src/generator/testing/fixtures/example-packages/code-examples/tsconfig.json
  libs/components/manifest/src/generator/testing/fixtures/example-packages/code-examples/tsconfig.lib.json
  libs/components/manifest/src/generator/testing/fixtures/example-packages/code-examples/tsconfig.lib.prod.json
  libs/components/manifest/src/generator/testing/fixtures/example-packages/foo/documentation.json
  libs/components/manifest/src/generator/testing/fixtures/example-packages/foo/src/index.ts
  libs/components/manifest/src/generator/testing/fixtures/example-packages/foo/src/lib/foo.class.ts
  libs/components/manifest/src/generator/testing/fixtures/example-packages/invalid-docs-id/documentation.json
  libs/components/manifest/src/generator/testing/fixtures/example-packages/invalid-docs-id/package.json
  libs/components/manifest/src/generator/utility/get-class.ts
  libs/components/manifest/src/generator/utility/get-comment.ts
  libs/components/manifest/src/generator/utility/get-directive.ts
  libs/components/manifest/src/generator/utility/get-enum.ts
  libs/components/manifest/src/generator/utility/get-function.ts
  libs/components/manifest/src/generator/utility/get-interface.ts
  libs/components/manifest/src/generator/utility/get-type-alias.ts
  libs/components/manifest/src/generator/utility/get-variable.ts
  libs/components/manifest/src/generator/validations.ts
  libs/components/manifest/src/get-documentation-group.test.ts
  libs/components/manifest/src/get-documentation-group.ts
  libs/components/manifest/src/index.ts
  libs/components/manifest/src/types/base-def.ts
  libs/components/manifest/src/types/manifest.ts
  libs/components/router/documentation.json
  libs/components/router/testing/src/modules/href/href-harness-filters.ts
  libs/components/router/testing/src/public-api.ts
  libs/components/tabs/documentation.json
  libs/components/theme/documentation.json
  package-lock.json
  package.json
Labels: risk level (author): 1

#3114 chore: release 11.39.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease 11.x.x: pending

#3127 chore: changelog for 11.39.0 (#3114) 🍒
  CHANGELOG.md
Labels: risk level (author): 1, risk level (reviewer): 1

#3131 feat(components/pages): add `sky-modal-link-list` component
  libs/components/pages/src/index.ts
  libs/components/pages/src/lib/modules/action-hub/action-hub.component.html
  libs/components/pages/src/lib/modules/modal-link-list/modal-link-list.component.html
  libs/components/pages/src/lib/modules/modal-link-list/modal-link-list.component.spec.ts
  libs/components/pages/src/lib/modules/modal-link-list/modal-link-list.component.ts
  libs/components/pages/src/lib/modules/page/page.module.ts
Labels: risk level (author): 1

#3132 feat(components/pages): add `sky-modal-link-list` component (#3131)
  libs/components/pages/src/index.ts
  libs/components/pages/src/lib/modules/action-hub/action-hub.component.html
  libs/components/pages/src/lib/modules/modal-link-list/modal-link-list.component.html
  libs/components/pages/src/lib/modules/modal-link-list/modal-link-list.component.spec.ts
  libs/components/pages/src/lib/modules/modal-link-list/modal-link-list.component.ts
  libs/components/pages/src/lib/modules/page/page.module.ts
Labels: risk level (author): 1

#3134 fix(components/router): skyHref should shut down when the application is destroyed
  libs/components/router/src/lib/modules/href/fixtures/href-resolver-fixture.service.ts
  libs/components/router/src/lib/modules/href/href.directive.spec.ts
  libs/components/router/src/lib/modules/href/href.directive.ts
Labels: risk level (author): 1

#3135 chore: add tokenization github copilot prompts
  .github/prompts/add-scss-override.prompt.md
  .github/prompts/scss-override-mixins.prompt.md
  .github/prompts/setup-tokenization.prompt.md
Labels: risk level (author): 1

#3129 feat(components/popovers): add support for custom trigger buttons to dropdown harness
  libs/components/popovers/testing/src/modules/dropdown/dropdown-harness.spec.ts
  libs/components/popovers/testing/src/modules/dropdown/dropdown-harness.ts
Labels: risk level (author): 1

#3133 chore: release 11.40.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease 11.x.x: pending

#3138 chore: changelog for 11.40.0 (#3133) 🍒
  CHANGELOG.md
Labels: risk level (author): 1, risk level (reviewer): 1

#3136 fix(components/router): skyHref should shut down when the application is destroyed (#3134)
  libs/components/router/src/lib/modules/href/fixtures/href-resolver-fixture.service.ts
  libs/components/router/src/lib/modules/href/href.directive.spec.ts
  libs/components/router/src/lib/modules/href/href.directive.ts
Labels: risk level (author): 1

#3128 fix(components/datetime): address flaky display behavior of key date tooltips
  libs/components/datetime/src/lib/modules/datepicker/calendar/datepicker-calendar-inner.component.ts
  libs/components/datetime/src/lib/modules/datepicker/calendar/daypicker-cell.component.html
  libs/components/datetime/src/lib/modules/datepicker/calendar/daypicker-cell.component.spec.ts
  libs/components/datetime/src/lib/modules/datepicker/calendar/daypicker-cell.component.ts
Labels: risk level (author): 2

#3140 fix(components/datetime): address flaky display behavior of key date tooltips (#3128)
  libs/components/datetime/src/lib/modules/datepicker/calendar/datepicker-calendar-inner.component.ts
  libs/components/datetime/src/lib/modules/datepicker/calendar/daypicker-cell.component.html
  libs/components/datetime/src/lib/modules/datepicker/calendar/daypicker-cell.component.spec.ts
  libs/components/datetime/src/lib/modules/datepicker/calendar/daypicker-cell.component.ts
Labels: risk level (author): 2

#3120 feat(components/core): add SkyViewkeeper support for SkyAppViewportService properties
  libs/components/core/src/lib/modules/dock/dock.component.spec.ts
  libs/components/core/src/lib/modules/viewkeeper/viewkeeper-host-options.ts
  libs/components/core/src/lib/modules/viewkeeper/viewkeeper-options.ts
  libs/components/core/src/lib/modules/viewkeeper/viewkeeper.spec.ts
  libs/components/core/src/lib/modules/viewkeeper/viewkeeper.ts
  libs/components/theme/src/lib/viewport/viewport-reserve-args.ts
  libs/components/theme/src/lib/viewport/viewport.service.spec.ts
  libs/components/theme/src/lib/viewport/viewport.service.ts
  scripts/publish-local.ts
Labels: risk level (author): 2

#3137 feat(components/popovers): add support for custom trigger buttons to dropdown harness (#3129)
  libs/components/popovers/testing/src/modules/dropdown/dropdown-harness.spec.ts
  libs/components/popovers/testing/src/modules/dropdown/dropdown-harness.ts
Labels: risk level (author): 1

#3144 chore: changelog for 11.41.0 (#3139) 🍒
  CHANGELOG.md
Labels: risk level (author): 1, risk level (reviewer): 1

#3141 feat(components/toast): add toast and toaster harness
  apps/code-examples/src/app/code-examples/toast/toast/basic/demo.component.spec.ts
  apps/code-examples/src/app/code-examples/toast/toast/basic/demo.component.ts
  apps/code-examples/src/app/code-examples/toast/toast/custom-component/custom-toast-harness.ts
  apps/code-examples/src/app/code-examples/toast/toast/custom-component/demo.component.spec.ts
  apps/code-examples/src/app/code-examples/toast/toast/custom-component/demo.component.ts
  libs/components/core/testing/src/modules/overlay/overlay-harness-filters.ts
  libs/components/toast/package.json
  libs/components/toast/project.json
  libs/components/toast/src/lib/modules/toast/types/toast-config.ts
  libs/components/toast/testing/src/modules/toast-harness-filters.ts
  libs/components/toast/testing/src/modules/toast-harness.ts
  libs/components/toast/testing/src/modules/toaster-harness.spec.ts
  libs/components/toast/testing/src/modules/toaster-harness.ts
  libs/components/toast/testing/src/public-api.ts
Labels: risk level (author): 1

#3148 ci: workflow to keep automated-translations in sync (#3145)
  .github/workflows/automated-translations.yml
  scripts/automated-translations.ps1
Labels: risk level (author): 1

#3147 feat(components/toast): add toast and toaster harness (#3141)
  apps/code-examples/src/app/code-examples/toast/toast/basic/demo.component.spec.ts
  apps/code-examples/src/app/code-examples/toast/toast/basic/demo.component.ts
  apps/code-examples/src/app/code-examples/toast/toast/custom-component/custom-toast-harness.ts
  apps/code-examples/src/app/code-examples/toast/toast/custom-component/demo.component.spec.ts
  apps/code-examples/src/app/code-examples/toast/toast/custom-component/demo.component.ts
  libs/components/code-examples/src/lib/modules/toast/toast/basic/example.component.spec.ts
  libs/components/code-examples/src/lib/modules/toast/toast/basic/example.component.ts
  libs/components/code-examples/src/lib/modules/toast/toast/custom-component/custom-toast-harness.ts
  libs/components/code-examples/src/lib/modules/toast/toast/custom-component/example.component.spec.ts
  libs/components/code-examples/src/lib/modules/toast/toast/custom-component/example.component.ts
  libs/components/core/testing/src/modules/overlay/overlay-harness-filters.ts
  libs/components/toast/package.json
  libs/components/toast/project.json
  libs/components/toast/src/lib/modules/toast/types/toast-config.ts
  libs/components/toast/testing/src/modules/toast-harness-filters.ts
  libs/components/toast/testing/src/modules/toast-harness.ts
  libs/components/toast/testing/src/modules/toaster-harness.spec.ts
  libs/components/toast/testing/src/modules/toaster-harness.ts
  libs/components/toast/testing/src/public-api.ts
Labels: risk level (author): 1

#3115 chore: release 12.0.0-alpha.4
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#3151 fix(components/tabs): vertical tabs keyboard operable in mobile view (#3150)
  libs/components/tabs/src/lib/modules/vertical-tabset/vertical-tabset.component.html
  libs/components/tabs/src/lib/modules/vertical-tabset/vertical-tabset.component.spec.ts
  libs/components/tabs/src/lib/modules/vertical-tabset/vertical-tabset.component.ts
Labels: risk level (author): 2

#3153 fix(components/popovers): fix sporadic dropdown menu misalignment
  libs/components/popovers/src/lib/modules/dropdown/dropdown.component.ts
Labels: risk level (author): 3

#3146 chore: release 11.42.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease 11.x.x: pending

#3156 fix(components/layout): exclude controls text content when returning heading text for the box harness
  libs/components/layout/testing/src/modules/box/box-harness.spec.ts
  libs/components/layout/testing/src/modules/box/box-harness.ts
  libs/components/layout/testing/src/modules/box/fixtures/box-harness-test.component.html
  libs/components/layout/testing/src/modules/box/fixtures/box-harness-test.component.ts
Labels: risk level (author): 3

#3155 feat: add code example viewer component (internal use only)
  .github/workflows/validate-pr.yml
  .prettierignore
  .skyuxdev.json
  libs/components/docs-tools/README.md
  libs/components/docs-tools/eslint.config.js
  libs/components/docs-tools/karma.conf.js
  libs/components/docs-tools/ng-package.json
  libs/components/docs-tools/package.json
  libs/components/docs-tools/project.json
  libs/components/docs-tools/src/assets/locales/resources_en_US.json
  libs/components/docs-tools/src/index.ts
  libs/components/docs-tools/src/lib/modules/clipboard/clipboard.service.spec.ts
  libs/components/docs-tools/src/lib/modules/clipboard/clipboard.service.ts
  libs/components/docs-tools/src/lib/modules/code-example-viewer/code-example-viewer.component.html
  libs/components/docs-tools/src/lib/modules/code-example-viewer/code-example-viewer.component.scss
  libs/components/docs-tools/src/lib/modules/code-example-viewer/code-example-viewer.component.spec.ts
  libs/components/docs-tools/src/lib/modules/code-example-viewer/code-example-viewer.component.ts
  libs/components/docs-tools/src/lib/modules/code-example-viewer/code-example-viewer.module.ts
  libs/components/docs-tools/src/lib/modules/code-example-viewer/stackblitz-launch-config.ts
  libs/components/docs-tools/src/lib/modules/code-example-viewer/stackblitz.service.spec.ts
  libs/components/docs-tools/src/lib/modules/code-example-viewer/stackblitz.service.ts
  libs/components/docs-tools/src/lib/modules/code-snippet/code-snippet-language.ts
  libs/components/docs-tools/src/lib/modules/code-snippet/code-snippet.component.html
  libs/components/docs-tools/src/lib/modules/code-snippet/code-snippet.component.scss
  libs/components/docs-tools/src/lib/modules/code-snippet/code-snippet.component.spec.ts
  libs/components/docs-tools/src/lib/modules/code-snippet/code-snippet.component.ts
  libs/components/docs-tools/src/lib/modules/code-snippet/code-snippet.module.ts
  libs/components/docs-tools/src/lib/modules/code-snippet/themes/visual-studio-light.scss
  libs/components/docs-tools/src/lib/modules/shared/sky-docs-tools-resources.module.ts
  libs/components/docs-tools/tsconfig.json
  libs/components/docs-tools/tsconfig.lib.json
  libs/components/docs-tools/tsconfig.lib.prod.json
  libs/components/docs-tools/tsconfig.spec.json
  libs/components/packages/package.json
  package-lock.json
  package.json
  tsconfig.base.json
Labels: risk level (author): 1

#3158 test: wait for SVG icon sprite when loading fonts
  apps/e2e/popovers-storybook-e2e/src/e2e/dropdown.component.cy.ts
  apps/e2e/popovers-storybook/src/app/dropdown/dropdown.component.html
  apps/e2e/popovers-storybook/src/app/dropdown/dropdown.component.ts
  libs/components/storybook/src/lib/font-loading/font-loading.service.spec.ts
  libs/components/storybook/src/lib/font-loading/font-loading.service.ts
Labels: risk level (author): 1

#3159 test: wait for SVG icon sprite when loading fonts (#3158)
  apps/e2e/popovers-storybook-e2e/src/e2e/dropdown.component.cy.ts
  apps/e2e/popovers-storybook/src/app/dropdown/dropdown.component.html
  apps/e2e/popovers-storybook/src/app/dropdown/dropdown.component.ts
  libs/components/storybook/src/lib/font-loading/font-loading.service.spec.ts
  libs/components/storybook/src/lib/font-loading/font-loading.service.ts
Labels: risk level (author): 1

#3157 chore: changelog for 11.42.0 (#3146) 🍒
  CHANGELOG.md
Labels: risk level (author): 1, risk level (reviewer): 1

#3161 feat(components/layout): tokenize text expand styles
  apps/e2e/layout-storybook-e2e/src/e2e/text-expand-repeater.component.cy.ts
  apps/e2e/layout-storybook-e2e/src/e2e/text-expand.component.cy.ts
  libs/components/layout/src/lib/modules/text-expand/text-expand.component.scss
Labels: risk level (author): 2

#3154 fix(components/popovers): fix sporadic dropdown menu misalignment (#3153)
  libs/components/popovers/src/lib/modules/dropdown/dropdown.component.ts
Labels: risk level (author): 3

#3160 fix: use alias instead of property name for directive inputs in the manifest
  .github/workflows/validate-pr.yml
  libs/components/manifest/src/generator/__snapshots__/generate-manifest.test.ts.snap
  libs/components/manifest/src/generator/plugins/typedoc-plugin-decorators.mjs
  libs/components/manifest/src/generator/testing/fixtures/example-packages/foo/src/lib/foo.directive.ts
  libs/components/manifest/src/generator/utility/get-directive.ts
Labels: risk level (author): 1

#3162 fix: use alias instead of property name for directive inputs in the manifest (#3160)
  libs/components/manifest/src/generator/__snapshots__/generate-manifest.test.ts.snap
  libs/components/manifest/src/generator/plugins/typedoc-plugin-decorators.mjs
  libs/components/manifest/src/generator/testing/fixtures/example-packages/foo/src/lib/foo.directive.ts
  libs/components/manifest/src/generator/utility/get-directive.ts
Labels: risk level (author): 1

#3163 chore: release 11.42.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease 11.x.x: pending

#3170 chore: changelog for 11.42.1 (#3163) 🍒
  CHANGELOG.md
Labels: risk level (author): 1, risk level (reviewer): 1

#3169 fix(components/theme): set initial active status for viewport reserve space element (#3168)
  libs/components/theme/src/lib/viewport/viewport.service.spec.ts
  libs/components/theme/src/lib/viewport/viewport.service.ts
Labels: risk level (author): 1

#3167 feat(components/lookup): lookup and country field input contents are selected automatically on focus
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-editors/cell-editor-lookup/cell-editor-lookup.component.spec.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-editors/cell-editor-lookup/cell-editor-lookup.component.ts
  libs/components/lookup/src/lib/modules/lookup/lookup.component.html
  libs/components/lookup/src/lib/modules/lookup/lookup.component.spec.ts
  libs/components/lookup/src/lib/modules/lookup/lookup.component.ts
Labels: risk level (author): 2

#3166 feat(components/lookup)!: remove flag from country field input
  apps/e2e/lookup-storybook-e2e/src/e2e/country-field.component.cy.ts
  apps/e2e/lookup-storybook/src/app/country-field/country-field.component.html
  apps/e2e/lookup-storybook/src/app/country-field/country-field.component.stories.ts
  apps/e2e/lookup-storybook/src/app/country-field/country-field.component.ts
  libs/components/lookup/src/lib/modules/country-field/country-field.component.html
  libs/components/lookup/src/lib/modules/country-field/country-field.component.scss
  libs/components/lookup/src/lib/modules/country-field/country-field.component.spec.ts
  libs/components/lookup/src/lib/modules/country-field/country-field.component.ts
  libs/components/lookup/testing/src/legacy/country-field/country-field-fixture.spec.ts
  libs/components/lookup/testing/src/legacy/country-field/country-field-fixture.ts
  libs/components/phone-field/src/lib/modules/phone-field/phone-field.component.html
Labels: risk level (author): 2, screenshot removed

#3173 fix(components/toast): move harness files under `/toast` to match docs
  libs/components/toast/testing/src/modules/toast/toast-harness-filters.ts
  libs/components/toast/testing/src/modules/toast/toast-harness.ts
  libs/components/toast/testing/src/modules/toast/toaster-harness.spec.ts
  libs/components/toast/testing/src/modules/toast/toaster-harness.ts
  libs/components/toast/testing/src/public-api.ts
Labels: risk level (author): 1

#3174 fix(components/toast): move harness files under `/toast` to match docs (#3173)
  libs/components/toast/testing/src/modules/toast/toast-harness-filters.ts
  libs/components/toast/testing/src/modules/toast/toast-harness.ts
  libs/components/toast/testing/src/modules/toast/toaster-harness.spec.ts
  libs/components/toast/testing/src/modules/toast/toaster-harness.ts
  libs/components/toast/testing/src/public-api.ts
Labels: risk level (author): 1

#3172 chore: release 11.43.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease 11.x.x: pending

#3152 chore: release 12.0.0-alpha.5
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#3176 feat(components/help-inline)!: remove TemplateRef return type on getPopoverContent
  libs/components/colorpicker/testing/src/modules/colorpicker/colorpicker-harness.ts
  libs/components/forms/testing/src/modules/checkbox/checkbox-group-harness.ts
  libs/components/forms/testing/src/modules/checkbox/checkbox-harness.ts
  libs/components/forms/testing/src/modules/field-group/field-group-harness.ts
  libs/components/forms/testing/src/modules/file-attachment/file-attachment/file-attachment-harness.ts
  libs/components/forms/testing/src/modules/file-attachment/file-drop/file-drop-harness.ts
  libs/components/forms/testing/src/modules/input-box/input-box-harness.ts
  libs/components/forms/testing/src/modules/radio/radio-group-harness.ts
  libs/components/forms/testing/src/modules/radio/radio-harness.ts
  libs/components/help-inline/testing/src/modules/help-inline/help-inline-harness.ts
  libs/components/indicators/testing/src/modules/status-indicator/status-indicator-harness.ts
  libs/components/layout/testing/src/modules/box/box-harness.ts
  libs/components/layout/testing/src/modules/description-list/description-list-content-harness.ts
  libs/components/modals/testing/src/modules/modal/modal-harness.ts
  libs/components/progress-indicator/testing/src/modules/progress-indicator/progress-indicator-item-harness.ts
  libs/components/tiles/testing/src/modules/tiles/tile-harness.ts
Labels: risk level (author): 1

#3164 feat(components/avatar): tokenize avatar styles
  apps/e2e/avatar-storybook-e2e/src/e2e/avatar.component.cy.ts
  apps/e2e/avatar-storybook/project.json
  libs/components/avatar/src/lib/modules/avatar/avatar.component.scss
  libs/components/avatar/src/lib/modules/avatar/avatar.inner.component.scss
  libs/components/layout/src/lib/modules/page-summary/page-summary-image.component.scss
  libs/components/theme/package.json
  libs/components/theme/src/lib/styles/_public-api/_compat/_variables.scss
  package-lock.json
  package.json
Labels: risk level (author): 2

#3178 fix(components/core)!: remove live announcer message from DOM after a set duration
  apps/playground/src/app/components/core/core.module.ts
  apps/playground/src/app/components/core/live-announcer/live-announcer.component.html
  apps/playground/src/app/components/core/live-announcer/live-announcer.component.ts
  libs/components/core/src/lib/modules/live-announcer/live-announcer.service.spec.ts
  libs/components/core/src/lib/modules/live-announcer/live-announcer.service.ts
  libs/components/core/src/lib/modules/live-announcer/types/live-announcer-args.ts
Labels: risk level (author): 3

#3180 fix: mark all harness `hostSelector` properties as "internal"
  libs/components/core/testing/src/shared/harness-filters.ts
  libs/components/core/testing/src/shared/input-harness.ts
  libs/components/modals/testing/src/modules/confirm/confirm-button-harness.ts
  libs/components/modals/testing/src/modules/confirm/confirm-harness.ts
  libs/components/pages/testing/src/modules/action-hub/action-hub-harness.ts
  libs/components/router/testing/src/modules/href/href-harness.ts
Labels: risk level (author): 1

#3183 fix: mark all harness `hostSelector` properties as "internal" (#3180)
  libs/components/core/testing/src/shared/harness-filters.ts
  libs/components/core/testing/src/shared/input-harness.ts
  libs/components/modals/testing/src/modules/confirm/confirm-button-harness.ts
  libs/components/modals/testing/src/modules/confirm/confirm-harness.ts
  libs/components/pages/testing/src/modules/action-hub/action-hub-harness.ts
  libs/components/router/testing/src/modules/href/href-harness.ts
Labels: risk level (author): 1

#3177 chore: release 12.0.0-alpha.6
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#3186 chore: update library resources
  .github/workflows/automated-translations.yml
  libs/components/a11y/src/assets/locales/resources_fr_CA.json
  libs/components/a11y/src/lib/modules/shared/sky-a11y-resources.module.ts
  libs/components/action-bars/src/assets/locales/resources_fr_CA.json
  libs/components/action-bars/src/lib/modules/shared/sky-action-bars-resources.module.ts
  libs/components/ag-grid/src/assets/locales/resources_fr_CA.json
  libs/components/ag-grid/src/lib/modules/shared/sky-ag-grid-resources.module.ts
  libs/components/angular-tree-component/src/assets/locales/resources_fr_CA.json
  libs/components/angular-tree-component/src/lib/modules/shared/sky-angular-tree-component-resources.module.ts
  libs/components/avatar/src/assets/locales/resources_fr_CA.json
  libs/components/avatar/src/lib/modules/shared/sky-avatar-resources.module.ts
  libs/components/colorpicker/src/assets/locales/resources_fr_CA.json
  libs/components/colorpicker/src/lib/modules/shared/sky-colorpicker-resources.module.ts
  libs/components/core/src/assets/locales/resources_fr_CA.json
  libs/components/core/src/lib/modules/shared/sky-core-resources.module.ts
  libs/components/data-manager/src/assets/locales/resources_fr_CA.json
  libs/components/data-manager/src/lib/modules/shared/sky-data-manager-resources.module.ts
  libs/components/datetime/src/assets/locales/resources_fr_CA.json
  libs/components/datetime/src/lib/modules/shared/sky-datetime-resources.module.ts
  libs/components/errors/src/assets/locales/resources_fr_CA.json
  libs/components/errors/src/lib/modules/shared/sky-errors-resources.module.ts
  libs/components/flyout/src/assets/locales/resources_fr_CA.json
  libs/components/flyout/src/lib/modules/shared/sky-flyout-resources.module.ts
  libs/components/forms/src/assets/locales/resources_fr_CA.json
  libs/components/forms/src/lib/modules/shared/sky-forms-resources.module.ts
  libs/components/grids/src/assets/locales/resources_fr_CA.json
  libs/components/grids/src/lib/modules/shared/sky-grids-resources.module.ts
  libs/components/help-inline/src/assets/locales/resources_fr_CA.json
  libs/components/help-inline/src/lib/modules/shared/sky-help-inline-resources.module.ts
  libs/components/indicators/src/assets/locales/resources_fr_CA.json
  libs/components/indicators/src/lib/modules/shared/sky-indicators-resources.module.ts
  libs/components/inline-form/src/assets/locales/resources_fr_CA.json
  libs/components/inline-form/src/lib/modules/shared/sky-inline-form-resources.module.ts
  libs/components/layout/src/assets/locales/resources_fr_CA.json
  libs/components/layout/src/lib/modules/shared/sky-layout-resources.module.ts
  libs/components/lists/src/assets/locales/resources_fr_CA.json
  libs/components/lists/src/lib/modules/shared/sky-lists-resources.module.ts
  libs/components/lookup/src/assets/locales/resources_fr_CA.json
  libs/components/lookup/src/lib/modules/shared/sky-lookup-resources.module.ts
  libs/components/modals/src/assets/locales/resources_fr_CA.json
  libs/components/modals/src/lib/modules/shared/sky-modals-resources.module.ts
  libs/components/pages/src/assets/locales/resources_fr_CA.json
  libs/components/pages/src/lib/modules/shared/sky-pages-resources.module.ts
  libs/components/phone-field/src/assets/locales/resources_fr_CA.json
  libs/components/phone-field/src/lib/modules/shared/sky-phone-field-resources.module.ts
  libs/components/popovers/src/assets/locales/resources_fr_CA.json
  libs/components/popovers/src/lib/modules/shared/sky-popovers-resources.module.ts
  libs/components/progress-indicator/src/assets/locales/resources_fr_CA.json
  libs/components/progress-indicator/src/lib/modules/shared/sky-progress-indicator-resources.module.ts
  libs/components/split-view/src/assets/locales/resources_fr_CA.json
  libs/components/split-view/src/lib/modules/shared/sky-split-view-resources.module.ts
  libs/components/tabs/src/assets/locales/resources_fr_CA.json
  libs/components/tabs/src/lib/modules/shared/sky-tabs-resources.module.ts
  libs/components/text-editor/src/assets/locales/resources_fr_CA.json
  libs/components/text-editor/src/lib/modules/shared/sky-text-editor-resources.module.ts
  libs/components/tiles/src/assets/locales/resources_fr_CA.json
  libs/components/tiles/src/lib/modules/shared/sky-tiles-resources.module.ts
  libs/components/toast/src/assets/locales/resources_fr_CA.json
  libs/components/toast/src/lib/modules/shared/sky-toast-resources.module.ts
  scripts/automated-translations.ps1
Labels: risk level (author): 1, skip e2e

#3188 ci: pin version for nrwl/nx-set-shas
  .github/actions/nx-set-shas/action.yml
Labels: risk level (author): 1, skip e2e

#3189 ci: pin version for nrwl/nx-set-shas (#3188)
  .github/actions/nx-set-shas/action.yml
Labels: risk level (author): 1

#3187 chore: update library resources (#3186)
  .github/workflows/automated-translations.yml
  libs/components/a11y/src/assets/locales/resources_fr_CA.json
  libs/components/a11y/src/lib/modules/shared/sky-a11y-resources.module.ts
  libs/components/action-bars/src/assets/locales/resources_fr_CA.json
  libs/components/action-bars/src/lib/modules/shared/sky-action-bars-resources.module.ts
  libs/components/ag-grid/src/assets/locales/resources_fr_CA.json
  libs/components/ag-grid/src/lib/modules/shared/sky-ag-grid-resources.module.ts
  libs/components/angular-tree-component/src/assets/locales/resources_fr_CA.json
  libs/components/angular-tree-component/src/lib/modules/shared/sky-angular-tree-component-resources.module.ts
  libs/components/avatar/src/assets/locales/resources_fr_CA.json
  libs/components/avatar/src/lib/modules/shared/sky-avatar-resources.module.ts
  libs/components/colorpicker/src/assets/locales/resources_fr_CA.json
  libs/components/colorpicker/src/lib/modules/shared/sky-colorpicker-resources.module.ts
  libs/components/core/src/assets/locales/resources_fr_CA.json
  libs/components/core/src/lib/modules/shared/sky-core-resources.module.ts
  libs/components/data-manager/src/assets/locales/resources_fr_CA.json
  libs/components/data-manager/src/lib/modules/shared/sky-data-manager-resources.module.ts
  libs/components/datetime/src/assets/locales/resources_fr_CA.json
  libs/components/datetime/src/lib/modules/shared/sky-datetime-resources.module.ts
  libs/components/errors/src/assets/locales/resources_fr_CA.json
  libs/components/errors/src/lib/modules/shared/sky-errors-resources.module.ts
  libs/components/flyout/src/assets/locales/resources_fr_CA.json
  libs/components/flyout/src/lib/modules/shared/sky-flyout-resources.module.ts
  libs/components/forms/src/assets/locales/resources_fr_CA.json
  libs/components/forms/src/lib/modules/shared/sky-forms-resources.module.ts
  libs/components/grids/src/assets/locales/resources_fr_CA.json
  libs/components/grids/src/lib/modules/shared/sky-grids-resources.module.ts
  libs/components/help-inline/src/assets/locales/resources_fr_CA.json
  libs/components/help-inline/src/lib/modules/shared/sky-help-inline-resources.module.ts
  libs/components/indicators/src/assets/locales/resources_fr_CA.json
  libs/components/indicators/src/lib/modules/shared/sky-indicators-resources.module.ts
  libs/components/inline-form/src/assets/locales/resources_fr_CA.json
  libs/components/inline-form/src/lib/modules/shared/sky-inline-form-resources.module.ts
  libs/components/layout/src/assets/locales/resources_fr_CA.json
  libs/components/layout/src/lib/modules/shared/sky-layout-resources.module.ts
  libs/components/lists/src/assets/locales/resources_fr_CA.json
  libs/components/lists/src/lib/modules/shared/sky-lists-resources.module.ts
  libs/components/lookup/src/assets/locales/resources_fr_CA.json
  libs/components/lookup/src/lib/modules/shared/sky-lookup-resources.module.ts
  libs/components/modals/src/assets/locales/resources_fr_CA.json
  libs/components/modals/src/lib/modules/shared/sky-modals-resources.module.ts
  libs/components/pages/src/assets/locales/resources_fr_CA.json
  libs/components/pages/src/lib/modules/shared/sky-pages-resources.module.ts
  libs/components/phone-field/src/assets/locales/resources_fr_CA.json
  libs/components/phone-field/src/lib/modules/shared/sky-phone-field-resources.module.ts
  libs/components/popovers/src/assets/locales/resources_fr_CA.json
  libs/components/popovers/src/lib/modules/shared/sky-popovers-resources.module.ts
  libs/components/progress-indicator/src/assets/locales/resources_fr_CA.json
  libs/components/progress-indicator/src/lib/modules/shared/sky-progress-indicator-resources.module.ts
  libs/components/split-view/src/assets/locales/resources_fr_CA.json
  libs/components/split-view/src/lib/modules/shared/sky-split-view-resources.module.ts
  libs/components/tabs/src/assets/locales/resources_fr_CA.json
  libs/components/tabs/src/lib/modules/shared/sky-tabs-resources.module.ts
  libs/components/text-editor/src/assets/locales/resources_fr_CA.json
  libs/components/text-editor/src/lib/modules/shared/sky-text-editor-resources.module.ts
  libs/components/tiles/src/assets/locales/resources_fr_CA.json
  libs/components/tiles/src/lib/modules/shared/sky-tiles-resources.module.ts
  libs/components/toast/src/assets/locales/resources_fr_CA.json
  libs/components/toast/src/lib/modules/shared/sky-toast-resources.module.ts
  scripts/automated-translations.ps1
Labels: risk level (author): 1

#3182 fix(components/tabs): puts focus on active tab in mobile view
  libs/components/tabs/src/lib/modules/vertical-tabset/vertical-tabset.component.html
  libs/components/tabs/src/lib/modules/vertical-tabset/vertical-tabset.component.spec.ts
Labels: risk level (author): 2

#3184 chore: release 11.43.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease 11.x.x: pending

#3191 chore: changelog for 11.43.1 (#3184) 🍒
  CHANGELOG.md
Labels: risk level (author): 1, risk level (reviewer): 1

#3190 fix(components/tabs): puts focus on active tab in mobile view (#3182)
  libs/components/tabs/src/lib/modules/vertical-tabset/vertical-tabset.component.html
  libs/components/tabs/src/lib/modules/vertical-tabset/vertical-tabset.component.spec.ts
Labels: risk level (author): 2
