Repository blackbaud/skyux, pull requests merged in 2025-03, with the labels that each got.

#3179 feat(components/lookup): country field displays hint text within the dropdown before a search is executed
  apps/e2e/lookup-storybook-e2e/src/e2e/country-field.component.cy.ts
  apps/e2e/lookup-storybook/src/app/country-field/country-field.component.html
  apps/e2e/lookup-storybook/src/app/country-field/country-field.component.stories.ts
  apps/e2e/lookup-storybook/src/app/country-field/country-field.component.ts
  apps/playground/src/app/components/lookup/country-field/country-field.component.html
  libs/components/lookup/src/assets/locales/resources_en_US.json
  libs/components/lookup/src/lib/modules/autocomplete/autocomplete-adapter.service.ts
  libs/components/lookup/src/lib/modules/autocomplete/autocomplete.component.html
  libs/components/lookup/src/lib/modules/autocomplete/autocomplete.component.scss
  libs/components/lookup/src/lib/modules/autocomplete/autocomplete.component.spec.ts
  libs/components/lookup/src/lib/modules/autocomplete/autocomplete.component.ts
  libs/components/lookup/src/lib/modules/autocomplete/fixtures/autocomplete.component.fixture.html
  libs/components/lookup/src/lib/modules/autocomplete/fixtures/autocomplete.component.fixture.ts
  libs/components/lookup/src/lib/modules/country-field/country-field.component.html
  libs/components/lookup/src/lib/modules/country-field/country-field.component.spec.ts
  libs/components/lookup/src/lib/modules/country-field/country-field.component.ts
  libs/components/lookup/src/lib/modules/country-field/fixtures/country-field-input-box.component.fixture.html
  libs/components/lookup/src/lib/modules/country-field/fixtures/country-field-input-box.component.fixture.ts
  libs/components/lookup/src/lib/modules/country-field/types/country-field-context.ts
  libs/components/lookup/src/lib/modules/country-field/types/country.ts
  libs/components/lookup/src/lib/modules/shared/sky-lookup-resources.module.ts
  libs/components/phone-field/src/lib/modules/phone-field/phone-field.component.html
  libs/components/phone-field/src/lib/modules/phone-field/phone-field.component.spec.ts
  libs/components/phone-field/src/lib/modules/phone-field/phone-field.component.ts
Labels: risk level (author): 2, screenshot removed

#3181 feat(components/modals): support `fit` layout in modal content
  apps/integration-e2e/src/e2e/modal-split-view-tile-dashboard.cy.ts
  apps/integration/src/app/integrations/modal-split-view-tile-dashboard/context.ts
  apps/integration/src/app/integrations/modal-split-view-tile-dashboard/data.service.ts
  apps/integration/src/app/integrations/modal-split-view-tile-dashboard/modal-split-view-tile-dashboard.component.html
  apps/integration/src/app/integrations/modal-split-view-tile-dashboard/modal-split-view-tile-dashboard.component.spec.ts
  apps/integration/src/app/integrations/modal-split-view-tile-dashboard/modal-split-view-tile-dashboard.component.ts
  apps/integration/src/app/integrations/modal-split-view-tile-dashboard/modal.component.html
  apps/integration/src/app/integrations/modal-split-view-tile-dashboard/modal.component.ts
  apps/playground/src/app/components/modal/layout/fit/data-record.ts
  apps/playground/src/app/components/modal/layout/fit/data.service.ts
  apps/playground/src/app/components/modal/layout/fit/data.ts
  apps/playground/src/app/components/modal/layout/fit/demosplitview.component.html
  apps/playground/src/app/components/modal/layout/fit/demosplitview.component.ts
  apps/playground/src/app/components/modal/layout/fit/modal.component.html
  apps/playground/src/app/components/modal/layout/fit/modal.component.ts
  apps/playground/src/app/components/modal/modal-visual.component.html
  apps/playground/src/app/components/modal/modal-visual.component.ts
  libs/components/core/src/index.ts
  libs/components/core/src/lib/modules/layout-host/layout-host.directive.spec.ts
  libs/components/core/src/lib/modules/layout-host/layout-host.directive.ts
  libs/components/modals/src/lib/modules/modal/modal-component-adapter.service.ts
  libs/components/modals/src/lib/modules/modal/modal.component.html
  libs/components/modals/src/lib/modules/modal/modal.component.scss
  libs/components/modals/src/lib/modules/modal/modal.component.spec.ts
  libs/components/modals/src/lib/modules/modal/modal.component.ts
  libs/components/pages/src/lib/modules/page/page.component.ts
  tsconfig.base.json
Labels: risk level (author): 1

#3194 fix(components/ag-grid): show validator changes for editable cell
  apps/e2e/ag-grid-storybook/src/app/ag-grid/ag-grid-stories.component.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/ag-grid.service.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-renderers/cell-renderer-currency/cell-renderer-currency-validator.component.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-renderers/cell-renderer-currency/cell-renderer-currency.component.html
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-renderers/cell-renderer-currency/cell-renderer-currency.component.scss
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-renderers/cell-renderer-currency/cell-renderer-currency.component.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-validator/ag-grid-cell-validator-tooltip.component.html
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-validator/ag-grid-cell-validator-tooltip.component.scss
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-validator/ag-grid-cell-validator-tooltip.component.spec.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-validator/ag-grid-cell-validator-tooltip.component.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/fixtures/ag-grid-cell-validator-tooltip.component.fixture.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/types/cell-class.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/types/validator-properties.ts
  libs/components/ag-grid/src/lib/styles/_base.scss
  libs/components/ag-grid/src/lib/styles/_default.scss
  libs/components/ag-grid/src/lib/styles/_modern-dark.scss
  libs/components/ag-grid/src/lib/styles/_modern-light.scss
Labels: risk level (author): 1

#3200 fix(components/ag-grid): show validator changes for editable cell (#3194)
  apps/e2e/ag-grid-storybook/src/app/ag-grid/ag-grid-stories.component.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/ag-grid.service.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-renderers/cell-renderer-currency/cell-renderer-currency-validator.component.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-renderers/cell-renderer-currency/cell-renderer-currency.component.html
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-renderers/cell-renderer-currency/cell-renderer-currency.component.scss
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-renderers/cell-renderer-currency/cell-renderer-currency.component.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-validator/ag-grid-cell-validator-tooltip.component.html
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-validator/ag-grid-cell-validator-tooltip.component.scss
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-validator/ag-grid-cell-validator-tooltip.component.spec.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-validator/ag-grid-cell-validator-tooltip.component.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/fixtures/ag-grid-cell-validator-tooltip.component.fixture.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/types/cell-class.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/types/validator-properties.ts
  libs/components/ag-grid/src/lib/styles/_base.scss
  libs/components/ag-grid/src/lib/styles/_default.scss
  libs/components/ag-grid/src/lib/styles/_modern-dark.scss
  libs/components/ag-grid/src/lib/styles/_modern-light.scss
Labels: risk level (author): 1

#3197 fix(components/icon): migrate harness types from @skyux/indicators/testing
  apps/code-examples/src/app/code-examples/icon/basic/demo.component.spec.ts
  apps/code-examples/src/app/code-examples/icon/icon-button/demo.component.spec.ts
  libs/components/code-examples/src/lib/modules/icon/basic/example.component.spec.ts
  libs/components/code-examples/src/lib/modules/icon/icon-button/example.component.spec.ts
  libs/components/indicators/testing/src/public-api.ts
  libs/components/packages/src/schematics/migrations/update-12/help-inline-import-path/help-inline-import-path.schematic.ts
  libs/components/packages/src/schematics/migrations/update-12/icons-migration/icons-migration.schematic.spec.ts
  libs/components/packages/src/schematics/migrations/update-12/icons-migration/icons-migration.schematic.ts
  libs/components/packages/src/schematics/utility/move-class-to-library.spec.ts
  libs/components/packages/src/schematics/utility/move-class-to-library.ts
Labels: risk level (author): 2, screenshot removed

#3199 feat(components/modals): support `fit` layout in modal content (#3181)
  apps/integration-e2e/src/e2e/modal-split-view-tile-dashboard.cy.ts
  apps/integration/src/app/integrations/modal-split-view-tile-dashboard/context.ts
  apps/integration/src/app/integrations/modal-split-view-tile-dashboard/data.service.ts
  apps/integration/src/app/integrations/modal-split-view-tile-dashboard/modal-split-view-tile-dashboard.component.html
  apps/integration/src/app/integrations/modal-split-view-tile-dashboard/modal-split-view-tile-dashboard.component.spec.ts
  apps/integration/src/app/integrations/modal-split-view-tile-dashboard/modal-split-view-tile-dashboard.component.ts
  apps/integration/src/app/integrations/modal-split-view-tile-dashboard/modal.component.html
  apps/integration/src/app/integrations/modal-split-view-tile-dashboard/modal.component.ts
  apps/playground/src/app/components/modal/layout/fit/data-record.ts
  apps/playground/src/app/components/modal/layout/fit/data.service.ts
  apps/playground/src/app/components/modal/layout/fit/data.ts
  apps/playground/src/app/components/modal/layout/fit/demosplitview.component.html
  apps/playground/src/app/components/modal/layout/fit/demosplitview.component.ts
  apps/playground/src/app/components/modal/layout/fit/modal.component.html
  apps/playground/src/app/components/modal/layout/fit/modal.component.ts
  apps/playground/src/app/components/modal/modal-visual.component.html
  apps/playground/src/app/components/modal/modal-visual.component.ts
  libs/components/core/src/index.ts
  libs/components/core/src/lib/modules/layout-host/layout-host.directive.spec.ts
  libs/components/core/src/lib/modules/layout-host/layout-host.directive.ts
  libs/components/modals/src/lib/modules/modal/modal-component-adapter.service.ts
  libs/components/modals/src/lib/modules/modal/modal.component.html
  libs/components/modals/src/lib/modules/modal/modal.component.scss
  libs/components/modals/src/lib/modules/modal/modal.component.spec.ts
  libs/components/modals/src/lib/modules/modal/modal.component.ts
  libs/components/pages/src/lib/modules/page/page.component.ts
  tsconfig.base.json
Labels: risk level (author): 1, screenshot removed

#3198 chore: release 11.44.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease 11.x.x: pending

#3201 chore: changelog for 11.44.0 (#3198) 🍒
  CHANGELOG.md
Labels: risk level (author): 1, risk level (reviewer): 1

#3192 chore: release 12.0.0-alpha.7
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#3205 docs(components/toast): clarify use of `SkyToasterHarness`
  libs/components/toast/testing/src/modules/toast/toaster-harness.ts
Labels: risk level (author): 1

#3206 docs(components/toast): clarify use of `SkyToasterHarness` (#3205)
  libs/components/toast/testing/src/modules/toast/toaster-harness.ts
Labels: risk level (author): 1

#3208 ci: resolve JSON module when running TypeDoc
  libs/components/manifest/src/generator/get-entry-points-reflections.ts
Labels: risk level (author): 1

#3207 fix(components/datetime): show key date popover
  apps/playground/src/app/app.component.html
  apps/playground/src/app/app.component.scss
  apps/playground/src/app/app.component.ts
  apps/playground/src/app/components/datetime/datetime.module.ts
  apps/playground/src/app/components/datetime/key-dates/key-dates.component.html
  apps/playground/src/app/components/datetime/key-dates/key-dates.component.ts
  libs/components/core/src/lib/modules/affix/affixer.spec.ts
  libs/components/core/src/lib/modules/affix/dom-utils.ts
Labels: risk level (author): 1

#3210 fix(components/datetime): show key date popover (#3207)
  apps/playground/src/app/app.component.html
  apps/playground/src/app/app.component.scss
  apps/playground/src/app/app.component.ts
  apps/playground/src/app/components/datetime/datetime.module.ts
  apps/playground/src/app/components/datetime/key-dates/key-dates.component.html
  apps/playground/src/app/components/datetime/key-dates/key-dates.component.ts
  libs/components/core/src/lib/modules/affix/affixer.spec.ts
  libs/components/core/src/lib/modules/affix/dom-utils.ts
Labels: risk level (author): 1

#3211 feat(components/docs-tools): add global stylesheet; demos in code examples application
  apps/code-examples/project.json
  apps/code-examples/src/app/app-routing.module.ts
  apps/code-examples/src/app/app.component.ts
  apps/code-examples/src/app/app.module.ts
  apps/code-examples/src/app/v2/v2.component.html
  apps/code-examples/src/app/v2/v2.component.ts
  apps/code-examples/src/assets/stack-blitz/.gitignore
  apps/code-examples/src/assets/stack-blitz/package-lock.json
  apps/code-examples/src/assets/stack-blitz/package.json
  apps/code-examples/src/styles.scss
  apps/code-examples/tsconfig.app.json
  libs/components/docs-tools/css/styles.css
  libs/components/docs-tools/ng-package.json
  libs/components/docs-tools/package.json
  libs/components/docs-tools/src/lib/modules/code-snippet/code-snippet-wrapper.component.ts
  libs/components/docs-tools/src/lib/modules/code-snippet/code-snippet.component.scss
  libs/components/docs-tools/src/lib/modules/code-snippet/code-snippet.component.ts
  libs/components/docs-tools/src/lib/modules/heading-anchor/heading-anchor.component.html
  libs/components/docs-tools/src/lib/modules/heading-anchor/heading-anchor.component.scss
  libs/components/docs-tools/src/lib/modules/type-definition/box.component.ts
  libs/components/docs-tools/src/lib/modules/type-definition/type-definition.component.scss
  libs/components/manifest/project.json
  nx.json
  tsconfig.base.json
Labels: risk level (author): 1

#3203 chore: release 12.0.0-alpha.8
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#3214 fix(components/code-examples): provide example service to prevent timeouts
  apps/code-examples/src/app/code-examples/lookup/selection-modal/add-item/demo.component.spec.ts
  apps/code-examples/src/app/code-examples/lookup/selection-modal/basic/demo.component.spec.ts
  libs/components/code-examples/src/lib/modules/lookup/selection-modal/add-item/example.component.spec.ts
  libs/components/code-examples/src/lib/modules/lookup/selection-modal/add-item/example.component.ts
  libs/components/code-examples/src/lib/modules/lookup/selection-modal/add-item/example.service.ts
  libs/components/code-examples/src/lib/modules/lookup/selection-modal/basic/example.component.spec.ts
  libs/components/code-examples/src/lib/modules/lookup/selection-modal/basic/example.component.ts
  libs/components/code-examples/src/lib/modules/lookup/selection-modal/basic/example.service.ts
Labels: risk level (author): 1

#3216 ci: fix `skyux-eslint` test mock for @skyux/manifest
  libs/sdk/skyux-eslint/project.json
  libs/sdk/skyux-eslint/src/rules/template/no-deprecated-directives.spec.ts
Labels: risk level (author): 1

#3215 fix(components/packages): fix test timeouts related to SSR
  libs/components/packages/src/schematics/rules/workspace-check/workspace-check.spec.ts
Labels: risk level (author): 1

#3217 feat(components/docs-tools): add `ExampleHelpService` to code examples
  apps/code-examples/project.json
  apps/code-examples/src/app/app.module.ts
  apps/code-examples/src/app/help.service.ts
  apps/code-examples/src/app/v2/v2.component.ts
  apps/code-examples/src/assets/stack-blitz/package-lock.json
  apps/code-examples/src/assets/stack-blitz/package.json
  libs/components/docs-tools/src/lib/modules/code-example-viewer/stackblitz.service.spec.ts
  libs/components/docs-tools/src/lib/modules/code-example-viewer/stackblitz.service.ts
  tsconfig.base.json
Labels: risk level (author): 1

#3223 fix: adjust `ng2-dragula` override ranges
  libs/components/grids/package.json
  libs/components/lists/package.json
  libs/components/tiles/package.json
  package.json
Labels: risk level (author): 1

#3209 chore: release 11.45.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease 11.x.x: pending

#3225 chore: changelog for 11.45.0 (#3209) 🍒
  CHANGELOG.md
Labels: risk level (author): 1, risk level (reviewer): 1

#3224 fix(components/ag-grid): validator cell not updating status (#3222)
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-validator/ag-grid-cell-validator-tooltip.component.html
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-validator/ag-grid-cell-validator-tooltip.component.spec.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-validator/ag-grid-cell-validator-tooltip.component.ts
  libs/components/ag-grid/src/lib/styles/_base.scss
Labels: risk level (author): 1

#3213 chore: release 12.0.0-alpha.9
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#3220 fix(components/code-examples): remove extra font class from repeater titles in code examples
  apps/code-examples/src/app/code-examples/lists/repeater/add-remove/demo.component.html
  apps/code-examples/src/app/code-examples/lists/repeater/basic/demo.component.html
  apps/code-examples/src/app/code-examples/pages/page/home-page-blocks-layout-demo/tile-my-actions.component.html
  libs/components/code-examples/src/lib/modules/lists/repeater/add-remove/example.component.html
  libs/components/code-examples/src/lib/modules/lists/repeater/basic/example.component.html
  libs/components/code-examples/src/lib/modules/pages/page/home-page-blocks-layout-demo/tile-my-actions.component.html
Labels: risk level (author): 1

#3230 feat(components/packages): remove eslint comments for prefer-standalone-component rule
  libs/components/packages/src/schematics/migrations/migration-collection.json
  libs/components/packages/src/schematics/migrations/update-12/remove-angular-eslint-prefer-standalone-component/remove-angular-eslint-prefer-standalone-component.schematic.spec.ts
  libs/components/packages/src/schematics/migrations/update-12/remove-angular-eslint-prefer-standalone-component/remove-angular-eslint-prefer-standalone-component.schematic.ts
  libs/components/packages/src/schematics/rules/remove-eslint-disable-comment/remove-eslint-disable-comment.test.ts
  libs/components/packages/src/schematics/rules/remove-eslint-disable-comment/remove-eslint-disable-comment.ts
Labels: risk level (author): 1

#3229 chore: release 12.0.0-alpha.10
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#3231 refactor: enable '@typescript-eslint/consistent-indexed-object-style' ESLint rule
  apps/e2e/layout-storybook/src/app/page/page.component.ts
  eslint-overrides-angular.config.js
  libs/components/data-manager/src/lib/modules/data-manager/models/data-view-column-widths.ts
  libs/components/docs-tools/src/lib/modules/type-definition/type-anchor-ids.service.ts
  libs/components/theme/src/lib/viewport/viewport.service.ts
Labels: risk level (author): 1

#3233 feat(components/icon): pull in updated icon manifest
  libs/components/packages/package.json
  libs/components/theme/package.json
  libs/components/theme/src/lib/styles/sky.scss
  package-lock.json
  package.json
Labels: risk level (author): 1

#3234 chore: release 12.0.0-alpha.11
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#3195 fix(components/theme): viewport service should work with overlay elements
  apps/playground/src/app/components/theme/theme.module.ts
  apps/playground/src/app/components/theme/viewport-service/viewport-service.component.css
  apps/playground/src/app/components/theme/viewport-service/viewport-service.component.html
  apps/playground/src/app/components/theme/viewport-service/viewport-service.component.ts
  libs/components/core/src/lib/modules/resize-observer/resize-observer.service.ts
  libs/components/theme/src/lib/viewport/viewport.service.spec.ts
  libs/components/theme/src/lib/viewport/viewport.service.ts
Labels: risk level (author): 1

#3236 chore: release 11.45.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease 11.x.x: pending

#3238 chore: changelog for 11.45.1 (#3236) 🍒
  CHANGELOG.md
Labels: risk level (author): 1, risk level (reviewer): 1

#3243 feat(components/icon): remove inline styles from SVG sprite
  libs/components/packages/package.json
  libs/components/theme/package.json
  libs/components/theme/src/lib/styles/sky.scss
  package-lock.json
  package.json
Labels: risk level (author): 1

#3241 feat(components/tabs): add vertical tabs harness
  apps/code-examples/src/app/code-examples/tabs/vertical-tabs/basic/demo.component.html
  apps/code-examples/src/app/code-examples/tabs/vertical-tabs/basic/demo.component.spec.ts
  apps/code-examples/src/app/code-examples/tabs/vertical-tabs/grouped/demo.component.html
  apps/code-examples/src/app/code-examples/tabs/vertical-tabs/grouped/demo.component.spec.ts
  libs/components/tabs/src/lib/modules/vertical-tabset/vertical-tabset-group.component.ts
  libs/components/tabs/testing/src/modules/tabs/tab-button-harness.ts
  libs/components/tabs/testing/src/modules/tabs/tab-content-harness-filters.ts
  libs/components/tabs/testing/src/modules/vertical-tabset/vertical-tab-button-harness-filters.ts
  libs/components/tabs/testing/src/modules/vertical-tabset/vertical-tab-button-harness.ts
  libs/components/tabs/testing/src/modules/vertical-tabset/vertical-tab-content-harness-filters.ts
  libs/components/tabs/testing/src/modules/vertical-tabset/vertical-tab-content-harness.ts
  libs/components/tabs/testing/src/modules/vertical-tabset/vertical-tabset-group-harness-filters.ts
  libs/components/tabs/testing/src/modules/vertical-tabset/vertical-tabset-group-harness.ts
  libs/components/tabs/testing/src/modules/vertical-tabset/vertical-tabset-harness-filters.ts
  libs/components/tabs/testing/src/modules/vertical-tabset/vertical-tabset-harness.spec.ts
  libs/components/tabs/testing/src/modules/vertical-tabset/vertical-tabset-harness.ts
  libs/components/tabs/testing/src/public-api.ts
Labels: risk level (author): 1

#3244 feat(components/tabs): add vertical tabs harness (#3241)
  apps/code-examples/src/app/code-examples/tabs/vertical-tabs/basic/demo.component.html
  apps/code-examples/src/app/code-examples/tabs/vertical-tabs/basic/demo.component.spec.ts
  apps/code-examples/src/app/code-examples/tabs/vertical-tabs/grouped/demo.component.html
  apps/code-examples/src/app/code-examples/tabs/vertical-tabs/grouped/demo.component.spec.ts
  libs/components/code-examples/src/lib/modules/tabs/vertical-tabs/basic/example.component.html
  libs/components/code-examples/src/lib/modules/tabs/vertical-tabs/basic/example.component.spec.ts
  libs/components/code-examples/src/lib/modules/tabs/vertical-tabs/grouped/example.component.html
  libs/components/code-examples/src/lib/modules/tabs/vertical-tabs/grouped/example.component.spec.ts
  libs/components/tabs/src/lib/modules/vertical-tabset/vertical-tabset-group.component.ts
  libs/components/tabs/testing/src/modules/tabs/tab-button-harness.ts
  libs/components/tabs/testing/src/modules/tabs/tab-content-harness-filters.ts
  libs/components/tabs/testing/src/modules/vertical-tabset/vertical-tab-button-harness-filters.ts
  libs/components/tabs/testing/src/modules/vertical-tabset/vertical-tab-button-harness.ts
  libs/components/tabs/testing/src/modules/vertical-tabset/vertical-tab-content-harness-filters.ts
  libs/components/tabs/testing/src/modules/vertical-tabset/vertical-tab-content-harness.ts
  libs/components/tabs/testing/src/modules/vertical-tabset/vertical-tabset-group-harness-filters.ts
  libs/components/tabs/testing/src/modules/vertical-tabset/vertical-tabset-group-harness.ts
  libs/components/tabs/testing/src/modules/vertical-tabset/vertical-tabset-harness-filters.ts
  libs/components/tabs/testing/src/modules/vertical-tabset/vertical-tabset-harness.spec.ts
  libs/components/tabs/testing/src/modules/vertical-tabset/vertical-tabset-harness.ts
  libs/components/tabs/testing/src/public-api.ts
Labels: risk level (author): 1

#3249 refactor(components/popovers): remove `skyDropdownTriggerBase` directive
  libs/components/popovers/src/lib/modules/dropdown/dropdown-trigger-base.directive.ts
  libs/components/popovers/src/lib/modules/dropdown/dropdown-trigger.directive.ts
  libs/components/popovers/src/lib/modules/dropdown/dropdown.component.html
  libs/components/popovers/src/lib/modules/dropdown/dropdown.component.ts
  libs/components/popovers/src/lib/modules/dropdown/dropdown.module.ts
Labels: risk level (author): 3

#3240 fix(components/docs-tools): various adjustments to showcase and code example viewer components
  apps/code-examples/src/app/app.component.scss
  apps/code-examples/src/app/app.module.ts
  apps/code-examples/src/app/code-examples/pages/page/home-page-blocks-layout-demo/home-page-content.component.ts
  apps/code-examples/src/app/v2/v2.component.html
  libs/components/code-examples/src/lib/modules/indicators/wait/element/example.component.html
  libs/components/code-examples/src/lib/modules/indicators/wait/element/example.component.ts
  libs/components/code-examples/src/lib/modules/layout/back-to-top/infinite-scroll/example.component.ts
  libs/components/code-examples/src/lib/modules/layout/back-to-top/repeater/example.component.ts
  libs/components/code-examples/src/lib/modules/layout/inline-delete/repeater/example.component.html
  libs/components/code-examples/src/lib/modules/layout/page/layout-fit/example.component.ts
  libs/components/code-examples/src/lib/modules/lists/infinite-scroll/repeater/example.component.html
  libs/components/code-examples/src/lib/modules/lists/infinite-scroll/repeater/example.component.ts
  libs/components/code-examples/src/lib/modules/lists/sort/basic/example.component.html
  libs/components/code-examples/src/lib/modules/lists/sort/basic/example.component.ts
  libs/components/code-examples/src/lib/modules/pages/action-hub/example.component.ts
  libs/components/code-examples/src/lib/modules/pages/page/home-page-blocks-layout-demo/example.component.ts
  libs/components/code-examples/src/lib/modules/pages/page/home-page-blocks-layout-demo/home-page-content.component.ts
  libs/components/code-examples/src/lib/modules/pages/page/list-page-list-layout-demo/example.component.ts
  libs/components/code-examples/src/lib/modules/pages/page/list-page-tabs-layout-demo/example.component.ts
  libs/components/code-examples/src/lib/modules/pages/page/record-page-blocks-layout-demo/example.component.ts
  libs/components/code-examples/src/lib/modules/pages/page/record-page-tabs-layout-demo/example.component.ts
  libs/components/code-examples/src/lib/modules/pages/page/split-view-page-fit-layout-demo/example.component.ts
  libs/components/core/documentation.json
  libs/components/core/src/index.ts
  libs/components/docs-tools/css/styles.css
  libs/components/docs-tools/src/lib/modules/category-tag/category-tag.component.scss
  libs/components/docs-tools/src/lib/modules/code-example-viewer/code-example-viewer.module.ts
  libs/components/docs-tools/src/lib/modules/code-example-viewer/help.service.ts
  libs/components/docs-tools/src/lib/modules/code-example-viewer/stackblitz.service.spec.ts
  libs/components/docs-tools/src/lib/modules/code-example-viewer/stackblitz.service.ts
  libs/components/docs-tools/src/lib/modules/heading-anchor/heading-anchor.component.html
  libs/components/docs-tools/src/lib/modules/heading-anchor/heading-anchor.component.scss
  libs/components/docs-tools/src/lib/modules/showcase/showcase-area-development.component.ts
  libs/components/docs-tools/src/lib/modules/showcase/showcase-area-examples.component.ts
  libs/components/docs-tools/src/lib/modules/showcase/showcase-area-overview.component.ts
  libs/components/docs-tools/src/lib/modules/showcase/showcase-area-testing.component.html
  libs/components/docs-tools/src/lib/modules/showcase/showcase-area-testing.component.ts
  libs/components/docs-tools/src/lib/modules/showcase/showcase-host.service.ts
  libs/components/docs-tools/src/lib/modules/showcase/showcase.component.html
  libs/components/docs-tools/src/lib/modules/showcase/showcase.component.ts
  libs/components/docs-tools/src/lib/modules/table-of-contents/table-of-contents-page.component.scss
Labels: risk level (author): 1

#3235 chore: release 12.0.0-alpha.12
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#3245 chore: release 11.46.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease 11.x.x: pending

#3247 feat(components/ag-grid): set background color for boxes and tiles
  libs/components/layout/src/lib/modules/box/box.component.scss
  libs/components/tiles/src/lib/modules/tiles/tile/tile.component.scss
Labels: risk level (author): 1

#3255 fix(components/docs-tools): add @skyux/packages/polyfills to StackBlitz launcher
  libs/components/docs-tools/src/lib/modules/code-example-viewer/stackblitz.service.spec.ts
  libs/components/docs-tools/src/lib/modules/code-example-viewer/stackblitz.service.ts
  libs/components/theme/src/lib/styles/_public-api/_compat/_variables.scss
  libs/components/theme/src/lib/styles/themes/modern/_buttons.scss
Labels: risk level (author): 1

#3256 feat(components/packages): add schematic to convert existing icons to new `iconName`
  libs/components/packages/src/schematics/migrations/migration-collection.json
  libs/components/packages/src/schematics/migrations/update-12/icon-name/icon-name-mappings.ts
  libs/components/packages/src/schematics/migrations/update-12/icon-name/icon-name.schematic.spec.ts
  libs/components/packages/src/schematics/migrations/update-12/icon-name/icon-name.schematic.ts
Labels: risk level (author): 3

#3252 chore: changelog for 11.46.0 (#3245) 🍒
  CHANGELOG.md
Labels: risk level (author): 1, risk level (reviewer): 1

#3254 chore: release 12.0.0-alpha.13
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#3259 fix(components/theme): viewport space check
  libs/components/theme/src/lib/viewport/viewport.service.spec.ts
  libs/components/theme/src/lib/viewport/viewport.service.ts
Labels: risk level (author): 1

#3261 chore: release 11.46.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease 11.x.x: pending

#3263 chore: changelog for 11.46.1 (#3261) 🍒
  CHANGELOG.md
Labels: risk level (author): 1, risk level (reviewer): 1

#3248 feat(components/theme): add ability to specify a brand through `SkyThemeService`
  apps/code-examples/src/app/shared/theme-selector/theme-selector.component.ts
  apps/integration/project.json
  apps/integration/src/app/app.module.ts
  apps/integration/src/app/shared/theme-selector/theme-selector-mode-value.ts
  apps/integration/src/app/shared/theme-selector/theme-selector-value.ts
  apps/integration/src/app/shared/theme-selector/theme-selector.component.html
  apps/integration/src/app/shared/theme-selector/theme-selector.component.ts
  apps/integration/src/app/shared/theme-selector/theme-selector.module.ts
  apps/playground/src/app/shared/theme-selector/theme-selector.component.ts
  libs/components/storybook/src/lib/preview-wrapper/preview-wrapper.component.spec.ts
  libs/components/storybook/src/lib/preview-wrapper/preview-wrapper.component.ts
  libs/components/theme/src/index.ts
  libs/components/theme/src/lib/styles/themes/modern/_compat-tokens-mixins.scss
  libs/components/theme/src/lib/theming/theme-brand.spec.ts
  libs/components/theme/src/lib/theming/theme-brand.ts
  libs/components/theme/src/lib/theming/theme-settings.ts
  libs/components/theme/src/lib/theming/theme.service.spec.ts
  libs/components/theme/src/lib/theming/theme.service.ts
  libs/sdk/cypress-commands/src/lib/choose-theme-command.ts
Labels: risk level (author): 3

#3262 chore: release 12.0.0-alpha.14
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#3268 feat(components/lists): add infinite scroll test harness
  apps/code-examples/src/app/code-examples/lists/infinite-scroll/repeater/demo.component.spec.ts
  apps/code-examples/src/app/code-examples/lists/infinite-scroll/repeater/demo.component.ts
  libs/components/lists/testing/src/modules/infinite-scroll/infinite-scroll-harness-filters.ts
  libs/components/lists/testing/src/modules/infinite-scroll/infinite-scroll-harness.ts
Labels: risk level (author): 1

#3266 docs(components/popovers): update dropdown harness docs comments
  libs/components/popovers/testing/src/modules/dropdown/dropdown-harness.ts
  libs/components/popovers/testing/src/modules/dropdown/dropdown-item-harness.ts
  libs/components/popovers/testing/src/modules/dropdown/dropdown-menu-harness.ts
Labels: risk level (author): 1

#3267 fix(components/forms): file attachment code examples fix double download
  apps/code-examples/src/app/code-examples/forms/file-attachment/basic/demo.component.html
  apps/code-examples/src/app/code-examples/forms/file-attachment/basic/demo.component.ts
  apps/code-examples/src/app/code-examples/forms/file-attachment/help-key/demo.component.html
  apps/code-examples/src/app/code-examples/forms/file-attachment/help-key/demo.component.ts
  apps/playground/src/app/components/forms/single-file-attachment/single-file-attachment.component.html
  apps/playground/src/app/components/forms/single-file-attachment/single-file-attachment.component.ts
Labels: risk level (author): 1

#3271 fix(components/forms): file attachment code examples fix double download (#3267)
  apps/playground/src/app/components/forms/single-file-attachment/single-file-attachment.component.html
  apps/playground/src/app/components/forms/single-file-attachment/single-file-attachment.component.ts
  libs/components/code-examples/src/lib/modules/forms/file-attachment/basic/example.component.html
  libs/components/code-examples/src/lib/modules/forms/file-attachment/basic/example.component.ts
  libs/components/code-examples/src/lib/modules/forms/file-attachment/help-key/example.component.html
  libs/components/code-examples/src/lib/modules/forms/file-attachment/help-key/example.component.ts
Labels: risk level (author): 1

#3272 feat(components/lists): add infinite scroll test harness (#3268)
  libs/components/code-examples/src/lib/modules/lists/infinite-scroll/repeater/example.component.spec.ts
  libs/components/code-examples/src/lib/modules/lists/infinite-scroll/repeater/example.component.ts
  libs/components/lists/testing/src/modules/infinite-scroll/infinite-scroll-harness-filters.ts
  libs/components/lists/testing/src/modules/infinite-scroll/infinite-scroll-harness.ts
Labels: risk level (author): 1

#3275 build: fix update-dependencies on Windows (#3274)
  libs/sdk/tools/src/generators/update-dependencies/generator.ts
Labels: risk level (author): 1

#3265 feat(components/lists): add sort harnesses
  apps/code-examples/src/app/code-examples/lists/sort/basic/demo.component.spec.ts
  libs/components/lists/project.json
  libs/components/lists/testing/src/modules/sort/fixtures/sort-harness-test.component.html
  libs/components/lists/testing/src/modules/sort/fixtures/sort-harness-test.component.ts
  libs/components/lists/testing/src/modules/sort/sort-harness-filters.ts
  libs/components/lists/testing/src/modules/sort/sort-harness.spec.ts
  libs/components/lists/testing/src/modules/sort/sort-harness.ts
  libs/components/lists/testing/src/modules/sort/sort-item-harness-filters.ts
  libs/components/lists/testing/src/modules/sort/sort-item-harness.ts
  libs/components/lists/testing/src/public-api.ts
Labels: risk level (author): 1

#3276 fix(components/docs-tools): adjust heading anchors to fit within viewport
  libs/components/docs-tools/src/lib/modules/heading-anchor/heading-anchor.component.html
  libs/components/docs-tools/src/lib/modules/heading-anchor/heading-anchor.component.scss
  libs/components/docs-tools/src/lib/modules/heading-anchor/heading-anchor.component.ts
Labels: risk level (author): 1

#3278 feat(components/lists): add sort harnesses (#3265)
  libs/components/code-examples/src/lib/modules/lists/sort/basic/example.component.spec.ts
  libs/components/lists/project.json
  libs/components/lists/testing/src/modules/sort/fixtures/sort-harness-test.component.html
  libs/components/lists/testing/src/modules/sort/fixtures/sort-harness-test.component.ts
  libs/components/lists/testing/src/modules/sort/sort-harness-filters.ts
  libs/components/lists/testing/src/modules/sort/sort-harness.spec.ts
  libs/components/lists/testing/src/modules/sort/sort-harness.ts
  libs/components/lists/testing/src/modules/sort/sort-item-harness-filters.ts
  libs/components/lists/testing/src/modules/sort/sort-item-harness.ts
  libs/components/lists/testing/src/public-api.ts
Labels: risk level (author): 1

#3279 feat(components/ag-grid): add schematics for changes in AG Grid 33
  libs/components/ag-grid/src/lib/modules/ag-grid/ag-grid.service.spec.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/ag-grid.service.ts
  libs/components/packages/src/schematics/migrations/update-12/ag-grid/ag-grid.schematic.spec.ts
  libs/components/packages/src/schematics/migrations/update-12/ag-grid/ag-grid.schematic.ts
Labels: risk level (author): 1

#3250 feat(components/pages): links filtered with `SkyHrefResolverService`
  libs/components/pages/src/lib/modules/action-hub/action-hub.component.spec.ts
  libs/components/pages/src/lib/modules/action-hub/fixtures/action-hub-async-fixture.component.ts
  libs/components/pages/src/lib/modules/action-hub/fixtures/action-hub-content-fixture.component.ts
  libs/components/pages/src/lib/modules/action-hub/fixtures/action-hub-fixture.module.ts
  libs/components/pages/src/lib/modules/action-hub/fixtures/action-hub-inputs-fixture.component.ts
  libs/components/pages/src/lib/modules/action-hub/fixtures/action-hub-recent-svc-fixture.component.ts
  libs/components/pages/src/lib/modules/action-hub/fixtures/action-hub-sync-fixture.component.ts
  libs/components/pages/src/lib/modules/link-as/link-as.pipe.ts
  libs/components/pages/src/lib/modules/link-list/link-list-item.component.ts
  libs/components/pages/src/lib/modules/needs-attention/needs-attention.component.html
  libs/components/pages/src/lib/modules/needs-attention/needs-attention.component.spec.ts
  libs/components/pages/src/lib/modules/needs-attention/needs-attention.component.ts
  libs/components/pages/src/lib/modules/needs-attention/needs-attention.module.ts
  libs/components/pages/src/lib/modules/page/page-links.component.ts
  libs/components/pages/testing/src/modules/needs-attention/needs-attention-harness.spec.ts
  libs/components/router/testing/src/modules/href/href-testing.module.ts
  libs/components/router/testing/src/modules/href/provide-href-testing.ts
  libs/components/router/testing/src/public-api.ts
Labels: risk level (author): 1

#3280 feat(sdk/prettier-schematics): add support for ESLint flat config
  libs/sdk/prettier-schematics/src/schematics/ng-add/ng-add.schematic.spec.ts
  libs/sdk/prettier-schematics/src/schematics/ng-add/rules/configure-eslint.ts
Labels: risk level (author): 1

#3269 chore: release 11.47.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease 11.x.x: pending

#3283 chore: changelog for 11.47.0 (#3269) 🍒
  CHANGELOG.md
Labels: risk level (author): 1, risk level (reviewer): 1

#3273 chore: release 12.0.0-alpha.15
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#3282 fix(components/core)!: update querySelector method signature
  libs/components/code-examples/src/lib/modules/layout/toolbar/basic/example.component.spec.ts
  libs/components/code-examples/src/lib/modules/layout/toolbar/sectioned/example.component.spec.ts
  libs/components/core/testing/src/shared/queryable-component-harness.ts
  libs/components/datetime/testing/src/modules/date-range-picker/date-range-picker-harness.ts
  libs/components/lookup/testing/src/modules/autocomplete/autocomplete-harness.ts
  libs/components/lookup/testing/src/modules/country-field/country-field-harness.ts
Labels: risk level (author): 2

#3277 feat(components/indicators): add text highlight harness
  apps/code-examples/src/app/code-examples/indicators/text-highlight/basic/demo.component.spec.ts
  libs/components/indicators/src/lib/modules/text-highlight/text-highlight.directive.ts
  libs/components/indicators/testing/src/modules/text-highlight/fixtures/text-highlight-harness-test.component.html
  libs/components/indicators/testing/src/modules/text-highlight/fixtures/text-highlight-harness-test.component.ts
  libs/components/indicators/testing/src/modules/text-highlight/text-highlight-harness-filters.ts
  libs/components/indicators/testing/src/modules/text-highlight/text-highlight-harness.spec.ts
  libs/components/indicators/testing/src/modules/text-highlight/text-highlight-harness.ts
  libs/components/indicators/testing/src/public-api.ts
Labels: risk level (author): 1

#3286 fix(components/theme): baseline align inline link buttons
  libs/components/theme/src/lib/styles/_buttons.scss
  libs/components/theme/src/lib/styles/themes/modern/_buttons.scss
Labels: risk level (author): 3

#3288 feat(components/indicators): add text highlight harness (#3277)
  libs/components/code-examples/src/lib/modules/indicators/text-highlight/basic/example.component.spec.ts
  libs/components/indicators/src/lib/modules/text-highlight/text-highlight.directive.ts
  libs/components/indicators/testing/src/modules/text-highlight/fixtures/text-highlight-harness-test.component.html
  libs/components/indicators/testing/src/modules/text-highlight/fixtures/text-highlight-harness-test.component.ts
  libs/components/indicators/testing/src/modules/text-highlight/text-highlight-harness-filters.ts
  libs/components/indicators/testing/src/modules/text-highlight/text-highlight-harness.spec.ts
  libs/components/indicators/testing/src/modules/text-highlight/text-highlight-harness.ts
  libs/components/indicators/testing/src/public-api.ts
Labels: risk level (author): 1

#3290 fix(components/ag-grid): use correct spacing in ag-grid header buttons
  libs/components/ag-grid/src/lib/modules/ag-grid/header/header.component.scss
Labels: risk level (author): 1

#3292 feat(components/help-inline): use solid icon for help inline
  libs/components/help-inline/src/lib/modules/help-inline/help-inline.component.html
  libs/components/packages/package.json
  libs/components/theme/package.json
  libs/components/theme/src/lib/styles/sky.scss
  package-lock.json
  package.json
Labels: risk level (author): 1

#3296 ci: release 12 beta
  .github/workflows/release-please.yml
Labels: risk level (author): 1

#3295 refactor(components/manifest): replace decorator plugin with app converter
  libs/components/manifest/src/generator/__snapshots__/generate-manifest.test.ts.snap
  libs/components/manifest/src/generator/apply-decorator-metadata.ts
  libs/components/manifest/src/generator/get-entry-points-reflections.ts
  libs/components/manifest/src/generator/get-project-definitions.test.ts
  libs/components/manifest/src/generator/get-project-definitions.ts
  libs/components/manifest/src/generator/plugins/typedoc-plugin-decorators.mjs
  libs/components/manifest/src/generator/testing/fixtures/example-packages/foo/src/lib/foo.component.ts
  libs/components/manifest/src/generator/types/declaration-reflection-with-decorators.ts
Labels: risk level (author): 2

#3293 feat(components/config): add theme brand properties to config theming object
  libs/components/config/src/index.ts
  libs/components/config/src/lib/config.ts
Labels: risk level (author): 1

#3294 refactor: address warnings from TypeDoc regarding JSDoc comments
  libs/components/colorpicker/testing/src/modules/colorpicker/colorpicker-harness.ts
  libs/components/config/src/lib/params.ts
  libs/components/core/src/lib/modules/shared/number-format/number-format-utility.ts
  libs/components/datetime/src/lib/modules/date-range-picker/types/date-range-relative-value.ts
  libs/components/datetime/testing/src/modules/date-range-picker/date-range-picker-harness.ts
  libs/components/i18n/src/lib/utils/format.ts
  libs/components/indicators/src/lib/modules/text-highlight/text-highlight.directive.ts
  libs/components/indicators/src/lib/modules/wait/wait-adapter.service.ts
  libs/components/modals/src/lib/modules/modal/modal-host.service.ts
  libs/components/phone-field/src/lib/modules/phone-field/phone-field.component.ts
  libs/components/popovers/src/lib/modules/popover/popover-context.ts
  libs/components/validation/src/lib/modules/validators/validators.ts
  libs/sdk/skyux-eslint/dev-transpiler.cjs
Labels: risk level (author): 1

#3281 feat(components/phone-field)!: close country field when focus leaves phone field
  apps/e2e/phone-field-storybook-e2e/src/e2e/phone-field.component.cy.ts
  apps/e2e/phone-field-storybook/src/app/phone-field/phone-field.component.html
  libs/components/forms/src/lib/modules/input-box/fixtures/input-box-host-service.component.fixture.ts
  libs/components/forms/src/lib/modules/input-box/fixtures/input-box.component.fixture.html
  libs/components/forms/src/lib/modules/input-box/input-box-adapter.service.ts
  libs/components/forms/src/lib/modules/input-box/input-box-host.service.spec.ts
  libs/components/forms/src/lib/modules/input-box/input-box-host.service.ts
  libs/components/forms/src/lib/modules/input-box/input-box.component.spec.ts
  libs/components/forms/src/lib/modules/input-box/input-box.component.ts
  libs/components/lookup/src/lib/modules/country-field/country-field.component.html
  libs/components/lookup/src/lib/modules/country-field/country-field.component.spec.ts
  libs/components/lookup/src/lib/modules/country-field/country-field.component.ts
  libs/components/lookup/src/lib/modules/country-field/fixtures/country-field.component.fixture.html
  libs/components/lookup/src/lib/modules/country-field/fixtures/country-field.component.fixture.ts
  libs/components/phone-field/src/lib/modules/phone-field/fixtures/phone-field-input-box.component.fixture.html
  libs/components/phone-field/src/lib/modules/phone-field/phone-field.component.html
  libs/components/phone-field/src/lib/modules/phone-field/phone-field.component.spec.ts
  libs/components/phone-field/src/lib/modules/phone-field/phone-field.component.ts
Labels: risk level (author): 3, breaking

#3285 chore: release 12.0.0-beta.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#3287 chore: release 11.48.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease 11.x.x: pending

#3297 chore: changelog for 11.48.0 (#3287) 🍒
  CHANGELOG.md
Labels: risk level (author): 1, risk level (reviewer): 1

#3298 feat(components/ag-grid): add `valueResourceObservable` parameter for validator tooltip cell type
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-renderers/cell-renderer-validator-tooltip/cell-renderer-validator-tooltip.component.html
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-renderers/cell-renderer-validator-tooltip/cell-renderer-validator-tooltip.component.spec.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-renderers/cell-renderer-validator-tooltip/cell-renderer-validator-tooltip.component.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-renderers/cell-renderer-validator-tooltip/cell-renderer-validator-tooltip.module.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-validator/ag-grid-cell-validator-tooltip.component.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/types/cell-type.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/types/validator-properties.ts
Labels: risk level (author): 1

#3301 feat(components/theme): theme service validates if branding is available for the current theme when applying brands
  libs/components/theme/src/lib/theming/theme.service.spec.ts
  libs/components/theme/src/lib/theming/theme.service.ts
  libs/components/theme/src/lib/theming/theme.ts
Labels: risk level (author): 2

#3303 chore: release 12.0.0-beta.2
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#3304 feat(components/ag-grid): add `valueResourceObservable` parameter for validator tooltip cell type (#3298)
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-renderers/cell-renderer-validator-tooltip/cell-renderer-validator-tooltip.component.html
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-renderers/cell-renderer-validator-tooltip/cell-renderer-validator-tooltip.component.spec.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-renderers/cell-renderer-validator-tooltip/cell-renderer-validator-tooltip.component.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-validator/ag-grid-cell-validator-tooltip.component.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/types/cell-type.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/types/validator-properties.ts
Labels: risk level (author): 1

#3308 fix(components/layout): use smaller action button icon at xs breakpoint
  libs/components/layout/src/lib/modules/action-button/action-button-icon.component.html
  libs/components/layout/src/lib/modules/action-button/action-button-icon.component.ts
  libs/components/layout/src/lib/modules/action-button/action-button.component.spec.ts
  libs/components/packages/package.json
  libs/components/theme/package.json
  libs/components/theme/src/lib/styles/sky.scss
  package-lock.json
  package.json
Labels: risk level (author): 1

#3306 fix(components/lookup): add hover state for selection modal when using single select mode
  libs/components/lookup/src/lib/modules/selection-modal/selection-modal.component.html
  libs/components/lookup/src/lib/modules/selection-modal/selection-modal.component.scss
Labels: risk level (author): 1

#3311 fix(components/lookup): use correct spacing in search icons
  libs/components/lookup/src/lib/modules/search/search.component.scss
Labels: risk level (author): 1

#3310 feat(components/lookup): add `allowAnyValue` and `highlightSearchText` to autocomplete
  apps/playground/src/app/components/lookup/autocomplete/autocomplete.component.html
  libs/components/lookup/src/lib/modules/autocomplete/autocomplete.component.html
  libs/components/lookup/src/lib/modules/autocomplete/autocomplete.component.spec.ts
  libs/components/lookup/src/lib/modules/autocomplete/autocomplete.component.ts
  libs/components/lookup/src/lib/modules/autocomplete/fixtures/autocomplete.component.fixture.html
  libs/components/lookup/src/lib/modules/autocomplete/fixtures/autocomplete.component.fixture.ts
Labels: risk level (author): 3

#3313 feat(components/ag-grid): update to AG Grid 33.2.1
  apps/e2e/ag-grid-storybook/src/app/ag-grid-widgets/ag-grid-widgets.component.ts
  apps/e2e/ag-grid-storybook/src/app/ag-grid/ag-grid-stories.component.ts
  apps/e2e/ag-grid-storybook/src/app/data-entry-grid/data-entry-grid.component.ts
  apps/e2e/ag-grid-storybook/src/app/data-manager/data-manager.component.ts
  libs/components/ag-grid/package.json
  libs/components/code-examples/package.json
  libs/components/packages/package.json
  libs/components/packages/src/schematics/ag-grid-migrate/ag-grid-migrate.schematic.spec.ts
  libs/components/packages/src/schematics/ag-grid-migrate/ag-grid-migrate.schematic.ts
  libs/components/packages/src/schematics/migrations/update-12/ag-grid/ag-grid.schematic.spec.ts
  libs/components/packages/src/schematics/migrations/update-12/ag-grid/ag-grid.schematic.ts
  package-lock.json
  package.json
Labels: risk level (author): 1

#3314 chore: changelog for 11.49.0 (#3302) 🍒
  CHANGELOG.md
Labels: risk level (author): 1, risk level (reviewer): 1

#3307 chore: release 12.0.0-beta.3
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#3309 feat(components/theme): include modern v2 design tokens in generated styles
  apps/code-examples/project.json
  apps/e2e/action-bars-storybook/project.json
  apps/e2e/avatar-storybook/project.json
  apps/e2e/colorpicker-storybook/project.json
  apps/e2e/datetime-storybook/project.json
  apps/e2e/errors-storybook/project.json
  apps/e2e/flyout-storybook/project.json
  apps/e2e/forms-storybook/project.json
  apps/e2e/help-inline-storybook/project.json
  apps/e2e/indicators-storybook/project.json
  apps/e2e/inline-form-storybook/project.json
  apps/e2e/layout-storybook/project.json
  apps/e2e/lists-storybook/project.json
  apps/e2e/lookup-storybook/project.json
  apps/e2e/pages-storybook/project.json
  apps/e2e/phone-field-storybook/project.json
  apps/e2e/popovers-storybook/project.json
  apps/e2e/split-view-storybook/project.json
  apps/e2e/tabs-storybook/project.json
  apps/e2e/text-editor-storybook/project.json
  apps/e2e/theme-storybook/project.json
  apps/e2e/toast-storybook/project.json
  apps/integration/project.json
  apps/playground/project.json
  libs/components/storybook/project.json
  libs/components/theme/package.json
  libs/components/theme/src/lib/styles/themes/modern/styles.scss
  package-lock.json
  package.json
Labels: risk level (author): 2
