Repository blackbaud/skyux, pull requests merged in 2025-05, with the labels that each got.

#3416 chore: release 12.10.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#3427 feat: update `@skyux/icons` to 7.23.1
  libs/components/packages/package.json
  libs/components/theme/package.json
  libs/components/theme/src/lib/styles/sky.scss
  package-lock.json
  package.json
Labels: risk level (author): 1

#3421 feat(components/forms): add selection box harnesses
  libs/components/code-examples/src/lib/modules/forms/selection-box/checkbox/example.component.spec.ts
  libs/components/code-examples/src/lib/modules/forms/selection-box/radio/example.component.spec.ts
  libs/components/forms/documentation.json
  libs/components/forms/project.json
  libs/components/forms/src/lib/modules/selection-box/selection-box-adapter.service.spec.ts
  libs/components/forms/testing/src/modules/selection-box/fixtures/selection-box-harness-test.component.html
  libs/components/forms/testing/src/modules/selection-box/fixtures/selection-box-harness-test.component.ts
  libs/components/forms/testing/src/modules/selection-box/selection-box-description-harness.ts
  libs/components/forms/testing/src/modules/selection-box/selection-box-grid-harness-filters.ts
  libs/components/forms/testing/src/modules/selection-box/selection-box-grid-harness.ts
  libs/components/forms/testing/src/modules/selection-box/selection-box-harness-filters.ts
  libs/components/forms/testing/src/modules/selection-box/selection-box-harness.spec.ts
  libs/components/forms/testing/src/modules/selection-box/selection-box-harness.ts
  libs/components/forms/testing/src/modules/selection-box/selection-box-header-harness.ts
  libs/components/forms/testing/src/public-api.ts
Labels: risk level (author): 1

#3428 build: node 22 support
  package-lock.json
  package.json
Labels: risk level (author): 1

#3430 fix(components/theme): correct block button line height in modern theme
  libs/components/theme/src/lib/styles/themes/modern/_buttons.scss
Labels: risk level (author): 1

#3431 fix(components/ag-grid): cell focus handling should not affect row dragging
  libs/components/ag-grid/src/lib/modules/ag-grid/ag-grid-adapter.service.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/ag-grid.service.spec.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/ag-grid.service.ts
Labels: risk level (author): 1

#3426 feat(sdk/skyux-eslint): create `strict-type-checked` ruleset
  libs/components/code-examples/eslint.config.js
  libs/components/code-examples/src/lib/modules/datetime/date-range-picker/basic/example.component.ts
  libs/components/code-examples/src/lib/modules/errors/error/embedded/example.component.html
  libs/components/code-examples/src/lib/modules/forms/file-drop/basic/example.component.spec.ts
  libs/components/code-examples/src/lib/modules/forms/radio/icon/example.component.html
  libs/components/code-examples/src/lib/modules/forms/radio/icon/example.component.ts
  libs/components/code-examples/src/lib/modules/inline-form/inline-form/basic/example.component.spec.ts
  libs/components/code-examples/src/lib/modules/inline-form/inline-form/custom-buttons/example.component.spec.ts
  libs/components/code-examples/src/lib/modules/layout/description-list/help-key/example.component.spec.ts
  libs/components/code-examples/src/lib/modules/layout/description-list/horizontal/example.component.spec.ts
  libs/components/code-examples/src/lib/modules/layout/description-list/inline-help/example.component.spec.ts
  libs/components/code-examples/src/lib/modules/layout/description-list/long-description/example.component.spec.ts
  libs/components/code-examples/src/lib/modules/layout/description-list/vertical/example.component.spec.ts
  libs/components/code-examples/src/lib/modules/lookup/autocomplete/any-value/example.component.spec.ts
  libs/components/code-examples/src/lib/modules/lookup/lookup/multi-select/example.component.ts
  libs/components/code-examples/src/lib/modules/lookup/lookup/single-select/example.component.ts
  libs/components/code-examples/tsconfig.lib.json
  libs/sdk/eslint-schematics/package.json
  libs/sdk/eslint-schematics/src/schematics/ng-add/ng-add.schematic.spec.ts
  libs/sdk/eslint-schematics/src/schematics/ng-add/ng-add.schematic.ts
  libs/sdk/eslint-schematics/src/schematics/ng-add/schema.json
  libs/sdk/eslint-schematics/src/schematics/ng-add/schema.ts
  libs/sdk/eslint-schematics/src/schematics/utility/json-file.ts
  libs/sdk/skyux-eslint/src/configs/README.md
  libs/sdk/skyux-eslint/src/configs/template-recommended.ts
  libs/sdk/skyux-eslint/src/configs/ts-all.ts
  libs/sdk/skyux-eslint/src/configs/ts-base.ts
  libs/sdk/skyux-eslint/src/configs/ts-recommended.ts
  libs/sdk/skyux-eslint/src/configs/ts-strict-base-type-checked.ts
  libs/sdk/skyux-eslint/src/configs/ts-strict-base.ts
  libs/sdk/skyux-eslint/src/configs/ts-strict-type-checked.ts
  libs/sdk/skyux-eslint/src/index.ts
  package-lock.json
  package.json
Labels: risk level (author): 1

#3393 fix(components/ag-grid): include `styleNonce` option when using CSP headers
  libs/components/ag-grid/src/lib/modules/ag-grid/ag-grid-wrapper.component.html
  libs/components/ag-grid/src/lib/modules/ag-grid/ag-grid-wrapper.component.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/ag-grid.service.spec.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/ag-grid.service.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/icons/icon-map.ts
  libs/components/ag-grid/src/lib/styles/_ag-grid-extra.scss
  libs/components/ag-grid/src/lib/styles/_base.scss
  libs/components/ag-grid/src/lib/styles/_modern.scss
  libs/components/ag-grid/src/lib/styles/ag-grid-theme.ts
  libs/components/packages/package.json
  libs/components/theme/package.json
  libs/components/theme/src/lib/styles/sky.scss
  package-lock.json
  package.json
Labels: risk level (author): 1

#3429 chore: release 12.11.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#3432 fix(components/tiles): validate tile config when loading dashboard from ui-config
  libs/components/tiles/src/lib/modules/tiles/tile-dashboard/fixtures/mock-ui-config.service.ts
  libs/components/tiles/src/lib/modules/tiles/tile-dashboard/tile-dashboard.service.spec.ts
  libs/components/tiles/src/lib/modules/tiles/tile-dashboard/tile-dashboard.service.ts
Labels: risk level (author): 1

#3433 docs(components/forms): add note to file drop's `loadFile(s)` to include providers
  libs/components/forms/testing/src/modules/file-attachment/file-drop/file-drop-harness.spec.ts
  libs/components/forms/testing/src/modules/file-attachment/file-drop/file-drop-harness.ts
Labels: risk level (author): 1

#3434 chore: release 12.11.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#3435 fix(sdk/eslint-schematics): only set `strictNullChecks` if `strict` unset
  libs/sdk/eslint-schematics/src/schematics/ng-add/ng-add.schematic.spec.ts
  libs/sdk/eslint-schematics/src/schematics/ng-add/ng-add.schematic.ts
Labels: risk level (author): 1

#3437 fix: add explicit harness predicate return type
  libs/components/indicators/testing/src/modules/tokens/tokens-harness.ts
  libs/components/lists/testing/src/modules/infinite-scroll/infinite-scroll-harness.ts
Labels: risk level (author): 1

#3438 chore: release 12.11.3
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#3444 chore(apps/playground): add playground page for navbar
  apps/playground/src/app/components/components.module.ts
  apps/playground/src/app/components/navbar/navbar.module.ts
  apps/playground/src/app/components/navbar/navbar/navbar-routing.module.ts
  apps/playground/src/app/components/navbar/navbar/navbar.component.html
  apps/playground/src/app/components/navbar/navbar/navbar.component.scss
  apps/playground/src/app/components/navbar/navbar/navbar.component.ts
  apps/playground/src/app/components/navbar/navbar/navbar.module.ts
Labels: risk level (author): 1

#3441 feat(components/lists): tokenize repeater styles
  apps/e2e/lists-storybook-e2e/src/e2e/repeater.component.cy.ts
  apps/playground/src/app/components/lists/repeater/repeater-visual.component.ts
  libs/components/lists/src/lib/modules/repeater/repeater-item.component.html
  libs/components/lists/src/lib/modules/repeater/repeater-item.component.scss
  libs/components/lookup/src/lib/modules/selection-modal/selection-modal.component.scss
Labels: risk level (author): 2

#3443 chore: release 12.12.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#3445 fix(sdk/eslint-schematics): do not modify tsconfig.json when adding `eslint-config-skyux` to a project
  libs/sdk/eslint-config-skyux/src/index.ts
  libs/sdk/eslint-schematics/src/schematics/ng-add/ng-add.schematic.spec.ts
  libs/sdk/eslint-schematics/src/schematics/ng-add/ng-add.schematic.ts
Labels: risk level (author): 1

#3447 feat(components/navbar): tokenize navbar styles
  .github/instructions/add-scss-override.instructions.md
  apps/e2e/navbar-storybook-e2e/src/e2e/navbar.component.cy.ts
  apps/playground/src/app/components/navbar/navbar/navbar.component.html
  apps/playground/src/app/components/navbar/navbar/navbar.component.ts
  libs/components/navbar/src/lib/modules/navbar/navbar-item.component.scss
  libs/components/navbar/src/lib/modules/navbar/navbar.component.scss
Labels: risk level (author): 2

#3449 fix(components/docs-tools): add `provideRouter` in `main.ts`
  libs/components/docs-tools/src/lib/modules/code-example-viewer/stackblitz.service.spec.ts
  libs/components/docs-tools/src/lib/modules/code-example-viewer/stackblitz.service.ts
Labels: risk level (author): 1

#3451 feat(components/progress-indicator): tokenize passive and waterfall progress indicator styles
  apps/e2e/progress-indicator-storybook-e2e/src/e2e/progress-indicator.component.cy.ts
  libs/components/progress-indicator/src/lib/modules/progress-indicator/progress-indicator-item/progress-indicator-item.component.html
  libs/components/progress-indicator/src/lib/modules/progress-indicator/progress-indicator-item/progress-indicator-item.component.scss
  libs/components/progress-indicator/src/lib/modules/progress-indicator/progress-indicator-status-marker/progress-indicator-status-marker.component.scss
  libs/components/progress-indicator/src/lib/modules/progress-indicator/progress-indicator-title/progress-indicator-title.component.scss
  libs/components/progress-indicator/src/lib/modules/progress-indicator/progress-indicator.component.scss
  libs/components/progress-indicator/src/lib/modules/progress-indicator/scss/progress-indicator-variables.scss
  libs/components/theme/package.json
  package-lock.json
  package.json
Labels: risk level (author): 2

#3450 fix(components/lookup): search component automatically focuses on expanding in mobile view
  libs/components/lookup/src/lib/modules/search/search.component.spec.ts
  libs/components/lookup/src/lib/modules/search/search.component.ts
Labels: risk level (author): 1

#3454 feat(components/docs-tools): add showcase highlight component
  libs/components/docs-tools/src/index.ts
  libs/components/docs-tools/src/lib/modules/showcase/showcase-area-highlight.component.ts
  libs/components/docs-tools/src/lib/modules/showcase/showcase.component.html
  libs/components/docs-tools/src/lib/modules/showcase/showcase.component.ts
  libs/components/docs-tools/src/lib/modules/showcase/showcase.module.ts
Labels: risk level (author): 1

#3455 fix(sdk/eslint-config-skyux): add missing rules from legacy "recommended" config
  libs/sdk/eslint-config-skyux/src/index.ts
Labels: risk level (author): 1

#3448 chore: release 12.13.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#3456 fix(components/colorpicker): checkered background properly displays on non-transparent parent backgrounds
  libs/components/colorpicker/src/lib/modules/colorpicker/colorpicker.component.html
  libs/components/colorpicker/src/lib/modules/colorpicker/colorpicker.component.scss
Labels: risk level (author): 2

#3458 fix(sdk/skyux-eslint): add `no-sky-selectors` rule
  libs/sdk/eslint-config-skyux/README.md
  libs/sdk/eslint-config-skyux/src/index.ts
  libs/sdk/skyux-eslint/src/configs/ts-all.ts
  libs/sdk/skyux-eslint/src/configs/ts-recommended.ts
  libs/sdk/skyux-eslint/src/rules/no-sky-selectors.spec.ts
  libs/sdk/skyux-eslint/src/rules/no-sky-selectors.ts
Labels: risk level (author): 1

#3460 fix(sdk/skyux-eslint): apply `no-sky-selectors` rule to plugin
  libs/sdk/skyux-eslint/src/plugins/ts-plugin.ts
Labels: risk level (author): 1

#3459 ci: update dev-infra to 12.0.0-alpha.3
  package-lock.json
  package.json
Labels: risk level (author): 1

#3461 chore: release 12.13.2
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#3464 fix(components/lookup): adjust item tracking in template
  libs/components/lookup/src/lib/modules/autocomplete/autocomplete.component.html
Labels: risk level (author): 1

#3465 feat(components/theme): update `@skyux/icons` to 8.0.0
  libs/components/docs-tools/src/lib/modules/code-example-viewer/stackblitz.service.spec.ts
  libs/components/docs-tools/src/lib/modules/code-example-viewer/stackblitz.service.ts
  libs/components/icon/src/lib/modules/icon/icon-resolver.service.spec.ts
  libs/components/icon/src/lib/modules/icon/icon-svg-resolver.service.spec.ts
  libs/components/icon/src/lib/modules/icon/icon-svg-resolver.service.ts
  libs/components/packages/package.json
  libs/components/theme/package.json
  libs/components/theme/src/lib/styles/sky.scss
  package-lock.json
  package.json
Labels: risk level (author): 2

#3462 chore: release 12.14.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#3463 fix(sdk/skyux-eslint): remove `.sky-form-control` classname from inputs when fixing `prefer-label-text` rule
  libs/sdk/eslint-config-skyux/src/index.ts
  libs/sdk/skyux-eslint/src/rules/template/prefer-label-text.spec.ts
  libs/sdk/skyux-eslint/src/rules/template/prefer-label-text.ts
  libs/sdk/skyux-eslint/src/rules/utils/ast-utils.ts
Labels: risk level (author): 2

#3468 fix(components/i18n): generate assets for library resources in the same directory as the entry point
  libs/components/i18n/schematics/ng-generate/lib-resources-module/lib-resources-module.schematic.spec.ts
  libs/components/i18n/schematics/ng-generate/lib-resources-module/lib-resources-module.schematic.ts
Labels: risk level (author): 1

#3473 chore: release 12.14.2
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#3476 chore(components/code-examples): set `@angular-eslint/directive-selector` ESLint rule
  libs/components/code-examples/eslint.config.js
Labels: risk level (author): 1

#3475 fix: set `sideEffects` to `false` in libraries package.json
  libs/components/a11y/package.json
  libs/components/action-bars/package.json
  libs/components/ag-grid/package.json
  libs/components/angular-tree-component/package.json
  libs/components/animations/package.json
  libs/components/assets/package.json
  libs/components/autonumeric/package.json
  libs/components/avatar/package.json
  libs/components/code-examples/package.json
  libs/components/colorpicker/package.json
  libs/components/config/package.json
  libs/components/core/package.json
  libs/components/data-manager/package.json
  libs/components/datetime/package.json
  libs/components/docs-tools/package.json
  libs/components/errors/package.json
  libs/components/flyout/package.json
  libs/components/forms/package.json
  libs/components/grids/package.json
  libs/components/help-inline/package.json
  libs/components/i18n/package.json
  libs/components/indicators/package.json
  libs/components/inline-form/package.json
  libs/components/layout/package.json
  libs/components/list-builder-common/package.json
  libs/components/list-builder-view-checklist/package.json
  libs/components/list-builder-view-grids/package.json
  libs/components/list-builder/package.json
  libs/components/lists/package.json
  libs/components/lookup/package.json
  libs/components/manifest-generator/package.json
  libs/components/manifest/package.json
  libs/components/modals/package.json
  libs/components/navbar/package.json
  libs/components/packages/package.json
  libs/components/pages/package.json
  libs/components/phone-field/package.json
  libs/components/popovers/package.json
  libs/components/progress-indicator/package.json
  libs/components/router/package.json
  libs/components/select-field/package.json
  libs/components/split-view/package.json
  libs/components/storybook/package.json
  libs/components/tabs/package.json
  libs/components/text-editor/package.json
  libs/components/theme/package.json
  libs/components/tiles/package.json
  libs/components/toast/package.json
  libs/components/validation/package.json
Labels: risk level (author): 2

#3479 fix(sdk/skyux-eslint): remove unused peer dependencies
  libs/sdk/skyux-eslint/package.json
  libs/sdk/skyux-eslint/src/rules/template/no-deprecated-classnames.ts
  libs/sdk/skyux-eslint/src/rules/template/no-deprecated-directives.ts
  libs/sdk/skyux-eslint/src/rules/template/no-legacy-icons.ts
  libs/sdk/skyux-eslint/src/rules/template/no-radio-group-with-nested-list.ts
  libs/sdk/skyux-eslint/src/rules/template/prefer-label-text.ts
  libs/sdk/skyux-eslint/src/rules/template/utils/get-directive-selector-details.ts
  libs/sdk/skyux-eslint/src/rules/template/utils/no-legacy-icons-mappings.ts
  libs/sdk/skyux-eslint/src/rules/utils/ast-utils.ts
  libs/sdk/skyux-eslint/tsconfig.lib.json
  libs/sdk/skyux-eslint/tsconfig.spec.json
  package-lock.json
  package.json
Labels: risk level (author): 1

#3469 chore: update README files related to ESLint packages
  libs/sdk/eslint-config-skyux/README.md
  libs/sdk/eslint-config/README.md
  libs/sdk/prettier-schematics/README.md
  libs/sdk/skyux-eslint/README.md
Labels: risk level (author): 1

#3478 chore: release 12.14.3
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#3482 fix(components/forms): field group component stacked input uses correct class
  libs/components/forms/src/lib/modules/field-group/field-group.component.spec.ts
  libs/components/forms/src/lib/modules/field-group/field-group.component.ts
  libs/components/forms/testing/src/modules/field-group/field-group-harness.ts
Labels: risk level (author): 1

#3486 fix(components/theme): remove data label font tokens
  libs/components/theme/src/lib/styles/themes/modern/_type.scss
Labels: risk level (author): 1

#3484 fix(components/forms): update switch border color styles
  libs/components/forms/src/lib/modules/toggle-switch/toggle-switch.component.scss
  libs/components/theme/src/lib/styles/themes/modern/_switch.scss
Labels: risk level (author): 1

#3452 feat(components/ag-grid): tokenize data grid styles
  apps/e2e/ag-grid-storybook-e2e/src/e2e/ag-grid-stories.component.cy.ts
  apps/e2e/ag-grid-storybook-e2e/src/e2e/ag-grid-widgets.component.cy.ts
  apps/e2e/ag-grid-storybook-e2e/src/e2e/data-entry-grid.component.cy.ts
  apps/e2e/ag-grid-storybook-e2e/src/e2e/data-manager.component.cy.ts
  apps/e2e/data-manager-storybook-e2e/src/e2e/data-manager.component.cy.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/ag-grid-wrapper.component.spec.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/ag-grid-wrapper.component.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/ag-grid.service.spec.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/ag-grid.service.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-editors/cell-editor-autocomplete/cell-editor-autocomplete.component.scss
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-editors/cell-editor-currency/cell-editor-currency.component.html
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-editors/cell-editor-currency/cell-editor-currency.component.scss
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-editors/cell-editor-currency/cell-editor-currency.component.spec.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-editors/cell-editor-currency/cell-editor-currency.component.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-editors/cell-editor-datepicker/cell-editor-datepicker.component.scss
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-editors/cell-editor-datepicker/cell-editor-datepicker.component.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-editors/cell-editor-number/cell-editor-number.component.scss
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-editors/cell-editor-text/cell-editor-text.component.html
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-editors/cell-editor-text/cell-editor-text.component.scss
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-renderers/cell-renderer-currency/cell-renderer-currency.component.scss
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-renderers/cell-renderer-row-selector/cell-renderer-row-selector.component.html
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-renderers/cell-renderer-row-selector/cell-renderer-row-selector.component.scss
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-validator/ag-grid-cell-validator-tooltip.component.scss
  libs/components/ag-grid/src/lib/modules/ag-grid/header/header-group.component.scss
  libs/components/ag-grid/src/lib/modules/ag-grid/header/header.component.scss
  libs/components/ag-grid/src/lib/styles/_ag-grid-extra.scss
  libs/components/ag-grid/src/lib/styles/_base.scss
  libs/components/ag-grid/src/lib/styles/_default.scss
  libs/components/ag-grid/src/lib/styles/_modern-dark.scss
  libs/components/ag-grid/src/lib/styles/_modern-light.scss
  libs/components/ag-grid/src/lib/styles/_modern.scss
  libs/components/ag-grid/src/lib/styles/_overrides.scss
  libs/components/ag-grid/src/lib/styles/_variables.scss
  libs/components/ag-grid/src/lib/styles/ag-grid-styles.scss
  libs/components/ag-grid/src/lib/styles/ag-grid-theme.ts
  libs/components/data-manager/src/lib/modules/data-manager/data-manager-column-picker/data-manager-column-picker.component.scss
  libs/components/indicators/src/lib/modules/status-indicator/status-indicator.component.scss
  libs/components/theme/package.json
  libs/components/theme/src/lib/styles/themes/modern/_custom-properties.scss
  libs/components/theme/src/lib/styles/themes/modern/_forms.scss
  package-lock.json
  package.json
Labels: risk level (author): 3

#3488 fix(components/packages): add `"sideEffects": true` to support `@skyux/packages/polyfills`
  libs/components/packages/package.json
Labels: risk level (author): 1

#3483 chore: release 12.15.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#3490 chore: do not run integration E2E tests for modern V2
  apps/integration-e2e/src/e2e/field-heights.cy.ts
  apps/integration-e2e/src/e2e/lookup-in-modal.cy.ts
  apps/integration-e2e/src/e2e/modal-colorpicker.cy.ts
  apps/integration-e2e/src/e2e/modal-date-range-picker.cy.ts
  apps/integration-e2e/src/e2e/modal-footer-dropdown.cy.ts
  apps/integration-e2e/src/e2e/modal-split-view-tile-dashboard.cy.ts
  apps/integration-e2e/src/e2e/modal-viewkept-toolbars.cy.ts
  apps/integration-e2e/src/e2e/vertical-tabset-back-to-top.cy.ts
  apps/integration-e2e/src/e2e/viewkeeper-tabset.cy.ts
  libs/sdk/e2e-schematics/src/lib/e2e-variations/e2e-variations.spec.ts
  libs/sdk/e2e-schematics/src/lib/e2e-variations/e2e-variations.ts
Labels: risk level (author): 1
