Repository blackbaud/skyux, pull requests merged in 2025-08, with the labels that each got.

#3782 chore: update design token library to alpha.14 (#3781)
  libs/components/theme/package.json
  package-lock.json
  package.json
Labels: risk level (author): 1

#3780 feat!: remove modern v1 support from ag-grid, avatar, colorpicker, summary action bar, and tree view
  .github/instructions/remove-modern-theme-v1.instructions.md
  libs/components/action-bars/src/lib/modules/summary-action-bar/actions/summary-action-bar-secondary-actions.component.scss
  libs/components/action-bars/src/lib/modules/summary-action-bar/summary-action-bar.component.scss
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-editors/cell-editor-currency/cell-editor-currency.component.scss
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-editors/cell-editor-text/cell-editor-text.component.scss
  libs/components/ag-grid/src/lib/modules/ag-grid/header/header-group.component.scss
  libs/components/ag-grid/src/lib/styles/_modern.scss
  libs/components/ag-grid/src/lib/styles/_overrides.scss
  libs/components/angular-tree-component/src/lib/modules/angular-tree/angular-tree-wrapper.component.scss
  libs/components/avatar/src/lib/modules/avatar/avatar.inner.component.scss
  libs/components/colorpicker/src/lib/modules/colorpicker/colorpicker.component.scss
Labels: risk level (author): 2

#3786 feat!: remove modern v1 support from autocomplete, confirm, country field, dropdown, lookup, modal, navbar, phone field, popover, progress indicator, and search
  libs/components/lookup/src/lib/modules/autocomplete/autocomplete.component.scss
  libs/components/lookup/src/lib/modules/country-field/country-field.component.scss
  libs/components/lookup/src/lib/modules/lookup/lookup.component.scss
  libs/components/lookup/src/lib/modules/search/search.component.scss
  libs/components/modals/src/lib/modules/confirm/confirm.component.scss
  libs/components/modals/src/lib/modules/modal/modal-header.component.scss
  libs/components/modals/src/lib/modules/modal/modal.component.scss
  libs/components/navbar/src/lib/modules/navbar/navbar-item.component.scss
  libs/components/navbar/src/lib/modules/navbar/navbar.component.scss
  libs/components/phone-field/src/lib/modules/phone-field/phone-field.component.scss
  libs/components/popovers/src/lib/modules/dropdown/dropdown-item.component.scss
  libs/components/popovers/src/lib/modules/dropdown/dropdown.component.scss
  libs/components/popovers/src/lib/modules/popover/popover-content.component.scss
  libs/components/progress-indicator/src/lib/modules/progress-indicator/progress-indicator-item/progress-indicator-item.component.scss
  libs/components/progress-indicator/src/lib/modules/progress-indicator/progress-indicator-status-marker/progress-indicator-status-marker.component.scss
  libs/components/progress-indicator/src/lib/modules/progress-indicator/progress-indicator.component.scss
Labels: risk level (author): 2

#3793 feat(components/layout)!: remove deprecated `iconType` input from the action button icon in favor of `iconName`
  apps/e2e/layout-storybook/src/app/action-button/action-button-modal.component.html
  apps/e2e/layout-storybook/src/app/action-button/action-button.component.html
  apps/integration/src/app/home/home.component.html
  apps/playground/src/app/components/layout/action-button/action-button-modal.component.html
  libs/components/layout/src/lib/modules/action-button/action-button-icon.component.html
  libs/components/layout/src/lib/modules/action-button/action-button-icon.component.ts
  libs/components/layout/src/lib/modules/action-button/action-button.component.spec.ts
  libs/components/layout/src/lib/modules/action-button/fixtures/action-button-ngfor.component.fixture.ts
  libs/components/layout/src/lib/modules/action-button/fixtures/action-button.component.fixture.html
  libs/components/layout/src/lib/modules/action-button/fixtures/action-button.component.fixture.ts
  libs/components/layout/testing/src/legacy/action-button-fixture.spec.ts
  libs/components/layout/testing/src/legacy/action-button-fixture.ts
  libs/components/layout/testing/src/modules/action-button/action-button-container-harness.spec.ts
  libs/components/layout/testing/src/modules/action-button/action-button-harness.spec.ts
Labels: risk level (author): 2

#3795 chore: changelog for 12.32.0 (#3767) 🍒
  CHANGELOG.md
Labels: risk level (author): 1

#3797 ci: set up automated-translations-12.x.x workflow
  .github/workflows/automated-translations.yml
Labels: risk level (author): 1, skip e2e

#3801 ci: set up automated-translations-12.x.x workflow (#3797)
  .github/workflows/automated-translations.yml
Labels: risk level (author): 1, skip e2e

#3796 feat(components/forms)!: remove deprecated `icon` input from radios in favor of `iconName`
  apps/e2e/ag-grid-storybook/src/app/data-manager/data-manager.component.html
  apps/e2e/forms-storybook/src/app/radio-button/radio-button.component.html
  apps/e2e/forms-storybook/src/app/radio-button/radio-button.component.ts
  apps/e2e/layout-storybook/src/app/toolbar/toolbar.component.html
  apps/e2e/theme-storybook/src/app/switch-controls/switch-controls.component.html
  apps/e2e/theme-storybook/src/app/switch-controls/switch-controls.component.ts
  apps/playground/src/app/components/forms/radio/radio.component.html
  libs/components/code-examples/src/lib/modules/forms/radio/icon/example.component.html
  libs/components/code-examples/src/lib/modules/forms/radio/icon/example.component.ts
  libs/components/forms/src/lib/modules/radio/fixtures/radio-single.component.fixture.html
  libs/components/forms/src/lib/modules/radio/fixtures/radio-single.component.fixture.ts
  libs/components/forms/src/lib/modules/radio/radio.component.html
  libs/components/forms/src/lib/modules/radio/radio.component.spec.ts
  libs/components/forms/src/lib/modules/radio/radio.component.ts
Labels: risk level (author): 2

#3800 chore: finish v1 modern removal
  .github/instructions/add-scss-override.instructions.md
  .github/instructions/remove-modern-theme-v1.instructions.md
  .github/instructions/scss-override-mixins.instructions.md
  .github/instructions/setup-tokenization.instructions.md
  apps/e2e/popovers-storybook/src/app/popover/popover.component.scss
  libs/components/action-bars/src/lib/modules/summary-action-bar/actions/summary-action-bar-cancel.component.scss
  libs/components/ag-grid/src/lib/styles/_overrides.scss
  libs/components/colorpicker/src/lib/modules/colorpicker/colorpicker.component.scss
  libs/components/datetime/src/lib/modules/datepicker/calendar/datepicker-calendar-inner.component.scss
  libs/components/filter-bar/src/lib/modules/filter-bar/filter-bar-item.component.scss
  libs/components/flyout/src/lib/modules/flyout/flyout.component.scss
  libs/components/forms/src/lib/modules/file-attachment/file-drop/file-drop.component.scss
  libs/components/forms/src/lib/modules/input-box/input-box.component.scss
  libs/components/forms/src/lib/modules/selection-box/selection-box-grid.component.scss
  libs/components/forms/src/lib/modules/selection-box/selection-box.component.scss
  libs/components/forms/src/lib/modules/toggle-switch/toggle-switch.component.scss
  libs/components/indicators/src/lib/modules/label/label.component.scss
  libs/components/inline-form/src/lib/modules/inline-form/inline-form.component.scss
  libs/components/lists/src/lib/modules/repeater/repeater-item.component.scss
  libs/components/lists/src/lib/modules/sort/sort-item.component.scss
  libs/components/modals/src/lib/modules/modal/modal-header.component.scss
  libs/components/navbar/src/lib/modules/navbar/navbar-item.component.scss
  libs/components/popovers/src/lib/modules/popover/popover-content.component.scss
  libs/components/split-view/src/lib/modules/split-view/split-view-workspace-footer.component.scss
  libs/components/storybook/src/lib/preview-wrapper/preview-wrapper-global-types.ts
  libs/components/storybook/src/lib/preview-wrapper/preview-wrapper-theme-value.ts
  libs/components/storybook/src/lib/preview-wrapper/preview-wrapper.component.spec.ts
  libs/components/storybook/src/lib/preview-wrapper/preview-wrapper.component.ts
  libs/components/tabs/src/lib/modules/tabs/tab-button.component.scss
  libs/components/tabs/src/lib/modules/tabs/tabset.component.scss
  libs/components/tabs/src/lib/modules/vertical-tabset/vertical-tab.component.scss
  libs/components/theme/src/lib/styles/_compat-tokens-mixins.scss
  libs/components/theme/src/lib/styles/themes/modern/_compat-tokens-mixins.scss
  libs/components/theme/src/lib/styles/themes/modern/_forms.scss
  libs/components/theme/src/lib/styles/themes/modern/_theme.scss
  libs/components/theme/src/lib/styles/themes/modern/_type.scss
  libs/components/tiles/src/lib/modules/tiles/tile/tile.component.scss
  libs/components/toast/src/lib/modules/toast/toast.component.scss
Labels: risk level (author): 2

#3802 feat(components/forms)!: remove deprecated `icon` input from checkboxes in favor of `iconName`
  apps/e2e/ag-grid-storybook/src/app/data-manager/data-manager.component.html
  apps/e2e/forms-storybook/src/app/checkbox/checkbox.component.html
  apps/playground/src/app/components/forms/checkbox/checkbox.component.html
  libs/components/forms/src/lib/modules/checkbox/checkbox-group.component.html
  libs/components/forms/src/lib/modules/checkbox/checkbox.component.html
  libs/components/forms/src/lib/modules/checkbox/checkbox.component.spec.ts
  libs/components/forms/src/lib/modules/checkbox/checkbox.component.ts
  libs/components/forms/testing/src/legacy/checkbox-fixture.spec.ts
  libs/components/forms/testing/src/legacy/checkbox-fixture.ts
Labels: risk level (author): 2

#3805 feat(components/theme)!: remove the `--sky-category-color-light-blue` custom property in favor of `--sky-category-color-green` and add a schematic to convert existing usages
  libs/components/avatar/src/lib/modules/avatar/avatar.inner.component.scss
  libs/components/docs-tools/src/lib/modules/category-tag/category-tag.component.scss
  libs/components/packages/migrations.json
  libs/components/packages/src/schematics/migrations/update-13/replace-light-blue-custom-property/replace-light-blue-custom-property.schematic.spec.ts
  libs/components/packages/src/schematics/migrations/update-13/replace-light-blue-custom-property/replace-light-blue-custom-property.schematic.ts
  libs/components/packages/src/schematics/rules/replace-custom-property/replace-custom-property.spec.ts
  libs/components/packages/src/schematics/rules/replace-custom-property/replace-custom-property.ts
  libs/components/theme/src/lib/styles/_custom-properties.scss
  libs/components/theme/src/lib/styles/themes/modern/_custom-properties.scss
Labels: risk level (author): 2

#3808 fix(components/packages): adjust spacing generated by convert-page-summary-to-page-header schematic
  libs/components/packages/src/schematics/rules/convert-definition-list-to-description-list/convert-definition-list-to-description-list.spec.ts
  libs/components/packages/src/schematics/rules/convert-definition-list-to-description-list/convert-definition-list-to-description-list.ts
  libs/components/packages/src/schematics/rules/convert-page-summary-to-page-header/convert-page-summary-to-page-header.spec.ts
  libs/components/packages/src/schematics/rules/convert-page-summary-to-page-header/convert-page-summary-to-page-header.ts
  libs/components/packages/src/schematics/utility/log-once.spec.ts
  libs/components/packages/src/schematics/utility/log-once.ts
Labels: risk level (author): 1, skip e2e

#3806 chore: release 12.32.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease 12.x.x: pending

#3811 fix(components/packages): adjust spacing generated by convert-page-summary-to-page-header schematic (#3808)
  libs/components/packages/src/schematics/rules/convert-definition-list-to-description-list/convert-definition-list-to-description-list.spec.ts
  libs/components/packages/src/schematics/rules/convert-definition-list-to-description-list/convert-definition-list-to-description-list.ts
  libs/components/packages/src/schematics/rules/convert-page-summary-to-page-header/convert-page-summary-to-page-header.spec.ts
  libs/components/packages/src/schematics/rules/convert-page-summary-to-page-header/convert-page-summary-to-page-header.ts
  libs/components/packages/src/schematics/utility/log-once.spec.ts
  libs/components/packages/src/schematics/utility/log-once.ts
Labels: risk level (author): 1, skip e2e

#3812 chore: changelog for 12.32.1 (#3806) 🍒
  CHANGELOG.md
Labels: risk level (author): 1, skip e2e

#3823 fix(components/pages): flexbox layout should grow for sky-page-header-details
  apps/e2e/pages-storybook-e2e/src/e2e/page-layout-blocks.component.cy.ts
  apps/e2e/pages-storybook/src/app/page/layouts/blocks-page/blocks-page.component.html
  apps/e2e/pages-storybook/src/app/page/layouts/blocks-page/blocks-page.component.stories.ts
  apps/e2e/pages-storybook/src/app/page/layouts/blocks-page/blocks-page.component.ts
  libs/components/pages/src/lib/modules/page-header/page-header.component.scss
Labels: risk level (author): 1

#3825 fix(components/pages): flexbox layout should grow for sky-page-header-details (#3823)
  apps/e2e/pages-storybook-e2e/src/e2e/page-layout-blocks.component.cy.ts
  apps/e2e/pages-storybook/src/app/page/layouts/blocks-page/blocks-page.component.html
  apps/e2e/pages-storybook/src/app/page/layouts/blocks-page/blocks-page.component.stories.ts
  apps/e2e/pages-storybook/src/app/page/layouts/blocks-page/blocks-page.component.ts
  libs/components/pages/src/lib/modules/page-header/page-header.component.scss
Labels: risk level (author): 1

#3822 fix(components/popovers): use microtask to resolve positioning issue in Safari browser (#3820)
  libs/components/popovers/src/lib/modules/popover/popover.component.ts
  libs/components/popovers/src/lib/modules/popover/popover.directive.spec.ts
Labels: risk level (author): 2

#3753 fix(components/code-examples): add popover example for help inline component
  libs/components/code-examples/src/index.ts
  libs/components/code-examples/src/lib/modules/help-inline/action-click/example.component.html
  libs/components/code-examples/src/lib/modules/help-inline/action-click/example.component.spec.ts
  libs/components/code-examples/src/lib/modules/help-inline/action-click/example.component.ts
  libs/components/code-examples/src/lib/modules/help-inline/help-key/example.component.html
  libs/components/code-examples/src/lib/modules/help-inline/help-key/example.component.spec.ts
  libs/components/code-examples/src/lib/modules/help-inline/help-key/example.component.ts
  libs/components/code-examples/src/lib/modules/help-inline/popover/example.component.html
  libs/components/code-examples/src/lib/modules/help-inline/popover/example.component.spec.ts
  libs/components/code-examples/src/lib/modules/help-inline/popover/example.component.ts
  libs/components/help-inline/documentation.json
Labels: risk level (author): 1

#3824 feat(components/layout)!: deprecated page component has been removed and consumers should use the page component in the pages library
  apps/e2e/layout-storybook-e2e/src/e2e/page.component.cy.ts
  apps/e2e/layout-storybook/src/app/app.module.ts
  apps/e2e/layout-storybook/src/app/page/page.component.html
  apps/e2e/layout-storybook/src/app/page/page.component.scss
  apps/e2e/layout-storybook/src/app/page/page.component.stories.ts
  apps/e2e/layout-storybook/src/app/page/page.component.ts
  apps/e2e/layout-storybook/src/app/page/page.module.ts
  apps/e2e/tabs-storybook/src/app/vertical-tabs/vertical-tabs.module.ts
  apps/playground/src/app/components/split-view/split-view/split-view.module.ts
  apps/playground/src/app/components/tabs/tabs/tabs.module.ts
  libs/components/code-examples/src/lib/modules/layout/page/layout-fit/example.component.ts
  libs/components/code-examples/src/lib/modules/split-view/split-view/page-bound/example.component.ts
  libs/components/layout/documentation.json
  libs/components/layout/src/index.ts
  libs/components/layout/src/lib/modules/page/page-layout-type.ts
  libs/components/layout/src/lib/modules/page/page-theme-adapter.service.spec.ts
  libs/components/layout/src/lib/modules/page/page-theme-adapter.service.ts
  libs/components/layout/src/lib/modules/page/page.component.html
  libs/components/layout/src/lib/modules/page/page.component.scss
  libs/components/layout/src/lib/modules/page/page.component.spec.ts
  libs/components/layout/src/lib/modules/page/page.component.ts
  libs/components/layout/src/lib/modules/page/page.module.ts
Labels: risk level (author): 2, screenshot removed

#3830 fix: ag-grid headers are correctly styled when within a page component with a list layout
  libs/components/pages/src/lib/modules/page/page.component.scss
  libs/components/tabs/src/lib/modules/tabs/tab.component.scss
Labels: risk level (author): 2

#3817 chore: release 12.33.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease 12.x.x: pending

#3814 feat(components/packages): create schematic to convert progress-indicator wizard to tabs wizard
  libs/components/packages/collection.json
  libs/components/packages/src/schematics/ng-generate/convert-progress-indicator-wizard-to-tab-wizard/convert-progress-indicator-wizard-to-tab-wizard.schematic.spec.ts
  libs/components/packages/src/schematics/ng-generate/convert-progress-indicator-wizard-to-tab-wizard/convert-progress-indicator-wizard-to-tab-wizard.schematic.ts
  libs/components/packages/src/schematics/ng-generate/convert-progress-indicator-wizard-to-tab-wizard/schema.json
  libs/components/packages/src/schematics/ng-generate/convert-progress-indicator-wizard-to-tab-wizard/schema.ts
  libs/components/packages/src/schematics/rules/convert-progress-indicator-wizard-to-tab-wizard/__snapshots__/convert-progress-indicator-wizard-to-tab-wizard.spec.ts.snap
  libs/components/packages/src/schematics/rules/convert-progress-indicator-wizard-to-tab-wizard/convert-progress-indicator-wizard-to-tab-wizard.spec.ts
  libs/components/packages/src/schematics/rules/convert-progress-indicator-wizard-to-tab-wizard/convert-progress-indicator-wizard-to-tab-wizard.ts
  libs/components/packages/src/schematics/rules/convert-progress-indicator-wizard-to-tab-wizard/options.ts
  libs/components/packages/src/schematics/testing/__snapshots__/angular-module-generator.spec.ts.snap
  libs/components/packages/src/schematics/testing/angular-module-generator.spec.ts
  libs/components/packages/src/schematics/testing/angular-module-generator.ts
Labels: risk level (author): 2, skip e2e

#3847 feat(components/packages): create schematic to convert progress-indicator wizard to tabs wizard (#3814)
  libs/components/packages/collection.json
  libs/components/packages/src/schematics/ng-generate/convert-progress-indicator-wizard-to-tab-wizard/convert-progress-indicator-wizard-to-tab-wizard.schematic.spec.ts
  libs/components/packages/src/schematics/ng-generate/convert-progress-indicator-wizard-to-tab-wizard/convert-progress-indicator-wizard-to-tab-wizard.schematic.ts
  libs/components/packages/src/schematics/ng-generate/convert-progress-indicator-wizard-to-tab-wizard/schema.json
  libs/components/packages/src/schematics/ng-generate/convert-progress-indicator-wizard-to-tab-wizard/schema.ts
  libs/components/packages/src/schematics/rules/convert-progress-indicator-wizard-to-tab-wizard/__snapshots__/convert-progress-indicator-wizard-to-tab-wizard.spec.ts.snap
  libs/components/packages/src/schematics/rules/convert-progress-indicator-wizard-to-tab-wizard/convert-progress-indicator-wizard-to-tab-wizard.spec.ts
  libs/components/packages/src/schematics/rules/convert-progress-indicator-wizard-to-tab-wizard/convert-progress-indicator-wizard-to-tab-wizard.ts
  libs/components/packages/src/schematics/rules/convert-progress-indicator-wizard-to-tab-wizard/options.ts
  libs/components/packages/src/schematics/testing/__snapshots__/angular-module-generator.spec.ts.snap
  libs/components/packages/src/schematics/testing/angular-module-generator.spec.ts
  libs/components/packages/src/schematics/testing/angular-module-generator.ts
  libs/components/packages/src/schematics/utility/typescript/__snapshots__/ng-ast.spec.ts.snap
  libs/components/packages/src/schematics/utility/typescript/ng-ast.spec.ts
  libs/components/packages/src/schematics/utility/typescript/ng-ast.ts
Labels: risk level (author): 2, skip e2e

#3849 chore: update NX AI settings to utilize MCP via the extension and autogenerate instructions (#3848)
  .vscode/mcp.json
  .vscode/settings.json
Labels: risk level (author): 1

#3850 chore: changelog for 12.35.0 (#3844) 🍒
  CHANGELOG.md
Labels: risk level (author): 1

#3851 feat(sdk/stylelint-config-skyux): add `no-static-color-values` rule to prevent usage of static color values in stylesheets
  .cspell.json
  libs/sdk/skyux-stylelint/docs/rules/no-static-color-values.md
  libs/sdk/skyux-stylelint/src/index.ts
  libs/sdk/skyux-stylelint/src/rules/no-static-color-values.test.ts
  libs/sdk/skyux-stylelint/src/rules/no-static-color-values.ts
  libs/sdk/stylelint-config-skyux/src/index.ts
Labels: risk level (author): 1

#3852 feat(sdk/stylelint-config-skyux): add `no-static-color-values` rule to prevent usage of static color values in stylesheets (#3851)
  .cspell.json
  libs/sdk/skyux-stylelint/docs/rules/no-static-color-values.md
  libs/sdk/skyux-stylelint/src/index.ts
  libs/sdk/skyux-stylelint/src/rules/no-static-color-values.test.ts
  libs/sdk/skyux-stylelint/src/rules/no-static-color-values.ts
  libs/sdk/stylelint-config-skyux/src/index.ts
Labels: risk level (author): 1

#3864 feat(components/tabs): vertical tab groups and top level tabs are aligned and use new interactive states
  libs/components/indicators/src/lib/modules/expansion-indicator/expansion-indicator.component.scss
  libs/components/tabs/src/lib/modules/sectioned-form/sectioned-form.component.scss
  libs/components/tabs/src/lib/modules/vertical-tabset/vertical-tab.component.scss
  libs/components/tabs/src/lib/modules/vertical-tabset/vertical-tabset-button.scss
  libs/components/tabs/src/lib/modules/vertical-tabset/vertical-tabset-group.component.html
  libs/components/tabs/src/lib/modules/vertical-tabset/vertical-tabset-group.component.scss
  libs/components/tabs/src/lib/modules/vertical-tabset/vertical-tabset.component.scss
  libs/components/theme/package.json
  package-lock.json
  package.json
Labels: risk level (author): 2

#3867 feat: pull in latest design tokens
  libs/components/theme/package.json
  package-lock.json
  package.json
Labels: risk level (author): 1

#3869 fix(components/docs-tools): scroll to header on page load
  libs/components/docs-tools/src/lib/modules/table-of-contents/table-of-contents-page.component.ts
Labels: risk level (author): 1

#3873 fix(components/docs-tools): scroll to header on page load (#3869)
  libs/components/docs-tools/src/lib/modules/table-of-contents/table-of-contents-page.component.ts
Labels: risk level (author): 1

#3872 feat(components/packages): create schematic to fix deep imports
  libs/components/packages/migrations.json
  libs/components/packages/src/schematics/migrations/update-13/fix-imports/fix-imports.schematic.spec.ts
  libs/components/packages/src/schematics/migrations/update-13/fix-imports/fix-imports.schematic.ts
Labels: risk level (author): 1

#3868 feat(components/tabs): add code example for vertical tabs with both grouped and ungrouped tabs
  libs/components/code-examples/src/index.ts
  libs/components/code-examples/src/lib/modules/tabs/vertical-tabs/mixed/example.component.html
  libs/components/code-examples/src/lib/modules/tabs/vertical-tabs/mixed/example.component.spec.ts
  libs/components/code-examples/src/lib/modules/tabs/vertical-tabs/mixed/example.component.ts
  libs/components/code-examples/src/lib/modules/tabs/vertical-tabs/mixed/group.ts
  libs/components/tabs/documentation.json
Labels: risk level (author): 1

#3855 feat(sdk/stylelint-config-skyux): add `no-sky-theme-imports` rule to prevent imports from `@skyux/theme/scss/*` in stylesheets
  libs/components/theme/src/lib/styles/_public-api/_compat/_mixins.scss
  libs/components/theme/src/lib/styles/_public-api/_compat/_variables.scss
  libs/components/theme/src/lib/styles/_public-api/_component-theme.scss
  libs/components/theme/src/lib/styles/_public-api/_mixins.scss
  libs/components/theme/src/lib/styles/_public-api/_responsive.scss
  libs/components/theme/src/lib/styles/_public-api/_variables.scss
  libs/components/theme/src/lib/styles/_public-api/themes/modern/_compat/_mixins.scss
  libs/components/theme/src/lib/styles/_public-api/themes/modern/_compat/_variables.scss
  libs/sdk/skyux-stylelint/src/index.ts
  libs/sdk/skyux-stylelint/src/rules/no-sky-theme-imports.md
  libs/sdk/skyux-stylelint/src/rules/no-sky-theme-imports.test.ts
  libs/sdk/skyux-stylelint/src/rules/no-sky-theme-imports.ts
  scripts/postbuild-theme.ts
Labels: risk level (author): 2

#3871 feat: pull in latest design tokens (#3867)
  libs/components/theme/package.json
  package-lock.json
  package.json
Labels: risk level (author): 1

#3878 chore: release 13.0.0-alpha.8
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending
