Repository blackbaud/skyux, pull requests merged in 2025-06, with the labels that each got.

#3466 feat(components/action-bars): add support for `formError` input in summary action bar
  apps/e2e/action-bars-storybook-e2e/src/e2e/summary-action-bar.component.cy.ts
  apps/e2e/action-bars-storybook/src/app/summary-action-bar/summary-action-bar-modal.component.html
  apps/e2e/action-bars-storybook/src/app/summary-action-bar/summary-action-bar-modal.component.ts
  apps/e2e/action-bars-storybook/src/app/summary-action-bar/summary-action-bar.component.html
  apps/e2e/action-bars-storybook/src/app/summary-action-bar/summary-action-bar.component.stories.ts
  apps/e2e/action-bars-storybook/src/app/summary-action-bar/summary-action-bar.component.ts
  apps/playground/src/app/components/action-bars/summary-action-bar/summary-action-bar-modal.component.html
  apps/playground/src/app/components/action-bars/summary-action-bar/summary-action-bar-modal.component.ts
  apps/playground/src/app/components/action-bars/summary-action-bar/summary-action-bar.component.html
  apps/playground/src/app/components/action-bars/summary-action-bar/summary-action-bar.component.ts
  libs/components/action-bars/documentation.json
  libs/components/action-bars/src/index.ts
  libs/components/action-bars/src/lib/modules/summary-action-bar/fixtures/summary-action-bar.component.fixture.html
  libs/components/action-bars/src/lib/modules/summary-action-bar/fixtures/summary-action-bar.component.fixture.ts
  libs/components/action-bars/src/lib/modules/summary-action-bar/summary-action-bar.component.html
  libs/components/action-bars/src/lib/modules/summary-action-bar/summary-action-bar.component.scss
  libs/components/action-bars/src/lib/modules/summary-action-bar/summary-action-bar.component.spec.ts
  libs/components/action-bars/src/lib/modules/summary-action-bar/summary-action-bar.component.ts
  libs/components/action-bars/src/lib/modules/summary-action-bar/types/summary-action-bar-error.ts
  libs/components/action-bars/testing/src/modules/summary-action-bar/summary-action-bar-harness.spec.ts
  libs/components/action-bars/testing/src/modules/summary-action-bar/summary-action-bar-harness.ts
  libs/components/modals/src/lib/modules/modal/modal-footer.component.html
  libs/components/modals/src/lib/modules/modal/modal-footer.component.scss
  libs/components/theme/src/lib/styles/_theme.scss
Labels: risk level (author): 2

#3493 fix(components/ag-grid): row delete overlay should not be clipped
  apps/playground/src/app/components/ag-grid/data-manager-large/data-manager-large.component.html
  apps/playground/src/app/components/ag-grid/data-manager-large/data-manager-large.component.ts
  apps/playground/src/app/components/ag-grid/data-manager-large/delete-button/delete-button.component.html
  apps/playground/src/app/components/ag-grid/data-manager-large/delete-button/delete-button.component.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/ag-grid-row-delete.directive.spec.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/ag-grid-row-delete.directive.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/fixtures/ag-grid-row-delete.component.fixture.ts
  libs/components/core/src/lib/modules/scrollable-host/scrollable-host.service.spec.ts
  libs/components/core/src/lib/modules/scrollable-host/scrollable-host.service.ts
Labels: risk level (author): 2

#3491 chore: release 12.16.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#3499 fix(components/icon): support xxxl icon size in icon harness
  libs/components/icon/testing/src/modules/icon/icon-harness.spec.ts
  libs/components/icon/testing/src/modules/icon/icon-harness.ts
Labels: risk level (author): 1

#3504 ci: skip rebase during build
  .github/workflows/ci.yml
  .github/workflows/e2e-cancel.yml
  .github/workflows/e2e.yml
  .github/workflows/update-branch.yml
  scripts/rebase-pr.js
Labels: risk level (author): 1, skip e2e

#3495 feat(components/action-bars): add summary action bar code example with error
  apps/code-examples/src/assets/stack-blitz/package.json
  libs/components/action-bars/documentation.json
  libs/components/code-examples/src/index.ts
  libs/components/code-examples/src/lib/modules/action-bars/summary-action-bar/error/example.component.html
  libs/components/code-examples/src/lib/modules/action-bars/summary-action-bar/error/example.component.spec.ts
  libs/components/code-examples/src/lib/modules/action-bars/summary-action-bar/error/example.component.ts
Labels: risk level (author): 1

#3506 chore: release 12.18.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#3507 fix(components/lookup): stop magnifying glass from showing in country field when focused
  libs/components/lookup/src/lib/modules/country-field/country-field.component.html
  libs/components/lookup/src/lib/modules/country-field/country-field.component.spec.ts
  libs/components/lookup/src/lib/modules/country-field/country-field.component.ts
Labels: risk level (author): 2

#3511 fix(components/lookup): country field input contents are selected automatically on focus
  libs/components/lookup/src/lib/modules/country-field/country-field.component.html
  libs/components/lookup/src/lib/modules/country-field/country-field.component.spec.ts
  libs/components/lookup/src/lib/modules/country-field/country-field.component.ts
Labels: risk level (author): 2

#3508 chore: release 12.19.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#3515 ci: adjust e2e skipped job handling
  .github/workflows/e2e.yml
  libs/sdk/e2e-schematics/src/workflow/verify-e2e/verify-e2e.spec.ts
  libs/sdk/e2e-schematics/src/workflow/verify-e2e/verify-e2e.ts
Labels: risk level (author): 1, skip e2e

#3514 fix(components/tabs): permalink handling should not override other query parameters
  libs/components/tabs/src/lib/modules/tabs/tabset-permalink.service.ts
  libs/components/tabs/src/lib/modules/tabs/tabset.component.spec.ts
Labels: risk level (author): 1

#3520 docs(components/flyout): tweak beforeClose description
  libs/components/flyout/src/lib/modules/flyout/flyout-instance.ts
Labels: risk level (author): 1

#3523 fix(components/modals): tweak styleType description
  libs/components/modals/src/lib/modules/confirm/confirm-button-config.ts
Labels: risk level (author): 1

#3521 feat: add experimental `skyux-stylelint` package
  libs/components/packages/package.json
  libs/sdk/skyux-stylelint/README.md
  libs/sdk/skyux-stylelint/docs/rules/no-sky-selectors.md
  libs/sdk/skyux-stylelint/eslint.config.cjs
  libs/sdk/skyux-stylelint/package.json
  libs/sdk/skyux-stylelint/project.json
  libs/sdk/skyux-stylelint/src/index.ts
  libs/sdk/skyux-stylelint/src/rules/no-sky-selectors.test.ts
  libs/sdk/skyux-stylelint/src/rules/no-sky-selectors.ts
  libs/sdk/skyux-stylelint/src/testing/test-rule.ts
  libs/sdk/skyux-stylelint/src/testing/types.ts
  libs/sdk/skyux-stylelint/src/utility/meta.ts
  libs/sdk/skyux-stylelint/src/utility/namespace.ts
  libs/sdk/skyux-stylelint/tsconfig.json
  libs/sdk/skyux-stylelint/tsconfig.lib.json
  libs/sdk/skyux-stylelint/tsconfig.spec.json
  libs/sdk/skyux-stylelint/vitest.config.ts
  package-lock.json
  package.json
  tsconfig.base.json
Labels: risk level (author): 1

#3527 ci: create filter-bar-storybook-e2e
  apps/e2e/filter-bar-storybook-e2e/cypress.config.ts
  apps/e2e/filter-bar-storybook-e2e/eslint.config.cjs
  apps/e2e/filter-bar-storybook-e2e/project.json
  apps/e2e/filter-bar-storybook-e2e/src/e2e/.gitkeep
  apps/e2e/filter-bar-storybook-e2e/src/e2e/filter-bar/filter-bar.component.cy.ts
  apps/e2e/filter-bar-storybook-e2e/src/support/commands.ts
  apps/e2e/filter-bar-storybook-e2e/src/support/e2e.ts
  apps/e2e/filter-bar-storybook-e2e/tsconfig.json
  apps/e2e/filter-bar-storybook/.storybook/main.ts
  apps/e2e/filter-bar-storybook/.storybook/manager.ts
  apps/e2e/filter-bar-storybook/.storybook/preview.ts
  apps/e2e/filter-bar-storybook/.storybook/tsconfig.json
  apps/e2e/filter-bar-storybook/eslint.config.cjs
  apps/e2e/filter-bar-storybook/project.json
  apps/e2e/filter-bar-storybook/public/favicon.ico
  apps/e2e/filter-bar-storybook/src/app/app.component.ts
  apps/e2e/filter-bar-storybook/src/app/app.module.ts
  apps/e2e/filter-bar-storybook/src/app/filter-bar/filter-bar.component.html
  apps/e2e/filter-bar-storybook/src/app/filter-bar/filter-bar.component.scss
  apps/e2e/filter-bar-storybook/src/app/filter-bar/filter-bar.component.stories.ts
  apps/e2e/filter-bar-storybook/src/app/filter-bar/filter-bar.component.ts
  apps/e2e/filter-bar-storybook/src/index.html
  apps/e2e/filter-bar-storybook/src/main.ts
  apps/e2e/filter-bar-storybook/src/styles.scss
  apps/e2e/filter-bar-storybook/tsconfig.app.json
  apps/e2e/filter-bar-storybook/tsconfig.editor.json
  apps/e2e/filter-bar-storybook/tsconfig.json
Labels: risk level (author): 1

#3529 ci: bump node to 20.19.2
  .github/workflows/cherry-pick.yml
  .github/workflows/ci.yml
  .github/workflows/e2e.yml
  .github/workflows/release-please.yml
  .nvmrc
Labels: risk level (author): 1, skip e2e

#3530 ci: fix npm install step for e2e build-apps job on branch builds
  .github/workflows/e2e.yml
Labels: risk level (author): 1, skip e2e

#3522 feat(components/icon): update icons package
  libs/components/docs-tools/src/lib/modules/code-example-viewer/stackblitz.service.spec.ts
  libs/components/docs-tools/src/lib/modules/code-example-viewer/stackblitz.service.ts
  libs/components/packages/package.json
  libs/components/theme/package.json
  libs/components/theme/src/lib/styles/sky.scss
  package-lock.json
  package.json
Labels: risk level (author): 1

#3531 chore: release 12.21.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#3517 feat(components/forms): file attachment and file drop `dragover` accept and reject states tokenization update
  apps/e2e/forms-storybook-e2e/src/e2e/file-attachment.component.cy.ts
  apps/e2e/forms-storybook-e2e/src/e2e/single-file-attachment.component.cy.ts
  apps/e2e/forms-storybook/src/app/single-file-attachment/single-file-attachment.component.html
  apps/playground/src/app/components/forms/file-attachment/file-attachment-routing.module.ts
  apps/playground/src/app/components/forms/single-file-attachment/single-file-attachment-routing.module.ts
  libs/components/forms/src/lib/modules/file-attachment/file-attachment/file-attachment.component.scss
  libs/components/forms/src/lib/modules/file-attachment/file-drop/file-drop.component.html
  libs/components/forms/src/lib/modules/file-attachment/file-drop/file-drop.component.scss
Labels: risk level (author): 1, screenshot removed

#3533 ci: additional e2e error handling
  .cspell.json
  .github/actions/e2e-affected/action.yml
  .github/workflows/e2e.yml
  libs/sdk/e2e-schematics/package.json
  libs/sdk/e2e-schematics/src/workflow/percy-api/percy-api.spec.ts
  libs/sdk/e2e-schematics/src/workflow/percy-api/percy-api.ts
  libs/sdk/e2e-schematics/src/workflow/verify-e2e/verify-e2e.spec.ts
  libs/sdk/e2e-schematics/src/workflow/verify-e2e/verify-e2e.ts
  package-lock.json
  package.json
Labels: risk level (author): 1, skip e2e

#3537 feat: update v2 design tokens
  apps/e2e/forms-storybook-e2e/src/e2e/selection-box.component.cy.ts
  libs/components/theme/package.json
  package-lock.json
  package.json
Labels: risk level (author): 2

#3536 feat(components/theme): add serialization methods to theme
  libs/components/theme/src/lib/theming/theme-brand.spec.ts
  libs/components/theme/src/lib/theming/theme-brand.ts
  libs/components/theme/src/lib/theming/theme-mode.spec.ts
  libs/components/theme/src/lib/theming/theme-mode.ts
  libs/components/theme/src/lib/theming/theme-serialization-types.ts
  libs/components/theme/src/lib/theming/theme-settings.spec.ts
  libs/components/theme/src/lib/theming/theme-settings.ts
  libs/components/theme/src/lib/theming/theme-spacing.spec.ts
  libs/components/theme/src/lib/theming/theme-spacing.ts
  libs/components/theme/src/lib/theming/theme.spec.ts
  libs/components/theme/src/lib/theming/theme.ts
Labels: risk level (author): 2

#3528 fix(components/indicators): update `iconsize` to `xl` for alerts
  libs/components/indicators/src/lib/modules/alert/alert.component.html
  libs/components/indicators/src/lib/modules/alert/alert.modern.component.scss
Labels: risk level (author): 1

#3541 fix(components/ag-grid): add validator event handlers to the grid cell element
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-validator/ag-grid-cell-validator-tooltip.component.spec.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-validator/ag-grid-cell-validator-tooltip.component.ts
Labels: risk level (author): 1

#3546 fix: update input labels to use default color instead of deemphasized color
  libs/components/colorpicker/src/lib/modules/colorpicker/colorpicker.component.scss
  libs/components/forms/src/lib/modules/file-attachment/file-attachment/file-attachment.component.scss
  libs/components/forms/src/lib/modules/file-attachment/file-drop/file-drop.component.scss
  libs/components/forms/src/lib/modules/input-box/input-box.component.scss
  libs/components/text-editor/src/lib/modules/text-editor/text-editor.component.scss
Labels: risk level (author): 2

#3552 chore: fix nx formatting issues
  apps/e2e/forms-storybook-e2e/src/e2e/selection-box.component.cy.ts
  libs/components/ag-grid/src/lib/styles/_modern.scss
Labels: risk level (author): 1

#3544 feat: update tokens package
  libs/components/theme/package.json
  package-lock.json
  package.json
Labels: risk level (author): 1

#3557 feat: update tokens
  libs/components/theme/package.json
  package-lock.json
  package.json
Labels: risk level (author): 1

#3547 chore(components/filter-bar): add filter item component and begin filter modal workflow
  apps/e2e/filter-bar-storybook/src/app/filter-bar/filter-bar.component.html
  apps/e2e/filter-bar-storybook/src/app/filter-bar/filter-bar.component.ts
  apps/playground/src/app/components/filter-bar/filter-bar/filter-bar.component.ts
  apps/playground/src/app/components/filter-bar/filter-bar/test-modal.component.html
  apps/playground/src/app/components/filter-bar/filter-bar/test-modal.component.ts
  libs/components/filter-bar/src/index.ts
  libs/components/filter-bar/src/lib/modules/filter-bar/filter-bar-item.component.html
  libs/components/filter-bar/src/lib/modules/filter-bar/filter-bar-item.component.scss
  libs/components/filter-bar/src/lib/modules/filter-bar/filter-bar-item.component.spec.ts
  libs/components/filter-bar/src/lib/modules/filter-bar/filter-bar-item.component.ts
  libs/components/filter-bar/src/lib/modules/filter-bar/filter-bar.component.html
  libs/components/filter-bar/src/lib/modules/filter-bar/filter-bar.component.ts
  libs/components/filter-bar/src/lib/modules/filter-bar/fixtures/filter-bar.component.fixture.ts
  libs/components/filter-bar/src/lib/modules/filter-bar/models/filter-bar-filter-item.ts
  libs/components/filter-bar/src/lib/modules/filter-bar/models/filter-bar-filter-modal-config.ts
  libs/components/filter-bar/src/lib/modules/filter-bar/models/filter-bar-filter-modal-context.ts
  libs/components/filter-bar/src/lib/modules/filter-bar/models/filter-bar-filter-value.ts
  libs/components/filter-bar/src/lib/modules/filter-bar/models/filter-bar-filter.ts
Labels: risk level (author): 1

#3542 chore: release 12.23.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending
