Repository blackbaud/skyux, pull requests merged in 2025-09, with the labels that each got.

#3881 fix(sdk/skyux-stylelint): use correct documentation link for rules
  libs/sdk/skyux-stylelint/src/utility/meta.ts
Labels: risk level (author): 1

#3886 fix(sdk/skyux-stylelint): use correct documentation link for rules (#3881)
  libs/sdk/skyux-stylelint/src/utility/meta.ts
Labels: risk level (author): 1

#3889 fix: update tokens package, use correct tokens (#3880)
  libs/components/help-inline/src/lib/modules/help-inline/help-inline.modern.component.scss
  libs/components/split-view/src/lib/modules/split-view/split-view-drawer.component.scss
  libs/components/tabs/src/lib/modules/vertical-tabset/vertical-tabset.component.scss
  libs/components/theme/package.json
  package-lock.json
  package.json
Labels: risk level (author): 1

#3892 feat(components/select-field): create instructions to convert select-field to lookup (#3766)
  docs/migrating-deprecated-components/README.md
  docs/migrating-deprecated-components/select-field/README.md
Labels: risk level (author): 1, skip e2e

#3888 fix: viewkeeper and summary action bar use correct fallback values for css calculations using a fallback for a custom property
  apps/playground/src/app/components/popovers/dropdown/dropdown.component.ts
  libs/components/action-bars/src/lib/modules/summary-action-bar/summary-action-bar-adapter.service.ts
  libs/components/action-bars/src/lib/modules/summary-action-bar/summary-action-bar.component.spec.ts
  libs/components/core/src/lib/modules/viewkeeper/viewkeeper.spec.ts
  libs/components/core/src/lib/modules/viewkeeper/viewkeeper.ts
  libs/components/docs-tools/src/lib/modules/heading-anchor/heading-anchor.component.scss
  libs/components/split-view/src/lib/modules/split-view/split-view.component.spec.ts
Labels: risk level (author): 2

#3882 chore: release 13.0.0-alpha.9
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#3893 fix: viewkeeper and summary action bar use correct fallback values for css calculations using a fallback for a custom property (#3888)
  apps/playground/src/app/components/popovers/dropdown/dropdown.component.ts
  libs/components/action-bars/src/lib/modules/summary-action-bar/summary-action-bar-adapter.service.ts
  libs/components/action-bars/src/lib/modules/summary-action-bar/summary-action-bar.component.spec.ts
  libs/components/core/src/lib/modules/viewkeeper/viewkeeper.spec.ts
  libs/components/core/src/lib/modules/viewkeeper/viewkeeper.ts
  libs/components/docs-tools/src/lib/modules/heading-anchor/heading-anchor.component.scss
  libs/components/split-view/src/lib/modules/split-view/split-view.component.spec.ts
Labels: risk level (author): 2

#3894 chore: changelog for 12.38.0 (#3885) 🍒
  CHANGELOG.md
Labels: risk level (author): 1

#3899 fix(components/docs-tools): allow scrolling away from the anchor position (#3896)
  libs/components/docs-tools/src/lib/modules/table-of-contents/table-of-contents-page.component.ts
Labels: risk level (author): 1

#3890 fix(components/lookup): add transformations for boolean inputs
  apps/playground/src/app/components/components.module.ts
  apps/playground/src/app/components/select-field/select-field.component.css
  apps/playground/src/app/components/select-field/select-field.component.html
  apps/playground/src/app/components/select-field/select-field.component.spec.ts
  apps/playground/src/app/components/select-field/select-field.component.ts
  libs/components/lookup/src/lib/modules/lookup/lookup.component.ts
Labels: risk level (author): 1

#3895 feat(components/packages): create schematic to remove fixedWidth input on sky-icon
  libs/components/packages/migrations.json
  libs/components/packages/src/schematics/migrations/update-13/icon-name/icon-name.schematic.spec.ts
  libs/components/packages/src/schematics/migrations/update-13/icon-name/icon-name.schematic.ts
  libs/components/packages/src/schematics/utility/template.ts
Labels: risk level (author): 1, skip e2e

#3903 fix(components/manifest): include `ModelSignal` in directive properties metadata
  libs/components/manifest-generator/src/lib/__snapshots__/generate-manifest.test.ts.snap
  libs/components/manifest-generator/src/lib/utility/get-directive.ts
  libs/components/manifest-generator/src/testing/fixtures/example-packages/foo/src/lib/foo.component.ts
Labels: risk level (author): 1

#3905 fix(components/manifest): include `ModelSignal` in directive properties metadata (#3903)
  libs/components/manifest-generator/src/lib/__snapshots__/generate-manifest.test.ts.snap
  libs/components/manifest-generator/src/lib/utility/get-directive.ts
  libs/components/manifest-generator/src/testing/fixtures/example-packages/foo/src/lib/foo.component.ts
Labels: risk level (author): 1

#3904 fix(sdk/skyux-eslint): do not apply fix for `prefer-label-text` rule when label element uses control flow syntax
  libs/sdk/skyux-eslint/src/rules/template/prefer-label-text.spec.ts
  libs/sdk/skyux-eslint/src/rules/template/prefer-label-text.ts
  libs/sdk/skyux-eslint/src/rules/utils/ast-utils.ts
Labels: risk level (author): 1

#3906 fix(sdk/skyux-eslint): do not apply fix for `prefer-label-text` rule when label element uses control flow syntax (#3904)
  libs/sdk/skyux-eslint/src/rules/template/prefer-label-text.spec.ts
  libs/sdk/skyux-eslint/src/rules/template/prefer-label-text.ts
  libs/sdk/skyux-eslint/src/rules/utils/ast-utils.ts
Labels: risk level (author): 1

#3897 chore: release 12.38.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease 12.x.x: pending

#3909 chore: changelog for 12.38.1 (#3897) 🍒
  CHANGELOG.md
Labels: risk level (author): 1

#3907 feat(sdk/skyux-eslint): add `prefer-disabled-attr` rule
  libs/sdk/skyux-eslint/docs/rules/template/prefer-disabled-attr.md
  libs/sdk/skyux-eslint/src/configs/template-all.ts
  libs/sdk/skyux-eslint/src/plugins/template-plugin.ts
  libs/sdk/skyux-eslint/src/rules/template/prefer-disabled-attr.spec.ts
  libs/sdk/skyux-eslint/src/rules/template/prefer-disabled-attr.ts
Labels: risk level (author): 1

#3898 chore: release 13.0.0-alpha.10
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#3911 fix(components/packages): update format when converting `sky-page-summary-key-info` (#3901)
  libs/components/packages/src/schematics/rules/convert-page-summary-to-page-header/convert-page-summary-to-page-header.spec.ts
  libs/components/packages/src/schematics/rules/convert-page-summary-to-page-header/convert-page-summary-to-page-header.ts
Labels: risk level (author): 1, skip e2e

#3914 fix(components/layout): fix track expression error in text-expand-repeater (#3908)
  libs/components/layout/src/lib/modules/text-expand-repeater/text-expand-repeater.component.html
  libs/components/layout/src/lib/modules/text-expand-repeater/text-expand-repeater.component.ts
Labels: risk level (author): 1

#3915 fix(components/packages): update data view config icon when property is initialized later
  libs/components/packages/src/schematics/migrations/update-13/fix-imports/fix-imports.schematic.spec.ts
  libs/components/packages/src/schematics/migrations/update-13/fix-imports/fix-imports.schematic.ts
  libs/components/packages/src/schematics/migrations/update-13/icon-name/icon-name.schematic.spec.ts
  libs/components/packages/src/schematics/migrations/update-13/icon-name/icon-name.schematic.ts
Labels: risk level (author): 1, skip e2e

#3936 fix(components/packages): icon name schematic should handle exceptions
  libs/components/packages/src/schematics/migrations/update-13/icon-name/icon-name.schematic.spec.ts
  libs/components/packages/src/schematics/migrations/update-13/icon-name/icon-name.schematic.ts
Labels: risk level (author): 1

#3941 feat: use latest version of design tokens
  libs/components/theme/package.json
  package-lock.json
  package.json
Labels: risk level (author): 1

#3942 chore: release 12.41.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease 12.x.x: pending

#3946 chore: changelog for 12.41.0 (#3942) 🍒
  CHANGELOG.md
Labels: risk level (author): 1

#3943 chore: release 13.0.0-alpha.14
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#3947 chore: patch inquirer
  package-lock.json
Labels: risk level (author): 1

#3949 ci: update release please action to v4
  .github/workflows/release-please.yml
  release-please-config.json
Labels: risk level (author): 1

#3955 ci: fix release please
  .github/workflows/release-please.yml
  .release-please-manifest.json
  release-please-config.json
Labels: risk level (author): 1, skip e2e

#3956 feat: initial beta release
  .github/workflows/release-please.yml
  release-please-config.json
Labels: risk level (author): 1, skip e2e

#3957 ci: fix release please
  .github/workflows/release-please.yml
Labels: risk level (author): 1, skip e2e

#3958 ci: release please checkout
  .github/workflows/release-please.yml
Labels: risk level (author): 1, skip e2e

#3959 ci: release please version
  release-please-config.json
Labels: risk level (author): 1, skip e2e

#3969 ci: update manifest-path
  .release-please-manifest.json
Labels: risk level (author): 1, skip e2e

#3970 ci: include packages in config
  release-please-config.json
Labels: risk level (author): 1, skip e2e

#3973 chore: release 13.0.0-beta.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#3975 feat: release 13.0.0
  .github/workflows/release-please.yml
Labels: risk level (author): 1

#3977 ci: set `release-as` to "13.0.0"
  .github/workflows/release-please.yml
Labels: risk level (author): 1, skip e2e

#3980 fix(components/ag-grid): add JSDocs for cell editor params interfaces (#3939)
  libs/components/ag-grid/src/lib/modules/ag-grid/types/autocomplete-properties.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/types/cell-editor-autocomplete-params.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/types/cell-editor-currency-params.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/types/cell-editor-datepicker-params.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/types/cell-editor-lookup-params.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/types/cell-editor-number-params.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/types/cell-editor-text-params.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/types/cell-editor-utils.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/types/currency-properties.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/types/datepicker-properties.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/types/lookup-properties.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/types/number-properties.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/types/text-properties.ts
  libs/components/datetime/src/lib/modules/datepicker/datepicker-input.directive.ts
  libs/components/lookup/src/lib/modules/autocomplete/autocomplete.component.ts
  libs/components/lookup/src/lib/modules/lookup/lookup-autocomplete-adapter.ts
  libs/components/lookup/src/lib/modules/lookup/lookup.component.ts
Labels: risk level (author): 1

#3984 fix(components/theme): update missing custom properties for modern theme
  libs/components/theme/src/lib/styles/themes/modern/_custom-properties.scss
Labels: risk level (author): 1

#3982 ci: revert release please on 12.x.x
  .github/workflows/release-please.yml
  .release-please-manifest.json
  release-please-config.json
Labels: risk level (author): 1, skip e2e

#3990 chore: update changelog for 13.0.0
  CHANGELOG.md
Labels: risk level (author): 1

#3981 chore: release 13.0.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#3994 feat(components/icon): use v10 of icons
  libs/components/icon/src/lib/modules/icon/icon-svg-resolver.service.spec.ts
  libs/components/icon/src/lib/modules/icon/icon-svg-resolver.service.ts
  libs/components/packages/package.json
  package-lock.json
  package.json
Labels: risk level (author): 1

#3997 fix: downgrade required version of ag-grid
  libs/components/ag-grid/package.json
  libs/components/code-examples/package.json
  libs/components/packages/package.json
  package-lock.json
  package.json
Labels: risk level (author): 1

#3999 ci: fix release branch name
  .skyuxdev.json
Labels: risk level (author): 1, skip e2e

#3998 ci: use skyux-dev release (#3996)
  .github/actions/e2e-affected/action.yml
  .github/actions/nx-set-shas/action.yml
  .github/workflows/automated-translations.yml
  .github/workflows/cherry-pick.yml
  .github/workflows/ci.yml
  .github/workflows/e2e-check.yml
  .github/workflows/e2e-cleanup.yml
  .github/workflows/e2e.yml
  .github/workflows/release-please.yml
  .github/workflows/risk-assessment.yml
  .github/workflows/validate-pr.yml
  .skyuxdev.json
  .versionrc
  package-lock.json
  package.json
Labels: risk level (author): 1, skip e2e

#4004 fix(components/forms): validate file attachment on cancel and on blur when not opening file dialog
  libs/components/forms/src/lib/modules/file-attachment/file-attachment/file-attachment.component.html
  libs/components/forms/src/lib/modules/file-attachment/file-attachment/file-attachment.component.spec.ts
  libs/components/forms/src/lib/modules/file-attachment/file-attachment/file-attachment.component.ts
Labels: risk level (author): 3

#4006 fix: selected switch background should go to border edge
  libs/components/ag-grid/src/lib/styles/_base.scss
  libs/components/forms/src/lib/modules/toggle-switch/toggle-switch.component.scss
  libs/components/theme/src/lib/styles/themes/modern/_switch.scss
Labels: risk level (author): 1

#4008 fix(components/forms): file attachment file names are styled with `sky-btn-inline-link`
  libs/components/forms/src/lib/modules/file-attachment/file-attachment/file-attachment.component.html
Labels: risk level (author): 1
