Repository blackbaud/skyux, pull requests merged in 2025-10, with the labels that each got.

#3991 feat: add support for split view in a data manager docked in a page
  .github/instructions/code-examples-unit-testing.instructions.md
  apps/integration-e2e/src/e2e/page-data-manager-split-view.cy.ts
  apps/integration/src/app/app.component.ts
  apps/integration/src/app/integrations/integrations.module.ts
  apps/integration/src/app/integrations/page-data-manager-split-view/page-data-manager-split-view-routing.module.ts
  apps/integration/src/app/integrations/page-data-manager-split-view/page-data-manager-split-view.component.html
  apps/integration/src/app/integrations/page-data-manager-split-view/page-data-manager-split-view.component.scss
  apps/integration/src/app/integrations/page-data-manager-split-view/page-data-manager-split-view.component.spec.ts
  apps/integration/src/app/integrations/page-data-manager-split-view/page-data-manager-split-view.component.ts
  apps/integration/src/app/integrations/page-data-manager-split-view/page-data-manager-split-view.module.ts
  apps/playground/src/app/components/split-view/split-view/data-manager/record.ts
  apps/playground/src/app/components/split-view/split-view/data-manager/split-view-data-manager.component.html
  apps/playground/src/app/components/split-view/split-view/data-manager/split-view-data-manager.component.ts
  apps/playground/src/app/components/split-view/split-view/split-view-routing.module.ts
  apps/playground/src/app/components/split-view/split-view/split-view.module.ts
  libs/components/code-examples/src/index.ts
  libs/components/code-examples/src/lib/modules/pages/page/data-manager-split-view-fit-layout/example.component.html
  libs/components/code-examples/src/lib/modules/pages/page/data-manager-split-view-fit-layout/example.component.spec.ts
  libs/components/code-examples/src/lib/modules/pages/page/data-manager-split-view-fit-layout/example.component.ts
  libs/components/code-examples/src/lib/modules/pages/page/data-manager-split-view-fit-layout/record.ts
  libs/components/data-manager/documentation.json
  libs/components/data-manager/src/index.ts
  libs/components/data-manager/src/lib/modules/data-manager/data-manager.component.html
  libs/components/data-manager/src/lib/modules/data-manager/data-manager.component.scss
  libs/components/data-manager/src/lib/modules/data-manager/data-manager.component.spec.ts
  libs/components/data-manager/src/lib/modules/data-manager/data-manager.component.ts
  libs/components/data-manager/src/lib/modules/data-manager/fixtures/data-manager.component.fixture.html
  libs/components/data-manager/src/lib/modules/data-manager/fixtures/data-manager.component.fixture.ts
  libs/components/data-manager/src/lib/modules/data-manager/types/data-manager-dock-type.ts
  libs/components/data-manager/testing/src/modules/data-manager/data-manager-harness.spec.ts
  libs/components/data-manager/testing/src/modules/data-manager/data-manager-harness.ts
  libs/components/data-manager/testing/src/modules/data-manager/fixtures/data-manager-harness-test.component.html
  libs/components/data-manager/testing/src/modules/data-manager/fixtures/data-manager-harness-test.component.ts
  libs/components/pages/documentation.json
  libs/components/split-view/documentation.json
Labels: risk level (author): 3

#4017 feat(components/indicators): add help popover methods to key info harness
  libs/components/indicators/testing/src/modules/key-info/fixtures/key-info-harness-test.component.html
  libs/components/indicators/testing/src/modules/key-info/fixtures/key-info-harness-test.module.ts
  libs/components/indicators/testing/src/modules/key-info/key-info-harness.spec.ts
  libs/components/indicators/testing/src/modules/key-info/key-info-harness.ts
Labels: risk level (author): 1

#4012 chore: changelog for 12.42.0 (#4009) 🍒
  CHANGELOG.md
Labels: risk level (author): 1

#4019 fix(components/flyout): account for header height in flyout content height
  libs/components/flyout/src/lib/modules/flyout/flyout.component.scss
Labels: risk level (author): 1

#4018 fix(components/theme): properly default brand to blackbaud for modern theme
  libs/components/storybook/src/lib/preview-wrapper/preview-wrapper.component.spec.ts
  libs/components/theme/src/lib/theming/theme.service.spec.ts
  libs/components/theme/src/lib/theming/theme.service.ts
Labels: risk level (author): 2

#4023 ci: code example changes should trigger preview build
  libs/components/code-examples/project.json
  libs/components/manifest/project.json
Labels: risk level (author): 1
