Repository blackbaud/skyux, pull requests merged in 2025-04, with the labels that each got.

#3316 fix(sdk/skyux-eslint): set module resolution to "Node16" to address pathing issues with `@typescript-eslint/utils`
  libs/sdk/skyux-eslint/package.json
  libs/sdk/skyux-eslint/src/rules/template/no-deprecated-classnames.ts
  libs/sdk/skyux-eslint/src/rules/template/no-deprecated-directives.ts
  libs/sdk/skyux-eslint/src/rules/template/no-legacy-icons.ts
  libs/sdk/skyux-eslint/src/rules/template/no-radio-group-with-nested-list.ts
  libs/sdk/skyux-eslint/tsconfig.json
  package-lock.json
  package.json
Labels: risk level (author): 2

#3317 chore: release 12.0.0-beta.4
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: tagged

#3315 feat(components/lookup): add allowAnyValue and highlightSearchText to SkyAgGridAutocompleteProperties
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-editors/cell-editor-autocomplete/cell-editor-autocomplete.component.html
  libs/components/ag-grid/src/lib/modules/ag-grid/types/autocomplete-properties.ts
Labels: risk level (author): 1

#3323 fix: fix icon mapping for previous `usd` icon
  libs/components/packages/src/schematics/migrations/update-12/icon-name/icon-name-mappings.ts
  libs/sdk/skyux-eslint/src/rules/template/utils/no-legacy-icons-mappings.ts
Labels: risk level (author): 1

#3325 ci: fix e2e step exit code
  .github/workflows/e2e.yml
  apps/e2e/forms-storybook/src/app/field-group/field-group.component.ts
  apps/e2e/layout-storybook-e2e/src/e2e/page.component.cy.ts
  apps/e2e/pages-storybook/src/app/page/layouts/tabs-tile-dashboard-page/tabs-tile-dashboard-page.component.ts
  apps/e2e/tabs-storybook/src/app/sectioned-form/sectioned-form-address-form-demo.component.ts
  apps/e2e/tabs-storybook/src/app/sectioned-form/sectioned-form-date-form-demo.component.ts
  apps/e2e/tabs-storybook/src/app/sectioned-form/sectioned-form-information-form-demo.component.ts
  apps/e2e/tabs-storybook/src/app/sectioned-form/sectioned-form-modal.component.ts
  apps/e2e/tabs-storybook/src/app/sectioned-form/sectioned-form-phone-form-demo.component.ts
  apps/integration-e2e/src/e2e/modal-colorpicker.cy.ts
  apps/integration/src/app/integrations/modal-colorpicker/modal-colorpicker.component.ts
  apps/integration/src/app/integrations/modal-date-range-picker/modal-date-range-picker.component.ts
  apps/playground/src/app/components/ag-grid/data-manager/data-manager-paged-items.pipe.ts
  apps/playground/src/app/components/ag-grid/edit-complex-cells/action/action.component.ts
  apps/playground/src/app/components/ag-grid/edit-complex-cells/custom-multiline/custom-multiline.component.ts
  apps/playground/src/app/components/ag-grid/edit-complex-cells/edit-complex-cells-in-modal.component.ts
  apps/playground/src/app/components/ag-grid/readonly-grid/readonly-grid-in-modal.component.ts
  apps/playground/src/app/components/core/live-announcer/live-announcer.component.ts
  apps/playground/src/app/components/core/media-query/basic/media-query.component.ts
  apps/playground/src/app/components/datetime/key-dates/key-dates.component.ts
  apps/playground/src/app/components/modal/layout/fit/demosplitview.component.ts
  apps/playground/src/app/components/modal/layout/fit/modal.component.ts
  apps/playground/src/app/components/modal/standalone/modal-opener.component.ts
  apps/playground/src/app/components/tabs/sectioned-form/sectioned-form-address-form-demo.component.ts
  apps/playground/src/app/components/tabs/sectioned-form/sectioned-form-phone-form-demo.component.ts
  apps/playground/src/app/components/text-editor/text-editor-series/text-editor-series.component.ts
  apps/playground/src/app/components/theme/viewport-service/viewport-service.component.ts
  apps/playground/src/app/components/toast/toast/toast-body.component.ts
  apps/playground/src/app/shared/lipsum/lipsum.component.ts
Labels: risk level (author): 1, skip e2e

#3328 chore: release 11.49.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease 11.x.x: pending

#3330 chore: changelog for 11.49.1 (#3328) 🍒
  CHANGELOG.md
Labels: risk level (author): 1, risk level (reviewer): 1

#3327 fix(components/tabs): accessibility tests for sectioned-form in mobile view (#3326)
  libs/components/tabs/src/lib/modules/sectioned-form/sectioned-form.component.html
  libs/components/tabs/src/lib/modules/sectioned-form/sectioned-form.component.spec.ts
  libs/components/tabs/src/lib/modules/vertical-tabset/vertical-tabset.component.html
  libs/components/tabs/src/lib/modules/vertical-tabset/vertical-tabset.component.spec.ts
Labels: risk level (author): 1

#3322 fix(components/docs-tools): set correct path for type definition anchor links
  libs/components/docs-tools/src/lib/modules/type-definition/pipes/type-anchor-links.pipe.ts
Labels: risk level (author): 2

#3329 fix(components/packages): only set `size` on icon component if `iconSize` not set
  libs/components/packages/src/schematics/migrations/update-12/icons-size/icons-size.schematic.spec.ts
  libs/components/packages/src/schematics/migrations/update-12/icons-size/icons-size.schematic.ts
Labels: risk level (author): 2

#3333 feat: release 12.0.0
  .github/workflows/release-please.yml
Labels: risk level (author): 1

#3335 fix(components/packages): harden migration collection versions
  libs/components/packages/src/schematics/migrations/migration-collection.json
Labels: risk level (author): 1

#3318 chore(components/ag-grid): reduce false failures in visual tests
  apps/e2e/ag-grid-storybook-e2e/src/e2e/data-entry-grid.component.cy.ts
  apps/e2e/ag-grid-storybook-e2e/src/e2e/data-manager.component.cy.ts
  libs/sdk/cypress-commands/src/lib/visual-test-command.ts
Labels: risk level (author): 2

#3332 fix(components/ag-grid): hide AG Grid row dragging icon
  apps/playground/src/app/components/ag-grid/data-manager-large/data-manager-large.component.ts
  libs/components/ag-grid/src/lib/styles/_base.scss
Labels: risk level (author): 1

#3341 fix(components/ag-grid): hide AG Grid row dragging icon (#3332)
  apps/playground/src/app/components/ag-grid/data-manager-large/data-manager-large.component.ts
  libs/components/ag-grid/src/lib/styles/_base.scss
Labels: risk level (author): 1

#3338 feat(components/tabs): tokenize wizard styles
  apps/e2e/tabs-storybook-e2e/src/e2e/wizard.component.cy.ts
  libs/components/tabs/src/lib/modules/tabs/tabset.component.scss
Labels: risk level (author): 2

#3324 feat(components/lists): tokenize paging styles
  apps/e2e/lists-storybook-e2e/src/e2e/paging.component.cy.ts
  libs/components/lists/src/lib/modules/paging/paging.component.html
  libs/components/lists/src/lib/modules/paging/paging.component.scss
Labels: risk level (author): 2

#3345 fix: use correct icon and best practices in code examples
  libs/components/code-examples/src/lib/modules/ag-grid/data-entry-grid/data-manager-added/view-grid.component.ts
  libs/components/code-examples/src/lib/modules/ag-grid/data-grid/data-manager-multiselect/view-grid.component.ts
  libs/components/code-examples/src/lib/modules/ag-grid/data-grid/data-manager/view-grid.component.ts
  libs/components/code-examples/src/lib/modules/data-manager/data-manager/basic/view-grid.component.ts
  libs/components/code-examples/src/lib/modules/data-manager/data-manager/basic/view-repeater.component.ts
  libs/components/code-examples/src/lib/modules/icon/icon-button/example.component.html
  libs/components/code-examples/src/lib/modules/layout/toolbar/sectioned/example.component.html
Labels: risk level (author): 1

#3348 fix(components/icon): ensure icon colors work in Firefox
  libs/components/icon/src/lib/modules/icon/icon-svg.component.scss
  libs/components/icon/src/lib/modules/icon/icon-svg.component.spec.ts
  libs/components/theme/src/lib/styles/_theme.scss
Labels: risk level (author): 1

#3337 chore: release 12.1.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#3351 fix(components/code-examples): selection modal add item example uses correct button classes and order
  libs/components/code-examples/src/lib/modules/lookup/selection-modal/add-item/add-item-modal.component.html
Labels: risk level (author): 1

#3339 fix(components/indicators): block-level wait should not overlap other elements
  apps/playground/src/app/components/indicators/wait/wait.component.css
  apps/playground/src/app/components/indicators/wait/wait.component.html
  apps/playground/src/app/components/indicators/wait/wait.component.ts
  libs/components/indicators/src/lib/modules/wait/fixtures/wait.component.fixture.html
  libs/components/indicators/src/lib/modules/wait/fixtures/wait.component.fixture.ts
  libs/components/indicators/src/lib/modules/wait/wait-adapter.service.ts
  libs/components/indicators/src/lib/modules/wait/wait.component.spec.ts
  libs/components/theme/src/lib/styles/_theme.scss
Labels: risk level (author): 1

#3352 fix(components/icon): apply fill color to all child elements of icon symbol
  libs/components/theme/src/lib/styles/_theme.scss
Labels: risk level (author): 1

#3347 fix(components/manifest): add support for directive input properties with type `InputSignalWithTransform`
  libs/components/manifest-generator/src/lib/__snapshots__/generate-manifest.test.ts.snap
  libs/components/manifest-generator/src/lib/utility/get-directive.ts
  libs/components/manifest-generator/src/testing/fixtures/example-packages/foo/src/lib/foo.component.ts
Labels: risk level (author): 1

#3355 fix(components/docs-tools): add "static" keyword to static class property definitions
  libs/components/docs-tools/src/lib/modules/type-definition/pipes/property-name.pipe.ts
  libs/components/docs-tools/src/lib/modules/type-definition/pipes/type-anchor-links.pipe.ts
Labels: risk level (author): 2

#3353 chore(apps/code-examples-playground): save selected documentation group as URL param
  apps/code-examples/src/app/home/home.component.html
  apps/code-examples/src/app/home/home.component.ts
Labels: risk level (author): 1

#3357 feat(components/manifest): add support for `typedoc@0.28.2`
  libs/components/manifest-generator/package.json
  libs/components/manifest-generator/src/lib/__snapshots__/generate-manifest.test.ts.snap
  libs/components/manifest-generator/src/lib/utility/format-type-custom.ts
  libs/components/manifest-generator/src/lib/utility/format-type.ts
  package-lock.json
  package.json
Labels: risk level (author): 2

#3340 fix(components/data-manager): toolbar should not overlap other elements
  libs/components/core/src/lib/modules/viewkeeper/viewkeeper.ts
  libs/components/theme/src/lib/styles/_custom-properties.scss
  libs/components/theme/src/lib/styles/_theme.scss
  libs/components/theme/src/lib/styles/themes/modern/_custom-properties.scss
Labels: risk level (author): 1

#3342 chore: release 11.49.2
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease 11.x.x: pending

#3360 chore: changelog for 11.49.2 (#3342) 🍒
  CHANGELOG.md
Labels: risk level (author): 1, risk level (reviewer): 1

#3358 feat(components/config): add `containerAliases` to `remoteModules` config
  libs/components/config/src/lib/config-remote-container-reference.ts
  libs/components/config/src/lib/config-remote-modules.ts
Labels: risk level (author): 2

#3349 fix(components/manifest): add more granular control when adding `@docsIds` to documentation groups
  libs/components/action-bars/documentation.json
  libs/components/ag-grid/documentation.json
  libs/components/angular-tree-component/documentation.json
  libs/components/autonumeric/documentation.json
  libs/components/avatar/documentation.json
  libs/components/colorpicker/documentation.json
  libs/components/core/documentation.json
  libs/components/data-manager/documentation.json
  libs/components/data-manager/src/index.ts
  libs/components/datetime/documentation.json
  libs/components/errors/documentation.json
  libs/components/flyout/documentation.json
  libs/components/forms/documentation.json
  libs/components/grids/documentation.json
  libs/components/help-inline/documentation.json
  libs/components/icon/documentation.json
  libs/components/indicators/documentation.json
  libs/components/inline-form/documentation.json
  libs/components/layout/documentation.json
  libs/components/list-builder-view-checklist/documentation.json
  libs/components/list-builder-view-grids/documentation.json
  libs/components/list-builder/documentation.json
  libs/components/lists/documentation.json
  libs/components/lookup/documentation.json
  libs/components/manifest-generator/documentation-schema.json
  libs/components/manifest-generator/src/lib/__snapshots__/generate-manifest.test.ts.snap
  libs/components/manifest-generator/src/lib/validations.ts
  libs/components/manifest-generator/src/testing/fixtures/example-packages/foo/documentation.json
  libs/components/manifest-generator/src/testing/fixtures/example-packages/invalid-code-examples/documentation.json
  libs/components/manifest-generator/src/testing/fixtures/example-packages/invalid-documentation-json/documentation.json
  libs/components/manifest/documentation-schema.json
  libs/components/manifest/src/__snapshots__/get-documentation-group.test.ts.snap
  libs/components/manifest/src/get-documentation-config.test.ts
  libs/components/manifest/src/get-documentation-group.test.ts
  libs/components/manifest/src/get-documentation-group.ts
  libs/components/manifest/src/types/documentation-config.ts
  libs/components/modals/documentation.json
  libs/components/navbar/documentation.json
  libs/components/pages/documentation.json
  libs/components/phone-field/documentation.json
  libs/components/popovers/documentation.json
  libs/components/progress-indicator/documentation.json
  libs/components/router/documentation.json
  libs/components/select-field/documentation.json
  libs/components/split-view/documentation.json
  libs/components/tabs/documentation.json
  libs/components/text-editor/documentation.json
  libs/components/theme/documentation.json
  libs/components/tiles/documentation.json
  libs/components/toast/documentation.json
  libs/components/validation/documentation.json
Labels: risk level (author): 2

#3350 chore: release 12.2.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#3364 chore(apps/playground): add selection box playground page
  apps/playground/src/app/components/forms/forms.module.ts
  apps/playground/src/app/components/forms/selection-box/selection-box-routing.module.ts
  apps/playground/src/app/components/forms/selection-box/selection-box.component.html
  apps/playground/src/app/components/forms/selection-box/selection-box.component.ts
  apps/playground/src/app/components/forms/selection-box/selection-box.module.ts
Labels: risk level (author): 1

#3362 feat(components/tiles): tokenize tile styles
  apps/e2e/tiles-storybook-e2e/src/e2e/tile-dashboard.component.cy.ts
  libs/components/core/src/lib/modules/dynamic-component/dynamic-component-options.ts
  libs/components/core/src/lib/modules/dynamic-component/dynamic-component.service.spec.ts
  libs/components/core/src/lib/modules/dynamic-component/dynamic-component.service.ts
  libs/components/theme/src/lib/styles/themes/modern/_buttons.scss
  libs/components/tiles/src/lib/modules/tiles/tile-content/tile-content-section.component.html
  libs/components/tiles/src/lib/modules/tiles/tile-content/tile-content-section.component.scss
  libs/components/tiles/src/lib/modules/tiles/tile-dashboard-column/tile-dashboard-column.component.scss
  libs/components/tiles/src/lib/modules/tiles/tile-dashboard-column/tile-dashboard-column.component.ts
  libs/components/tiles/src/lib/modules/tiles/tile-dashboard/tile-dashboard.component.scss
  libs/components/tiles/src/lib/modules/tiles/tile-dashboard/tile-dashboard.component.ts
  libs/components/tiles/src/lib/modules/tiles/tile-dashboard/tile-dashboard.service.ts
  libs/components/tiles/src/lib/modules/tiles/tile/tile.component.html
  libs/components/tiles/src/lib/modules/tiles/tile/tile.component.scss
Labels: risk level (author): 2

#3368 fix(components/theme): darken borderless icon button color in default theme to handle new svg icons
  libs/components/indicators/src/lib/modules/chevron/chevron.default.component.scss
  libs/components/indicators/src/lib/modules/expansion-indicator/expansion-indicator.component.scss
  libs/components/tabs/src/lib/modules/vertical-tabset/vertical-tab.component.scss
  libs/components/theme/src/lib/styles/_public-api/_compat/_mixins.scss
Labels: risk level (author): 2

#3361 feat(components/datetime): add timepicker harnesses
  libs/components/code-examples/src/lib/modules/datetime/timepicker/basic/example.component.html
  libs/components/code-examples/src/lib/modules/datetime/timepicker/basic/example.component.spec.ts
  libs/components/code-examples/src/lib/modules/datetime/timepicker/basic/example.component.ts
  libs/components/datetime/src/lib/modules/timepicker/timepicker.component.html
  libs/components/datetime/src/lib/modules/timepicker/timepicker.component.spec.ts
  libs/components/datetime/src/lib/modules/timepicker/timepicker.component.ts
  libs/components/datetime/src/lib/modules/timepicker/timepicker.directive.ts
  libs/components/datetime/testing/src/modules/timepicker/timepicker-harness-filters.ts
  libs/components/datetime/testing/src/modules/timepicker/timepicker-harness.spec.ts
  libs/components/datetime/testing/src/modules/timepicker/timepicker-harness.ts
  libs/components/datetime/testing/src/modules/timepicker/timepicker-input-harness.ts
  libs/components/datetime/testing/src/modules/timepicker/timepicker-selector-column-harness.ts
  libs/components/datetime/testing/src/modules/timepicker/timepicker-selector-harness-filters.ts
  libs/components/datetime/testing/src/modules/timepicker/timepicker-selector-harness.ts
  libs/components/datetime/testing/src/public-api.ts
Labels: risk level (author): 1

#3366 feat(components/forms): add toggle switch harness
  libs/components/code-examples/src/lib/modules/forms/toggle-switch/basic/example.component.html
  libs/components/code-examples/src/lib/modules/forms/toggle-switch/basic/example.component.spec.ts
  libs/components/code-examples/src/lib/modules/forms/toggle-switch/help-key/example.component.html
  libs/components/code-examples/src/lib/modules/forms/toggle-switch/help-key/example.component.spec.ts
  libs/components/forms/src/lib/modules/toggle-switch/toggle-switch.component.html
  libs/components/forms/testing/src/modules/checkbox/checkbox-harness.spec.ts
  libs/components/forms/testing/src/modules/checkbox/checkbox-harness.ts
  libs/components/forms/testing/src/modules/radio/radio-harness.spec.ts
  libs/components/forms/testing/src/modules/radio/radio-harness.ts
  libs/components/forms/testing/src/modules/toggle-switch/fixtures/toggle-switch-harness-test.component.html
  libs/components/forms/testing/src/modules/toggle-switch/fixtures/toggle-switch-harness-test.component.ts
  libs/components/forms/testing/src/modules/toggle-switch/toggle-switch-harness-filters.ts
  libs/components/forms/testing/src/modules/toggle-switch/toggle-switch-harness.spec.ts
  libs/components/forms/testing/src/modules/toggle-switch/toggle-switch-harness.ts
  libs/components/forms/testing/src/modules/toggle-switch/toggle-switch-label-harness.ts
  libs/components/forms/testing/src/public-api.ts
Labels: risk level (author): 1

#3369 fix(components/tabs): adjust aria roles in mobile
  libs/components/tabs/src/lib/modules/vertical-tabset/vertical-tab.component.html
  libs/components/tabs/src/lib/modules/vertical-tabset/vertical-tabset.component.html
  libs/components/tabs/src/lib/modules/vertical-tabset/vertical-tabset.component.spec.ts
Labels: risk level (author): 1

#3365 chore: release 12.3.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#3370 fix: add missing harness classes to documentation schema
  libs/components/data-manager/documentation.json
  libs/components/datetime/documentation.json
  libs/components/errors/documentation.json
  libs/components/flyout/documentation.json
  libs/components/forms/documentation.json
  libs/components/indicators/documentation.json
  libs/components/layout/documentation.json
  libs/components/lists/documentation.json
  libs/components/tabs/documentation.json
  libs/components/toast/documentation.json
Labels: risk level (author): 1

#3367 feat(components/action-bars): add summary action bar harness
  libs/components/action-bars/documentation.json
  libs/components/action-bars/package.json
  libs/components/action-bars/project.json
  libs/components/action-bars/testing/src/modules/summary-action-bar/summary-action-bar-cancel-harness-filters.ts
  libs/components/action-bars/testing/src/modules/summary-action-bar/summary-action-bar-cancel-harness.ts
  libs/components/action-bars/testing/src/modules/summary-action-bar/summary-action-bar-harness-filters.ts
  libs/components/action-bars/testing/src/modules/summary-action-bar/summary-action-bar-harness.spec.ts
  libs/components/action-bars/testing/src/modules/summary-action-bar/summary-action-bar-harness.ts
  libs/components/action-bars/testing/src/modules/summary-action-bar/summary-action-bar-primary-action-harness-filters.ts
  libs/components/action-bars/testing/src/modules/summary-action-bar/summary-action-bar-primary-action-harness.ts
  libs/components/action-bars/testing/src/modules/summary-action-bar/summary-action-bar-secondary-action-harness-filters.ts
  libs/components/action-bars/testing/src/modules/summary-action-bar/summary-action-bar-secondary-action-harness.ts
  libs/components/action-bars/testing/src/modules/summary-action-bar/summary-action-bar-secondary-actions-harness-filters.ts
  libs/components/action-bars/testing/src/modules/summary-action-bar/summary-action-bar-secondary-actions-harness.ts
  libs/components/action-bars/testing/src/modules/summary-action-bar/summary-action-bar-summary-harness-filters.ts
  libs/components/action-bars/testing/src/modules/summary-action-bar/summary-action-bar-summary-harness.ts
  libs/components/action-bars/testing/src/public-api.ts
  libs/components/code-examples/src/lib/modules/action-bars/summary-action-bar/basic/example.component.html
  libs/components/code-examples/src/lib/modules/action-bars/summary-action-bar/basic/example.component.spec.ts
  libs/components/code-examples/src/lib/modules/action-bars/summary-action-bar/basic/example.component.ts
  libs/components/code-examples/src/lib/modules/action-bars/summary-action-bar/modal/modal.component.html
  libs/components/code-examples/src/lib/modules/action-bars/summary-action-bar/modal/modal.component.spec.ts
  libs/components/code-examples/src/lib/modules/action-bars/summary-action-bar/modal/modal.component.ts
  libs/components/code-examples/src/lib/modules/action-bars/summary-action-bar/tab/example.component.html
  libs/components/code-examples/src/lib/modules/action-bars/summary-action-bar/tab/example.component.spec.ts
  libs/components/code-examples/src/lib/modules/action-bars/summary-action-bar/tab/example.component.ts
  libs/components/code-examples/src/lib/modules/datetime/datepicker/custom-dates/example.component.ts
  libs/components/code-examples/src/lib/modules/modals/modal/basic-with-controller/example.component.ts
  libs/components/code-examples/src/lib/modules/tabs/tabs/dynamic-add-close/example.component.html
  libs/components/code-examples/src/lib/modules/tabs/tabs/dynamic-add-close/example.component.spec.ts
  libs/components/code-examples/src/lib/modules/tabs/tabs/dynamic/example.component.html
  libs/components/code-examples/src/lib/modules/tabs/tabs/dynamic/example.component.spec.ts
  libs/components/code-examples/src/lib/modules/tabs/tabs/static-add-close/example.component.html
  libs/components/code-examples/src/lib/modules/tabs/tabs/static-add-close/example.component.spec.ts
  libs/components/code-examples/src/lib/modules/tabs/tabs/static-add-close/example.component.ts
  libs/components/code-examples/src/lib/modules/tabs/tabs/static/example.component.html
  libs/components/code-examples/src/lib/modules/tabs/tabs/static/example.component.spec.ts
  libs/components/tabs/testing/src/modules/vertical-tabset/vertical-tabset-group-harness.ts
Labels: risk level (author): 1

#3373 fix(components/datetime): enable resetting fuzzy datepickers initialized with `undefined` after a value change
  libs/components/datetime/src/lib/modules/datepicker/fuzzy/datepicker-input-fuzzy.directive.ts
  libs/components/datetime/src/lib/modules/datepicker/fuzzy/fuzzy-datepicker.component.spec.ts
Labels: risk level (author): 2

#3374 fix: correct errors in test file manifests
  libs/components/data-manager/documentation.json
  libs/components/errors/testing/src/public-api.ts
  libs/components/tabs/documentation.json
Labels: risk level (author): 1

#3375 fix(sdk/skyux-eslint): export plugins to public API
  libs/sdk/skyux-eslint/src/index.ts
Labels: risk level (author): 1

#3371 chore: release 12.4.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#3380 feat(components/forms): add method to `SkyFormErrorHarness` to get error text (#2992) (#2994)
  libs/components/forms/testing/src/modules/form-error/form-error-harness.spec.ts
  libs/components/forms/testing/src/modules/form-error/form-error-harness.ts
Labels: risk level (author): 1

#3379 chore: release 12.5.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#3372 feat(components/layout): add text expand repeater harness
  libs/components/code-examples/src/lib/modules/layout/text-expand-repeater/example.component.spec.ts
  libs/components/layout/documentation.json
  libs/components/layout/testing/src/modules/text-expand-repeater/fixtures/text-expand-repeater-harness-test.component.html
  libs/components/layout/testing/src/modules/text-expand-repeater/fixtures/text-expand-repeater-harness-test.component.ts
  libs/components/layout/testing/src/modules/text-expand-repeater/text-expand-repeater-harness-filters.ts
  libs/components/layout/testing/src/modules/text-expand-repeater/text-expand-repeater-harness.spec.ts
  libs/components/layout/testing/src/modules/text-expand-repeater/text-expand-repeater-harness.ts
  libs/components/layout/testing/src/modules/text-expand-repeater/text-expand-repeater-item-harness.ts
  libs/components/layout/testing/src/public-api.ts
Labels: risk level (author): 1

#3363 feat(components/modals): tokenize modal styles
  apps/e2e/modals-storybook-e2e/src/e2e/modal.component.cy.ts
  libs/components/core/src/lib/modules/scroll-shadow/scroll-shadow.directive.spec.ts
  libs/components/core/src/lib/modules/scroll-shadow/scroll-shadow.directive.ts
  libs/components/modals/src/lib/modules/modal/modal-component-adapter.service.ts
  libs/components/modals/src/lib/modules/modal/modal-content.component.scss
  libs/components/modals/src/lib/modules/modal/modal-footer.component.html
  libs/components/modals/src/lib/modules/modal/modal-footer.component.scss
  libs/components/modals/src/lib/modules/modal/modal-header.component.scss
  libs/components/modals/src/lib/modules/modal/modal-host.component.scss
  libs/components/modals/src/lib/modules/modal/modal.component.html
  libs/components/modals/src/lib/modules/modal/modal.component.scss
  libs/components/modals/src/lib/modules/modal/modal.component.spec.ts
  libs/components/modals/src/lib/modules/modal/modal.component.ts
  libs/components/theme/package.json
  package-lock.json
  package.json
Labels: risk level (author): 2

#3385 feat(components/layout): tokenize back to top styles
  apps/e2e/layout-storybook-e2e/src/e2e/back-to-top.component.cy.ts
  libs/components/layout/src/lib/modules/back-to-top/back-to-top.component.scss
Labels: risk level (author): 2

#3384 feat(components/theme): add block button styles
  apps/e2e/theme-storybook/src/app/buttons/buttons.component.html
  apps/e2e/theme-storybook/src/app/buttons/buttons.component.ts
  apps/e2e/theme-storybook/src/app/buttons/buttons.module.ts
  apps/playground/src/app/components/theme/buttons/buttons.component.html
  apps/playground/src/app/components/theme/buttons/buttons.component.scss
  apps/playground/src/app/components/theme/buttons/buttons.component.ts
  apps/playground/src/app/components/theme/buttons/buttons.module.ts
  libs/components/theme/src/lib/styles/_buttons.scss
  libs/components/theme/src/lib/styles/_theme.scss
  libs/components/theme/src/lib/styles/themes/modern/_buttons.scss
Labels: risk level (author): 2

#3386 fix(sdk/skyux-eslint): ignore `sky-page` for `no-deprecated-directives` rule
  libs/sdk/skyux-eslint/src/rules/template/no-deprecated-directives.spec.ts
  libs/sdk/skyux-eslint/src/rules/template/utils/get-deprecated-template-features.ts
Labels: risk level (author): 1

#3383 fix(components/ag-grid): row delete directive should not block async tests
  apps/playground/src/app/components/ag-grid/readonly-grid/readonly-grid.component.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/ag-grid-row-delete-context.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/ag-grid-row-delete.component.css
  libs/components/ag-grid/src/lib/modules/ag-grid/ag-grid-row-delete.component.html
  libs/components/ag-grid/src/lib/modules/ag-grid/ag-grid-row-delete.component.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/ag-grid-row-delete.directive.spec.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/ag-grid-row-delete.directive.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-renderers/cell-renderer-row-selector/cell-renderer-row-selector.component.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/fixtures/ag-grid-row-delete.component.fixture.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/header/header-group.component.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/header/header.component.ts
  libs/components/core/src/lib/modules/scrollable-host/fixtures/scrollable-host.component.fixture.html
  libs/components/core/src/lib/modules/scrollable-host/fixtures/scrollable-host.component.fixture.scss
  libs/components/core/src/lib/modules/scrollable-host/scrollable-host.service.spec.ts
  libs/components/core/src/lib/modules/scrollable-host/scrollable-host.service.ts
Labels: risk level (author): 2, risk level (reviewer): 4

#3381 chore: release 12.6.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#3387 feat(components/modals): tokenize confirm modal styles
  apps/e2e/modals-storybook-e2e/src/e2e/confirm.component.cy.ts
  libs/components/modals/src/lib/modules/confirm/confirm.component.html
  libs/components/modals/src/lib/modules/confirm/confirm.component.scss
Labels: risk level (author): 1

#3388 feat(components/tabs): add wizard test harness
  .cspell.json
  libs/components/code-examples/src/lib/modules/tabs/wizard/basic/modal.component.html
  libs/components/code-examples/src/lib/modules/tabs/wizard/basic/modal.component.spec.ts
  libs/components/code-examples/src/lib/modules/tabs/wizard/basic/modal.component.ts
  libs/components/tabs/documentation.json
  libs/components/tabs/src/lib/modules/tabs/tabset-nav-button.component.ts
  libs/components/tabs/src/lib/modules/tabs/tabset.component.ts
  libs/components/tabs/testing/src/modules/tabs/tab-button-harness.ts
  libs/components/tabs/testing/src/modules/tabs/tabset-harness.spec.ts
  libs/components/tabs/testing/src/modules/tabs/tabset-harness.ts
  libs/components/tabs/testing/src/modules/tabs/tabset-nav-button-harness-filters.ts
  libs/components/tabs/testing/src/modules/tabs/tabset-nav-button-harness.ts
  libs/components/tabs/testing/src/public-api.ts
Labels: risk level (author): 1

#3392 feat(components/lookup): tokenize selection modal styles
  libs/components/lists/src/lib/modules/repeater/repeater-item.component.scss
  libs/components/lookup/src/lib/modules/selection-modal/selection-modal.component.scss
Labels: risk level (author): 1

#3391 fix(components/ag-grid): row delete overlay should not require overflow style rule
  libs/components/core/src/lib/modules/scrollable-host/fixtures/scrollable-host.component.fixture.scss
  libs/components/core/src/lib/modules/scrollable-host/scrollable-host.service.spec.ts
  libs/components/core/src/lib/modules/scrollable-host/scrollable-host.service.ts
Labels: risk level (author): 1

#3390 chore: release 12.7.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#3398 fix(sdk/prettier-schematics): add support for workspaces with library projects using ESLint flat config
  libs/sdk/prettier-schematics/collection.json
  libs/sdk/prettier-schematics/src/schematics/ng-add/ng-add.schematic.spec.ts
  libs/sdk/prettier-schematics/src/schematics/ng-add/rules/configure-eslint.ts
  libs/sdk/prettier-schematics/src/schematics/testing/scaffold.ts
Labels: risk level (author): 2

#3395 feat(sdk/skyux-eslint): create `@skyux-sdk/eslint-schematics` library
  .github/workflows/validate-pr.yml
  libs/components/packages/package.json
  libs/sdk/eslint-schematics/README.md
  libs/sdk/eslint-schematics/collection.json
  libs/sdk/eslint-schematics/eslint.config.cjs
  libs/sdk/eslint-schematics/jest.config.ts
  libs/sdk/eslint-schematics/migrations.json
  libs/sdk/eslint-schematics/package.json
  libs/sdk/eslint-schematics/project.json
  libs/sdk/eslint-schematics/src/schematics/migrations/noop/noop.schematic.ts
  libs/sdk/eslint-schematics/src/schematics/ng-add/ng-add.schematic.spec.ts
  libs/sdk/eslint-schematics/src/schematics/ng-add/ng-add.schematic.ts
  libs/sdk/eslint-schematics/src/schematics/ng-add/schema.json
  libs/sdk/eslint-schematics/src/schematics/testing/scaffold.ts
  libs/sdk/eslint-schematics/tsconfig.json
  libs/sdk/eslint-schematics/tsconfig.lib.json
  libs/sdk/eslint-schematics/tsconfig.spec.json
  libs/sdk/skyux-eslint/package.json
  package-lock.json
  package.json
  tsconfig.base.json
Labels: risk level (author): 2

#3396 chore: release 12.8.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#3400 fix(components/layout): update deprecation guidance for page summary component
  libs/components/layout/src/lib/modules/page-summary/page-summary.component.ts
Labels: risk level (author): 1

#3402 fix(sdk/eslint-schematics): make `ng-add` schematic idempotent
  libs/sdk/eslint-schematics/src/schematics/ng-add/ng-add.schematic.spec.ts
  libs/sdk/eslint-schematics/src/schematics/ng-add/ng-add.schematic.ts
Labels: risk level (author): 1

#3406 fix(components/code-examples): add `@skyux/ag-grid` styles to code examples
  libs/components/docs-tools/src/lib/modules/code-example-viewer/stackblitz.service.spec.ts
  libs/components/docs-tools/src/lib/modules/code-example-viewer/stackblitz.service.ts
Labels: risk level (author): 1

#3408 chore: address flaky ag-grid visual tests
  apps/e2e/ag-grid-storybook-e2e/src/e2e/data-manager.component.cy.ts
Labels: risk level (author): 1

#3404 fix(sdk/prettier-schematics): add support for `eslint-config-prettier@^10.1.2` and ESM config files
  libs/sdk/prettier-schematics/package.json
  libs/sdk/prettier-schematics/src/schematics/ng-add/ng-add.schematic.spec.ts
  libs/sdk/prettier-schematics/src/schematics/ng-add/ng-add.schematic.ts
  libs/sdk/prettier-schematics/src/schematics/ng-add/rules/add-prettier-dependencies.ts
  libs/sdk/prettier-schematics/src/schematics/ng-add/rules/configure-eslint.ts
  libs/sdk/prettier-schematics/src/schematics/utility/get-eslint-config-file.ts
Labels: risk level (author): 2, risk level (reviewer): 2

#3405 fix(sdk/eslint-schematics): add support for ESM config files
  libs/sdk/eslint-schematics/src/schematics/ng-add/ng-add.schematic.spec.ts
  libs/sdk/eslint-schematics/src/schematics/ng-add/ng-add.schematic.ts
Labels: risk level (author): 2, risk level (reviewer): 2

#3399 feat(components/angular-tree-component): tokenize tree view styles
  apps/e2e/angular-tree-component-storybook-e2e/src/e2e/angular-tree-component.component.cy.ts
  apps/playground/src/app/components/angular-tree-component/angular-tree-component/angular-tree-component.component.ts
  libs/components/angular-tree-component/src/lib/modules/angular-tree/angular-tree-node.component.html
  libs/components/angular-tree-component/src/lib/modules/angular-tree/angular-tree-wrapper.component.scss
Labels: risk level (author): 2

#3412 fix(sdk/skyux-eslint): disable `@angular-eslint/prefer-standalone` ESLint rule
  libs/sdk/skyux-eslint/src/configs/ts-base.ts
Labels: risk level (author): 1

#3411 feat(sdk/prettier-schematics): add ability to sort import statements
  libs/sdk/prettier-schematics/src/schematics/ng-add/ng-add.schematic.spec.ts
  libs/sdk/prettier-schematics/src/schematics/ng-add/ng-add.schematic.ts
  libs/sdk/prettier-schematics/src/schematics/ng-add/rules/add-prettier-dependencies.ts
  libs/sdk/prettier-schematics/src/schematics/ng-add/rules/write-prettier-config.ts
  libs/sdk/prettier-schematics/src/schematics/ng-add/schema.json
  libs/sdk/prettier-schematics/src/schematics/ng-add/schema.ts
Labels: risk level (author): 1

#3413 docs(components/navbar): add navbar harnesses to docs
  libs/components/navbar/documentation.json
Labels: risk level (author): 1

#3407 feat(components/lists): tokenize infinite scroll styles
  .github/instructions/add-scss-override.instructions.md
  .github/instructions/scss-override-mixins.instructions.md
  .github/instructions/setup-tokenization.instructions.md
  apps/e2e/lists-storybook-e2e/src/e2e/infinite-scroll.component.cy.ts
  libs/components/lists/src/lib/modules/infinite-scroll/infinite-scroll.component.scss
Labels: risk level (author): 2

#3403 feat(components/tabs): add sectioned form harnesses
  libs/components/code-examples/src/lib/modules/tabs/sectioned-form/modal/example.component.spec.ts
  libs/components/code-examples/src/lib/modules/tabs/sectioned-form/modal/example.component.ts
  libs/components/code-examples/src/lib/modules/tabs/sectioned-form/modal/information-form.component.html
  libs/components/code-examples/src/lib/modules/tabs/sectioned-form/modal/modal.component.html
  libs/components/code-examples/src/lib/modules/tabs/sectioned-form/modal/modal.component.ts
  libs/components/tabs/documentation.json
  libs/components/tabs/src/lib/modules/sectioned-form/sectioned-form.component.html
  libs/components/tabs/src/lib/modules/sectioned-form/sectioned-form.component.ts
  libs/components/tabs/testing/src/modules/sectioned-form/fixtures/sectioned-form-harness-test.component.html
  libs/components/tabs/testing/src/modules/sectioned-form/fixtures/sectioned-form-harness-test.component.ts
  libs/components/tabs/testing/src/modules/sectioned-form/sectioned-form-harness-filters.ts
  libs/components/tabs/testing/src/modules/sectioned-form/sectioned-form-harness.spec.ts
  libs/components/tabs/testing/src/modules/sectioned-form/sectioned-form-harness.ts
  libs/components/tabs/testing/src/modules/sectioned-form/sectioned-form-section-content-harness-filters.ts
  libs/components/tabs/testing/src/modules/sectioned-form/sectioned-form-section-content-harness.ts
  libs/components/tabs/testing/src/modules/sectioned-form/sectioned-form-section-harness-filters.ts
  libs/components/tabs/testing/src/modules/sectioned-form/sectioned-form-section-harness.ts
  libs/components/tabs/testing/src/public-api.ts
Labels: risk level (author): 1

#3415 feat(components/layout): tokenize action button styles
  apps/e2e/layout-storybook-e2e/src/e2e/action-button.component.cy.ts
  libs/components/layout/src/lib/modules/action-button/action-button-container.modern.component.scss
  libs/components/layout/src/lib/modules/action-button/action-button-header.modern.component.scss
  libs/components/layout/src/lib/modules/action-button/action-button-icon.modern.component.scss
  libs/components/layout/src/lib/modules/action-button/action-button.modern.component.scss
Labels: risk level (author): 2

#3417 chore: add PR #3246 to breaking changes
  CHANGELOG.md
Labels: risk level (author): 1

#3419 feat(components/indicators): tokenize illustration component
  apps/e2e/indicators-storybook-e2e/src/e2e/illustration.component.cy.ts
  libs/components/indicators/src/lib/modules/illustration/illustration.component.html
  libs/components/indicators/src/lib/modules/illustration/illustration.component.ts
  libs/components/indicators/src/lib/modules/illustration/illustration.default.component.scss
  libs/components/indicators/src/lib/modules/illustration/illustration.modern.component.scss
  libs/components/indicators/testing/src/modules/illustration/illustration-harness.spec.ts
  libs/components/indicators/testing/src/modules/illustration/illustration-harness.ts
Labels: risk level (author): 2

#3422 feat(components/lookup): added input box support and code examples to autocomplete
  libs/components/code-examples/src/index.ts
  libs/components/code-examples/src/lib/modules/lookup/autocomplete/advanced/example.component.html
  libs/components/code-examples/src/lib/modules/lookup/autocomplete/advanced/example.component.ts
  libs/components/code-examples/src/lib/modules/lookup/autocomplete/any-value/color-option.ts
  libs/components/code-examples/src/lib/modules/lookup/autocomplete/any-value/example.component.html
  libs/components/code-examples/src/lib/modules/lookup/autocomplete/any-value/example.component.spec.ts
  libs/components/code-examples/src/lib/modules/lookup/autocomplete/any-value/example.component.ts
  libs/components/code-examples/src/lib/modules/lookup/autocomplete/any-value/example.service.ts
  libs/components/code-examples/src/lib/modules/lookup/autocomplete/any-value/search-results.ts
  libs/components/code-examples/src/lib/modules/lookup/autocomplete/basic/example.component.html
  libs/components/code-examples/src/lib/modules/lookup/autocomplete/basic/example.component.ts
  libs/components/code-examples/src/lib/modules/lookup/autocomplete/custom-search/example.component.html
  libs/components/code-examples/src/lib/modules/lookup/autocomplete/custom-search/example.component.ts
  libs/components/code-examples/src/lib/modules/lookup/autocomplete/search-filters/example.component.html
  libs/components/code-examples/src/lib/modules/lookup/autocomplete/search-filters/example.component.ts
  libs/components/forms/src/lib/modules/input-box/input-box.component.html
  libs/components/lookup/documentation.json
  libs/components/lookup/src/lib/modules/autocomplete/autocomplete.component.scss
  libs/components/lookup/src/lib/modules/autocomplete/autocomplete.component.spec.ts
  libs/components/lookup/src/lib/modules/autocomplete/fixtures/autocomplete-input-box.component.fixture.html
  libs/components/lookup/src/lib/modules/autocomplete/fixtures/autocomplete-input-box.component.fixture.ts
Labels: risk level (author): 2

#3423 fix: address `track by identity` console warnings
  libs/components/a11y/src/lib/modules/skip-link/skip-link-host.component.html
  libs/components/code-examples/src/lib/modules/data-manager/data-manager/basic/view-repeater.component.html
  libs/components/code-examples/src/lib/modules/pages/page/record-page-blocks-layout-demo/record-page-content.component.html
  libs/components/code-examples/src/lib/modules/pages/page/record-page-tabs-layout-demo/record-page-notes-tab.component.html
  libs/components/code-examples/src/lib/modules/pages/page/record-page-tabs-layout-demo/record-page-overview-tab.component.html
  libs/components/code-examples/src/lib/modules/pages/page/split-view-page-fit-layout-demo/split-view-page-content.component.html
  libs/components/data-manager/src/lib/modules/data-manager/data-manager-column-picker/data-manager-column-picker.component.html
  libs/components/data-manager/src/lib/modules/data-manager/data-manager-toolbar/data-manager-toolbar.component.html
  libs/components/forms/src/lib/modules/file-attachment/file-drop/file-drop.component.html
  libs/components/inline-form/src/lib/modules/inline-form/inline-form.component.html
  libs/components/layout/src/lib/modules/action-button/fixtures/action-button-links.component.html
  libs/components/lookup/src/lib/modules/autocomplete/autocomplete.component.html
  libs/components/modals/src/lib/modules/confirm/confirm.component.html
  libs/components/modals/src/lib/modules/modal/modal-footer.component.html
  libs/components/pages/src/lib/modules/link-list/link-list.component.html
  libs/components/pages/src/lib/modules/modal-link-list/modal-link-list.component.html
  libs/components/pages/src/lib/modules/needs-attention/needs-attention.component.html
  libs/components/pages/src/lib/modules/needs-attention/needs-attention.component.spec.ts
  libs/components/pages/src/lib/modules/needs-attention/needs-attention.component.ts
  libs/components/text-editor/src/lib/modules/text-editor/menubar/text-editor-menubar.component.html
  libs/components/text-editor/src/lib/modules/text-editor/toolbar/text-editor-toolbar.component.html
  libs/components/toast/src/lib/modules/toast/toaster.component.html
Labels: risk level (author): 2

#3410 feat(components/inline-form): add inline form harnesses
  libs/components/code-examples/src/lib/modules/inline-form/inline-form/basic/example.component.html
  libs/components/code-examples/src/lib/modules/inline-form/inline-form/basic/example.component.spec.ts
  libs/components/code-examples/src/lib/modules/inline-form/inline-form/basic/example.component.ts
  libs/components/code-examples/src/lib/modules/inline-form/inline-form/custom-buttons/example.component.html
  libs/components/code-examples/src/lib/modules/inline-form/inline-form/custom-buttons/example.component.spec.ts
  libs/components/code-examples/src/lib/modules/inline-form/inline-form/custom-buttons/example.component.ts
  libs/components/code-examples/src/lib/modules/inline-form/inline-form/repeaters/example.component.spec.ts
  libs/components/inline-form/documentation.json
  libs/components/inline-form/package.json
  libs/components/inline-form/project.json
  libs/components/inline-form/src/lib/modules/inline-form/inline-form.component.ts
  libs/components/inline-form/testing/eslint.config.js
  libs/components/inline-form/testing/karma.conf.js
  libs/components/inline-form/testing/ng-package.json
  libs/components/inline-form/testing/project.json
  libs/components/inline-form/testing/src/modules/inline-form/inline-form-button-harness.filters.ts
  libs/components/inline-form/testing/src/modules/inline-form/inline-form-button-harness.ts
  libs/components/inline-form/testing/src/modules/inline-form/inline-form-harness.filters.ts
  libs/components/inline-form/testing/src/modules/inline-form/inline-form-harness.spec.ts
  libs/components/inline-form/testing/src/modules/inline-form/inline-form-harness.ts
  libs/components/inline-form/testing/src/modules/inline-form/inline-form-template-harness.ts
  libs/components/inline-form/testing/src/public-api.ts
  libs/components/inline-form/testing/tsconfig.spec.json
  tsconfig.base.json
Labels: risk level (author): 1

#3420 feat(components/layout): add inline delete harness
  libs/components/code-examples/src/lib/modules/layout/inline-delete/custom/example.component.html
  libs/components/code-examples/src/lib/modules/layout/inline-delete/custom/example.component.spec.ts
  libs/components/code-examples/src/lib/modules/layout/inline-delete/custom/example.component.ts
  libs/components/code-examples/src/lib/modules/layout/inline-delete/repeater/example.component.spec.ts
  libs/components/code-examples/src/lib/modules/layout/inline-delete/repeater/example.component.ts
  libs/components/layout/documentation.json
  libs/components/layout/project.json
  libs/components/layout/testing/src/modules/inline-delete/inline-delete-harness.filters.ts
  libs/components/layout/testing/src/modules/inline-delete/inline-delete-harness.spec.ts
  libs/components/layout/testing/src/modules/inline-delete/inline-delete-harness.ts
  libs/components/layout/testing/src/public-api.ts
Labels: risk level (author): 1

#3425 docs(components/forms): update field group code example form layouts in responsive mode
  libs/components/code-examples/src/lib/modules/forms/field-group/basic/example.component.html
  libs/components/code-examples/src/lib/modules/forms/field-group/help-key/example.component.html
Labels: risk level (author): 1

#3424 fix(components/docs-tools): show `?` indicator only for optional interface properties
  eslint-base.config.js
  libs/components/docs-tools/src/lib/modules/type-definition/pipes/property-name.pipe.ts
Labels: risk level (author): 1
