Repository blackbaud/skyux, pull requests merged in 2025-01, with the labels that each got.

#2961 ci: update github-actions-issue-to-work-item
  .github/workflows/skyux-azboards.yml
Labels: risk level (author): 1

#2963 ci: fix e2e build id
  .github/workflows/e2e.yml
Labels: risk level (author): 1, skip e2e

#2960 docs: mock `SkyHelpService` in code-examples spa
  apps/code-examples/src/app/app.module.ts
  apps/code-examples/src/app/shared/help-service/help-service.ts
Labels: risk level (author): 1, skip e2e

#2965 ci: fix e2e build id (#2963)
  .github/workflows/e2e.yml
Labels: risk level (author): 1, skip e2e

#2967 ci: update cherry-pick for lts branch
  .github/workflows/cherry-pick.yml
Labels: risk level (author): 1

#2971 fix: update `@skyux/dev-infra-private` to `10.0.0-alpha.18` to address issues with documentation generation
  package-lock.json
  package.json
Labels: risk level (author): 1

#2974 feat(components/layout): remove extra space from view actions
  apps/e2e/layout-storybook/src/app/toolbar/toolbar.component.html
  apps/e2e/layout-storybook/src/app/toolbar/toolbar.component.ts
  apps/e2e/layout-storybook/src/app/toolbar/toolbar.module.ts
  libs/components/layout/src/lib/modules/toolbar/toolbar-view-actions.component.scss
Labels: risk level (author): 1

#2972 fix: update `@skyux/dev-infra-private` to `10.0.0-alpha.18` to address issues with documentation generation (#2971)
  package-lock.json
  package.json
Labels: risk level (author): 1

#2975 feat(components/layout): remove extra space from view actions (#2974)
  apps/e2e/layout-storybook/src/app/toolbar/toolbar.component.html
  apps/e2e/layout-storybook/src/app/toolbar/toolbar.component.ts
  apps/e2e/layout-storybook/src/app/toolbar/toolbar.module.ts
  libs/components/layout/src/lib/modules/toolbar/toolbar-view-actions.component.scss
Labels: risk level (author): 1

#2977 ci: set release to 12.0.0-alpha.0
  .github/workflows/release-please.yml
Labels: risk level (author): 1

#2978 build: apply `@skyux/dev-infra-private@10.0.0-alpha.19`
  package-lock.json
  package.json
Labels: risk level (author): 1

#2979 build: apply `@skyux/dev-infra-private@10.0.0-alpha.19`
  package-lock.json
  package.json
Labels: risk level (author): 1

#2970 deprecation(components/layout): mark all definition list components as deprecated; use `SkyDescriptionListModule` instead
  libs/components/layout/src/lib/modules/definition-list/definition-list-content.component.ts
  libs/components/layout/src/lib/modules/definition-list/definition-list-heading.component.ts
  libs/components/layout/src/lib/modules/definition-list/definition-list-label.component.ts
  libs/components/layout/src/lib/modules/definition-list/definition-list-value.component.ts
  libs/components/layout/src/lib/modules/definition-list/definition-list.component.ts
Labels: risk level (author): 1

#2973 chore: release 11.31.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease 11.x.x: pending

#2980 feat(components/layout): tokenize toolbar component
  apps/e2e/layout-storybook-e2e/src/e2e/toolbar.component.cy.ts
  apps/playground/src/app/components/layout/toolbar/toolbar.component.html
  apps/playground/src/app/components/layout/toolbar/toolbar.component.ts
  apps/playground/src/app/components/layout/toolbar/toolbar.module.ts
  libs/components/layout/src/lib/modules/toolbar/toolbar-item.component.scss
  libs/components/layout/src/lib/modules/toolbar/toolbar-section.component.scss
  libs/components/layout/src/lib/modules/toolbar/toolbar-view-actions.component.scss
  libs/components/layout/src/lib/modules/toolbar/toolbar.component.scss
  libs/components/lookup/src/lib/modules/search/search.component.scss
Labels: risk level (author): 1

#2986 chore: changelog for 11.31.0 (#2973) 🍒
  CHANGELOG.md
Labels: risk level (author): 1, risk level (reviewer): 1

#2989 ci: fix e2e concurrency groups
  .github/workflows/e2e.yml
Labels: risk level (author): 1, skip e2e

#2991 ci: fix e2e concurrency groups (#2989)
  .github/workflows/e2e.yml
Labels: risk level (author): 1

#2990 feat(components/packages): remove old schematics; move some to v12
  libs/components/packages/collection.json
  libs/components/packages/src/schematics/migrations/migration-collection.json
  libs/components/packages/src/schematics/migrations/update-11/ag-grid/__snapshots__/ag-grid.schematic.spec.ts.snap
  libs/components/packages/src/schematics/migrations/update-11/ag-grid/ag-grid.schematic.spec.ts
  libs/components/packages/src/schematics/migrations/update-11/ag-grid/ag-grid.schematic.ts
  libs/components/packages/src/schematics/migrations/update-11/ag-grid/event-type-strings/event-type-strings.spec.ts
  libs/components/packages/src/schematics/migrations/update-11/ag-grid/event-type-strings/event-type-strings.ts
  libs/components/packages/src/schematics/migrations/update-11/ag-grid/schema.json
  libs/components/packages/src/schematics/migrations/update-11/ag-grid/switch-to-set-grid-option/switch-to-set-grid-option.spec.ts
  libs/components/packages/src/schematics/migrations/update-11/ag-grid/switch-to-set-grid-option/switch-to-set-grid-option.ts
  libs/components/packages/src/schematics/migrations/update-11/forms/forms.schematic.spec.ts
  libs/components/packages/src/schematics/migrations/update-11/forms/forms.schematic.ts
  libs/components/packages/src/schematics/migrations/update-11/ng-wait-for-async-test/ng-wait-for-async-test.schematic.spec.ts
  libs/components/packages/src/schematics/migrations/update-11/ng-wait-for-async-test/ng-wait-for-async-test.schematic.ts
  libs/components/packages/src/schematics/migrations/update-11/remove-deprecation-eslint-plugin/remove-deprecation-eslint-plugin.schematic.spec.ts
  libs/components/packages/src/schematics/migrations/update-11/remove-deprecation-eslint-plugin/remove-deprecation-eslint-plugin.schematic.ts
  libs/components/packages/src/schematics/migrations/update-11/vscode-eslint-setting/vscode-eslint-setting.schematic.spec.ts
  libs/components/packages/src/schematics/migrations/update-11/vscode-eslint-setting/vscode-eslint-setting.schematic.ts
  libs/components/packages/src/schematics/migrations/update-12/axe-core/axe-core.schematic.spec.ts
  libs/components/packages/src/schematics/migrations/update-12/axe-core/axe-core.schematic.ts
  libs/components/packages/src/schematics/migrations/update-12/help-inline-import-path/help-inline-import-path.schematic.spec.ts
  libs/components/packages/src/schematics/migrations/update-12/help-inline-import-path/help-inline-import-path.schematic.ts
  libs/components/packages/src/schematics/migrations/update-12/i18n-resources-module/i18n-resources-module.schematic.spec.ts
  libs/components/packages/src/schematics/migrations/update-12/i18n-resources-module/i18n-resources-module.schematic.ts
  libs/components/packages/src/schematics/migrations/update-12/icons-migration/icons-migration.schematic.spec.ts
  libs/components/packages/src/schematics/migrations/update-12/icons-migration/icons-migration.schematic.ts
  libs/components/packages/src/schematics/migrations/update-12/remove-nx-cache/remove-nx-cache.schematic.spec.ts
  libs/components/packages/src/schematics/migrations/update-12/remove-nx-cache/remove-nx-cache.schematic.ts
  libs/components/packages/src/schematics/migrations/update-12/remove-old-compat-stylesheets/remove-old-compat-stylesheets.schematic.spec.ts
  libs/components/packages/src/schematics/migrations/update-12/remove-old-compat-stylesheets/remove-old-compat-stylesheets.schematic.ts
  libs/components/packages/src/schematics/migrations/update-12/workspace-check/workspace-check.schematic.spec.ts
  libs/components/packages/src/schematics/migrations/update-12/workspace-check/workspace-check.schematic.ts
  libs/sdk/prettier-schematics/src/schematics/migrations/migration-collection.json
  libs/sdk/prettier-schematics/src/schematics/migrations/update-10/sort-imports-plugin/sort-imports-plugin.schematic.spec.ts
  libs/sdk/prettier-schematics/src/schematics/migrations/update-10/sort-imports-plugin/sort-imports-plugin.schematic.ts
Labels: risk level (author): 1

#2987 feat(components/layout): tokenize toolbar component (#2980)
  apps/e2e/layout-storybook-e2e/src/e2e/toolbar.component.cy.ts
  apps/playground/src/app/components/layout/toolbar/toolbar.component.html
  apps/playground/src/app/components/layout/toolbar/toolbar.component.ts
  apps/playground/src/app/components/layout/toolbar/toolbar.module.ts
  libs/components/layout/src/lib/modules/toolbar/toolbar-item.component.scss
  libs/components/layout/src/lib/modules/toolbar/toolbar-section.component.scss
  libs/components/layout/src/lib/modules/toolbar/toolbar-view-actions.component.scss
  libs/components/layout/src/lib/modules/toolbar/toolbar.component.scss
  libs/components/lookup/src/lib/modules/search/search.component.scss
Labels: risk level (author): 1

#2976 chore: release 12.0.0-alpha.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#2992 feat(skyformerrorharness): add method to get error text
  libs/components/forms/testing/src/modules/form-error/form-error-harness.spec.ts
  libs/components/forms/testing/src/modules/form-error/form-error-harness.ts
  libs/components/forms/testing/src/modules/form-error/form-errors-harness.spec.ts
Labels: risk level (author): 1

#2994 feat(components/forms): add method to `SkyFormErrorHarness` to get error text (#2992)
  libs/components/forms/testing/src/modules/form-error/form-error-harness.spec.ts
  libs/components/forms/testing/src/modules/form-error/form-error-harness.ts
  libs/components/forms/testing/src/modules/form-error/form-errors-harness.spec.ts
Labels: risk level (author): 1

#2996 fix: update e2e workflow
  .github/workflows/e2e.yml
Labels: risk level (author): 1, skip e2e

#2995 fix(components/text-editor): update package dependencies
  libs/components/text-editor/package.json
  package-lock.json
  package.json
Labels: risk level (author): 1

#2997 chore: release 10.44.3
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease 10.x.x: pending

#2998 chore: changelog for 10.44.3 (#2997) 🍒
  CHANGELOG.md
Labels: risk level (author): 1, risk level (reviewer): 1

#2988 chore: release 11.32.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease 11.x.x: pending

#3000 chore: changelog for 11.32.0 (#2988) 🍒
  CHANGELOG.md
Labels: risk level (author): 1, risk level (reviewer): 1

#2993 fix(components/ag-grid): handle focus for adjacent editor cells
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-editors/cell-editor-autocomplete/cell-editor-autocomplete.component.spec.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-editors/cell-editor-autocomplete/cell-editor-autocomplete.component.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-editors/cell-editor-currency/cell-editor-currency.component.spec.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-editors/cell-editor-currency/cell-editor-currency.component.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-editors/cell-editor-datepicker/cell-editor-datepicker.component.spec.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-editors/cell-editor-datepicker/cell-editor-datepicker.component.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-editors/cell-editor-text/cell-editor-text.component.spec.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-editors/cell-editor-text/cell-editor-text.component.ts
Labels: risk level (author): 1

#3005 fix(components/ag-grid): handle focus for adjacent editor cells (#2993)
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-editors/cell-editor-autocomplete/cell-editor-autocomplete.component.spec.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-editors/cell-editor-autocomplete/cell-editor-autocomplete.component.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-editors/cell-editor-currency/cell-editor-currency.component.spec.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-editors/cell-editor-currency/cell-editor-currency.component.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-editors/cell-editor-datepicker/cell-editor-datepicker.component.spec.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-editors/cell-editor-datepicker/cell-editor-datepicker.component.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-editors/cell-editor-text/cell-editor-text.component.spec.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-editors/cell-editor-text/cell-editor-text.component.ts
Labels: risk level (author): 1

#3007 feat(components/pages): create testing harness for action hub (#2962)
  apps/code-examples/project.json
  apps/code-examples/src/app/code-examples/pages/action-hub/demo.component.html
  apps/code-examples/src/app/code-examples/pages/action-hub/demo.component.spec.ts
  apps/code-examples/src/app/code-examples/pages/action-hub/settings-modal.component.html
  apps/code-examples/src/app/code-examples/pages/action-hub/settings-modal.component.spec.ts
  apps/code-examples/src/app/code-examples/pages/action-hub/settings-modal.component.ts
  libs/components/pages/src/index.ts
  libs/components/pages/src/lib/modules/link-list/link-list.component.html
  libs/components/pages/src/lib/modules/modal-link-list/modal-link-list.component.html
  libs/components/pages/src/lib/modules/needs-attention/needs-attention.component.html
  libs/components/pages/src/lib/modules/needs-attention/needs-attention.component.ts
  libs/components/pages/src/lib/modules/needs-attention/needs-attention.module.ts
  libs/components/pages/testing/src/modules/action-hub/action-hub-harness-filters.ts
  libs/components/pages/testing/src/modules/action-hub/action-hub-harness.spec.ts
  libs/components/pages/testing/src/modules/action-hub/action-hub-harness.ts
  libs/components/pages/testing/src/modules/link-list/link-list-harness.spec.ts
  libs/components/pages/testing/src/modules/link-list/link-list-harness.ts
  libs/components/pages/testing/src/modules/link-list/link-list-item-harness-filters.ts
  libs/components/pages/testing/src/modules/link-list/link-list-item-harness.ts
  libs/components/pages/testing/src/modules/needs-attention/needs-attention-harness-filters.ts
  libs/components/pages/testing/src/modules/needs-attention/needs-attention-harness.spec.ts
  libs/components/pages/testing/src/modules/needs-attention/needs-attention-harness.ts
  libs/components/pages/testing/src/modules/needs-attention/needs-attention-item-harness-filters.ts
  libs/components/pages/testing/src/modules/needs-attention/needs-attention-item-harness.ts
  libs/components/pages/testing/src/public-api.ts
Labels: risk level (author): 1

#3008 feat: update `@skyux/icons` to 7.10.0
  libs/components/packages/package.json
  libs/components/theme/package.json
  libs/components/theme/src/lib/styles/sky.scss
  package-lock.json
  package.json
Labels: risk level (author): 2

#3010 fix(components/lists): update filter visual tests
  apps/e2e/lists-storybook/src/app/filter/filter.component.html
Labels: risk level (author): 1

#3011 chore: update `prettier` to `3.4.2`
  apps/e2e/lists-storybook/src/polyfills.ts
  libs/components/a11y/src/lib/modules/shared/sky-a11y-resources.module.ts
  libs/components/action-bars/src/lib/modules/shared/sky-action-bars-resources.module.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/header/header.component.scss
  libs/components/ag-grid/src/lib/modules/shared/sky-ag-grid-resources.module.ts
  libs/components/ag-grid/src/lib/styles/_base.scss
  libs/components/angular-tree-component/src/lib/modules/shared/sky-angular-tree-component-resources.module.ts
  libs/components/avatar/src/lib/modules/shared/sky-avatar-resources.module.ts
  libs/components/colorpicker/src/lib/modules/colorpicker/colorpicker.component.scss
  libs/components/colorpicker/src/lib/modules/shared/sky-colorpicker-resources.module.ts
  libs/components/core/src/lib/modules/numeric/numeric.service.spec.ts
  libs/components/core/src/lib/modules/shared/sky-core-resources.module.ts
  libs/components/data-manager/src/lib/modules/shared/sky-data-manager-resources.module.ts
  libs/components/datetime/src/lib/modules/datepicker/calendar/daypicker-button.component.scss
  libs/components/datetime/src/lib/modules/shared/sky-datetime-resources.module.ts
  libs/components/datetime/src/lib/modules/timepicker/timepicker.component.scss
  libs/components/errors/src/lib/modules/shared/sky-errors-resources.module.ts
  libs/components/flyout/src/lib/modules/shared/sky-flyout-resources.module.ts
  libs/components/forms/src/lib/modules/file-attachment/file-attachment/file-attachment.component.scss
  libs/components/forms/src/lib/modules/file-attachment/file-drop/file-item.component.scss
  libs/components/forms/src/lib/modules/input-box/input-box.component.scss
  libs/components/forms/src/lib/modules/shared/sky-forms-resources.module.ts
  libs/components/forms/src/lib/modules/toggle-switch/toggle-switch.component.scss
  libs/components/grids/src/lib/modules/shared/sky-grids-resources.module.ts
  libs/components/help-inline/src/lib/modules/shared/sky-help-inline-resources.module.ts
  libs/components/indicators/src/lib/modules/shared/sky-indicators-resources.module.ts
  libs/components/indicators/src/lib/modules/tokens/token.component.scss
  libs/components/inline-form/src/lib/modules/shared/sky-inline-form-resources.module.ts
  libs/components/layout/src/lib/modules/fluid-grid/row.component.scss
  libs/components/layout/src/lib/modules/shared/sky-layout-resources.module.ts
  libs/components/list-builder-view-grids/src/lib/modules/shared/sky-list-builder-view-grids-resources.module.ts
  libs/components/list-builder/src/lib/modules/shared/sky-list-builder-resources.module.ts
  libs/components/lists/src/lib/modules/shared/sky-lists-resources.module.ts
  libs/components/lookup/src/lib/modules/autocomplete/autocomplete.component.scss
  libs/components/lookup/src/lib/modules/lookup/lookup.component.scss
  libs/components/lookup/src/lib/modules/search/search.component.scss
  libs/components/lookup/src/lib/modules/shared/sky-lookup-resources.module.ts
  libs/components/manifest/src/generator/plugins/typedoc-plugin-decorators.mjs
  libs/components/modals/src/lib/modules/shared/sky-modals-resources.module.ts
  libs/components/packages/src/schematics/utility/json-file.ts
  libs/components/pages/src/lib/modules/shared/sky-pages-resources.module.ts
  libs/components/phone-field/src/lib/modules/shared/sky-phone-field-resources.module.ts
  libs/components/popovers/src/lib/modules/shared/sky-popovers-resources.module.ts
  libs/components/progress-indicator/src/lib/modules/shared/sky-progress-indicator-resources.module.ts
  libs/components/select-field/src/lib/modules/shared/sky-select-field-resources.module.ts
  libs/components/split-view/src/lib/modules/shared/sky-split-view-resources.module.ts
  libs/components/tabs/src/lib/modules/shared/sky-tabs-resources.module.ts
  libs/components/text-editor/src/lib/modules/shared/sky-text-editor-resources.module.ts
  libs/components/theme/src/lib/styles/themes/modern/_switch.scss
  libs/components/tiles/src/lib/modules/shared/sky-tiles-resources.module.ts
  libs/components/toast/src/lib/modules/shared/sky-toast-resources.module.ts
  libs/sdk/eslint-config/src/schematics/shared/utility/json-file.ts
  package-lock.json
  package.json
Labels: risk level (author): 1

#3006 chore: release 11.33.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease 11.x.x: pending

#3013 chore: changelog for 11.33.0 (#3006) 🍒
  CHANGELOG.md
Labels: risk level (author): 1, risk level (reviewer): 1

#2999 chore(apps/playground): add a disabled vertical tab to the playground
  apps/playground/src/app/components/tabs/vertical-tabset/vertical-tabset.component.html
Labels: risk level (author): 1

#3014 fix(components/pages): hide blocks with hidden `[skyHref]` links
  libs/components/pages/src/lib/modules/link-list/link-list.component.scss
  libs/components/pages/src/lib/modules/modal-link-list/modal-link-list.component.scss
  libs/components/pages/src/lib/modules/needs-attention/needs-attention.component.scss
  libs/components/pages/src/lib/modules/page-header/page-header.component.scss
Labels: risk level (author): 1

#3017 fix(components/pages): hide blocks with hidden `[skyHref]` links (#3014)
  libs/components/pages/src/lib/modules/link-list/link-list.component.scss
  libs/components/pages/src/lib/modules/modal-link-list/modal-link-list.component.scss
  libs/components/pages/src/lib/modules/needs-attention/needs-attention.component.scss
  libs/components/pages/src/lib/modules/page-header/page-header.component.scss
Labels: risk level (author): 1

#3016 chore: update `prettier` to `3.4.2`
  apps/e2e/lists-storybook/src/polyfills.ts
  libs/components/a11y/src/lib/modules/shared/sky-a11y-resources.module.ts
  libs/components/action-bars/src/lib/modules/shared/sky-action-bars-resources.module.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/header/header.component.scss
  libs/components/ag-grid/src/lib/modules/shared/sky-ag-grid-resources.module.ts
  libs/components/ag-grid/src/lib/styles/_base.scss
  libs/components/angular-tree-component/src/lib/modules/shared/sky-angular-tree-component-resources.module.ts
  libs/components/avatar/src/lib/modules/shared/sky-avatar-resources.module.ts
  libs/components/colorpicker/src/lib/modules/colorpicker/colorpicker.component.scss
  libs/components/colorpicker/src/lib/modules/shared/sky-colorpicker-resources.module.ts
  libs/components/core/src/lib/modules/numeric/numeric.service.spec.ts
  libs/components/core/src/lib/modules/shared/sky-core-resources.module.ts
  libs/components/data-manager/src/lib/modules/shared/sky-data-manager-resources.module.ts
  libs/components/datetime/src/lib/modules/datepicker/calendar/daypicker-button.component.scss
  libs/components/datetime/src/lib/modules/shared/sky-datetime-resources.module.ts
  libs/components/datetime/src/lib/modules/timepicker/timepicker.component.scss
  libs/components/errors/src/lib/modules/shared/sky-errors-resources.module.ts
  libs/components/flyout/src/lib/modules/shared/sky-flyout-resources.module.ts
  libs/components/forms/src/lib/modules/file-attachment/file-attachment/file-attachment.component.scss
  libs/components/forms/src/lib/modules/file-attachment/file-drop/file-item.component.scss
  libs/components/forms/src/lib/modules/input-box/input-box.component.scss
  libs/components/forms/src/lib/modules/shared/sky-forms-resources.module.ts
  libs/components/forms/src/lib/modules/toggle-switch/toggle-switch.component.scss
  libs/components/grids/src/lib/modules/shared/sky-grids-resources.module.ts
  libs/components/help-inline/src/lib/modules/shared/sky-help-inline-resources.module.ts
  libs/components/indicators/src/lib/modules/shared/sky-indicators-resources.module.ts
  libs/components/indicators/src/lib/modules/tokens/token.component.scss
  libs/components/inline-form/src/lib/modules/shared/sky-inline-form-resources.module.ts
  libs/components/layout/src/lib/modules/fluid-grid/row.component.scss
  libs/components/layout/src/lib/modules/shared/sky-layout-resources.module.ts
  libs/components/list-builder-view-grids/src/lib/modules/shared/sky-list-builder-view-grids-resources.module.ts
  libs/components/list-builder/src/lib/modules/shared/sky-list-builder-resources.module.ts
  libs/components/lists/src/lib/modules/shared/sky-lists-resources.module.ts
  libs/components/lookup/src/lib/modules/autocomplete/autocomplete.component.scss
  libs/components/lookup/src/lib/modules/lookup/lookup.component.scss
  libs/components/lookup/src/lib/modules/search/search.component.scss
  libs/components/lookup/src/lib/modules/shared/sky-lookup-resources.module.ts
  libs/components/manifest/src/generator/plugins/typedoc-plugin-decorators.mjs
  libs/components/modals/src/lib/modules/shared/sky-modals-resources.module.ts
  libs/components/packages/src/schematics/utility/json-file.ts
  libs/components/pages/src/lib/modules/shared/sky-pages-resources.module.ts
  libs/components/phone-field/src/lib/modules/shared/sky-phone-field-resources.module.ts
  libs/components/popovers/src/lib/modules/shared/sky-popovers-resources.module.ts
  libs/components/progress-indicator/src/lib/modules/shared/sky-progress-indicator-resources.module.ts
  libs/components/select-field/src/lib/modules/shared/sky-select-field-resources.module.ts
  libs/components/split-view/src/lib/modules/shared/sky-split-view-resources.module.ts
  libs/components/tabs/src/lib/modules/shared/sky-tabs-resources.module.ts
  libs/components/text-editor/src/lib/modules/shared/sky-text-editor-resources.module.ts
  libs/components/theme/src/lib/styles/themes/modern/_switch.scss
  libs/components/tiles/src/lib/modules/shared/sky-tiles-resources.module.ts
  libs/components/toast/src/lib/modules/shared/sky-toast-resources.module.ts
  libs/sdk/eslint-config/src/schematics/shared/utility/json-file.ts
  package-lock.json
  package.json
Labels: risk level (author): 1

#3012 feat: update `@skyux/icons` to 7.10.0 (#3008)
  libs/components/packages/package.json
  libs/components/theme/package.json
  libs/components/theme/src/lib/styles/sky.scss
  package-lock.json
  package.json
Labels: risk level (author): 1

#3021 build: update `@skyux/dev-infra-private` to `10.0.0-alpha.22`
  package-lock.json
  package.json
Labels: risk level (author): 1

#3018 chore: release 11.34.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease 11.x.x: pending

#3023 chore: turn off eslint plugin quick fix on save of standalone rule
  .vscode/settings.json
Labels: risk level (author): 1

#2968 feat(components/forms): file drop add control value accessor
  apps/code-examples/src/app/code-examples/forms/file-drop/basic/demo.component.html
  apps/code-examples/src/app/code-examples/forms/file-drop/basic/demo.component.ts
  apps/playground/src/app/components/forms/file-attachment/file-attachment.component.html
  apps/playground/src/app/components/forms/file-attachment/file-attachment.component.ts
  apps/playground/src/app/components/forms/file-attachment/file-attachment.module.ts
  libs/components/forms/src/lib/modules/file-attachment/file-attachment/file-attachment.component.html
  libs/components/forms/src/lib/modules/file-attachment/file-attachment/file-attachment.component.ts
  libs/components/forms/src/lib/modules/file-attachment/file-attachment/file-attachment.service.ts
  libs/components/forms/src/lib/modules/file-attachment/file-drop/file-drop.component.html
  libs/components/forms/src/lib/modules/file-attachment/file-drop/file-drop.component.spec.ts
  libs/components/forms/src/lib/modules/file-attachment/file-drop/file-drop.component.ts
  libs/components/forms/src/lib/modules/file-attachment/file-drop/fixtures/reactive-file-drop.component.fixture.html
  libs/components/forms/src/lib/modules/file-attachment/file-drop/fixtures/reactive-file-drop.component.fixture.ts
Labels: risk level (author): 3

#3019 feat(components/lists): tokenize filter styles
  apps/e2e/lists-storybook-e2e/src/e2e/filter.component.cy.ts
  libs/components/lists/src/lib/modules/filter/filter-button.component.scss
  libs/components/lists/src/lib/modules/filter/filter-inline-item.component.scss
  libs/components/lists/src/lib/modules/filter/filter-inline.component.scss
  libs/components/lists/src/lib/modules/filter/filter-summary-item.component.scss
  libs/components/lists/src/lib/modules/filter/filter-summary-item.component.ts
  libs/components/lists/src/lib/modules/filter/filter-summary.component.scss
Labels: risk level (author): 1

#3015 feat(components/tabs): tokenize vertical tabset styles
  apps/e2e/tabs-storybook-e2e/src/e2e/vertical-tabs.component.cy.ts
  libs/components/icon/src/lib/modules/icon/icon-svg.component.ts
  libs/components/indicators/src/lib/modules/expansion-indicator/expansion-indicator.component.ts
  libs/components/indicators/src/lib/modules/expansion-indicator/expansion-indicator.modern.component.scss
  libs/components/indicators/src/lib/modules/illustration/illustration.component.ts
  libs/components/tabs/src/lib/modules/vertical-tabset/vertical-tab.component.html
  libs/components/tabs/src/lib/modules/vertical-tabset/vertical-tab.component.scss
  libs/components/tabs/src/lib/modules/vertical-tabset/vertical-tabset-group.component.html
  libs/components/tabs/src/lib/modules/vertical-tabset/vertical-tabset-group.component.scss
  libs/components/tabs/src/lib/modules/vertical-tabset/vertical-tabset.component.scss
  libs/components/theme/src/lib/styles/_switch.scss
Labels: risk level (author): 2

#3004 refactor(components/phone-field): use standalone components, address all linting errors
  libs/components/phone-field/src/lib/modules/phone-field/fixtures/phone-field-input-box.component.fixture.ts
  libs/components/phone-field/src/lib/modules/phone-field/fixtures/phone-field-reactive.component.fixture.ts
  libs/components/phone-field/src/lib/modules/phone-field/fixtures/phone-field.component.fixture.ts
  libs/components/phone-field/src/lib/modules/phone-field/fixtures/phone-field.fixture.module.ts
  libs/components/phone-field/src/lib/modules/phone-field/phone-field-input.directive.ts
  libs/components/phone-field/src/lib/modules/phone-field/phone-field.component.spec.ts
  libs/components/phone-field/src/lib/modules/phone-field/phone-field.component.ts
  libs/components/phone-field/src/lib/modules/phone-field/phone-field.module.ts
Labels: risk level (author): 1

#3009 chore: update development dependencies
  package-lock.json
  package.json
Labels: risk level (author): 1

#3026 fix(components/modals): make modal footer error message focusable
  libs/components/modals/src/lib/modules/modal/modal-footer.component.html
Labels: risk level (author): 1

#3027 fix(components/modals): make modal footer error message focusable (#3026)
  libs/components/modals/src/lib/modules/modal/modal-footer.component.html
Labels: risk level (author): 1

#3024 feat(components/forms): file drop add control value accessor (#2968)
  apps/code-examples/src/app/code-examples/forms/file-drop/basic/demo.component.html
  apps/code-examples/src/app/code-examples/forms/file-drop/basic/demo.component.ts
  apps/playground/src/app/components/forms/file-attachment/file-attachment.component.html
  apps/playground/src/app/components/forms/file-attachment/file-attachment.component.ts
  apps/playground/src/app/components/forms/file-attachment/file-attachment.module.ts
  libs/components/forms/src/lib/modules/file-attachment/file-attachment/file-attachment.component.html
  libs/components/forms/src/lib/modules/file-attachment/file-attachment/file-attachment.component.ts
  libs/components/forms/src/lib/modules/file-attachment/file-attachment/file-attachment.service.ts
  libs/components/forms/src/lib/modules/file-attachment/file-drop/file-drop.component.html
  libs/components/forms/src/lib/modules/file-attachment/file-drop/file-drop.component.spec.ts
  libs/components/forms/src/lib/modules/file-attachment/file-drop/file-drop.component.ts
  libs/components/forms/src/lib/modules/file-attachment/file-drop/fixtures/reactive-file-drop.component.fixture.html
  libs/components/forms/src/lib/modules/file-attachment/file-drop/fixtures/reactive-file-drop.component.fixture.ts
Labels: risk level (author): 3

#3028 fix(components/action-bars): account for left nav in summary action bar position
  libs/components/action-bars/src/lib/modules/summary-action-bar/summary-action-bar.component.scss
Labels: risk level (author): 1

#3032 fix(components/action-bars): account for left nav in summary action bar position (#3028)
  libs/components/action-bars/src/lib/modules/summary-action-bar/summary-action-bar.component.scss
Labels: risk level (author): 1

#3034 refactor(components/tiles): remove deprecated observers from tile control handlers
  libs/components/tiles/src/lib/modules/tiles/tile/tile.component.ts
Labels: risk level (author): 1

#3025 chore: release 11.35.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease 11.x.x: pending

#3036 chore: changelog for 11.35.0 (#3025) 🍒
  CHANGELOG.md
Labels: risk level (author): 1, risk level (reviewer): 1

#3035 refactor(components/tiles): remove deprecated observers from tile control handlers (#3034)
  libs/components/tiles/src/lib/modules/tiles/tile/tile.component.ts
Labels: risk level (author): 1

#3029 feat(components/forms): file drop harness
  apps/code-examples/src/app/code-examples/forms/file-drop/basic/demo.component.html
  apps/code-examples/src/app/code-examples/forms/file-drop/basic/demo.component.spec.ts
  apps/code-examples/src/app/code-examples/forms/file-drop/basic/demo.component.ts
  libs/components/avatar/testing/src/modules/avatar/avatar-harness.ts
  libs/components/forms/src/lib/modules/file-attachment/file-drop/file-drop.component.html
  libs/components/forms/src/lib/modules/file-attachment/file-drop/fixtures/reactive-file-drop.component.fixture.html
  libs/components/forms/src/lib/modules/file-attachment/file-drop/fixtures/reactive-file-drop.component.fixture.ts
  libs/components/forms/testing/src/modules/file-attachment/file-drop/file-drop-harness.spec.ts
  libs/components/forms/testing/src/modules/file-attachment/file-drop/file-drop-harness.ts
  libs/components/forms/testing/src/modules/file-attachment/file-drop/file-drop-link-upload-harness.ts
  libs/components/forms/testing/src/modules/file-attachment/file-drop/file-drop-link-upload-input-harness.ts
  libs/components/forms/testing/src/modules/file-attachment/file-drop/file-item-harness-filters.ts
  libs/components/forms/testing/src/modules/file-attachment/file-drop/file-item-harness.ts
  libs/components/forms/testing/src/public-api.ts
Labels: risk level (author): 1

#3033 feat(components/tabs): tokenize sectioned form styles
  apps/e2e/tabs-storybook-e2e/src/e2e/sectioned-form.component.cy.ts
  libs/components/tabs/src/lib/modules/sectioned-form/sectioned-form-section.component.html
  libs/components/tabs/src/lib/modules/sectioned-form/sectioned-form-section.component.scss
  libs/components/tabs/src/lib/modules/sectioned-form/sectioned-form-section.component.ts
  libs/components/tabs/src/lib/modules/sectioned-form/sectioned-form.component.scss
  libs/components/tabs/src/lib/modules/sectioned-form/sectioned-form.component.spec.ts
  libs/components/tabs/src/lib/modules/vertical-tabset/vertical-tab.component.html
  libs/components/tabs/src/lib/modules/vertical-tabset/vertical-tab.component.scss
  libs/components/tabs/src/lib/modules/vertical-tabset/vertical-tab.component.ts
Labels: risk level (author): 2

#3039 feat(components/forms): file drop harness (#3029)
  apps/code-examples/src/app/code-examples/forms/file-drop/basic/demo.component.html
  apps/code-examples/src/app/code-examples/forms/file-drop/basic/demo.component.spec.ts
  apps/code-examples/src/app/code-examples/forms/file-drop/basic/demo.component.ts
  libs/components/avatar/testing/src/modules/avatar/avatar-harness.ts
  libs/components/forms/src/lib/modules/file-attachment/file-drop/file-drop.component.html
  libs/components/forms/src/lib/modules/file-attachment/file-drop/fixtures/reactive-file-drop.component.fixture.html
  libs/components/forms/src/lib/modules/file-attachment/file-drop/fixtures/reactive-file-drop.component.fixture.ts
  libs/components/forms/testing/src/modules/file-attachment/file-drop/file-drop-harness.spec.ts
  libs/components/forms/testing/src/modules/file-attachment/file-drop/file-drop-harness.ts
  libs/components/forms/testing/src/modules/file-attachment/file-drop/file-drop-link-upload-harness.ts
  libs/components/forms/testing/src/modules/file-attachment/file-drop/file-drop-link-upload-input-harness.ts
  libs/components/forms/testing/src/modules/file-attachment/file-drop/file-item-harness-filters.ts
  libs/components/forms/testing/src/modules/file-attachment/file-drop/file-item-harness.ts
  libs/components/forms/testing/src/public-api.ts
Labels: risk level (author): 1

#3037 fix(components/ag-grid): header should have readable text
  libs/components/ag-grid/package.json
  libs/components/ag-grid/src/lib/modules/ag-grid/header/header.component.html
  libs/components/ag-grid/src/lib/modules/ag-grid/header/header.component.ts
  libs/components/packages/package.json
  libs/components/packages/src/schematics/ag-grid-migrate/ag-grid-migrate.schematic.spec.ts
  libs/components/packages/src/schematics/ag-grid-migrate/ag-grid-migrate.schematic.ts
  libs/components/packages/src/schematics/migrations/update-11/ag-grid/ag-grid.schematic.spec.ts
  libs/components/packages/src/schematics/migrations/update-11/ag-grid/ag-grid.schematic.ts
  libs/components/pages/project.json
  libs/components/split-view/package.json
  libs/sdk/e2e-schematics/package.json
  libs/sdk/testing/package.json
  package-lock.json
  package.json
Labels: risk level (author): 1

#3041 fix(components/ag-grid): header should have readable text (#3037)
  libs/components/ag-grid/package.json
  libs/components/ag-grid/src/lib/modules/ag-grid/header/header.component.html
  libs/components/ag-grid/src/lib/modules/ag-grid/header/header.component.ts
  libs/components/packages/package.json
  libs/components/packages/src/schematics/ag-grid-migrate/ag-grid-migrate.schematic.spec.ts
  libs/components/packages/src/schematics/ag-grid-migrate/ag-grid-migrate.schematic.ts
  libs/components/packages/src/schematics/migrations/migration-collection.json
  libs/components/packages/src/schematics/migrations/update-12/ag-grid/ag-grid.schematic.spec.ts
  libs/components/packages/src/schematics/migrations/update-12/ag-grid/ag-grid.schematic.ts
  libs/components/packages/src/schematics/migrations/update-12/ag-grid/schema.json
  libs/components/packages/src/schematics/rules/workspace-check/workspace-check.spec.ts
  libs/components/packages/src/schematics/rules/workspace-check/workspace-check.ts
  libs/components/pages/project.json
  libs/components/split-view/package.json
  libs/sdk/e2e-schematics/package.json
  libs/sdk/testing/package.json
  libs/sdk/tools/package.json
  package-lock.json
  package.json
Labels: risk level (author): 1

#3038 chore: release 11.36.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease 11.x.x: pending

#3042 chore: changelog for 11.36.0 (#3038) 🍒
  CHANGELOG.md
Labels: risk level (author): 1, risk level (reviewer): 1

#3044 ci: run postbuild in ci
  .github/workflows/ci.yml
  libs/components/manifest/project.json
  nx.json
Labels: risk level (author): 1

#3045 ci: run postbuild in ci (#3044)
  .github/workflows/ci.yml
  libs/components/manifest/project.json
  nx.json
Labels: risk level (author): 1

#3043 feat(components/layout): tokenize description list styles
  apps/e2e/layout-storybook-e2e/src/e2e/description-list.component.cy.ts
  libs/components/layout/src/lib/modules/description-list/description-list.component.scss
Labels: risk level (author): 2

#3046 fix(components/pages): export `SkyNeedsAttentionItemHarness` for testing
  libs/components/pages/testing/src/public-api.ts
Labels: risk level (author): 1

#3047 fix(components/pages): export `SkyNeedsAttentionItemHarness` for testing (#3046)
  libs/components/pages/testing/src/public-api.ts
Labels: risk level (author): 1

#3049 fix(components/autonumeric): support negativeBracketsTypeOnBlur option
  libs/components/autonumeric/src/lib/modules/autonumeric/autonumeric.directive.spec.ts
  libs/components/autonumeric/src/lib/modules/autonumeric/autonumeric.directive.ts
Labels: risk level (author): 1

#3050 fix(components/autonumeric): support negativeBracketsTypeOnBlur option (#3049)
  libs/components/autonumeric/src/lib/modules/autonumeric/autonumeric.directive.spec.ts
  libs/components/autonumeric/src/lib/modules/autonumeric/autonumeric.directive.ts
Labels: risk level (author): 1

#3048 chore: release 11.36.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease 11.x.x: pending

#3051 chore: changelog for 11.36.1 (#3048) 🍒
  CHANGELOG.md
Labels: risk level (author): 1, risk level (reviewer): 1

#3003 chore: release 12.0.0-alpha.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#3053 fix(components/packages): remove v11 `ag-grid` schematic
  libs/components/packages/src/schematics/migrations/migration-collection.json
  libs/components/packages/src/schematics/migrations/update-12/ag-grid/ag-grid.schematic.spec.ts
  libs/components/packages/src/schematics/migrations/update-12/ag-grid/ag-grid.schematic.ts
  libs/components/packages/src/schematics/migrations/update-12/ag-grid/schema.json
Labels: risk level (author): 1

#3054 chore: release 12.0.0-alpha.2
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#3056 fix(components/ag-grid): datepicker cell editor should handle refresh refocus
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-editors/cell-editor-datepicker/cell-editor-datepicker.component.spec.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-editors/cell-editor-datepicker/cell-editor-datepicker.component.ts
Labels: risk level (author): 1

#3057 fix(components/ag-grid): datepicker cell editor should handle refresh refocus (#3056)
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-editors/cell-editor-datepicker/cell-editor-datepicker.component.spec.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/cell-editors/cell-editor-datepicker/cell-editor-datepicker.component.ts
Labels: risk level (author): 1

#3058 chore: release 11.36.2
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease 11.x.x: pending

#3060 chore: changelog for 11.36.2 (#3058) 🍒
  CHANGELOG.md
Labels: risk level (author): 1, risk level (reviewer): 1

#3067 fix(components/text-editor): value initializing for multiple text-editors
  apps/playground/src/app/components/text-editor/text-editor-series/text-editor-series.component.html
  apps/playground/src/app/components/text-editor/text-editor-series/text-editor-series.component.scss
  apps/playground/src/app/components/text-editor/text-editor-series/text-editor-series.component.ts
  apps/playground/src/app/components/text-editor/text-editor.module.ts
  apps/playground/src/app/components/text-editor/text-editor/text-editor.component.html
  apps/playground/src/app/home/home.component.ts
  libs/components/text-editor/src/lib/modules/text-editor/services/text-editor-adapter.service.spec.ts
  libs/components/text-editor/src/lib/modules/text-editor/services/text-editor-adapter.service.ts
Labels: risk level (author): 1

#3070 fix(components/text-editor): value initializing for multiple text-editors (#3067)
  apps/playground/src/app/components/text-editor/text-editor-series/text-editor-series.component.html
  apps/playground/src/app/components/text-editor/text-editor-series/text-editor-series.component.scss
  apps/playground/src/app/components/text-editor/text-editor-series/text-editor-series.component.ts
  apps/playground/src/app/components/text-editor/text-editor.module.ts
  apps/playground/src/app/components/text-editor/text-editor/text-editor.component.html
  apps/playground/src/app/home/home.component.ts
  libs/components/text-editor/src/lib/modules/text-editor/services/text-editor-adapter.service.spec.ts
  libs/components/text-editor/src/lib/modules/text-editor/services/text-editor-adapter.service.ts
Labels: risk level (author): 1

#3071 fix(components/forms): ensure form error always has `errorName` attribute for test harnesses
  libs/components/forms/src/lib/modules/form-error/form-error.component.ts
  libs/components/forms/testing/src/modules/form-error/form-errors-harness.spec.ts
Labels: risk level (author): 1

#3073 feat(components/forms)!: file attachment components now wait for system dialogs to close before handling files so that errors are read to screen readers appropriately
  libs/components/forms/src/lib/modules/file-attachment/file-attachment/file-attachment.component.spec.ts
  libs/components/forms/src/lib/modules/file-attachment/file-attachment/file-attachment.component.ts
  libs/components/forms/src/lib/modules/file-attachment/file-drop/file-drop.component.spec.ts
  libs/components/forms/src/lib/modules/file-attachment/file-drop/file-drop.component.ts
Labels: risk level (author): 3

#3063 feat: implement `@docsId` and `@docsIncludeIds` JSDoc tags to capture documentation relationships in the manifest
  .github/workflows/validate-pr.yml
  libs/components/manifest/package.json
  libs/components/manifest/src/__snapshots__/get-public-api.test.ts.snap
  libs/components/manifest/src/generator/__snapshots__/generate-manifest.test.ts.snap
  libs/components/manifest/src/generator/assign-docs-include-ids.ts
  libs/components/manifest/src/generator/generate-manifest.test.ts
  libs/components/manifest/src/generator/get-public-api.ts
  libs/components/manifest/src/generator/testing/fixtures/example-packages/foo/src/index.ts
  libs/components/manifest/src/generator/testing/fixtures/example-packages/foo/src/lib/foo.class.ts
  libs/components/manifest/src/generator/testing/fixtures/example-packages/foo/src/lib/foo.component.ts
  libs/components/manifest/src/generator/testing/fixtures/example-packages/foo/src/lib/foo.module.ts
  libs/components/manifest/src/generator/utility/get-class.ts
  libs/components/manifest/src/generator/utility/get-comment.ts
  libs/components/manifest/src/generator/utility/get-directive.ts
  libs/components/manifest/src/generator/utility/get-enum.ts
  libs/components/manifest/src/generator/utility/get-function.ts
  libs/components/manifest/src/generator/utility/get-interface.ts
  libs/components/manifest/src/generator/utility/get-type-alias.ts
  libs/components/manifest/src/generator/utility/get-variable.ts
  libs/components/manifest/src/get-public-api.test.ts
  libs/components/manifest/src/get-public-api.ts
  libs/components/manifest/src/types/base-def.ts
  libs/components/manifest/src/utils.test.ts
Labels: risk level (author): 1

#3069 feat(components/indicators)!: remove forwarded exports from `@skyux/help-inline` and `@skyux/icon`
  libs/components/indicators/src/index.ts
Labels: risk level (author): 2

#3072 fix(components/forms): ensure form error always has `errorName` attribute for test harnesses (#3071)
  libs/components/forms/src/lib/modules/form-error/form-error.component.ts
  libs/components/forms/testing/src/modules/form-error/form-errors-harness.spec.ts
Labels: risk level (author): 1

#3074 feat: add `@docsIncludeIds` to action bars, tree, autonumeric, avatar, colorpicker, core, datetime, errors, flyout, and forms packages
  libs/components/action-bars/src/lib/modules/summary-action-bar/summary-action-bar.module.ts
  libs/components/angular-tree-component/src/lib/modules/angular-tree/angular-tree.module.ts
  libs/components/autonumeric/src/lib/modules/autonumeric/autonumeric.module.ts
  libs/components/avatar/src/lib/modules/avatar/avatar.module.ts
  libs/components/colorpicker/src/lib/modules/colorpicker/colorpicker.module.ts
  libs/components/core/src/lib/modules/affix/affix.module.ts
  libs/components/core/src/lib/modules/dock/dock.service.ts
  libs/components/core/src/lib/modules/id/id.module.ts
  libs/components/core/src/lib/modules/media-query/media-query.service.ts
  libs/components/core/src/lib/modules/numeric/numeric.module.ts
  libs/components/core/src/lib/modules/percent-pipe/percent-pipe.module.ts
  libs/components/core/src/lib/modules/trim/trim.module.ts
  libs/components/core/src/lib/modules/viewkeeper/viewkeeper.module.ts
  libs/components/core/testing/src/modules/help/help-testing.module.ts
  libs/components/datetime/src/lib/modules/date-pipe/date-pipe.module.ts
  libs/components/datetime/src/lib/modules/date-range-picker/date-range-picker.module.ts
  libs/components/datetime/src/lib/modules/datepicker/datepicker.module.ts
  libs/components/datetime/src/lib/modules/timepicker/timepicker.module.ts
  libs/components/errors/src/lib/modules/error/error.module.ts
  libs/components/flyout/src/lib/modules/flyout/flyout.module.ts
  libs/components/forms/src/lib/modules/character-counter/character-counter.module.ts
  libs/components/forms/src/lib/modules/checkbox/checkbox.module.ts
  libs/components/forms/src/lib/modules/field-group/field-group.module.ts
  libs/components/forms/src/lib/modules/file-attachment/file-attachment/file-attachment.module.ts
  libs/components/forms/src/lib/modules/file-attachment/file-drop/file-drop.module.ts
  libs/components/forms/src/lib/modules/form-error/form-error.module.ts
  libs/components/forms/src/lib/modules/input-box/input-box.module.ts
  libs/components/forms/src/lib/modules/radio/radio.module.ts
  libs/components/forms/src/lib/modules/selection-box/selection-box.module.ts
  libs/components/forms/src/lib/modules/toggle-switch/toggle-switch.module.ts
Labels: risk level (author): 1

#3065 chore: release 11.37.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease 11.x.x: pending

#3075 chore: changelog for 11.37.0 (#3065) 🍒
  CHANGELOG.md
Labels: risk level (author): 1, risk level (reviewer): 1

#3061 feat(sdk/skyux-eslint): add linting rule to detect the use of legacy icons
  .cspell.json
  libs/sdk/skyux-eslint/docs/rules/template/no-legacy-icons.md
  libs/sdk/skyux-eslint/project.json
  libs/sdk/skyux-eslint/src/configs/template-all.ts
  libs/sdk/skyux-eslint/src/configs/template-recommended.ts
  libs/sdk/skyux-eslint/src/plugins/template-plugin.ts
  libs/sdk/skyux-eslint/src/rules/template/no-legacy-icons.spec.ts
  libs/sdk/skyux-eslint/src/rules/template/no-legacy-icons.ts
  libs/sdk/skyux-eslint/src/rules/template/utils/no-legacy-icons-mappings.ts
  libs/sdk/skyux-eslint/src/rules/template/utils/types.ts
Labels: risk level (author): 1

#3062 deprecation: deprecated action button icon `iconType` input and checkbox and radio button `icon` inputs in favor of new `iconName` input which utilizes SVG icons
  libs/components/data-manager/src/lib/modules/data-manager/data-manager-toolbar/data-manager-toolbar.component.html
  libs/components/data-manager/src/lib/modules/data-manager/models/data-view-config.ts
  libs/components/forms/src/lib/modules/checkbox/checkbox-group.component.html
  libs/components/forms/src/lib/modules/checkbox/checkbox.component.html
  libs/components/forms/src/lib/modules/checkbox/checkbox.component.spec.ts
  libs/components/forms/src/lib/modules/checkbox/checkbox.component.ts
  libs/components/forms/src/lib/modules/radio/fixtures/radio-single.component.fixture.html
  libs/components/forms/src/lib/modules/radio/fixtures/radio-single.component.fixture.ts
  libs/components/forms/src/lib/modules/radio/radio.component.html
  libs/components/forms/src/lib/modules/radio/radio.component.spec.ts
  libs/components/forms/src/lib/modules/radio/radio.component.ts
  libs/components/icon/src/lib/modules/icon/icon-svg.component.html
  libs/components/layout/src/lib/modules/action-button/action-button-icon.component.html
  libs/components/layout/src/lib/modules/action-button/action-button-icon.component.ts
  libs/components/layout/src/lib/modules/action-button/action-button.component.spec.ts
  libs/components/layout/src/lib/modules/action-button/action-button.module.ts
  libs/components/layout/src/lib/modules/action-button/fixtures/action-button.component.fixture.html
  libs/components/layout/src/lib/modules/action-button/fixtures/action-button.component.fixture.ts
  scripts/__snapshots__/deprecations.json
Labels: risk level (author): 1

#3079 fix(components/datetime): add missing harness exports
  apps/code-examples/src/app/code-examples/datetime/datepicker/basic/demo.component.spec.ts
  libs/components/datetime/testing/src/modules/datepicker/datepicker-calendar-harness.ts
  libs/components/datetime/testing/src/public-api.ts
Labels: risk level (author): 1

#3083 chore(code-examples): change eslint rule for legacy icons to warn for code examples
  apps/code-examples/eslint.config.js
Labels: risk level (author): 1

#3085 chore(code-examples): add skyux-eslint as an implicit dependency to the code-examples app
  apps/code-examples/project.json
Labels: risk level (author): 1

#3086 chore(code-examples): add skyux-eslint as an implicit dependency to the code-examples app (#3085)
  apps/code-examples/project.json
Labels: risk level (author): 1

#3088 fix(components/ag-grid): allow overriding grid min-height (#3077)
  libs/components/ag-grid/src/lib/modules/ag-grid/ag-grid-wrapper.component.html
  libs/components/ag-grid/src/lib/modules/ag-grid/ag-grid-wrapper.component.spec.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/ag-grid-wrapper.component.ts
  libs/components/ag-grid/src/lib/styles/_base.scss
Labels: risk level (author): 1

#3078 fix(components/ag-grid): row delete confirmation event handling
  libs/components/ag-grid/src/lib/modules/ag-grid/ag-grid-row-delete.directive.spec.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/ag-grid-row-delete.directive.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/fixtures/ag-grid-row-delete.component.fixture.ts
Labels: risk level (author): 1

#3089 fix(components/ag-grid): row delete confirmation event handling (#3078)
  libs/components/ag-grid/src/lib/modules/ag-grid/ag-grid-row-delete.directive.spec.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/ag-grid-row-delete.directive.ts
  libs/components/ag-grid/src/lib/modules/ag-grid/fixtures/ag-grid-row-delete.component.fixture.ts
Labels: risk level (author): 1

#3080 fix(components/datetime): add missing harness exports (#3079)
  apps/code-examples/src/app/code-examples/datetime/datepicker/basic/demo.component.spec.ts
  libs/components/datetime/testing/src/modules/datepicker/datepicker-calendar-harness.ts
  libs/components/datetime/testing/src/public-api.ts
Labels: risk level (author): 1
