Repository blackbaud/skyux, pull requests merged in 2025-07, with the labels that each got.

#3558 chore(components/filter-bar): add clear all values button
  libs/components/filter-bar/src/assets/locales/resources_en_US.json
  libs/components/filter-bar/src/lib/modules/filter-bar/filter-bar-item.component.ts
  libs/components/filter-bar/src/lib/modules/filter-bar/filter-bar.component.html
  libs/components/filter-bar/src/lib/modules/filter-bar/filter-bar.component.spec.ts
  libs/components/filter-bar/src/lib/modules/filter-bar/filter-bar.component.ts
  libs/components/filter-bar/src/lib/modules/filter-bar/fixtures/filter-bar.component.fixture.html
  libs/components/filter-bar/src/lib/modules/filter-bar/fixtures/filter-bar.component.fixture.ts
  libs/components/filter-bar/src/lib/modules/shared/sky-filter-bar-resources.module.ts
Labels: risk level (author): 1

#3566 chore(components/filter-bar): add clear all values button (#3558)
  libs/components/filter-bar/src/assets/locales/resources_en_US.json
  libs/components/filter-bar/src/lib/modules/filter-bar/filter-bar-item.component.ts
  libs/components/filter-bar/src/lib/modules/filter-bar/filter-bar.component.html
  libs/components/filter-bar/src/lib/modules/filter-bar/filter-bar.component.spec.ts
  libs/components/filter-bar/src/lib/modules/filter-bar/filter-bar.component.ts
  libs/components/filter-bar/src/lib/modules/filter-bar/fixtures/filter-bar.component.fixture.html
  libs/components/filter-bar/src/lib/modules/filter-bar/fixtures/filter-bar.component.fixture.ts
  libs/components/filter-bar/src/lib/modules/shared/sky-filter-bar-resources.module.ts
Labels: risk level (author): 1

#3554 fix(components/modals): update modal headers in v2 modern to use standard h2 font styles
  libs/components/modals/src/lib/modules/modal/modal-header.component.html
  libs/components/modals/src/lib/modules/modal/modal-header.component.scss
  libs/components/modals/src/lib/modules/modal/modal.component.html
Labels: risk level (author): 1

#3555 feat: update composite icons to use the new matte variables
  libs/components/help-inline/src/lib/modules/help-inline/help-inline.modern.component.scss
  libs/components/indicators/src/lib/modules/alert/alert.modern.component.scss
  libs/components/indicators/src/lib/modules/label/label.component.scss
  libs/components/indicators/src/lib/modules/status-indicator/status-indicator.component.scss
  libs/components/toast/src/lib/modules/toast/toast.component.scss
Labels: risk level (author): 1

#3576 feat: update composite icons to use the new matte variables (#3555)
  libs/components/help-inline/src/lib/modules/help-inline/help-inline.modern.component.scss
  libs/components/indicators/src/lib/modules/alert/alert.modern.component.scss
  libs/components/indicators/src/lib/modules/label/label.component.scss
  libs/components/indicators/src/lib/modules/status-indicator/status-indicator.component.scss
  libs/components/toast/src/lib/modules/toast/toast.component.scss
Labels: risk level (author): 1

#3575 chore(components/filter-bar): add confirmation to clear all filters action
  libs/components/filter-bar/src/assets/locales/resources_en_US.json
  libs/components/filter-bar/src/lib/modules/filter-bar/filter-bar.component.spec.ts
  libs/components/filter-bar/src/lib/modules/filter-bar/filter-bar.component.ts
  libs/components/filter-bar/src/lib/modules/filter-bar/fixtures/filter-bar.component.fixture.html
  libs/components/filter-bar/src/lib/modules/filter-bar/fixtures/filter-bar.component.fixture.ts
  libs/components/filter-bar/src/lib/modules/shared/sky-filter-bar-resources.module.ts
Labels: risk level (author): 1

#3577 feat: replace container tokens
  libs/components/modals/src/lib/modules/modal/modal.component.scss
  libs/components/tabs/src/lib/modules/vertical-tabset/vertical-tabset.component.scss
  libs/components/theme/package.json
  libs/components/theme/src/lib/styles/_layout-host.scss
  libs/components/tiles/src/lib/modules/tiles/tile-dashboard-column/tile-dashboard-column.component.scss
  libs/components/tiles/src/lib/modules/tiles/tile-dashboard/tile-dashboard.component.scss
  package-lock.json
  package.json
Labels: risk level (author): 2

#3580 chore(components/filter-bar): add confirmation to clear all filters action (#3575)
  libs/components/filter-bar/src/assets/locales/resources_en_US.json
  libs/components/filter-bar/src/lib/modules/filter-bar/filter-bar.component.spec.ts
  libs/components/filter-bar/src/lib/modules/filter-bar/filter-bar.component.ts
  libs/components/filter-bar/src/lib/modules/filter-bar/fixtures/filter-bar.component.fixture.html
  libs/components/filter-bar/src/lib/modules/filter-bar/fixtures/filter-bar.component.fixture.ts
  libs/components/filter-bar/src/lib/modules/shared/sky-filter-bar-resources.module.ts
Labels: risk level (author): 1

#3588 ci: don't cancel baseline e2e runs
  .github/workflows/e2e.yml
Labels: risk level (author): 1, skip e2e

#3585 fix: update all linting dependencies
  libs/components/storybook/package.json
  libs/sdk/eslint-config-skyux/package.json
  libs/sdk/skyux-eslint/package.json
  libs/sdk/skyux-stylelint/package.json
  libs/sdk/stylelint-schematics/package.json
  libs/sdk/stylelint-schematics/src/schematics/ng-add/ng-add.schematic.spec.ts
  package-lock.json
  package.json
Labels: risk level (author): 1

#3590 fix: update various dependencies
  libs/components/autonumeric/package.json
  libs/components/docs-tools/package.json
  libs/components/manifest-generator/package.json
  libs/components/packages/package.json
  libs/components/text-editor/package.json
  libs/components/validation/package.json
  libs/sdk/cypress-commands/package.json
  package-lock.json
  package.json
Labels: risk level (author): 2

#3570 feat(components/packages): create schematic to convert definition list to description list
  libs/components/packages/collection.json
  libs/components/packages/src/schematics/ng-generate/convert-definition-list-to-description-list/convert-definition-list-to-description-list.schematic.spec.ts
  libs/components/packages/src/schematics/ng-generate/convert-definition-list-to-description-list/convert-definition-list-to-description-list.schematic.ts
  libs/components/packages/src/schematics/ng-generate/convert-definition-list-to-description-list/schema.json
  libs/components/packages/src/schematics/ng-generate/convert-definition-list-to-description-list/schema.ts
  libs/components/packages/src/schematics/rules/convert-definition-list-to-description-list/convert-definition-list-to-description-list.spec.ts
  libs/components/packages/src/schematics/rules/convert-definition-list-to-description-list/convert-definition-list-to-description-list.ts
  libs/components/packages/src/schematics/utility/template.spec.ts
  libs/components/packages/src/schematics/utility/template.ts
  libs/components/packages/src/schematics/utility/typescript/ng-ast.spec.ts
  libs/components/packages/src/schematics/utility/typescript/ng-ast.ts
  libs/components/packages/src/schematics/utility/typescript/remove-import.spec.ts
  libs/components/packages/src/schematics/utility/typescript/remove-import.ts
  libs/components/packages/src/schematics/utility/typescript/swap-imported-class.spec.ts
  libs/components/packages/src/schematics/utility/typescript/swap-imported-class.ts
Labels: risk level (author): 1

#3589 fix(components/modals): fix punctuation in error messages
  libs/components/forms/src/assets/locales/resources_en_US.json
  libs/components/forms/src/lib/modules/shared/sky-forms-resources.module.ts
Labels: risk level (author): 1

#3598 fix(components/split-view): add background color to split view drawer and remove right border in v2 modern
  libs/components/split-view/src/lib/modules/split-view/split-view-drawer.component.scss
  libs/components/split-view/src/lib/modules/split-view/split-view.component.scss
Labels: risk level (author): 1

#3599 fix(components/split-view): add background color to split view drawer and remove right border in v2 modern (#3598)
  libs/components/split-view/src/lib/modules/split-view/split-view-drawer.component.scss
  libs/components/split-view/src/lib/modules/split-view/split-view.component.scss
Labels: risk level (author): 1

#3596 fix(components/help-inline): help inline uses line icon for modern v2
  libs/components/help-inline/src/lib/modules/help-inline/help-inline.component.html
Labels: risk level (author): 1

#3594 fix(components/lookup): multi-select lookup does not have extra left value space in v2 modern when no tokens are present
  libs/components/lookup/src/lib/modules/lookup/lookup.component.scss
Labels: risk level (author): 1

#3601 feat: use reference tokens for public API
  libs/components/theme/src/lib/styles/themes/modern/_custom-properties.scss
Labels: risk level (author): 1

#3593 fix(components/forms): input box hint text and errors have left margin in v2 modern
  libs/components/forms/src/lib/modules/input-box/input-box.component.scss
Labels: risk level (author): 2

#3607 fix(components/forms): input box hint text and errors have left margin in v2 modern (#3593)
  libs/components/forms/src/lib/modules/input-box/input-box.component.scss
Labels: risk level (author): 2

#3606 ci: run migrations during cherry-pick workflow
  .github/workflows/cherry-pick.yml
Labels: risk level (author): 1, skip e2e

#3595 fix(components/modals): fix punctuation in error messages (#3589)
  libs/components/forms/src/assets/locales/resources_en_US.json
  libs/components/forms/src/lib/modules/shared/sky-forms-resources.module.ts
Labels: risk level (author): 1

#3608 fix(components/forms): help inline is aligned with field group text in v2 modern
  libs/components/forms/src/lib/modules/field-group/field-group.component.scss
Labels: risk level (author): 1

#3611 fix(components/forms): help inline is aligned with field group text in v2 modern (#3608)
  libs/components/forms/src/lib/modules/field-group/field-group.component.scss
Labels: risk level (author): 1

#3615 ci: e2e read build id from logs
  .github/actions/e2e-affected/action.yml
  .github/workflows/e2e.yml
  libs/sdk/e2e-schematics/src/workflow/index.ts
  libs/sdk/e2e-schematics/src/workflow/percy-api/percy-api.spec.ts
  libs/sdk/e2e-schematics/src/workflow/percy-api/percy-api.ts
  libs/sdk/e2e-schematics/src/workflow/percy-api/read-build-number-from-logs.spec.ts
  libs/sdk/e2e-schematics/src/workflow/percy-api/read-build-number-from-logs.ts
  libs/sdk/e2e-schematics/src/workflow/verify-e2e/verify-e2e.spec.ts
  libs/sdk/e2e-schematics/src/workflow/verify-e2e/verify-e2e.ts
Labels: risk level (author): 1, skip e2e

#3618 feat: button and dropdown elevations (#3610)
  libs/components/theme/package.json
  libs/components/theme/src/lib/styles/themes/modern/_buttons.scss
  package-lock.json
  package.json
Labels: risk level (author): 1

#3563 chore: release 12.24.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease 12.x.x: pending

#3620 feat(components/packages): create schematic to convert definition list to description list (#3570)
  libs/components/packages/collection.json
  libs/components/packages/src/schematics/ng-generate/convert-definition-list-to-description-list/convert-definition-list-to-description-list.schematic.spec.ts
  libs/components/packages/src/schematics/ng-generate/convert-definition-list-to-description-list/convert-definition-list-to-description-list.schematic.ts
  libs/components/packages/src/schematics/ng-generate/convert-definition-list-to-description-list/schema.json
  libs/components/packages/src/schematics/ng-generate/convert-definition-list-to-description-list/schema.ts
  libs/components/packages/src/schematics/rules/convert-definition-list-to-description-list/convert-definition-list-to-description-list.spec.ts
  libs/components/packages/src/schematics/rules/convert-definition-list-to-description-list/convert-definition-list-to-description-list.ts
  libs/components/packages/src/schematics/utility/template.spec.ts
  libs/components/packages/src/schematics/utility/template.ts
  libs/components/packages/src/schematics/utility/typescript/ng-ast.spec.ts
  libs/components/packages/src/schematics/utility/typescript/ng-ast.ts
  libs/components/packages/src/schematics/utility/typescript/remove-import.spec.ts
  libs/components/packages/src/schematics/utility/typescript/remove-import.ts
  libs/components/packages/src/schematics/utility/typescript/swap-imported-class.spec.ts
  libs/components/packages/src/schematics/utility/typescript/swap-imported-class.ts
Labels: risk level (author): 1

#3619 chore: changelog for 12.24.0 (#3563) 🍒
  CHANGELOG.md
Labels: risk level (author): 1

#3617 fix: selected horizontal and vertical tabs use medium border in v2 modern
  libs/components/tabs/src/lib/modules/vertical-tabset/vertical-tab.component.scss
  libs/components/theme/src/lib/styles/themes/modern/_buttons.scss
Labels: risk level (author): 1

#3621 chore: release 12.25.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease 12.x.x: pending

#3623 fix(components/tabs): vertical tabs use nav border color tokens
  libs/components/tabs/src/lib/modules/vertical-tabset/vertical-tab.component.scss
  libs/components/theme/package.json
  package-lock.json
  package.json
Labels: risk level (author): 1

#3632 fix(components/tabs): vertical tabs use nav border color tokens (#3623)
  libs/components/tabs/src/lib/modules/vertical-tabset/vertical-tab.component.scss
  libs/components/theme/package.json
  package-lock.json
  package.json
Labels: risk level (author): 1

#3631 feat: add input and input button elevations
  libs/components/forms/src/lib/modules/input-box/input-box.component.scss
Labels: risk level (author): 1

#3626 fix(components/forms): select inputs use updated icon in v2 modern
  libs/components/forms/src/lib/modules/input-box/input-box.component.scss
  libs/components/theme/src/lib/styles/themes/modern/_forms.scss
Labels: risk level (author): 1

#3637 fix(components/forms): select inputs use updated icon in v2 modern (#3626)
  libs/components/forms/src/lib/modules/input-box/input-box.component.scss
  libs/components/theme/src/lib/styles/themes/modern/_forms.scss
Labels: risk level (author): 1

#3638 feat(components/icon): upgrade icons library to version 9 (#3635)
  libs/components/docs-tools/src/lib/modules/code-example-viewer/stackblitz.service.spec.ts
  libs/components/docs-tools/src/lib/modules/code-example-viewer/stackblitz.service.ts
  libs/components/icon/src/lib/modules/icon/icon-svg-resolver.service.spec.ts
  libs/components/icon/src/lib/modules/icon/icon-svg-resolver.service.ts
  libs/components/packages/package.json
  libs/components/theme/package.json
  libs/components/theme/src/lib/styles/sky.scss
  package-lock.json
  package.json
Labels: risk level (author): 1

#3636 fix(components/tabs): tabs use new tab color tokens
  libs/components/theme/src/lib/styles/themes/modern/_buttons.scss
Labels: risk level (author): 1

#3633 feat(components/theme): add brand registry with URL and SRI hash
  .cspell.json
  libs/components/theme/src/lib/theming/theme-brand.spec.ts
  libs/components/theme/src/lib/theming/theme-brand.ts
  libs/components/theme/src/lib/theming/theme-serialization-types.ts
  libs/components/theme/src/lib/theming/theme.service.spec.ts
  libs/components/theme/src/lib/theming/theme.service.ts
Labels: risk level (author): 2

#3649 feat(components/theme): add brand registry with URL and SRI hash (#3633)
  .cspell.json
  libs/components/theme/src/lib/theming/theme-brand.spec.ts
  libs/components/theme/src/lib/theming/theme-brand.ts
  libs/components/theme/src/lib/theming/theme-serialization-types.ts
  libs/components/theme/src/lib/theming/theme.service.spec.ts
  libs/components/theme/src/lib/theming/theme.service.ts
Labels: risk level (author): 2

#3647 fix(components/forms): standalone checkboxes and radios use less hint text space in v2 modern (#3645)
  libs/components/forms/src/lib/modules/checkbox/checkbox.modern.component.scss
  libs/components/forms/src/lib/modules/radio/radio.component.scss
Labels: risk level (author): 1

#3654 fix(components/lookup): search component uses deemphasized placeholder color in v2 modern (#3646)
  libs/components/lookup/src/lib/modules/search/search.component.scss
Labels: risk level (author): 1

#3652 chore(components/forms): add more robust logic to showing error states in checkbox visual tests
  apps/e2e/forms-storybook-e2e/src/e2e/checkbox.component.cy.ts
Labels: risk level (author): 1

#3657 chore: add visual tests and playground for card (#3650)
  apps/e2e/layout-storybook-e2e/src/e2e/card.component.cy.ts
  apps/e2e/layout-storybook/src/app/card/card.component.html
  apps/e2e/layout-storybook/src/app/card/card.component.scss
  apps/e2e/layout-storybook/src/app/card/card.component.stories.ts
  apps/e2e/layout-storybook/src/app/card/card.component.ts
  apps/e2e/layout-storybook/src/app/card/card.module.ts
  apps/playground/src/app/components/layout/card/card-routing.module.ts
  apps/playground/src/app/components/layout/card/card.component.html
  apps/playground/src/app/components/layout/card/card.component.ts
  apps/playground/src/app/components/layout/card/card.module.ts
  apps/playground/src/app/components/layout/layout.module.ts
Labels: risk level (author): 1

#3660 fix(components/lists): selected sort item uses medium border width in v2 modern (#3656)
  libs/components/lists/src/lib/modules/sort/sort-item.component.scss
Labels: risk level (author): 1

#3662 feat(components/layout): remove secondary button overrides in modern v2 toolbar (#3643)
  apps/playground/src/app/components/layout/toolbar/toolbar.component.html
  libs/components/layout/src/lib/modules/toolbar/toolbar-item.component.scss
Labels: risk level (author): 1

#3669 fix: checkboxes, radios, and toggle switches use deemphasized label color when the switch is disabled in v2 modern (#3665)
  libs/components/forms/src/lib/modules/toggle-switch/toggle-switch.component.scss
  libs/components/theme/src/lib/styles/themes/modern/_switch.scss
Labels: risk level (author): 1

#3670 feat(components/theme): pull in latest design tokens, allow major version only for brand version
  libs/components/theme/package.json
  libs/components/theme/src/lib/theming/theme-brand.spec.ts
  libs/components/theme/src/lib/theming/theme-brand.ts
  package-lock.json
  package.json
Labels: risk level (author): 1

#3671 chore: changelog for 12.27.0 (#3653) 🍒
  CHANGELOG.md
Labels: risk level (author): 1

#3672 fix: update border colors and remove list and fit layout horizontal space in v2 modern
  libs/components/theme/package.json
  package-lock.json
  package.json
Labels: risk level (author): 1

#3675 fix: update border colors and remove list and fit layout horizontal space in v2 modern (#3672)
  libs/components/theme/package.json
  package-lock.json
  package.json
Labels: risk level (author): 1

#3668 fix(components/lists): remove hover and active state from `collapsible` items
  libs/components/lists/src/lib/modules/repeater/repeater-item.component.scss
Labels: risk level (author): 1

#3659 fix(components/packages): updated the `ng add` schematic to configure a workspace with a single project; workspaces with multiple projects should use the `add-skyux-to-project` schematic
  libs/components/packages/README.md
  libs/components/packages/collection.json
  libs/components/packages/migrations.json
  libs/components/packages/project.json
  libs/components/packages/src/schematics/migrations/update-13/i18n-resources-module/i18n-resources-module.schematic.spec.ts
  libs/components/packages/src/schematics/migrations/update-13/i18n-resources-module/i18n-resources-module.schematic.ts
  libs/components/packages/src/schematics/migrations/update-13/remove-old-compat-stylesheets/remove-old-compat-stylesheets.schematic.spec.ts
  libs/components/packages/src/schematics/ng-add/__snapshots__/ng-add.schematic.spec.ts.snap
  libs/components/packages/src/schematics/ng-add/ng-add.schematic.spec.ts
  libs/components/packages/src/schematics/ng-add/ng-add.schematic.ts
  libs/components/packages/src/schematics/ng-add/schema.json
  libs/components/packages/src/schematics/ng-add/schema.ts
  libs/components/packages/src/schematics/ng-generate/add-ag-grid-styles/add-ag-grid-styles.schematic.spec.ts
  libs/components/packages/src/schematics/ng-generate/add-skyux-to-project/add-skyux-to-project.schematic.spec.ts
  libs/components/packages/src/schematics/ng-generate/add-skyux-to-project/add-skyux-to-project.schematic.ts
  libs/components/packages/src/schematics/ng-generate/add-skyux-to-project/schema.json
  libs/components/packages/src/schematics/ng-generate/add-skyux-to-project/schema.ts
  libs/components/packages/src/schematics/ng-generate/convert-definition-list-to-description-list/convert-definition-list-to-description-list.schematic.ts
  libs/components/packages/src/schematics/ng-generate/polyfills/polyfills.schematic.spec.ts
  libs/components/packages/src/schematics/ng-generate/polyfills/polyfills.schematic.ts
  libs/components/packages/src/schematics/ng-generate/polyfills/schema.json
  libs/components/packages/src/schematics/ng-generate/polyfills/schema.ts
  libs/components/packages/src/schematics/ng-generate/remove-compat-stylesheets/remove-compat-stylesheets.schematic.ts
  libs/components/packages/src/schematics/rules/add-ag-grid-styles-config.ts
  libs/components/packages/src/schematics/rules/add-commonjs-config.spec.ts
  libs/components/packages/src/schematics/rules/add-commonjs-config.ts
  libs/components/packages/src/schematics/rules/add-polyfills-config.spec.ts
  libs/components/packages/src/schematics/rules/add-polyfills-config.ts
  libs/components/packages/src/schematics/rules/apply-skyux-stylesheets-to-workspace.ts
  libs/components/packages/src/schematics/rules/install-angular-cdk.spec.ts
  libs/components/packages/src/schematics/rules/install-angular-cdk.ts
  libs/components/packages/src/schematics/rules/workspace-check/workspace-check.ts
  libs/components/packages/src/schematics/utility/move-class-to-library.spec.ts
  libs/components/packages/src/schematics/utility/move-class-to-library.ts
  libs/components/packages/src/schematics/utility/regex.ts
  libs/components/packages/src/schematics/utility/theme.ts
  libs/components/packages/src/schematics/utility/tree.ts
  libs/components/packages/src/schematics/utility/workspace.ts
Labels: risk level (author): 2

#3676 fix(components/lists): remove hover and active state from `collapsible` items (#3668)
  libs/components/lists/src/lib/modules/repeater/repeater-item.component.scss
Labels: risk level (author): 1

#3667 feat(components/ag-grid): update unchecked checkbox cell renderer color tokens
  libs/components/ag-grid/src/lib/styles/_overrides.scss
  libs/components/ag-grid/src/lib/styles/ag-grid-theme.ts
Labels: risk level (author): 1

#3565 chore: release 13.0.0-alpha.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#3678 feat(components/ag-grid): update unchecked checkbox cell renderer color tokens (#3667)
  libs/components/ag-grid/src/lib/styles/_overrides.scss
  libs/components/ag-grid/src/lib/styles/ag-grid-theme.ts
Labels: risk level (author): 1

#3673 chore: release 12.28.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease 12.x.x: pending

#3680 fix(components/tiles): tile tools items are center aligned (#3677)
  apps/playground/src/app/components/tiles/tile-dashboard/tile1.component.html
  apps/playground/src/app/components/tiles/tile-dashboard/tile1.component.ts
  apps/playground/src/app/components/tiles/tile-dashboard/tile2.component.html
  apps/playground/src/app/components/tiles/tile-dashboard/tile2.component.ts
  apps/playground/src/app/components/tiles/tile-dashboard/tile3.component.ts
  libs/components/tiles/src/lib/modules/tiles/tile/tile.component.scss
Labels: risk level (author): 1

#3655 test(components/filter-bar): add filter bar test harnesses
  libs/components/filter-bar/project.json
  libs/components/filter-bar/src/lib/modules/filter-bar/filter-bar-item.component.html
  libs/components/filter-bar/src/lib/modules/filter-bar/filter-bar-item.component.spec.ts
  libs/components/filter-bar/src/lib/modules/filter-bar/filter-bar-item.component.ts
  libs/components/filter-bar/src/lib/modules/filter-bar/filter-bar.component.html
  libs/components/filter-bar/testing/eslint.config.js
  libs/components/filter-bar/testing/karma.conf.js
  libs/components/filter-bar/testing/ng-package.json
  libs/components/filter-bar/testing/project.json
  libs/components/filter-bar/testing/src/modules/filter-bar/filter-bar-harness-filters.ts
  libs/components/filter-bar/testing/src/modules/filter-bar/filter-bar-harness.spec.ts
  libs/components/filter-bar/testing/src/modules/filter-bar/filter-bar-harness.ts
  libs/components/filter-bar/testing/src/modules/filter-bar/filter-bar-item-harness-filters.ts
  libs/components/filter-bar/testing/src/modules/filter-bar/filter-bar-item-harness.ts
  libs/components/filter-bar/testing/src/modules/filter-bar/fixtures/filter-bar-harness-test.component.html
  libs/components/filter-bar/testing/src/modules/filter-bar/fixtures/filter-bar-harness-test.component.ts
  libs/components/filter-bar/testing/src/public-api.ts
  libs/components/filter-bar/testing/tsconfig.spec.json
  tsconfig.base.json
Labels: risk level (author): 1

#3682 chore: changelog for 12.28.0 (#3673) 🍒
  CHANGELOG.md
Labels: risk level (author): 1

#3683 test(components/filter-bar): add filter bar test harnesses (#3655)
  libs/components/filter-bar/project.json
  libs/components/filter-bar/src/lib/modules/filter-bar/filter-bar-item.component.html
  libs/components/filter-bar/src/lib/modules/filter-bar/filter-bar-item.component.spec.ts
  libs/components/filter-bar/src/lib/modules/filter-bar/filter-bar-item.component.ts
  libs/components/filter-bar/src/lib/modules/filter-bar/filter-bar.component.html
  libs/components/filter-bar/testing/eslint.config.js
  libs/components/filter-bar/testing/karma.conf.js
  libs/components/filter-bar/testing/ng-package.json
  libs/components/filter-bar/testing/project.json
  libs/components/filter-bar/testing/src/modules/filter-bar/filter-bar-harness-filters.ts
  libs/components/filter-bar/testing/src/modules/filter-bar/filter-bar-harness.spec.ts
  libs/components/filter-bar/testing/src/modules/filter-bar/filter-bar-harness.ts
  libs/components/filter-bar/testing/src/modules/filter-bar/filter-bar-item-harness-filters.ts
  libs/components/filter-bar/testing/src/modules/filter-bar/filter-bar-item-harness.ts
  libs/components/filter-bar/testing/src/modules/filter-bar/fixtures/filter-bar-harness-test.component.html
  libs/components/filter-bar/testing/src/modules/filter-bar/fixtures/filter-bar-harness-test.component.ts
  libs/components/filter-bar/testing/src/public-api.ts
  libs/components/filter-bar/testing/tsconfig.spec.json
  tsconfig.base.json
Labels: risk level (author): 1

#3686 fix: ag-grid and repeater rows use row background base color token in v2 modern (#3684)
  libs/components/ag-grid/src/lib/styles/_overrides.scss
  libs/components/ag-grid/src/lib/styles/ag-grid-theme.ts
  libs/components/lists/src/lib/modules/repeater/repeater-item.component.scss
  libs/components/theme/package.json
  package-lock.json
  package.json
Labels: risk level (author): 1

#3681 chore: release 13.0.0-alpha.2
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#3691 fix(components/packages): fix "noop" migration path
  libs/components/packages/migrations.json
  libs/components/packages/src/schematics/migrations/noop/noop.schematic.spec.ts
Labels: risk level (author): 1

#3690 fix: selected tabs use new text and background color tokens, disabled toggle switches use updated tokens, and typography tokens are updated in v2 modern (#3688)
  libs/components/popovers/src/lib/modules/dropdown/dropdown.component.scss
  libs/components/theme/package.json
  libs/components/theme/src/lib/styles/themes/modern/_buttons.scss
  package-lock.json
  package.json
Labels: risk level (author): 1

#3685 chore: release 12.28.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease 12.x.x: pending

#3693 chore: changelog for 12.28.1 (#3685) 🍒
  CHANGELOG.md
Labels: risk level (author): 1

#3692 chore: release 13.0.0-alpha.3
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease main: pending

#3697 fix(components/forms): toggle has a base background color in v2 modern (#3694)
  libs/components/forms/src/lib/modules/toggle-switch/toggle-switch.component.scss
Labels: risk level (author): 1

#3698 chore: bump design token library to `alpha.7`
  libs/components/theme/package.json
  package-lock.json
  package.json
Labels: risk level (author): 1

#3700 feat: pull in latest design tokens
  libs/components/theme/package.json
  package-lock.json
  package.json
Labels: risk level (author): 1

#3696 feat: remove `background-color` from inline buttons for all states
  libs/components/flyout/src/lib/modules/flyout/flyout.component.scss
  libs/components/theme/src/lib/styles/themes/modern/_buttons.scss
Labels: risk level (author): 1

#3695 chore: release 12.29.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease 12.x.x: pending

#3704 chore: changelog for 12.29.0 (#3695) 🍒
  CHANGELOG.md
Labels: risk level (author): 1

#3702 feat: remove `background-color` from inline buttons for all states (#3696)
  libs/components/flyout/src/lib/modules/flyout/flyout.component.scss
  libs/components/theme/src/lib/styles/themes/modern/_buttons.scss
Labels: risk level (author): 1

#3687 feat: replace `font-weight` tokens with `font-style`
  libs/components/colorpicker/src/lib/modules/colorpicker/colorpicker.component.scss
  libs/components/forms/src/lib/modules/file-attachment/file-drop/file-drop.component.scss
  libs/components/forms/src/lib/modules/file-attachment/file-drop/file-item.component.scss
  libs/components/forms/src/lib/modules/input-box/input-box.component.scss
  libs/components/forms/src/lib/modules/selection-box/selection-box-grid.component.scss
  libs/components/layout/src/lib/modules/description-list/description-list.component.scss
  libs/components/lists/src/lib/modules/filter/filter-summary.component.scss
  libs/components/lists/src/lib/modules/sort/sort-item.component.scss
  libs/components/modals/src/lib/modules/modal/modal-header.component.scss
  libs/components/navbar/src/lib/modules/navbar/navbar-item.component.scss
  libs/components/popovers/src/lib/modules/dropdown/dropdown.component.scss
  libs/components/text-editor/src/lib/modules/text-editor/text-editor.component.scss
  libs/components/theme/src/lib/styles/themes/modern/_buttons.scss
  libs/components/theme/src/lib/styles/themes/modern/_theme.scss
  libs/components/theme/src/lib/styles/themes/modern/_type.scss
Labels: risk level (author): 1

#3706 feat(components/layout): tokenize card styles (#3703)
  libs/components/layout/src/lib/modules/card/card-actions.component.scss
  libs/components/layout/src/lib/modules/card/card-actions.component.ts
  libs/components/layout/src/lib/modules/card/card.component.html
  libs/components/layout/src/lib/modules/card/card.component.scss
  libs/components/theme/src/lib/styles/themes/modern/_switch.scss
Labels: risk level (author): 2

#3709 chore: bump design token library to `alpha.7` (#3698)
  libs/components/theme/package.json
  package-lock.json
  package.json
Labels: risk level (author): 1

#3708 feat: replace `font-weight` tokens with `font-style` (#3687)
  libs/components/colorpicker/src/lib/modules/colorpicker/colorpicker.component.scss
  libs/components/forms/src/lib/modules/file-attachment/file-drop/file-drop.component.scss
  libs/components/forms/src/lib/modules/file-attachment/file-drop/file-item.component.scss
  libs/components/forms/src/lib/modules/input-box/input-box.component.scss
  libs/components/forms/src/lib/modules/selection-box/selection-box-grid.component.scss
  libs/components/layout/src/lib/modules/description-list/description-list.component.scss
  libs/components/lists/src/lib/modules/filter/filter-summary.component.scss
  libs/components/lists/src/lib/modules/sort/sort-item.component.scss
  libs/components/modals/src/lib/modules/modal/modal-header.component.scss
  libs/components/navbar/src/lib/modules/navbar/navbar-item.component.scss
  libs/components/popovers/src/lib/modules/dropdown/dropdown.component.scss
  libs/components/text-editor/src/lib/modules/text-editor/text-editor.component.scss
  libs/components/theme/src/lib/styles/themes/modern/_buttons.scss
  libs/components/theme/src/lib/styles/themes/modern/_theme.scss
  libs/components/theme/src/lib/styles/themes/modern/_type.scss
Labels: risk level (author): 1

#3715 fix(components/datetime): datepicker callendar header uses standard button styles in v2 modern (#3707)
  libs/components/datetime/src/lib/modules/datepicker/calendar/datepicker-calendar-inner.component.html
  libs/components/datetime/src/lib/modules/datepicker/calendar/datepicker-calendar-inner.component.scss
  libs/components/datetime/src/lib/modules/datepicker/calendar/datepicker-calendar-inner.component.ts
Labels: risk level (author): 2

#3717 fix(components/forms): toggle switch uses active border width token in v2 modern
  libs/components/forms/src/lib/modules/toggle-switch/toggle-switch.component.scss
Labels: risk level (author): 1

#3716 fix(components/angular-tree-component): tree view uses nav color tokens in v2 modern
  libs/components/angular-tree-component/src/lib/modules/angular-tree/angular-tree-wrapper.component.scss
Labels: risk level (author): 1

#3722 fix(components/angular-tree-component): tree view uses nav color tokens in v2 modern (#3716)
  libs/components/angular-tree-component/src/lib/modules/angular-tree/angular-tree-wrapper.component.scss
Labels: risk level (author): 1

#3727 fix(components/tabs): tab close buttons have border radius and no browser outline in v2 modern (#3724)
  libs/components/tabs/src/lib/modules/tabs/tab-button.component.scss
Labels: risk level (author): 1

#3714 feat(components/lookup): lookup no longer displays a search icon when `showMore` is not enabled
  libs/components/lookup/src/lib/modules/lookup/lookup.component.html
  libs/components/lookup/src/lib/modules/lookup/lookup.component.ts
Labels: risk level (author): 1

#3726 fix(components/tabs): dropdown tab menu uses medium left selected border in v2 modern
  libs/components/theme/src/lib/styles/themes/modern/_buttons.scss
Labels: risk level (author): 1

#3731 feat(components/tabs): add token for disabled tabs in wizard (#3725)
  libs/components/tabs/src/lib/modules/tabs/tab-button.component.scss
Labels: risk level (author): 1

#3728 fix(components/tabs): selected vertical tabs do not show the hover and active interactive state in v2 modern
  libs/components/tabs/src/lib/modules/vertical-tabset/vertical-tab.component.scss
Labels: risk level (author): 1

#3733 fix(components/tabs): dropdown tab menu uses medium left selected border in v2 modern (#3726)
  libs/components/theme/src/lib/styles/themes/modern/_buttons.scss
Labels: risk level (author): 1

#3734 fix(components/tabs): selected vertical tabs do not show the hover and active interactive state in v2 modern (#3728)
  libs/components/tabs/src/lib/modules/vertical-tabset/vertical-tab.component.scss
Labels: risk level (author): 1

#3721 feat(components/tabs): tab dropdowns have interactive state styles in v2 modern
  libs/components/popovers/src/lib/modules/dropdown/dropdown.component.scss
  libs/components/tabs/src/lib/modules/tabs/tabset.component.scss
Labels: risk level (author): 2

#3741 fix(components/theme): icon switch components are sized based on the icon size in v2 modern (#3723)
  libs/components/theme/src/lib/styles/themes/modern/_switch.scss
Labels: risk level (author): 2

#3737 fix(components/text-editor): remove `background-color` to show border and change spacing token from `xl` to `m` (#3729)
  libs/components/text-editor/src/lib/modules/text-editor/text-editor.component.scss
Labels: risk level (author): 1

#3743 feat(components/lists): remove hover state from selected sort item (#3730)
  libs/components/lists/src/lib/modules/sort/sort-item.component.scss
Labels: risk level (author): 1

#3740 fix(components/theme): components using the layout host use component tokens for link area margin
  libs/components/theme/src/lib/styles/_layout-host.scss
Labels: risk level (author): 1

#3749 chore: list view grid playground and visual tests
  apps/e2e/lists-storybook-e2e/src/e2e/list-view-grid.component.cy.ts
  apps/e2e/lists-storybook/src/app/list-view-grid/list-view-grid.component.html
  apps/e2e/lists-storybook/src/app/list-view-grid/list-view-grid.component.stories.ts
  apps/e2e/lists-storybook/src/app/list-view-grid/list-view-grid.component.ts
  apps/e2e/lists-storybook/src/app/list-view-grid/list-view-grid.module.ts
  apps/e2e/lists-storybook/tsconfig.json
  apps/playground/src/app/components/lists/list-view-grid/list-view-grid.component.html
  apps/playground/src/app/components/lists/list-view-grid/list-view-grid.component.ts
  apps/playground/src/app/components/lists/lists.module.ts
Labels: risk level (author): 1

#3754 fix(components/forms): radio buttons do not use interactive styling when checked in v2 modern (#3746)
  libs/components/forms/src/lib/modules/radio/radio.component.scss
  libs/components/theme/src/lib/styles/themes/modern/_switch.scss
Labels: risk level (author): 2

#3755 fix(components/datetime): timepicker buttons use a set size in v2 modern (#3742)
  apps/playground/src/app/components/datetime/timepicker/timepicker.component.html
  libs/components/datetime/src/lib/modules/timepicker/timepicker.component.html
  libs/components/datetime/src/lib/modules/timepicker/timepicker.component.scss
Labels: risk level (author): 1

#3736 fix(components/forms): selection box uses interactive states in v2 modern
  libs/components/forms/src/lib/modules/selection-box/selection-box.component.scss
Labels: risk level (author): 2

#3758 fix(components/forms): selection box uses interactive states in v2 modern (#3736)
  libs/components/forms/src/lib/modules/selection-box/selection-box.component.scss
Labels: risk level (author): 2

#3760 feat(components/theme): allow undefined value to be passed to SkyThemeService.setThemeBrand() to clear branding
  libs/components/theme/src/lib/theming/theme.service.spec.ts
  libs/components/theme/src/lib/theming/theme.service.ts
Labels: risk level (author): 2

#3769 chore: fix datepicker e2e tests to be more consistent
  apps/e2e/datetime-storybook-e2e/src/e2e/datepicker.component.cy.ts
  apps/e2e/datetime-storybook/src/app/datepicker/datepicker.component.ts
Labels: risk level (author): 1

#3770 chore: fix datepicker e2e tests to be more consistent (#3769)
  apps/e2e/datetime-storybook-e2e/src/e2e/datepicker.component.cy.ts
  apps/e2e/datetime-storybook/src/app/datepicker/datepicker.component.ts
Labels: risk level (author): 1

#3761 feat(components/theme): update tokens from `page` to `layout`
  libs/components/tabs/src/lib/modules/tabs/tabset.component.scss
  libs/components/theme/package.json
  libs/components/theme/src/lib/styles/_layout-host.scss
  package-lock.json
  package.json
Labels: risk level (author): 2

#3763 feat(components/forms): checkbox uses a component token to set its border radius in modern theme
  libs/components/forms/src/lib/modules/checkbox/checkbox.modern.component.scss
  libs/components/theme/package.json
  package-lock.json
  package.json
Labels: risk level (author): 1

#3771 chore(components/filter-bar): remove filter bar summary component
  apps/e2e/filter-bar-storybook/src/app/filter-bar/filter-bar.component.html
  apps/playground/src/app/components/filter-bar/filter-bar/filter-bar.component.html
  libs/components/filter-bar/package.json
  libs/components/filter-bar/src/index.ts
  libs/components/filter-bar/src/lib/modules/filter-bar/filter-bar-summary-item.component.html
  libs/components/filter-bar/src/lib/modules/filter-bar/filter-bar-summary-item.component.scss
  libs/components/filter-bar/src/lib/modules/filter-bar/filter-bar-summary-item.component.spec.ts
  libs/components/filter-bar/src/lib/modules/filter-bar/filter-bar-summary-item.component.ts
  libs/components/filter-bar/src/lib/modules/filter-bar/filter-bar-summary.component.html
  libs/components/filter-bar/src/lib/modules/filter-bar/filter-bar-summary.component.scss
  libs/components/filter-bar/src/lib/modules/filter-bar/filter-bar-summary.component.spec.ts
  libs/components/filter-bar/src/lib/modules/filter-bar/filter-bar-summary.component.ts
  libs/components/filter-bar/src/lib/modules/filter-bar/filter-bar.component.html
  libs/components/filter-bar/src/lib/modules/filter-bar/filter-bar.module.ts
Labels: risk level (author): 1

#3747 feat(components/split-view): add responsive padding around repeater in split view drawer
  apps/e2e/split-view-storybook-e2e/src/e2e/split-view.component.cy.ts
  apps/e2e/split-view-storybook/src/app/split-view/split-view.component.html
  apps/e2e/split-view-storybook/src/app/split-view/split-view.component.stories.ts
  apps/e2e/split-view-storybook/src/app/split-view/split-view.component.ts
  apps/e2e/split-view-storybook/src/app/split-view/split-view.module.ts
  libs/components/split-view/src/lib/modules/split-view/split-view-drawer.component.scss
Labels: risk level (author): 1

#3777 feat(components/split-view): add responsive padding around repeater in split view drawer (#3747)
  apps/e2e/split-view-storybook-e2e/src/e2e/split-view.component.cy.ts
  apps/e2e/split-view-storybook/src/app/split-view/split-view.component.html
  apps/e2e/split-view-storybook/src/app/split-view/split-view.component.stories.ts
  apps/e2e/split-view-storybook/src/app/split-view/split-view.component.ts
  apps/e2e/split-view-storybook/src/app/split-view/split-view.module.ts
  libs/components/split-view/src/lib/modules/split-view/split-view-drawer.component.scss
Labels: risk level (author): 1

#3765 chore: add GitHub Copilot instructions for Angular and commit conventions
  .github/instructions/angular.instructions.md
  .github/instructions/commit-message.instructions.md
  .gitignore
  .vscode/mcp.json
  .vscode/settings.json
Labels: risk level (author): 1

#3779 chore: add GitHub Copilot instructions for Angular and commit conventions (#3765)
  .github/instructions/angular.instructions.md
  .github/instructions/commit-message.instructions.md
  .gitignore
  .vscode/mcp.json
  .vscode/settings.json
Labels: risk level (author): 1
